### ISSUE TITLE
Are all Linux based distros compatible with Che

### ISSUE THREAD

**Issue by Mikerr1111** [eclipse/che#10072]
Looking at the documentation under 'Getting Started' I see Ubuntu and then Linux. I'm just wondering if all Linux distros are compatible for example RedHat, Debian, Arch, and OpenSUSE? If you could elaborate on the Linux distros tested and supported it would be helpful.

![che](https://user-images.githubusercontent.com/18353476/41517470-0d285e68-7270-11e8-94b3-9194620fdf43.PNG)

**Comment by eivantsov** [comment]
@Mikerr1111 yes, all Linux distros should be ok as long as you can run Docker 1.13+ there.

**Comment by Mikerr1111** [comment]
Okay, Thank You!
