### ISSUE TITLE
After login users get redirected to the dashboard although they used a link to start a workspace 

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20463]
### Describe the bug

Native authentication drops browser params (part of URL after #), so the factory is not accepted after logging.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with DevWorkspace enabled on OpenShift.
2. Try to accept factory with URL without being logged in, like $CHE_HOST#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2.
3. Check that just Dashboard is opened without workspace being created.

### Expected behavior

Workspace is created and started.

### Runtime

OpenShift

### Screenshots

![Screenshot_20210914_112306](https://user-images.githubusercontent.com/5887312/133222667-084bafbe-e1a0-48a1-a771-7dc0ba21ddc3.png)

### Installation method

chectl/next

### Environment

Linux

### Release Notes Text

With this fix users will be correctly redirected to the workspace after authentication.

**Comment by sparkoo** [comment]
Can't reproduce

https://user-images.githubusercontent.com/1160903/133246759-e250f0a9-fc2a-4ee1-a8ea-b77973975bac.mp4

**Comment by skabashnyuk** [comment]
@sparkoo looks like you are already logged in. Loggin screen is supposed to appear.  Or at least an authorization screen.

**Comment by sparkoo** [comment]
omg yes, from title I've understand it that I should be logged in

**Comment by sleshchenko** [comment]
> is it working with che-workspaces and keycloak?

yes! It should. Let me know if it does not for you
