### ISSUE TITLE
Dashboard is broken after creating a new devworkspace from the minimal devfile

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#20468]
### Describe the bug

Dashboard is broken after creating a new devworkspace from the minimal devfile.

```
schemaVersion: 2.1.0
metadata:
  name: wksp-hyuh
```

### Che version

next (development version)

### Steps to reproduce

1. Open dashboard with devWorkspaces enabled and go to custom workspace panel.
2. Create a new workspace from the devfile
```
schemaVersion: 2.1.0
metadata:
  name: wksp-skvg
```  

### Expected behavior

A new devworkspace should be created and opened.

### Runtime

minikube

### Screenshots

![Знімок екрана 2021-09-14 о 12 16 26](https://user-images.githubusercontent.com/6310786/133264406-1187ac7e-85b8-490d-bf8f-428ef2fc2ec6.png)

### Installation method

chectl/next

### Environment

macOS

### Additional context

It is happening because of our WorkspaceAdapter which is thrown an Error
```
  constructor(workspace: T) {
    if (isCheWorkspace(workspace) || isDevWorkspace(workspace)) {
      this.workspace = workspace;
    } else {
      console.error('Unexpected workspace object shape:', workspace);
      throw new Error('Unexpected workspace object shape.');
    }
  }
```
https://github.com/eclipse-che/che-dashboard/blob/main-7.37/packages/dashboard-frontend/src/services/workspace-adapter/index.ts#L53

And we have 
```
export function isDevfileV2(devfile: unknown): devfile is devfileApi.Devfile {
  return (devfile as devfileApi.Devfile).schemaVersion !== undefined
    && (devfile as devfileApi.Devfile).components !== undefined
    && isDevfileV2Metadata((devfile as devfileApi.Devfile).metadata);
}
```

https://github.com/eclipse-che/che-dashboard/blob/main-7.37/packages/dashboard-frontend/src/services/devfileApi/typeguards.ts#L21

This field 'components' is required.

In any case we should handle these kind of errors in proper way

**Comment by sleshchenko** [comment]
should be fixed by https://github.com/eclipse-che/che-dashboard/pull/347
