### ISSUE TITLE
Support for private devfile registries

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20465]
### Is your enhancement related to a problem? Please describe

It follows up the https://github.com/eclipse-che/che-dashboard/pull/333.
The user story is the one of devfile registries is behind proxy and dashboard fails to load devfile because of CORS, even though authentication cookies is set.

### Describe the solution you'd like

It's needed to extend configuration somehow to tell Dashboard that one particular registry is private and cookies are already set by someone else, so then dashboard will attach cookies to the request.

### Describe alternatives you've considered

Dashboard is told and registry is behind the same authentication mechanism that it is - like OpenShift OAuth and reach devfile registry via their backend to avoid CORS issues.

**Comment by benoitf** [comment]
if dashboard load content from its backend there should not have any CORS issue (but maybe auth issue)
