### ISSUE TITLE
Build command fails for devfilev2 sample of Java Spring Petclinic

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20464]
### Describe the bug

Build command fails for https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with devworkspaces enabled.
2. Create workspace with https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
3. Try to start build command in tools container.
4. Check that it fails.

### Expected behavior

build command works

### Runtime

OpenShift

### Screenshots

![Screenshot_20210914_114701](https://user-images.githubusercontent.com/5887312/133228231-77836811-6346-4c23-a205-c1bd1431b436.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by svor** [comment]
Seems it was fixed by https://github.com/che-samples/java-spring-petclinic/pull/
![screenshot-192 168 49 2 nip io-2021 09 20-10_39_06](https://user-images.githubusercontent.com/1271546/133969802-8c2e5e38-8d67-4388-8ed3-24530b0b1c3c.png)
3
