### ISSUE TITLE
Expose on dashboard instructions how to configure Secrets/ConfigMaps for DevWorkspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20469]
### Is your enhancement related to a problem? Please describe

Currently, DWO allows to mount any secret/configmap into devworkspaces, but there is no any clue on dashboard.

### Describe the solution you'd like

Instead of building fully functional UI on Dashboard, it's decided to move with just instruction how to do it with K8s cluster CLI.
It's STEP 1 from https://github.com/eclipse/che/issues/17954

**Comment by l0rd** [comment]
@ibuziuk this has milestone 7.39 but it hasn't been completed (because of unplanned work dashboard side I guess). I am removing the milestone since I don't think you have plans to work on it for 7.40 (not a DW milestone 3 priority).
