### ISSUE TITLE
plugin registry deployed on github.io for main branch is not updated since a couple of months

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20473]
### Describe the bug

main branch registry is deployed on https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/

but we can see on https://github.com/eclipse-che/che-plugin-registry/tree/gh-pages that main folder is not updated since a couple of months

### Che version

next (development version)

### Steps to reproduce

Go to https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/ , some plug-ins are missing

### Expected behavior

online version being updated at every commit to main branch

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by svor** [comment]
the same problem for surge.sh https://che-plugin-registry-main.surge.sh/v3/plugins/
