### ISSUE TITLE
Eclipse IDE plug-in development using Eclipse Che

### ISSUE THREAD

**Issue by source-code-10010** [eclipse/che#20478]
### Summary

Hello,

Currently, we develop our plug-ins using Eclipse IDE. As Eclipse Che provides cool features, we would like to know if it's possible to do eclipse IDE plug-in development and run workbench application in Eclipse Che. 
Thank you!

**Comment by benoitf** [comment]
Hello @source-code-10010 

there are multiple editors that you can plug into Che.
While we're defaulting with native 'web-based ide' editor, you can find community contribution to use Eclipse IDE running with a GTK export to html
 (you'll need to select 'Eclipse IDE' in the available list of editors)
