### ISSUE TITLE
devfile v2 editors plug-ins should go in editor subdirectory and not in v3/plugins folder

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20488]
### Is your task related to a problem? Please describe

In devfile v1, we had IDE plug-ins handled by the runtime.
So all plug-ins were in `v3/plugins` folder.

With devfile v2, the IDE plug-ins are no longer part of the devfile

### Describe the solution you'd like

All the IDE plug-ins for DevWorkspaces (devfile v2) described by the `che-theia-plugin.yaml` file should be stored in `/v3/che-theia/id/che-theia-plugin.yaml` path (and no longer in `/v3/plugins`)

And other IDE editors will store their plug-ins metadata in /v3/<editor-name>/ subdirectory

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by svor** [comment]
I'll take care about it when che-server engine will be disabled
