### ISSUE TITLE
main DevWorkspace Endpoint is considered as ready/available while it's not

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20481]
### Describe the bug

Dashboard redirect to the IDE page when the editor is ready
DevWorkspace operator flags the editor being as ready when the `main` endpoint is ready.

But it turns out that as now the endpoint are secured, DevWorkspace will check the main URL endpoint and it'll return for example on openshift a OAuth page. (so the answer is HTTP/200)

While the endpoint may not be listening or ready, DW is flagged as ready due to that oAuth page

so at the end, dashboard think the DevWorkspace is ready, redirects to the main URL and we get a 502/bad gateway error as the underlying component may not be ready.

### Che version

next (development version)

### Steps to reproduce

Deploy a workspace on openshift (to make it really reproducible, the editor listening port should never be started)

### Expected behavior

DevWorkspace is flagged ready only when main endpoint is really reachable (not the oAuth page)

### Runtime

OpenShift

### Screenshots

![Screenshot 2021-09-17 at 11 35 42](https://user-images.githubusercontent.com/436777/133773863-5aef5e9e-1594-4620-bf8c-83fdf93ec092.png)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by amisevsk** [comment]
Related: https://github.com/devfile/api/issues/168
