### ISSUE TITLE
Token are expiring after a while in dashboard

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20485]
### Describe the bug

After using for a while (like being authenticated since one hour) Dashboard/DevWorkspace, I've 401 unauthorized access notifications after clicking some workspaces
![image](https://user-images.githubusercontent.com/436777/133799684-72d6e52f-c2eb-427b-9546-be40bc9d4b6e.png)

### Che version

next (development version)

### Steps to reproduce

Use OpenShift (like rhpds) + devWorkspace mode

Then log in and wait 1hour, then click on workspaces menu in dashboard, you should have these 401 errors

### Expected behavior

I should not see these unauthenticated errors

### Runtime

OpenShift

### Screenshots

![Screenshot 2021-09-17 at 16 13 17](https://user-images.githubusercontent.com/436777/133800032-72094502-60f7-4641-9bed-e53709bcdfdb.png)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by skabashnyuk** [comment]
Potentially duplicate of https://github.com/eclipse/che/issues/20304
