### ISSUE TITLE
Dashboard should tell even more when fails to resolve devfile from repo

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20491]
### Describe the bug

1. Dashboard does not show details when fails to load devfile from repo.

### Che version

next (development version)

### Steps to reproduce

1. To reproduce it you need to find a way how to fail to resolve, like today's Che Server is broken and we have the following:

![Screenshot_20210920_160154](https://user-images.githubusercontent.com/5887312/134007173-3e253a80-c9fb-4749-8461-aaac317769e7.png)

![Screenshot_20210920_152721](https://user-images.githubusercontent.com/5887312/134007628-7c051042-8db5-4920-8adf-2b790dfc23e0.png)

### Expected behavior

The server's message is shown to end user

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by akurinnoy** [comment]
This issue has been already fixed. 

<details>
<summary>Screencast</summary>

https://user-images.githubusercontent.com/16220722/157867989-53f1edba-d825-4394-8a93-f0f1ad63cf26.mov

</details>
