### ISSUE TITLE
Cannot expand left panel if a direct link to a workspace is using

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse/che#20494]
### Describe the bug

Prehistory of my case:

> it is related to https://github.com/eclipse-theia/theia/discussions/8292. 
But because `workspace-loader` was replaced with `che-dashboard` this question became actual again.
I need to share a link to a specific file(with line and column) in workspace. The problem was solved with a custom plugin that reads query parameters and uses Theia API to open files. The base of the solution was the ability to pass query parameters to the plugin.  It was possible with URIs like `/workspace-loader/lego/temp-prj?f=/projects/22.txt&l=61&c=421&uid=42`

But now there is no `workspace-loader` and I use [link from workspace dto](https://github.com/eclipse-che/che-dashboard/blob/7.34.1/packages/dashboard-frontend/src/services/workspaceAdapter/index.ts#L171). This works as well as earlier, except expanding left panel. 

Exactly the problem is in the link that client side got from server via `/services`
I expect link is https://che-namespace.k8s.managed.cloud/dashboard/#/ide/admin/temp-prj. But link is: `http://che-host.namespace.svc:8080/dashboard/#/ide/admin/temp-prj`

### Che version

7.34

### Steps to reproduce

* https://server8wkx32v7-jwtproxy-server-4402.k8s.managed.cloud/#/projects
* Press "Expand navigation bar" button
* AR: Opened link http://che-host.namespace.svc:8080/dashboard/#/ide/admin/temp-prj
![7_34 gif](https://user-images.githubusercontent.com/2270831/134145222-027b334b-d752-4dd3-b59b-ee3a3579de18.gif)

### Expected behavior

As in 7.15
* https://server71ljacf3-jwtproxy-server-4402.k8s.managed.cloud/#/projects
* Press "Expand navigation bar" button
* Opened link https://che-namespace.k8s.managed.cloud/dashboard/#/ide/admin/temp-prj
![7_15 gif](https://user-images.githubusercontent.com/2270831/134145233-95d57420-1b31-441c-b189-a17247c3e579.gif)

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by azatsarynnyy** [comment]
When clicking on `show-navbar` button, Che-Theia [sends a message](https://github.com/eclipse-che/che-theia/blob/f85127cc2f697967338c786ac0edd5e0608a9376/extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts#L77) to the dashboard.
I suppose this behavior has been changed in the new dashboard.
@sleshchenko could someone from your team look at this?

**Comment by sleshchenko** [comment]
@azatsarynnyy according to the shared context, I think it's the theia bug and it uses internal CHE URL (CHE_INTERNAL_URL) but should use public (CHE_URL).
Possible related PR https://github.com/eclipse-che/che-theia/pull/1161

**Comment by azatsarynnyy** [comment]
I believe there's not much sense to work on that issue for us. Considering [there's no IDE IFRAME in the Dashboard](https://github.com/eclipse-che/che-dashboard/pull/377) anymore.
