### ISSUE TITLE
Bitbucket PAT-based authentication does not works w/out configured OAuth

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse/che#20499]
### Describe the bug

Due to specific token validation procedure, bitbucket PAT-based authentication does not works w/out configured OAuth.

### Che version

next (development version)

### Steps to reproduce

1. Setup Che and Bitbucket (or use existing instance)
2. Create PAT on BB side
3. Create secret in Che with PAT and configure server URL
4. Accept private project factory. There is 500 failure on dashboard.

### Expected behavior

Accept is succeed - workspace created.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by skabashnyuk** [comment]
The general recommendation is to use OAuth for private repositories access.
