### ISSUE TITLE
How to specify the file to be opened (URL API or the way keeping query parameters upto Theia Plugin). 

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse/che#20495]
### Summary

Hello, my question is related to https://github.com/eclipse-theia/theia/discussions/8292. 
But because `workspace-loader` was replaced with `che-dashboard` this question became actual again.
I need to share a link to a specific file(with line and column) in a workspace. The problem was solved with a custom plugin that reads query parameters and uses Theia API to open files. The base of the solution was the ability to pass query parameters to the plugin. It was possible with URIs like /workspace-loader/lego/temp-prj?f=/projects/22.txt&l=61&c=421&uid=42

But now there is no `workspace-loader` and I use [link from workspace dto](https://github.com/eclipse-che/che-dashboard/blob/7.34.1/packages/dashboard-frontend/src/services/workspaceAdapter/index.ts#L171),  for example, `https://server8wkx32v7-jwtproxy-server-4402.k8s.managed.cloud/#/projects?f=/projects/22.txt&l=61&c=421&uid=42`. It works as well as earlier, except expanding left panel (see #20494). 

Does any better approach exist to open files via URL API?  Or maybe somebody knows how to get query parameters in a custom plugin without using links to `jwtproxy`, ideally with the usage of link in the context of workspace?

**Comment by azatsarynnyy** [comment]
cc @sleshchenko

**Comment by sleshchenko** [comment]
> But now there is no workspace-loader and I use link from workspace dto, for example, https://server8wkx32v7-jwtproxy-server-4402.k8s.managed.cloud/#/projects?f=/projects/22.txt&l=61&c=421&uid=42. It works as well as earlier, except expanding left panel (see #20494).

This way is good enough.
Also, we can guide how to pass params from dashboard in case like 
```
${che_host}/dashboard/#/ide/opentlc-mgr-che/spring-petclinic-pv2s${params-here-in-some-format}
```
or just drop feature request but not any promise when it can be done.

I wonder if you share the same account with the user you share link?

**Comment by gorshkov-leonid** [comment]
@sleshchenko thank you
> Also, we can guide how to pass params from dashboard in case like
It would be great!

> I wonder if you share the same account with the user you share link?
Actually, the link is not shared in general meaning. To be exact, an external system retrieves and shows this link navigating to cloud IDE.  This system uses the same token from keycloak as Che.
