### ISSUE TITLE
Add a factory link parameter to specify the editor

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20508]
### Is your enhancement related to a problem? Please describe

Today, with DevWorkspaces, when selecting a default stack we can't select another editor than the default one.

As we've more and more editors and project is being cloned, we may want to have to select the IDE that we want as the default one.

### Describe the solution you'd like

In user preferences page, be able to have a list of available editors and be able to choose the one that we want.

Then when opening the getting started examples, this editor will be pickup.

I don't know if we can provide through factory the editor that we may want as well ?
like http://che-server#https://github.com/eclipse/che&editor=che-theia

### Describe alternatives you've considered

Small icons on every tiles of the Getting Started stacks (one for each available editor)

### Additional context

Maybe when we connect the first time on Dashboard we should be prompted to configure the editor that we want.

Or connect to github to get token.

### Release Notes Text

A user can specify a particular editor to use as a factory link parameter. For example, to use Che-Theia, http://che-server#https://github.com/eclipse/che&editor=che-theia.

**Comment by max-cx** [comment]
@benoitf Is there any new docs content that we need to add to the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by max-cx** [comment]
@benoitf, I updated the Release Notes Text for this issue:

----

= Selecting an editor by using a factory link parameter

With this update, users can specify their choices of an editor as a factory link parameter. For example, {prod-url}#__<repository-url>__&editor=che&#45;theia is to select Che-Theia.

----

Feel free to okay, comment, or correct it in https://issues.redhat.com/browse/CRW-2372.
Thanks!
