### ISSUE TITLE
Improve logging of cluster state in Che Operator CI tests

### ISSUE THREAD

**Issue by metlos** [eclipse/che#20504]
### Is your enhancement related to a problem? Please describe

Currently, when there is a CI test failure, the scripts collect a selection of logs from various pods and containers, together with logs saved by `chectl`. Importantly, we may miss some logs in certain configurations. It would be easier to just collect logs from all containers of all pods in all affected namespaces unconditionally so that we don't miss anything.

### Describe the solution you'd like

We can take inspiration from DWO: https://github.com/devfile/devworkspace-operator/blob/main/.ci/common.sh#L18

**Comment by mmorhun** [comment]
Done
