### ISSUE TITLE
Include VS Code editor in che plugin registry

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20505]
### Is your task related to a problem? Please describe

In order to use more easily the editor it should be added into he plug-in registry

### Describe the solution you'd like

Add devfile.yaml to use this editor

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by wcho** [comment]
Do you mean [code-server](https://github.com/cdr/code-server)?

**Comment by benoitf** [comment]
@wcho: https://github.com/che-incubator/che-code

**Comment by benoitf** [comment]
added by https://github.com/eclipse-che/che-plugin-registry/pull/1093
