### ISSUE TITLE
Extend troubleshooting guide with self-signed certificate use case

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20518]
### Is your task related to a problem? Please describe

Several times reported that Bitbucket integration failed. The common reason was that self-signed certificates were imported incorrectly see more https://github.com/eclipse/che/issues/20335 . 

### Describe the solution you'd like

We need to extend the troubleshooting guide describing this use-case.

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-3334
