### ISSUE TITLE
Maximize editors when opening a workspace

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20521]
### Is your enhancement related to a problem? Please describe

Today, when opening a workspace some editors like che-theia editor has some chevron to hide dashboard top menu bar.

It could be nice if there was something common on all editors or if Dashboard could provide this feature on all editors (top left  top right corner)

### Describe the solution you'd like

1. at least, when a workspace is opened (and the IDE is there) we should maximize the window of the editor

2. Optional: maybe have some common UI to show again the dashboard

### Describe alternatives you've considered

It would be nice if something is handled on dashboard so it can work with any editors.
But if there is no agreement/ bad UX then we could enhance every editor or just let the maximized window

**Comment by l0rd** [comment]
If https://github.com/eclipse/che/issues/20523 implementation is simple I would rather close this one.
