### ISSUE TITLE
Remove iframe of the editor in dashboard

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20523]
### Is your enhancement related to a problem? Please describe

When opening editors we have sidebar of the dashboard and the sidebar of the editor

Then, from UX, it's hard to know which sidebar do what.
Also we need to add some specific buttons (chevron in che-theia) inside the editors to collapse the dashboard sidebar

### Describe the solution you'd like

Opening a editor (like clicking a getting started) should open a new window and not embed it inside an iframe

The workspaces running should be seen in a different view than with a sidebar inside dashboard

### Describe alternatives you've considered

Rework iframe with some common UI to hide/show but it may still not look a correct UX/UI with the multiple sidebars

**Comment by wcho** [comment]
I think it's also good for IntelliJ IDEs.

**Comment by benoitf** [comment]
iFrame is removed when devWorkspace engine is enabled
