### ISSUE TITLE
Memory limit/Memory request for traefik that is running as a part of workspace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20520]
### Is your task related to a problem? Please describe

In this issue https://github.com/eclipse/che/issues/20190 we introduce traefik as a part of workspace pod to secure services. Now memory limit/request is not set and used the system default 

### Describe the solution you'd like

Set reasonable memory limit/Memory request for traefik that is running as a part of the workspace

**Comment by sparkoo** [comment]
here's the traefik podaddition https://github.com/eclipse-che/che-operator/blob/main/controllers/devworkspace/solver/che_routing.go#L162 I've also noticed there is `ImagePullPolicy: corev1.PullAlways`, which does not make much sense so imho we should change it as well

**Comment by sparkoo** [comment]
should we also set CPU L/R?

**Comment by benoitf** [comment]
yes for CPU limit/request

**Comment by mshaposhnik** [comment]
so what's the proposal? 64 / 256 Mb on RAM and 0.05 / 0.5 CPU?

**Comment by sparkoo** [comment]
> so what's the proposal? 64 / 256 Mb on RAM and 0.05 / 0.5 CPU? Enough?

seems reasonable to me
