### ISSUE TITLE
Configurable resource limits for devworkspaces

### ISSUE THREAD

**Issue by metlos** [eclipse/che#20527]
### Is your enhancement related to a problem? Please describe

Currently, the devworkspace-operator (DWO) sets the default CPU and memory limit unconditionally to a certain value (64M/128M for memory request/limit and no defaults for CPU, leaving them to the cluster defaults).

Che server can be configured with custom default memory and cpu requests/limits.

### Describe the solution you'd like

We should enable this functionality also for the devworkspaces. This would probably be implemented as a new property in `CheCluster` custom resource (both `v1` and `v2alpha1`).

**Comment by l0rd** [comment]
For clarity: you are talking about the cpu/mem limits/requests of workspaces containers or about those of the operator controller?

**Comment by l0rd** [comment]
Note that:

- users are able and encouraged to specify cpu/mem limits/requests for the components in their devfiles. Doing that for them is a source of errors and eventually non starting workspaces.
- an admin can always set the default cpu/mem limits of the workspace containers configuring namespaces `LimitRange`

That said I think that this issue should consist in making sure that:

- cpu/mem limits/requests of **all** our plugins/editors should be explicitly specified in the plugin registry
- cpu/mem limits/requests of **all** our samples components should be explicitly specified in the corresponding devfiles
- there are containers that a user doesn't control (workspaces traefik, init containers, ...): for those containers only we should have `CheCluster` fields to make the values configurable.
