### ISSUE TITLE
Support custom certificates for git hosts for devworkspaces

### ISSUE THREAD

**Issue by metlos** [eclipse/che#20528]
### Is your enhancement related to a problem? Please describe

Che server supports custom certificates for the git servers that it uses to create the `gitconfig` file in the workspace pod. This feature seems to be missing in `devworkspace-operator`.

### Describe the solution you'd like

Che server currently supports only a single custom git credentials, while DWO supports multiple. Therefore we need to be careful and design this differently in DWO.

### Additional context

https://github.com/eclipse-che/che-server/blob/d1c3570fca85807edb4528fce2f346a23ee66d35/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisioner.java#L206

https://github.com/devfile/devworkspace-operator/issues/613

**Comment by sleshchenko** [comment]
Note that DWO has mechanism for generating gitconfig that currently taking into account only git credentials with personal access tokens https://github.com/devfile/devworkspace-operator/pull/564

**Comment by l0rd** [comment]
This is the `CheCluster` side issue of https://github.com/devfile/devworkspace-operator/issues/613. An admin should be able to specify custom certificates for git hosts in the CheCluster CR.

**Comment by l0rd** [comment]
@metlos @skabashnyuk is someone working on this?

**Comment by skabashnyuk** [comment]
No

**Comment by gazarenkov** [comment]
Should it be fixed by https://github.com/devfile/devworkspace-operator/issues/613 ?

**Comment by metlos** [comment]
To use `CheCluster` CR for configuring DevWorkspaces, we first need support for this feature in DWO. Once DWO can use the certificates in gitconfig, we can then update our `usernamespace` controller that transforms the configuration in `CheCluster` CR into configuration within the user's namespace where it can be picked up by DWO.

Updating the `usernamespace` controller should not be hard, but we first need to know what "format" DWO will use for this. The names of labels used, etc.
