### ISSUE TITLE
Factory workflow loader

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20522]
### Is your enhancement related to a problem? Please describe

When loading a project through factory workflow I expect to see a loader of my workspace but not be inside dashboard view where I can do other stuff during the startup

### Describe the solution you'd like

When I click on a link to open a project using factory link, I expect to see progress/logs, etc but not be inside full dashboard where I can for example go into my profile, switch to other workspaces or even create new workspaces during this loading sequence.

### Describe alternatives you've considered

I may not enter into dashboard as well, I expect to see a minimal loading page that disappear when the IDE is loaded.

**Comment by sleshchenko** [comment]
I'm more or less support opening IDE in a separate frame, but I still see the sense in workspace loading page as part of dashboard.

> I may not enter into dashboard as well, I expect to see a minimal loading page that disappear when the IDE is loaded.

It's what we had previously called Workspace Loader =)

**Comment by benoitf** [comment]
implemented within https://github.com/eclipse-che/che-dashboard/pull/377
