### ISSUE TITLE
Include debug into devworkspace happy path test

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20537]
### Is your task related to a problem? Please describe

Debug is not included into happy path test

### Describe the solution you'd like

Include debug into devworkspace happy path test. it includes
Display source code changes in the running application, Validation of debug functionality
More see https://github.com/eclipse/che/issues/20385#issuecomment-924646468.

### Additional context

Depends on https://github.com/eclipse/che/issues/20536

**Comment by ibuziuk** [comment]
@musienko-maxim could you please clarify the status of the issue? should we move it to the next sprint?

**Comment by musienko-maxim** [comment]
It was included in the PR: https://github.com/eclipse/che/pull/20948
