### ISSUE TITLE
Needed images to deploy Eclipse Che in disconnected environment

### ISSUE THREAD

**Issue by michelecurioni** [eclipse/che#20539]
### Summary

Hi all,
we would like to run eclipse che in an airgapped environment, but it's not clear what images need to be available in the local registry for the operator to function.
Is there a way to get a list of all the images for a specific version of the operator?
Also, it would be useful to call out any platform dependencies for a specific version. 
This page talks about 7.36.x (https://www.eclipse.org/che/docs/che-7/installation-guide/supported-platforms/), is there a way to get similar information from the operator release notes.

Thanks,
Michele

**Comment by tolusha** [comment]
Hi @michelecurioni 
The list of images does not depend on the specific platform.
We have a doc [1] and script [2] to test Eclipse Che operator in a restricted environment.

[1] https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/
[2] https://github.com/eclipse-che/che-operator/blob/main/.ci/oci-disconnected.sh#L56

**Comment by michelecurioni** [comment]
Hi @tolusha, 
I looked at [1], and I can see a list of required images here: https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/#preparing-a-private-registry_che, but that list doesn't specify which version of those images need to be downloaded. I imagine a specific version of the operator will require specific version of those images.
Are those the only ones required for a successful installation?
It would be useful to have a way to list exactly what images the operator will need otherwise when deployed to the airgapped environment it will fail.

Thanks,
Michele

**Comment by tolusha** [comment]
That's a good question. It seems the doc is not full.
So, the complete list of images and their tags can be extracted from che-operator deployment + you need the operator image itself [1]

[1] https://github.com/eclipse-che/che-operator/blob/7.36.2/config/manager/manager.yaml#L60-L95

**Comment by michelecurioni** [comment]
That's what I was looking for, thanks.
Could you create a feature request to expose that list via command or store it in a file?
It's a bit hidden away, and I'd like to automate the download of everything required by the operator so that I can transfer it all to the airgapped environment in one archive.

There are also other images referred to in that yaml, like RELATED_IMAGE_che_plugin_sidecar_plugin_registry_image_...
Are those optional?
How do I know which ones are optional, and which ones are required?

Thanks,
Michele

**Comment by tolusha** [comment]
Regarding plugin & devfile registries images. You don't need to mirror them all but the only ones needed for your case.

1. build offline plugin & devfile registries following the doc [1]
2. check all external images
 `docker run -ti <DEVFILE_REGISTRY_IMAGE> cat /usr/local/apache2/htdocs/devfiles/external_images.txt`
 `docker run -ti <PLUGIN_REGISTRY_IMAGE> cat /usr/local/apache2/htdocs/v3/external_images.txt`
3. Mirror ones for you devfile & plugins
 
 [1] https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/

**Comment by tolusha** [comment]
Closed in favor of https://github.com/eclipse-che/che/issues/21646
