### ISSUE TITLE
Use image pull secrets stored as credentials in user preferences of Che-server in DevWorkspaces

### ISSUE THREAD

**Issue by metlos** [eclipse/che#20534]
### Is your enhancement related to a problem? Please describe

Che-server supports storing docker config json in `dockerCredentials` user preference. It is then able to create secret with this configuration and mount it as a image pull secret of workspace pods.

Devworkspace operator is able to mount labeled secrets as image pull secrets of the workspace pod.

### Describe the solution you'd like

Che server should synchronize the docker config stored in user prefs as a secret in the user's namespace with the correct labels so that it is picked up by DWO.

**Comment by l0rd** [comment]
As mentioned yesterday this issue should not be addressed on che-server side because the credentials are per user and should not be managed by the che-sever. It's something that should be changed at dashboard side and part of https://github.com/eclipse/che/issues/17954
