### ISSUE TITLE
Align Che-Theia with the upstream breaking changes (rework build system)

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#20538]
### Is your task related to a problem? Please describe

The changes related to [reworking build system](https://github.com/eclipse-theia/theia/pull/9710/files) were merged in the upstream recently.
Che-theia was broken due to those changes.
So, we should provide some adaptation on `che-theia` side.

### Describe the solution you'd like

Provide some adaptation on the `che-theia` side for [reworking build system](https://github.com/eclipse-theia/theia/pull/9710/files) changes.

**Comment by RomanNikitenko** [comment]
A new breaking changes were merged in the upstream recently

<img width="1170" alt="Screenshot 2021-11-01 at 18 04 15" src="https://user-images.githubusercontent.com/5676062/139702790-162f6617-db83-4af9-bd39-7d4cb3e55da3.png">

The `Happy tests` [passed successfully](https://github.com/eclipse-che/che-theia/pull/1238#issuecomment-953916358) for my draft PR before merging those changes in the upstream.
Now [it's failing](https://github.com/eclipse-che/che-theia/pull/1238#issuecomment-956358443)

**Comment by azatsarynnyy** [comment]
Let's pin to the commit before the new breakings, with applying your fixes for Che-Theia.
And file an issue for another new breakage.

**Comment by RomanNikitenko** [comment]
Unfortunately, I faced with a new problem. It's related to `jest` and `ts-jest` dependencies, we use for tests in `che-theia`. 
Some info about the problem:
- there are [some rules](https://github.com/eclipse-theia/theia/blob/23e09c2df53e6b8c57ea14c1baf2ffbaa6555408/configs/base.tsconfig.json#L9) in `tsconfig` of `theia` 
- the rules are NOT applied for tests
- you can see it [here](https://github.com/eclipse-theia/theia/blob/bb5a4366f5abac1e44df53d2ad961027d2ae0316/packages/core/src/browser/tree/tree-iterator.spec.ts#L137), for example  
- but if we add `ts-jest` as dev dependency (even to vanilla `theia`) - those rules from `tsconfig` are applied to tests
- it happens on compilation step, not running tests step
- as result - we have compilation errors like
![Screenshot 2021-11-12 at 12 46 58](https://user-images.githubusercontent.com/5676062/141454818-8bc79eb4-49b9-4229-8349-8a64fed4c4c9.png)

So, `theia`  doesn't have such errors due to it doesn't have `ts-jest` dependency, adding the dependency leads to the same problems
 
About che-theia
- our extensions depend on `theia`, `core` package, for example
- with new `theia` build system our extensions have those dependencies in `tsconfig` like:
```
"references": [
    {
      "path": "../../../../packages/core"
    }
  ]
```
 - so, at compilation step `tsc` see that an extension depends on the `core` module, goes to `core` module and builds it
- `che-theia` has the `ts-jest` as a dependency - so the rules from `tsconfig` are applied and we get compilation errors 

I see that it's possible to provide a configuration for `ts-jest` in package.json file.
I thought that we could add `exclude` (check `che-theia`  tests but do NOT check `theia` tests) or something else to the configuration to avoid our current problems. I played with it and it looks like the configuration is applied on the running `jest` step, but there is no influence on compilation step...

I'm continue to search a true way to fix it, but if someone has an idea, please let me know...

**Comment by RomanNikitenko** [comment]
I discussed with Florent the problem which I described above. 
He was able to reproduce it as well for vanilla `theia` and investigated it.
The problem should be fixed by an upgrade versions for `ts-jest` and `jest`.
I tried this way for `theia` and it worked well, so thank you, Florent, very much for your help!

About `che-theia` - I have got some errors after upgrade those versions, so working on adaptation...

**Comment by RomanNikitenko** [comment]
I applied new versions `ts-jest`,`jest` and `@types/jest` for `che-theia` extensions and plugins, also I provided some adaptation for tests.
It works well for building `che-theia`, but it fails on CI jobs and at building images with errors which I provided on the screenshot [here](https://github.com/eclipse/che/issues/20538#issuecomment-967007208).

Continue to work on that problem...

**Comment by tsmaeder** [comment]
Sorry if I sound like a broken record, but switching to linkless build everywhere for che-theia would make us independent of how theia is built. There is already a next PR in Theia that will turn on strict checking on the typescript compiler. If we built theia and che-theia separately, most of the recent changes would have been non-issues :shrug: We just need to bite the bullet and finally switch.

**Comment by RomanNikitenko** [comment]
@tsmaeder 

Thank you, Thomas, for the idea. I think we could avoid problems which I described above using `linkless` build.
Unfortunately, the `linkless` build is broken even for the `latest` of the `che-theia`, so it's NOT related to our current problems with build system.
I created a separate issue for that problem https://github.com/eclipse/che/issues/20814

**Comment by RomanNikitenko** [comment]
Update: 
I have got a new problem related to dependencies:

<img width="1487" alt="Screenshot 2021-11-26 at 11 35 34" src="https://user-images.githubusercontent.com/5676062/143559359-be7621b7-8d07-4ac1-91ec-dec516dab3cc.png">

Note: 
- after my last pushing changes to the PR (8 days ago) - the `Happy Path` tests were happy, CI Docker build was successful and so on
- yesterday I started to reproduce the problem locally on my machine
- I restarted jobs for the PR (without any changes to the PR) - I have got the same errors for the jobs
- so, starting from yesterday, the problem is reproduced on my PR without any additional changes (my last commit to the PR was 8 days ago)

<img width="948" alt="Screenshot 2021-11-26 at 11 47 27" src="https://user-images.githubusercontent.com/5676062/143561036-a59e117f-384f-4762-8629-3789e4ec4cfc.png">

Looking for the cause of the problem....

**Comment by benoitf** [comment]
maybe you could try to add `acorn-import-assertions` into https://github.com/eclipse-che/che-theia/blob/8a48c2fbd803e0c37548cd4720cdd7282a13b3a6/generator/src/production.ts#L33

**Comment by RomanNikitenko** [comment]
I still don't see what caused the problem, but I applied [the workaround](https://github.com/eclipse/che/issues/20538#issuecomment-979873113) and it fixed build for my PR.

Thanks, Florent!
