### ISSUE TITLE
List Che 3rd party runtime dependencies

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20543]
### Is your task related to a problem? Please describe

Eclipse Che is [under review](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/66) and one of the artifact required is the list of 3rd party dependencies.

### Describe the solution you'd like

Provide, [using this gdoc](https://docs.google.com/document/d/1DTLpciY6sgZ-U53wdvK-B1dIg8b5rHn7YR8V_YuEIDA/edit#), the list of libraries used at runtime by the following che components:

- [x] [che-operator](https://github.com/eclipse-che/che-operator) @tolusha 
  - https://github.com/eclipse-che/che-operator/blob/main/DEPENDENCIES.md
- [x] [che-machine-exec](https://github.com/eclipse-che/che-machine-exec) @tolusha 
  - https://github.com/eclipse-che/che-machine-exec/blob/main/DEPENDENCIES.md
- [x] [che-server](https://github.com/eclipse-che/che-server) @skabashnyuk  https://github.com/eclipse-che/che-server/blob/main/assembly/assembly-wsmaster-war/.deps/prod.md
- [x] [che-jwtproxy](https://github.com/eclipse/che-jwtproxy) @skabashnyuk  https://github.com/eclipse/che-jwtproxy/blob/main/DEPENDENCIES.md
- [x] [che-theia](https://github.com/eclipse-che/che-theia) @azatsarynnyy 
- [x] [che-dashboard](https://github.com/eclipse-che/che-dashboard) @sleshchenko
  - https://github.com/eclipse-che/che-dashboard/blob/main/.deps/prod.md
- [x] [che-workspace-client](https://github.com/eclipse-che/che-workspace-client) @sleshchenko
  - https://github.com/eclipse-che/che-workspace-client/blob/main/.deps/prod.md
- [x] ~~[che-workspace-loader](https://github.com/eclipse/che-workspace-loader) @sleshchenko~~ is archived already
- [x] [che-plugin-broker](https://github.com/eclipse/che-plugin-broker) @sleshchenko 
  - See GDoc aboce
- [x] [che-plugin-registry](https://github.com/eclipse-che/che-plugin-registry) @svor 
- [x] [che-devfile-registry](https://github.com/eclipse-che/che-devfile-registry) @svor

**Comment by sleshchenko** [comment]
Provided info about Controller's team components and dropped our areas. Let me know if anything else is needed.

**Comment by svor** [comment]
It seems we don't have runtime dependencies in che-plugin-registry and che-devfile-registry components
