### ISSUE TITLE
'JavaMaven' test is fail on 'Che-nightly' launch via absent the notification 'Do you trust the authors of'

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#20548]
### Describe the bug

* The 'JavaMaven' E2E test is failed on 'Che-nightly' launch job, e.g. https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/802/

### Che version

next (development version)

### Steps to reproduce

* There is waiting the appearing the notification with text: "Do you trust the authors of", but in fact it doesn't present.

### Expected behavior

* The test should passed

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs
```
TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[@class='theia-notification-message']/span[contains(.,'Do you trust the authors of')])' element, timeouted after 60000
```

https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/791/console

**Comment by dmytro-ndp** [comment]
Fixed: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/804/
