### ISSUE TITLE
Can't start any devworkspace

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20545]
### Describe the bug

I can't start any workspace when using DevWorkspaces.

Workspace log from the Dashboard:
```
Initializing DevWorkspace

Preparing networking

Preparing services

Networking ready

Waiting for DevWorkspace ServiceAccount

Error provisioning storage: Could not rewrite container volume mounts: volume component 'plugins' is defined multiple times
```

### Che version

next (development version)

### Steps to reproduce

1. `chectl server:deploy --platform=openshift --workspace-engine=dev-workspace`
2. login and try start any workspace from samples

### Expected behavior

Workspace will start

### Runtime

OpenShift

### Screenshots

![20210927_144729_1635x373_scrot](https://user-images.githubusercontent.com/1160903/134910887-0d24d4dc-e3aa-4dd1-b0ba-58711622df04.png)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

### Additional context

env: RHPDS

**Comment by amisevsk** [comment]
Issue appears to be due to https://github.com/devfile/devworkspace-operator/issues/586, which is fixed in https://github.com/devfile/devworkspace-operator/pull/593 but currently only available in `next`.

**Comment by sleshchenko** [comment]
Well, but spring samples used to work just fine, even before https://github.com/devfile/devworkspace-operator/pull/593 but I missed something

**Comment by vzhukovs** [comment]
Will take a look

**Comment by sparkoo** [comment]
workaround is to use older plugin-registry:
```
spec:
  server:
    pluginRegistryImage: quay.io/eclipse/che-plugin-registry:7.36.2
```
