### ISSUE TITLE
Introduce a new operator-based Helm chart and publish it on ArtifactHub. Remove chectl helm installer.

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20552]
### Is your task related to a problem? Please describe

Current helmcharts [1] that are using to deploy Eclipse Che are deprecated 
We have to replace them on ones to deploy che-operator.

[1] https://github.com/eclipse-che/che-server/tree/main/deploy

### Describe the solution you'd like

- [x] remove `--installer helm` from chectl options
- [x] update doc not to mention `helm` anymore
- [x] Introduce helmcharts to deploy che-operator
- [x] publish the new chart to https://artifacthub.io/ and setup a gh action to automatically release a new version of the chart at every che release

### Additional context

https://github.com/eclipse/che/issues/20178

### Release Notes Text

The old Helm chart has been replaced with a new one that reuse Che Kubernetes operator to deploy Che. The new Chart has been published on [ArtifactHub](https://artifacthub.io/packages/helm/eclipse-che/eclipse-che). We have removed the helm chart installer in `chectl`: to install the new Chart users are required to use `helm` command line tool.

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-3313

**Comment by tolusha** [comment]
Helm Charts are available at https://artifacthub.io/packages/helm/eclipse-che/eclipse-che

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2552
