### ISSUE TITLE
Programmatically get the preview URL generated after starting an app

### ISSUE THREAD

**Issue by nupurnegi** [eclipse/che#20566]
### Summary

As soon as we start an app in eclipse che, a URL is generated which opens up in the preview tab. Is there a way to programmatically get/find that URL. Or is there an environment variable where it is stored.

Below is a React app running on localhost:3000 and preview tab is opening it up via another URL. I want to get that URL programmatically.
<img width="1208" alt="Che-theia" src="https://user-images.githubusercontent.com/35726589/135595378-ff892dd8-6af4-4c00-b0ac-21f66d8f3aef.png">

**Comment by sleshchenko** [comment]
I don't think there is a way to get that Theia port forward URL, but you should be able to define endpoint with the corresponding port on your container component with devfile and then get the URL with help of Che Server API. You can play with it with swagger. Note token is needed and it should be available as MACHINE_TOKEN as var.
Swagger is at `CHE_HOST/swagger/#!/workspace/getByKey`
key is namespace/name but this combination does not work through swagger.
or workspaceId, which you can get with help of `swagger/#!/workspace/getWorkspaces` or I believe it should be available as env var, like `WORKSPACE_ID` or `CHE_WORKSPACE_ID`.

Closing issue assuming that answer above is complete enough.
@benoitf @azatsarynnyy maybe you have other ideas on how it can be achieved in an easier way.

@nupurnegi but feel free to reopen issue or drop another one if you still have problems with that.
