### ISSUE TITLE
Devfile field in Dashboard Custom Workspace page should be validated

### ISSUE THREAD

**Issue by svor** [eclipse/che#20561]
### Describe the bug

Dashboard Custom Workspace page view has a field where we can specify a devfile and the title of this field contains star, which means that the field must be set. But even if all fields are empty Create & Open button is active. 

### Che version

7.37@latest

### Steps to reproduce

1. Go to the Custom Workspace page in the dashboard
2. Delete default devfile
3. See that Create & Open button is still active 

### Expected behavior

Create & Open button should be disabled if devfile wasn't specified

### Runtime

minikube

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 09 30-18_14_52](https://user-images.githubusercontent.com/1271546/135483441-0ba7de51-57c8-4525-a6f2-ddebd4d33a7b.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by akurinnoy** [comment]
I'm closing this issue because the Custom Workspace tab is not available to users anymore.
