### ISSUE TITLE
Dashboard Custom Workspace page has different styles of the components

### ISSUE THREAD

**Issue by svor** [eclipse/che#20560]
### Describe the bug

Dashboard Custom Workspace page we see 4 attributes: Namspace, Worksapce Name, Storage Type and Devfile. The style of Devfile should be fixed to make it similar to others. 

### Che version

7.37@latest

### Steps to reproduce

Go to the Custom Workspace page in the dashboard

### Expected behavior

All fields should have the same style

### Runtime

minikube

### Screenshots

![screenshot-192 168 49 2 nip io-2021 09 30-18_03_37](https://user-images.githubusercontent.com/1271546/135481236-601b135e-d463-42a6-94a9-1c2d107945cb.png)

### Installation method

chectl/latest

### Environment

Linux

**Comment by akurinnoy** [comment]
I'm closing this issue because the Custom Workspace tab is not available to users anymore.
