### ISSUE TITLE
Failed to request factory resolver: There is an error happened when communicate with SCM server. Error message: Unexpected status code 401

### ISSUE THREAD

**Issue by mtsmfm** [eclipse/che#20572]
### Describe the bug

After revoking OAuth, we can't create workspace for private repo with Import from Git because Che uses old (invalid) token.

### Che version

7.36

### Steps to reproduce

1. Install Che
2. Setup GitHub OAuth
3. Input private repo URL on Import from Git form
4. Click Create & Open
5. Revoke OAuth
![スクリーンショット 2021-10-02 181313](https://user-images.githubusercontent.com/1796864/135710529-30899563-a729-4cec-983f-0ace58312485.png)
6. Logout
7. Login
8. Input private repo URL on Import from Git form
9. Click Create & Open

### Expected behavior

Create workspace successfully

### Runtime

Docker Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/1796864/135710385-d90490b5-9b3e-4896-864b-ce5f479dffe7.png)

### Installation method

chectl/latest

### Environment

Windows

**Comment by skabashnyuk** [comment]
Duplicated https://github.com/eclipse/che/issues/21014  fixed in https://github.com/eclipse-che/che-server/pull/243
