### ISSUE TITLE
Document the setup needed for syncing Che settings to devworkspace namespaces

### ISSUE THREAD

**Issue by metlos** [eclipse/che#20582]
### Is your enhancement related to a problem? Please describe

We're recently introduced the ability to sync certain options from `CheCluster` CR to user namespaces in a way consumable by devworkspaces (https://github.com/eclipse-che/che-operator/pull/1027).

https://issues.redhat.com/browse/RHDEVDOCS-3364 

This is currently not documented.

### Describe the solution you'd like

Document the way a namespace is labeled as containing devworkspaces and what and how is synchronized.

**Comment by skabashnyuk** [comment]
@metlos from your pov, is this admin or user guide or something else?

**Comment by metlos** [comment]
This would IMHO fit in an admin guide because users usually don't have the ability to label namespaces.
