### ISSUE TITLE
Unable to execute 'checluster' related commands

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [eclipse/che#20589]
### Describe the bug

Unable execute any commands related to "checluster"

### Che version

7.36

### Steps to reproduce

Followed this to create in local, MAC
chectl server:deploy --platform=docker-desktop --installer=helm
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/

![image](https://user-images.githubusercontent.com/64516009/136061505-e44c4f63-a97b-422b-a9bc-6c05d7aff67b.png)
![Screenshot 2021-10-05 at 9 38 02 PM](https://user-images.githubusercontent.com/64516009/136061605-0436779b-c540-4052-925e-e2ae45074738.png)

### Expected behavior

Those command should be executed without error.

### Runtime

Docker Desktop

### Installation method

chectl/latest
chectl server:deploy --platform=docker-desktop --installer=helm

### Environment

macOS

### Eclipse Che Logs

```shell
Eclipse Che logs will be available in '/var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1633450381960'
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ Verify if namespace 'eclipse-che' exists
  ✔ Read Operator logs...done
  ✔ Read Eclipse Che Server logs...done
  ✔ Read PostgreSQL logs...done
  ✔ Read Keycloak logs...done
  ✔ Read Plug-in Registry logs...done
  ✔ Read Devfile Registry logs...done
  ✔ Read Eclipse Che Dashboard logs...done
  ✔ Read namespace events...done
Command server:logs has completed successfully in 00:01.
```

**Comment by kollachaitanyakrishna** [comment]
[eclipse-che.zip](https://github.com/eclipse/che/files/7287505/eclipse-che.zip)
Adding the logs

**Comment by sparkoo** [comment]
`CheCluster` is CR of che-operator. You're installing with helm, in that case operator is not deployed. You have to use `--installer=operator`.

**Comment by tolusha** [comment]
@kollachaitanyakrishna 
If you are referencing this doc [1] then just update che configmap:
`CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS`: 'http://apache-che.apps-crc.testing/meta.yaml'

[1] https://www.eclipse.org/che/docs/che-7/extensions/creating-a-telemetry-plugin/#_updating_che_to_reference_your_telemetry_plug_in

**Comment by kollachaitanyakrishna** [comment]
@tolusha : can you share me the steps to be followed to update the "che" configmap. 
Available namespaces are 
admin-che              Active   25d
cert-manager           Active   40d
che-che                Active   39d
default                Active   40d
eclipse-che            Active   40d
ingress-nginx          Active   40d
kube-node-lease        Active   40d
kube-public            Active   40d
kube-system            Active   40d

Pods:
che-che                che-workspace-telemetry-example-67f7958574-wzthh   1/1     Running            14         18d
eclipse-che            apache-5d8c78fd7b-lhll8                            0/1     ImagePullBackOff   0          18d
eclipse-che            che-7bfd4d6f87-ss5qf                               1/1     Running            59         25d
eclipse-che            che-dashboard-69f69cbcf6-tnbkq                     1/1     Running            57         25d
eclipse-che            devfile-registry-5b84db5b45-dncph                  1/1     Running            76         25d
eclipse-che            keycloak-8f4b6d4c7-2h4c8                           1/1     Running            17         25d
eclipse-che            plugin-registry-67fcbc967f-vvlbh                   1/1     Running            70         25d
eclipse-che            postgres-755c4cb9db-8hsk5                          1/1     Running            49         25d
ingress-nginx          nginx-ingress-controller-757cc8b9c9-bgdtm          1/1     Running            66         25d
kube-system            coredns-558bd4d5db-8p4m7                           1/1     Running            36         40d
kube-system            coredns-558bd4d5db-vklfw                           1/1     Running            38         40d
kube-system            etcd-docker-desktop                                1/1     Running            35         40d
kube-system            kube-apiserver-docker-desktop                      1/1     Running            35         40d
kube-system            kube-controller-manager-docker-desktop             1/1     Running            35         40d
kube-system            kube-proxy-w9f4k                                   1/1     Running            35         40d
kube-system            kube-scheduler-docker-desktop                      1/1     Running            131        40d
kube-system            storage-provisioner                                1/1     Running            141        40d
kube-system            vpnkit-controller                                  1/1     Running            620        40d
kubernetes-dashboard   dashboard-metrics-scraper-856586f554-jbmns         1/1     Running            9          12d
kubernetes-dashboard   kubernetes-dashboard-67484c44f6-xsv59              1/1     Running            23         12d

**Comment by kollachaitanyakrishna** [comment]
@tolusha : can you provide me the command to update the value.

**Comment by kollachaitanyakrishna** [comment]
@tolusha : Thanks for your support, the above command worked properly.
