### ISSUE TITLE
Preview Notification setting via devfile

### ISSUE THREAD

**Issue by aishwaryapradeep01** [eclipse/che#20595]
### Summary

Hi,

I am trying to turn off the preview notifications that need a user's confirmation before the web app opens up in the preview. (Aiming to get the app to open straight away in the preview)

While there is a setting that can be done via the 'Settings -> Preferences' in the menu, is there a way that I could change this setting in the devfile instead, so that any workspace that uses this devfile would not have the preview notifications show up when an app starts running on a port?

<img width="1083" alt="che-preview" src="https://user-images.githubusercontent.com/87689930/136180631-477fb5b6-8229-4d49-bd2d-ae64567840ca.png">

### Relevant information

I've referred the settings related to the preview notifications here: https://www.eclipse.org/che/docs/che-7/end-user-guide/authoring-devfiles-version-1/#_setting_the_default_way_of_opening_preview_urls

**Comment by l0rd** [comment]
Oh right. No, that's supposed to be a user setting. Something that you set and that will be persisted even if you restart the workspace or move to another workspace.

Another option, if you want all developers that are using your instance of Che, to share some custom preferences you may customize your plugin registry and patch Che-Theia definition. @azatsarynnyy @svor do you think it's possilble to override Theia general preferences in [the plugins registry](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml) as we do for extensions?

**Comment by aishwaryapradeep01** [comment]
@l0rd I agree. I followed the steps mentioned in the doc regarding `che.task.preview.notifications` , but none of the options - `on, alwaysPreview, alwaysGoTo, off` worked
