### ISSUE TITLE
che-gateway naming

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20608]
### Is your enhancement related to a problem? Please describe

Today with devWorkspaces there are two components named `che-gateway`

- One pod running inside the `eclipse-che` namespace called `che-gateway-randomdigits`
- One container running inside every workspace pod where container is called `che-gateway`

I'm finding the naming `che-gateway` confusing inside the workspace pod because there is already a global `che-gateway`

### Describe the solution you'd like

Maybe name the component inside the workspace pod `workspace-gateway` or `che-workspace-gateway`

### Describe alternatives you've considered

I think any naming not being `che-gateway` inside the workspace pod would be fine

**Comment by sparkoo** [comment]
it's this constant https://github.com/eclipse-che/che-operator/blob/main/controllers/devworkspace/solver/che_routing.go#L54 used here https://github.com/eclipse-che/che-operator/blob/main/controllers/devworkspace/solver/che_routing.go#L166
