### ISSUE TITLE
Ability to provide the path to the devfile yaml file when using factory workflow

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20607]
### Is your enhancement related to a problem? Please describe

I have a repository having a devfile v1 there.
Then, I want to add devfile v2 in my repository but still have the v1.

I would like to be able to specify the path to my v2 when I'm running in a DevWorkspace instance

### Describe the solution you'd like

I would like to be able to specify like `devfilePath=devfile.v2` at the end of the URL for factory workflow to switch to different devfiles

### Describe alternatives you've considered

N/A but if there are better proposals

### Additional context

to have both devfile v1 and v2 in a repository and be able to use for example online instance workspaces.openshift.com  and a DevWorkspace instance to load my projects using my devfiles.

## Release Notes Text

If the devfile is not at the root of a repository or has a different name than `devfile.yaml` it can be referenced using a parameter `devfilePath` in the factory URL.

**Comment by max-cx** [comment]
@benoitf, a Yes/No question to you:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by max-cx** [comment]
@benoitf, I updated the Release Notes Text for this issue:

----

= Support for concurrent inclusion of v1 and v2 devfiles

With this update, you can have both a devfile v1 and a devfile v2 in the same repository for loading your projects in a {prod-short} instance when using the DevWorkspace engine. You can also specify the path to your devfile v2 if your devfile v2 is not at the root of the repository or has a name different from `devfile.yaml`.

----

Feel free to okay, comment, or correct it in https://issues.redhat.com/browse/CRW-2396.
Thanks!
