### ISSUE TITLE
Ensure Che release process checks that sidecar images exist

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#20609]
### Is your task related to a problem? Please describe

In the 7.37.0 release, it was discovered that sidecar imge verification is not being done correctly -- when images are missing, no failure is reported.

So, there's a missing golang sidecar image in 7.37.0.

For 7.37.1, this is apparently fixed.

### Describe the solution you'd like

But we should make sure that tests are run and report pass/fail if a required sidecar image tag doesn't exist for the current release-in-progress.

That said, we shouldn't me retagging the same content over and over if we can instead use something newer. See https://github.com/eclipse/che/issues/20610 for the golang 1.14 / 1.16 example.

**Comment by nickboldt** [comment]
latest golang 1.17 sidecars exist in https://quay.io/repository/eclipse/che-golang-1.17?tab=tags

not sure if we have anything that checks if they exist during the release yet.

**Comment by ibuziuk** [comment]
@nickboldt should we remove the `next/sprint` label to avoid confusion?

**Comment by nickboldt** [comment]
closing won't fix, as we have UDI in both up and downstream now.
