### ISSUE TITLE
Huge che-gateway RAM consumption (potential memory leak)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20606]
### Describe the bug

Che Gateway RAM consumption on production clusters is 5 and 12 GB

![image](https://user-images.githubusercontent.com/1461122/136393811-3ad798b1-adc5-4aad-b8f4-32d050742e87.png)
![image](https://user-images.githubusercontent.com/1461122/136394074-fd4202e2-c195-4ef6-9dcd-69dff8f05617.png)

`gateway` container consumes more than 6GB of RAM vs only 73 Mb for the `configbump`

### Che version

7.34

### Steps to reproduce

N/A

### Expected behavior

RAM consumption is around 200 - 500Mb for the pod

### Runtime

OpenShift

### Screenshots

PROMQL 

`sum(container_memory_working_set_bytes{container!="", namespace='codeready-workspaces-operator'}) by (container)`

![image](https://user-images.githubusercontent.com/1461122/136540052-66ceb925-c661-4e82-8d6d-eab345f97f5d.png)

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

### Eclipse Che Logs

configbump logs are pretty laconic

```
{"level":"info","ts":1632895846.6313307,"logger":"controller-runtime.controller","caller":"zapr@v0.1.0/zapr.go:69","msg":"Starting EventSource","controller":"config-bump","source":"kind source: /, Kind="}
{"level":"info","ts":1632895847.0319622,"logger":"controller-runtime.controller","caller":"zapr@v0.1.0/zapr.go:69","msg":"Starting Controller","controller":"config-bump"}
{"level":"info","ts":1632895847.13215,"logger":"controller-runtime.controller","caller":"zapr@v0.1.0/zapr.go:69","msg":"Starting workers","controller":"config-bump","worker count":1}
```
gateway logs have been shared internally

**Comment by sparkoo** [comment]
What is the gateway image please?

**Comment by ibuziuk** [comment]
@sparkoo @skabashnyuk the issue is still there on CRW 2.12.1 

![image](https://user-images.githubusercontent.com/1461122/140155199-7aafeb37-190b-4cc2-83cd-e93053083dfc.png)

**Comment by skabashnyuk** [comment]
@ibuziuk yeh picture https://github.com/eclipse/che/issues/20606#issuecomment-959758445 is unpleasant. Can you set up some limits, let's say 4G. So Kubernetes will restart the pod by itself. Meanwhile, we will work on understanding why it happening.

**Comment by ibuziuk** [comment]
@skabashnyuk not sure how it is possible to set up on the running instance powered by OLM (for operator pod it is possible to patch csv, but not sure about the operands). Currently I just restarted the pod - looks like the gateway pod is the only one without limits.

**Comment by gazarenkov** [comment]
As agreed with all stakeholders, let's start with setting container limits and see if it is a real memory-leak problem or just the way GC works.

**Comment by sparkoo** [comment]
I've merged the PR to set gateway containers resources https://github.com/eclipse-che/che-operator/pull/1276. I'm keeping this issue open, but I'm not actively working on it atm. I want to discuss with @ibuziuk whats current state on affected cluster and we may either close it or dig deeper.

**Comment by ibuziuk** [comment]
thanks, I guess the limits will land on the product only in 2.15
so, we can wait once production is running against the version of the product with the correct limits and monitor. +1 for not closing the issue until than

**Comment by ibuziuk** [comment]
the current state is that the gateway keeps restarting with OOM ~ once per day

![image](https://user-images.githubusercontent.com/1461122/163142520-fff468e5-2766-48d0-868e-1f49c3ab65d6.png)

Memory usage details for the last 2 days:

![image](https://user-images.githubusercontent.com/1461122/163142775-d88c029a-6fcb-4fae-8a6b-9ed57c63a158.png)
