### ISSUE TITLE
Users can select the editor when starting an example from Che Dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20627]
### Is your enhancement related to a problem? Please describe

When a user select a quick start (sample or URL) he cannot choose the editor that will be used in the workspace.

### Describe the solution you'd like

Having an editor dropdown list in the dashboar Getting Started page to select the specific editor. cc @beaumorley

### Release Notes Text

When starting a workspace from Che samples page in user dashboard it's possible to select the editor that will be included in the development environment.

**Comment by max-cx** [comment]
The outcome will require new content for the docs, correct?

Do we already know which SME will draft the new content?

**Comment by beaumorley** [comment]
HI @olexii4 Thanks for sharing the video. It looks great. A few suggestions. 

1.) It would be nice to give the user a little more info on what they are doing to compliment the tooltip that gives more info on the editor. There is a title options for a dropdown you could use. Like this:
![image](https://user-images.githubusercontent.com/52013984/177890123-6aba8973-efd4-4b59-b550-866658e64975.png)

2.) You could also indicate the editor that is already selected. Like this:
![image](https://user-images.githubusercontent.com/52013984/177890211-7f8f7fed-29e3-40fc-86b9-016f25e2dbf4.png)

3.) If you wanted to not have the tooltip on rollover, you could also add the icon next to each editor (if they each have a distinct icon that would help the user understand what they are). If that interested you, I could help figure out the icons.

I have a design meeting with my team tomorrow. I will LYK if they have more ideas.

**Comment by l0rd** [comment]
Thank you @beaumorley that's great.

**Comment by l0rd** [comment]
@olexii4 I like the `next` icon but I am confused: if I am using a nightly Che I will have `next` editors and if I am using stable Che I expect to see `stable` editors. I would not provide too many options to developers.

**Comment by ibuziuk** [comment]
@beaumorley could you please review - https://github.com/eclipse-che/che-dashboard/pull/575
would be great to get your approval before merging ;-)

**Comment by beaumorley** [comment]
@ibuziuk LGTM. Thank you!
