### ISSUE TITLE
New account is created after switching an existing Eclipse Che instance from 'stable' -> 'tech-preview-stable-all-namespace' channel, and enabling DevWorkspace engine

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20629]
### Describe the bug

New account is created after switching an existing Eclipse Che instance from 'stable' -> 'tech-preview-stable-all-namespace' channel, and enabling DevWorkspace engine

### Che version

7.37@latest

### Steps to reproduce

- install 'eclipse-che' using the stable channel
- create CR with a single-host and OpenShift Auth enabled 
- create an account (using 'developer' OpenShift account on the crc for example) with a couple of workspaces and start one of them
- wait until workspace is running, run build / run command
- start preparations for the migration procedure from the `stable` to `tech-preview-stable-all-namespace` 
- delete `eclipse-che` subscription from the namespace
```
[ibuziuk@fedora ~]$ oc get subscription
NAME          PACKAGE       SOURCE                CHANNEL
eclipse-che   eclipse-che   community-operators   stable
[ibuziuk@fedora ~]$ oc delete subscription eclipse-che
subscription.operators.coreos.com "eclipse-che" deleted
```
- delete csv and dependent objects
![image](https://user-images.githubusercontent.com/1461122/136939650-68264761-b18c-4bd1-adf5-d4d948fe15aa.png)
- IMPORTANT! Do not delete previously created CR / CRD
- operator pod in the namespace will be terminated
![image](https://user-images.githubusercontent.com/1461122/136939785-4ce7ca52-25c5-4f90-834a-bfcd6c3e956c.png)
- install 'eclipse-che' using the `tech-preview-stable-all-namespace`
![image](https://user-images.githubusercontent.com/1461122/136939892-aafdd299-a146-473a-9c47-5bf71022cdeb.png)
- operators are installed in the `all-namespace` mode as expected
![image](https://user-images.githubusercontent.com/1461122/136940264-78ac2212-3e4f-4d9a-b6ee-d1778e5075d9.png)
- update the CR from the `eclipse-che` namespace and enable devWorkspace
```
  devWorkspace:
    enable: true
```
- go back to the running workspace
- session expired / re-login is required
- login using the existing 'developer' account that was used previously
- ERROR: on the 'eclipse-che' end the new account is created 

![image](https://user-images.githubusercontent.com/1461122/136941334-226aae5d-b495-4cad-9c7f-21b0064b2804.png)

- ERROR: UD shows the following errors
![image](https://user-images.githubusercontent.com/1461122/136941444-f332e3ab-371e-4e82-a75e-7e4a567dba67.png)

- Start a new DevWorkspace
- ERROR: Workspace is started, but since the account is different, in a different namespace (not `developer-dev`, but 
`developeryv6z-dev`)
![image](https://user-images.githubusercontent.com/1461122/136941647-d981a7fb-0801-4e47-8ec9-37f2d830ce2a.png)

for some reason, a new account is created after the devWorkspace switch, which is utterly unexpected:

```
dbche=# SELECT * from account;
                  id                  |     name      |   type   
--------------------------------------+---------------+----------
 434d4bdf-7bae-47de-b657-9c3d675bf4d2 | developer     | personal
 e8a1a712-743c-4978-b095-9b3db488a110 | developeryv6z | personal
(2 rows)
```

### Expected behavior

The same account is used after switching an existing eclipse-che instance to all-namespace channel and enabling DevWorkspace engine

### Runtime

CodeReady Container

### Installation method

OperatorHub

### Environment

Linux

**Comment by tolusha** [comment]
Investigation is completed. There is nothing to code.
Users migration script will be a part of https://github.com/eclipse/che/issues/20602

@AndrienkoAleksandr 
Thank you!
