### ISSUE TITLE
Provide a pie chart Grafana vizualization for DevWorkspace failure reasons

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20661]
### Is your task related to a problem? Please describe

As an Admin, I want to have a proper visualization of the DevWorkspace failure reasons exposed as a Grafana Dashboard:

- bad_request
- infrastructure_failure
- workspace_engine_failure
- unknown

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1461122/137937293-60914168-f877-4366-bad7-1b6f30a71b0c.png)
![image](https://user-images.githubusercontent.com/1461122/137937347-a5e7f2a8-e5b8-4d76-8dad-d5c6e39e7b0b.png)

### Describe alternatives you've considered

N/A

### Additional context

Related epic - https://github.com/eclipse/che/issues/20261

**Comment by dkwon17** [comment]
Closing thanks to https://github.com/devfile/devworkspace-operator/pull/663
