### ISSUE TITLE
Enable 'Try in Web IDE GitHub action' in every Eclipse Che related repository

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20664]
### Is your task related to a problem? Please describe

https://github.com/marketplace/actions/try-in-web-ide

List of repositories from https://github.com/eclipse/che/blob/main/CONTRIBUTING.md 

- [ ] che https://github.com/eclipse/che
- [x] che-server https://github.com/eclipse-che/che-server/
     - [x]  https://github.com/eclipse-che/che-server/pull/258
- [x] che-code https://github.com/che-incubator/che-code
- [x] che-theia https://github.com/eclipse-che/che-theia/
- [x] chectl https://github.com/che-incubator/chectl
    - [x] https://github.com/che-incubator/chectl/pull/1838
- [x] dashboard https://github.com/eclipse-che/che-dashboard
    - [x] https://github.com/eclipse-che/che-dashboard/pull/402
- [x] devfile-registry https://github.com/eclipse-che/che-devfile-registry
- [x] docs https://github.com/eclipse/che-docs
- [x] machine-exec
    - [x] https://github.com/eclipse-che/che-machine-exec/pull/194
- [x] che-operator
    - [x] https://github.com/eclipse-che/che-operator/pull/1177
- [ ] plugin-broker
- [x] plugin-registry https://github.com/eclipse-che/che-plugin-registry
- [ ] website
- [ ] workspace-client
- [ ] che-cert-manager-ca-cert-generator-image
- [ ] che-buildkit-base
- [ ] che-sidecar-scala
- [ ] che-buildah-base
- [ ] che-docker-registry-image-copier
- [ ] che-php-base
- [ ] che-tls-secret-creator
- [ ] build-action
- [ ] che-theia-openshift-auth
- [ ] configbump
- [ ] workspace-data-sync
- [ ] che-workspace-telemetry-client
- [ ] che-workspace-telemetry-woopra-plugin
   - https://github.com/che-incubator/che-workspace-telemetry-woopra-plugin/pull/21
- [x] kubernetes-image-puller https://github.com/che-incubator/kubernetes-image-puller
- [x] kubernetes-image-puller-operator https://github.com/che-incubator/kubernetes-image-puller-operator

### Describe the solution you'd like

Each repo should have the 'Try in Web IDE GitHub action'  enabled https://github.com/marketplace/actions/try-in-web-ide

### Additional context

Blog Posts
https://developers.redhat.com/articles/2021/10/07/test-pull-requests-try-web-ide-github-action 
https://che.eclipseprojects.io/2021/10/18/@david.kwon-test-pull-requests-with-the-try-in-web-ide-github-action.html

**Comment by ibuziuk** [comment]
@svor @skabashnyuk @tolusha @themr0c @l0rd @nickboldt @azatsarynnyy please, take a moment to discuss during the team's next sprint planning

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by azatsarynnyy** [comment]
I've added for Che-Code as well https://github.com/che-incubator/che-code/pull/117
