### ISSUE TITLE
Dashboard backend support for native auth on kubernetes

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20677]
### Is your enhancement related to a problem? Please describe

Native auth (`nativeUserMode`) is coming to Kubernetes https://github.com/eclipse/che/issues/20635 https://github.com/eclipse/che/issues/20633. Currently che-dashboard can do native auth only on OpenShift.

### Describe the solution you'd like

Dasboard backend is currently trying to obtain token from Keycloak because it's expecting keycloak token. However, in native auth we're using kubernetes token directly and there is no Keycloak, so this fails in the process of creating the Kubernetes client.

Dashboard backend must use the token coming from request authorization header to create a kubernetes client, similar as it's doing already on OpenShift.

### Additional context
I've built test image (`quay.io/mvala/che-dashboard:kubeNativeAuth`) for native auth development with this patch, which looks like is doing the job:

```
diff --git a/packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts b/packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts
index 3e8a9642..d3442369 100644
--- a/packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts
+++ b/packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts
@@ -15,7 +15,6 @@ import { KubeConfig } from '@kubernetes/client-node';
 import { DevWorkspaceClient } from '../../devworkspace-client';
 import * as helper from './helpers';
 import { KubeConfigProvider } from './kubeConfigProvider';
-import { validateToken } from './keycloak';
 
 export class DwClientProvider {
   private kubeconfigProvider: KubeConfigProvider;
@@ -30,21 +29,7 @@ export class DwClientProvider {
   }
 
   async getDWClient(token: string) {
-    let contextKc: KubeConfig;
-    if (await this.isOpenShift) {
-      // on OpenShift it's supposed to be access token which we can use directly
-      contextKc = this.kubeconfigProvider.getKubeConfig(token);
-    } else {
-      // on K8s it's supposed to be keycloak token which we can't use to access the cluster
-      // so, validate token and use SA
-      try {
-        await validateToken(token);
-      } catch (e) {
-        console.error(e);
-        throw e;
-      }
-      contextKc = this.kubeconfigProvider.getSAKubeConfig();
-    }
-    return new DevWorkspaceClient(contextKc);
+    console.log("getting kube client with token: ", token);
+    return new DevWorkspaceClient(this.kubeconfigProvider.getKubeConfig(token));
   }
 }
```

_No response_

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by l0rd** [comment]
Moving to milestone 7.40 so that we can close milestone 7.39
