### ISSUE TITLE
Remove duplicated directory with plugins in theia container 

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse/che#20678]
### Is your task related to a problem? Please describe

In theia-rhel8 container, there are two directories with plugins present:
- /default-theia-plugins
- /home/theia/plugins 

### Describe the solution you'd like

leave only one directory with plugins

**Comment by benoitf** [comment]
@azatsarynnyy 7.41.0 release will be cut tomorrow. This issue is not yet closed, so please close it if it's done or move it to 7.42
