### ISSUE TITLE
Deploying Eclipse Che using Kubespray(chectl)

### ISSUE THREAD

**Issue by wbondarchuk** [eclipse/che#20693]
### Summary

Hello, everyone! I am trying to deploy che using kubespray.
I took ip adress from ingress-nginx-controller LoadBalancer   10.233.7.134    <pending>     80:31046/TCP,443:30311/TCP 44d. After that I tryed to deploy chectl 
sudo chectl server:deploy --platform k8s --domain 10.233.7.134.nip.io
And I get error.
 Installer type is set to: 'operator'
› Current Kubernetes context: 'kubernetes-admin@cluster.local'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.21.4.
    ✔ Verify domain is set...set to 10.233.7.134.nip.io.
    ↓ Check if cluster accessible [skipped]
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a
 ›    stable release of Eclipse Che (--installer=olm).
  ✔ Create Namespace eclipse-che...[Exists]
  ❯ 🏃‍  Running the Eclipse Che operator
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...It already e
xists.
    ✔ Read Roles and Bindings...done.
    ✔ Creating Roles and Bindings...done.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Create backup and restore CRDs...already exist.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace eclipse-che...It already exist
s.
    ❯ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✖ Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 255
      Prepare Eclipse Che cluster CR
    Error: Command server:deploy failed. Error log: 
    /root/.cache/chectl/error.log.
Can you help me with this problem? I'm new to this thing and I want to figure it out.

**Comment by tolusha** [comment]
Pls provide operator logs.
You can use `chectl server:logs` command

**Comment by wbondarchuk** [comment]
Everything seems to be ok.
sudo chectl server:logs
Eclipse Che logs will be available in '/tmp/chectl-logs/1635851746585'
› Current Kubernetes context: 'kubernetes-admin@cluster.local'
  ✔ Verify Kubernetes API...OK
  ✔ Verify if namespace 'eclipse-che' exists
  ✔ Read Operator logs...done
  ✔ Read Eclipse Che Server logs...done
  ✔ Read PostgreSQL logs...done
  ✔ Read Keycloak logs...done
  ✔ Read Plug-in Registry logs...done
  ✔ Read Devfile Registry logs...done
  ✔ Read Eclipse Che Dashboard logs...done
  ✔ Read namespace events...done
Command server:logs has completed successfully in 00:00.

**Comment by wbondarchuk** [comment]
Everything seems to be ok.
sudo chectl server:logs
Eclipse Che logs will be available in '/tmp/chectl-logs/1635851746585'
› Current Kubernetes context: 'kubernetes-admin@cluster.local'
  ✔ Verify Kubernetes API...OK
  ✔ Verify if namespace 'eclipse-che' exists
  ✔ Read Operator logs...done
  ✔ Read Eclipse Che Server logs...done
  ✔ Read PostgreSQL logs...done
  ✔ Read Keycloak logs...done
  ✔ Read Plug-in Registry logs...done
  ✔ Read Devfile Registry logs...done
  ✔ Read Eclipse Che Dashboard logs...done
  ✔ Read namespace events...done
Command server:logs has completed successfully in 00:00.

**Comment by tolusha** [comment]
> pls. attach logs from `/tmp/chectl-logs/1635851746585'

**Comment by wbondarchuk** [comment]
I don't have this directory with logs in tmp. My logs in /root/.cache/chectl/error.log
2021-11-03T12:34:14.572Z Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
2021-11-03T12:34:14.572Z at Object.warn (/root/.local/share/chectl/client/7.38.1/node_modules/@oclif/errors/lib/index.js:49:15)
2021-11-03T12:34:14.572Z at Deploy.warn (/root/.local/share/chectl/client/7.38.1/node_modules/@oclif/command/lib/command.js:57:16)
2021-11-03T12:34:14.572Z at OperatorTasks.<anonymous> (/root/.local/share/chectl/client/7.38.1/lib/tasks/installers/operator.js:139:25)
2021-11-03T12:34:14.572Z at Generator.next (<anonymous>)
2021-11-03T12:34:14.572Z at fulfilled (/root/.local/share/chectl/client/7.38.1/node_modules/tslib/tslib.js:114:62)
2021-11-03T12:34:14.572Z at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-11-03T12:34:19.813Z Error: Command server:deploy failed. Error log: /root/.cache/chectl/error.log.
2021-11-03T12:34:19.813Z at newError (~/.local/share/chectl/client/7.38.1/lib/util.js:199:19)
2021-11-03T12:34:19.813Z at Object.wrapCommandError (~/.local/share/chectl/client/7.38.1/lib/util.js:195:12)
2021-11-03T12:34:19.813Z at Deploy.<anonymous> (~/.local/share/chectl/client/7.38.1/lib/commands/server/deploy.js:243:35)
2021-11-03T12:34:19.813Z at Generator.throw (<anonymous>)
2021-11-03T12:34:19.813Z at rejected (~/.local/share/chectl/client/7.38.1/node_modules/tslib/tslib.js:115:69)
2021-11-03T12:34:19.813Z Cause: Error: Failed to start a pod, reason: Error, exitCode: 255
2021-11-03T12:34:19.813Z at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.38.1/lib/tasks/kube.js:134:35)
2021-11-03T12:34:19.813Z at Generator.next (<anonymous>)
2021-11-03T12:34:19.813Z at fulfilled (~/.local/share/chectl/client/7.38.1/node_modules/tslib/tslib.js:114:62)

**Comment by wbondarchuk** [comment]
It's strange why some lines were crossed out

**Comment by wbondarchuk** [comment]
They are normal in the logs, not crossed out
[logs.txt](https://github.com/eclipse/che/files/7467537/logs.txt)

**Comment by tolusha** [comment]
That was `chectl` logs but I am interested into operator logs. Let's go in another way. 
Could you execute:
```
OPERATOR_POD=$(kubectl get pods -n eclipse-che | grep che-operator | awk '{print $1}')
kubectl logs $OPERATOR_POD -n eclipse-che
```

**Comment by wbondarchuk** [comment]
OPERATOR_POD=$(kubectl get pods -n eclipse-che | grep che-operator | awk '{print $1}')
The connection to the server localhost:8080 was refused - did you specify the right host or port?

sudo kubectl logs $OPERATOR_POD -n eclipse-che
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples

sudo chectl server:deploy --platform k8s --domain 10.233.7.134.nip.io
› Installer type is set to: 'operator'
› Current Kubernetes context: 'kubernetes-admin@cluster.local'
  ✔ Verify Kubernetes API
  ❯ 👀  Looking for an already existing Eclipse Che instance
    ✖ Verify if Eclipse Che is deployed into namespace "eclipse-che"
      → connect ECONNREFUSED 127.0.0.1:6443
    Error: Command server:deploy failed. Error log: /root/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1636049602930.

**Comment by wbondarchuk** [comment]
root@node1:/tmp# ls
dbus-lLmCL0EpiQ
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-colord.service-UGDXnO
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-ModemManager.service-x4VVQh
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-power-profiles-daemon.service-WbqdV1
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-switcheroo-control.service-zdQf5u
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-systemd-logind.service-82FDuh
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-systemd-resolved.service-esQ7bD
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-systemd-timesyncd.service-dIsu9x
systemd-private-00b79d7982304e35aee4a9d7c3dc6b4b-upower.service-dN1BrZ
Temp-1e36c3ab-53a0-40c1-9922-e8ee09b2133a
tracker-extract-files.1000
VMwareDnD

**Comment by wbondarchuk** [comment]
It says that the logs are here, but they are not
