### ISSUE TITLE
Creating token for private git repository as part of Dev File Configuration

### ISSUE THREAD

**Issue by ironheart-angel** [eclipse/che#20714]
### Summary

Hi I was wondering if anyone may have guidance on how I could create a dev file pointing at a private git repo, containing my own git credentials/token within it.

This is the sample I am looking at

https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/python/devfile.yaml

Was wondering where I could put my token/git credentials in it if it was a private repo

**Comment by skabashnyuk** [comment]
https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#enabling-authentication-with-social-accounts-and-brokering_che
