### ISSUE TITLE
Under some conditions dashboard fails to open IDE

### ISSUE THREAD

**Issue by mmorhun** [eclipse/che#20717]
### Describe the bug

Sometimes dashboard fails to open IDE, however the workspace status is `Running`.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che using chectl 
2. Create a workspace and start it, so starting progress apears on dashboard
3. Sometimes it hangs, but if it opens IDE, press `F5` to refresh the page. Dashboard will not open IDE after the refresh, even in another tab.

### Expected behavior

Dashboard opens IDE

### Runtime

Kubernetes (vanilla), OpenShift

### Screenshots

![screenshot-Wait_for_workspace_readiness](https://user-images.githubusercontent.com/15607393/139867881-dff375c3-0aaf-4fbe-99be-d0f92d824be1.png)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

Due to this bug happy path test is failing: https://github.com/che-incubator/chectl/actions/runs/1399564038

**Comment by olexii4** [comment]
the same issue https://github.com/eclipse/che/issues/21055

**Comment by ibuziuk** [comment]
closing in favour of https://github.com/eclipse/che/issues/21055
