### ISSUE TITLE
Unable to build che-plugin-registry

### ISSUE THREAD

**Issue by siarhei-fedziukovich** [eclipse/che#20713]
### Summary

Node v12.22.7, Yarn v.1.22.1, there are './node_modules/.bin' in $PATH,

branch: 7.38.x
cmd: ./build.sh --organization eclipseche  --registry coreimfeiddev002.azurecr.io  --tag 7.38.0  --offline

one test failed: 
Summary of all failing tests
[test]  FAIL  tests/registry/registry-helper.spec.ts (36.971 s)
  ● Test RegistryHelper › basics with current sha1
[test]
[test]     getaddrinfo ENOTFOUND fake-docker-registry.com

**Comment by svor** [comment]
@Ga2nibal I'm able to build without problem via 
`./build.sh --organization eclipseche --registry coreimfeiddev002.azurecr.io --tag 7.38.0 --offline`
```
node --version
v12.14.1

yarn --version
3.0.2
```
try to remove cached che-plugin-registry by `rm -rf /tmp/che-plugin-registry/`

**Comment by Ga2nibal** [comment]
`rm -rf /tmp/che-plugin-registry/` resolves issue. 
thanks!
