### ISSUE TITLE
It's not possible to install not sidecar plugin via devfile v2  

### ISSUE THREAD

**Issue by svor** [eclipse/che#20718]
### Describe the bug

If extensions.json file contains plugins which are not sidecar for example [dbaeumer.vscode-eslint](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/dbaeumer/vscode-eslint/latest/meta.yaml), they won't be installed in the workspace. 

### Che version

7.38@latest

### Steps to reproduce

Try to start the forkspace form this sample https://github.com/svor/web-nodejs-sample/tree/noplugins.
The content of extensions.json is
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=827846
    // for the documentation about the extensions.json format
    "recommendations": [
        "dbaeumer.vscode-eslint"
    ]
}
```

### Expected behavior

The plugins should be installed

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
from what I see,

1. download script is not analyzing the theia component now as this one is inside a plug-in
2. it fails on empty array of attribute vscode-extensions so it tries to curl tons of dummy files

**Comment by l0rd** [comment]
@svor this looks critical to me. I have set `severity/P1`.

**Comment by benoitf** [comment]
fixed
