### ISSUE TITLE
unable to build theia-dev image

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20729]
### Describe the bug

Unable to build theia-dev image

it reports a problem of vsce being only compliant with nodejs14 while theia still requires nodejs12

https://github.com/microsoft/vscode-vsce/commit/302d33d65be4a0b773178cd0a0dd806884b0cba0

### Che version

next (development version)

### Steps to reproduce

./build.sh in dockerfiles folder

### Expected behavior

it should work

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/436777/140380310-7b370950-05a3-4f6d-814f-4bfc86e0d0ca.png)

problem is quite recent :-)

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

![image](https://user-images.githubusercontent.com/436777/140380310-7b370950-05a3-4f6d-814f-4bfc86e0d0ca.png)

**Comment by nickboldt** [comment]
new build from 9 hrs ago:

https://quay.io/repository/eclipse/che-theia-dev?tab=tags

![image](https://user-images.githubusercontent.com/227597/140450918-88cc7de8-8883-41bb-9d13-eb7e2611497c.png)

maps to the commit used to build it:

![image](https://user-images.githubusercontent.com/227597/140450961-48fb147c-2f73-44a7-bc87-fb756a460012.png)

So... resolved?
