### ISSUE TITLE
Devfile registry support for Devfile v2 zip files 

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20720]
### Is your enhancement related to a problem? Please describe

Devfile v2 are specified using the `link.v2` field in meta.yaml:

```
---
displayName: Go
description: Stack with Go 1.14
tags: ["Debian", "Go"]
icon: /images/go.svg
links:
  v2: https://github.com/che-samples/golang-echo-example/tree/devfile2
```

The `link.v2` URL points to a git repository that includes a devfile (devfiles are not included in the devfile registry anymore).

In the case of zip files what should be the value of `link.v2`? Where is the devfile stored? 

### Describe the solution you'd like

There are 2 alternatives:

#### Alternative n1: Include ~~v2 devfile~~ DevWorkspace files in the devfile registry

At registry build time we should:
- extract the `devfile.yaml`, `.vscode/extensions.json` and `.che/che-theia-plugins.yaml` from the git repo
- export the git repository as a zip file
- generate a ~~devfilev2.yaml~~ DevWorkspace and DevWorkspaceTemplates yaml files from the `.vscode/extensions.json`, `.che/che-theia-plugins.yaml`
- include the DevWorkspace and DevWorkspaceTemplates yaml files in the stack folder
- update the meta.yaml
```yaml
generatedDevWorkspaceFiles:
  path: ./DevWorkspaceFiles/
```
 
#### Alternative n2: Include a git server in the devfile registry

- clone the sample in some devfile-registry folders
- expose these git repositories through [gitweb](https://git-scm.com/book/en/v2/Git-on-the-Server-GitWeb)
- Update v2 links URLs with the devfile registry URL in entrypoint
--> Need to add a gitweb URL provider/resolver to handle it properly (protocol could be used with something like `gitweb://<host>/repository-name` )

**Comment by svor** [comment]
We are going to start with https://github.com/eclipse/che/issues/19718 to provide Dev Workspace templates for che-theia editor and host them in the devfile registry

**Comment by l0rd** [comment]
Updated the description to use `DevWorkspace` yaml files instead of `devfile`

**Comment by svor** [comment]
We finished work to pre-build DevWorkspace templates for devfile v2 in devfile registry #19718. But this templates don't have `projects` section which references on zip file. Currently we are working on it.

To support AirGap scenarios, the final step should be done on the dashboard side to apply generated DevWorspace objects from the registry: [Use generated DevWorkspaceTemplates from the devfile registry to create workspaces ](https://github.com/eclipse/che/issues/20829) 

cc @l0rd @ibuziuk
