### ISSUE TITLE
Che administrators can specify a header message on User Dashboard visible to every user

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20724]
### Is your task related to a problem? Please describe

From time to time, Admin needs to communicate some information with the users e.g.:
- scheduled maintenance  
- deprecation / EOL notifications

Admin should have a possibility to configure the header that will be applied to the UD layout.

from the UX perspective It could look similar to the warning we are having for workspace format were not only the text, but also links are supported in the message body:

![image](https://user-images.githubusercontent.com/1461122/104163902-6e732700-53f7-11eb-9af1-e15e58d7cc68.png)

### Describe the solution you'd like

It should be possible to configure the warning for UD on the CheCluster CR level e.g.

```
spec:
  dashboard:
    warning: "On date January 04, 2022 07:00 GMT, The service will undergo scheduled maintenance. More information can be found on the <a href='url'>website</a>"

```
### Describe alternatives you've considered

Currently, it is possible to configure the warning on the product.json level but this requires rebuilding the whole project which does not look like an option - https://github.com/eclipse/che/issues/18769
It should be possible to configure the banner in runtime 

### Release Notes Text

It's now possible to customize Che User Dashboard, Che users landing page, to show a message that has been setup by the administrator. The message will be visible to every user that will have access to Che User Dashboard.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by akurinnoy** [comment]
@max-cx if the question is still relevant: yes

**Comment by ibuziuk** [comment]
Fixed in the https://github.com/eclipse-che/che-operator/pull/1330
The configuration has been enabled on the dogfooding instance:
![warning](https://user-images.githubusercontent.com/1461122/157008206-ebe9c3be-751b-4233-bae3-e597a8b3bda1.gif)
