### ISSUE TITLE
Database migration script should be run automatically when user enables DevWorkspace engine on the 'all-namespace' channel

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20722]
### Is your task related to a problem? Please describe

The investigation related to the new account creation is finished as part of the https://github.com/eclipse/che/issues/20629, and the solution is the execution of the database migration script https://github.com/eclipse/che/issues/20629#issuecomment-953824124

As part of this issue, the migration script should be integrated into the operator, and run automatically only once when the user enables DevWorkspace engine after switching to the `all-namespace` channel.

### Describe the solution you'd like

the migration script should be integrated into the operator and run automatically when the user enables DevWorkspace engine after switching to the `all-namespace` channel. Potential flow

1. Eclipse Che is running in the single-namespace mode with che-server engine enabled
2. Admin switches the operator to the all-namespace mode (manual subscription / csv removal + installing operator from scratch in the 'all-namespace' mode).
3. Admin enables the DevWorkspace engine
4. Operator is running the database script automatically + creates a cm as an indicator that the script has been executed
5. Eclipse Che is running in the `all-namespace` mode with the DevWrokspace engine enabled (it is not possible to run che-server based workspaces anymore)

N/B the script should be run only once (it should be possible to create a cm as an indicator of the successful miigration).

### Describe alternatives you've considered

N/A

### Additional context

Related issue with new account creation - https://github.com/eclipse/che/issues/20629
Details regarding the migration script  - https://github.com/eclipse/che/issues/20629#issuecomment-953824124

**Comment by tolusha** [comment]
Sorry, I missed that call.
-1 from my side. Operator knows nothing about channels. 
What is the problem of running script as part of migration guide?
We already need to create subscription, so script can be run before that.

**Comment by ibuziuk** [comment]
well, every single customer will need to follow the low-level instructions for migration that is the only concern. On the other hand, performing the migration manually would allow more control and flexibility. @l0rd wdyt? can we close this issue in favour of https://github.com/eclipse/che/issues/20614 as part of which the migration documentation will be provided for upstream and downstream.

**Comment by tolusha** [comment]
We agreed to move migration script into a doc to have completely manual migration guide.
