### ISSUE TITLE
Github action happy path tests are failing on workspace readiness

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20734]
### Describe the bug

The IDE is not loaded in dashboard, it's stuck in 'waiting for IDE' state

https://user-images.githubusercontent.com/436777/140500671-efd9fa5f-44f5-414d-9ac4-dc704e07ec16.mp4

### Che version

next (development version)

### Steps to reproduce

look at various github action happy path tests https://github.com/che-incubator/chectl/actions/workflows/happy-path.yml

### Expected behavior

it should work, Dashboard should redirect to the IDE.
Also we can see that there is a green status meaning that the dashboard found that the workspace is started

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by olexii4** [comment]
Sims the same reason https://github.com/eclipse/che/issues/20698

**Comment by benoitf** [comment]
I would not say it's a blocker as it's only reproduced on github actions

**Comment by olexii4** [comment]
It was fixed with 
https://github.com/eclipse-che/che-dashboard/pull/397/files#diff-2d556cdfe15eb82ec2a340ff2714e8eafc110ea6ce5377b1724eeec628ea4f43R273

![2021-11-26_14_30_09](https://user-images.githubusercontent.com/6310786/143581441-9b710688-964f-4846-a260-7e509e8a2287.png)
