### ISSUE TITLE
Handle gracefully when an invalid devfile is found in a git repository

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20738]
### Is your enhancement related to a problem? Please describe

Currently Che starts successfully workspaces from a Git repository where there are no devfiles: the default component and editor will be used. When a workspace has a devfile that's invalid instead, there is no way for a user to start it using the default component (to fix the devfile for example).

### Describe the solution you'd like

When Che finds a devfile in a git repository but that's an invalid devfile, we should warn the user and prompt him if the workspace should start anyway (ignoring the existing devfile) or if he wants to cancel the workspace startup.

![warning-invalid-devfile](https://user-images.githubusercontent.com/606959/182797889-457e8f6d-2654-4d35-a776-8798b63f823b.png)

This is related to https://github.com/eclipse/che/issues/20616.

### Release Notes Text

Workspace creation doesn't fail anymore if the developer provides an invalid Devfile (or if an invalid Devfile is found in the git repository provided by the developer). Instead a warning is shown asking wether the workspace should be started anyway with a default Devfile. This is particularly useful when a developer is editing and testing a Devfile.

**Comment by l0rd** [comment]
I have updated the wireframe and the description.

**Comment by l0rd** [comment]
I have updated the warning text after some a @RickJWagner comment on #21606

**Comment by max-cx** [comment]
Sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-3638
