### ISSUE TITLE
It's not possible to run Happy Path tests for che-theia PRs

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#20732]
### Describe the bug

Happy Path tests are not started for `che-theia` PRs.

Please see:
- https://github.com/eclipse-che/che-theia/pull/1049#issuecomment-961694650
- https://github.com/eclipse-che/che-theia/pull/1238#issuecomment-961685451

### Che version

next (development version)

### Steps to reproduce

I tried 2 ways:
- push a new commit to my PR
- add comment `[crw-ci-test --rebuild]` to my PR

### Expected behavior

The tests are started successfully.

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: thanks for reporting about an issue!

There was an outage on CRW Jenkins side, which had broken Happy path test triggering.

It works correctly now.
