### ISSUE TITLE
Support more python versions in extension sidecar

### ISSUE THREAD

**Issue by john-heinnickel** [eclipse/che#20743]
### Is your enhancement related to a problem? Please describe

The VSCode Python extension is capable of using a range of Python versions for its target interpreter.  Only version 3.6 and up are officially supported, but the extension seems functional when targeting an unsupported python version in my limited experience.

On a desktop, the extension is able to select any interpreter on a host system, but in a containerized sidecar, it can only target python interpreter versions that are installed in the container, which currently is build from an official 3.8.6 distribution and so only has that version installed.

This is something of a liability if I am writing code that has to support 3.6 or 3.7, because I cannot rely on the IDE to tell me when I've used functionality that won't be available in those earlier versions, and I cannot toggle anything to test such support (at least as far as I'm aware--could there be some compatibility testing flags I'm unaware of?)

And in the case where I am bold enough to venture into unsupported territory, because I have to support python version earlier than 3.6 and am willing to use the extension with an unsupported interpreter at my own risk, I likewise have no way of doing this.

### Describe the solution you'd like

I think in the final analysis, the best balance between variant and/or build time explosion in the plugin registry is to add one additional variant of the che python plugin that include build tools needed to support installation of additional python versions.

### Describe alternatives you've considered

I can think of four possible avenues to pursue this, any of which I would be content with, but each of which trades off certain qualities in favor of others.

1)
If the Dockerfile producing the sidecar took on the task of installing a suite of alternate python versions outside of the default PATH, say, under /usr/local/python37, /usr/local/python36, etc., this would go a long way but it would certainly increase the build time complexity and image size.  It would also limit the developer to whichever point releases you chose--there are a lot of z's in 3.6.z an 3.7.z, and technically even 3.8.z.

It would also put you in questionable ground for users that wanted to disregard the extensions's advertised support limits and proceed ahead with an unsupported version at their own risk.  It's one thing for an end user to do that but another thing entirely for an open source re-user to publish something that includes unsupported options for reuse.

2)
Instead of providing a single Python plugin, you could follow the pattern used by s2i and other python-related projects and use a named artifact for the latest revision of each minor version.  This manages the size of each individual supported revision, but would similarly increase your build time, albeit distributed across a larger number of python che plugin variants.

3)
Install pyenv into the base image.  This would require adding build tools to the image that are not strictly needed to use Python, but are required to build alternatives.  Also, pyenv itself has been deprecated in favor of venv, which covers the aspects of pyenv related to installing virtual environments, but not with regard to maintaining multiple available versions....

4). There are `yum` installable packages for every variant I've been interested in having on hand.  But opening up sudo access to allow yum execution is probably a non-starter.  Perhaps it would be possible to extend setuid root privilege to a low-complexity read-only wrapper around yum that could only be used to select additional python versions from a list of options and then have each option map to a fixed list of arguments to `yum install`.  The only reason this was not my first suggestion was because I want to be able to step outside the extension's declared range of supported python versions without asking the che project to provide an an explicitly enumerated option for doing so in any interface it provides.

4a). There is enough similarity between the various package version names that you could let the user provide an input string that gets mixed with the pattern to select an installed version and thereby enable installing earlier python interpreters without explicitly listing them in a set of options, but it's a thin argument, and such a tool to more potential vulnerabilities in the likes of SQL injection by doing more with a user's input than just indexing into a fixed array.  

5)
Leave it up to individual users to fork the che plugin registry and customize using any of the options above or anything else that would suit their needs.  This is currently my next step and it seems like a lot. of pain to go through to customize one plugin.  I do see that there is support for providing additional Che Plugin Registries to augment the built-in one, but I'm not sure I'd know how to replicate all the appropriate details such a repository would require.  Perhaps adding a template project that users could fork and fill in content from a near-blank initial state without having to fork the entire base project would be helpful?

**Comment by benoitf** [comment]
Hello John, 

with upcoming DevWorkspace engine (and devfile v2) we're able to run the extensions in the 'user container'.
So it means, that users can define a container with the version of Python that they want and it'll be able to use it. And de facto, more Python versions can be brought.

Also there is the introduction of the universal developer image https://github.com/devfile/developer-images where for example different languages are already there.
