### ISSUE TITLE
Creating a DevWorkspace with memoryRequest > memoryLimit incorrectly results in WorkspaceEngineFailure

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#20751]
### Describe the bug

When deploying a DevWorkspace with a container where `memoryRequest` is greater than `memoryLimit` results a `WorkspaceEngineFailure` instead of a `BadRequestFailure`.

![image](https://user-images.githubusercontent.com/83611742/140952361-a0ed4062-d737-4797-ad59-40e2c689ecd6.png)

### Che version

other (please specify in additional context)

### Steps to reproduce

1. Checkout https://github.com/devfile/devworkspace-operator/pull/647 (DevWorkspace startup failure reasons are set in this PR), and follow instructions from the PR to run locally.
2. Create a DevWorkspace with this YAML file in the `devworkspace-controller` namespace: https://gist.github.com/dkwon17/13c85b162874b9bf34abc50d576aa494
3. When the DevWorkspace startup fails, view the DevWorkspace's conditions. The `FailedStart` condition's `reason` field is `WorkspaceEngineFailure` (see screenshot above)

### Expected behavior

The `reason` field should be `BadRequest`, since a `memoryRequest` value greater than the `memoryLimit` is invalid.

### Runtime

CodeReady Container

### Installation method

other (please specify in additional context)

### Environment

macOS

### Additional context

The `FailedStart` condition's `reason` field is set thanks to this PR: https://github.com/devfile/devworkspace-operator/pull/647.

This issue was created to be a followup for the work done that PR, to improve the way failure reasons are determined.

**Comment by amisevsk** [comment]
This issue would be better suited for the [devworkspace-operator](https://github.com/devfile/devworkspace-operator) repo. I think the ultimate fix may belong in the (further) upstream devfile/api repo, as they provide the basic validation package used in DWO for validating DevWorkspaces.

**Comment by amisevsk** [comment]
https://github.com/devfile/api/issues/672 tracks this as a validation item in devfile/api.
