### ISSUE TITLE
Update tests documentation and scripts to use the "npm ci" command instead of "npm install"

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse/che#20756]
### Is your task related to a problem? Please describe

The ```npm ci``` command helps to reach reproducibility of environment it installs dependencies based on package-lock.json and dependencies always has particularly defined versions. Vise versa the ```npm install``` command can produce a different results and should be used only for installing new dependencies.

### Describe the solution you'd like

Update tests documentation and scripts to use the "npm ci" command instead of "npm install"

### Additional context

https://dev.to/adamklein/package-lock-json-in-git-or-not-50l5

**Comment by dmytro-ndp** [comment]
Duplicates https://github.com/eclipse/che/issues/18773
