### ISSUE TITLE
Java plugin CPU limit is too low

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20769]
### Describe the bug

The CPU used by Java vscode can go above 500m when activating. 
![image](https://user-images.githubusercontent.com/606959/141757363-07f3da0f-a6a7-4a52-b4b6-1a01c00bd68f.png)

### Che version

7.36

### Steps to reproduce

Start the Java Spring Boot sample on Developer Sandbox

### Expected behavior

We should increase the CPU limit. Note that this is a limit, not a request. That means that if we set it too low there is a risk that the vscode extension will be throttled (will run much slower) but if we set it too high there are no risks except that the extension will be able to consume as much CPU as it needs (the pod is scheduled anyway, even if if the amount of CPU available is lower than the limit).

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

### Release Notes Text

Title: Java language support was slow due to low CPU limit
Content: During startup and at runtime the Java language server was throttled because it required more CPU than the limit set by the container runtime. The CPU limit was increased from 500MB to 800MB.

**Comment by svor** [comment]
For che plugin registry it was fixed by https://github.com/eclipse-che/che-plugin-registry/pull/1107

**Comment by max-cx** [comment]
@l0rd, (for when you're back at work) would you consider this as an enhancement or a bug (for RN purposes)? Hope you're feeling better soon.
