### ISSUE TITLE
Increase CPU required by the OpenShift connector plugin

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20763]
### Is your enhancement related to a problem? Please describe

The OpenShift Connector plugin takes a long long time to start. I looked a the CPU consumption and it looked like it was using all the 500 milicores available. I increased the the CPU limit in the devfile to 1000 milicores and the problem disappeared.

Curiously I tried to reproduce it on hosted Che and the OpenShift connector loads fast. I looked at the resources monitor and the used CPU was more than the CPU limit. How is that possible?

<img width="596" alt="image" src="https://user-images.githubusercontent.com/606959/141251373-f2ba32e2-a0fa-405c-802a-dc1f5086c246.png">

### Describe the solution you'd like

Increase the CPU limit of the [OpenShift connector](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L360).

Figure out why a plugin CPU is not limited on hosted Che.

**Comment by svor** [comment]
partially was fixed by https://github.com/eclipse-che/che-plugin-registry/pull/1082

The problem why a plugin CPU is not limited should be investigated

**Comment by ScrewTSW** [comment]
Also added area/hosted-che and bumped up the severity because of the resource quota iisue

**Comment by l0rd** [comment]
I have tested on nightly Che and it works as expected. I have created as separate issue for the second problem ([used CPU is higher than limit on developer sandbox](https://github.com/eclipse/che/issues/20768)). I am closing this issue as for me the main problem is solved. @ScrewTSW please re-open if you need to keep this issue opened until its fixed on Developer sandbox.
