### ISSUE TITLE
chectl - ignore ssl errors

### ISSUE THREAD

**Issue by Proger666** [eclipse/che#20765]
### Summary

I use managed Kubernetes installation with self-signed certs and I have access to only intermediate CA certificate.

When I try to run chectl it's failing with error:
❯ 👀  Looking for an already existing Eclipse Che instance
    ✖ Verify if Eclipse Che is deployed into namespace "eclipse-che"
      → **unable to get issuer certificate**

Because kube-api server use certificate signed by intermediate CA.

How to ignore any SSL errors and continue (like --insecure flag for curl) ?

**Comment by tolusha** [comment]
Hi. @Proger666 
Try `export NODE_TLS_REJECT_UNAUTHORIZED=0` before running `chectl`

**Comment by tolusha** [comment]
@Proger666 
Did it help?
