### ISSUE TITLE
Chectl should print dex users credentials

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20779]
### Is your enhancement related to a problem? Please describe

Chectl can now deploy on minikube with Dex. There are predefined static users https://github.com/che-incubator/chectl/blob/main/resources/dex/configmap.yaml#L28 that can be used to login into Che. Also chectl still prints credentials to keycloak, which does not make sense in this setup.

### Describe the solution you'd like

At the end of Che deployment, chectl should print the static users that user can use.
Those are: `che@eclipse.org:admin` and `userN@che:password` where `N` is 1-5.

Remove any other printed credentials to keycloak/idm.

**Comment by tolusha** [comment]
@sparkoo 
To be honest chectl doesn't know users' password in general.
Is it enough to print predefined credentials for admin user?

**Comment by sparkoo** [comment]
@tolusha chectl deploys dex configmap with predefined users https://github.com/che-incubator/chectl/blob/main/resources/dex/configmap.yaml#L28 so it kind-off knows the users credentials. `admin` user here is same as any other user, it does not have any special privileges. These static users are really meant only for testing. In real world, you would connect dex to github/google/... I will prepare doc for that as well and we should reference it in chectl as well.
