### ISSUE TITLE
VSCode extension - code to expand the panels automatically is not working

### ISSUE THREAD

**Issue by bodarajeshkumar** [eclipse/che#20771]
### Describe the bug

I have a VSCode extension installed in Eclipse-Che. This extension has 4 panels on the left side. These 4 panels should be expanded state by default. They are expanded using the code below

```
 vscode.commands.executeCommand("panel1.focus");
vscode.commands.executeCommand("panel2.focus");
vscode.commands.executeCommand("panel3.focus");
```

This code used to work in the old version of Eclipse-Che (version: 7.20.1) 
Recently we upgraded the Eclipse-Che to the latest version ( 7.37.2) and now the same code is not working.

### Che version

7.37

### Steps to reproduce

1. Add a VSCode extension to Eclipse-Che which contains a few panels on the left side 
2. Add the code to expand the panels by default in the activate event. Code is given in the description.
3. launch the extension to see if the panels are expanded by default. 

### Expected behavior

All the panels should be expanded by default when launching the extension

### Runtime

IBM Cloud

### Screenshots

Expected behaviour:
<img width="454" alt="Screenshot 2021-11-15 at 10 10 15 PM" src="https://user-images.githubusercontent.com/82795269/141823146-e82f323d-2cc3-4451-9579-0b94b8537820.png">

Current behaviour:
<img width="328" alt="Screenshot 2021-11-15 at 10 11 33 PM" src="https://user-images.githubusercontent.com/82795269/141823180-f6aac092-4104-4c0a-9c7b-ffecd2644357.png">
>

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Installed in IBM Cloud Kubernetes Cluster

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar 
Hello!
thank you for reporting the problem!

Do you mind to share your VSCode extension (or some sample) to reproduce the issue?
We could try how it works for vanilla `theia` to detect if the problem on `che-theia` side or it's on `theia` side.

thanks in advance!

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko 
Thank you for checking. Here is the code for the sample VSCode extension 
https://github.com/bodarajeshkumar/tree-view-sample
This shows all the  node dependencies in the panel like below
<img width="655" alt="Screenshot 2021-11-16 at 11 37 45 PM" src="https://user-images.githubusercontent.com/82795269/142041904-39b0dd5b-5d31-4448-8018-7747d4fb2574.png">

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar 
thank you very much for your sample!

I modified a little your sample and tested the use case for vanilla `theia`:
```
vscode.commands.registerCommand('expandPanelsCommand', () => {
		vscode.commands.executeCommand("panel1.focus");
		vscode.commands.executeCommand("panel2.focus");
		vscode.commands.executeCommand("panel3.focus");
	});
``` 

At the moment `che-theia` [depends](https://github.com/eclipse-che/che-theia/blob/e121bd27198ace43ae43237bdf6ed50108eaccfe/build.include#L17) on [the commit](https://github.com/eclipse-theia/theia/commit/a73a746bfdefc115edb506f2351b5f4e3f267077) of `theia`.

I see that the functionality doesn't work for that commit of `theia`:

https://user-images.githubusercontent.com/5676062/142147487-f23ed0e3-0999-49e8-a14f-541b73f8b287.mov

But the functionality works well for the latest commit of `theia`:

https://user-images.githubusercontent.com/5676062/142147889-5e94db74-2f80-4d59-a67d-8846faa01282.mov

So, I believe it's already fixed in upstream and should be fixed for `che-theia` when we pick up the corresponding commit.

**Comment by bodarajeshkumar** [comment]
Thank you very much for working on this @RomanNikitenko.
when can we expect this fix to be merged to che-theia? is it possible to give some tentative date?

**Comment by RomanNikitenko** [comment]
Breaking changes were merged to upstream (`theia`), it's related to build system.
We are working on adaptation `che-theia` assembly to those changes.

You can track related issue https://github.com/eclipse/che/issues/20538

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko I see the blocking issue #20538 is now closed. Is che-theia pointing to the latest version of theia now?
Can I expect this issue to be fixed with the latest eclipse-che?

**Comment by RomanNikitenko** [comment]
please see https://github.com/eclipse/che/issues/20772#issuecomment-1014607599

**Comment by RomanNikitenko** [comment]
I didn't investigate which commit in upstream fixed the bug, so I don't know if we picked up that commit at the latest upgrade `Theia` version...
