### ISSUE TITLE
How to access host device's camera and microphone in browser preview window?

### ISSUE THREAD

**Issue by SuyashGupte** [eclipse/che#20777]
I am trying to run a React + Express language translation application in Eclipse che's default che-theia editor. The application is running in the browser preview window but I am unable to take user input using the microphone.

If I open the link in a new tab instead of browser preview the application works fine but is there a way to the same thing using the browser preview extension.

**Comment by azatsarynnyy** [comment]
Hello @SuyashGupte 
Thank you for an interesting question.
I'd suggest you investigate iframe restrictions related to accessing such resources as the user's devices.
E.g. iframe's `allow` attribute, Feature Policy, etc.
This article may be a good start https://developers.google.com/web/updates/2018/06/feature-policy

**Comment by SuyashGupte** [comment]
I tried to check for microphone access on the default workspace page using `document.featurePolicy.allowsFeature('microphone')` and it returned `false`.
I added `allow="microphone"` attribute in browser preview `iframe` but it didn’t work.
When I open the preview URL in new tab `document.featurePolicy.allowsFeature('microphone')` returns `true`.

**Comment by azatsarynnyy** [comment]
There're several iframes in Che:
- the Dashboard's container for embedding an ide
https://github.com/eclipse-che/che-dashboard/blob/4d4ca1f3a67d86cdc1c1b9f8ab1496a69b64fd46/packages/dashboard-frontend/src/pages/IdeLoader/index.tsx#L291

- Theia's preview iframe
https://github.com/eclipse-theia/theia/blob/29ebe4c1cc1f8608d23ad92220c6a615c775a27c/packages/mini-browser/src/browser/mini-browser-content.ts#L147

**Comment by SuyashGupte** [comment]
Thank you @azatsarynnyy

**Comment by azatsarynnyy** [comment]
Probably, there're just minimally required permissions.
So far, there were no specific reasons to add more permissions.
@SuyashGupte you can try to provide corresponding PRs.
