### ISSUE TITLE
VSCode extension TreeView context Icon not showing on hover

### ISSUE THREAD

**Issue by bodarajeshkumar** [eclipse/che#20772]
### Describe the bug

I have a VSCode extension installed in Eclipse-Che. The extension has a panel with TreeView. TreeView contains a list of items. Each item has a context Icon associated with it and can be clickable. This icon can be shown by hovering on the icon.
This functionality used to work in the old version of Eclipse-Che (7.20.1). We upgraded it to the latest version of Eclipse-Che and now the icon is not shown on hover. We have to click the item to show the icon instead of hovering.

### Che version

7.37

### Steps to reproduce

1. Add a VSCode extension to Eclipse-Che which contains a Tree-View. 
2. TreeView should contain some items along with a context icon
3. Upon Launching the extension, hover the mouse cursor on one of the items in the tree view to show the icon. 
4. Icon won't show up on hover. Instead, it will show on clicking the icon

### Expected behavior

The icon should show on hovering over the tree view item

### Runtime

other (please specify in additional context)

### Screenshots

See the document icon which should show up on hover
<img width="409" alt="Screenshot 2021-11-15 at 10 10 30 PM" src="https://user-images.githubusercontent.com/82795269/141826688-2dae77b5-0caf-4076-8c94-0226f8dbb8bb.png">

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Installed on IBM Cloud Kubernetes Cluster

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar
Hello!
thank you for reporting the problem!

> 1. Add a VSCode extension to Eclipse-Che which contains a Tree-View.
> 2. TreeView should contain some items along with a context icon

Do you mind to share your VSCode extension (or some sample) to reproduce the issue?
It will help to reproduce and investigate the problem! 

thanks in advance!

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko 
Thank you for checking. Here is the code for the sample VSCode extension 
https://github.com/bodarajeshkumar/tree-view-sample
This shows all the  node dependencies in the panel like below
<img width="655" alt="Screenshot 2021-11-16 at 11 37 45 PM" src="https://user-images.githubusercontent.com/82795269/142041904-39b0dd5b-5d31-4448-8018-7747d4fb2574.png">

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar 
thank you very much, for your sample - I tested the use case for vanilla `theia` and can confirm that the problem is on `theia` side.

Moreover, I found the upstream issue https://github.com/eclipse-theia/theia/issues/10369
It should be fixed by https://github.com/eclipse-theia/theia/pull/10375

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko I am still seeing this issue in the latest Eclipse-Che(version 7.41.2). Not sure if eclipse-che is using the latest version of theia or not. Can you please let me know if I am missing anything?

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko I see Che-theia is still pointing to the old version of eclipse-che. Is there any plan to point it to the latest version soon?

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar 
Hello!
I had a quite long vacation, so I saw your question only now.

Che-theia depends on [this commit of Theia](https://github.com/eclipse-che/che-theia/blob/05d296b5cd586561c483d62866f8412245a6361e/build.include#L17), so it looks like `che-theia` does not contain the fix.

> I see Che-theia is still pointing to the old version of eclipse-che. Is there any plan to point it to the latest version soon?

Unfortunately, as far as I know there is no plan to align `che-theia` to the latest `theia` at least for the next month (I don't see any related issue in progress or in plans)...
