### ISSUE TITLE
Disable timeline view plugin

### ISSUE THREAD

**Issue by bodarajeshkumar** [eclipse/che#20773]
### Summary

I am trying to remove Timeline view which shows Git History in Eclispe-Che. is there a way to do it?
or Can you point me to the code which contributes to this Plugin?

**Comment by RomanNikitenko** [comment]
@vinokurig 
Could you take a look?

**Comment by vinokurig** [comment]
@bodarajeshkumar To hide the view you can right click on the panel name and chose `Hide`:
![screenshot-che-eclipse-che 192 168 64 81 nip io-2021 11 17-09_04_12](https://user-images.githubusercontent.com/7668752/142150639-d7301a0a-517c-4aed-b613-3210adccf187.png)
This is an upstream [Theia module](https://github.com/eclipse-theia/theia/blob/master/packages/timeline/src/browser/timeline-frontend-module.ts), so if you need to disable the extension, you need to unbind it.

**Comment by bodarajeshkumar** [comment]
@vinokurig Thank you for the information. I want to completely remove the timeline instead of just hiding it. Is it possible to write a custom theia extension that does this task?

**Comment by RomanNikitenko** [comment]
I didn't test it, but it should be possible to rebind `TimelineContribution`.
Like:
```
@injectable()
export class EmptyTimelineContribution extends TimelineContribution {
 
  registerToolbarItems(registry: TabBarToolbarRegistry): void {
    // do hothing
  }
  registerCommands(commands: CommandRegistry): void {
    // do hothing
  }
}
```
and within a module of a `che-theia` extesion
```
bind(EmptyTimelineContribution).toSelf().inSingletonScope();
rebind(TimelineContribution).to(EmptyTimelineContribution);
```

**Comment by bodarajeshkumar** [comment]
Thank you @RomanNikitenko. I will test it.

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko When I tried the above code, I am getting below error for rebinding. Can you please suggest
![image](https://user-images.githubusercontent.com/82795269/142815594-0905f60b-a7af-4032-9fac-4dcfa5ec9248.png)

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko When I tried the above code, I am getting below error for rebinding. Can you please suggest

It looks strange, we have few places with rebinding on the `che-theia side` - it works well

<img width="474" alt="Screenshot 2021-11-22 at 15 29 41" src="https://user-images.githubusercontent.com/5676062/142870625-5fa678d6-17a4-4c3b-abe1-7d2d930b35e4.png">

You could find such cases as examples within `che-theia`.

Also I don't see the problem on my side

<img width="784" alt="Screenshot 2021-11-22 at 15 24 28" src="https://user-images.githubusercontent.com/5676062/142870779-34ab8c74-c168-4ce4-890b-0ef41eefaf79.png">

Do you have the same problem/errors when you build a module with the rebinding?

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko No, I don't see this error in che-theia project. I created a theia-hello-world-extension and copied your code  there for testing and there I am seeing this error. I will try to find I am missing anything. Please let me know if you have any thoughts.

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko I found the issue. It is because of not specifying the type of rebind object in the parameters. Following code fixed the issue. Thank you very much for your guidance.
```
export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
    // add your contribution bindings here
    bind(CommandContribution).to(HelloWorldCommandContribution);
    bind(MenuContribution).to(HelloWorldMenuContribution);
    bind(EmptyTimelineContribution).toSelf().inSingletonScope();
    rebind(TimelineContribution).to(EmptyTimelineContribution);
});
```
