### ISSUE TITLE
java.lang.IllegalStateException: getAttribute: Session already invalidated

### ISSUE THREAD

**Issue by Flugtiger** [eclipse/che#20789]
I repeatedly get an HTTP status 500, when calling REST APIs (e.g. GET /api/user). The first request seems to always go through but subsequent requests with the same user (but maybe a different access token) always result in this error:

```
java.lang.IllegalStateException: getAttribute: Session already invalidated
        org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1140)
        org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:102)
        org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:133)
        org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:99)
        org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:77)
        org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
        com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
```

This might be a regression of this problem: #15798

**Comment by skabashnyuk** [comment]
@Flugtiger thank you for this report. Could you please follow the bug template and provide additional details?

**Comment by cjsteele** [comment]
Might be completely irrelevant, but we encountered this error by creating users without specifying an email address in keycloak. Keycloak allows you to create the users like this but any attempt to login with that user would then cause the stacktrace as posted above.

**Comment by skabashnyuk** [comment]
Email is a mandatory thing for Eclipse Che with Keycloak.  I think it can't be avoided. That is one of the primary keys.

**Comment by skabashnyuk** [comment]
can't reproduce.
