### ISSUE TITLE
Inject user kubeconfig into Che workspaces with DevWorkspace enabled

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20782]
### Is your enhancement related to a problem? Please describe

In current Che workspaces with DevWorkspace disabled, when the OpenShift connector starts, [authentication to the OpenShift API is done automatically](https://github.com/eclipse/che/issues/15261). 

This mechanism has 2 problems:
1. It's fragile and intrusive https://github.com/eclipse/che/issues/16930
2. It doesn't work when DevWorkspace is enabled

### Describe the solution you'd like

Che should inject the Kubernetes configuration of the user in the workspace containers at workspace startup. The mechanism should be the one used by the OpenShift console for the Web Terminal DevWorkspace.

The OpenShift connector should not need to use `che-theia-openshift-auth` anymore as users are already authenticated.

**Comment by ibuziuk** [comment]
@l0rd are you ok with postponing this for DevWorkspace feature freeze?

**Comment by l0rd** [comment]
This is important. The openshift-connector requires it to login the user automatically. Not having it means having a regression that will break some Red Hat workshops. However, if including it in current sprint is not realistic, we can postpone it for later (Che 7.43 / CRW 2.16). cc @svor

**Comment by svor** [comment]
@ibuziuk @l0rd should it be removed from the milestone STEP3 ?

**Comment by l0rd** [comment]
@JPinkney can we close this issue?
