### ISSUE TITLE
Can't start a workspace with Che-IDEA editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#20783]
### Describe the bug

A workspace with Che-IDEA editor can't be started.

### Che version

next (development version)

### Steps to reproduce

Try to start a workspace with the following devfile
https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.13-rhel-8/tech-preview-devfiles/idea/latest.yaml

### Expected behavior

A workspace should start.

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/1636395/142031883-d11d76c9-ad5a-48b0-bd50-cdbe5a70a2f4.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by azatsarynnyy** [comment]
Che-Server Workspace API returns the correct URL:
https://serverek0aq93r-jwtproxy-server-4400.192.168.39.82.nip.io/?backgroundColor=434343&wss/

But the URL from the workspace loader error has the query parameters cut:
https://serverek0aq93r-jwtproxy-server-4400.192.168.39.82.nip.io/?backgroundColor

**Comment by azatsarynnyy** [comment]
Everything works well in Che 7.36.2.
The problem is reproduced with the latest Che - 7.40

**Comment by olexii4** [comment]
@azatsarynnyy I reproduce this issue. It wasn't on the dashboard side.

Just try to open that [URL](https://serverek0aq93r-jwtproxy-server-4400.192.168.39.82.nip.io/?backgroundColor=434343&wss/) from a different tab and you will see the same error.

It is a loader issue
https://github.com/eclipse-che/che-server/blob/7.39.x/assembly/assembly-root-war/src/main/webapp/_app/loader.js#L145

**Comment by azatsarynnyy** [comment]
I set `area/dashboard` as there's no `area/workspace-loader`.

**Comment by ibuziuk** [comment]
@benoitf could you please clarify what is the path parameter `/?backgroundColor=434343&wss` stands for from https://github.com/eclipse-che/che-plugin-registry/pull/1064

**Comment by benoitf** [comment]
it's the starting parameter used for all of our jetbrains IDE as defined there:
https://github.com/che-incubator/jetbrains-editor-images/tree/meta/che-idea

**Comment by ibuziuk** [comment]
@benoitf thanks, it looks like there is some subtle bug in the loader, but it was not reproducible before with the previous meta.yaml
@vzhukovs could you clarify why do we need this starting parameter in general - https://github.com/che-incubator/jetbrains-editor-images/blob/meta/che-idea/2020.3.3.meta.yaml#L23

**Comment by benoitf** [comment]
to clarify, before it was using the VNC approach of intellij and now it switched over to Projector based solution
