### ISSUE TITLE
Can not execute the @eclipse-che/che-theia-devworkspace-handler npm package

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20780]
### Describe the bug

The [npm package](https://www.npmjs.com/package/@eclipse-che/che-theia-devworkspace-handler) hasn't any executable references, so it cannot be executed e.g. by npx.

### Che version

next (development version)

### Steps to reproduce

execute `npx @eclipse-che/che-theia-devworkspace-handler`
See:
```
command not found: che-theia-devworkspace-handler
```

### Expected behavior

The command should provide some output.

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

macOS

**Comment by vinokurig** [comment]
@benoitf Could you please take a look?

**Comment by benoitf** [comment]
yes but it should not block you as you can workaround it by building the library

**Comment by benoitf** [comment]
PR to fix the issue: https://github.com/eclipse-che/che-theia/pull/1256
