### ISSUE TITLE
Use mvn commands to run and debug for java-maven-based devfiles

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20791]
### Is your enhancement related to a problem? Please describe

Currently, most devfiles are using `java -jar target/*.jar`.

the inconvenient of using java -jar is that it requires users to have launch the build task beforehand, and every time there si a modification done.
https://github.com/eclipse-che/che-devfile-registry/blob/884b521459fcc1b6657b2241044ccf222fd149c2/devfiles/java-web-spring/devfile.yaml#L59

### Describe the solution you'd like

For instance to launch in debug with mvn with springboot

https://github.com/eclipse-che/che-devfile-registry/blob/884b521459fcc1b6657b2241044ccf222fd149c2/devfiles/apache-camel-springboot/devfile.yaml#L72

### Additional context

/!\ devfiles are currently in migration to devfile v2 in che-samples repository

**Comment by vitaliy-guliy** [comment]
che-samples update status

- [ ] [apache-camel-springboot](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/apache-camel-springboot/meta.yaml) :: https://github.com/che-samples/fuse-rest-http-booster/tree/devfilev2 - up to date
- [ ] [java-lombok](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-lombok/meta.yaml) :: https://github.com/che-samples/lombok-project-sample/tree/devfilev2 - up to date
- [ ] [java-mongo](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-mongo/meta.yaml) :: https://github.com/che-samples/java-guestbook/tree/devfilev2 - [Pull Request](https://github.com/che-samples/java-guestbook/pull/5)

**Comment by vitaliy-guliy** [comment]
[Devfile registry](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles) contains only five java maven based samples.
Two of them, that were using `java -jar` have been updated.
