### ISSUE TITLE
Provide kamel binary in universal developer image

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20794]
### Is your enhancement related to a problem? Please describe

The VS Code Camel K is currently using a sidecar with [kamel binary in it](https://github.com/eclipse-che/che-plugin-registry/blob/a95fbe7e14dd6b50cc361bbbe2d1fedf90e8e018/sidecars/camelk/Dockerfile#L14). it allows to have a faster deployment, otherwise the binary needs to be downloaded on each workspace start (creation?).

### Describe the solution you'd like

To [migrate to devfile v2](https://github.com/eclipse/che/issues/19341), I think that the kamel binary should be provided in the [Universal Developer Image](https://github.com/devfile/developer-images)

**Comment by svor** [comment]
@apupier if you'd like to contribute this, I'd be happy to review the PR
