### ISSUE TITLE
Universal Developer Image enhancements

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20799]
### Is your enhancement related to a problem? Please describe

Issues related to [Developers images](https://github.com/devfile/developer-images)
- gh action publishes the wrong "universal base image"  
- there is not automated check for new versions the tools
- they are not compatible with  Red Hat internal image build tool
- they are not multi-arch
- there is no PR check against Che samples
- manual modification of the README.md (tools lists and sizes) is tedious and error prone

### Describe the solution you'd like

- #20798
- #20862
- #22029
- #20858
- [Migrate to UBI9](https://issues.redhat.com/browse/CRW-3185)
- Automate developers image updates (c.f. [dependabot ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems), [renovate data sources](https://docs.renovatebot.com/modules/datasource/repology/))
- Add developers images PR check that validate che samples work
- Add developers images PR check that does a security scan (c.f. [trivy](https://github.com/aquasecurity/trivy))
- Automate certs injections in the Java keystore
- Automatically update developers images README
- #22009
- #22010

### Additional context

- https://github.com/devfile/api/issues/616
- https://github.com/devfile/api/issues/674

**Comment by nickboldt** [comment]
> Rework developers images to make them compatible with Red Hat internal image build tool (aka brew)
Note: downstream in https://issues.redhat.com/browse/CRW-2463 and https://issues.redhat.com/browse/CRW-2464 we are required to have 3 images:
* udi for tech preview support
* udi for GA support w/ openjdk
* udi for GA support w/ openj9

Or, we need a way to differentiate which devfile tiles in the dashboard are GA-supported / tech-preview. Perhaps a red outline or a ribbon on the tiles?

**Comment by max-cx** [comment]
Please consider adding here the following issue (adding GH and GL CLI tools) as a sub-task: https://github.com/eclipse/che/issues/21253 .

**Comment by nickboldt** [comment]
> Or, we need a way to differentiate which devfile tiles in the dashboard are GA-supported / tech-preview. Perhaps a red outline or a ribbon on the tiles? Could also use this mechanism to differentiate Che samples from CRW samples.

We now have a way of labelling devfiles as "tech preview" or "community" via a label. 

![image](https://user-images.githubusercontent.com/227597/180789047-804778d4-77bd-42c1-bb79-1ed04e90cc17.png)

> udi for GA support w/ openj9

And there's no longer openJ9 images downstream (https://issues.redhat.com/browse/CRW-3048).

So, at this point we could consider having the same [devspaces-samples](https://github.com/devspaces-samples/) projects in both Che and Dev Spaces, augmented by some projects that are ONLY upstream.

This would reduce the sample list so we don't have slightly different samples for the same languages in up vs. down, and would make it more feasible to use the same (or a more-closely-aligned, less-forking-needed) UDI image in both up and downstream.
