### ISSUE TITLE
Provide JDK 8 in universal developer image

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20793]
### Is your enhancement related to a problem? Please describe

Java 8 still have support for some time (see https://access.redhat.com/solutions/4934371 or https://access.redhat.com/articles/1299013#OpenJDK_Life_Cycle )

At least one current che-samples requires Java 8: Camel on SpringBoot example: https://github.com/che-samples/fuse-rest-http-booster

### Describe the solution you'd like

it would be nice to have also Java 8 in the base image.

### Additional context

This will simplify Camel On SpringBoot migration, in the context of https://github.com/eclipse/che/issues/19341
it might make sense to add java 17 at the time to have all current LTS.

**Comment by svor** [comment]
@apupier is it something you'd like to contribute?

**Comment by apupier** [comment]
> @apupier is it something you'd like to contribute?

no, I do not know how it should be implemented in a good practice way and I have no time for it on short term
