### ISSUE TITLE
Not possible to start a workspace if DevWorkspace is enabled 

### ISSUE THREAD

**Issue by svor** [eclipse/che#20801]
### Describe the bug

It's not possible to start any workspace in DevWorkspace.

DevWorkspace was deployed by `chectl server:deploy --installer=operator  --platform=openshift --workspace-engine=dev-workspace` 

```
chectl version
chectl/0.0.20211119-next.53696c6 linux-x64 node-v12.22.7
```
### Che version

next (development version)

### Steps to reproduce

1. Deploy DevWorkspace
2. Try to create a workspace from the dashboard or by using factory

### Expected behavior

The workspace should be created and started

### Runtime

OpenShift

### Screenshots

![screenshot-che-eclipse-che apps cluster-5d7v2 5d7v2 sandbox925 opentlc com-2021 11 22-10_51_27](https://user-images.githubusercontent.com/1271546/142831033-1bc53d8a-0014-4ee7-99ca-00f5f2c9ede0.png)

![screenshot-nimbus-capture-2021 11 22-10_35_36](https://user-images.githubusercontent.com/1271546/142831035-bb9dad9d-9c44-4cda-a526-bb126ab5e1f1.png)

![screenshot-console-openshift-console apps cluster-5d7v2 5d7v2 sandbox925 opentlc com-2021 11 22-10_52_27](https://user-images.githubusercontent.com/1271546/142831119-7b8a815a-c5e8-4551-a412-802427630e90.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
Errors from devworkspace-controller-manager pod:

{"level":"info","ts":1637568774.1306536,"logger":"controllers.DevWorkspace","msg":"Error updating workspace status: Operation cannot be fulfilled on devworkspaces.workspace.devfile.io \"golang-echo-example-atxb\": the object has been modified; please apply your changes to the latest version and try again","Request.Namespace":"che-che","Request.Name":"golang-echo-example-atxb","devworkspace_id":"workspacee45c39d15b2a47e6"}
{"level":"error","ts":1637568774.130681,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"workspace.devfile.io","reconcilerKind":"DevWorkspace","controller":"devworkspace","name":"golang-echo-example-atxb","namespace":"che-che","error":"Operation cannot be fulfilled on devworkspaces.workspace.devfile.io \"golang-echo-example-atxb\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v...
```

**Comment by benoitf** [comment]
I've the same issue

**Comment by benoitf** [comment]
As a workaround I reverted some commits of che-operator on a custom image (using https://github.com/eclipse-che/che-operator/commit/3d6568af51eb0a7b2281788d89a9128342deed7b )

```
chectl server:deploy --installer=operator --platform=openshift --workspace-engine=dev-workspace --che-operator-image=quay.io/fbenoit/che-operator:18cdc6391
```

and it's working again doing that

**Comment by svor** [comment]
cc @tolusha @mmorhun

**Comment by mmorhun** [comment]
Fixed
