### ISSUE TITLE
Resources Monitor Plugin doesn't work when devWorkspace engine is enabled

### ISSUE THREAD

**Issue by svor** [eclipse/che#20800]
### Describe the bug

Resources Monitor plugin doesn't display information about the pod's resources when the workspace is running.

### Che version

7.39@latest

### Steps to reproduce

1. Deploy che with dev-workspace engine
2. Start any workspace 
3. Look at status bar where should be displayed an information from the Resources Monitor plugin

### Expected behavior

Information about resources should be displayed in the status bar

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
Extension-Host:With stack trace: Error: Cannot get workspace pod. HttpError: HTTP request failed
    at ResourceMonitor.getWorkspacePod (/tmp/theia-unpacked/eclipse_che_resource_monitor_plugin.theia/lib/resource-monitor.js:67:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Extension-Host:Promise rejection not handled in one second: TypeError: Cannot read property 'attributes' of undefined , reason: TypeError: Cannot read property 'attributes' of undefined
Extension-Host:With stack trace: TypeError: Cannot read property 'attributes' of undefined
    at DevfileHandler.isRecommendedExtensionsDisabled (/tmp/theia-unpacked/eclipse_che_recommendations_plugin.theia/lib/devfile/devfile-handler.js:31:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RecommendationsPlugin.start (/tmp/theia-unpacked/eclipse_che_recommendations_plugin.theia/lib/plugin/recommendations-plugin.js:47:26)
```

### Additional context

The problem could be related to a mechanism which is used in ResMonitor plugin to [get an information about workspace's pod](https://github.com/eclipse-che/che-theia/blob/main/plugins/resource-monitor-plugin/src/resource-monitor.ts#L66). As an alternative we can [try to reuse k8s-devfile-service api](https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts#L48). 

But it's important to check that it'll work when devWS engine is not enabled.

**Comment by svor** [comment]
I've fixed a problem with reading workspace pod information by setting right name of workspace's namespace.
The next problem is related to workspace SA, it's not possible to read metrics:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods.metrics.k8s.io "workspace4f756f319b3f4555-5f8b6bdff4-ktp5k" is forbidden: User "system:serviceaccount:opentlc-mgr-che:workspace4f756f319b3f4555-sa" cannot get resource "pods" in API group "metrics.k8s.io" in the namespace "opentlc-mgr-che"","reason":"Forbidden","details":{"name":"workspace4f756f319b3f4555-5f8b6bdff4-ktp5k","group":"metrics.k8s.io","kind":"pods"},"code":403}
```

**Comment by amisevsk** [comment]
PR https://github.com/devfile/devworkspace-operator/pull/695 adds get/list/watch permissions for pod metrics in the workspace ServiceAccount.

**Comment by svor** [comment]
Fixed by https://github.com/eclipse-che/che-theia/pull/1269 and https://github.com/devfile/devworkspace-operator/pull/695

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by svor** [comment]
depends on devworkspace-operator v0.12.0 https://github.com/devfile/devworkspace-operator/pull/695

**Comment by svor** [comment]
Works on https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/ instance

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 02 04-11_11_48](https://user-images.githubusercontent.com/1271546/152538447-66b604d8-6dee-484d-b10c-f38f34e048a2.png)
