### ISSUE TITLE
v2 devfiles are not working on Eclipse Che version : 7.39.1-SNAPSHOT

### ISSUE THREAD

**Issue by makambalaji** [eclipse/che#20807]
### Describe the bug

Unable to start the eclipse che workspace with devfile v2 sample : https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml, 

### Che version

7.39@latest

### Steps to reproduce

1. Login to eclipse che dashboard
2. Navigate to Create Workspace page
3. Click on Custom workspace tab
4. Enter the devfile url as "https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml"
5. Click on Load Devfile button

### Expected behavior

Workspace should start

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/61005404/142878852-6fb56b4f-eea2-49a2-ac47-cd49ff2df283.png)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

Related: https://github.com/eclipse/che/issues/20616

Factory url : https://che-eclipse-che.192.168.59.113.nip.io/dashboard/#/load-factory/?url=https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml

**Comment by makambalaji** [comment]
@ibuziuk didn't catch, that it DevWorkspace shouldn't be enabled. this is part of the use case related to pr: https://github.com/eclipse/che/issues/20616

**Comment by ibuziuk** [comment]
raw support of the devfiles v2 has been merged today - https://github.com/eclipse-che/che-dashboard/pull/408
@akurinnoy can provide more details, but this flow is expected to be working on nighlies now

**Comment by akurinnoy** [comment]
@makambalaji devfiles v2 in che-server mode are supported for factory flow only. The workaround here is to create workspaces using a factory link like `che-host/dashboard#https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml`.

@ibuziuk do you think if it makes sense to support this use case as well?
