### ISSUE TITLE
Deprecate VS Code wsdl2rest

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20811]
### Is your task related to a problem? Please describe

VS Code wsdl2rest is now deprecated

### Describe the solution you'd like

mark VS Code wsdl2rest as deprecated so that it can be remove din later release

**Comment by apupier** [comment]
asked here how to do that https://mattermost.eclipse.org/eclipse/pl/qxdgwoeoeprgxrpy54akwxbnny

**Comment by metlos** [comment]
Can this be closed now?

**Comment by apupier** [comment]
No, the PR has not been merged.
