### ISSUE TITLE
Dashboard error after first login "forbidden. User cannot list devworkspaces"

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20819]
### Describe the bug

After first login into Che with devworkspaces, dashboard shows an error that it can't list devworkspaces, because user does not have permissions to do so.

Issue is caused by dashboard asking for devworkspaces before the namespace is fully provisioned by che-server. As seen in the screenshot, Dashbaord asks che-server to provision the namespace (selected top request in network traffic). Then there are 2 red requests to get devworkspaces, which is causing 2 error popups. Then at the very bottom of the request list there is another devworkspace get request that is successfull. From waterfall in the right, it is visible that failing 2 requests were made while che-server was still provisioning the namespace.

Technically it is not serious issue, because namespace is eventually fully provisioned and dashboard will make successful requests since then. However, it is very user facing.

### Che version

next (development version)

### Steps to reproduce

1. deploy on openshift with devworkspaces enabled
2. login as any user, that does not have namespace created yet
3. error popup is shown after the login
4. It's not shown since then

### Expected behavior

no error popup

### Runtime

OpenShift

### Screenshots

<img width="1440" alt="Screenshot 2021-11-23 at 17 39 41" src="https://user-images.githubusercontent.com/1160903/143066231-06efe8d7-35f8-4e82-8eb8-779ade763cd2.png">

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by olexii4** [comment]
It was fixed in https://github.com/eclipse-che/che-dashboard/pull/418
