### ISSUE TITLE
Dashboard fails with 'updatedLink.startsWith is not a function'

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20827]
### Describe the bug

Try to load a DevWorkspace and we get this message

### Che version

next (development version)

### Steps to reproduce

Try to load a DevWorkspace and we get this message

### Expected behavior

No exception

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by vinokurig** [comment]
Workspace doesn't start, dashboard shows `Waiting for workspace to start` loader, but nothing happens.
