### ISSUE TITLE
Dashboard is not reporting error when requirements are not satisfied

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20821]
### Describe the bug

Try to load a DevWorkspace from the repository https://github.com/benoitf/spring-petclinic/tree/error-cpu

Expect to see workspace booting or reporting an error

Here is what we got: (workspace never reach error or failure state and is not displaying the k8s events)

https://user-images.githubusercontent.com/436777/143206018-d3bd4c61-3b7b-4cee-a90a-5ea2bd515294.mp4

while looking at pod events we can see
```
11m         Normal    SuccessfulDelete         replicaset/workspace26699a51196d4b4c-5cd994b68c   Deleted pod: workspace26699a51196d4b4c-5cd994b68c-8d64g
11m         Normal    ScalingReplicaSet        deployment/workspace26699a51196d4b4c              Scaled down replica set workspace26699a51196d4b4c-5cd994b68c to 0
11m         Warning   FailedCreate             replicaset/workspace26699a51196d4b4c-6d58f65b64   Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-k2n48" is forbidden: maximum cpu usage per Pod is 4, but limit is 6
11m         Warning   FailedCreate             replicaset/workspace26699a51196d4b4c-6d58f65b64   Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-qx89t" is forbidden: maximum cpu usage per Pod is 4, but limit is 6
11m         Warning   FailedCreate             replicaset/workspace26699a51196d4b4c-6d58f65b64   Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-5v2ms" is forbidden: maximum cpu usage per Pod is 4, but limit is 6
11m         Warning   FailedCreate             replicaset/workspace26699a51196d4b4c-6d58f65b64   Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-dxlpm" is forbidden: maximum cpu usage per Pod is 4, but limit is 6
11m         Warning   FailedCreate             replicaset/workspace26699a51196d4b4c-6d58f65b64   Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-dhnq6" is forbidden: maximum cpu usage per Pod is 4, but limit is 6
```

And these logs are not shown in the progress logs

### Che version

next (development version)

### Steps to reproduce

Use a devWorkspace engine and try the link like `https://che-host#https://github.com/benoitf/spring-petclinic/tree/error-cpu`

### Expected behavior

we should see the error at some point
```Error creating: pods "workspace26699a51196d4b4c-6d58f65b64-5v2ms" is forbidden: maximum cpu usage per Pod is 4, but limit is 6```

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
PR sent - https://github.com/devfile/devworkspace-operator/pull/701

**Comment by ibuziuk** [comment]
PR has been merged. Closing
