### ISSUE TITLE
Figure out reasons and fix failing of the HappyPath tests for the CHE dashboard and DWO projects

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse/che#20822]
### Is your task related to a problem? Please describe

After resolving problems with cloud providers for PROW CI:
We get a strange error when we run HappyPath test. For instance: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/23945/rehearse-23945-pull-ci-eclipse-che-che-dashboard-main-v8-dashboard-happy-path/1463444053726072832.
We have 2 problems:
* Sometimes the **htpswd** provider does not appear in the IDP table
* When **htpswd** provider and test user create successfully and we login in as test user using **oc** client - we get strange error on the Login page like **Error creation user**

### Describe the solution you'd like

I can try to reproduce this problem on a similar infra (cluster bot ) and figure out what it is more deeply.

**Comment by rhopp** [comment]
@musienko-maxim Quickly looking at this I see the IDP on the cluster is "htpasswd-eclipse-che" (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/23945/rehearse-23945-pull-ci-eclipse-che-che-dashboard-main-v8-dashboard-happy-path/1463444053726072832/artifacts/dashboard-happy-path/test/artifacts/e2e/Login_test_Login/screenshot-Login.png).
But the tests are expecting `che-htpasswd`

<details>
(from logs):
```
[INFO] Applying the following patched Che Happy Path Pod:
apiVersion: v1
kind: Pod
metadata:
  name: happy-path-che
  namespace: eclipse-che
spec:
  volumes:
    - name: test-run-results
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    # container containing the tests
    - name: happy-path-test
      image: quay.io/eclipse/che-e2e:next
      imagePullPolicy: Always
      env:
        - name: TEST_SUITE
          value: test-devworkspace-happy-path
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: TS_SELENIUM_BASE_URL
          value: http://che-eclipse-che.apps.ci-op-18gpb4bh-6aab1.origin-ci-int-aws.dev.rhcloud.com
        - name: TS_SELENIUM_DEVWORKSPACE_URL
          value: http://che-eclipse-che.apps.ci-op-18gpb4bh-6aab1.origin-ci-int-aws.dev.rhcloud.com/#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
        - name: TS_SELENIUM_MULTIUSER
          value: 'true'
        - name: TS_SELENIUM_LOG_LEVEL
          value: TRACE
        - name: TS_SELENIUM_OCP_USERNAME
          value: 'che-user'
        - name: TS_SELENIUM_OCP_PASSWORD
          value: "user"
        - name: TS_SELENIUM_VALUE_OPENSHIFT_OAUTH
          value: 'true'
        - name: TS_SELENIUM_USERNAME
          value: "admin"
        - name: TS_SELENIUM_PASSWORD
          value: 'admin'
        - name: TS_OCP_LOGIN_PAGE_PROVIDER_TITLE
          value: "che-htpasswd"
        - name: DELETE_WORKSPACE_ON_FAILED_TEST
          value: "true"
        - name: TS_SELENIUM_START_WORKSPACE_TIMEOUT
          value: '540000'
        - name: TS_IDE_LOAD_TIMEOUT
          value: '40000'
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          memory: "3Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
    # Download results    
    - name: download-reports
      image: quay.io/eclipse/che-e2e:next
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
```
</details>

**Comment by musienko-maxim** [comment]
> @musienko-maxim Quickly looking at this I see the IDP on the cluster is "htpasswd-eclipse-che" (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/23945/rehearse-23945-pull-ci-eclipse-che-che-dashboard-main-v8-dashboard-happy-path/1463444053726072832/artifacts/dashboard-happy-path/test/artifacts/e2e/Login_test_Login/screenshot-Login.png). But the tests are expecting `che-htpasswd`
> 
> (from logs): ``` [INFO] Applying the following patched Che Happy Path Pod: apiVersion: v1 kind: Pod metadata: name: happy-path-che namespace: eclipse-che spec: volumes: - name: test-run-results - name: dshm emptyDir: medium: Memory containers: # container containing the tests - name: happy-path-test image: quay.io/eclipse/che-e2e:next imagePullPolicy: Always env: - name: TEST_SUITE value: test-devworkspace-happy-path - name: NODE_TLS_REJECT_UNAUTHORIZED value: '0' - name: TS_SELENIUM_BASE_URL value: http://che-eclipse-che.apps.ci-op-18gpb4bh-6aab1.origin-ci-int-aws.dev.rhcloud.com - name: TS_SELENIUM_DEVWORKSPACE_URL value: http://che-eclipse-che.apps.ci-op-18gpb4bh-6aab1.origin-ci-int-aws.dev.rhcloud.com/#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 - name: TS_SELENIUM_MULTIUSER value: 'true' - name: TS_SELENIUM_LOG_LEVEL value: TRACE - name: TS_SELENIUM_OCP_USERNAME value: 'che-user' - name: TS_SELENIUM_OCP_PASSWORD value: "user" - name: TS_SELENIUM_VALUE_OPENSHIFT_OAUTH value: 'true' - name: TS_SELENIUM_USERNAME value: "admin" - name: TS_SELENIUM_PASSWORD value: 'admin' - name: TS_OCP_LOGIN_PAGE_PROVIDER_TITLE value: "che-htpasswd" - name: DELETE_WORKSPACE_ON_FAILED_TEST value: "true" - name: TS_SELENIUM_START_WORKSPACE_TIMEOUT value: '540000' - name: TS_IDE_LOAD_TIMEOUT value: '40000' volumeMounts: - name: test-run-results mountPath: /tmp/e2e/report/ - mountPath: /dev/shm name: dshm resources: requests: memory: "3Gi" cpu: "2" limits: memory: "4Gi" cpu: "2" # Download results - name: download-reports image: quay.io/eclipse/che-e2e:next imagePullPolicy: IfNotPresent volumeMounts: - name: test-run-results mountPath: /tmp/e2e/report/ command: ["sh"] args: [ "-c", "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done", ] restartPolicy: Never ```

**Comment by musienko-maxim** [comment]
Thx, Radim for your comment. I see, so looks like IDP item can appear with some delays. For accelerating this for the test I am going to try rollout **oauth-openshift ** deployment. I hope it should help. I tried it several times it worked. So I've just added this to the script. Just make sure that it does not break the main test flow. After this I'll create PR

**Comment by musienko-maxim** [comment]
Fixe in the PR: https://github.com/eclipse/che/pull/20903
