### ISSUE TITLE
[devfile-registry] The content of meta.yaml is in JSON format

### ISSUE THREAD

**Issue by svor** [eclipse/che#20828]
### Describe the bug

If we check the content of meta.yaml, its content is in JSON format:
```
bash-5.0# ls
devfile.yaml  devworkspace-che-theia-latest.yaml  devworkspace-che-theia-next.yaml  meta.yaml
bash-5.0# cat meta.yaml 
{
  "displayName": "Go",
  "description": "Stack with Go 1.14",
  "tags": [
    "Debian",
    "Go"
  ],
  "icon": "/images/go.svg",
  "links": {
    "v2": "https://github.com/che-samples/golang-echo-example/tree/devfile2",
    "self": "/devfiles/go/devfile.yaml",
    "devWorkspaces": {
      "eclipse/che-theia/latest": "/devfiles/go/devworkspace-che-theia-latest.yaml",
      "eclipse/che-theia/next": "/devfiles/go/devworkspace-che-theia-next.yaml"
    }
  }
}

``` 

### Che version

next (development version)

### Steps to reproduce

Open any meta.yaml file in the devfile folder

### Expected behavior

It should be in yaml format

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by nickboldt** [comment]
good news is that you can open a json file and dump it to yaml with yq

``
yq -y . < /tmp/meta.json.yaml > /tmp/meta.actual.yaml
```

**Comment by svor** [comment]
@nickboldt  thanks, should be a quick fix

**Comment by benoitf** [comment]
well, it's just that when we're calling yq, by default yq output to json rather than yaml
