### ISSUE TITLE
Provide documentation for enabling DevWorkspace telemetry and update existing docs

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#20820]
### Is your task related to a problem? Please describe

There is documentation for enabling telemetry and developing a telemetry plugin for workspaces created from the Che-server engine, but none for DevWorkspaces.

### Describe the solution you'd like

After https://github.com/eclipse/che/issues/20090 is complete, it would be great if the [creating a telemetry plugin](https://www.eclipse.org/che/docs/che-7/extensions/creating-a-telemetry-plugin/) section from the docs was updated to explain how to integrate a telemetry plugin to work with DevWorkspaces. 

In addition, it would be great if:
* the existing docs were updated to include a sample telemetry plugin GitHub project. The docs provide a sample implementation for the abstract methods, but not a full project example. This would help bring more clarity to the docs, for both DevWorkspace telemetry and Che-server workspace telemetry.
* this [section](https://www.eclipse.org/che/docs/che-7/extensions/creating-a-telemetry-plugin/#_packaging_the_quarkus_application) is updated to provide more details for packaging the plugin

**Comment by ibuziuk** [comment]
The issue can be closed once https://github.com/eclipse-che/che-docs/pull/2231 is merged
