### ISSUE TITLE
On prem private Gitlab repositores support with OAuth2 flow (without Keycloak)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20831]
### Is your task related to a problem? Please describe

Today Gitlab private factories that are required OAuth2 authorization are redirected to keycloak.
However, in devworkspaces keycloak is no longer a mandatory infrastructure element. 

### Describe the solution you'd like

OAuth2 configuration should be mounted as a file https://github.com/eclipse/che/issues/20496.
Embedded OAuth2 integration should be configured and used.

### Additional context

 - https://github.com/eclipse/che/issues/20497
 -  https://github.com/eclipse-che/che-server/pull/185

### Release notes text

Workspaces started using the DevWorkspace engine now support on premise private Gitlab repositories. On premise private Bitbucket and github.com private repositories were already supported.

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by l0rd** [comment]
@skabashnyuk can we close this issue or is there something to finish (like Gitlab SAAS support)?

**Comment by skabashnyuk** [comment]
I think we can close this. Gitlab SAAS most likely should be a different task. It was not in the scope of this one.
