### ISSUE TITLE
Support customizing the PVC size for internal PostgreSQL instance

### ISSUE THREAD

**Issue by gaocegege** [eclipse/che#20837]
### Is your enhancement related to a problem? Please describe

No

### Describe the solution you'd like

Now we hard-coded the PVC requests to 1Gi. It is better to support the custom size.

https://github.com/eclipse-che/che-operator/blob/b4930b5054c0bb951e8b3fcd5ab859a8eb671c7e/pkg/deploy/postgres/postgres.go#L78

I expect that the value should be configurable.

### Release Notes Text

`CheCluster` CR now has a `database.pvcClaimSize` field where administrators can specify a custom value for the database persistent volume. This is important because some public cloud providers' cloud disk does not support 1Gi, the minimum storage size is 10Gi.

**Comment by gaocegege** [comment]
https://github.com/eclipse-che/che-operator/issues/1193

**Comment by tolusha** [comment]
Hi.
That's not a big deal to make it configurable. 
But could you describe a case when pvc 1Gi is not enough for PostgreSQL data?
Would it help you `spec.storage.pvcClaimSize` to configure pvc size for workspace data.

**Comment by gaocegege** [comment]
> But could you describe a case when pvc 1Gi is not enough for PostgreSQL data?

Some public cloud providers' cloud disk does not support 1Gi. The minimum storage size is 10Gi. Thus the PVC cannot be provisioned successfully.

**Comment by tolusha** [comment]
I see. Thank you!

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2548
