### ISSUE TITLE
Adapt PR check Happy path and nightly tests on CRW Jenkins CI to be run against Eclipse Che with DW enabled by default

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#20838]
### Is your task related to a problem? Please describe

There is a plan to have DW enabled by default in Eclipse Che 7.41.0: https://github.com/eclipse/che/milestone/140

### Describe the solution you'd like

We need to reflect the changes in Eclipse Che E2E testing pipelines on CRW Jenkins CI:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/

DevWorkspace Happy Path tests pipeline: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/devworkspace/

Test script branch: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/tree/che-20838

### Additional context

Blocked by: 
- https://github.com/eclipse/che/issues/20969
- https://github.com/eclipse/che/issues/20973
- https://github.com/eclipse/che/issues/20986
- https://github.com/eclipse/che/issues/20663

**Comment by benoitf** [comment]
@dmytro-ndp 7.41.0 release will be cut tomorrow. This issue is not yet closed, so please close it if it's done or move it to 7.42

**Comment by dmytro-ndp** [comment]
@benoitf: thanks for reminding!

**Comment by dmytro-ndp** [comment]
I am closing the issue as rejected, because it's not possible to use CRW Jenkins after chectl stopped supporting minikube run with driver 'none' mode (https://github.com/eclipse/che/issues/20969).
