### ISSUE TITLE
Failure to fetch available workspaces the first time login in and open Che dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20833]
### Describe the bug

DevWorkspace is enabled. The first time I open the Dashboard after a fresh deployment of Che the following 2 error messages are shown.

### Che version

next (development version)

### Steps to reproduce

Deploy Che with DevWorkspace enabled, login and open the dashboard 

### Expected behavior

No error message should appear

### Runtime

OpenShift

### Screenshots

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/606959/143499309-c1d58e8a-a8b1-4bb4-a166-eadb402a3e68.png">

### Installation method

chectl/next

### Environment

Amazon

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/20819 ?

**Comment by sparkoo** [comment]
> Duplicate #20819 ?

Yes, looks like same issue. I'm closing this one as in #20819 there is also analysis of the issue.

**Comment by l0rd** [comment]
👍 thanks @skabashnyuk @sparkoo
