### ISSUE TITLE
[Dev-Workspace] Workspace doesn't start with a timeout error

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20844]
### Describe the bug

Workspace doesn't start in Che wit the latest Dev Workspace Operator.

### Che version

7.39@latest

### Steps to reproduce

1. Start Che with DWO: `chectl server:deploy --installer=operator --platform=minikube --workspace-engine=dev-workspace`
2. Apply the latest DWO: Go to the `devworkspace-operator` project and run `make install`
3. Start any workspace.

See: workspace doesn't start

### Expected behavior

Workspace must start successfully

### Runtime

minikube

### Screenshots

![screenshot-192 168 64 97 nip io-2021 11 30-12_29_54](https://user-images.githubusercontent.com/7668752/144031809-faddc551-91c9-4973-ad52-3932ebe7abb2.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by ibuziuk** [comment]
@vinokurig could you please provide openshift events?

**Comment by vinokurig** [comment]
I can't get any events from my minikube except some DWO logs:
```
{"level":"info","ts":1638268049.2181156,"logger":"controllers.DevWorkspace","msg":"Error updating workspace status: Operation cannot be fulfilled on devworkspaces.workspace.devfile.io \"golang-echo-example-bfk4\": the object has been modified; please apply your changes to the latest version and try again","Request.Namespace":"admin-che","Request.Name":"golang-echo-example-bfk4","devworkspace_id":"workspace94d777ee003e4c2a"}
{"level":"error","ts":1638268049.218193,"logger":"controller-runtime.manager.controller.devworkspace","msg":"Reconciler error","reconciler group":"workspace.devfile.io","reconciler kind":"DevWorkspace","name":"golang-echo-example-bfk4","namespace":"admin-che","error":"Operation cannot be fulfilled on devworkspaces.workspace.devfile.io \"golang-echo-example-bfk4\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
```

**Comment by JPinkney** [comment]
https://github.com/eclipse-che/che-operator/pull/1207 should fix this

**Comment by ibuziuk** [comment]
@JPinkney can we close the issue?

**Comment by JPinkney** [comment]
Technically yes, it depends on our definition of done :wink:. It's done from devworkspace operator side but eclipse che users won't be able to having a working devworkspace until 0.11 is released in January

**Comment by ibuziuk** [comment]
sounds good, let's close it once 0.11.0 is released :+1:

**Comment by amisevsk** [comment]
v0.11 is shipped, this issue can be closed.
