### ISSUE TITLE
[che-auth] document native user auth

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20847]
### Is your task related to a problem? Please describe

We've done many changes how authentication and authorization works now in Che with DevWorkspaces.

### Describe the solution you'd like

 - Review current documentation and make it up to date
 - Describe how auth works on Kubernetes and how to customize it (connect to github)
 - Describe current routing architecture (oauth-proxy, kube-rbac-proxy, traefik) - blogpost?

**Comment by benoitf** [comment]
@skabashnyuk  7.41.0 release will be cut tomorrow. This issue is not yet closed, so please close it if it's done or move it to 7.42

**Comment by sparkoo** [comment]
merged
