### ISSUE TITLE
NodeJS library to convert devfiles from v1 to v2 and viceversa

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20843]
### Is your task related to a problem? Please describe

For now it's used in che-theia and dashboard.
It should be moved out to a separate repository and be a 3rd party library

### Describe the solution you'd like

move it out and publish it

### Release Notes Text

We introduced a new Devfile conversion library https://www.npmjs.com/package/@eclipse-che/devfile-converter. Che Dashboard uses it. It can be included in any nodeJS project that requires it.

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2547
