### ISSUE TITLE
Rework developers images to make them compatible with Red Hat internal image build tool (aka brew)

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20858]
### Is your enhancement related to a problem? Please describe

Che samples devfiles use the [universal developer image](https://github.com/devfile/developer-images/). The image is built with 2 Dockerfiles ([base](https://github.com/devfile/developer-images/blob/main/base/ubi8/Dockerfile), [universal](https://github.com/devfile/developer-images/blob/main/universal/ubi8/Dockerfile)) that have invalid instructions for Red Hat CI:

- `RUN curl` instructions are not possible (what if the dependency gets removed from the website? Brew builds are offline, with no direct internet access to fetch tarballs, zips, go/node/pip dependencies, etc.)
- [Heredocs in Dockerfiles](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/) may not be supported

### Describe the solution you'd like

0) remove heredocs in Dockerfiles, since current dockerfiles use a mix of both heredoc and `&&` syntax already
1) add a `get-sources.sh` script that pre-downloads assets into the local folder and renames them to `asset-*` - see examples in https://github.com/redhat-developer/codeready-workspaces-images/
2) replace `RUN curl` with `COPY asset-*` instructions
3) extract hardcoded versions nested in heredoc scripts to a list of ENVs near the top of the file, so they're easier to keep current
4) remove hardcoded `ARCH="linux_amd64"`, `ARCH="x86_64-unknown-linux-musl"`, and `ARCH="Linux-x86_64"` declarations and compute these from `uname -m` (switching between x86_64 and amd64 as appropriate); this will allow multiarch builds in brew
5) `maintainer` should be an actual person's name + email address (or comma-separated list of more than one), not just a company. See https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-idea/Dockerfile#L112
6a) provide a transformation script that can remove registry references from `FROM` lines, leaving only `FROM org/image:tag ...` or `FROM org/image@digest ...`
6b) if anything is being installed via RPM from EPEL or Fedora, provide .repo files to enable this installation that can be disabled downstream in Brew (not allowed) via the transformation script

**Comment by nickboldt** [comment]
@l0rd see https://issues.redhat.com/browse/CRW-2459 for future work to make it easier to consume CRW dockerfiles outside of brew process. That will give you some insights into what differences there are between public online dockerfiles and Brew internal offline dockerfiles. 

the other thing we can now do in downstream vs. upstream is to use cachito to manage go, python, and node dependencies. See https://issues.redhat.com/browse/CRW-2444
