### ISSUE TITLE
Support v2.2 Devfiles

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20850]
### Is your enhancement related to a problem? Please describe

The OpenShift Developer Console will include some new examples that have Devfiles withouth [placeholder outerloop component](https://github.com/devfile/api/issues/666). But those Devfiles will use v2.2 of the spec.

Trying to start a workspace from this repo https://github.com/devfile-samples/devfile-sample-java-springboot-basic, on che next with devworkspace enabled, I faced the following problems:

1. Components of type `image` is considered invalid
2. Command `build-image` references the component of type `image` that is not supported
3. Commands of type `composite` are not supported
4. `mvn` commands fail because the default `workingDir` is `/projects`
5. (Related but not a problem with the devfile above): special variable `$PROJECT_SOURCE` is not supported

### Describe the solution you'd like

- [ ] When DevWorkspace is **enabled**:

1. DevWorkspace supports `image` components ignoring them
2. DevWorkspace ignores commands associated to `image` components
3. DevWorkspace supports `composite` commands
4. DevWorkspace sets default working directory to first project folder (not `/projects/`)
5. DevWorkspace supports `PROJECT_SOURCE` (not `PROJECTS_SOURCE`)
6. DevWorkspace ignores [placeholder outerloop component](https://github.com/devfile/api/issues/666)

- [x] When DevWorkspace is **disabled** https://github.com/eclipse/che/issues/20856

1. Devfile converter removes any `image` components during conversion
2. Devfile converter removes commands associated to `image` components
3. Devfile converter removes `composite` commands
4. Devfile converter sets default working directory to first project folder (not `/projects/`)
5. Devfile converter replaces `PROJECT_SOURCE` with the path to the first project `/projects/`
6. Devfile converter removes [placeholder outerloop component](https://github.com/devfile/api/issues/666)

**Comment by l0rd** [comment]
Created this PR https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/2 to fix some issues with https://github.com/devfile-samples/devfile-sample-java-springboot-basic

**Comment by amisevsk** [comment]
One issue that has to be resolved first is that currently `devfile/api` versions have removed v1alpha1 DevWorkspaces. However, there are still some users of DevWorkspaces that depend on this API version, so DWO must continue to ship conversion webhooks for the time being. We need to consider reverting https://github.com/devfile/api/pull/639

**Comment by benoitf** [comment]
part of che-server workspaces has been implemented and merged

**Comment by benoitf** [comment]
removed `area/devfile-converter` as this action has been done
