### ISSUE TITLE
[che-auth] default enable native auth on kubernetes with devworkspaces

### ISSUE THREAD

**Issue by sparkoo** [eclipse/che#20853]
### Is your enhancement related to a problem? Please describe

Once native authentication is implemented on kubernetes, we should enable it by default when devworkspaces are enabled. This is last piece missing https://github.com/eclipse-che/che-operator/pull/1185 but to enable native auth, one must pass CheCluster patch with `nativeUserMode:true` set.

### Describe the solution you'd like

enable native auth by default on kubernetes when devworkspaces enabled

It is not as trivial as simply setting one property. We need to deploy Dex on minikube first, which is now triggered with the `nativeUserMode` in CheCluster patch. However for similar job on OpenShift, the logic to use native auth by default is in che-operator. But che-operator is not available in the moment we need to deploy Dex.

### Additional context

https://github.com/eclipse-che/che-operator/pull/1185
https://github.com/eclipse/che/issues/20635
epic: https://github.com/eclipse/che/issues/19182

**Comment by tolusha** [comment]
Did I understand correctly that operator is supposed to deploy Dex once `nativeUserMode` is enabled?

**Comment by sparkoo** [comment]
> Did I understand correctly that operator is supposed to deploy Dex once `nativeUserMode` is enabled?

The goal is to enable `nativeUserMode` without the need of any checluster patch when you deploy on minikube with devworkspaces and we need Dex for that.

I'm only saying that on openshift, we're doing this logic in che-operator. However, here with dex it is more complicated and it will probably have to be in chectl as well. You better know how and where to implement that.

**Comment by tolusha** [comment]
I see. Then it is chectl task to create checluster with `devworkspace: enable` and it is relatively easy.

**Comment by tolusha** [comment]
Should it be done before https://github.com/eclipse-che/che-operator/pull/1185 ?

**Comment by sparkoo** [comment]
> Should it be done before [eclipse-che/che-operator#1185](https://github.com/eclipse-che/che-operator/pull/1185) is merged?

no. It should be done after because it would break default deployment without that patch
