### ISSUE TITLE
Che restore not possible when using own keycloak (and own database

### ISSUE THREAD

**Issue by pyrefrac16** [eclipse/che#20851]
### Describe the bug

The chectl server:restore is stuck in the "Restore Che database" step.

### Che version

7.39@latest

### Steps to reproduce

I have a che setup where I use an external keycloak and an own database. Regarding the logs (see below) this may have an impact on my current problem.

I use the operator installation.
```
...
spec:
  database:
    externalDb: true
...
  auth:
    externalIdentityProvider: true
...
```

1. I created a backup using
`chectl server:backup -r "s3:....." -p ******* --aws-access-key-id=******** --aws-secret-access-key=*********`

2. When I try to restore
`chectl server:restore -r "s3:....." -p ******* --aws-access-key-id=******** --aws-secret-access-key=********* --snapshot-id=xxxxxxx`

the restore never finishes. It is stuck in the "Restoring Che database" step as you can see below:
› Current Kubernetes context: 'xxxxxxxxxxxxxx'
  ✔ Verify Kubernetes API...OK
  ✔ Detecting existing operator version... 7.39.2 found
  ✔ Detecting installer...Operator
  ✔ Getting backup server info...OK
  ✔ Print restore information
    ✔ Current version:   7.39.2
    ✔ Restore version:   7.39.2
    ✔ Backup server:     xx.xxxxxx.xxx
    ✔ Backup repository: bucket
    ✔ Snapshot:          xxxxxxxxxxxxxxxxxxxxx
  ✔ Asking for restore confirmation...OK
  ✔ Scheduling restore...OK
  ⠴ Waiting until restore process finishes: Restoring Che database

In the log of the operator I find the log as shown in "Eclipse Che Log" below.

There are no log entries for the restore in the chectl log (/.cache/chectl/error.log)

### Expected behavior

The restore should restore the che 

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Azure

### Eclipse Che Logs

```shell
time="2021-11-30T19:10:21Z" level=info msg="Restore: Waiting for Che to be ready"
time="2021-11-30T19:10:24Z" level=info msg="Eclipse Che is now available at: "
time="2021-11-30T19:10:24Z" level=info msg="Custom resource status eclipse-che updated with status: Che API: Available"
time="2021-11-30T19:10:24Z" level=info msg="Custom resource status eclipse-che updated with che server URL: https://xxxxxx.xxx"
time="2021-11-30T19:10:24Z" level=info msg="Custom resource status eclipse-che updated with version: 7.39.2"
time="2021-11-30T19:10:24Z" level=info msg="Successfully reconciled."
time="2021-11-30T19:10:26Z" level=info msg="Status updated with {Restore is in progress. Start time: 2021-11-30 19:08:52.443320431 +0000 UTC m=+4617.940412180 Restoring Che database InProgress}: "
time="2021-11-30T19:10:26Z" level=error msg="Failed to find pod for component keycloak. List of pods: []"
time="2021-11-30T19:10:26Z" level=error msg="resource name may not be empty"
2021-11-30T19:10:26.115Z        ERROR   controller-runtime.manager.controller.checlusterrestore-controller      Reconciler error        {"reconciler group": "org.eclipse.che", "reconciler kind": "CheClusterRestore", "name": "eclipse-che-restore", "namespace": "eclipse-che", "error": "resource name may not be empty"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214
time="2021-11-30T19:10:26Z" level=error msg="Failed to find pod for component keycloak. List of pods: []"
time="2021-11-30T19:10:26Z" level=error msg="resource name may not be empty"
```

### Additional context

I am using an Azure Kubernetes (AKS)

Installation of che:
chectl server:deploy --batch --platform=k8s --domain=xxxxxxx.xxx --installer=operator --multiuser --che-operator-cr-patch-yaml=...

**Comment by tolusha** [comment]
WON'T FIX
Backup/Restore is flaky and doesn't works with DevWorkspace
Decommissioned by https://github.com/eclipse/che/issues/21006
