### ISSUE TITLE
Automatic connection to the OpenShift cluster when using the OpenShift connector (no need to login for the user anymore)

### ISSUE THREAD

**Issue by svor** [eclipse/che#20857]
When devWorksapce is enabled, the k8s configuration file should be injected into each container - https://github.com/eclipse/che/issues/20782. 

So, in devWorkspace we don't need [openshift-authentication-plugin](https://github.com/che-incubator/che-theia-openshift-auth) to login into the cluster.

When devWorkspace engine is enabled, we have to provide another che plugin **vscode-openshift-connector**  without **che-openshift-authentication-plugin**:  https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L361-L379

### Releases Notes Text

Users OpenShift connection token gets automatically injected in the workspace pods as startup and the OpenShift Connector VS Code extension leverages that now. This was already working with the Che server and we have aligned the DevWorkspace based workspaces too.

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by svor** [comment]
.kube/config file was injected into containers, tested on OpenShift:

![screenshot-che-eclipse-che apps ci-ln-mz81l9b-72292 origin-ci-int-gce dev rhcloud com-2022 01 12-11_24_38](https://user-images.githubusercontent.com/1271546/149102840-351e557d-cdf4-4fae-9248-5799f40d5134.png)

**Comment by svor** [comment]
I've created follow up issue for CRW: https://issues.redhat.com/browse/CRW-2640
