### ISSUE TITLE
OperatorHub stable channel must use "all-namespace" install mode

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20866]
### Is your task related to a problem? Please describe

OperatorHub stable channel must use "all-namespace" install mode.

### Describe the solution you'd like

- [x] Set allNamespaces install mode for a stable channel.
- [x] Drop `tech-preview` channels
- [ ] Provide migration guide from single to all namespaces mode
- [x] Adopt chectl
- [x] Adopt CI

### Additional context

[1] https://github.com/eclipse/che/issues/20668

**Comment by l0rd** [comment]
@tolusha I think this morning we discussed that it may not be possible to publish "all-namespace" mode AND [avoid automatic updates](https://github.com/eclipse/che/issues/20865). If that's confirmed we should just stop publishing new releases on OperatorHub.

**Comment by tolusha** [comment]
I've just checked. OLM doesn't allow to update from single namespace to all namespace mode

`OwnNamespace InstallModeType not supported, cannot configure to watch own namespace`

**Comment by tolusha** [comment]
@l0rd 
So, we can publish new releases on OperatorHub for a stable channel with allNamespace install mode.
Should we remove `tech-preview` channel ?

**Comment by l0rd** [comment]
@tolusha 👍 to remove `tech-preview` channel

**Comment by l0rd** [comment]
@tolusha do you plan to complete that in 7.42 rigth? I am asking to know if we can include that in the 7.42 release notes

**Comment by Kasturi1820** [comment]
Release Note text 
The stable channel of Che operator has the DevWorkspace enabled by default and use the operator "all-namespace" installation mode. The other channels are being deleted.

**Comment by tolusha** [comment]
For last two items I have corresponding PRs. So, yes I plan it for 7.42
- https://github.com/eclipse/che-docs/pull/2159
- https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/601

**Comment by tolusha** [comment]
There is the only one channel right now:

![screenshot-console-openshift-console apps ci-ln-5dknrct-72292 origin-ci-int-gce dev rhcloud com-2022 01 12-12_15_05](https://user-images.githubusercontent.com/1640675/149121219-35e3038d-77c3-4667-a5e2-59770f2a8cb7.png)

I mark this issue as resolved. Doc will be tracked separately.

**Comment by max-cx** [comment]
sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-2646
