### ISSUE TITLE
20+ seconds faster Che-Theia startup

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#20861]
### Describe the bug

It takes about 10 sec. after Che-Theia is loaded to the browser and before the project tree is rendered.

### Che version

next (development version)

### Steps to reproduce

Start a new workspace with the following factory URL:
`<che-host>#https://github.com/l0rd/spring-petclinic?devfilePath=.devfilev2.yaml`

It takes about 10 sec. before the project tree is rendered. During that time the tree is empty. However, the project sources are already cloned.

### Expected behavior

The projects tree should be rendered as soon as Che-Theia page is loaded to the browser.

### Runtime

OpenShift

### Screenshots

![Peek 2021-12-01 14-00](https://user-images.githubusercontent.com/1636395/144231031-170091d7-1ff9-41ed-8424-8f63296c078d.gif)

### Installation method

OperatorHub

### Environment

Linux

### Release Notes Text

The previous DevWorkspace based Che-Theia used to take more than 20 seconds to load due to some blocking built-in plugins startup. The built-in plugins are not blocking the main Theia process startup anymore.

**Comment by RomanNikitenko** [comment]
I detected that we have the delay at `sync plugins` step. It's actual for the dev workspace mode only.
Looking for a cause of the problem...

**Comment by benoitf** [comment]
@azatsarynnyy 7.41.0 release will be cut tomorrow. This issue is not yet closed, so please close it if it's done or move it to 7.42

**Comment by RomanNikitenko** [comment]
I had a quite long vacation, will come back to the issue today/tomorrow...

**Comment by RomanNikitenko** [comment]
I detected that the system hangs on `getDeployedPluginIds` step.
It looks like frontend waits for the backend at that step:

<img width="943" alt="Screenshot 2022-01-21 at 14 00 43" src="https://user-images.githubusercontent.com/5676062/150525329-9090b737-ca72-434c-959d-3989462826aa.png">

I investigated the problem using `minikube` locally on my machine. As you can see the delay for my machine is about 40 seconds.

Finally, I found that we are waiting for unpacking `che-theia` plugins at that delay.
The plugins are unpacked in parallel, but it takes about 30 seconds (in my environment) to unpack some of them.

I tried to put already unpacked `che-theia` plugins to the corresponding image and added an entity (like [PluginTheiaFileHandler](https://github.com/eclipse-theia/theia/blob/c56aa230fe50f20b598b2b4c4273cad4486b4750/packages/plugin-ext/src/main/node/handlers/plugin-theia-file-handler.ts#L37)) which handles them.
You can see the difference for my environment on the videos bellow.

Behaviour for **packed** `che-theia` plugins, so `main` branch without any changes 

https://user-images.githubusercontent.com/5676062/150526807-e48eaf9b-e745-4bc8-b30c-4f7fff2e7a64.mp4

Behaviour for **unpacked** `che-theia` plugins, so with my changes - plugins are unpacked at building images step

https://user-images.githubusercontent.com/5676062/150527271-da98d824-44e5-44a9-8be5-b72741481d73.mp4

**Comment by azatsarynnyy** [comment]
@l0rd actually, it's > 20 sec. faster for hosted Che instance
and > 30 sec. for the local minikube installation

just FYI :slightly_smiling_face:

**Comment by l0rd** [comment]
@azatsarynnyy thanks. I have updated the title and the[ release notes](https://github.com/eclipse/che/releases/tag/7.43.0).
