### ISSUE TITLE
Rework Che-IDEA image to sidecar-less model

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#20863]
### Is your task related to a problem? Please describe

There's a new workspace model a.k.a. "sidecar-less" - https://github.com/eclipse/che/issues/20435
We need to support it in our Che-IDEA editor.

#### How should it work?
The user's Devfile includes a [UDI-based](https://github.com/devfile/developer-images/) container, e.g.:
https://github.com/che-samples/java-guestbook/blob/b1561506771419c61ea81b1c8603fb6c20ddfcc2/devfile.yaml#L7

The editor's Devfile includes an init-container that copies the editor from the init-container to a mounted volume, e.g.:
https://github.com/eclipse-che/che-plugin-registry/blob/7bb4f565ffc10a83712040ea12ee71f31ed099bd/che-editors.yaml#L573
https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-init-container.sh

Then, the editor is launched in the user's UDI-based container, e.g.:
https://github.com/eclipse-che/che-plugin-registry/blob/7bb4f565ffc10a83712040ea12ee71f31ed099bd/che-editors.yaml#L592
https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh

### Describe the solution you'd like
At first, we need to check if the Projector-based IDEA can be run in a UBI container.

Then, we can try with a similar solution that is used in Che-Code:
https://github.com/eclipse-che/che-plugin-registry/blob/7bb4f565ffc10a83712040ea12ee71f31ed099bd/che-editors.yaml#L552-L612
https://github.com/che-incubator/che-code/tree/main/build

### Additional context

The issue is a part of the epic https://github.com/eclipse/che/issues/20591

**Comment by benoitf** [comment]
@azatsarynnyy 7.41.0 release will be cut tomorrow. This issue is not yet closed, so please close it if it's done or move it to 7.42

**Comment by azatsarynnyy** [comment]
Done by https://github.com/che-incubator/jetbrains-editor-images/pull/70
