### ISSUE TITLE
Directly Open the project without including all the workspace

### ISSUE THREAD

**Issue by kvermacalibo** [eclipse/che#20872]
### Is your enhancement related to a problem? Please describe

When I open the single workspace, then rest of the workspaces still visible.
'domain_named/dashboard/#/ide/user_id/workspace' shows all the workspaces under the same user.

### Describe the solution you'd like

Only show respective workspace, when 'domain_named/dashboard/#/ide/user_id/workspace' will call.

**Comment by l0rd** [comment]
@kvermacalibo thank you for your feedback. I am afraid we do not have enough information to help you though. Can you please provide a more detailed explanation. 

Please include some logs and screenshot and let us know how:
- what are you trying to achieve and why
- the instructions you have followed to install Che
- what version of Che you are using
- what version of Kubernetes you are using
- A list of steps to reproduce your problem

Thank you!

**Comment by kvermacalibo** [comment]
@l0rd Sorry for late reply. Thank you for responding.
- I implemented the create workspace APIs, and when I am opening the eclipse che workspace, then other created workspaces also display in left side menu in dashboard.
- It is not an issue, just want to confirm, is there any API which can directly open the workspace without redirecting to dashboard.
- Using eclipse che Theia.

It is good to have feature for us, Not a blocker. So, I can close the ticket, if we do not have any individual API for workspace.

**Comment by l0rd** [comment]
@kvermacalibo the che-server exposes a worksapce API. You can have a look at https://workspaces.openshift.com/swagger

But that API is going to be deprecated in ~1 month. We are switching to the DevWorkspace (see [epic](https://github.com/eclipse/che/issues/17307) and [first blog post](https://che.eclipseprojects.io/2021/10/12/@mario.loriedo-devfile-v2-and-the-devworkspace-operator-p1.html)). If you deploy Che with DevWorkspace enabled (`chectl server:deploy --workspace-engine=dev-workspace --platform=<your-platform>`) then you will be able to use the Kubernetes API to list/read/update/delete workspaces (using `kubectl` for example).
