### ISSUE TITLE
unable to edit DevWorkspace in dashboard 

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20889]
### Describe the bug

I've the error
```
Matches multiple schemas when only one must validate.yaml-schema: inmemory:yaml
```

If I switch to 2.0.0 or 2.2.0 it works

### Che version

next (development version)

### Steps to reproduce

I clicked on `http://<che-server>#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=che-incubator/che-code/insiders`

Then I tried to edit the devfile

### Expected behavior

Be able to edit the DevWorkspace

### Runtime

OpenShift

### Screenshots

https://user-images.githubusercontent.com/436777/144858554-55f448f8-cc37-4858-964f-90f9cb962bd6.mp4

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy folks, could you please take a look at what happened with 2.1.0 support?
