### ISSUE TITLE
Should display latest releases in github releases section

### ISSUE THREAD

**Issue by sunix** [eclipse/che#20887]
### Is your task related to a problem? Please describe

in Github, Eclipse Che releases stopped showing the latest release. Last one seemed to be May 19 2021 as the latest which is not right.
![image](https://user-images.githubusercontent.com/650571/144850808-783f6b0f-a467-42bc-9906-c383546ad375.png)

### Describe the solution you'd like

should show the latest

**Comment by nickboldt** [comment]
Technically speaking, it IS showing the latest. :) 

The actual problem is that the release process is no longer CREATING releases every week.

**Comment by nickboldt** [comment]
Appears that this was a consequence of moving release-changelog.yml from ecllipse/che to eclipse-che/che-server.

https://github.com/eclipse-che/che-server/releases

**Comment by nickboldt** [comment]
See https://github.com/eclipse-che/che-server/pull/190 and https://github.com/eclipse/che/pull/20890

**Comment by nickboldt** [comment]
![image](https://user-images.githubusercontent.com/227597/144876350-c5ec6e52-c72b-42f8-b6af-79f2da836aef.png)
