### ISSUE TITLE
[resource-monitor] CPU values have wrong presentation

### ISSUE THREAD

**Issue by svor** [eclipse/che#20895]
### Describe the bug

Metrics server provides the value of used CPU in nanocores (nanoCPU) but the Resource Monitor displays this value with **m**  (millicores/milliCPU)

### Che version

next (development version)

### Steps to reproduce

1. Start the workspace
2. Click on the Resource Monitor on the status bar 

### Expected behavior

The value provided by Metrics server should be converted to milliCPU

### Runtime

OpenShift

### Screenshots

![screenshot-nimbus-capture-2021 12 07-14_49_12](https://user-images.githubusercontent.com/1271546/145034020-b1f42ae5-ff8a-4f17-8497-a1dcd4483fb3.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by l0rd** [comment]
@svor I am moving to next release

**Comment by vitaliy-guliy** [comment]
Works fine on dogfooding instance in both che-theia and che-code

![Screenshot from 2022-05-25 16-33-47](https://user-images.githubusercontent.com/1655894/170289174-f4c5a0fa-fe81-48cd-b0a6-803fb7c053c8.png)
