### ISSUE TITLE
Starting a workspace from a repository without devfile is not adding/cloning the project

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20893]
### Describe the bug

Starts with the link `http://che-server#https://github.com/spring-projects/spring-petclinic` on a DevWorkspaces enabled che instance

I expect to see spring-petclinic sample being cloned

I've only Theia that is started.

https://user-images.githubusercontent.com/436777/145003286-f5e50af9-4cf9-4b5d-b667-f56cb99656ea.mp4

### Che version

next (development version)

### Steps to reproduce

Click on `http://che-server#https://github.com/spring-projects/spring-petclinic`

project is not added by Dashboard

### Expected behavior

project is being cloned

### Runtime

OpenShift, other (please specify in additional context)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by skabashnyuk** [comment]
are you able to clone the project manually from Theia?

**Comment by benoitf** [comment]
@skabashnyuk yes

Also resolver API returns
```json
{
  "v": "4.0",
  "source": "repo",
  "devfile": {
    "metadata": {
      "generateName": "spring-petclinic"
    },
    "projects": [
      {
        "name": "spring-petclinic",
        "source": {
          "location": "https://github.com/spring-projects/spring-petclinic.git",
          "type": "github"
        }
      }
    ],
    "apiVersion": "1.0.0"
  }
}
```

but `projects` section is empty in my DevWorkspace

**Comment by benoitf** [comment]
And the clone is done by `project-clone` init container but as there is no `projects` section in the devfile it does nothing as well.

**Comment by l0rd** [comment]
@ibuziuk @benoitf could you provide the link to the PR that should fix this issue?

**Comment by ibuziuk** [comment]
@akurinnoy could you please confirm that https://github.com/eclipse-che/che-dashboard/pull/420 should also fix this problem?

**Comment by akurinnoy** [comment]
yes, that PR will fix this issue as well
