### ISSUE TITLE
Provide instructions to setup an OIDC provider for the major public cloud vendors

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20909]
### Is your enhancement related to a problem? Please describe

The deployment of an OIDC provider is required to install Che on Kubernetes. On minikube `chectl` deploys dex and configure the api-server to use it. But what about the other Kubernetes distributions? In particular what are the preliminary steps that GCP, AWS, Azure and Docker Desktop users should do?

### Describe the solution you'd like

- [x] Try out and document (ideally just a link to external doc) how to setup an OIDC providers for the major Kube distros (EKS, GKE, AKS) and for Docker Desktop (https://github.com/eclipse-che/che-docs/pull/2187)
- [x] Add a link about how to deploy Dex on other distributions (https://github.com/che-incubator/chectl/pull/1978)
- [x] https://github.com/eclipse/che/issues/20992

**Comment by Kasturi1820** [comment]
@tolusha : Can this be closed?
