### ISSUE TITLE
Ensure that CHE_INTEGRATION_XXXX_SERVER__ENDPOINTS and CHE_INTEGRATION_XXXX_OAUTH__ENDPOINT properties are properly set.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20902]
### Is your task related to a problem? Please describe

Ensure that CHE_INTEGRATION_XXXX_SERVER__ENDPOINTS CHE_INTEGRATION_XXXX_OAUTH__ENDPOINT properties are properly set.

### Describe the solution you'd like

For Gitlab, Github, Bitbucket we need to ensure that che-operator is able to.
1. CHE_INTEGRATION_XXXX_SERVER__ENDPOINTS from  customProperties appended with `che.eclipse.org/scm-server-endpoint` from all *-oauth-config secrets
3. CHE_INTEGRATION_XXXX_OAUTH__ENDPOINT is set from  `che.eclipse.org/scm-server-endpoint` from all *-oauth-config secrets

### Additional context

https://github.com/eclipse/che/issues/20496
https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring_gitlab_servers_che

**Comment by xbaran4** [comment]
To be more consistent with github config (CHE_OAUTH2_GITHUB...), I would propose to also change: 
CHE_OAUTH_GITLAB_CLIENTID__FILEPATH --> CHE_OAUTH2_GITLAB_CLIENTID__FILEPATH
CHE_OAUTH_GITLAB_CLIENTSECRET__FILEPATH --> CHE_OAUTH2_GITLAB_CLIENTSECRET__FILEPATH
