### ISSUE TITLE
Improve "Accept Trust author" notification

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20906]
### Is your enhancement related to a problem? Please describe

During a workshop, half of the attendees missed the "Trust authors" or did not accepted and so were stuck after that.

### Describe the solution you'd like

Notification that cannot vanish?
A warning dialog when clicking no?
if no action happened to the notification and workspace is empty, provide guidance in file explorer and/or welcome page

**Comment by ibuziuk** [comment]
@azatsarynnyy could you please take a look?

**Comment by azatsarynnyy** [comment]
I think it comes from the GitHub Plug-in. @svor do you happen to know?

**Comment by svor** [comment]
it comes from the [workspace plugin](https://github.com/eclipse-che/che-theia/blob/main/plugins/workspace-plugin/src/theia-commands.ts#L125)
