### ISSUE TITLE
Use latest DevWorkspace Operator release when using stable channel

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20908]
### Is your enhancement related to a problem? Please describe

After I install `chectl` from the stable channel and I do `chectl server:deploy`, the DevWorkspace Operator 0.9 installed. But I am expecting the latest "upstream" release of DWO to be deployed: v0.11 (and it's the version deployed on Developer Sandbox).

### Describe the solution you'd like

On OpenShift `chectl` stable should add the [DevWorkspace catalog source](https://github.com/devfile/devworkspace-operator/blob/main/catalog-source.yaml) and subscribe to the stable channel.

I am not sure how we should handle that on Kubernetes if OLM is not there.

### Additional context

There is a separte issue for chectl `next` channel: https://github.com/eclipse/che/issues/20899

**Comment by amisevsk** [comment]
The DevWorkspace Operator uses the `fast` channel in all cases. The [index images](https://quay.io/repository/devfile/devworkspace-operator-index?tag=latest&tab=tags) are:

* `quay.io/devfile/devworkspace-operator-index:release` - contains release of DWO starting with v0.10.0, with an upgrade path to the latest bugfix version released in the upstream repo: https://github.com/devfile/devworkspace-operator/tags/ (i.e. once `v0.12.0` is released, using the `fast` channel in this image will automatically upgrade)
* `quay.io/devfile/devworkspace-operator-index:next` - contains `next` builds of DWO, single version, no upgrades. Note we may run into an issue with this catalogsource as the version used isn't static (investigating here)

**Comment by tolusha** [comment]
Templates are updated to v0.11.0
When Eclipse Che is deployed with chectl, then the latest stable version of Dev Workspace is deployed from a custom catalog source.
