### ISSUE TITLE
Migrate E2E devfile tests from v1 to v2 

### ISSUE THREAD

**Issue by svor** [eclipse/che#20913]
### Is your task related to a problem? Please describe

Some of devfiles version 1 were migrated to version 2, the whole list of ported devfiles could be found [here](https://github.com/eclipse/che/issues/19341#issuecomment-947443288). 

When DevWorkspace is enabled, only devfiles v2 will be displayed in the dashboard. 

### Describe the solution you'd like

The idea is to migrate current E2E devfiles tests to make it possible to test devfiles version 2.

**Comment by dmytro-ndp** [comment]
List of devfiles to migrate [1]:
- CSlashCPlusPlus.spec.ts
- DevfileSmoke.spec.ts
- DotNetCore.spec.ts
- Go.spec.ts
- JavaMaven.spec.ts
- JavaSpringBoot.spec.ts
- JavaVertx.spec.ts
- NodeJS.spec.ts
- PHPSimple.spec.ts
- Python.spec.ts
- PythonDjango.spec.ts
- Quarkus.spec.ts
- Scala.spec.ts

[1] https://github.com/eclipse/che/tree/main/tests/e2e/tests/devfiles
