### ISSUE TITLE
Allow to update the devfile V2 without automatically restarting the workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#20920]
### Is your task related to a problem? Please describe

When changing the devfile from Che-Theia, workspace is restarted automatically.
It's needed for plugin installation feature https://github.com/eclipse/che/issues/20638
The user should be able to open Plugins panel, install few plugins ( each installation will change the devfile ) and only then restart the workspace by clicking some button on the UI.

How to test current behavior?
- create a workspace, using https://github.com/vitaliy-guliy/java-spring-petclinic/tree/devfilev2
- open Plugins panel, install `asciidoctor-vscode` plugin.

### Describe the solution you'd like

Should be able to update the devfie w/o restarting the workspace.

**Comment by svor** [comment]
basically it means that we need to find a way how to disable the workspace autorestarting

**Comment by vitaliy-guliy** [comment]
ATM, patching the devworkspace object does not force the workspace to be restarted.
Closing this issue as not relevant anymore.
