### ISSUE TITLE
Email Verification email is missing link to 'Verify Email', so cannot verify email used to register

### ISSUE THREAD

**Issue by gnoejuan** [eclipse/che#20933]
### Summary

Is there a setting I'm missing? I've searched https://www.eclipse.org/che/docs/che-7/administration-guide/managing-identities-and-authorizations/ and https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.1/html/administration_guide/managing_users
I might have missed something, but nothing jumped out as what I'm missing

![image](https://user-images.githubusercontent.com/4656027/146135898-ac17f29d-8490-4aa0-843d-d7866cc12fa2.png)

**Comment by nickboldt** [comment]
Can you explain what you were doing to get this email? Might help narrow down the process that created it and why the button doesn't work for you.

Also, can you define which email client you're using? Maybe it's a CSS or JS thing that's not supported?

**Comment by gnoejuan** [comment]
I apologize for the late response. 

After filling out the email and Github identity provider settings in the keycloak, I used Login with OAuth: GitHub  button to register as a new user. 

Email Client: mail.google.com
