### ISSUE TITLE
Provision git name or email with OIDC data

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20937]
### Is your task related to a problem? Please describe

Provide some defaults from git name and email configuration.

### Describe the solution you'd like

If che is running in conjunction with OIDC provider we can take this data to populate git name and email configuration if it is not configured yet.

### Describe alternatives you've considered

n/a

### Additional context

https://github.com/devfile/devworkspace-operator/pull/708

**Comment by skabashnyuk** [comment]
Closing. I think it is better to set up this data explicitly.

**Comment by l0rd** [comment]
@skabashnyuk I am no sure why it should be better to set this data explicitly so I am re-opening this issue as I think that this feature adds a lot of value to Che.
