### ISSUE TITLE
Unable to install with latest version of chectl

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [eclipse/che#20939]
### Describe the bug

chectl server:deploy is not working. below is the log out.
Due some issue it errored, but errorlogs are also not available

`bash <(curl -sL  https://www.eclipse.org/che/chectl/) 
chectl script requires superuser access.
You will be prompted for your password by sudo.
Password:
Downloading https://github.com/che-incubator/chectl/releases/download/7.40.1/chectl-darwin-x64.tar.gz...
######################################################################################################################################## 100.0%######################################################################################################################################## 100.0%
SUCCESS: chectl installed to /usr/local/bin/chectl
SUCCESS: installation log written in /Users/ckkolla/Documents/chectl/chectl-install.log
chectl/7.40.1 darwin-x64 node-v12.22.7
ckkolla@MacBook-Pro chectl % ls     
chectl-install.log
ckkolla@MacBook-Pro chectl % cat chectl-install.log 
mkdir -p /usr/local/lib
cd /usr/local/lib
rm -rf chectl
rm -rf ~/.local/share/chectl/client
curl -fsSL https://che-incubator.github.io/chectl/download-link/stable-darwin-x64
curl -#fSL https://github.com/che-incubator/chectl/releases/download/7.40.1/chectl-darwin-x64.tar.gz | tar xz
rm -f /usr/local/bin/chectl || true
rm -f /usr/local/bin/chectl
ln -s /usr/local/lib/chectl/bin/chectl /usr/local/bin/chectl
/usr/local/lib/chectl/bin/node -v > /dev/null 2>&1 || rm /usr/local/lib/chectl/bin/node
ckkolla@MacBook-Pro chectl % chectl update
chectl: Updating CLI... already on latest version: 7.40.1
ckkolla@MacBook-Pro chectl % chectl server:deploy
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✖ ✈️  Platform preflight checklist
    → Platform is required ¯\_(ツ)_/¯
    Error: Command server:deploy failed. Error log: /Users/ckkolla/Library/Caches/chectl/error.log. Eclipse Che logs: 
    /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688.
ckkolla@MacBook-Pro chectl % cd /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688
cd: no such file or directory: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688
ckkolla@MacBook-Pro chectl % cat /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688
cat: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688: No such file or directory
ckkolla@MacBook-Pro chectl % cd /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/              
cd: no such file or directory: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/
ckkolla@MacBook-Pro chectl % mkdir /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688
mkdir: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs: No such file or directory
ckkolla@MacBook-Pro chectl % mkdir /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/             
ckkolla@MacBook-Pro chectl % mkdir /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561621688
ckkolla@MacBook-Pro chectl % chectl server:deploy                                                           
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✖ ✈️  Platform preflight checklist
    → Platform is required ¯\_(ツ)_/¯
    Error: Command server:deploy failed. Error log: /Users/ckkolla/Library/Caches/chectl/error.log. Eclipse Che logs: 
    /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333.
ckkolla@MacBook-Pro chectl % cd /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333
cd: no such file or directory: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333
ckkolla@MacBook-Pro chectl % cd ~/var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333
cd: no such file or directory: /Users/ckkolla/var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333
ckkolla@MacBook-Pro chectl % cd /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333 
cd: no such file or directory: /var/folders/hj/mkwj122j6lng0kcxknrv6qb80000gn/T/chectl-logs/1639561712333
`

### Che version

7.40@latest

### Steps to reproduce

1. go to : https://github.com/che-incubator/chectl
2. Check the installations steps 
3. $ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
     a. chectl server:deploy

### Expected behavior

This command should try to start the installation

### Runtime

Docker Desktop

### Installation method

chectl/latest

### Environment

macOS

### Eclipse Che Logs

```shell
Unable to find those logs.
```

**Comment by kollachaitanyakrishna** [comment]
<img width="1022" alt="Screenshot 2021-12-15 at 3 26 15 PM" src="https://user-images.githubusercontent.com/64516009/146164746-a3da7341-f4c2-4b5b-9b33-d85fd0e3b674.png">
<img width="1029" alt="Screenshot 2021-12-15 at 3 26 30 PM" src="https://user-images.githubusercontent.com/64516009/146164795-10bf8bb1-7305-43ad-930d-037733417edc.png">

**Comment by gnoejuan** [comment]
You need the -p or --platform flag.

  -p, --platform=minikube|minishift|k8s|openshift|microk8s|docker-desktop|crc
      Type of Kubernetes platform. Valid values are "minikube", "minishift", "k8s (for kubernetes)", "openshift", "crc 
      (for CodeReady Containers)", "microk8s".

https://github.com/che-incubator/chectl#chectl-serverdeploy

**Comment by kollachaitanyakrishna** [comment]
chectl server:deploy --platform docker-desktop --telemetry=on --installer operator
