### ISSUE TITLE
As a user, I want the workspace I open from the browser's address bar have my GitHub credentials as in my browser

### ISSUE THREAD

**Issue by max-cx** [eclipse/che#20946]
### Is your enhancement related to a problem? Please describe

I am usually signed in to GitHub in my open browser.
So when I go to the address bar of my browser and I enter the URL of my Che workspace appended by the URL of my GitHub-hosted repository, I want the same permissions (GitHub user authentication and privileges) to propagate into the Che workspace that I am opening.
In other words, I want the third-party GitHub authentication by using the internet browser (like I can log in to GitLab using my GitHub credentials), as opposed to using an app/IDE.

### Describe the solution you'd like

I don't have to configure anything. If I'm logged in to GitHub in my open browser, the authentication and permissions will be handled without me thinking about it.
(In some situations, I'd like to be able to turn off or disable this feature temporarily, for example by using a different URL format).

**Comment by skabashnyuk** [comment]
The best UX at this point that doesn't break your privacy is OAuth2 integration.
See more https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che
