### ISSUE TITLE
Upgrade Rust to 1.57

### ISSUE THREAD

**Issue by monaka** [eclipse/che#20952]
### Is your task related to a problem? Please describe

The current stable version of Rust is 1.57.
Images in che-{plugin|devfile|-registry are older versions.
Some crates can't build on Che.

### Describe the solution you'd like

Fix Dockerfile to use docker.io/rust:1.57-slim-bullseye.

### Describe alternatives you've considered

None.

### Additional context

I'll send some PR soon.

**Comment by ibuziuk** [comment]
@monaka PRs have been merged to both plugin and devfile regitries. Do you think the issue can be closed now?

**Comment by monaka** [comment]
@ibuziuk Thank you for merging them. I close this.

**Comment by ibuziuk** [comment]
@monaka thank you for the contribution!
