### ISSUE TITLE
che-operator fails to reconcile after 7.41.0 update

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20968]
### Describe the bug

The operator has been updated to 7.41.0 but fail to reconcile:

2021-12-23T13:13:59.800Z	ERROR	controller-runtime.manager.controller.checluster	Reconciler error	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "name": "eclipse-che", "namespace": "test-operatorhub-che", "error": "namespaces \"test-operatorhub-che\" not found"}

It looks like the culprit is obsolete CRs left in various namespaces:
![image](https://user-images.githubusercontent.com/1461122/147254360-5930a634-e99b-4937-8f59-fab6650157f7.png)

Starting from 7.41 operator is trying to get all the CRs on the cluster even it installed in a single namespace mode

### Che version

next (development version)

### Steps to reproduce

Update to 7.41.0

### Expected behavior

Operator reconciles without errors

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux, other (please specify in additional context)

**Comment by ibuziuk** [comment]
Resolving. Removal of the obsolete CRs was required

**Comment by tolusha** [comment]
Another fix was to add `app.kubernetes.io/part-of: che.eclipse.org` label to some k8s object that che-operator couldn't see.
