### ISSUE TITLE
Plugins installation process failed - eclipse che installation on minikube

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#20979]
### Summary

i installed eclipseche (latest version) in minikube using chectl in mac os 
`minikube start --addons=ingress --vm=true --memory=9000 --cpus=3 --container-runtime=docker`
i get below error when i open a workspace from eclipse-che. Please let me know how to resolve this error

![image](https://user-images.githubusercontent.com/10482177/148101415-d9388947-63f6-4977-9deb-201e72b3a27a.png)

below are the pods currently available in the `eclipse-che` cluster
![image](https://user-images.githubusercontent.com/10482177/148101497-e9a01a84-fae7-421a-a008-008eb8be71e8.png)

this is the repository which contains dev file that i used  `https://github.com/Divine1/demonodejs.git`

below is the version details.

![image](https://user-images.githubusercontent.com/10482177/148101877-b9a19821-efb8-475a-be46-0ac58ad3c769.png)

![image](https://user-images.githubusercontent.com/10482177/148161018-46212536-9962-4303-aade-8f8434facb80.png)

### Relevant information

Plugins installation process failed

**Comment by Divine1** [comment]
i tried again this morning to open a workspace using the samples provided in eclipse che. still receiving below error

 
![image](https://user-images.githubusercontent.com/10482177/148160295-b882d8e9-9604-48b6-9407-8d4f461d91b4.png)

**Comment by tolusha** [comment]
I can't reproduce. Workspace is successfully started.

![screenshot-che-eclipse-che 192 168 59 100 nip io-2022 01 05-09_46_11](https://user-images.githubusercontent.com/1640675/148179739-8d0f24b5-3697-4a06-a208-9fdc75032321.png)

**Comment by Divine1** [comment]
@tolusha  i will comeback to you on this issue

**Comment by Divine1** [comment]
i think this issue occured to me due to my slow internet. i didnot make any changes to fix this issues.
