### ISSUE TITLE
Use OperatorHub style for Community and Tech-Preview tags

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20976]
### Is your task related to a problem? Please describe

`Community` and `Tech-Preview` tags should follow the Operatorhub style:
![image](https://user-images.githubusercontent.com/1461122/147676402-b57e9bbe-b0fb-44a8-91cf-b48f3679c2fe.png) 

Currently, all the tags are, lowercased:
* https://github.com/eclipse-che/che-devfile-registry/pull/523
* https://github.com/redhat-developer/codeready-workspaces/pull/632

### Describe the solution you'd like

Use `Community` and `Tech-Preview` tags instead of the lowercase equivalent

**Comment by ibuziuk** [comment]
@nickboldt could you please update the tags accordingly?

**Comment by nickboldt** [comment]
Yes. https://github.com/redhat-developer/codeready-workspaces/pull/666

Note that I don't generally see GH comments, so slack pings and JIRAs are better.
