### ISSUE TITLE
[DevWorkspace] Mount SSH secret to all workspace containers

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20975]
### Is your task related to a problem? Please describe

Che-server mounts SSH keys stored in the postgres to all workspace containers, [see](https://github.com/eclipse-che/che-server/commit/d3b25a9471bd55ada6da37b2bf37d87ee3be462e).  Also it creates a predefined SSH key if no SSH keys are stored in the database, and then mounts it to the workspace containers.
Need to apply the same logic for the `DevWorkspace` engine. We already have the `workspace-credentials-secret` which is expected to store SSH keys, so we don't need to read the database, just mount the existing secret.

### Describe the solution you'd like

Implement the logic in the DevWorkspce Operator.

**Comment by ibuziuk** [comment]
@vinokurig the ssh story has been finalized as part of the https://github.com/eclipse/che/issues/20832
Could you clarify what exactly is missing?
