### ISSUE TITLE
Remove obsolete code after switching to Dev Workspace engine

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20982]
### Is your task related to a problem? Please describe

Che Operator contains a lot of codebase that is not used anymore since Dev Workspace is the only workspace engine.

The goals of this task:
- remove codebase
- update readme/docs

### Describe the solution you'd like

N/A

### Additional context

This task is a prerequisite for https://github.com/eclipse/che/issues/20758

**Comment by nickboldt** [comment]
Downstream; https://issues.redhat.com/browse/CRW-2643
