### ISSUE TITLE
release process for che-dockerfiles/che-custom-nodejs-deasync broken - no new multi-arch quay images (only single-arch ones)

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#20980]
### Is your task related to a problem? Please describe

7 months ago we updated to node 12.22.1 but didn't release an amalgamated image under the 12.22.1 tag. Unclear why this happened. 

https://quay.io/repository/eclipse/che-custom-nodejs-deasync?tab=tags

So we have some CI builds of the latest partials (single arch) but no amalgamation under the 12.22.1 tag. 

Anyway, that last commit failed here:

https://github.com/che-dockerfiles/che-custom-nodejs-deasync/actions/runs/898928416

### Describe the solution you'd like

Something appears to be failing with https://github.com/che-dockerfiles/che-custom-nodejs-deasync/actions/workflows/build-publish.yaml but as I can't trigger the workflow, I'm not sure how to proceed to debug this... could you give run rights to this action so I can iterate?

We could also disable the s390x part of the build since it's no longer supported in GH.

### Describe alternatives you've considered

we could stay with quay.io/eclipse/che-custom-nodejs-deasync:12.20.1 for another 7 months?

### Additional context

Discovered while doing some base image updates in crw-theia / che-theia. Latest UBI node image uses v12.22.5, so I wanted to move up to the same version upstream too.

**Comment by benoitf** [comment]
We didn't updated to 10.22.1 in che-theia https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile#L1

Won't fix

**Comment by nickboldt** [comment]
yes but the latest node being used to build theia is 12.22.5... see https://github.com/eclipse-che/che-theia/pull/1283
