### ISSUE TITLE
[plugin-registry] openshift-ci GH action should be fixed 

### ISSUE THREAD

**Issue by svor** [eclipse/che#20985]
### Is your task related to a problem? Please describe

After switching che-operator to the Dev Workspace engine by default [1] [2], openshift-ci PR check fails in che plugin registry: https://github.com/eclipse-che/che-plugin-registry/pull/1161#issuecomment-1005726354

[1] https://github.com/eclipse-che/che-operator/pull/1265
[2] https://github.com/che-incubator/chectl/pull/1910

### Describe the solution you'd like

openshift-ci PR check should be adapted to the Dev Workspace engine

### Additional context

Since openshift-ci is not fixed we have to unblock opened PRs (remove Required status from the action)

**Comment by dmytro-ndp** [comment]
Here an example of switch to DevWorkspace: https://github.com/eclipse-che/che-operator/blob/main/.ci/oci-devworkspace-happy-path.sh

**Comment by dmytro-ndp** [comment]
It's about fixup of next E2E plugin tests:
- [VSCodeYamlPluginTest](VscodeYamlPlugin.spec.ts)
- [TypescriptPluginTest](https://github.com/eclipse/che/blob/main/tests/e2e/tests/plugins/TypescriptPlugin.spec.ts)

**Comment by SkorikSergey** [comment]
After update tests work well on our OCP 4.9 cluster but fail on openshift-ci because settings.json is empty. 
![screenshot-Wait_until_project_is_imported](https://user-images.githubusercontent.com/7760565/154931286-9ca7b1ca-782c-4f4e-bbc6-92176e9cce31.png)

**Comment by SkorikSergey** [comment]
I checked it today on OCP 4.9(from cluster-bot) and it has `{}` content as expected.

**Comment by SkorikSergey** [comment]
Done
