### ISSUE TITLE
Documentation: Update the Eclipse Che4z page to remove "CA" from product names

### ISSUE THREAD

**Issue by zeibura** [eclipse/che#20983]
Broadcom mainframe products no longer have "CA" in their names. The page https://www.eclipse.org/che/docs/che-7/extensions/eclipse-che4z/ should be updated accordingly to have the mentions of "CA" removed. Products should only be referred to as:

Endevor (not CA Endevor SCM)
InterTest for CICS/Batch
Brightside

**Comment by themr0c** [comment]
The che4z extension docs have been removed.
