### ISSUE TITLE
Default Che URL prefix should be eclipse-che rather than che-eclipse-che

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20998]
### Is your enhancement related to a problem? Please describe

Today, when installing che, it ends up with an URL like `https://che-eclipse-che.apps.my-cluster.com/`

### Describe the solution you'd like

While now there is only one installation of che per cluster, and as there is single-host, it would be better to have a shorter url

something like `https://eclipse-che.apps.my-cluster.com` (no double che)

### Describe alternatives you've considered

could be just che as well https://che.apps.my-cluter.com

### Release Notes Text

The default URL is now shorter and doesn't have the name che repeated twice in it. In fact the URL doesn't depend on the Kubernetes namespace where Che is deployed anymore but is always in the format `eclipse-che.<cluster-domain>`.

**Comment by l0rd** [comment]
@tolusha I have removed the sprint/current label and removed the milestone. Feel free to add a milestone if you plan to work on it during this sprint.
