### ISSUE TITLE
Add GitHub authentication manual flow

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20995]
### Is your task related to a problem? Please describe

Since [GitHub oauth flow is not implemented for the DevWorkspace engine](https://github.com/eclipse/che/issues/20860), we need to have an ability to manually add a GitHub token.

### Describe the solution you'd like

* Show an input box which asks for a GitHub token. 
* Store the token in the `workspace-credentials-secret` secret.
* Get the token from the secret when needed.

**Comment by svor** [comment]
@benoitf @l0rd FYI

**Comment by benoitf** [comment]
I was wondering if when using oAuth, dashboard could not write the github token in the user namespace

so editor will just read it (no need to prompt the user)

**Comment by vinokurig** [comment]
Dashboard uses che-server oauth API which is going to be deprecated right?

**Comment by benoitf** [comment]
if I try to use a private repository, I've a personal token secret in my user namespace

```
kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token-4v47q
  namespace: opentlc-mgr-che
  resourceVersion: '79901'
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/che-userid: .....
    che.eclipse.org/scm-personal-access-token-id: id-o1gt2
    che.eclipse.org/scm-personal-access-token-name: oauth2-pegbi
    che.eclipse.org/scm-url: 'https://github.com'
    che.eclipse.org/scm-userid: 'xxx'
    che.eclipse.org/scm-username: benoitf
```

**Comment by benoitf** [comment]
> Dashboard uses che-server oauth API which is going to be deprecated right?

The idea is to decouple things that are today being tied.

Import a repository from github: always use oAuth flow: https://github.com/eclipse/che/issues/20583
Need a token: --> read the secret

so editor don't need to get any oAuth configuration.
