### ISSUE TITLE
scm authentication required error when  devfile present inside organization repository (gitlab.org.com) is given as input

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#20997]
### Summary

currently i have installed eclipse-che on minikube and this setup works fine while using the `devfile` hosted in public github.com respository.

i'm facing a error while trying to access a `devfile` hosted inside my company's gitlab repository  `gitlab.org.com` .
below is the error message

![image](https://user-images.githubusercontent.com/10482177/148778022-ed06bd35-5923-4634-a0e3-5128198abd40.png)

i have followed the steps mentioned in below documentation to add personal access token of my gitlab as a secret in kubernetes.

https://www.eclipse.org/che/docs/che-7/end-user-guide/authenticating-on-scm-server-with-a-personal-access-token/#configuring_gitlab_authentication_che

i have added the secret file in `eclipse-che ` namespace, but still the error appears

![image](https://user-images.githubusercontent.com/10482177/148778640-95e4c8a7-93e3-475e-8e0b-73605c6be07e.png)

how to find our value for ` che.eclipse.org/che-userid`? currently i'm using the userid taken from below window in kubernetes `secret` file

![image](https://user-images.githubusercontent.com/10482177/148781749-18c54e6f-1f28-4a13-aa96-95a0b894e830.png)

please let me know how to resolve this issue

**Comment by skabashnyuk** [comment]
@Divine1 thank you for sharing this report. To get a better answer for you it is important to know the che version and the way how did you install che. (with or without devworkspacce support). Context https://github.com/eclipse/che/issues/20831.

**Comment by Divine1** [comment]
@skabashnyuk 

i have figuredout the issue.


the `che.eclipse.org/che-userid` value i updated in secret file and the user i used to login into eclipseche website were different. Once i logged-in with the matching userid, the issue got resolved.

please let me know if more explanation is needed related to the solution.

thank you for the support.
