### ISSUE TITLE
Invalid github oAuth configuration client URL

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20994]
### Describe the bug

When using private github repository in dashboard, at some point, we're redirected to something like 
`https://github.com/login/oauth/authorize?client_id=b964ab48346fc074cff8%0A&response_type=code.....`
which leads to a 404 error
client_id contains %0A which is like a carriage return character
client_id should be `https://github.com/login/oauth/authorize?client_id=b964ab48346fc074cff8`

### Che version

next (development version)

### Steps to reproduce

1. Setup github oAuth using https://www.eclipse.org/che/docs/next/administration-guide/configuring-authorization/#configuring-github-oauth_che
2. Then, try to load a github private repository in dashboard
3. URL of github oAuth is invalid

### Expected behavior

it should work

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by skabashnyuk** [comment]
When I last time has this issue, it was caused by an incorrectly base64 encoded value in configuration secret.
Can you check the value of `client_id` in configuration secret?

**Comment by benoitf** [comment]
the secret is using base64 so value is `Yjk2NGFiNDgzNDZmYzA3NGNmZjgK` and no space at the end
![image](https://user-images.githubusercontent.com/436777/148744428-33379729-564d-4824-a5eb-2210de00b6f3.png)

**Comment by benoitf** [comment]
I suspect this line: https://github.com/eclipse-che/che-server/blob/fb8735b8c4196c6be8a8977ad006ab073212191c/wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProvider.java#L73

```
$ cat /tmp/foo.txt
b964ab48346fc074cff8

jshell> Files.readString(Path.of("/tmp/foo.txt"));
$3 ==> "b964ab48346fc074cff8\n"

jshell> Files.readString(Path.of("/tmp/foo.txt")).trim();
$4 ==> "b964ab48346fc074cff8"
```
