### ISSUE TITLE
Workspace Error - Failed to Download Plugin

### ISSUE THREAD

**Issue by Les-Linux** [eclipse/che#21004]
Hello,

I deployed a clean Openshift 4.9.11 instance (single node) with AD LDAP integration. Following that, I deployed the Che Operator and Cluster Instance v.7.41.2. Once I login to che with oAuth and create a workspace, I am presented with the following error(s)

failed to download plugin from https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.63.0-2222.vsix: Get https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.63.0-2222.vsix: x509: certificate is valid for *.apps.k8s.mydomain, not download.jboss.org

failed to download plugin from https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix: Get https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix: x509: certificate is valid for *.apps.k8s.mydomain not open-vsx.org

Back-off restarting failed container

Back-off restarting failed container

Pulling from quay.io is working as expected, based on the log output.

This is a new installation, both for Openshift and Che. I did not make any changes to the che instance in any form and not sure why this error is being thrown. The only other error I could find beside the workspace log output, is attached

![Screenshot 2022-01-11 at 16 12 25](https://user-images.githubusercontent.com/1759713/148981271-d7905593-8d63-40c6-bb51-cf5390e9689b.png)
.

**Comment by azatsarynnyy** [comment]
@ibuziuk if I remember correctly, plugin-broker is your team's area

**Comment by Les-Linux** [comment]
I am not using a Proxy either, in case you need to know.

**Comment by Les-Linux** [comment]
If you require further details (setup, network etc) do not hesitate to reach out to me.

**Comment by Les-Linux** [comment]
Would anybody be available to troubleshoot this matter?

**Comment by tolusha** [comment]
> failed to download plugin from

You can see that plubin broker is configured with Self signed certificate (/tmp/che/secret/ca.crt) and CA bundle certificate path (/public-certs). These public certs are mounted from `workspace<...>.ca-certs` config map which *must* contain `DigiCert Global Root CA` which is used to access https://download.jboss.org. Could you check it?

**Comment by tolusha** [comment]
You can find `workspace<...>.ca-certs` in a user's namespace when workspace is starting.

**Comment by Les-Linux** [comment]
Hi Anatolii, thanks very much for the info. I will check it out immediately and let you know the outcome.

**Comment by Les-Linux** [comment]
Anatolli, this is the output when I look at my workspaceqsp9g5zpy4dikhew.ca-certs configmap

Name:         workspaceqsp9g5zpy4dikhew.ca-certs
Namespace:    lfleming-che
Labels:       che.original_name=ca-certs
                   che.workspace_id=workspaceqsp9g5zpy4dikhew
                   config.openshift.io/inject-trusted-cabundle=true
Annotations:  che.eclipse.org/included-configmaps:

#-- LIsted Certs in ConfigMap --#
# DigiCert Assured ID Root CA
# DigiCert Assured ID Root G2
# DigiCert Assured ID Root G3
# DigiCert Global Root CA
# DigiCert Global Root G2
# DigiCert Global Root G3
# DigiCert High Assurance EV Root CA
# DigiCert Trusted Root G4

**Comment by Les-Linux** [comment]
Digicert Global Root CA seems fine when I decode 
Certificate Information:
Common Name: DigiCert Global Root CA
Organization: DigiCert Inc
Organization Unit: www.digicert.com
Country: US
Valid From: November 9, 2006
Valid To: November 9, 2031
Issuer: DigiCert Global Root CA, DigiCert Inc
Serial Number: 083be056904246b1a1756ac95991c74a

**Comment by tolusha** [comment]
ok. Certificates exists and it correct.
Could you check if they are mounted in /public-certs folder of plugin folder then?

**Comment by Les-Linux** [comment]
do I check this on the plugin-registry-85667f8df4-qjws9 pod?

**Comment by Les-Linux** [comment]
output of the che pod

Pod:  che-75d78cbf8b-4564g
Directory: /public-certs
lrwxrwxrwx. 1 root 1000670000 31 Jan 11 15:52 ..data -> ..2022_01_11_15_52_49.475254648
drwxr-sr-x. 2 root 1000670000  6 Jan 11 15:52 ..2022_01_11_15_52_49.475254648
drwxrwsrwx. 3 root 1000670000 59 Jan 11 15:52 .
dr-xr-xr-x. 1 root root       83 Jan 11 15:53 ..

Mounts:
overlay on / type overlay (rw,relatime,context="system_u:object_r:container_file_t:s0:c10,c26",lowerdir=/var/lib/containers/storage/overlay/l/JDXVXJJEEZJVBVHLNE45WO7SJT:/var/lib/containers/storage/overlay/l/UYGWWBPU5S525EJMO5T7TKTGIT:/var/lib/containers/storage/overlay/l/XTEJZPI5ZZKWYLS5RCYZRJHIWI:/var/lib/containers/storage/overlay/l/CRUGLGIDPMIY6LCSV54AJ4FDM2:/var/lib/containers/storage/overlay/l/3FGRMZ4SLABTDPMYW27TXERQ43:/var/lib/containers/storage/overlay/l/UECGMNBBGRS22HXK6VH7VFUF73:/var/lib/containers/storage/overlay/l/3YDVZBKSUK6PRGVMH6A3UH3LGJ:/var/lib/containers/storage/overlay/l/JWRCFT3OMDRJIDVBUE3U5SSBUQ,upperdir=/var/lib/containers/storage/overlay/1146d82685151a995b48cb14520bb232d1dd3c2b85c4601b5be91568902e2867/diff,workdir=/var/lib/containers/storage/overlay/1146d82685151a995b48cb14520bb232d1dd3c2b85c4601b5be91568902e2867/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c10,c26",gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c10,c26",mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,rdma)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,perf_event)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k)
tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,noexec,seclabel,mode=755)
tmpfs on /etc/hostname type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /etc/passwd type tmpfs (rw,nosuid,nodev,noexec,seclabel,mode=755)
/dev/sda4 on /public-certs type xfs (ro,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota)
/dev/sda4 on /etc/hosts type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota)
/dev/sda4 on /dev/termination-log type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota)
tmpfs on /run/secrets type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime,seclabel,size=1048576k)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c10,c26")
tmpfs on /proc/kcore type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c10,c26",size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c10,c26")
tmpfs on /sys/firmware type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c10,c26")

**Comment by tolusha** [comment]
Does  `/public-certs` is empty?

**Comment by Les-Linux** [comment]
Hello @tolusha ,

Yes it would seem so. See image for greater detail
![Screenshot 2022-01-14 at 11 48 25](https://user-images.githubusercontent.com/1759713/149510980-670e3213-5110-488b-8a23-6cf9503c9d5d.png)
.

**Comment by Les-Linux** [comment]
I connected to the Che Pod, just want to ensure that was the correct Pod to query?

**Comment by Les-Linux** [comment]
@tolusha if you need me to pull further logs or clarify anything for you, don't hesitate to ping me.

**Comment by tolusha** [comment]
Unfortunately not che pod log.
che-plugin-broker logs appears for a couple of seconds in user's namespace to download plugins

**Comment by Les-Linux** [comment]
the che pod was the correct source for the certificate folder?

**Comment by tolusha** [comment]
yes, /public-certs in che pod can be empty

**Comment by tolusha** [comment]
yes, that's would be nice

**Comment by Les-Linux** [comment]
will try to grab that info

**Comment by tolusha** [comment]
@Les-Linux 
Could you try a new Eclipse Che version 7.42.0 ?
It has a different architecture [1] and does not contain plugin broker

[1] https://www.eclipse.org/che/docs/next/administration-guide/architecture-overview-with-devworkspace/

**Comment by Les-Linux** [comment]
Hi @tolusha , I had noticed that there was an update for Openshift 4.9.13 and Che 7.42.0 and applied both this morning. The workspace now bootstraps and the pet-clinic project is pulled from GIT :). Unfortunately however, when I try to run/debug the app, it throws the error 'the debug session type "java" is not supported', furthermore the launch.json schema has an issue with the property hostName - see attached image.
![che-error2](https://user-images.githubusercontent.com/1759713/149774347-bb0162e5-c016-46b2-ba6c-40472fb2d18b.jpg)

**Comment by Les-Linux** [comment]
@svor if you require logs etc. just let me know what you need and I will pull the info. This is a vanilla deployment so no changes made by me :).

**Comment by svor** [comment]
it seems java-plugin wasn't installed, do you see some errors in java-plugin container?

**Comment by Les-Linux** [comment]
@svor is it the che-plugin-registry you are referring to ?

quay.io/che-incubator/configbump@sha256:
      1 quay.io/eclipse/che--centos--mysql-57-centos7:latest
      1 quay.io/eclipse/che--centos--postgresql-13-centos7@sha256:
      2 quay.io/eclipse/che--traefik@sha256
      1 quay.io/eclipse/che-dashboard@sha256
      1 quay.io/eclipse/che-devfile-registry@sha256:
      1 quay.io/eclipse/che-machine-exec:7.42.0
      1 quay.io/eclipse/che-operator@sha256
      1 quay.io/eclipse/che-plugin-registry@sha256:
      1 quay.io/eclipse/che-server@sha256:
      1 quay.io/eclipse/che-theia:7.42.0

**Comment by svor** [comment]
@Les-Linux have you updated your previous version of che to 7.42.0 or you have installed it from the scratch?

**Comment by Les-Linux** [comment]
Hey @svor , this is a new from scratch deployed instance.

**Comment by svor** [comment]
How did you deploy it, if it was `chectl` - which version?
Also it would be nice if you provide logs from the containers from the workspace pod

**Comment by Les-Linux** [comment]
I deployed the instance from open shift via the che operator. Is there any particular log events output you require?

**Comment by Les-Linux** [comment]
[logs.tar.gz](https://github.com/eclipse/che/files/7889268/logs.tar.gz)

@svor , please find all container logs attached.

**Comment by svor** [comment]
@Les-Linux thank you for providing logs
I've tried to deploy che via che operator 7.42.0 on OCP 4.9 and I haven't reproduce the problem.
From your logs I see that plugins were not downloaded because of certificate problem:
```
downloading https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.82.0-369.vsix to /plugins/sidecars/tools for component tools
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
```
@tolusha does it say something to you?

**Comment by tolusha** [comment]
That's what we saw in pluing broker for 7.41.x version ^(

**Comment by tolusha** [comment]
@svor 
What was the container with an error?

@Les-Linux 
It would be nice to try curl inside that container

**Comment by svor** [comment]
> What was the container with an error?

it's from `remote-runtime-injector` init continer

**Comment by Les-Linux** [comment]
hey @svor, I noticed the issue initially around debugging and when I checked plugin's I could see the error I included in this thread. Let me do a curl next and post the response.

**Comment by Les-Linux** [comment]
[curl-tools.log](https://github.com/eclipse/che/files/7890634/curl-tools.log)
[curl-theia-ide.log](https://github.com/eclipse/che/files/7890635/curl-theia-ide.log)
[curl-che-pod.log](https://github.com/eclipse/che/files/7890636/curl-che-pod.log)

**Comment by Les-Linux** [comment]
> remote-runtime-injector

@svor ,
do you need me to do something specific with remote-runtime-injector ?

**Comment by Les-Linux** [comment]
![Screenshot 2022-01-18 at 22 37 28](https://user-images.githubusercontent.com/1759713/150029946-d179ce00-8e8b-4d8a-a99d-6ec82947c461.png)

 from the theia-ide container, curl would seem to be working

**Comment by Les-Linux** [comment]
![Screenshot 2022-01-18 at 22 38 57](https://user-images.githubusercontent.com/1759713/150030100-90f98f9e-de12-4066-bbf2-cb31ceefdc2f.png)

**Comment by svor** [comment]
@Les-Linux I see the problems with plugins view on my side as well, could you please register an issue for that

but java-debug and vscode-java plugins should work, it would be nice to see what you have in remote-runtime-injector container (you can find it in the workspace pod):

![screenshot-console-openshift-console apps cluster-vh88l vh88l sandbox801 opentlc com-2022 01 19-10_46_46](https://user-images.githubusercontent.com/1271546/150095497-d3558bee-5a53-4615-89bd-207666117886.png)

**Comment by tolusha** [comment]
@benoitf 
Could you point out the exact `curl` command line that is used to donwload plugins
It would be nice to try the same command manually inside `remote-runtime-injector` container by @Les-Linux to figure out the problem

**Comment by Les-Linux** [comment]
hello @svor, this is the output of the logs for the remote-runtime-injector. there is a error with the log retrieval shown and I am not sure what that is about.
![Screenshot 2022-01-19 at 12 21 48](https://user-images.githubusercontent.com/1759713/150128705-0f93149b-47ba-494f-992c-3b140a39bcc0.png)

**Comment by benoitf** [comment]
@tolusha curl commands are there: https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh

https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh#L89

**Comment by Les-Linux** [comment]
@tolusha i executed the curl from the theia-ide container and attach the output
[entrypoint.log](https://github.com/eclipse/che/files/7897301/entrypoint.log)
[entrypointL89.log](https://github.com/eclipse/che/files/7897302/entrypointL89.log)

**Comment by Les-Linux** [comment]
@svor, attaching the debugger after the build process completed worked. thank you for that :).

**Comment by Les-Linux** [comment]
final comments -  upgrading to Che v7.42.0 resolved my issue with the wildcard certificate. In relation to the plugin, this is being managed under [https://github.com/eclipse/che/issues/21043](url)

I would like to thank everybody, especially @svor, @tolusha for their invaluable assistance.
