### ISSUE TITLE
chectl `--version` flag doesn't work any more

### ISSUE THREAD

**Issue by mmorhun** [eclipse/che#21001]
### Describe the bug

Even if the version flag given, chectl tries to deploy Che in the new manner (for devworkspaces)

### Che version

next (development version)

### Steps to reproduce

Run deploy command with version flag, for example:
```
chectl server:deploy --version=7.39.0 -p minikube
```

### Expected behavior

`--version` flags works
or
we release Che 8 and do not support Che 7.x versions any more

### Runtime

minikube, CodeReady Container

### Screenshots

N/A

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
N/A
```

**Comment by tolusha** [comment]
We don't have statisticks regarding flag `--version` on Woopra

**Comment by tolusha** [comment]
It is possible to easily update chectl to a specific version to deploy a corresponding version of Eclipse Che.
(For linux)
1. Download chectl 
```
chectl_version=7.39.0
mkdir ~/.local/share/chectl/client/${chectl_version}
curl -L  https://github.com/che-incubator/chectl/releases/download/7.40.0/chectl-linux-x64.tar.gz  | tar -xz -C ~/.local/share/chectl/client/${chectl_version}
```
2. Update to chectl from a local repository
`chectl update --from-local` and select a desired version

Having this I believe when can drop `--version` flag to simplify codebase

**Comment by l0rd** [comment]
@tolusha does the `--version` work for 7.42 and above (devworkspace based versions)? Or even `--version 7.42` doesn't work?

**Comment by tolusha** [comment]
To  support `--version 7.42.0`, I need to keep some code related to backup/restore, which has been removed here https://github.com/che-incubator/chectl/pull/1996
So, answer is No now.

If we decide to support it, then I will need to keep codebase related to different versions of CheCluster  (https://github.com/eclipse/che/issues/20758), which I would like to avoid

**Comment by l0rd** [comment]
Ok I agree with you. 

Instead of removing `--version`, can we keep it but return an error and print the message with the "workaround" or pointing to the doc if someone specify it?
