### ISSUE TITLE
Dashboard shows an error in che-server mode on minikube

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21017]
### Describe the bug

Dshboard shows an error in che-server mode on minikube

### Che version

next (development version)

### Steps to reproduce

1. Start Che and switch the engine to `che-workspace`: `kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": false}]'`.
2. Wait for a minute for the che-server container to restart.
3. Open the dashboard URL and see:
![screenshot-192 168 64 126 nip io-2022 01 13-15_49_29](https://user-images.githubusercontent.com/7668752/149342536-01ed59b3-66ca-4b8a-ad62-568af337e231.png)

### Expected behavior

Dashboard must work properly.

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS

### Eclipse Che Logs

```shell
13-Jan-2022 12:37:04.722 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Jan-2022 12:37:04.793 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [27605] milliseconds
2022-01-13 12:37:38,077[nio-8080-exec-6]  [ERROR] [nvironmentInitializationFilter 222]  - Rejecting the request due to missing/expired token in Authorization header.
```
```


### Additional context

_No response_

**Comment by tolusha** [comment]
WON'T FIX
There is no way to deploy Eclipse Che with Dev Workspace disabled
