### ISSUE TITLE
Workspaces conversion fails [devfile-converter]

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21018]
### Describe the bug

We have workspace conversion(v1 to v2) errors when trying to convert workspaces made from the next 6 samples:
 - golang
 - java-mongo
 - java-mysql
 - nodejs-web-app
 - php-laravel
 - rust

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse-CHE
2. Turn of  devWorkspaces with patch ```kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": false}]'```
3. Create workspaces v1 from the next 6 samples:
     - golang
     - java-mongo
     - java-mysql
     - nodejs-web-app
     - php-laravel
     - rust
4. Turn on  devWorkspaces with patch ```kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'```
5. Clone [che-dashboard](https://github.com/eclipse-che/che-dashboard.git)
6. Checkout to the branch [che-20845](https://github.com/eclipse-che/che-dashboard/tree/che-20845)
7. [Start UD locally against remote Che Cluster](https://github.com/eclipse-che/che-dashboard/tree/che-20845#running-locally-against-remote-che-cluster)
8. Try to convert workspaces(v1 to v2) 

### Expected behavior

All workspaces v1 which was created from CHE samples should be converted successfully.

### Runtime

minikube

### Screenshots

![2022-01-13_18_10_15](https://user-images.githubusercontent.com/6310786/149391385-afa0aa05-dcc5-4745-a6c4-7768e406489d.png)
![2022-01-13_18_09_36](https://user-images.githubusercontent.com/6310786/149391400-132191ec-0b4f-4c00-bdcb-e42ad9693186.png)
![2022-01-13_18_08_58](https://user-images.githubusercontent.com/6310786/149391414-7bba5c0b-9a4d-44c8-b770-c424103cf21b.png)
![2022-01-13_17_42_04](https://user-images.githubusercontent.com/6310786/149391431-7d25cf4f-cce5-459e-89d1-5818f52bb696.png)
![2022-01-13_17_41_31](https://user-images.githubusercontent.com/6310786/149391447-037e0d3b-a552-4bdc-a243-6089a00504fe.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by benoitf** [comment]
Fixed by `@eclipse-che/devfile-converter@0.0.1-14c62ee`

**Comment by benoitf** [comment]
closing as library has been updated and is now in use by Dashboard
