### ISSUE TITLE
Unexpected errors during creating a workspace from the ASP.NET sample 

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21019]
### Describe the bug

Unexpected errors during creating a workspace from the ASP.NET sample if devworkspace enabled.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse-CHE
2. Open the 'Create Workspace' page
3. Click on 'ASP.NET Core Web Application' sample

### Expected behavior

A new workspace should be created

### Runtime

minikube

### Screenshots

![2022-01-13_12_55_38](https://user-images.githubusercontent.com/6310786/149394237-b4b36c91-b59d-4d6a-892a-c2c9bf4cbca9.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by svor** [comment]
I think it should be fixed on devworkspace-handler side, because the value of `metadata.name` could be any string https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference.html.

As a quick workaround we can apply https://github.com/che-samples/aspnetcore-realworld-example-app/pull/3

**Comment by benoitf** [comment]
@svor I didn't see the notification

the error is coming from Kubernetes API
a metadata name is not "any string"

**Comment by olexii4** [comment]
I am not able to reproduce this using the next images on minikube.
