### ISSUE TITLE
Support running the Devfile commands by Che-IDEA

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21029]
### Is your task related to a problem? Please describe

As a user, I want to be able to run my Devfile commands in Che-IDEA.
The commands should be visible as IDEA's Run Configurations.

### Describe the solution you'd like

Before starting Che-IDEA, we can parse a flattened Devfile to read the commands and pass them to the corresponding IDEA's configurations files.

### Additional context

This issue is a part of the epic https://github.com/eclipse/che/issues/20591

**Comment by azatsarynnyy** [comment]
There are three possible solutions that were discussed internally.
1. With `sh` script, make the required changes to IDEA-specific XML configurations.
2. Do the same as above, but with a Java library.
3. With a native IDEA plug-in, contribute a `Run Configurations` through the Plug-in API.

We decided to go with solution 2, as it provides a much easier way to work with XML compared to solution 1.
And solution 2 should be faster for implementation compared to solution 3, as `2` doesn't require knowledge of IDEA plug-ins development.

**Comment by vzhukovs** [comment]
Solution 2 is more convenient, but requires more time for implementation on initial step. As far as we need some mechanism for manipulating with Devfile and XML configurations (run configurations in JetBrains IDEs), it will be better to create a simple library in Kotlin that can parse Devfile to fetch necessary information about commands, that can be used in simple command adapter on step 2 and standalone plugin for JetBrains IDEs on step 3.

Kotlin library for parsing Devfile will be located here: https://github.com/che-incubator/kotlin-devfile-api
It will be similar as implemented library for Go: https://github.com/devfile/library

Will create a dedicate issue for implementing simple kotlin library for manipulating with Devfile and support only necessary functionality at first time. On future iterations, the library will receive improvements to align to all Devfile fields.

cc @l0rd @benoitf @azatsarynnyy

**Comment by azatsarynnyy** [comment]
I'm ok with a Kotlin library for the Devfile-related operations. As we will need it anyway for deeper integration of JetBrains IDE's with Che.
Unless we already have a similar Java library.
@benoitf do you happen to know if there's a Java library for Devfile stuff?

**Comment by benoitf** [comment]
Hello, as Jetbrains is part of devfile specification I think it it would make sense to get their feedback on how they'll handle that part


Anyway, there is a javascript library that is generated from the schema
So I think it could generate as well java stuff

https://github.com/devfile/api/blob/main/.github/workflows/release-typescript-models.yaml

https://github.com/devfile/api/blob/main/build/typescript-model/generate.sh
