### ISSUE TITLE
Increase the default PVC size for DevWorkspaces to 10GB

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21033]
### Is your enhancement related to a problem? Please describe

claim-devworkspace is just 1GB, which does not look like a good defaults

![image](https://user-images.githubusercontent.com/1461122/149781733-e86ae9bb-c0a2-4c0d-b988-10dec1dfb133.png)

### Describe the solution you'd like

Increase claim-devworkspace to 10 GB (same defaults for che-server claim-che-workspace)

### Describe alternatives you've considered

N/A

**Comment by benoitf** [comment]
related to https://github.com/devfile/devworkspace-operator/issues/740
