### ISSUE TITLE
Enable single running workspace restriction for DevWorkspaces started from UD

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21032]
### Describe the bug

It is possible to start multiple devworkspaces from UD. The second and subsequent would fail on some clusters due to RWO limitation.limitations

### Che version

7.41@latest

### Steps to reproduce

start a devworkspace from UD when there is already one running.

### Expected behavior

It should be possible to have only one running workspace by default

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/149783261-9b8e5595-af78-4530-b073-85b245ffca29.png)

what is more workspace startup is failing with the Unknown Error:

![image](https://user-images.githubusercontent.com/1461122/149784076-ae0059ef-1b9b-4f22-ba09-6d339911375d.png)

### Installation method

OperatorHub

### Environment

Amazon

**Comment by ibuziuk** [comment]
looks like it is possible to start multiple workspace from getting-started on the dogfooding instance :/ reopening

**Comment by olexii4** [comment]
I can reproduce the problem locally against **main**

**Comment by nickboldt** [comment]
Should be fixed in devspaces dashboard 3.0-16 in downstream https://quay.io/repository/devspaces/dashboard-rhel8?tab=tags&tag=3.0-16
