### ISSUE TITLE
Reuse common PVC 'claim-che-workspace' if exists instead of creating a new 'claim-devworkspace'

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21038]
### Is your enhancement related to a problem? Please describe

Currently, a new common `claim-devworkspace` PVC is created for devworkspaces
![image](https://user-images.githubusercontent.com/1461122/149945663-c5888113-2de7-41a1-b57f-15a59e0f393a.png)
Probably it makes sense to reuse existing `claim-che-workspace` if it exists in the namespace.

### Describe the solution you'd like

reuse existing `claim-che-workspace` instead of creating a new `claim-devworkspace`

### Additional context

This would be important for the conversion mechanism if we want to mount the sources from the Che 7 based workspaces during the convertion - https://github.com/eclipse/che/issues/20845

**Comment by amisevsk** [comment]
As a workaround, we can potentially do this by setting `.config.workspace.pvcName: claim-che-workspace` in the `devworkspace-operator-config` DevWorkspaceOperatorConfig.

**Comment by ibuziuk** [comment]
yeah, the only drawback is the `che` wording the naming

**Comment by amisevsk** [comment]
I've built `quay.io/amisevsk/devworkspace-controller:che-compatibility` to include changes from both https://github.com/devfile/devworkspace-operator/pull/777 and https://github.com/devfile/devworkspace-operator/pull/747. To test if the two PRs will allow automatic PVC reuse from Che:
1. Create a devfile v1 workspace that uses `claim-che-workspace`, make changes to files in workspace, etc.
2. Stop devfile v1 workspace but do not delete it.
3. Install DWO using image from above (either directly or by updating the CSV if installed via OperatorHub)
4. Create a new DevWorkspace with the annotation `controller.devfile.io/devworkspace_id_override: <v1-workspace-ID>`, where `<v1-workspace-ID>` is the workspace ID of the original devfile v1 workspace.
5. Verify that same paths in the claim-che-workspace PVC are mounted and that changes made in step 1 are persisted.
