### ISSUE TITLE
DevWorkspaces resources are not removed when DevWorkspace is removed

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21039]
### Describe the bug

Using Che, I've created lot of workspaces then I remove all of them.

But browsing resources with oc/kubectl or console I see tons of routes, devWorkspaceRoutings or DevWorkspaceTemplates that are still there.

### Che version

next (development version)

### Steps to reproduce

1. Create workspaces and start them
2. delete all workspaces
3. check the resources like routes, devWorkspaceRouting, etc in the user namespace

### Expected behavior

all resources should be gone if I delete the DevWorkspace

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by tolusha** [comment]
@benoitf 
Did you use chectl?
It removes all Dev Workspace resources.

**Comment by benoitf** [comment]
@tolusha yes I installed using chectl

But I remove a devworkspace, not the devworkspace operator

(Like deleting workspace from dashboard)

**Comment by ibuziuk** [comment]
I see a couple of issues with workspaces:
1. A lot of DevWorkspaceRouting hang in the terminating state due to  `finalizers:
    - devworkspacerouting.controller.devfile.io`

![image](https://user-images.githubusercontent.com/1461122/150107157-4e79b89a-28fa-42ed-9a02-8c3d4613632d.png)

2. one `che-code` devworkspace hangs in the terminating state due to   `finalizers:
    - storage.controller.devfile.io` @amisevsk I belive this one is added on our end, but not sure what exactly we need to do to prevent this. This is particularly important for https://github.com/devfile/devworkspace-operator/issues/738

**Comment by amisevsk** [comment]
The Che Operator appears to be setting a finalizer on the routes and not removing it, which causes the DevWorkspaceRouting to not be removed: [`solver.go`](https://github.com/eclipse-che/che-operator/blob/b4930b5054c0bb951e8b3fcd5ab859a8eb671c7e/controllers/devworkspace/solver/solver.go#L119-L130)

**Comment by ibuziuk** [comment]
@skabashnyuk @sparkoo @metlos folks, could you please take a look - routing finalizers prevents workspaces from being removed

**Comment by tolusha** [comment]
I will take a look

**Comment by tolusha** [comment]
https://github.com/devfile/devworkspace-operator/pull/761
