### ISSUE TITLE
Failed to retrieve default plugins for user

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21035]
### Describe the bug

When logged in as a user (i.e. not a cluster admin), and when opening the dashboard, there is an error when fetching default plugins from the CheCluster CR:

![image](https://user-images.githubusercontent.com/83611742/149806008-f218c2d6-f72f-439e-bcce-641f5f707743.png)

```
vendor.17c9d3f10f3c53b31426.js:81 GET https://che-openshift-operators.apps-crc.testing/dashboard/api/server-config/default-plugins 403 (Forbidden)

client.f6ca09f23965c8daef82.js:1 Failed to retrieve default plug-ins. Failed to fetch default plugins. Unable to fetch listClusterCustomObject: checlusters.org.eclipse.che is forbidden: User "developer" cannot list resource "checlusters" in API group "org.eclipse.che" at the cluster scope
```

The user token does not have permissions to access the CheCluster CR.

### Che version

next (development version)

### Steps to reproduce

On CRC:

1. Deploy Che on CRC with devworkspaces engine
2. Authenticate against the cluster with these credentials:
```
user: developer
pass: developer
```
3. Open the Che Dashboard, and view the output in the browser's developer console. The error message from the screenshot above should appear.

### Expected behavior

There should be no error message.

### Runtime

OpenShift, CodeReady Container

### Installation method

chectl/next

### Environment

macOS

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy I believe we need to design a solution for using some SA for reading the CR properties

**Comment by akurinnoy** [comment]
Yes, we need to update the che-dashboard SA . 
@tolusha suggested adding a new entry to these rules to allow the dashboard to read checlusters CR:

https://github.com/eclipse-che/che-operator/blob/20982/pkg/deploy/dashboard/rbac.go#L31
