### ISSUE TITLE
che dashboard version in main branch has not been updated in package.json since 7.37

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21044]
### Is your task related to a problem? Please describe

Che dashboard version in 7.yy.x branches is upversioned to the latest 7.yy.1-SNAPSHOT. For 7.42.x branch, we have:

```
  "version": "7.42.1-SNAPSHOT",
```
-- https://github.com/eclipse-che/che-dashboard/blob/7.42.x/package.json#L3-L4

Of course it's not a maven project, so why we're using -SNAPSHOT is a mystery -- we should stop using maven conventions for node and go project versioning.

Meanwhile in the main branch, the version of Che dashboard according to the package.json file is 
```
  "version": "7.37.0-SNAPSHOT",
```
-- https://github.com/eclipse-che/che-dashboard/blob/main/package.json#L3-L4

### Describe the solution you'd like

1. When creating a new 7.yy.x branch, version should be set to 7.yy.0, and only bumped to 7.yy.1 if a respin occurs.
2. When creating a new 7.yy.x branch, version in MAIN BRANCH should be set to 7.yy+1.0
3. Replace "Eclipse CHE" with the correct name, "Eclipse Che", in the package.json file

Seems we already have a method for this, but perhaps it's not running for main branch?

https://github.com/eclipse-che/che-dashboard/blob/main/make-release.sh#L69

### Additional context

https://coreos.slack.com/archives/GJWNXSY4E/p1642626864268500

**Comment by ibuziuk** [comment]
@akurinnoy @olexii4 could you please take a look?

**Comment by mkuznyetsov** [comment]
@ibuziuk a PR with suggested fix https://github.com/eclipse-che/che-dashboard/pull/443
