### ISSUE TITLE
Workspace IDE throws 500 error

### ISSUE THREAD

**Issue by madeinindiadot** [eclipse/che#21045]
### Summary

After creating test workspace on che dashboard, its unable to open che theia IDE. Throws 500 error on screen
Used chectl for deploying the eclipse-che. Dashboard auth with keycloak works fine but the IDE doesnt come up.

Attached the screenshots

### Relevant information

Steps followed

1. used kubeadm for creating kubernetes cluster using haproxy load balancer
2. Created my own cert-manager, keycloak and traefik 
3. Modified the required params and custom certs using cr-patch
4. set che-host and domain for chectl to haproxy load balancer url
5. set ingressdomain to ingressroute host which will be used against che-gatewaty service in step 8
6. created eclipse-che on kubernetes cluster using chectl
7. All the pods and services are created successfully
8. Created an ingressroute to the che-gateway service
9. Able to view the dashboard after keycloak authentication
10. on dashboard, under create workspace -> quick add, selected a sample project like python/go
11. After sometime, the workspaces is created and finally when the page is navigating to IDE seeing a 500 error

please let me know what is missing and how to get the workspace IDE 
<img width="1774" alt="Screenshot 2022-01-20 at 7 28 32 PM" src="https://user-images.githubusercontent.com/27811760/150353476-ef6aa0b7-50fb-4665-9783-124d308aa660.png">
<img width="1774" alt="Screenshot 2022-01-20 at 7 25 38 PM" src="https://user-images.githubusercontent.com/27811760/150353488-2dc5a59a-21cd-463a-bb2c-dbda8f60a05d.png">

**Comment by ibuziuk** [comment]
@madeinindiadot hello, could you please clarify what version of the Eclipse Che are you using. Logs from operator and dashboard pods would also help

> Created my own cert-manager, keycloak and traefik

@tolusha could you please confirm that in the latest Eclipse Che we do not support keycloak anymore

**Comment by madeinindiadot** [comment]
Eclipse Che Version    : 7.42.0
I was able to authenticate using my external keycloak. I followed the documentation from here
https://www.eclipse.org/che/docs/che-7/overview/introduction-to-eclipse-che/

Also one of the things I see is that even though the strategy is single-host, I see a different ingress getting created for workspace. Is this cause of concern. Also please let me know if there is any support for using my own traefik which is setup in a traefik namespace instead of having it as sidecar and path based routing which seems to be the case in che

[root@che-km01 ~]# kubectl get ingress --all-namespaces
NAMESPACE       NAME                                           CLASS    HOSTS                                                   ADDRESS        PORTS     AGE
eclipse-che     che                                            <none>   che.test.sample.net                               56.113.92.70   80, 443   14m
username-che   workspace2977e7394c1047ea-nodejs-3000-nodejs   <none>   workspace2977e7394c1047ea-1.che.test.sample.net   56.113.92.70   80        8m43s

**Comment by madeinindiadot** [comment]
@ibuziuk please let me know if you have any updates on the above questions. Thanks in advance

**Comment by tolusha** [comment]
@ibuziuk
Keycloak is not a case since 7.42.0

**Comment by madeinindiadot** [comment]
@tolusha  But I dont see any errors on keycloak. Authentication seems fine with keycloak only the routing is issue. Does this mean internal JWT auth is failing when navigating to workspaces?

**Comment by flavienbwk** [comment]
> Any updates on this? Also any help on how to install eclipse-che on kubernetes cluster built using kubeadm with our own keycloak and our traefik would be really helpful. Tried with nginx as well but the devworkspaces navigation is failing and throwing 500 error always. Thanks

Better late than never, you might be interested in following [this repo](https://github.com/flavienbwk/eclipse-che-kubernetes) for installing Eclipse Che with a kubeadm-installed K8S cluster.
