### ISSUE TITLE
Unexpected errors during creating a workspace from the Python Django sample

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21055]
### Describe the bug

Unexpected errors during creating a workspace from the Python Django sample if devworkspace enabled.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse-CHE.
2. Open the 'Create Workspace' page.
3. Click on 'Python Django' sample.

The error message '...Could not retrieve mainUrl for the running workspace.' will be shown.

### Expected behavior

Theia-editor should be opened.

### Runtime

minikube

### Screenshots

<img width="1789" alt="Знімок екрана 2022-01-21 о 16 31 08" src="https://user-images.githubusercontent.com/6310786/150569691-653f3202-b255-4a00-bdcb-4947c7d505af.png">

### Installation method

chectl/next

### Environment

macOS

**Comment by amisevsk** [comment]
Hm, I wasn't able to reproduce this in the current `next` images on minikube

**Comment by olexii4** [comment]
I am not able to reproduce this using the next images on minikube too.

**Comment by nickboldt** [comment]
I'm getting this error trying to load the che-docs devfile from this fork:

https://github.com/eclipse-che/che-docs/tree/fix-devfile-v2-import

![image](https://user-images.githubusercontent.com/227597/153278525-c82c7efd-f13b-4bf1-97c0-848f3e4f4211.png)

**Comment by amisevsk** [comment]
To clarify with Nick's issue -- after conversion for some reason the dashboard was not adding an editor, and so the DevWorkspace on the cluster did not get a `mainUrl` set (there was no container with endpoints).
