### ISSUE TITLE
Create custom workspace from private gitlab

### ISSUE THREAD

**Issue by j0eW** [eclipse/che#21059]
### Summary

Hello,

I am trying to create a custom workspace from a private gitlab repository. I followed the instructions in the [documentation](https://www.eclipse.org/che/docs/che-7/end-user-guide/authenticating-on-scm-server-with-a-personal-access-token/#configuring_gitlab_authentication_che) but when i try to create a new workspace from git repo i get following error message:

`Danger alert:Failed to resolve a devfile. Failed to request factory resolver: Error occurred during creation a workspace from devfile located at `https://gitlab.myserver.de/username/test.git`. Cause: Neither of `apiVersion` or `schemaVersion` found. This is not a valid devfile.`

UPDATE
I just tested again it looks like only github repos are working even public gitlab repos are showing the same error message

Do i have to do something after adding the secret? In the openshift console there is a button "add secret to workload" but its not mentioned in the documentation.

I am using eclipse che 7.42.0 che with crc openshift 4.9.12

**Comment by skabashnyuk** [comment]
Do you have devfile v1 or v2 in your repository?
Can you share the form how your **gitlab** configuration secret looks like?
