### ISSUE TITLE
Check that workspaces start successfully with OCP 4.10 Console samples

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21063]
### Is your enhancement related to a problem? Please describe

The devfiles included in OCP samples have been updated recently (for [v4.10](https://github.com/openshift/console/pull/10394) and [v4.9](https://github.com/openshift/console/pull/10620), see the issue for [reference](https://github.com/devfile/api/issues/666)).

In particular those devfiles have a [parent](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/devfile.yaml#L14) and include components of type [image](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/devfile.yaml#L19) and of type [kubernetes](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/devfile.yaml#L26).

### Describe the solution you'd like

We need to verify that Che `ConsoleLink` in an OCP cluster with the latest Che and DevWorkspace starts a workspace successfully. 

It doesn't matter if the `parent` or kubernetes/image components are not supported but source code should be cloned and the IDE should load successfully in the user browser. 

### Describe alternatives you've considered

After assessing the situation we should evaluate if we need to implement [this](https://github.com/eclipse/che/issues/20738) or not.

### Additional context

![image](https://user-images.githubusercontent.com/606959/150780317-26bf4a76-68c6-4f36-acfd-9ba95617af99.png)

### Reported issues in devfile org:

- [x] https://github.com/devfile/api/issues/767
- [x] https://github.com/devfile/api/issues/768
- [x] https://github.com/devfile/api/issues/777
- [x] https://github.com/devfile/api/issues/778

**Comment by ibuziuk** [comment]
related devworkspace issue - https://github.com/devfile/devworkspace-operator/issues/752

**Comment by ibuziuk** [comment]
Currently the samples are failing during workspace startup with 

![image](https://user-images.githubusercontent.com/1461122/150973759-7adcdd54-5b5f-4ee1-88a8-c2e7a2f4baa4.png)

**Comment by ibuziuk** [comment]
Verified against the dogfooding instance (DevWorkspace engine) with the 2.2 samples from https://registry.devfile.io/viewer

![image](https://user-images.githubusercontent.com/1461122/150778894-b3bfa229-a7f5-4039-a0ba-de61d7068cad.png)

- Node.js 
There is a `"projects" is not found` [1] error displayed on the dashboard, but the workspace is started. However  `npm install` command does not work:

```
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/theia/.npm/_logs/2022-02-03T12_50_38_639Z-debug.log

Terminal will be reused by tasks. 
```

Executing commands from the terminal works fine (this works because npm is part of the theia container)

- Python 
There is a `"projects" is not found` [1] error displayed on the dashboard, but the workspace is started.

No pre-defined commands, executing `python` commands manually is failing because there is no runtime available in the workspace containers:

![image](https://user-images.githubusercontent.com/1461122/152347831-7dbbfb70-948d-4351-b6ea-09233419b9f8.png)

- Quarkus
Workspace is starting without any problems. There are no predefined commands. it is not possible to build / run projects because of the missing java runtime and mvn in the workspace container.

- Spring Boot
Workspace is starting without any problems. There are no predefined commands. it is not possible to build / run projects because of the missing java runtime and mvn in the workspace container.


@l0rd apart from addressing the `"projects" is not found` [1] error (funny enough reproducible with Node and Python, but not with Quarkus and Spring Boot) do we need to support runtimes via UDI or it is enough for now to just start a workspace without the possibility of building and running the projects?  


[1] https://github.com/eclipse/che/issues/21114

**Comment by l0rd** [comment]
> @l0rd apart from addressing the "projects" is not found [1] error (funny enough reproducible with Node and Python, but not with Quarkus and Spring Boot) do we need to support runtimes via UDI or it is enough for now to just start a workspace without the possibility of building and running the projects?

I think it's ok but what image is used if it's not UDI?

**Comment by ibuziuk** [comment]
> I think it's ok but what image is used if it's not UDI?

It is theia. 
Workspace pod would only contain theia, exec and gateway containers for those 2.2 samples

**Comment by l0rd** [comment]
Oh ok, that's fine I think although at some point we want to run Theia on the dev container too. I don't know if we have an issue for that. cc @benoitf @azatsarynnyy

**Comment by benoitf** [comment]
the devfile samples have `tools` container
the one in 4.8/4.9 had https://github.com/devfile-samples/devfile-sample-code-with-quarkus/blob/501e68462dbda71f5bf242879d7cd6ebdfbd8adc/devfile.yaml#L31-L41

**Comment by benoitf** [comment]
so I wanted to know how the check was done ?
from openshift console or trying directly from current state of https://registry.devfile.io/viewer ?

**Comment by ibuziuk** [comment]
> so I wanted to know how the check was done?

Well, I used the factory link against the dogfooding instance with 2.2 samples for verification e.g. #https://github.com/nodeshift-starters/devfile-sample

> for example quarkus has parent
https://registry.devfile.io/viewer/devfiles/Community+java-quarkus

@benoitf my understanding was that this issue is about 2.2 devfiles with `kubernetes` and `image` componets available on https://registry.devfile.io/viewer as samples

![image](https://user-images.githubusercontent.com/1461122/150778894-b3bfa229-a7f5-4039-a0ba-de61d7068cad.png)

**Comment by ibuziuk** [comment]
@benoitf ok, I think I got what you mean - `2.2` sample devfile is referring [1]  `2.0` devfile as parent https://registry.devfile.io/devfiles/nodejs and it is expected to be resolved correctly - https://registry.devfile.io/devfiles/nodejs

I'm not sure if we ever verified this flow cc: @olexii4 @akurinnoy 

@benoitf @l0rd is it in general supported flow to have a 2.0 parent for 2.2 devfile? how should this be resolved from the schema perspective>


[1] https://github.com/nodeshift-starters/devfile-sample/blob/main/devfile.yaml#L14-L16

**Comment by l0rd** [comment]
> @benoitf @l0rd is it in general supported flow to have a 2.0 parent for 2.2 devfile? how should this be resolved from the schema perspective?

I don't think that's a bug, the spec allows that, but it would be better to update the parents versions yes.

**Comment by ibuziuk** [comment]
@l0rd another thing that looks inconsistent is the parent reference.

```
parent:
  id: nodejs
  registryUrl: "https://registry.devfile.io"
```

DevWorkspace controller tries to resolve it to https://registry.devfile.io/nodejs which is 404. 
The correct link is https://registry.devfile.io/devfiles/nodejs 

IMO, `registryUrl` defined in 2.2 samples should be `https://registry.devfile.io/devfile` which would be more straightforward and compatible with DWO. We can handle this case on DWO end of course, but for me this looks like registry / reference issue.

**Comment by ibuziuk** [comment]
@amisevsk probably we will need to support `/devfiles` path in DWO - https://github.com/johnmcollier/registry-docs/blob/main/registry-REST-API.adoc#gets-registry-stack-devfile 
this is a personal rep with docs, but is linked from https://devfile.io/getting-started#Technology_and_Tools_Builders+Getting_Started

**Comment by amisevsk** [comment]
There's the doc I was looking for :)

https://github.com/devfile/devworkspace-operator/pull/770

I agree that it makes more sense to have the registryUrl just be `https://registry.devfile.io/devfiles` but if this is the expected convention then we can accomodate it.

**Comment by ibuziuk** [comment]
The `parent` is now processed on both UD and DW end, however, starting the 2.2 nodejs sample is failing with `Container runtime has state CrashLoopBackOff` for the runtime container:

- Node.js 

Some problems with `registry.access.redhat.com/ubi8/nodejs-14:latest`

![image](https://user-images.githubusercontent.com/1461122/153005036-5bef6a1e-e582-4a0b-a9d1-e3e77b5e6a55.png)

2.0 devfile is also failing with the same error # https://registry.devfile.io/devfiles/nodejs 

- Python 2.2 seems to be started correctly, however commands do not work OOTB:

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 19.3; however, version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

- Quarkus 
the`tools` container from parent does not exist in workspace pod

![image](https://user-images.githubusercontent.com/1461122/153008492-08809908-d3db-4978-b1f7-9be17484f968.png)

- Spring Boot

Commands are not working OOTB:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.066 s
[INFO] Finished at: 2022-02-0
```

Also not sure why, but during the first startup of Quarkus and Spring Boot the parent was not proceeded correctly (`tools` container was missing)

**Comment by l0rd** [comment]
@ibuziuk thank you. These are bugs that should be reported to github.com/devfile/api, I would suggest to list them as subtasks of https://github.com/devfile/api/issues/681. I had try to list some of the problems [here](https://github.com/devfile/api/issues/681#issuecomment-972594175).

**Comment by svor** [comment]
@ibuziuk 
The main problem is that the commands don't have `workingDir` attribute or it has a wrong value. I've created two issues:
- https://github.com/devfile/api/issues/777
- https://github.com/devfile/api/issues/778

**Comment by ibuziuk** [comment]
The current state with the 2.2 samples on workspaces.openshift.com (conversion from 2.2 to 1)

- Python [1]
- Node.js [2]
- Quarkus [3]
- Spring Boot [4]

Workspaces are started, the projects are cloned, no pre-defined commands are available (the parent devfiles are not processed, hence the containers with runtimes are not available)


[1] https://workspaces.openshift.com/#https://github.com/devfile-samples/devfile-sample-python-basic
[2] https://workspaces.openshift.com/#https://github.com/nodeshift-starters/devfile-sample
[3] https://workspaces.openshift.com/#https://github.com/devfile-samples/devfile-sample-code-with-quarkus
[4] https://workspaces.openshift.com/#https://github.com/devfile-samples/devfile-sample-java-springboot-basic

**Comment by ibuziuk** [comment]
Developer Sandbox clusters have been updated to the latest 4.10.3 
the state of the 2.2 samples for CRW 2.15.2  https://github.com/eclipse/che/issues/21063#issuecomment-1049923247 
Workspaces are started without errors but proper development is not possible
