### ISSUE TITLE
The User Dashboard should better handle errors happened during bootstrap

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#21069]
### Describe the bug

The UD shows a blank page when the request to `api/kubernetes/namespace/provision` returns status code 500.

### Che version

next (development version)

### Steps to reproduce

```sh
chectl update next
chectl server:deploy --platform minikube
chectl dashboard:open
```

### Expected behavior

The UD shows an error page with a meaningful description.

### Runtime

minikube

### Screenshots

<img width="1786" alt="Screenshot 2022-01-25 at 17 50 19" src="https://user-images.githubusercontent.com/16220722/151013369-ba5c9def-878a-44c1-b03c-23d81d5b5e98.png">

### Installation method

chectl/next

### Environment

macOS

**Comment by dmytro-ndp** [comment]
The issue is reproduced in CRW 2.15.0 based on Eclipse Che 7.42.x:
![Screenshot from 2022-02-07 12-54-09](https://user-images.githubusercontent.com/1197777/152774952-79dc0407-ad43-4248-a42e-7c7032fd6cab.png)

**Comment by dmytro-ndp** [comment]
The issue is more important than P2, because it's a real pain to understand what has happened when there is completely empty page displayed without any error messages.

The issue has been faced on minikube, e.g. https://github.com/eclipse/che/issues/20984#issuecomment-1040161733

**Comment by ibuziuk** [comment]
changed the priority to P1 + added the `next/sprint` label
