### ISSUE TITLE
Update devfiles to use PROJECT_SOURCE instead of PROJECTS_ROOT

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21079]
### Is your enhancement related to a problem? Please describe

most of our devfiles are single-project based.

so we should try to avoid to use PROJECTS_ROOT variable that is pointing to the parent folder of the project but use instead PROJECT_SOURCE variable that is pointing to the first project of the devfile.

Issue when using PROJECTS_ROOT is that if someone fork a repository and rename the repository name, devfile has still pointer to the previous project's name.

### Describe the solution you'd like

- remove PROJECTS_ROOT in devfiles
- use PROJECT_SOURCE *only* if really needed as default working directory of commands should be PROJECT_SOURCE

so devfiles could be simplified

### Additional context

I've added editor area to be sure that when we execute commands, default directory if not specified is using PROJECT_SOURCE environment variable and not something else.

**Comment by vzhukovs** [comment]
Hi! If user omitted the `workingDir` parameter in Devfile, would it be added automatically in to the Flattened Devfile?

**Comment by vzhukovs** [comment]
And if Devfile didn't contain `workingDir` in the command, would the environment variable `PROJECT_SOURCE` point to the first project?

**Comment by benoitf** [comment]
yes that's correct

**Comment by vitaliy-guliy** [comment]
List of samples to be updated

- [ ] apache-camel-k https://github.com/che-samples/apache-camel-k/tree/devfilev2
- [ ] apache-camel-springboot https://github.com/benoitf/fuse-rest-http-booster/tree/devfilev2
- [ ] bash https://github.com/che-samples/bash/tree/devfilev2
- [ ] che4z
- [ ] cpp https://github.com/che-samples/cpp-hello-world/tree/devfilev2
- [ ] dotnet-asp.net https://github.com/che-samples/aspnetcore-realworld-example-app/tree/devfilev2
- [ ] dotnet
- [ ] go https://github.com/che-samples/golang-example/tree/devfilev2
- [ ] java-gradle
- [ ] java-lombok https://github.com/che-samples/lombok-project-sample/tree/devfilev2
- [ ] java-maven
- [ ] java-mongo https://github.com/che-samples/java-guestbook/tree/devfilev2
- [ ] java-mysql
- [ ] java-web-spring https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
- [ ] java-web-vertx
- [ ] nodejs-angular https://github.com/che-samples/nodejs-angular/tree/devfilev2
- [ ] nodejs-mongo https://github.com/che-samples/nodejs-mongodb-sample/tree/devfilev2
- [ ] nodejs-react https://github.com/che-samples/nodejs-react-redux/tree/devfilev2
- [ ] nodejs-yarn https://github.com/che-samples/react-web-app/tree/devfilev2
- [ ] nodejs https://github.com/che-samples/web-nodejs-sample/tree/devfilev2
- [ ] php-laravel
- [ ] php-mysql
- [ ] php-symfony https://github.com/che-samples/php-symfony/tree/devfilev2
- [ ] php-web-simple
- [ ] python-django https://github.com/che-samples/django-realworld-example-app/tree/devfile2
- [ ] python https://github.com/che-samples/python-hello-world/tree/devfilev2
- [ ] quarkus-command-mode
- [ ] quarkus https://github.com/che-samples/quarkus-quickstarts/tree/devfilev2
- [ ] rust https://github.com/che-samples/helloworld-rust/tree/devfilev2
- [ ] scala-sbt https://github.com/che-samples/scala-sbt/tree/devfilev2
