### ISSUE TITLE
GitHub OAuth flow is going into infinite loop if wrong configuration

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21077]
### Describe the bug

After setup the GitHub oAuth provider and using a factory with private repo browser goes into a refresh loop. 

### Che version

next (development version)

### Steps to reproduce

1. [Configure GitHub oAuth](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che)
2. Create factory wit a private repo url.
3. See: browser goes to cyclic refresh: 

https://user-images.githubusercontent.com/7668752/151192289-471970f0-60c8-41dc-96c3-82bed37f1892.mp4

### Expected behavior

Workspace should start.

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS

**Comment by l0rd** [comment]
@ibuziuk @olexii4 @akurinnoy I am setting that as a blocker as it looks like it's not possible to use Che with private repositories anymore.

**Comment by ibuziuk** [comment]
Thanks for reporting. @vinokurig is it reproducible against the dogfooding instance for you, since I was not able to repro?
@olexii4 @akurinnoy could you please take a look?

**Comment by vinokurig** [comment]
Closing as it was a problem on my side. Wrong copy paste :)

**Comment by benoitf** [comment]
I think that even if oAuth is not configured properly Dashboard should display an error and not goes into an infinite loop
