### ISSUE TITLE
chectl should use latest LTS node release

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21075]
### Is your enhancement related to a problem? Please describe

Today, chectl is using nodejs 12 while this version is not the active LTS release (there was nodejs 14 and now it's 16)

https://nodejs.org/en/about/releases/

nodejs 12 EOL is in 3 months 2022-04-30

### Describe the solution you'd like

Use newer version of nodejs: 16

**Comment by nickboldt** [comment]
Downstream impact: https://issues.redhat.com/browse/CRW-2695
