### ISSUE TITLE
'chectl login' command in the dashboard should not be there anymore

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21070]
### Describe the bug

In dashboard we can click on the account and then 'Copy chectl login command'

But this command has been removed in chectl with DevWorkspace engine, so it should be removed from the dashboard

### Che version

next (development version)

### Steps to reproduce

Go to the dashboard and click on the account

### Expected behavior

No login command should be displayed 
(now there is an optional link on OpenShift to get the console)

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/436777/151019087-f5256017-cdc6-475c-ab06-a1ed93121561.png)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by tolusha** [comment]
It must completely removed from the dashboard since there is no anymore `chectl auth:login` command

**Comment by akurinnoy** [comment]
Resolved in https://github.com/eclipse-che/che-dashboard/pull/538
