### ISSUE TITLE
che-code - add a volume to /home/user/.vscode-remote/

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21086]
### Is your enhancement related to a problem? Please describe

che-code allows installing extensions using the extension view. From what I can see these are stored in `/home/user/.vscode-remote/`. 

After installing gitlens the following files are created and should get lost after a container is restarted.

```
$ find . -name '*gitlens*'
./home/user/.vscode-remote/data/CachedExtensionVSIXs/eamodio.gitlens-11.7.0
./home/user/.vscode-remote/extensions/eamodio.gitlens-11.7.0
./home/user/.vscode-remote/extensions/eamodio.gitlens-11.7.0/dist/gitlens.js.map
./home/user/.vscode-remote/extensions/eamodio.gitlens-11.7.0/dist/gitlens.js
./home/user/.vscode-remote/extensions/eamodio.gitlens-11.7.0/images/gitlens-icon.png
./home/user/.vscode-remote/extensions/eamodio.gitlens-11.7.0/images/gitlens-activitybar.svg
```

### Describe the solution you'd like

It might be useful to add a volume to `/home/user/.vscode-remote/`.

**Comment by benoitf** [comment]
probably we might need to use another path (instead of /home/user) for parent folder  as while it will work when using universal developer image that has /home/user folder, it might now work with custom docker images.

**Comment by benoitf** [comment]
@nils-mosbach Issue is fixed but I let you reopen the issue if you still have the problem
