### ISSUE TITLE
Handle all terminal options using Che-Code

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21080]
### Is your enhancement related to a problem? Please describe

There is a basic implementation of terminal across different containers of a pod using machine-exec

but it's lacking some features, like displaying the current terminals when reloading the window (it should display again the launched terminals)

There is also resize option and few other that are not implemented

### Describe the solution you'd like

- implement reload of previous terminal
- implement resize

### Additional context

https://user-images.githubusercontent.com/606959/170955674-10055934-b0b3-4b92-a8ab-b466a9f96b37.mov

**Comment by azatsarynnyy** [comment]
I've extracted the cursor problem to a separate issue https://github.com/eclipse/che/issues/21473

**Comment by azatsarynnyy** [comment]
The previous multi-container terminal implementation has been replaced with the extension API-based
https://github.com/che-incubator/che-code/pull/122
So, this issue isn't relevant anymore.
For any terminal-related issue, please create a separate ticket.
