### ISSUE TITLE
[plugin-registry] Enable to deploy sidecar containers to private repositories.

### ISSUE THREAD

**Issue by monaka** [eclipse/che#21090]
### Is your enhancement related to a problem? Please describe

* Plugin-registry caches vsix plugins.
* many plugins require sidecar containers on quay.io.

So offiline mode doesn't work well.

### Describe the solution you'd like

* Enable the sidecar builder to accept image prefixes. (like `quay.io/eclipse/che-plugin-sidecar` to `example.com/foo/che-plugin-sidecar`)
* Add options `--offline-image` to `build.sh`.

**Comment by monaka** [comment]
In general, private repositories are much faster than the public quay.io . They will provide for good user experiences.

**Comment by tolusha** [comment]
Is that something you looking for ?
https://github.com/eclipse-che/che-plugin-registry/blob/main/build.sh#L34
