### ISSUE TITLE
Authorization using scopes or custom claims

### ISSUE THREAD

**Issue by martinelli-francesco** [eclipse/che#21096]
### Summary

I have configured Eclipse Che to use an external OIDC.
Let's suppose we have two users and two applications:
user A can only access application A (Eclipse Che) and user B can only access application B (this can be achieved by specifying specific roles for users and therefore at the login time the OIDC can verify if the user can access the specific resource).

User B could log in to application B, take the obtained access token and use it for application A.

One way to avoid this problem is to define a specific scope or a custom claim in the access token to define what the token was created for, and the backend should check if the token contains the expected scope/custom claim.

So, my question is:
Is there a way to configure Che to check if the access token contains a specific scope or custom claim?

**Comment by skabashnyuk** [comment]
@sparkoo do you remember if oauth2-proxy has some kind of `specific scope or a custom claim ` filtering.  
Maybe experiments with `--oidc-groups-claim` or `--scope` can answer this question. 
Context https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview

@martinelli-francesco what do you have as OIDC provider?

**Comment by martinelli-francesco** [comment]
I am using auth0 as OIDC provider.

I think the problem is conceptual, let me tell you what I understand about the current login flow and token management.

1. Login to Eclipse Che
2. Redirect to my OIDC
3. Successful login
4. Redirect to Eclipse Che: the OIDC after successful login generates the id_token. It will be passed to Eclipse Che.
5. Eclipse Che takes the id_token to understand who am I and then generates a cookie used on subsequent calls to indicate that I am already authenticated.
6. When a kubernetes API Server API is called, Kubernetes itself checks the id_token.

It seems that Eclipse Che/Kubernetes only handles id_token, so if I need to allow only some OIDC users I can add a custom claim in id_token and, for example, make it mandatory in the kubernetes configuration (see --oidc-required-claim https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server).
Unfortunately the id_token is obtained only at login, so if I remove the custom claim for a user the authorization check will only fail on the next login. In other words, I can remove the custom claim but the user is still able to work with Eclipse Che until they log in again.

In fact, usually, custom claims (or scope) to manage the authorization are in the access token because it is of short duration (a few minutes) and therefore as soon as a new access token is requested, it is possible to perform a new check of authorization. Unfortunately, in Eclipse Che it seems that after obtaining the id_token there is no more communication with the OIDC and therefore it seems that the access tokens are not used. 

So my problem is that I have not found a way to manage authorization from OIDC (using custom scope, roles or claims) which is able to also handle adding/removing authorization when user is already logged in.

**Comment by sparkoo** [comment]
Yes, we're using ID token on kubernetes https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go#L99 https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options.

On OpenShift however, we're using access token so you may try to replicate that. If you're able to setup kubernetes to use access token, you can then set `--pass-access-token` on oauth2-proxy. With that, you only get the token into `X-Forwarded-Access-Token` header and you need to get it to `Authorization` header. We're doing this on OpenShift with https://github.com/eclipse-che/che-operator/blob/main/controllers/devworkspace/solver/che_routing.go#L452.

Even then, I'm not sure you'll get what you need. You may search/ask on oauth2-proxy https://github.com/oauth2-proxy/oauth2-proxy/issues
