### ISSUE TITLE
Cleanup devfile registry

### ISSUE THREAD

**Issue by svor** [eclipse/che#21119]
### Is your task related to a problem? Please describe

Since we migrated devfiles from version 1 to version 2, we can simplify [che-devfile-registry ](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles).

### Describe the solution you'd like

There are a few steps to do:
1. Remove all devfile folders which we don't use for v2: [dotnet](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/dotnet), [php-laravel](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/php-laravel), [che4z](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/che4z), [java-gradle](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/java-gradle), [java-maven](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/java-maven), [java-mysql](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/java-mysql), [java-web-vertx](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/java-web-vertx), [php-mysql](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/php-mysql), [php-web-simple](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/php-web-simple), [quarkus-command-mode](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/quarkus-command-mode).
2. Remove all devfile.yaml files (we don't need them in DevWorkspace mode)
3. Improve script to [publish on GH pages](https://github.com/eclipse-che/che-devfile-registry/blob/main/.ci/generate_and_publish_registry_url_devfiles.sh) to avoid adding devfile.yaml files.  
4. Remove **self** link from the [index.json](https://eclipse-che.github.io/che-devfile-registry/7.43.0/devfiles/)

**Comment by l0rd** [comment]
@svor moving to next release

**Comment by l0rd** [comment]
Moving to next milestone.
