### ISSUE TITLE
Che-IDEA should trust the sources in `PROJECTS_ROOT` by default

### ISSUE THREAD

**Issue by vzhukovs** [eclipse/che#21110]
### Is your task related to a problem? Please describe

When the user starts a Che-IDEA-based workspace, it asks to trust the sources:

![image](https://user-images.githubusercontent.com/1636395/152516370-1d3109b8-d0ac-47ec-acb2-1cc404b0cf4d.png)

It may be annoying for the users.

### Describe the solution you'd like

Add `PROJECTS_ROOT` as the trusted location for opening cloned projects to avoid dialog that asks the user trust to a particular project. Need to modify the default provided configuration by adding the value for `PROJECTS_ROOT` directory.

<img width="1094" alt="Снимок экрана 2022-02-02 в 13 51 50" src="https://user-images.githubusercontent.com/1968177/152148548-0ada4e85-352e-457e-93d5-7a99f88c77aa.png">

**Comment by azatsarynnyy** [comment]
Adding an example of the dialog, to be clear what this issue about
![image](https://user-images.githubusercontent.com/1636395/152343690-e75a180f-25af-43b3-a2ef-7494ff3166cc.png)
