### ISSUE TITLE
Workspace conversion failed

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21120]
### Describe the bug

Workspace conversion failed if you try to convert workspaces that were created from these samples:

- [apache-camel-k](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/apache-camel-k/devfile.yaml)
- [che4z](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/che4z/devfile.yaml)
- [rust](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/rust/devfile.yaml)

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse-CHE with devWorkspace disabled.
2. Open the 'Create Workspace' page.
3. Create new workspaces from the samples: 'Rust', 'Apache Camel K', 'che4z'.
4. Run 
    ```sh
     chectl server:update --che-operator-cr-patch-yaml=...
     ``` 
    with a patch that enables devWorkspaces.
6. Try to convert created workspaces.

### Expected behavior

Workspaces should be successfully converted.

### Runtime

minikube

### Screenshots

**apache-camel-k**
![2022-01-26__11_22_50](https://user-images.githubusercontent.com/6310786/151137292-ec6ae466-b2c9-409e-babe-d00a5b6773b4.png)

**che4z**
![2022-01-26_11_30_04](https://user-images.githubusercontent.com/6310786/151138149-b2124235-2647-4b3d-99c4-de66f566c2a9.png)

**rust**
![2022-01-26__11_33_54](https://user-images.githubusercontent.com/6310786/151138523-24287728-cc43-4b3e-9606-0eafa92ef064.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by benoitf** [comment]
I think you should provide .yaml/gist files of the devfiles in addition to the screenshot

**Comment by olexii4** [comment]
@benoitf I have added links to the issue description:
- [apache-camel-k](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/apache-camel-k/devfile.yaml)
- [che4z](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/che4z/devfile.yaml)
- [rust](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/rust/devfile.yaml)

**Comment by ibuziuk** [comment]
Also, have the covertion failure for cpp devfile

```
apiVersion: 1.0.0
metadata:
  name: cpp-test-convert
projects:
  - name: CPP
    source:
      location: 'https://codeready-codeready-workspaces-operator.apps.sandbox-m2.ll9k.p1.openshiftapps.com/devfile-registry/resources/cpp-CPP-master.zip'
      type: zip
components:
  - id: che-incubator/cpptools/latest
    preferences:
      clangd.path: /usr/bin/clangd
      cdt.clangd.binaries.enable: false
    type: chePlugin
    alias: cpp-plugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    alias: cpp-dev
    image: 'registry.redhat.io/codeready-workspaces/stacks-cpp-rhel8@sha256:c2f38140f52112b2a7688c2a179afcaa930ad6216925eb322cfd9634a71cfc13'
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
commands:
  - name: 1. Build current algorithm
    actions:
      - workdir: '${fileDirname}'
        type: exec
        command: 'rm -f "${fileDirname}"/bin.out && g++ -g "${file}" -o bin.out && echo "Build complete"'
        component: cpp-dev
  - name: 2. Run current algorithm
    actions:
      - workdir: '${fileDirname}'
        type: exec
        command: ./bin.out
        component: cpp-dev
  - name: Debug current algorithm
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
                {
                    "type": "gdb",
                    "name": "Debug current algorithm",
                    "request": "launch",
                    "program": "${fileDirname}/bin.out"
                }
            ]
          }
        type: vscode-launch

```
```
![image](https://user-images.githubusercontent.com/1461122/163155377-b416704a-dc2e-4ecb-b41c-274966dcfc46.png)
```

**Comment by benoitf** [comment]
it's strange to have the failure for Cpp as the CPP tools plug-in is not there
https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/

it has been migrated to https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/eclipse-cdt/cdt-vscode/ almost a couple of years ago

**Comment by ibuziuk** [comment]
The rust convertion has been fixed. However there are still convertion issues for che4z / camel 

```
Workspace conversion failed.
Failed to create a new workspace from the devfile, reason: Unable to resolve theia plugins: Not able to find any dev container component in DevWorkspace
Find manual instructions for converting devfile v1 to devfile v2 in the [documentation](https://devfile.io/docs/devfile/2.2.0/user-guide/migrating-to-devfile-v2/).
```

@benoitf wdyt maybe we can address it in the FAQ as part of the https://github.com/eclipse/che/issues/21005 ?

e.g. how to add the dev container component to v1 devfile

**Comment by ibuziuk** [comment]
Should be closed once https://github.com/eclipse-che/che-dashboard/pull/510 backported to 7.46.x
