### ISSUE TITLE
Problems with Certificates on Minikube Eclipse Che 

### ISSUE THREAD

**Issue by wbondarchuk** [eclipse/che#21125]
### Summary

I installed Eclipse Che using Minikube 
chectl server:deploy --platform minikube --installer operator
Everything seemed to be good but when I click on the link I get error 503.
I received the certificate and added it to the browser using the command
chectl cacert:export —destination=/home/vladimir/Downloads
Eclipse Che self-signed CA certificate is exported to /home/vladimir/Downloads/cheCA.crt
What could be the problem and how to solve it?
![image](https://user-images.githubusercontent.com/55180931/152550518-9c4e924c-ffb5-4b9a-88d6-142a0bc60c72.png)
![image](https://user-images.githubusercontent.com/55180931/152550582-898bda0f-f823-42d8-9480-537a7cf82991.png)

**Comment by dmytro-ndp** [comment]
Issue has been reproduced in https://github.com/eclipse-che/che-plugin-registry/actions/runs/1800124531:
[Eclipse Che logs (rhel).zip](https://github.com/eclipse/che/files/8009086/Eclipse.Che.logs.rhel.zip)
[Happy path test report (rhel).zip](https://github.com/eclipse/che/files/8009087/Happy.path.test.report.rhel.zip)

https://user-images.githubusercontent.com/1197777/152661888-e3c30762-dbae-487d-bf48-bd09ff995382.mp4

Page console logs:
```
"SEVERE" "" "https://192.168.49.2.nip.io/ - Failed to load resource: the server responded with a status of 503 ()"
"SEVERE" "" "https://192.168.49.2.nip.io/favicon.ico - Failed to load resource: the server responded with a status of 503 ()"
"SEVERE" "" "https://192.168.49.2.nip.io/favicon.ico - Failed to load resource: the server responded with a status of 503 ()"
```

**Comment by tolusha** [comment]
@dmytro-ndp 
I haven't tried minikube v1.21.1 but I am prety sure it should work with v.23.2 and  1.24.0

**Comment by debovema** [comment]
> @dmytro-ndp I was able to solve my problem using Minikube v1.24.0 and allocating more memory:
> minikube start --memory=10240 --cpus=4

After increasing the allocated memory I succeeded to reach the dex UI and I'm able to log in. However the dashboard does not load:
![image](https://user-images.githubusercontent.com/8082252/152983379-9db06778-d32b-4513-9bc6-9d497ab8bdc9.png)

**Comment by amol-m-deshpande** [comment]
@debovema I followed the above steps, I can see the dex login.
I used a couple of creds from the output
```
16:10:27] Dex user credentials      : che@eclipse.org:admin [started]
[16:10:27] Dex user credentials      : che@eclipse.org:admin [completed]
[16:10:27] Dex user credentials      : user1@che:password [started]
[16:10:27] Dex user credentials      : user1@che:password [completed]
```
username: che@eclipse.org
password: admin
**or**
username: user1@che
password: password
I get 500 internal server.
Did I miss any step?



<img width="1436" alt="image" src="https://user-images.githubusercontent.com/97450729/154673451-58e11d4c-8f08-4463-a40b-69fc74e28adc.png">

**Comment by karatkep** [comment]
I got the same 500 error issue as @tolusha 

Is there any update on this topic?

**Comment by tolusha** [comment]
It works locally on my minikube v1.25.2

**Comment by prasanthmvp** [comment]
@karatkep did u resolved 500 error on Oauth callback

**Comment by debovema** [comment]
@prasanthmvp @amol-m-deshpande : I used to have an error 500 and then I updated this [gist](https://gist.github.com/debovema/783f29040059f8b2b784a246dbd96365). I have tested it on WSL2 + Docker Desktop (Minikube 1.26.0, k8s 1.24.1, chectl 7.49.0).
What is your host system ?
Also check that you have no problem of DNS rebinding protection to use *.nip.io hostnames (see https://nip.io/ and https://en.wikipedia.org/wiki/DNS_rebinding).

**Comment by prasanthmvp** [comment]
@debovema We had seen the script and kindly guide how to use it in the following environment.

Minikube Version: v1.26.0
Docker version 20.10.17, build 100c701
OS : AlmaLinux release 9.0 (Emerald Puma)

minikube start --addons=ingress,dashboard --driver=docker --memory=12288 --cpus=6

Due to the *.nip.io restricted in our Network, We modified the /etc/hosts file as follows.,
192.168.49.2  192.168.49.2.nip.io dex.192.168.49.2.nip.io *.192.168.49.2.nip.io
