### ISSUE TITLE
Workspace status failed after conversion

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21121]
### Describe the bug

Workspace status failed after conversion if you try to convert workspaces that were created from these samples:

 - [quarkus](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/quarkus/devfile.yaml)
 - [java-gradle](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/java-gradle/devfile.yaml)
 - [dotnet](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/dotnet/devfile.yaml)
 - [asp.net](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/dotnet-asp.net/devfile.yaml)
 - [scala-sbt](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/scala-sbt/devfile.yaml)

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse-CHE with devWorkspace disabled.
2. Open the 'Create Workspace' page.
3. Create new workspaces from the samples: 'Quarkus', 'java-gradle', 'dotnet', 'asp.net', 'scala-sbt'.
4. Run 
    ```sh
     chectl server:update --che-operator-cr-patch-yaml=...
     ``` 
    with a patch that enables devWorkspaces.
6. Try to convert created workspaces.

### Expected behavior

Workspaces should be successfully converted without status failure.

### Runtime

minikube

### Screenshots

**scala-sbt**
![2022-01-26__11_01_16](https://user-images.githubusercontent.com/6310786/151133643-142e2181-ae3f-434e-b845-86f5a44fbb57.png)

 **quarkus**
![2022-01-26__11_08_07](https://user-images.githubusercontent.com/6310786/151134757-449a50c7-ee44-49c1-9634-8bf3e5fb4e06.png)

 **java-gradle**
![2022-01-26__11_12_15](https://user-images.githubusercontent.com/6310786/151135423-86a8ac50-5af1-41ce-9ec3-6caa608b2e53.png)

 **dotnet**
![2022-01-26__11_17_36](https://user-images.githubusercontent.com/6310786/151135941-687f9a1c-3b55-4a61-a643-0de3a8898f72.png)

 **asp.net**
![2022-01-26__11_20_29](https://user-images.githubusercontent.com/6310786/151136420-945add5b-196d-4beb-b3b3-b2351d065042.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by benoitf** [comment]
I think you should provide .yaml/gist files of the devfiles in addition to the screenshot

**Comment by olexii4** [comment]
@benoitf I have added links to the issue description:

 - [quarkus](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/quarkus/devfile.yaml)
 - [java-gradle](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/java-gradle/devfile.yaml)
 - [dotnet](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/dotnet/devfile.yaml)
 - [asp.net](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/dotnet-asp.net/devfile.yaml)
 - [scala-sbt](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/scala-sbt/devfile.yaml)
