### ISSUE TITLE
Update all workspaces ingress

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse/che#21123]
### Summary

Hello we use che 7.18.0 and we integrated Jupyter for our scientists.
We noticed that the Jupyter has by default a limitation for upload. When we drag and drop or use upload button, we can't upload more than 20Ko.

To correct it, the solution founded is to add in the ingress file the nginx property `nginx.ingress.kubernetes.io/proxy-body-size: 8m`...

When i update the che and plugin-registry ingress with this property and i create a new Jupyter workspace, the new workspace doesn't have the property.

Where is located the ingress file used by all new workspaces ? So i can update it once, and all new workspace will be created wtith the correct property. 

Thanks.

**Comment by skabashnyuk** [comment]
Try experement with `CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON`  see more https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/

**Comment by KOSSOKO** [comment]
Hello @skabashnyuk we use helm to deploy our che. I don't really know where to put the key you mentioned above.

**Comment by skabashnyuk** [comment]
That is an environment variable of che server.

**Comment by KOSSOKO** [comment]
Hello @skabashnyuk, I found where to add the env variable `CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"nginx.ingress.kubernetes.io/proxy-body-size":"256m"}'` but when i update the config map of che with `kc edit cinfigmap -n che -o yaml` to add this property, new workspaces are created without the property.

Is there any way to patch the che ? We use che 7.18, with helm for deployment.

**Comment by KOSSOKO** [comment]
Ok, I just edit the config map, delete the che pod and it works.
Thanks
