### ISSUE TITLE
Provide a way to navigate to Che Dashboard from Che-Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21130]
### Is your enhancement related to a problem? Please describe

When the user has opened Che-Code editor and has closed the page with Che Dashboard it may require several extra steps to navigate to the Dashboard.
It can be much simpler if Che-Code provides a command to navigate to Che Dashboard.

### Describe the solution you'd like

Add the `Go to Dashboard` command to Che-Code.
It would be really convenient having it in the bottom-left `Eclipse Che` menu:

![image](https://user-images.githubusercontent.com/1636395/152780514-ac79c1ce-17fd-4b95-a844-679dd358a245.png)

### Additional context

Depends on https://github.com/eclipse/che/issues/21102

**Comment by benoitf** [comment]
the command is there but not displayed (enabled) due to https://github.com/eclipse/che/issues/21102

**Comment by azatsarynnyy** [comment]
The command should be enabled automatically once `CHE_DASHBOARD_URL` is present.

Thanks @benoitf for the link!

**Comment by azatsarynnyy** [comment]
depends on https://github.com/eclipse/che/issues/21102

**Comment by azatsarynnyy** [comment]
It works now
![image](https://user-images.githubusercontent.com/1636395/170193837-152fc3ae-9f02-4d8a-9211-af23f3c717ce.png)
