### ISSUE TITLE
how to replace the `dex` login interface with my `organization sso` login interface in `eclipse-che`?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21136]
### Summary

i have installed below `chectl` version
![image](https://user-images.githubusercontent.com/10482177/152839434-b16d9dc5-badc-4d21-87b5-61fef14c7590.png)

i have installed `eclipse-che` on minikube cluster.
below are the namespaces currently available in my  minikube cluster
![image](https://user-images.githubusercontent.com/10482177/152839500-987524ce-c94f-4c28-ae73-06ba2fc2a379.png)

below is the default `dex` login interface. i want to  replace the `dex` login interface with my `organization sso`  login interface.  
![image](https://user-images.githubusercontent.com/10482177/152839308-26c5ea33-6ab2-42ad-b3d0-68dd776067e6.png)

please let me know the steps on how integrate `organization sso` login with `eclipse-che` instead of `dex` login interface

**Comment by svor** [comment]
@tolusha could you help with that?

**Comment by Divine1** [comment]
@tolusha kindly help me out

**Comment by Divine1** [comment]
@svor @tolusha 
please share with me if any details or docs are available on this? :)

**Comment by svor** [comment]
@Divine1 I see that it's possible to customize Dex https://dexidp.io/docs/templates/
maybe @sparkoo could provide some details how to do that in Che

**Comment by Divine1** [comment]
should i have to update the `dex` `configmap` with `gitlab` connector as it is mentioned [here](https://dexidp.io/docs/connectors/gitlab/)?

![image](https://user-images.githubusercontent.com/10482177/153378188-ceb2b34a-8504-46cd-8eb1-7a76247ab9b5.png)



![image](https://user-images.githubusercontent.com/10482177/153378300-1daf5b38-23bc-40a4-9077-a65d22be5318.png)

**Comment by sparkoo** [comment]
I've never did that, sorry. Please try to follow dex documentation

**Comment by Divine1** [comment]
@sparkoo @svor @tolusha 


i followed this documentation. i'm able to view my `gitlab sso login screen` instead of `dex login screen`. the sso authentication is successful, the but redirection back to the `dex - eclipse-che website` shows below error

![image](https://user-images.githubusercontent.com/10482177/153574785-77bb4644-182f-41fa-93fd-3e3d4b1fce27.png)

below is the redirect url i have configured in the `gitlab application`. i suspect this url is incorrect, but i'm not able to figure our what is the valid redirect url. Please let me know the valid callbackUrl for this.
![image](https://user-images.githubusercontent.com/10482177/153575206-90c169cc-913a-4f76-8310-28c10809b01c.png)


`kubectl edit configmap dex -n dex` - below is the gitlab configuration in `configmap`
![image](https://user-images.githubusercontent.com/10482177/153574409-a87fa3cb-db1d-4d20-975b-f0201cf35b49.png)


please help me out on this

**Comment by Divine1** [comment]
@sparkoo thank you for the response. i have updated the redirect url to `https://dex.192.168.49.2.nip.io/callback`

now i get `the requested scope is invalid, unknown or malformed` error message as shown below

![image](https://user-images.githubusercontent.com/10482177/153585964-0c593c62-c45e-4643-bd16-743c10d0d804.png)


i have added below scopes in my gitlab application
![image](https://user-images.githubusercontent.com/10482177/153586186-4556ce5c-c904-4673-877d-96b774498fa4.png)

What i'm i missing here? Please let me know how to resolve this error.

**Comment by Divine1** [comment]
@sparkoo 
The above `requested scope is invalid` issue is resolved now.

in my `gitlab -> applications` `read_user` scope was missing. Now the `gitlab -sso` integration with `dex` works fine.
![image](https://user-images.githubusercontent.com/10482177/153623501-f00338b0-b59d-496f-bca9-aaed05c09588.png)
