### ISSUE TITLE
Failed banner is not cleared from dashboard when DevWorkspace is restarted

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21134]
### Describe the bug

When a DevWorkspace fails to start, the dashboard shows a banner with the failure reason. However, when you click "restart" in that banner, the "Workspace failed to start" message is not cleared, making it seem like the restart has _also_ failed, even if the DevWorkspace is starting normally.

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace that will fail to start
2. After it has failed, from dashboard, click "Open" link
3. Note dashboard shows failure reason, click "restart"
4. DevWorkspace starts but message still says it failed

### Expected behavior

Once a DevWorkspace is in the starting state/the user clicks restart, the "failed to start" message should be cleared.

### Runtime

OpenShift

### Screenshots

1. Workspace fails to start
![initial-failure](https://user-images.githubusercontent.com/16168279/152820970-540f9881-7ca3-48df-b7c9-239adefb97f2.png)

2. Open workspace from dashboard, see error message + restart button
![open-from-dashboard](https://user-images.githubusercontent.com/16168279/152821745-952644a0-25b1-4627-b81d-89c869057573.png)

3. Click restart button; workspace is Starting but failure message still present (in this case, the workspace eventually started and the page redirected to the editor)
![restarting](https://user-images.githubusercontent.com/16168279/152820974-8c1ac3de-46b8-4a4a-b340-5c06d27e475e.png)

### Installation method

OperatorHub

### Environment

Linux

### Additional context

I tried checking the underlying DevWorkspace object's status, and it appears the failed condition is cleared when it is restarted.

**Comment by ibuziuk** [comment]
fixed in https://github.com/eclipse-che/che-dashboard/pull/471
