### ISSUE TITLE
Native build command fails for devworkspace Quarkus Che sample

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21145]
### Describe the bug

The `package-native` command does not work for the devfile v2 Quarkus quick start Che sample project, because the [tools container](https://github.com/che-samples/quarkus-quickstarts/blob/743501d86e6e7b262029fbddbc141a77d541be5e/devfile.yaml#L5) does not have GraalVM installed.

#### Workaround
It can be installed by running `sdk install java 20.3.5.r11-grl && gu install native-image` in the tools container, but it would be great if the `package-native` command worked out-of-the-box (like the devfile v1 Quarkus sample).

### Che version

next (development version)

### Steps to reproduce

1. On the latest version of Che (with devworkspace engine), create a new devworkspace with the Quarkus sample:
![image](https://user-images.githubusercontent.com/83611742/153097824-4e45049d-bc7d-47d1-bdba-9b4e1905f149.png)

2. Run the `package-native` command:
![image](https://user-images.githubusercontent.com/83611742/153051768-f8cbf1f1-95d1-448b-ae36-1e6963bb4b80.png)
3. This results in the following error in the output:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.990 s
[INFO] Finished at: 2022-02-09T00:12:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.3.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:209)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 125
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:350)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:181)
[ERROR]         ... 10 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
Full output here: https://gist.github.com/dkwon17/51e312188a05ba407916c57400ec788e

### Expected behavior

Would have expected the native build to be successful, similar to the devfile v1 Quarkus sample.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by ibuziuk** [comment]
Just for the context, we are using the same image for the https://github.com/che-incubator/quarkus-api-example that we are going to use in the PR review blog post, and want to show case all quarkus capabilities including native builds. This issue is also related to https://github.com/eclipse/che/issues/18587

**Comment by svor** [comment]
New UDI with mandrel was built in quay.io/devfile/universal-developer-image:ubi8-3055e6d
