### ISSUE TITLE
New Che website - first iteration

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21149]
### Is your enhancement related to a problem? Please describe

@benoitf has created a draft of a [new website](https://tmp-ws-ch.surge.sh/) (source code https://github.com/benoitf/eclipse-che-website) that would replace the existing one that is outdated. In this issue we list the few things that need to be addressed before the new website can go live.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/606959/153234458-95662126-e68a-4ab9-8078-78b79b6a9e68.png">

### Describe the solution you'd like

- [x] Complete content @l0rd 
	- [x] Main page: 3 boxes of "Same Code, different IDE" section
	- [x] Features page: titles and subtitles
	- [x] How it works page: high level diagram footnote
	- [x] How it works page: dashboard and che server description
	- [x] How it works page: devworkspace opertor description
	- [x] How it works page: workspace components description
	- [x] Extend page: whitelabelling subtitle
	- [x] Extend page: git services section
	- [x] Extend page: samples section
	- [x] Main page: show blog post correct date in the "Discover" section @benoitf
- [ ] Language (english) review
- [ ] Global UX review
- [x] Add screenshots @benoitf 
    - [x] Main page: Add VS Code, IntelliJ, PyCharm screenshot (rotating animated gif)
    - [x] Main page: Software defined development environments add a devfile.yaml
    - [x] Features: Add an animated gif of debuggin in VS Code in the "Code,build, Test..." section
    - [x] Features: add a screenshot of a README with che badge in the "Share development setups with a URL"
    - [x] Features: Add "DEX" login screenshot in the "multi tenant" section
    - [x] Extend page: add a Che and CRW dashboard screenshot in the "Whitelabelling" section
   - [x] Extend: add a screenshot of the current dashboard samples in the "Add sample" section
- [x] Add icons @l0rd 
    - [x] Main page: "Same Code, different IDE" section, icons for VS 
Code, JetBrains IDEs (intellij and pycharm), Eclipse Theia
    - [x] Main page: "Try Ecipse Che online" logos java, go, python, react, .NET, Rust,...
    - [x] Main page: "Or try it on your Kubernete cluster" minikube, kind logos
    - [x] Features: add GitHub, BB, Gitlab icons in Git services
    - [x] Features: add an icon of Tux and of a container for section "IDEs are packaged and distributed as Linux containers".
    - [x] Features: add icons to represent restricted network, proxy, fips, enterprise TLS certs in section "Enterprise features"
    - [x] Extend: add icons of web IDEs that we do not include in the "Add IDE" section? (@benoitf: added temporary icons)
                original: Or a screenshot of the yaml of an editor definition 
    - [x] icons for Enjoy Development Again (easy/fast/cloud ready) @benoitf 
- [x] Add diagrams @benoitf 
    - [x] How it works: Add an high Level system diagram
    - [x] How it works: Add a devfile to devworkspace diagram in the "user dashboard and che server" section
        - input = devfile.yaml, output = devWorkspace
    - [x] How it works: Add a devworkspace to Kubernetes objects diagram in the "DevWorkspace" section
        - slide 15
    - [x] How it works: Add a workspace creation flow diagram
         - [archi](https://www.eclipse.org/che/docs/che-7/administration-guide/che-workspaces-architecture-with-che-server/#che-workspace-creation-flow_che)

**Comment by ibuziuk** [comment]
@l0rd @benoitf can we close the issue? the new website is up and running for more than 3 month ;-)

**Comment by benoitf** [comment]
but maybe that can be moved to a separate issue

**Comment by l0rd** [comment]
English review has been done and is in this [gdoc](https://docs.google.com/document/d/1zXtFsgvX9sj-zszwcXcqxzWCPpF5HDKiYzaKYTmqhG0/edit#heading=h.n6e8oipybe91). The changes haven't been applied to the website yet. We can close and open a separate issue or leave this one open.
