### ISSUE TITLE
Kubeconfig is not injected to any container on OpenShift

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21147]
### Describe the bug

Since https://github.com/eclipse-che/che-dashboard/pull/431 is merged, it is expected that `~/.kube/config` file is present in all containers, but now the file is missed.

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace.
2. Search for `~/.kube/config` file.
See: the file is not present in the user directory:
![screenshot-che-eclipse-che apps ci-ln-lkiw9k2-72292 origin-ci-int-gce dev rhcloud com-2022 02 09-12_35_12](https://user-images.githubusercontent.com/7668752/153186991-65c20950-8d6c-4391-b6f0-35eab5cbfd5e.png)

### Expected behavior

The kubeconfig file must be injected to all containers.

### Runtime

OpenShift, minikube

### Installation method

chectl/next

### Environment

macOS

**Comment by olexii4** [comment]
BTW: I can reproduce it with  '{che-server}/dashboard/api/swagger' on che-dogfooding instance.
![2022-02-09_14_08_40](https://user-images.githubusercontent.com/6310786/153198938-5ec015ab-7385-49b2-9d3c-b26d533523ba.png)

**Comment by vinokurig** [comment]
I still can't see the `~/.kube/config` file in Che deployed on minikube.

**Comment by ibuziuk** [comment]
@vinokurig for minikube see https://github.com/eclipse/che/issues/21171 feel free to comment in this issue
