### ISSUE TITLE
Overriding devfile values using factory parameters

### ISSUE THREAD

**Issue by martinelli-francesco** [eclipse/che#21148]
### Summary

I would like to customize my devfile in creating a workspace using a query string parameter, but it seems that with DevWorkspace it doesn't work. I tried following the guide at https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/#overriding-devfile-values- using-factory-parameters_che and change the name or generateName in the same way as the example but the generated workspace does not have the new name.

Is it supported? Is the syntax changed?

Actually, what I need is to simply get an environment variable set in query string to the containers.
So I thought about changing the name in the devfile so that the container instances have the env var `DEVWORKSPACE_NAME` set as requested by the user. Is there another way to do it? 

I am using version 7.43, kubernetes in EKS.

Thanks!

### Relevant information

I found an old issue about my question: https://github.com/eclipse/che/issues/18950

**Comment by benoitf** [comment]
Hello @martinelli-francesco, let's reopen https://github.com/eclipse/che/issues/18950
