### ISSUE TITLE
Che-IDEA should support opening a terminal into a sidecar container

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21140]
### Is your enhancement related to a problem? Please describe

When the user starts a workspace from a typical Devfile with a database,
(e.g.: https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml)
he/she needs to open a terminal into more than one container.

But Che-IDEA supports a terminal for the editor's container only.
So, there's no way to execute a command in a DB container's terminal.

### Describe the solution you'd like

It can be a plugin that adds the support for opening a terminal into the specified sidecar container using the machine-exec component. Like Che-Theia and Che-Code do.

### Describe alternatives you've considered

As this task is quite complex, first, we need to investigate how it can be implemented, e.g.: plugin API, some 3-rd party libraries, etc.

### Additional context

The related issue:
- https://github.com/eclipse/che/issues/21139

**Comment by l0rd** [comment]
@azatsarynnyy @vzhukovs if we could copy JetBrains IDEs and their dependencies in a volume and then execute it in the devfile container we would (partially) solve this problem. And we would make it work as VS Code. Is there a separate issue for this?

**Comment by azatsarynnyy** [comment]
@l0rd it was done within https://github.com/eclipse/che/issues/20863

**Comment by azatsarynnyy** [comment]
and for DS 3.0 https://issues.redhat.com/browse/CRW-2736

**Comment by l0rd** [comment]
@azatsarynnyy great!

**Comment by l0rd** [comment]
So I am closing #21354
