### ISSUE TITLE
Che-Code, Che-IDEA feature gap (compared to Che-Theia)

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21144]
This is a quick feature gap analysis to identify what's missing in Che-Code/Che-IDEA compared to Che-Theia.

:warning: What is not a goal of this analysis?
It's not intended to achieve complete feature parity between Che-Theia and Che-Code/Che-IDEA.

The main goal of this analysis is to identify the minimum set of base functionality that must be supported by Che-Code and Che-IDEA in order to satisfy the common developers' needs.

To identify the missing features I used one of the typical developer's scenarios:

1. Start a workspace with a Spring PetClinic Sample Application. https://github.com/azatsarynnyy/java-spring-petclinic/tree/devfilev2
2. Build the project.
3. Run a command in a non-editor container, like DB-container.
4. Run the built application and get the app preview link.
5. Debug the code, make some changes.
6. Open a terminal to a non-editor container to execute some commands.
7. Commit the code changes & push them to a remote repository.
8. Go back to the Dashboard, from IDE.

Running the Devfile commands (steps 2, 3, 4) must be possible with the Code's Task or IDEA's Run/Debug Configurations.

The comparison table below is to track the progress and have greater clarity of the missing features.
Che-Theia is present here as the desired state for Che-Code and Che-IDEA editors.

| IDE functionality | Che-Theia | Che-Code | Che-IDEA |
| --- | --- | --- | --- |
| Run a Devfile command in an editor container | :heavy_check_mark: | :heavy_check_mark: https://github.com/eclipse/che/issues/21030 | :heavy_check_mark: https://github.com/eclipse/che/issues/21029 |
| Run a Devfile command in a non-editor container | :heavy_check_mark: | :heavy_check_mark: https://github.com/eclipse/che/issues/21030 | :heavy_check_mark: https://github.com/eclipse/che/issues/21139 |
| Preview URL | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: https://github.com/eclipse/che/issues/21212 https://github.com/eclipse/che/issues/21141 |
| Terminal to a non-editor container | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: https://github.com/eclipse/che/issues/21140 |
| Git Commit & Push | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| Navigate to the Dashboard from IDE | :heavy_check_mark: | :heavy_check_mark: https://github.com/eclipse/che/issues/21130 | :heavy_check_mark: https://github.com/eclipse/che/issues/21137 |

:heavy_check_mark: - implemented | :heavy_multiplication_x: - not implemented | :runner: - work in progress

---

Note, some of these issues are part of the related epics:
- https://github.com/eclipse/che/issues/20500
- https://github.com/eclipse/che/issues/20591

**Comment by azatsarynnyy** [comment]
Update.
In 7.49:
for Che-Code, we've added running the Devfile commands in both editor and non-editor containers:
- https://github.com/eclipse/che/issues/21030

for Che-IDEA, it's possible to navigate to the Dashboard from IDE:
- https://github.com/eclipse/che/issues/21137

For 7.50, we're working on:
running a Devfile command in a non-editor container from Che-IDEA:
- https://github.com/eclipse/che/issues/21139

and preview URL features for Che-IDEA:
- https://github.com/eclipse/che/issues/21212
- https://github.com/eclipse/che/issues/21141

Updated the comparison table accordingly.

**Comment by vzhukovs** [comment]
Created the following PR to implement machine exec support: https://github.com/che-incubator/jetbrains-editor-images/pull/121 it can be tested by using factory link:

`https://che-host/#https://github.com/vzhukovs/vaadin-demo?che-editor=https://gist.githubusercontent.com/vzhukovs/95337765cbde9b6ed1f252e6e77671a2/raw/ce2508d6cd101d400a4b99cc788933ef5f7eff84/che-editor.yaml`

@azatsarynnyy @l0rd

**Comment by l0rd** [comment]
@azatsarynnyy @vzhukovs we can close this one now right?

**Comment by azatsarynnyy** [comment]
@l0rd yes, we've implemented all the missing features for both Che-Code and Che-IDEA. Closing it.
