### ISSUE TITLE
Update Che-Theia images to use Node.js 14

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21150]
### Is your task related to a problem? Please describe

Currently, Che-Theia runtime images are based on `node:12.20.1-alpine3.12` and `registry.access.redhat.com/ubi8/nodejs-12:1-104`.
Node.js 12 will reach EOL on 2022-04-30.

### Describe the solution you'd like

Need to upgrade Che-Theia runtime images to use Node.js 16 - the latest LTS release.

### Additional context

Node.js releases https://nodejs.org/en/about/releases/

**Comment by l0rd** [comment]
We are going to use nodejs 14 because some VS Code extensions may be not compatible with nodejs 16
