### ISSUE TITLE
Scala sample hangs when trying to be launched

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#21152]
### Describe the bug

It's possible to build the scala sample, but when trying to launch it, the sample hangs and does nothing.
When clicking on the corresponding endpoint, it says, that application is not available.

![Screenshot from 2022-02-10 12-17-36](https://user-images.githubusercontent.com/1655894/153389409-e553a4b2-cc5f-4cd1-8094-c7e8a0fe01ba.png)

![Screenshot from 2022-02-10 12-17-51](https://user-images.githubusercontent.com/1655894/153389427-59aae477-8d22-4f8b-a619-84d922aef169.png)

### Che version

next (development version)

### Steps to reproduce

1. Create workspace using https://github.com/che-samples/scala-sbt/tree/devfilev2
2. Build and then run the sample

### Expected behavior

Should display notification, that the application is launched and listening port 8080.

### Runtime

OpenShift

**Comment by svor** [comment]
remove-lifecycle stale
