### ISSUE TITLE
Don't use built-in VS Code logic for reopening last opened workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21151]
### Describe the bug

Che-Code tries to reopen the last opened folder despite it was opened in another Che Workspace.

The root cause of the problem is that Che-Code stores the last opened folder in the browser's local storage, see `workspaces.lastOpened` key.

The UX is really confusing. See the attached screenshot.

### Che version

next (development version)

### Steps to reproduce

1. Create two Che workspaces with different projects. For both, use Che-Code as an editor.
2. Open and close the first workspace. Then, open the second workspace.
3. When opening the second workspace, Che-Code tries to open the folder that was last opened in the first workspace.

### Expected behavior

Che-Code should open the folder defined by the Devfile.

It can ignore what is stored in the local storage. Or it can skip storing the info, so nothing to reopen from the VS Code built-in logic.
Only [che-on-start extension](https://github.com/che-incubator/che-code/tree/main/code/extensions/che-on-start) should decide what folder to open on the next IDE start.

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/1636395/153353477-10e95329-593a-49c6-ad14-d5eff8347bb2.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
fixed
