### ISSUE TITLE
devfile 2 convertor is generating invalid components

### ISSUE THREAD

**Issue by sunix** [eclipse/che#21167]
### Describe the bug

devfile 2 convertor is generating invalid components

### Che version

next (development version)

### Steps to reproduce

1. create a workspace from https://github.com/eclipse/jkube
![Selection_614](https://user-images.githubusercontent.com/650571/154076335-8b354b4e-6dd5-4c83-b263-bfec4976e413.png)

2. it cannot start with the errors
```
1 error occurred: * duplicate key: www
```
![Selection_616](https://user-images.githubusercontent.com/650571/154076961-ed86e23e-407e-404c-bb8a-5417596b292c.png)
![Selection_617](https://user-images.githubusercontent.com/650571/154076980-79965053-31cc-400f-958d-7be7ef9aa945.png)

3. it is because it has generated invalid components like

```
  - name: m2
    volume: {}
  - name: www
    volume: {}
  - name: kube
    volume: {}
  - name: www
    volume: {}
  - name: www
    volume: {}

```
![Selection_618](https://user-images.githubusercontent.com/650571/154077317-1789a4c4-ef2e-46c4-8a03-3d8e04771c87.png)

### Expected behavior

it should start the workspace

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Red Hat internal Che instance.

**Comment by ibuziuk** [comment]
@benoitf could you please take a look?
