### ISSUE TITLE
Persistent Volume strategies: add “per workspace”

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21185]
### Is your enhancement related to a problem? Please describe

The only possible PVC strategy is “common”. But that doesn’t allow users to run more than one workspace at a time 

### Describe the solution you'd like

We should support another PV strategy: per workspace. This strategy associates a new PV to every new workspace

**Comment by ibuziuk** [comment]
Closing
DWO issue has been closed - https://github.com/devfile/devworkspace-operator/issues/792
