### ISSUE TITLE
Eclipse-che workspace(s) restarts randomly(?)

### ISSUE THREAD

**Issue by celalsahin** [eclipse/che#21191]
### Summary

We have an eclipse-che (7.39.2) installed on EKS (v1.21.5-eks-bc4871b).
On our productive instance developers face random restarts of their workspaces while they are actively working on the tab. Restart of the workspace results in "the default project and branch are loaded into the tab." & in lower left you can see that default project of the workspace is shown although you have been working on a different project before the restart. 

Currently we have two instances, one is productive which already has load & one that staging where practically no one works. This behavior happens on our productive instance but not on our staging environment. Currently our guess is this is sth. due to load but I cannot find anything in the logs/events regarding this. 

Checking events shows that the workspace pod is not rescheduled after initially spinning up. workspace pod logs mentions connection issues but it is during the restart of the workspace, so not sure if this is a cause or a result. 

Reading debug ingress logs also did not produce any fruit :(

Would be great if someone can point to a direction where we can extend our investigations.

**Comment by svor** [comment]
@celalsahin could you please provide logs when the restart is happening: https://www.eclipse.org/che/docs/che-7/administration-guide/collecting-logs-using-chectl/

**Comment by celalsahin** [comment]
Thanks a lot for the quick feedback!

1 - Please see attached workspace pod logs, right when the restart is happening (so you have an alignment/timestamp when checking other logs): (around 15:18:24 UTC) [workspace_pod_logs.txt](https://github.com/eclipse/che/files/8110371/workspace_pod_logs.txt)
2 - Please find the logs as requested also from eclipse-che namespace:  
[eclipse_che_namespace_logs.tar.gz](https://github.com/eclipse/che/files/8110382/eclipse_che_namespace_logs.tar.gz)

**Comment by svor** [comment]
@celalsahin one more question: have you tried to upgrade Che? 7.39.2 version is a bit outdated

**Comment by celalsahin** [comment]
Sorry for the late reply - I will get back as soon as I do the update, as this is a productive instance & the pre-requisite is:
"Shut down all workspaces"
from [1] it might take some time to test, arrange the downtime etc.
[1]https://www.eclipse.org/che/docs/che-7/installation-guide/upgrading-che-using-the-cli-management-tool/
