### ISSUE TITLE
Add a resource monitoring extension for VS Code based Che workspaces

### ISSUE THREAD

**Issue by svor** [eclipse/che#21207]
### Is your task related to a problem? Please describe

Currently Che-Code doesn't have a mechanism to monitor resources of the workspace, we need to provide the same functionality which we have in Che-Theia.

### Describe the solution you'd like

Create **che-resource-monitor** extension in Che-Code, it could be transferred from [Che-Theia plugin](https://github.com/eclipse-che/che-theia/tree/main/plugins/resource-monitor-plugin) 

### Release Notes Text

The resource monitoring extension tracks memory and cpu usage of the different components of a Che workspace. This is now a built-in extension of Che Code, the build of VS Code (Code OSS) for Che workspaces.

**Comment by nickboldt** [comment]
che-code not in DS 3 yet, so no N&N for downstream needed
