### ISSUE TITLE
[che-code] Add che-github-auth extension into che-code

### ISSUE THREAD

**Issue by svor** [eclipse/che#21206]
### Is your task related to a problem? Please describe

Che-Code should support GitHub auth flow and have an ability to get a GitHub token.

### Describe the solution you'd like

Add a new **che-github-auth** extension into che-code and transfer all functionality which we have in [che-theia](https://github.com/eclipse-che/che-theia/tree/main/plugins/github-auth-plugin)

**Comment by vinokurig** [comment]
fixed by https://github.com/che-incubator/che-code/pull/39
