### ISSUE TITLE
Airgap verification of the latest Eclipse Che with DevWorkspace engine enabled 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21205]
We need to make sure that Eclipse Che functions correctly in an air-gapped cluster and document any issues or additional requirements that are needed. DWO standalone has been verified already as part of https://github.com/devfile/devworkspace-operator/issues/668

**Comment by ibuziuk** [comment]
@ScrewTSW @musienko-maxim FYI

**Comment by ScrewTSW** [comment]
This was verified using DWO 0.13 and Che 7.45 on OCP 4.9
Deployment worked as expected, only issue I encountered was starting a workspace, and that was probably because of mirrorring. I'm missing some images required for workspace start

```
Failed to pull image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.45.0": rpc error: code = Unknown desc = pinging container registry quay.io: Get "https://quay.io/v2/": Forbidden
```

I consider this a successful test of the issue at hand.
