### ISSUE TITLE
[plugin-registry] Adapt nightly E2E tests on OS CI

### ISSUE THREAD

**Issue by svor** [eclipse/che#21210]
### Is your task related to a problem? Please describe

For now nightly tests of che-plugins-registry fail on OS CI https://prow.ci.openshift.org/?repo=eclipse-che%2Fche-plugin-registry

### Describe the solution you'd like

All plugins tests should be adapted to run with DevWorkspace.

**Comment by SkorikSergey** [comment]
We still need to adapt next tests:
- InstallPluginUsingUI
- JavaPlugin
- PhpPlugin
- PythonPlugin
- VscodeKubernetesPlugin
- VscodeShellcheckPlugin
- VscodeValePlugin
- VscodeXmlPlugin
- GitHubPullRequestPlugin

**Comment by svor** [comment]
Also need to fix:
- VscodeYamlPlugin
- TypescriptPlugin
