### ISSUE TITLE
Integrate My Web application with Eclipse Che IDE

### ISSUE THREAD

**Issue by csa-nathan** [eclipse/che#21213]
### Summary

Have a multi-user web application. Want to integrate Eclipse Che IDE running in Azure (Version 7.41.0) from web application.

On click of a link / button from my web application, it should (without asking for login credentials, maybe the credentials can be passed while invoking) invoke the Eclipse Che with a pre-defined workspace from Git Repo URL... 

How to achieve it? 

As Eclipse Che IDE is browser based IDE, can it be invoked through API call? 

The Git Repo URL may be a small Python / Java /.NET tasks / app.   For each user, it may vary. I mean for user1 it should load Python app with the corresponding workspace in Eclipse Che and for user 2 it should load Java App and so on...

In a way want to seamlessly integrate Eclipse Che IDE with my web application...

Looking forward for a solution /approach...

**Comment by nils-mosbach** [comment]
Workspaces are defined by devfiles that are part of the projects. Have you tried using factory links? That actually starts a workspace and displays the IDE when its ready. We've placed "open in che" links in our git projects.

`https://my-local-che.dev/#https://github.com/..../repo.git`

So every project can have its own devfile.yaml. If all of these sources are part of one project I would prepare a workspace that contains tooling for all languages. I you look at current ubi-dev-images these already contain java, python, etc.
