### ISSUE TITLE
Installing Che on Google Cloud Platform

### ISSUE THREAD

**Issue by wbondarchuk** [eclipse/che#21225]
### Summary

Hello, I'm installing Che on gcp. I got to the point Installing cert-manager on Kubernetes and ran into a problem on the 5th point. I don't understand what and where I need to check. The screenshot is not clear. (attached is a screenshot from the guide and my GCP). After skipping point 5, I went further and got errors (in the attached file). Before that, there were no problems. What is worth seeing and what could be the problem?

### Relevant information

![dns-challenge-gcp](https://user-images.githubusercontent.com/55180931/156154254-80934762-4c16-4af7-9849-db1aecd7a762.png)
![Снимок экрана от 2022-03-01 17-36-58](https://user-images.githubusercontent.com/55180931/156154265-8bf97693-f560-479f-8d01-22e858853ca5.png)
![Снимок экрана от 2022-03-01 17-36-43](https://user-images.githubusercontent.com/55180931/156154268-cf00efb5-eb2f-4ebc-8bc4-32ab143f422a.png)

**Comment by wbondarchuk** [comment]
[gcplogs.docx](https://github.com/eclipse/che/files/8160891/gcplogs.docx)

**Comment by sassyMatter** [comment]
@wbondarchuk did you find any solution to it eventually. I am also trying to follow along the same guide
