### ISSUE TITLE
Theia 7.44.0 build failed to compile 

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21223]
### Describe the bug

```
Error: [compile] src/github-auth-plugin.ts(19,55): error TS2345: Argument of type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: theia.Event<theia.AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is not assignable to parameter of type 'AuthenticationProvider'.
[compile]   Type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: Event<AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is missing the following properties from type 'AuthenticationProvider': createSession, removeSession
[compile] error Command failed with exit code 2.
```

-- https://github.com/eclipse-che/che-theia/runs/5362752467?check_suite_focus=true

### Che version

7.44.0

### Steps to reproduce

1. https://github.com/eclipse-che/che-theia/actions/workflows/release.yml
2. GHA fails
3. see log

### Expected behavior

1. https://github.com/eclipse-che/che-theia/actions/workflows/release.yml
2. GHA passes
3. branch created; new images pushed to Quay, new nodejs package published

### Eclipse Che Logs

See https://github.com/eclipse-che/che-theia/actions/runs/1911409438

**Comment by nickboldt** [comment]
Failure could be related to https://github.com/eclipse-che/che-theia/commit/7124cd944c1901f055eedeeff56285a3ddeb0768#annotation_2860286957 cc: [RomanNikitenko](https://github.com/eclipse-che/che-theia/commits?author=RomanNikitenko)

**Comment by benoitf** [comment]
It's related to https://github.com/eclipse-che/che-theia/blob/main/plugins/github-auth-plugin/package.json#L20

**Comment by nickboldt** [comment]
Fix pushed to 7.44.x branch and build triggered in https://github.com/eclipse-che/che-theia/actions/runs/1911874689 while we wait for the above PR to get checked and merged

**Comment by nickboldt** [comment]
aaaaand it failed again.

{code}
Error: [compile] src/github-auth-plugin.ts(19,55): error TS2769: No overload matches this call.
[compile]   Overload 1 of 3, '(provider: AuthenticationProvider): Disposable', gave the following error.
[compile]     Argument of type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: theia.Event<theia.AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is not assignable to parameter of type 'AuthenticationProvider'.
[compile]       Type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: Event<AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is missing the following properties from type 'AuthenticationProvider': createSession, removeSession
[compile]   Overload 2 of 3, '(provider: AuthenticationProvider): Disposable', gave the following error.
[compile]     Argument of type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: theia.Event<theia.AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is not assignable to parameter of type 'AuthenticationProvider'.
[compile]       Type '{ id: string; label: string; supportsMultipleAccounts: false; onDidChangeSessions: Event<AuthenticationProviderAuthenticationSessionsChangeEvent>; getSessions: () => Promise<...>; login: (scopes: string[]) => Promise<...>; logout: (id: string) => Promise<...>; }' is missing the following properties from type 'AuthenticationProvider': createSession, removeSession
[compile] error Command failed with exit code 2.
[compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[compile] yarn compile exited with code 2
{code}

-- https://github.com/eclipse-che/che-theia/runs/5364053326?check_suite_focus=true

**Comment by benoitf** [comment]
2 PRs: https://github.com/eclipse-che/che-theia/pull/1326 and https://github.com/eclipse-che/che-theia/pull/1327 (one for main branch and the other one for 7.44.x)

**Comment by nickboldt** [comment]
Running release against 7.44.x branch: https://github.com/eclipse-che/che-theia/actions/runs/1916188785
Running next build against main branch: https://github.com/eclipse-che/che-theia/actions/runs/1916184094

**Comment by nickboldt** [comment]
both builds are green! thanks for the assist, @benoitf !
