### ISSUE TITLE
Eclipse Che4z deprecation

### ISSUE THREAD

**Issue by zeibura** [eclipse/che#21243]
The Che4z basic and premium stacks are now deprecated and no longer supported. The mainframe extension package is now only offered on VS Code.

The individual open source plug-ins from the package (i.e. [COBOL Language Support](https://github.com/eclipse/che-che4z-lsp-for-cobol/), [HLASM Language Support](https://github.com/eclipse/che-che4z-lsp-for-hlasm) and [Explorer for Endevor](https://github.com/eclipse/che-che4z-explorer-for-endevor)) will remain open-source.

This means:
- Currently the Che4z basic stack (mainframe basic stack) is included as part of Che. It would be good if it can be removed from the next release, if this is possible.
- This page should be removed from Che docs: https://www.eclipse.org/che/docs/che-7/extensions/eclipse-che4z/
- This repository should be deleted: https://github.com/eclipse/che-che4z (I'm not sure if we can do this or if someone from Eclipse has to)
- This page: https://projects.eclipse.org/projects/ecd.che.che4z should be edited to describe the three individual open-source plug-ins rather than the Che4z stacks. I can edit this page and run the new wording past anyone who'd like to review it.

**Comment by l0rd** [comment]
> This repository should be deleted: [eclipse/che-che4z](https://github.com/eclipse/che-che4z) (I'm not sure if we can do this or if someone from Eclipse has to)

You need to [open a ticket ](https://gitlab.eclipse.org/eclipsefdn/helpdesk/) for that.

**Comment by l0rd** [comment]
@zeibura if you can and want provide them, it would be interesting to know the reasons for this decision.

**Comment by zeibura** [comment]
> > This repository should be deleted: [eclipse/che-che4z](https://github.com/eclipse/che-che4z) (I'm not sure if we can do this or if someone from Eclipse has to)
> 
> You need to [open a ticket ](https://gitlab.eclipse.org/eclipsefdn/helpdesk/) for that.

Thanks. We are going to hold off on deleting the doc page and the repo until everything else is done - I can make that PR to che/docs myself.

**Comment by zeibura** [comment]
Closing this as the decision to completely remove Che4z is being reconsidered.

**Comment by l0rd** [comment]
@zeibura let us know if you want to have a discussion around the roadmap and the future of Che and Che4z
