### ISSUE TITLE
Is it possible to configure custom annotations for che/workspace pods?

### ISSUE THREAD

**Issue by celalsahin** [eclipse/che#21257]
### Summary

I would like to be able to setup eclipse-che in a way that when it spins up any pod, it will be annotated with a custom tag, 
e.g.
"cluster-autoscaler.kubernetes.io/safe-to-evict": false.

Idea is to avoid EKS autoscaler to avoid evicting workspace/che pods hence not causing restarts/downtime for developers actively working.

**Comment by tolusha** [comment]
@celalsahin 
We have this [1] and this [2]. Does it solve your issue?
[1] https://github.com/eclipse-che/che-operator/blob/main/config/crd/bases/org_v1_che_crd.yaml#L1027
[2] https://github.com/eclipse-che/che-operator/blob/main/config/crd/bases/org_v1_che_crd.yaml#L1033

**Comment by celalsahin** [comment]
Checking the documentation/options - I see that for this[1] to work we will need to have a publicly available devfile & it is quite an abrupt way(adapting URLs etc...) to create a workspace for whole development. Even with that we just get an annotated deployment & not pod - that means that workspace pod can be evicted due to auto-scaling. 

Do you have any proposal/best practice to work with auto-scaler, for eclipse-che of course? We simply want to avoid developers' workspaces getting restarted when a node is scaled down. 

[1]https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/#allowing-users-to-define-workspace-deployment-labels-and-annotations_che
