### ISSUE TITLE
Including GitHub CLI and GLab as defaults that are CLI alternatives to GH/GL exenstions for IDEs

### ISSUE THREAD

**Issue by max-cx** [eclipse/che#21253]
### Is your task related to a problem? Please describe

Possible use cases:
(a) covering an unlimited number of IDEs that do not have any GH/GL extensions
(b) the lightweight editors Vim and Nano can be included for terminal-only use

### Describe the solution you'd like

I suggest adding these two CLI tools as defaults someplace like the UDI to have them as defaults in a workspace as a parallel option to various GH/GL extensions/plugins for various IDEs:
https://cli.github.com/
https://glab.readthedocs.io/en/latest/intro.html

### Describe alternatives you've considered

Advantages:
These two CLI tools may offer more GH/GL features/commands inside a workspace than the GH/GL extensions, and that is without having to include a full-size IDE like VS Code.

**Comment by l0rd** [comment]
Note that GitHub CLI is already part of the [universal developer image](https://github.com/devfile/developer-images/#developer-base-image) so this issue should be for GLab only.
