### ISSUE TITLE
"Init Container project-clone has state CrashLoopBackOff" error when start "Java Spring Boot" workspace in Che dogfooding instance

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21261]
### Describe the bug

Dashboard showed "**Init Container project-clone has state CrashLoopBackOff**" error when start "_Java Spring Boot_" workspace in Che dogfooding instance https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard :
```
Initializing DevWorkspace
Preparing networking
Preparing services
Networking ready
Waiting for DevWorkspace ServiceAccount
Waiting for workspace deployment
Preparing networking
Networking ready
Waiting for workspace deployment
Networking ready
Waiting for workspace deployment
Init Container project-clone has state CrashLoopBackOff
```
![Screenshot from 2022-03-15 12-16-54](https://user-images.githubusercontent.com/1197777/158357481-1ea0cf01-a576-470b-aa0b-0fb0bc97bb33.png)

### Che version

next (development version)

### Steps to reproduce

1. Go to Che dogfooding instance https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard
2. Start "**Java Spring Boot**" workspace.

### Expected behavior

"**Java Spring Boot**" workspace has started successfully.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
@dmytro-ndp seems to work just fine for me, could you provide some logs / openshift events?

**Comment by dmytro-ndp** [comment]
@ibuziuk : I wasn't able to restart workspace:
![Screenshot from 2022-03-16 10-35-12](https://user-images.githubusercontent.com/1197777/158598687-26f2ad07-d778-4354-a0fc-f61038ec3ff2.png)

At the same time new `Java Spring Boot` workspace has started successfully.

**Comment by ibuziuk** [comment]
O_O @amisevsk have you seen smth. like that before ^

**Comment by amisevsk** [comment]
I haven't directly, but the FailedMount error looks to be a cluster hiccup -- DWO/Che does nothing to manage the `kube-api-access-xxxxx` volume so if it's failing to mount I assume the cluster hit some block somewhere.

I've tested the devfile in our dogfooding cluster and the workspace started without issue.

Also, in the future, to debug issues like `Init Container project-clone has state CrashLoopBackOff`, you can add the annotation `controller.devfile.io/debug-start: "true"` to the DevWorkspace object. This stops DWO from removing the DevWorkspace pod on failure, allowing you to check the logs (`kubectl logs <workspaceID>-xxxxx-xxxxx -c project clone`)
