### ISSUE TITLE
OVH - Internal Server Error occurred on Che pod with user from identity provider 

### ISSUE THREAD

**Issue by EnergieZ** [eclipse/che#21263]
### Describe the bug

I'm having a strange behavior with eclise che, when triing to login throw identity provider.

When login with the initial user in keycloak (so no external identity provider), all seems to be ok : dashboard show ups, and i can launch some dev spaces.

When logging with gitlab (throw keycloak), at the fist time I need to complete some informations : username, email, ect...
That fine. 
Then I have a 500 error because email is not verified (even if I configure the identity provider is configured with "Trust Email").
Gooing to the admin area to declare this new user as "email verified", then login into eclipse dahsbord with this user.

I then have a white page ! Checking the browser console, I can see some ajax call failing : 
POST https://ide.dev.seven-group.com/api/kubernetes/namespace/provision => {"message":"Internal Server Error occurred, error time: 2022-03-15 12:49:07"}

Checking the logs of che pod, I can see this error : 

```
2022-03-15 12:49:07,526[nio-8080-exec-7]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2022-03-15 12:49:07
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://x.x.x.x/api/v1/namespaces/my-email-che-xxxx/secrets/workspace-credentials-secret. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "workspace-credentials-secret" is forbidden: User "https://mydomain.com/auth/realms/eclipse-che-k8s-oidc-authentication#xxxx-xxxx-xxxx-xxx" cannot get resource "secrets" in API group "" in the namespace "my-email-che-xxxxx".
```

I'm fighting with eclipse che since sevral days to install it on my mangaed kubernetes (by OVH), facing multiple problems :/ Deleting keyxloax from eclipse che may not be the best solution...

### Che version

7.44@latest

### Steps to reproduce

1. login for the first time with an identity provider throw keycloax
2. complete the form about your username, email, ect, and validate
3. go back to keycloax admin to declare "email verified" to this new user
4. login again in eclipse che

### Expected behavior

Should have eclipse dashboard showing up

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell
2022-03-15 12:49:07,526[nio-8080-exec-7]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2022-03-15 12:49:07
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://x.x.x.x/api/v1/namespaces/my-email-che-xxxx/secrets/workspace-credentials-secret. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "workspace-credentials-secret" is forbidden: User "https://mydomain.com/auth/realms/eclipse-che-k8s-oidc-authentication#xxxx-xxxx-xxxx-xxx" cannot get resource "secrets" in API group "" in the namespace "my-email-che-xxxxx".
```

### Additional context

Installed on kubernetes managed by OVH. 
OIDC is ok

**Comment by sparkoo** [comment]
I don't understand the repro steps. Keycloak is no longer part of Che deployment. For custom OIDC provider, you need to setup Kubernetes and Che to same OIDC https://github.com/eclipse/che/issues/21049#issuecomment-1022108499 or https://github.com/eclipse/che/issues/21049#issuecomment-1067776895

**Comment by EnergieZ** [comment]
I know keycloax isn't part of eclipse che any more.
I have install it, and configure oidc on K8S api.

The first user I have created on keycloax works well.

I've tried to create a second user, with out and identity provider : same problem with this new user.

My guess is that their is a problem on the oidc part. What does eclipse che exacly need ? 
I can see on K8S that each new user has his own : 
 - namespaces
 - configmap (kube-root-ca.crt)
 - secret (default-token)
 - 
 - service account (name default)
 - Role binding (2, including one with devworkspace)

Their is no deployment, no pods, no ingress for namespaces off these new users.

I'm checking every thing since few days, and can't see what is missing, or if it's a bug ! 

Thank you for your help

**Comment by EnergieZ** [comment]
Hi,

Do you have any update about this problem ? Do you need any more informations ?

**Comment by Ryder05** [comment]
> 

Hello, I need to deplot eclipse che on a  full managed k8s cluster from OVH, I deployed keycloak in the"kube-system" namespace, then i added a realm and client called kubernetes  but when i try to deploy it says "API server is not configured with OIDC Identity Provider"

**Comment by EnergieZ** [comment]
you have to configure it from OVH panel : 
![image](https://user-images.githubusercontent.com/1869463/158841520-d8bf0e35-72b2-4f09-9920-74b32c982993.png)

then use chectl with option "--bypass-oidc-check" (don't remeber th e exact name) to deploy the server.
Note that you must install keycloax before. 
You have an OVH tuto here : https://docs.ovh.com/gb/en/kubernetes/installing-keycloak/

**Comment by EnergieZ** [comment]
@sparkoo how can I help to solve this bug ?
