### ISSUE TITLE
che-dashboard configurable Kubernetes endpoint

### ISSUE THREAD

**Issue by cristian-radu** [eclipse/che#21260]
### Is your enhancement related to a problem? Please describe

It is not possible to run Eclipse Che 7.43 on GKE due to OIDC being required and no way to configure a different Kubernetes master endpoint. 

https://github.com/eclipse/che/issues/21049#issuecomment-1067776895

### Describe the solution you'd like

I would like the option to be able to configure the Kubernetes master endpoint for the che-dashboard.

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse-che/che-operator/pull/1468
