### ISSUE TITLE
Identify and deliver minimal administration guide, installation guide, and user guide to migrate to che-docs master branch

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21264]
### Is your task related to a problem? Please describe

In the che-docs `master` branch, we started a fresh documentation for Che using the Devworkspace engine only.

### Describe the solution you'd like

We need to migrate docs from the che-docs `master` branch that are still relevant.

### Describe alternatives you've considered

Blog posts are not covering everything https://github.com/eclipse-che/blog/issues/19

### Additional context

STEP 1: Remove obsolete sections considered

- #21270
- #21271
- #21273
- #21286

STEP 2: Update remaining content

- #21272
- #21283
- #21284
- #21285

STEP 3: Add new content (not required for v3.0, described in a separate issue)

**Comment by nickboldt** [comment]
`customizing registries` ... that section is SOOO outdated/broken

`backup-restore` can be ripped out, that's not supported w/ DW

`minikube` stuff not relevant to downstream

`differences-in-how-che-theia-webview-works-on-a-single-host-mode-comparing-to-a-multi-host-mode` didn't we drop support for one of those modes? @l0rd ?

`authoring-devfiles-version-1` - likely remove this as we don't want to encourage use of deprecated standards

why is this a "no"? `[NO] installing-che-on-openshift-4-using-operatorhub` -- that's 100% supported and recommended, as is the cli method

kubespray, gcp, and azure? I don't think those are supported. AWS is only supported in the context of ROSA afaik @RickJWagner ?

I'd remove the whole "running-che-locally" section as that's prone to problems. maybe keep codeready containers if @l0rd  agrees ?

`setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page` NO - sso/keycloak is not supported in DevSpaces 3 / anything with DW

`enabling-dev-workspace-operator` isn't needed as it's on by default

`upgrading-che-namespace-strategies-other-than-per-user` I suspect this is no longer supported - please check with @l0rd or @ibuziuk or @dmytro-ndp 

`rolling-back-a-che-upgrade` not sure if this is possible with DW, as backup-restore is not supported

**Comment by RickJWagner** [comment]
Re: AWS support:  Yes, we support on AWS (outside of ROSA).
We also test/develop/replicate in this environment (via cluster-bot).

**Comment by nickboldt** [comment]
To help map the blog posts to the future Guides, I've added a *Guides* column to the list of blogs. https://github.com/eclipse-che/blog/issues/19#issuecomment-1068674569 It is subject to interpretation / edit by various owners/stakeholders. WDYT @themr0c @l0rd ?

**Comment by l0rd** [comment]
Created a new issue for contributing and extensions https://github.com/eclipse/che/issues/21286. Cleaned up the description.
