### ISSUE TITLE
Installation guide: remove content for unavailable features on instances with devworkspace, in the master branch

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21271]
### Is your task related to a problem? Please describe

Installation guide to document only instances with devworkspace.

### Describe the solution you'd like

Installation guide: remove content for unavailable features on instances with devworkspace, in the `master` branch.

Here is the current list of the install guide articles. 
In **bold** the ones to remove: those that to eventually resume have the **[TEMP]** suffix, the rest has **[DEFINITIVE]** suffix.

* [ ] supported-platforms
* [ ] configuring-the-che-installation
* [ ] installing-che
  * [ ] installing-che-in-cloud
      * [ ] installing-che-on-openshift-4-using-operatorhub
      * [ ] installing-che-on-openshift-4-using-cli
      * [ ] **installing-che-on-openshift-3-using-the-operator [DEFINITIVE]**
      * [ ] **installing-che-on-kubespray [TEMP]**
      * [ ] **installing-che-on-aws [TEMP]**
      * [ ] **installing-che-on-google-cloud-platform [TEMP]**
      * [ ] **installing-che-on-microsoft-azure [TEMP]**
  * [ ] running-che-locally
      * [ ] installing-che-on-codeready-containers
      * [ ] **installing-che-on-docker-desktop [TEMP]**
      * [ ] installing-che-on-minikube
      * [ ] **installing-che-on-minishift [DEFINITIVE]**
      * [ ] **installing-che-on-kind [TEMP]**
  * [ ] using-the-chectl-management-tool
  * [ ] installing-che-in-a-restricted-environment
* [ ] advanced-configuration
  * [ ] advanced-configuration-options-for-the-che-server-component
  * [ ] configuring-namespace-strategies
  * [ ] **configuring-storage-strategies [TEMP]**
  * [ ] **configuring-storage-types [TEMP]**
  * [ ] **configuring-the-number-of-workspaces-that-a-user-can-run [TEMP]**
  * [ ] configuring-the-number-of-workspaces-that-a-user-can-create
  * [ ] **configuring-workspace-exposure-strategies [DEFINITIVE]**
  * [ ] configuring-workspaces-nodeselector
  * [ ] configuring-che-hostname
  * [ ] configuring-ingresses
  * [ ] configuring-routes
  * [ ] deploying-che-with-support-for-git-repositories-with-self-signed-certificates
  * [ ] installing-che-using-storage-classes
  * [ ] importing-untrusted-tls-certificates
  * [ ] **configuring-communication-between-che-components [DEFINITIVE]**
  * [ ] **setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page [DEFINITIVE]**
  * [ ] mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container
  * [ ] **enabling-dev-workspace-operator [DEFINITIVE]**
* [ ] upgrading-che
  * [ ] upgrading-che-using-operatorhub
  * [ ] upgrading-che-using-the-cli-management-tool
  * [ ] upgrading-che-using-the-cli-management-tool-in-restricted-environment
  * [ ] **upgrading-che-namespace-strategies-other-than-per-user [DEFINITIVE]**
  * [ ] **rolling-back-a-che-upgrade [DEFINITIVE]**
* [ ] uninstalling-che
 

### Describe alternatives you've considered

Start from scratch in the main branch.

**Comment by pmkovar** [comment]
Cloned in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3881
