### ISSUE TITLE
Remove references to jwtproxy and plugin-broker GitHub repositories

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21275]
### Is your task related to a problem? Please describe

Although [JWT Proxy](https://github.com/eclipse/che-jwtproxy) and the [plugin broker](https://github.com/eclipse/che-plugin-broker) are not used anymore since Che 7.42 (i.e. the switch to DevWorkspace Operator) they cannot be archived as they are still referenced in Che Operator CSV and tagged at every release by the build process.

### Describe the solution you'd like

- [x] Remove any reference to [JWT Proxy](https://github.com/eclipse/che-jwtproxy) and the [plugin broker](https://github.com/eclipse/che-plugin-broker) from Che Operator CSV (may already be done as part of #20758)
- [x] Adapt the build process to avoid tag/branch/update those images
- [x] Open an [eclipse.org ticket](https://gitlab.eclipse.org) to archive the repositories

**Comment by nickboldt** [comment]
Downstream https://issues.redhat.com/browse/CRW-2830

**Comment by l0rd** [comment]
@nickboldt @tolusha We are not referencing and releasing those 2 components anymore right? If you confirm I will create an eclipse.org ticket to archive the github repositories.
