### ISSUE TITLE
User guide: remove content for unavailable features on instances with devworkspace, in the master branch

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21273]
### Is your task related to a problem? Please describe

User guide to document only instances with devworkspace.

### Describe the solution you'd like

User guide: remove content for unavailable features on instances with devworkspace, in the `master` branch.

Here is the current list of the user guide articles. 
In **bold** the ones to remove: those that to eventually resume have the **[TEMP]** suffix, the rest has **[DEFINITIVE]** suffix.

* [ ] **Navigating Che [DEFINITIVE]**
* [ ] **Che-Theia IDE basics [DEFINITIVE]**
* [ ] **Using Developer workspaces [DEFINITIVE]**
* [ ] **Customizing Development Environments [DEFINITIVE]**
* [ ] TroubleShooting Che
  * [ ] Viewing Che workspaces logs
  * [ ] **Investigating failures at workspace start using the verbose mode [DEFINITIVE]**
  * [ ] Troubleshooting slow workspaces
  * [ ] Troubleshooting network problems
 
### Describe alternatives you've considered

Start from scratch in the main branch.

**Comment by pmkovar** [comment]
Cloned in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3882
