### ISSUE TITLE
Minimal hosted-che guide for the che-docs master branch 

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21272]
### Is your task related to a problem? Please describe

Minimal hosted-che guide for the che-docs main branch 

#### Hosted che

* [ ] hosted-che
  * [ ] try-in-web-ide-github-action.Installation Guide

**Comment by nickboldt** [comment]
Engineering ownership: controller team / Ilya + Angel

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse-che/che-docs/pull/2236
