### ISSUE TITLE
che-operator should propagate trusted CA certs to the che-dashboard

### ISSUE THREAD

**Issue by cristian-radu** [eclipse/che#21278]
### Describe the bug

The che-dashboard as deployed by the che-operator 7.43.0 does not trust the CA certificates defined in the `che-trust` ConfigMap.

It is not possible for a user to make this change themselves (without forking the dashboard) since the operator will overwrite any changes that are made to the che-dashboard Deployment object.

The che-dashboard needs to trust the certificate on the devworkspace controller webhook server. In my case, this is not a public certificate and results in the dashboard being unable to create workspaces with error: "x509: certificate signed by unknown authority" 

### Che version

7.43

### Steps to reproduce

Deploy Che using the operator and certificates signed by an internal (non-public) CA.

### Expected behavior

The che-dashboard should work and be able to create workspaces without errors.

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by amisevsk** [comment]
Hi @cristian-radu, thanks for reporting this issue. I have some initial questions:

* Could you clarify how you have installed Che in your cluster (e.g. via `chectl server:deploy <...>`, etc.). 
* Is this issue present if you use the current Che release (7.45.0)?
* In regards to 
    > dashboard being unable to create workspaces with error: "x509: certificate signed by unknown authority"

    where are you seeing this error? Could you share a screenshot?

I've marked this issue as a P1 for now as propagating certificates to the dashboard is important. However, I'm not clear about 

> The che-dashboard needs to trust the certificate on the devworkspace controller webhook server.

To my knowledge, the che-dashboard should never need to call the devworkspace controller webhook server directly, as it is generally only called by the Kubernetes apiserver to validate requests. This webhook server also shouldn't be impacted by certificate issues, as the MutatingWebhookConfiguration objects on the cluster specify the certificate that should be expected from the webhook server: 
```shell
$ kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io controller.devfile.io -o json | jq '.webhooks[].clientConfig'
{
  "caBundle": "LS0tLS1CRU<snip>LS0tLS0K",
  "service": {
    "name": "devworkspace-webhookserver",
    "namespace": "devworkspace-controller",
    "path": "/mutate",
    "port": 443
  }
}
{
  "caBundle": "LS0tLS1CRU<snip>LS0tLS0K",
  "service": {
    "name": "devworkspace-webhookserver",
    "namespace": "devworkspace-controller",
    "path": "/mutate",
    "port": 443
  }
}

```

I've tested installing Che 7.43.0 in minikube (where all certificates are signed by untrusted CA authorities) via `chectl server:deploy --platform=minikube --workspace-engine=dev-workspace` and was able to start a workspace without issue.

**Comment by cristian-radu** [comment]
Hi @amisevsk, I think this issue was only specific to my environment. Sorry. I have resolved it now. 

I installed the che-operator and devworkspace-operator using kustomize.
