### ISSUE TITLE
Administration guide: remove content for unavailable features on instances with devworkspace, in the master branch

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21270]
### Is your task related to a problem? Please describe

Administration guide to document only instances with devworkspace.

### Describe the solution you'd like

Administration guide: remove content for unavailable features on instances with devworkspace, in the `master` branch.

Here is the current list of the admin guide articles. 
In **bold** the ones to remove: those that to eventually resume have the **[TEMP]** suffix, the rest has **[DEFINITIVE]** suffix.

* [ ] architecutre-overview
  * [ ] **architecture-overview (with-che-server) [DEFINITIVE]**
  * [ ] architecture-overview (with-devworkspace)
* [ ] calculating-che-resource-requirements
* [ ] **customizing the registries [TEMP]**
*  [ ] retrieving-che-logs
  * [ ] configuring-server-logging
  * [ ] **viewing-kubernetes-events [DEFINITIVE]**
  * [ ] **viewing-operator-events [TEMP]**
  * [ ] **viewing-che-server-logs [TEMP]**
  * [ ] **viewing-external-service-logs [TEMP]**
  * [ ] **viewing-plug-in-broker-logs [TEMP]**
  * [ ] collecting-logs-using-chectl
* [ ] monitoring-che
*  [ ] monitoring-the-dev-workspace-operator
* [ ] **tracing-che [TEMP]**
* [ ] **backup and recovery [TEMP]**
* [ ] **migration postgres [TEMP]**
* [ ] **readiness-init-containers [DEFINITIVE]**
* [ ] caching-images-for-faster-workspace-start
* [ ] managing-identities-and-authorizations
  * [ ] **authenticating-users [TEMP]**
  * [ ] **authorizing-users [TEMP]**
  * [ ] **configuring-authorization [TEMP]**
  * [ ] removing-user-data

### Describe alternatives you've considered

Start from scratch in the main branch.

**Comment by pmkovar** [comment]
Cloned in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3880
