### ISSUE TITLE
Administration guide: update content for devworkspace, in the master branch

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21283]
### Is your task related to a problem? Please describe

Administration guide to document only instances with devworkspace.

### Describe the solution you'd like

Administration guide: update content for features on instances with devworkspace, in the `master` branch.

Here is the current list of the admin guide articles with in **bold** the ones to update:

* [x] architecutre-overview
  * [ ] **architecture-overview** [WONT FIX for 3.0] 
* [x] **calculating-che-resource-requirements** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2270
* [x] retrieving-che-logs 
  * [x] configuring-server-logging 
  * [x] **collecting-logs-using-chectl** @amisevsk https://github.com/eclipse-che/che-docs/pull/2263
* [x] **monitoring-che** @dkwon17  https://github.com/eclipse-che/che-docs/pull/2279
* [x] **monitoring-the-dev-workspace-operator** @dkwon17 https://github.com/eclipse-che/che-docs/pull/2276
* [x] **caching-images-for-faster-workspace-start** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2258
* [x] managing-identities-and-authorizations
  * [x] **removing-user-data** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2278
   - https://github.com/eclipse/che/issues/21330

**Comment by nickboldt** [comment]
Engineering ownership: controller team / Ilya + Angel

**Comment by pmkovar** [comment]
Cloned in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3883

**Comment by ibuziuk** [comment]
> Engineering ownership: controller team / Ilya + Angel

Each item now has ownership and a person assigned to it explicitly

**Comment by pmkovar** [comment]
Pairing writers with engineers:

* @themr0c x @l0rd 
* @deerskindoll  x @ibuziuk 
* @max-cx  x @dkwon17 
* @eva-lotte x @amisevsk

**Comment by pmkovar** [comment]
Update to the assignments above:

@swatikarmarkar and @Eva-Lotte x @amisevsk

**Comment by pmkovar** [comment]
One more update to the assignments:

@Eva-Lotte x @ibuziuk

**Comment by ibuziuk** [comment]
All sub-task have been done. Closing
