### ISSUE TITLE
Provide VS Code Debug Adapter for Apache Camel in plugin registry

### ISSUE THREAD

**Issue by apupier** [eclipse/che#21280]
### Is your enhancement related to a problem? Please describe

A new VS Code extension is available to work with Apache Camel project.

https://open-vsx.org/extension/redhat/vscode-debug-adapter-apache-camel

### Describe the solution you'd like

Have the new extension available in Che registry

**Comment by l0rd** [comment]
@apupier I have removed removed the milestone. Feel free to add a milestone if you plan to work on the PR during this sprint.
