### ISSUE TITLE
Installation guide: update content for devworkspace, in the master branch

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21284]
### Is your task related to a problem? Please describe

Installation guide to document only instances with devworkspace.

https://www.eclipse.org/che/docs/next/administration-guide/installing-che/

### Describe the solution you'd like

Installation guide: remove content for unavailable features on instances with devworkspace, in the `master` branch.

Here is the current list of the install guide articles with in **bold** the ones to update:

* [x] **supported-platforms** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2284
* [x] installing-che
  * [x] installing-che-in-cloud
      * [x] **installing-che-on-openshift-4-using-operatorhub** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2299
      * [x] **installing-che-on-openshift-4-using-cli** @ibuziuk   [NO UPDATE NEEDED] the content is up to date:
      - https://www.eclipse.org/che/docs/next/administration-guide/using-the-chectl-management-tool/
      - https://www.eclipse.org/che/docs/next/administration-guide/installing-che-on-openshift-4-using-cli/
  * [x] running-che-locally 
      * [x] **installing-che-on-codeready-containers** @ibuziuk  https://github.com/eclipse-che/che-docs/pull/2302
      * [x] **installing-che-on-minikube** @ibuziuk https://github.com/eclipse-che/che-docs/pull/2302
  * [x] **installing-che-in-a-restricted-environment** @ScrewTSW @themr0c https://github.com/eclipse-che/che-docs/pull/2307
* [x] **advanced-configuration** @l0rd 
  * [x] **configuring-namespace-strategies** @l0rd @themr0c https://github.com/eclipse-che/che-docs/pull/2301
  * [x] **mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container** @l0rd https://github.com/eclipse-che/che-docs/pull/2296 
* [x] **uninstalling-che** (add devworkspace related uninstall bits) @dkwon17 https://github.com/eclipse-che/che-docs/pull/2281
  * [x] uninstalling-che-after-operatorhub-installation-using-openshift-web-console
  * [x] uninstalling-che-after-operatorhub-installation-using-openshift-cli
  * [x] uninstalling-che-after-chectl-installation

**Comment by pmkovar** [comment]
Pairing engineers with writers:

* @deerskindoll x @nickboldt 
* @themr0c x @ScrewTSW 
* @max-cx x Sam + @dkwon17 
* @eva-lotte x @amisevsk

**Comment by themr0c** [comment]
I believe we can close this issue and follow up in https://github.com/eclipse/che/issues/21393 for the last bugs.
