### ISSUE TITLE
How to integrate Opensumi opensource by alibaba ?

### ISSUE THREAD

**Issue by tianlinzx** [eclipse/che#21292]
### Summary

How to integrate Opensumi opensource by alibaba ?
https://github.com/opensumi/core

**Comment by benoitf** [comment]
Hello @tianlinzx 

If you're talking about "integrating the IDE" you should add an editor there https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml

It'll require a OCI image available and declaring ports/volumes etc
