### ISSUE TITLE
Documentation: serverExposureStrategy missing performance impacts

### ISSUE THREAD

**Issue by Hadsch** [eclipse/che#21294]
At least on kubernetes, the setting `serverExposureStrategy` has a huge impact on the startup time of a workspace.

Here you can see a comparison (credits to @sparkoo):
https://www.youtube.com/watch?v=Fhzt8DiBajU
Link to the comment: https://github.com/eclipse/che/issues/19461#issuecomment-810808710

| Option | Startup-Time |
| ------- | ------------- |
| single-host, type 'gateway' | 17 sec |
| multi-host, type 'ingress' | 55 sec |
| single-host, type 'ingress' | 66 sec |

Depending on which option you choose, the start time of a workspace can be increased or decreased by about 40 seconds.
In my opinion, this is a huge design decision that is not covered in the docs.

This is the page for the `serverExposureStrategy`:
https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/

### Expected documentation
Performance impact for each option

_Note:_ This might be different on MiniKube or on OpenShift. But at least for Kubernetes this setting should be considered during the setup.

**Comment by ibuziuk** [comment]
@Hadsch thanks for sharing the performance impact. Indeed `single-host` / gateway (the default one) is by far the fastest option from the workspace startup perspective. Would you be interested in contributing the performance impact warning to che-docs - https://github.com/eclipse-che/che-docs ?

**Comment by l0rd** [comment]
@Hadsch what version of Che are you using? single-host using gateway should be the only option since 7.42 (when the switch to DevWorkspace happened). @sparkoo can you confirm?

**Comment by Hadsch** [comment]
Currently we are on 7.39.1 but we plan to update soon. 

@l0rd + @ibuziuk: If its true, that this is the only option I think we can close this ticket. Otherwise, of course I can give it a try ;)

**Comment by sparkoo** [comment]
> @Hadsch what version of Che are you using? single-host using gateway should be the only option since 7.42 (when the switch to DevWorkspace happened). @sparkoo can you confirm?

yes, devworkspaces runs only on gateway single-host. We should update the docs (I believe big docs refactorings for devworkspaces are in progress).

**Comment by Hadsch** [comment]
@l0rd: If it is the only option since 7.42 than it would still be the question why all three options are described?

**Comment by sparkoo** [comment]
> @l0rd: If it is the only option since 7.42 than it would still be the question why all three options are described?

switch to devworkspaces is big update and docs haven't catch up yet

**Comment by Hadsch** [comment]
Perfect, then I will close the ticket now!

**Comment by l0rd** [comment]
Yes, big documentation refactoring / clean up is in progress https://github.com/eclipse/che/issues/21264
