### ISSUE TITLE
User guide - Select a workspace IDE

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21295]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Select a workspace IDE" section. 

### Describe the solution you'd like

We should mention that current IDEs are Eclipse Theia (the default one), Open source VS Code and JetBrains IntelliJ and PyCharm.

We should mention that the workspace IDE can be selected:
- using the URL parameter
- using the file ./che/che-editor.yaml
- ~~using a devfile.yaml attributes~~ ([not implemented yet](https://github.com/eclipse/che/issues/16994))
and provide the 3 examples (for Theia/VSCode/IntelliJ/PyCharm)

We should describe how definition of an IDE can be overridden and how an alternative plugin registry can be referenced. 

We should provide a link to the plugin registry where the definition of the IDEs are.

**Comment by rbbl-dev** [comment]
hey @l0rd i wanted to open an issue kinda closely related so i figured i ask here first.

is it still possible to use custom theia images as ide like described [here](https://www.eclipse.org/che/docs/che-7/end-user-guide/support-for-theia-based-ides/)? 

the section is gone on the stable docs

**Comment by l0rd** [comment]
> hey @l0rd i wanted to open an issue kinda closely related so i figured i ask here first.
> 
> is it still possible to use custom theia images as ide like described [here](https://www.eclipse.org/che/docs/che-7/end-user-guide/support-for-theia-based-ides/)?
> 
> the section is gone on the stable docs

Hi @rbbl-dev, it's still possible to use Che-Theia as the editor (that's the default editor and [here is the definition](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L3)). Now if your question is about how to use your Theia based IDE (not the Che-Theia, the one packaged with Che) then the answer is no and there is [an issue for that](https://github.com/eclipse/che/issues/20282).

**Comment by nickboldt** [comment]
Existing content:
* https://github.com/eclipse-che/che-docs/blob/master/modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc (how to use URL params)
* https://github.com/eclipse-che/che-docs/blob/master/modules/end-user-guide/examples/snip_che-supported-ides.adoc (list of supported IDEs in Che)

Example of che-editor.yaml: https://github.com/crw-samples/gradle-demo-project/blob/devfilev2/.che/che-editor.yaml

link to the plugin registry where the definition of the IDEs are
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L5 theia next
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L173 theia latest 
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L439 codium latest
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L472 codium next (insiders)
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L554 idea next
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L633 idea latest
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L712 pycharm next 
* https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L791 pycharm latest

Things I don't know yet:
* using a devfile.yaml attributes / provide 4 examples (for Theia/VSCode/IntelliJ/PyCharm)
* how an alternative plugin registry can be referenced

**Comment by ibuziuk** [comment]
@nickboldt details should be in the blog post - https://che.eclipseprojects.io/2021/12/20/@florent.benoit-authoring-a-url-to-start-a-workspace.html 
Regarding the alternative plugin registry, @svor should be able to provide the details
Just for the record this issue is about providing the PR with the content to the che-docs repo

**Comment by l0rd** [comment]
@ibuziuk I think that the blog post you are referring to is about the URL parameters, not about the devfile attributes. 

@nickboldt for the attributes [that's not been implemented yet](https://github.com/eclipse/che/issues/16994) (my bad, I have updated this issue description). For `editor.yaml` we should cover the [3 options described here](https://github.com/eclipse/che/issues/20715). Note that what you call `codium latest` is [coder](https://coder.com/) and what you call `codium next` is [Visual Studio Code - Open Source ("Code - OSS")](https://github.com/Microsoft/vscode). And `coder` is not tested, it has been contributed a long time ago, so it should be tested and eventually deprecate/remove if it doesn't work.

**Comment by nickboldt** [comment]
thanks for the help, guys! 

If coder is not tested, why don't we just remove it in 7.47 and see if anyone complains :) Can add it back if someone complains AND provides tests :D

**Comment by l0rd** [comment]
> If coder is not tested, why don't we just remove it in 7.47 and see if anyone complains :) Can add it back if someone complains AND provides tests :D

Ideally we should not do not "remove a feature contributed by the community and see if anyone complains". If it doesn't work let's ping the contributor and warn that we are considering the removal as we cannot maintain it.

**Comment by nickboldt** [comment]
> If it doesn't work let's ping the contributor

That would require testing it to see if it works... :)

**Comment by themr0c** [comment]
Fixed by https://github.com/eclipse-che/che-docs/pull/2343
