### ISSUE TITLE
User guide - Start a Che workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21293]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Getting Started" section.  

### Describe the solution you'd like

We should explain how a user should use Che to start a workspace and clone his github/gitlab/bitbucket git repository ([using a Che URL](https://che.eclipseprojects.io/2021/12/20/@florent.benoit-authoring-a-url-to-start-a-workspace.html)). 

We should NOT document how to start a sample from the dashboard: this is obvious and adding doc about that is a waste of time.

**Comment by max-cx** [comment]
@l0rd, can you please make me the assignee? (I'm not able to assign myself.)

**Comment by ibuziuk** [comment]
@max-cx the new PR is https://github.com/eclipse-che/che-docs/pull/2252, right?

**Comment by max-cx** [comment]
Done. Please close. It's been finally merged today. Thank you.
