### ISSUE TITLE
User guide - Git credentials and Git settings

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21298]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Git credentials and Git settings" section.

### Describe the solution you'd like

Get content from former "user guide / using developer workspaces / mounting a secret as a file ..." and also from "Authenticating users on private repositories of SCM servers"

**Comment by max-cx** [comment]
I am already working on this in https://github.com/eclipse-che/che-docs/pull/2242, so we will need to collaborate on this. I am blocked on testing, where the product fails to clone a private repo. My PR is based on https://github.com/eclipse-che/blog/pull/24.

**Comment by max-cx** [comment]
@l0rd, re the scope of this issue, could you please have a quick look at the following section:
https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_che
I have two questions:
1. Do you expect this to be a Che admin-level procedure, or do you expect each and every workspace user to do this?
2. The current title reads "Mounting a Git credentials store into a workspace container"--does it mean that this procedure is to be performed again on every workspace that a single user will start when using Che?

**Comment by l0rd** [comment]
> 1. Do you expect this to be a Che admin-level procedure, or do you expect each and every workspace user to do this?

This is a user task: it's about creating a secret with your git credentials so that you can git clone commit and push. An admin is not supposed to know your git credentials so he cannot help. But I do not expect "every user to do this": if an administrator set up the GitHub, Gitlab or Bitbucket OAuth, this secret is created automatically and the user doesn't have to do anything but allow Che to have access to his account. That's the recommended way. Or at least that's how things "should" work because currently there a few limitations: the secret is created only if 1. Che admin has setup OAuth (that makes sense) 2. Only when a user starts a workspace of a private repository 3. Only for GitHub SaaS, Bitbucket on-prem, Gitlab on-prem (c.f. #20583).

> 2. The current title reads "Mounting a Git credentials store into a workspace container"--does it mean that this procedure is to be performed again on every workspace that any single user will start when using Che?

No. The secret only needs to be created once.

**Comment by l0rd** [comment]
>     1. Can we update the title to the following? **[Y/N]**
> 
> 
> `= Creating the {platforms-name} Secret for a Git credentials store`
> 
> upstream: `platforms-name: Kubernetes or OpenShift` downstream: `:platforms-name: OpenShift`

Yes that's fine although I would simplify `Kubernetes or OpenShift secret` with `Kubernetes secret` (i.e. an OpenShift secret is a Kubernetes secret, there is no difference. The same is true for configmaps and other Kubernetes object). It's like saying "Creating the vehicle or VW Golf engine"..."Creating the vehicle engine" is better.

> 
>     2. Can we add such prerequisite here? **[Y/N]**
> 
> 
> `* You have CLI or GUI access to the {platforms-name} cluster of your organization's {prod-short} instance.`

Yes.

**Comment by dkwon17** [comment]
@max-cx sounds great, will take a look

**Comment by max-cx** [comment]
Closing https://github.com/eclipse-che/che-docs/pull/2242 to `main`, reworking its contents after David's engineering review, and opening https://github.com/eclipse-che/che-docs/pull/2271 to `master`.
