### ISSUE TITLE
Document how to setup an OIDC provider

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21304]
### Is your enhancement related to a problem? Please describe

After the [switch to the DevWorkspace](https://github.com/eclipse/che/issues/20830) and the removal of the [dependency on keycloak](https://github.com/eclipse/che/issues/19182) a few issues regarding the deployment and use of an OIDC provider with Che have been created:

- #21036
- #21049
- #21229
- #21258
- #21282
- #21289
- #21301
- #21325
- #21378
- #21452
- #21477
- #21541
- #21556

and counting...

### Describe the solution you'd like

Add a _Setting up an OIDC provider_ section in the [new Admin Guide](https://github.com/eclipse/che/issues/21283) under _[Preparing the installation](https://www.eclipse.org/che/docs/stable/administration-guide/preparing-the-installation/)_

```
└──Administration Guide
	  └── Preparing the installation
		    ├── (...)
            └── Setting up an OIDC provider
 ```

There is already some good content for [Rancher](https://github.com/eclipse/che/issues/21049#issuecomment-1022108499) and [GKE (probably EKS and AKS too)](https://github.com/eclipse/che/issues/21049#issuecomment-1067776895).

### Describe alternatives you've considered

Beyond documentation at some point we should to [automate the OIDC configuration too](https://github.com/eclipse/che/issues/21176).

**Comment by divinesocial** [comment]
@l0rd  is the documentation available?  i need guidance on setting up OIDC provider on k8s cluster (https://github.com/eclipse/che/issues/21301). Please help

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-4198

**Comment by tolusha** [comment]
Closed in favor of https://github.com/eclipse-che/che/issues/22392
