### ISSUE TITLE
User guide - Kubernetes integrations

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21300]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Kubernetes integration" section.

### Describe the solution you'd like

In this new section we should talk about the integration with Kubernetes/OpenShift such as:Kubernetes toke 
- [x] The automatic injection of the user Kubernetes token: terminal and IDE can use the k8s API transparently (new content)
- [x] The link in the OpenShift Dev Console topology (content already exist in _OpenShift Developer Perspective integration with Che_ article in existing documentation)
- [x] The link in the Che dashboard to the OpenShift Console (new content)
- [ ] Managing workspaces via kubectl (optional)

**Comment by ibuziuk** [comment]
> The automatic injection of the user Kubernetes token: terminal and IDE can use the k8s API transparently (new content)

This is going to work only for OpenShift at this point - https://github.com/eclipse/che/issues/21171
