### ISSUE TITLE
git-credentials-secret not created when cloning a private repository that has no devfile

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21305]
### Describe the bug

The `git-credentials-secret` secret is not created automatically when:
1. The admin has set up the GitHub Oauth app (see [docs](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che))
2. A new user tries to create a devworkspace with a private repository that contains no devfile:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/83611742/160498645-79488205-91f2-4cb3-9e85-2a367d112582.png">

3. Click `Create & Open`

The Che-theia editor starts, however, the `git-credentials-secret` secret is not created in the user's namespace. Therefore the private repository is not cloned unless the user manually provides their GitHub credentials.

### Che version

next (development version)

### Steps to reproduce

See above

### Expected behavior

The `git-credentials-secret` secret should be created in the user's namespace when a devworkspace based on a private repository is created.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

**Comment by dkwon17** [comment]
I haven't checked in-depth but I think this might be happening because there is an IO exception when trying to read a devfile, before the `git-credentials-secret` can be created: https://github.com/eclipse-che/che-server/blob/d8bed4006aba47feb710612b1e19cfcb355cc611/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java#L89-L91

**Comment by tolusha** [comment]
@dkwon17 
Is it still an issue?

**Comment by dkwon17** [comment]
Hi @tolusha , yes I still have this issue.

After accepting the Oauth dialogue, the secret is `git-credentials-secret` is not created:
![image](https://user-images.githubusercontent.com/83611742/168296440-a69b940f-31f6-4a68-9e2a-7d16139b9b4e.png)

Therefore the project is not cloned in the editor unless I provide my credentials:
![image](https://user-images.githubusercontent.com/83611742/168296936-15b5db42-e1ec-4a19-b672-2d1a7abc1224.png)

**Comment by dkwon17** [comment]
For more information, this is the secret I would have expected to be created:
![image](https://user-images.githubusercontent.com/83611742/168302778-106207e3-8a16-43ce-b684-da5a3d6e38c2.png)

**Comment by dkwon17** [comment]
I'm not able to reproduce this issue anymore for chectl next:
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/83611742/201149812-34097dc9-560d-44e0-ad1d-13e98693068e.png">
