### ISSUE TITLE
Can not use ssh remote for pushing to che-docs repo from workspace terminal on workspaces.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21306]
### Is your enhancement related to a problem? Please describe

Can not use ssh remote for pushing to che-docs repo from workspace terminal on workspaces.openshift.com: 

```
~/che-docs $ git push ibuziuk che-21300
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

![image](https://user-images.githubusercontent.com/1461122/160586689-a9c27086-36cb-4413-87d6-6585223ce281.png)

### Describe the solution you'd like

can add and push to ssh remote from workspace terminal

### Describe alternatives you've considered

had to use username  + personal access token combo on workspaces.openshift.com for this repo

**Comment by ibuziuk** [comment]
FYI this flow works for other repos e.g. che-website

![image](https://user-images.githubusercontent.com/1461122/160589489-14be5bbd-8c63-4f15-be74-2fba05479a59.png)

**Comment by ibuziuk** [comment]
probably you should consider using ` quay.io/devfile/universal-developer-image` instead of custom `quay.io/eclipse/che-docs:latest` for the tools container

**Comment by themr0c** [comment]
@ibuziuk Definetely, using UDI is in the pipe, but we must fix this issue first: https://github.com/devfile/api/issues/873
