### ISSUE TITLE
API server is not configured with OIDC Identity Provider 

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21301]
### Summary

i have a k8s cluster, i used this command `chectl server:deploy --platform k8s --installer=operator` to install eclipse che on this cluster.

i received this error message during this installation
```
API server is not configured with OIDC Identity Provider, see details https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server
```

which OIDC identify provider should i configure to fix this issue? please help

![image](https://user-images.githubusercontent.com/10482177/159932755-ea403f7c-8474-4909-9335-3c592fc16ba9.png)

**Comment by Divine1** [comment]
@l0rd  how can i install `dex` as an OIDC provider to fix this issue.  if you have a simple way of doing it using couple of commands please let me know

**Comment by tolusha** [comment]
Maybe you can have a look at dex resources that are used for minikube cluster
https://github.com/che-incubator/chectl/tree/main/resources/dex

**Comment by Divine1** [comment]
@tolusha i'm not able to make it work. please help

**Comment by Divine1** [comment]
@tolusha i gained some understanding and now i'm able to install dex on k8s cluster. but its messy

**Comment by SockenSalat** [comment]
Well the thing is, and I'm watching this for a long time ... there is no intention to support on premise installation of che.

**Comment by tolusha** [comment]
@Divine1 
Can this issue be closed?

**Comment by Divine1** [comment]
@tolusha yes this can be closed. i was able to setup eclipse-che in k8s cluster.
i received answer for this question
