### ISSUE TITLE
Chectl should try to detect installed namespace for appropriate commands

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21311]
### Is your enhancement related to a problem? Please describe

Some commands, e.g. `chectl server:logs` require the `-n, --chenamespace` parameter if Che is installed in a non-default namespace. However, in many cases, it is possible to discover the installed namespace via the Kubernetes API (e.g. by listing all `CheClusters`).

```
❯ chectl server:logs
Eclipse Che logs will be available in '/tmp/chectl-logs/1648573985115'
› Current Kubernetes context: 'amisevsk-che/<snip>:6443/amisevsk'
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✖ Verify if namespace 'eclipse-che' exists
    → The Kubernetes Namespace "eclipse-che" doesn't exist.

❯ kubectl get CheClusters --all-namespaces
NAMESPACE    NAME          AGE
dogfooding   eclipse-che   650d
```

### Describe the solution you'd like

Since commands like `chectl server:logs` do not modify any resources on the cluster, they should automatically detect the namespace and report a useful message if this is not possible.

### Describe alternatives you've considered

The error message should suggest using the `-n` parameter if it cannot find the installation in the default namespace.

**Comment by tolusha** [comment]
`chectl server:logs -n <NAMESPACE>` ?

**Comment by amisevsk** [comment]
> chectl server:logs -n <NAMESPACE> ?

That's one of the alternatives suggested, but as an inexperienced user, if Che is not installed in `eclipse-che`, the error message is just 

```
  ✖ Verify if namespace 'eclipse-che' exists
    → The Kubernetes Namespace "eclipse-che" doesn't exist.
    Read logs
    Error: Command server:logs failed. Error log: /home/amisevsk/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1648646484798.
```

Which is a little confusing. Maybe to following is easier to understand without referencing docs or help pages:

```
  ✖ Verify if namespace 'eclipse-che' exists
    → The Kubernetes Namespace "eclipse-che" doesn't exist. Use the -n parameter to specify namespace for Eclipse Che installation.
    Read logs
    Error: Command server:logs failed. Error log: /home/amisevsk/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1648646484798.
```

It also means the documentation has to explicitly include "If Che is not installed in the default namespace, the `-n` parameter must be used to specify the installed namespace". 

However, if we're making k8s API calls already, it's very easy to figure out this namespace automatically and not require `-n` in the first place.
