### ISSUE TITLE
Pair programming: enable usage of CodeTogether propsed API for better UX

### ISSUE THREAD

**Issue by toddewilliams** [eclipse/che#21317]
### Is your enhancement related to a problem? Please describe

[CodeTogether](https://codetogether.com/) is a VS Code-compatible (code-oss) extension for developer collaboration and IDE live sharing.

However, to work to its full potential CodeTogether uses APIs that Microsoft has marked as "proposed." Unfortunately, these APIs will likely never be fully accessible as they are used only internally by Microsoft to gain competitive advantage for its products.

Using CodeTogether in Eclipse Che with the VS Code editor is already possible and the setup process is documented in this excellent [Eclipse Che blog article](https://che.eclipseprojects.io/2022/04/01/@florent.benoit-pair-programming-using-vscode-editor.html). 

Unfortunately, the process is rather involved and requires some manual work that could be avoided if CodeTogether was simply whitelisted for access to use the proposed APIs it requires to be fully functional.

### Describe the solution you'd like

Access to proposed APIs can be granted on the command line, programmatically, or from within the product.json file.

From the command line, arguments like this are normally supplied:
`--enable-proposed-api genuitecllc.codetogether`

If CodeTogether doesn't detect such access it requests to be able to add that access programmatically. However, many VS Code variants do not use the standard method for allowing programatic access enhancement so this method may fail.

The preferred and most seamless method is to grant access access to proposed APIs to CodeTogether from within the product.json file.

My enhancement request is that you grant the use of proposed APIs to CodeTogether directly in your product file [as GitPod did here](https://github.com/gitpod-io/gitpod/issues/6476).

This should make CodeTogether "just work" and allow us to get feedback and provide further support for the Eclipse Che community.

### Additional context

For convenience in case any enhancement work is needed on the CodeTogether side:
Issue Tracker: https://github.com/Genuitec/CodeTogether/issues

### Release Notes Text

This improve the UX of CodeTogether VS Code Extension in a Che workspace and for instance allows to share the terminal.

**Comment by benoitf** [comment]
@toddewilliams could you please list all proposal APIs required by the extension ?
because now, proposed APIs are fine-grained and we need to say the list of APIs for each extension

extensionEnabledApiProposals / see https://github.com/microsoft/vscode/issues/131165

**Comment by toddewilliams** [comment]
I checked with the technical team and here are the core APIs we use, with their related object models:
```
vscode.workspace.registerFileSearchProvider
vscode.workspace.findTextInFiles
vscode.window.onDidWriteTerminalData
vscode.window.onDidChangeTerminalDimensions
vscode.tests.runTests
vscode.tests.createTestObserver
vscode.tests.testResults
vscode.tests.onDidChangeTestResults
```
Stated in another format:

`"preferredProposedApis": ["fileSearchProvider", "findTextInFiles", "terminalDataWriteEvent", "terminalDimensions", "terminalLocation", "terminalNameChangeEvent", "testObserver", "textSearchProvider"]`

Please let me know if you need anything else.

**Comment by nickboldt** [comment]
che-code not in DS 3 yet, so no N&N for downstream needed

**Comment by max-cx** [comment]
@toddewilliams, we need to prepare a release note about this in our downstream product, Dev Spaces.

Could you please spell out in more tangible terms what the following sentence means?

> "This improve the UX of CodeTogether VS Code Extension in a Che workspace"

What difference does it make for a CodeTogether user? What's different? Which features or procedures are affected?

Sorry for taking your time with this, but clarifying this will be beneficial to both products.

**Comment by toddewilliams** [comment]
@max-cx I'll be happy to help if I'm able to.

> Could you please spell out in more tangible terms what the following sentence means?
> 
> >"This improve the UX of CodeTogether VS Code Extension in a Che workspace"
> What difference does it make for a CodeTogether user? What's different? Which features or procedures are affected?

If CodeTogether doesn't have access to the propose APIs I listed in [this comment](https://github.com/eclipse/che/issues/21317#issuecomment-1089172277), the remote access to the host's terminal will be restricted to read-only and none of the test running / result services on the host's machine will operate for the remote participants. 

> If the above is too much demand on your time, then we can shorten it to a single yes/no question:
> Is the following release note draft correct? [Yes/No]
> 
> ====
> 
> = Live sharing Visual Studio Code sessions in Dev Spaces by using CodeTogether
> 
> With this update, Dev Spaces supports the full functionality of [CodeTogether](https://marketplace.visualstudio.com/items?itemName=genuitecllc.codetogether), a pair-programming extension for Visual Studio Code. CodeTogether enables live sharing of Visual Studio Code sessions in Dev Spaces workspaces.
> 
> ====

I apologize, but I can't answer that question either way since I'm not familiar with exactly which product called "Dev Spaces" you're referring to as RedHat, Microsoft Azure, and at least one OSS project have all used that term. Or perhaps it's something else?

I'd assume answering the question properly would be up to your technical team to install CodeTogether into your environment and test the functionality versus what we have [documented](https://www.codetogether.com/docs/). I'll be happy to help expedite any technical collaborations that need to happen if you run into questions or issues, but that collaboration should take place on a forum for your product. 

If you'd like to start a collaboration there, just drop me an email with a link to <my GitHub name> at gmail. 

I look forward to finding out more about your product and how it has integrated CodeTogether.
