### ISSUE TITLE
As a user, I want to have a getting-started guided tour when accessing the dashboard for the first time

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21326]
### Is your task related to a problem? Please describe

When a user accesses the dashboard for the very first time dashboard needs to provide a getting-started guided tour for the initial setup.
### Describe the solution you'd like

For the User Dashboard we could start with the following items:

- Create Workspace
- Navigate to the Cluster 

In future, we need to rethink the UX and add potentially add the tour for:
- choosing the IDE (does not exist on UD atm)
- configuring gitconfig (does not exist on UD atm)

Guided tour example for OpenShift:
![guided-tour](https://user-images.githubusercontent.com/1461122/162708822-13eaa27d-0494-4ca9-a842-2da173113a37.gif)
 

### Additional context

There are multiple guided tour js plugins e.g. https://github.com/shipshapecode/shepherd 
but we should leverage the one that OpenShift Web Console is using, which is based on the patternfly - https://www.patternfly.org/v3/pattern-library/communication/tour/index.html

**Comment by sunix** [comment]
maybe related to https://github.com/eclipse/che/issues/20175
