### ISSUE TITLE
After upgrading from 7.41.x converted workspaces fail to start

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21329]
### Describe the bug

I have followed [instructions to upgrade a Che v7.41 instance](https://www.eclipse.org/che/docs/stable/administration-guide/upgrading-che-7-41-on-openshift/). My user had a couple of existing workspaces (chectl and devworkspaces-operator) that, after the upgrade, required to be converted in order to be used. After clicking on the `convert` button and then `open` the workspaces are not started:

The workspaces are stucked as "starting" in the dashboard:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/606959/162847039-83bafb31-7ee6-4304-9a2c-2ddad82982b8.png">

But the correspondent `DevWorkspace` phase is `Stopped`:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/606959/162847185-fcc49efd-2086-4d84-adca-2df1029d53ac.png">

And if I go back to "My Workspaces" it appears twice:
![image](https://user-images.githubusercontent.com/606959/162847308-3d5e64fb-72fc-47ae-ad76-5b71ea5368eb.png)

And when selecting it: it's a v2.1 but deprecated (but doesn’t allow to convert or start it anymore):
![image](https://user-images.githubusercontent.com/606959/162847442-9365e9be-b4de-4520-bca5-882783063d0e.png)

### Che version

7.44@latest

### Steps to reproduce

1. Deploy Che v7.41 using `chectl` on OpenShift
2. Use a factory link to start a chectl workspace: `https://<che-host>/#https://github.com/che-incubator/chectl`
3. Follow the [upgrade guide](https://www.eclipse.org/che/docs/stable/administration-guide/upgrading-che-7-41-on-openshift/)
4. Try to convert and start the workspace

### Expected behavior

Converted workspaces start successufully

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

**Comment by l0rd** [comment]
@ibuziuk I have added this issue to the [sprint plan](https://github.com/eclipse/che/issues/21318)

**Comment by ibuziuk** [comment]
Closing, feel free to reopen if still reproducible against 7.46
