### ISSUE TITLE
Unable to create devworkspace: Unauthorized

### ISSUE THREAD

**Issue by Ryder05** [eclipse/che#21325]
### Describe the bug

When i try to create a new devworkspace an error shows up saying " Failed to create a workspace. Failed to create a new workspace from the devfile, reason: Failed to create a new workspace. Unable to create devworkspace: Unauthorized " 

![image](https://user-images.githubusercontent.com/59898800/162475836-a2f9988d-33e5-40bd-84d4-b3d77aff4f68.png)

### Che version

7.44@latest

### Steps to reproduce

1.  chectl server:deploy --domain=che.xxx.eu --platform=k8s --che-operator-cr-yaml=checluster.yml  --skip-oidc-provider-check  -n che 

### Expected behavior

A devworkspace starts up =.

### Runtime

Kubernetes (vanilla)

### Screenshots

![image](https://user-images.githubusercontent.com/59898800/162476977-1121e563-fb64-422d-997a-738cb0e41638.png)

### Installation method

chectl/latest

### Environment

Windows

### Additional context

Checluster file used in deployment.
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    #identityProviderIngress: traefik
    identityProviderClientId: 'eclispe-che'
    identityProviderRealm: opencell
    identityProviderURL:  https://kc.osama-che.me/auth/realms/opencell/
    openShiftoAuth: false
    updateAdminPassword: false
    identityProviderPassword: 'admin' 

  server:
    serverExposureStrategy: 'multi-host'
    workspaceNamespaceDefault: che-ws-<username>
    #cheServerIngress: "traefik"
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: "email"
      CHE_INFRA_KUBERNETES_TLS__SECRET: ''
      CHE_KEYCLOAK_CLIENT__ID: 'eclipse-che'
      CHE_KEYCLOAK_REALM: 'opencell'

      CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: 
        '{
          "kubernetes.io/ingress.class": "nginx", 
          "nginx.ingress.kubernetes.io/affinity": "true", 
          "nginx.ingress.kubernetes.io/rewrite-target": "/",
          "ingress.kubernetes.io/ssl-redirect": "true",
          "ingress.kubernetes.io/force-ssl-redirect": "true" 
        }'
  database:
    externalDb: false

  k8s:
    tlsSecretName: 'che-tls'
    ingressClass: 'nginx'
    ingressDomain: 'che.xxx.eu'  
    ingressStrategy: 'multi-host'
    securityContextRunAsUser: '0'
    securityContextFsGroup: '0'

```

**Comment by benoitf** [comment]
Hello, we can see a certificate error
Do you have validated the self-signed certificate ?

**Comment by Ryder005** [comment]
> Hello, we can see a certificate error Do you have validated the self-signed certificate ?

i downloaded the self signed certificate and imported it in Trusted Root Certificate Authorities, but it is still not valid "windows does not have enough information to verify this certificate"

**Comment by Ryder005** [comment]
> Hello, we can see a certificate error Do you have validated the self-signed certificate ?

i downloaded the self signed certificate and imported it in Trusted Root Certificate Authorities, but it is still not valid "windows does not have enough information to verify this certificate"

**Comment by Ryder05** [comment]
> Hello, we can see a certificate error Do you have validated the self-signed certificate ?

i downloaded the self signed certificate and imported it in Trusted Root Certificate Authorities, but it is still not valid "windows does not have enough information to verify this certificate"

**Comment by Ryder05** [comment]
It seems roles, bindings and serviceaccounts are not created. Should this be done by eclipse che ?

**Comment by Ryder005** [comment]
> @Ryder05 have you setup an OIDC provider for authentication on your cluster? On what Kubernetes are you testing this (minikube, eks, gke...) ?

Hello, I am using an externeal keycloak as an OIDC  and i am using a full managed kubernetes provided by OVH cloud.

**Comment by homains-ou** [comment]
Having the same issue with version 7.46.0

**Comment by Ryder05** [comment]
> Having the same issue with version 7.46.0

I finally resolved the problem by configuring Keycloak  as an OIDC provider for my Kubernetes cluster.

**Comment by tolusha** [comment]
Can we close this issue?
