### ISSUE TITLE
Version of Dashboard in main branch not correctly updated every 3 weeks as part of release process

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21339]
### Describe the bug

On Jan 20th, the dasboard version was manually bumped:

https://github.com/eclipse-che/che-dashboard/commit/19d3682d021d57c4295b6ae102571b660944fef9

And then a fix was applied to ensure the .x branch version is correctly updated.

https://github.com/eclipse-che/che-dashboard/commit/80fd150a15ae920a020f64030e31a920db9b95a4

However, the main branch remains at 7.43 despite the fact that main == 7.47 now.

So... this block is misbehaving:

https://github.com/eclipse-che/che-dashboard/blob/main/make-release.sh#L139-L145

### Che version

main branch

### Expected behavior

every release should generate a PR to update the dashboard version.

**Comment by mkuznyetsov** [comment]
fix merged to main branch and produced a PR during a faulty 7.47(7.48) run https://github.com/eclipse-che/che-dashboard/pull/515/files, so this can be resolved
