### ISSUE TITLE
Commercial and Enterprise Support

### ISSUE THREAD

**Issue by celalsahin** [eclipse/che#21333]
### Summary

Hi,

I have, hopefully, a short question.
In this link [1] "Commercial and Enterprise Support" points to the page [2] which does not exists.
I wanted to ask if there is any way or form to get commercial support for self managed eclipse-che (e.g. on AWS EKS)

Regards
Celal

[1]https://www.eclipse.org/che/community/
[2]https://chat.openshift.io/developers/channels/che-enterprise

**Comment by ibuziuk** [comment]
Thanks for reporting
Eclipse Che is an open-source project under EPL 2.0 and there is no commercial support for it.
Red Hat provides the commeccial support for the productized version of Eclipse Che:
- https://developers.redhat.com/products/codeready-workspaces/overview
- https://developers.redhat.com/articles/2022/04/01/codeready-workspaces-scales-now-red-hat-openshift-dev-spaces

**Comment by celalsahin** [comment]
Thanks for the fast feedback - we were just curious due to "Commercial and Enterprise Support" statement in the home page but now is all clear.
