### ISSUE TITLE
need documentation which will describe how to install `eclipse-che` on virtual machines available in a LAN network

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21332]
### Summary

i have couple of virtual machines in my local area network (LAN). i have configured a kubernetes cluster in my LAN by linking couple of machines. i have decided to install `eclipse-che` in this environment.

In the documentation i'm not able to find the installation instructions of `eclipse-che` on LAN or an environment equivalent of LAN (like installing `eclipse-che` on a k8s cluster configured by connected multiple AWS EC2 instances).
Please help me understand what steps can i follow to accomplish this.

https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che/
![image](https://user-images.githubusercontent.com/10482177/163109522-6ebbe14f-2902-4229-b135-ffcd4799415e.png)

Thank you

**Comment by themr0c** [comment]
This is a good idea for a blog post on https://che.eclipseprojects.io/.

The screenshot displays the obsolete Installing Che page. The latest stable version for this page is at https://www.eclipse.org/che/docs/stable/administration-guide/installing-che/. As you can see, we have removed from the documentation most installation procedures designed for specific infrastructures such as AWS, Azure, GCP, Kubespray, Docker desktop, Minishift, Kind. We don't have sufficient resources to maintain these procedures. We chose to deprecate the content rather than keeping misleading procedures. 

The blog https://che.eclipseprojects.io/ is a better place for these procedures, and a blog post documenting this user story, as well as updated procedures for installing on various platforms, will be very welcome.

**Comment by amisevsk** [comment]
In general, many steps in the install are shared, and platform-specific documentation comes down to friction with specific cluster configurations. @Divine1 if you're willing to try stuff out, a starting point would be to use the [`chectl` utility](https://github.com/che-incubator/chectl) to attempt to install Che in the cluster:
```
# from a machine connected to the cluster
chectl server:deploy --platform=kubernetes
```

One friction point from running on a LAN is that it may be required to set up a LAN hostname for the cluster. I've not done this for Kubernetes, so I can't be of much help, but it is possible to e.g. run `crc` on a separate machine in your LAN: https://crc.dev/crc/#setting-up-remote-server_gsg by setting up local DNS for the cluster via `/etc/hosts` on client machines or at the network level.

**Comment by themr0c** [comment]
@l0rd Should we have a "Installing Che on Kubernetes using CLI" procedure based on https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-on-openshift-using-cli/, but with `--platform=kubernetes`. But how would we test it and list the prerequisites?

**Comment by Divine1** [comment]
@themr0c please do it

**Comment by l0rd** [comment]
@themr0c we can document that but users will need to [setup an OIDC provider](https://github.com/eclipse/che/issues/21304) before doing that (except on minikube where we automatically configure Dex) anyway as a prerequisite.

**Comment by Divine1** [comment]
> @themr0c we can document that but users will need to [setup an OIDC provider](https://github.com/eclipse/che/issues/21304) anyway as a prerequisite (except on minikube where we automatically configure Dex and on openshift where it's pre-installed).

if there is a documentation with details containing how to setup  an OIDC provider  (for example dex ) , it will be very helpful for me

**Comment by l0rd** [comment]
@Divine1 the issue I have linked has a lot of references. The Kubernetes documentation is [here](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server).

**Comment by Divine1** [comment]
@l0rd
i have setup dex as oidc and it works fine. now i have to integrate `dex` and `eclipse-che`.

 i ran into another trouble. where can i find the details on how to intergrate `eclipse-che` and `dex` ?

![image](https://user-images.githubusercontent.com/10482177/172531873-790dbfc1-377b-4d7f-acfb-ae624991245f.png)

**Comment by Divine1** [comment]
@l0rd  i have installed `eclipce-che` with `dex` as OIDC in my LAN on k8s cluster created using kubeadm. Thank you for the help
