### ISSUE TITLE
git-credentials-secret mount path is hardcoded to theia user directory

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21336]
### Describe the bug

After configuring oAuth for GitHub, credentials secret `git-credentials-secret` is appeared in the user namespace. The secret has a hardcoded to `/home/theia/.git-credentials` mount path. This is ok for theia editor, where the home directory is `/home/theia`, but in `che-code` editor this doesn't work because it knows nothing about theia.

### Che version

next (development version)

### Steps to reproduce

1. Configure GitHub oAuth: https://www.eclipse.org/che/docs/next/administration-guide/configuring-oauth-2-for-github/
2. Create a factory with a private project e.g. `<che-url>/dashboard/#<url to a private github project>`
3. Stop the factory workspace and start a che-code workspace: `<che-url>/dashboard/#https://github.com/benoitf/codetogether-che-petclinic`

See: the `credentials` file is located in `/home/theia/.git-credentials/` folder

### Expected behavior

The github credentials file must not be mounted to the hardcoded theia user directory.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

**Comment by ibuziuk** [comment]
@amisevsk wdyt? is it really smth. that devworkspace operator is expected to handle?

**Comment by amisevsk** [comment]
@ibuziuk I think this secret is being created by Che itself and is just using the automount functionality from DWO to configure the secret, following https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#adding-git-credentials-to-a-workspace. 

However, the specific mount path used here should not be an issue, as the mount path is just where the credentials file is to be stored. I agree that `theia` should not be used here, but using `theia` should not break git credentials functionality. 

@vinokurig in the Che code workspace, does git from the commandline correctly use the git credentials provided? `git config --list` should contain a `credential.helper` entry.

**Comment by amisevsk** [comment]
I briefly tested on OpenShift 4.10 and with a manually created git credentials secret per the instructions linked above, my che-code workspace has:
```
bash-4.4$ git config --list | grep "credentials"
credential.helper=store --file /home/theia/.git-credentials/credentials
bash-4.4$ cat /home/theia/.git-credentials/credentials
https://amisevsk:ghp_<snip>@github.com
bash-4.4$ 
```

**Comment by vinokurig** [comment]
The problem is that the GitHub authentication provider in che-code reads the credentials file from the user directory:
https://github.com/che-incubator/che-code/blob/main/code/extensions/che-api/src/impl/github-service-impl.ts#L25
I don't think it is a good idea to setup the provider to read hardcoded `theia` directory.

**Comment by amisevsk** [comment]
:+1: to using `/.git-credentials/credentials` by default, it should be an easy change (just change the annotation used when creating the secret. 

The alternative would be to have che-code resolve the proper path from gitconfig; I don't know how hard that would be.

**Comment by vinokurig** [comment]
Will merge after release
