### ISSUE TITLE
Use OAuth flow and authenticate users against Git services at first workspace startup

### ISSUE THREAD

**Issue by svor** [eclipse/che#21346]
### Is your task related to a problem? Please describe

At the moment when the administrator set up the GitHub, Gitlab or Bitbucket OAuth and the user has not logged in it yet, we ask to login only if the user starts a workspace of a **private repository**.  As a result the secret is created automatically and Che has access to his Git account that makes much simpler to work with git project.

The idea of this task is to use OAuth flow to authenticate git user even if a workspace was started of a **public repository**. 

### Describe the solution you'd like

Prompt the user to do git authentication even if the repository is a public one

### Release Notes Text

When starting a workspace for the first time users are prompted systematically to authenticate against the Git service provider if the OAuth flow has been enabled by the administrator. That allows to always inject personal tokens with git credentials in workspaces. That was done for private repositories only and it's now extended to any repository. The git services providers that are supported are GitHub SaaS, Gitlab on-prem and Bitbucket on-prem.

**Comment by benoitf** [comment]
implemented by https://github.com/eclipse-che/che-server/pull/301
