### ISSUE TITLE
"504 Gateway Time-out" after workspace went offline, and it wasn't clear how to restore workspace

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21347]
### Describe the bug

There was "504 Gateway Time-out" after workspace went offline:
![Screenshot from 2022-04-22 17-08-32](https://user-images.githubusercontent.com/1197777/165083960-c5797d4a-dbb8-434b-a941-833dd2633621.png)

There was white page with error message "504 Gateway Time-out" after refresh of page.
![Screenshot from 2022-04-22 13-03-36](https://user-images.githubusercontent.com/1197777/165083843-070c4f7a-ae0c-4332-82bd-d0d8fd8e53b6.png)

It wasn't clear how to restore 

### Che version

next (development version)

### Steps to reproduce

1. Go to Eclipse Che dogfooding instance.
2. Start workspace
3. Keep workspace tab opened, but do nothing inside workspace tab.
4. Wait on workspace to go offline
5. Reload workspace page

### Expected behavior

Workspace to be started automatically after refresh, like it was in che-server mode.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by nickboldt** [comment]
Similar issue (with 503) in https://github.com/eclipse/che/issues/20599

**Comment by dmytro-ndp** [comment]
@nickboldt : Error 503 != 504.
So, https://github.com/eclipse/che/issues/20599 is about different problem, IMHO

**Comment by nickboldt** [comment]
I'm aware that 503 != 504; my point is that there's apparently a lot of problems related to timeout/inactivity/expired tokens, which impact UX.

**Comment by dmytro-ndp** [comment]
Agreed.
I will closed the issue as duplicating.

Thank you for notice, @nickboldt !
