### ISSUE TITLE
[che-code] Port SSH plugin from che-theia to che-code

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21341]
### Is your task related to a problem? Please describe

There is no SSH tooling in che-code.

### Describe the solution you'd like

Need to port SSH plugin from che-theia to che-code.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by l0rd** [comment]
@vinokurig can we discuss this? I am not sure this should be a priority, [OAuth flow related issues are what we want to fix first](https://github.com/eclipse/che/issues/20583).

**Comment by l0rd** [comment]
cc @svor

**Comment by william-xiang** [comment]
Is there a schedule for this item now?
