### ISSUE TITLE
My daily authentication dance

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21352]
### Describe the bug

On Che dogfooding instance I get a 403 error once every day when my token expires and I am redirected to OpenShift authentication page. And, after re-logging in, I am not redirected to the dashboard but to the OpenShift authentication page and I need to edit the URL to get back to the dashboard.

![dogfooding-auth-problem](https://user-images.githubusercontent.com/606959/165400835-7b55a428-a3f1-43a2-8831-81ae710c4ead.gif)

### Che version

next (development version)

### Steps to reproduce

Wait for the authentication token to expire (24h) and click on a link on the dashboard or refresh the page.

### Expected behavior

After logging in I expect to be redirected to the dashboard instead of seeing a 403 error.
And after logging in the second time I expect to be redirected to the dashboard too.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

After trying too many times to login I get this error too:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/606959/165103654-3ac401d0-6fbf-42a5-990a-216d1beafb13.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/606959/165103740-7d95afd1-e87a-42f7-85b2-44386544cfe8.png">

**Comment by nickboldt** [comment]
Note: This problem has been reported against Che 7.46.x / Dev Spaces 3.0 ER too, not just in :next
