### ISSUE TITLE
[UX] Instead of error message "you already have a workspace by this name", ask user if they want to open that existing workspace, or create a new copy

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21358]
### Is your enhancement related to a problem? Please describe

If you have an existing old workspace definition created from a getting started sample, and click the tile again a week later, you get an error message.

But as a user, it would be WAAAY smoother if instead of being told "you did something dumb" I was instead prompted with calls to action:

* Would you like to open the existing workspace?
* Or would you like to create a new workspace, under a new name? 

### Describe the solution you'd like

On the https://<che-instance>/dashboard/#/load-factory page, provide me useful calls to action, which would be clickable links to either:

* open the existing workspace defined for this sample / git project / devfile, or 
* create a new workspace, under a new name, by appending ?new to the URL 

### Describe alternatives you've considered

Continue to throw errors and make users figure stuff out the hard way.

**Comment by dkwon17** [comment]
This issue is related to https://github.com/eclipse/che/issues/21561, and fixed by https://github.com/eclipse-che/che-dashboard/pull/622
