### ISSUE TITLE
[UX] Instead of error message "you are not allowed to start more workspaces", ask user if they want to switch to open workspace or close all workspaces in order to open this new one

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21359]
### Is your enhancement related to a problem? Please describe

If you have an existing workspace running, and attempt to open a new one (assuming the default 1 running workspace per user has not been overridden by adminstrator at install time), you get an error message.

But as a user, it would be WAAAY smoother if instead of being told "you did something dumb" I was instead prompted with calls to action:

Would you like to close running workspaces?
Or would you like switch to your running workspace, so you can save/commit changes?

### Describe the solution you'd like

On the https:///dashboard/#/load-factory page, provide me useful calls to action, which would be clickable links to either:

* open the currently running workspace (if only one found, or else link to /dashboard/#/workspaces if more than one)
* close the currently running workspace (if only one found, or else link to /dashboard/#/workspaces if more than one)

### Describe alternatives you've considered

Continue to throw errors and make users figure stuff out the hard way.

**Comment by ibuziuk** [comment]
Raising priority based on the retrospective discussion + adding the `sprint/next` label

**Comment by l0rd** [comment]
@dkwon17 can we close this issue? I am asking to decide if we can include it in 7.53 release notes

**Comment by dkwon17** [comment]
Oops, yes, this issue can be closed, fixed by https://github.com/eclipse-che/che-dashboard/pull/607
