### ISSUE TITLE
Remove postgres 9.6 from Che Operator CSV

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21350]
### Is your task related to a problem? Please describe

Today we have both the supported Postgres 13 and the deprecated Postgres 9.6 entries in the Che operator CSV:

https://github.com/eclipse-che/che-operator/blob/main/bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L976-L979
https://github.com/eclipse-che/che-operator/blob/main/bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L976-L979

Since the process for updating CRW 2.15 (Che 7.42) to 3.0 (Che 7.46) requires manual steps to clean up old deployments, switch to a new channel name and subscription, this means that any 3.0 deployments are NEW and therefore will never use Postgres 9.6 env vars, only 13.

I'm not sure if the same is true for Che users, but if so, then we could simpy remove these env vars and update the Che operator code such that Postgres 13 is the only option, with no fallback to 9.6.

### Describe the solution you'd like

See above

**Comment by nickboldt** [comment]
Related issues: 
* Stop building che-postgres image since it's not used in the Che operator CSV #21349
* Che docs page about PostgreSQL has outdated links #21348

**Comment by tolusha** [comment]
> Since the process for updating CRW 2.15 (Che 7.42) to 3.0 (Che 7.46) requires manual steps to clean up old deployments, switch to a new channel name and subscription, this means that any 3.0 deployments are NEW and therefore will never use Postgres 9.6 env vars, only 13.

That's not true.
3.0 deployments will use the existed version of PostgreSQL which might be either 9.6 or 13.x

**Comment by nickboldt** [comment]
@tolusha so we need to keep 9.x forever? or can we declare it deprecated in 7.47 and drop it in 7.50?

**Comment by tolusha** [comment]
Yes, we have to keep it forever. We can't drop anything.
Migration guide to devspace 3.0 has nothing to do with upgrading PostgreSQL version

**Comment by nickboldt** [comment]
ok, but a NEW DS 3 install won't migrate an existing postgres 9.6 db to 13, right? it will install a fresh DB with no old content?

**Comment by tolusha** [comment]
Completely new installations use PostgreSQL 13.x version.

**Comment by RickJWagner** [comment]
A quick wish:  Postgres has been the source of occasional user troubles, especially with super-secure users.  (These often want to use their own DB, have different administrators for DBs vs. the application, etc.)
I'm not sure if it would be possible, but if we could find a way to eventually move the state kept in Postgres to another location (i.e. a ConfigMap or something) that would be *awesome*.

**Comment by l0rd** [comment]
@RickJWagner that's the issue https://github.com/eclipse/che/issues/21183

**Comment by nickboldt** [comment]
Two final thoughts on this one:

a) could we put out a press release (che-dev list, mattermost, Che Community call, etc. saying that we plan to remove postgres 9.6 from the CSV in the next 4 months, after which time existing installs will break and will need to be reinstalled (or the DB will need to be migrated to postgres 13.3). We're doing this for two reasons: 9.6 is EOL; 13.x is getting CVE fixes and 9.x is not.

b) could we remove 9.6 from downstream only, since anyone installing 3.0 will need a NEW INSTALL? Or will existing 2.15 installed postgres image be copied across into the new 3.0 install, and used by the new subscription?

**Comment by tolusha** [comment]
a) We need to finalize https://github.com/eclipse-che/che-docs/pull/2163
b) We can't remove, because we have migration guide from 2.15 to 3.0.

**Comment by tolusha** [comment]
I close this issue since I don't see a way how we can get rid of PostgreSQL 9.6 image
