### ISSUE TITLE
Include a link to go back to the dashboard in the workspace loading page

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21368]
### Is your enhancement related to a problem? Please describe

It's possible to start factory flow without the Dashboard, simply pasting a factory link from the clipboard. In case of factory fails and workspace is created but not running, it's really frustrating not having the ability to go to the Dashboard and fix the problem. It would be nice to have the ability to restart the factory from this page as well, similarly to the IDE loading flow.
![2022-05-02_22_31_56](https://user-images.githubusercontent.com/6310786/166314716-78a8d1cf-af66-4bb1-a5bb-c9f5391f5ee1.png)

### Describe the solution you'd like

Add breadcrumbs to IDE-loader and Factory-loader pages. It brings an ability to fix problems and restart the workspace.
![2022-05-02_22_10_28](https://user-images.githubusercontent.com/6310786/166315164-ee436200-8079-44df-8f2d-c03b7e1a8ab5.png)

### Release Notes Text

The workspaces loading page didn't had any link to get back to the dashboard. Now it's possible to click on a link on the top left of the page to get back to the dashboard and on a link that is shown when an error occurs.

**Comment by akurinnoy** [comment]
Hi @olexii4 

From the screenshot you've added to the issue, this page has the ability to restart the workspace:

<img width="628" alt="Screenshot 2022-05-03 at 08 52 01" src="https://user-images.githubusercontent.com/16220722/166410217-4470375d-a9cc-4b25-bf60-a44b0e28cd8e.png">

Don't you think about implementing a similar action button for the factory loading flow?

**Comment by olexii4** [comment]
> implementing a similar action button for the factory loading flow

@akurinnoy Yes, I do. I am thinking about implementing a similar action button for the factory loading flow(optional).

**Comment by dmytro-ndp** [comment]
@olexii4: your idea looks pretty good from UX perspective.
