### ISSUE TITLE
Empty Dashboard page because CORB blocked dashboard/common.5e4ffba6dddfdbbc6de5.js script load on OCP 4.10

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21364]
### Describe the bug

There was empty Eclipse Che Dashboard page on OCP 4.10 with next warnings in browser console.

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://oauth-openshift.apps.ci-ln-fij1gmb-72292.origin-ci-int-gce.dev.rhcloud.com/oauth/authorize?approval_prompt=force&client_id=eclipse-che-openshift-identity-provider-zcxsd3&redirect_uri=https%3A%2F%2Fche-eclipse-che.apps.ci-ln-fij1gmb-72292.origin-ci-int-gce.dev.rhcloud.com%2Foauth%2Fcallback&response_type=code&scope=user%3Afull&state=230de022a2b1f3535c3ce3c0e7d45318%3A%2Fdashboard%2Fcommon.5e4ffba6dddfdbbc6de5.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://oauth-openshift.apps.ci-ln-fij1gmb-72292.origin-ci-int-gce.dev.rhcloud.com/oauth/authorize?approval_prompt=force&client_id=eclipse-che-openshift-identity-provider-zcxsd3&redirect_uri=https%3A%2F%2Fche-eclipse-che.apps.ci-ln-fij1gmb-72292.origin-ci-int-gce.dev.rhcloud.com%2Foauth%2Fcallback&response_type=code&scope=user%3Afull&state=e633ccefb84b24e7bc8238f786dbd976%3A%2Ffavicon.ico with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

![Screenshot from 2022-04-29 11-34-24](https://user-images.githubusercontent.com/1197777/165918638-dfd51f95-3e37-412f-96e5-0cebb57f9f78.png)

Workaround:
1) open {Che-URL}dashboard/common.5e4ffba6dddfdbbc6de5.js in separate tab
2) after successful login, return to Dashboard

### Che version

next (development version)

### Steps to reproduce

1. Install Eclipse Che Next on OCP 4.10
2. Go to Dashboard page

### Expected behavior

Dashboard page to be loaded

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment]
Should be fixed by https://github.com/eclipse-che/che-dashboard/pull/519
