### ISSUE TITLE
Che dogfood instance launches running application but application not available

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21360]
### Describe the bug

application not available when launched from running workspace 

### Che version

next (development version)

### Steps to reproduce

1. https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/create-workspace
2. click on the NodeJS Angular Web Application tile (or any other one -- java-fuse also failed)
3. wait as workspace loads
4. open the workspace commands/editors panel on the right, from the cube icon
![image](https://user-images.githubusercontent.com/227597/165577224-eb7c13c5-fcf4-46c9-ae29-e0010f31070f.png)

5. click the `install-dependencies` command, wait until it completes
6. click the `build` command, wait until it completes
7. click the `start` command, wait until it completes and prompts you to open a new tab for the application on port 4200

![image](https://user-images.githubusercontent.com/227597/165577994-590f35f1-614a-431e-b12a-a142ab8094d2.png)

### Expected behavior

application should load. 

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by amisevsk** [comment]
Works for me -- maybe Theia is prompting to open the link before it's fully ready? I happened to wait a few seconds before clicking.

**Comment by nickboldt** [comment]
yeah no idea, but this happens to me all the dang time. Maybe it's my chrome settings, or my fedora-in-virtual-box-on-windows that's to blame. Anyway, closing.
