### ISSUE TITLE
Cannot download old versions of chectl

### ISSUE THREAD

**Issue by ghost** [eclipse/che#21366]
### Describe the bug

See [#2027 on the chectl repository](https://github.com/che-incubator/chectl/issues/2027) (I'm posting it here because that repository no longer accepts issues).

Since I posted on that issue, it's started happening on my host system too. I suspect it's not actually Ubuntu-specific; rather it's something that changed very recently and I only thought it was working on my host system because I had a tarball downloaded before the problem started.

Note that it's not just the version output that's wrong. The binary actually has newer version behavior (eg. the binary obtained from downloading v7.41.2 fails to deploy if you don't have an OIDC provider installed, which actual v7.41.2 did not do).

### Che version

7.41

### Steps to reproduce

1. Download an old release, such as v7.41.2, from [the chectl releases page]()
2. Extract
3. Run `bin/chectl version`

### Expected behavior

It shows the version number downloaded.

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by yujiri8** [comment]
Update: discovered that this was happening because chectl had left behind some files in /usr/local/lib/chectl, ~/.cache, and ~/.local. Deleting them caused the executable to show the correct version. I guess that it had downloaded a new version of chectl at some point and installed it into one of these loations and the executable (realize I've been incorrectly referring to it as a binary, it's a shell script) has some behavior like "check if there's a newer version of chectl installed somewhere and silently run that one instead, even if this is an older version".

Terrible behavior to have, and I suspect there's still a bug involved because I'm positive I never said yes to it asking if I wanted to update. But the mystery is solved.

**Comment by yujiri8** [comment]
Ah, new findings! This is definitely something Che does without asking after some time. I've observed twice now that after my cluster has been deployed for a while, workspaces can no longer be created; the creation process hangs forever and eventually times out, saying `Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'FailedScheduling', '0/1 nodes are available: 1 persistentvolumeclaim "claim-che-workspace" is being deleted.', 'workspacez95mjmp0ilhua4h1.che-plugin-broker'"`.

Is there a way to disable this behavior in v7.41.2?

**Comment by tolusha** [comment]
@yujiri8 
If you downloaded a new chectl version, then 
- follow [1] to upgrade chectl
or
- launch `bin/run` instead of `bin/chectl`

[1] https://github.com/che-incubator/chectl/#updating

**Comment by yujiri8** [comment]
I absolutely did not say yes to it asking me if I wanted to upgrade. This happened twice, and looks like it may also have happened to @gidduhome.

**Comment by amisevsk** [comment]
It sounds like this issue is not resolved

**Comment by yujiri8** [comment]
I haven't seen this happen in a long time. Maybe it was an issue only with 7.41.2 :shrug:

**Comment by yujiri8** [comment]
I just saw this happen with v7.49.0 updating to v7.51.0. I had 7.49, was doing some other work with trying to build the plugin registry, then came back to chectl to deploy che and it was 7.51.0. I never said yes to the update prompt.

**Comment by tolusha** [comment]
Try to disable chectl auto update by setting `export CHECTL_DISABLE_AUTOUPDATE=1`

https://github.com/eclipse/che/issues/18680#issuecomment-749485107

**Comment by yujiri8** [comment]
Ahhhhhh that explains it. Thank you

**Comment by yujiri8** [comment]
The behavior really should be documented btw
