### ISSUE TITLE
Cherry-pick https://github.com/eclipse-che/che-operator/pull/1370 to 7.46.x

### ISSUE THREAD

**Issue by metlos** [eclipse/che#21365]
### Is your task related to a problem? Please describe

This is to make sure that the follow up fix for https://github.com/eclipse/che/issues/21327 contained in the https://github.com/eclipse-che/che-operator/pull/1370 PR gets merged into the 7.46.x branch.

### Describe the solution you'd like

Cherry-pick the above PR also to the 7.46.x branch.

**Comment by nickboldt** [comment]
Since #21327 is upstream of https://issues.redhat.com/browse/CRW-2882, which is blocker for 3.0, so too this issue a a blocker for 3.0.

**Comment by metlos** [comment]
This has been done in https://github.com/eclipse-che/che-server/pull/300
