### ISSUE TITLE
Chectl contributing: Error: command workspace:start not found

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21363]
### Summary

in [CONTRIBUTING.md ](https://github.com/che-incubator/chectl/blob/main/CONTRIBUTING.md) , below command is present. 
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/10482177/165694969-6db754e9-adf2-474d-a3a3-7e5dbcbd2241.png">

When i execute the command i get below error. How to use this? What am i doing wrong?
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10482177/165694903-cbc4c0e5-c074-4ed4-9566-6b01c76770b3.png">

**Comment by tolusha** [comment]
Thank you for noticing that. We don't have `workspace` command anymore, we will update https://github.com/che-incubator/chectl/blob/main/CONTRIBUTING.md

**Comment by Divine1** [comment]
@tolusha  i'm intending to contribute to the project in whatever ways possible. please let me know  when the details are up to date.

**Comment by tolusha** [comment]
@Divine1 
Thank you!

**Comment by Divine1** [comment]
@tolusha  any update on this ?

**Comment by tolusha** [comment]
@Divine1 
If we are talking about workspace commands then we don't have any plans to add them

**Comment by Divine1** [comment]
@tolusha if that is the case, then what is the alternate command for it. I was just looking into contributing.Md file and wanted to execute the steps mentioned in it

**Comment by tolusha** [comment]
We had some drafts here [1]. 

@dmytro-ndp 
Does QE use any cli commands to create workspaces? Could you share pls?

[1] https://github.com/eclipse/che/issues/20671#issuecomment-993051102

**Comment by tsadigovAgmail** [comment]
(related issue)[https://github.com/eclipse/che/issues/21401]

**Comment by themr0c** [comment]
Docs team is not maintaining the chectl documentation. Therefore, removing the team/docs label.

**Comment by tolusha** [comment]
We have to do:
1. Rework `Create workspace, clone sources`. It is not possible to create workspace using chectl anymore.
Instead we need a factory link.
2. Remove `Create Workspace` & `Generate Devfile` sections
3. Update devfile [1] and ensure all commands work

[1] https://github.com/che-incubator/chectl/blob/75e3141877980fb6fdf1430dc9ed9a083ab3d3da/devfile.yaml
