### ISSUE TITLE
invalid `chectl` commands in docs and Che Dashboardr

### ISSUE THREAD

**Issue by kadel** [eclipse/che#21369]
### Describe the bug

It looks like new chectl (7.47.0) doens't have `auth:login` or `chectl workspace:logs` commands

But documentation (https://www.eclipse.org/che/docs/che-7/administration-guide/collecting-logs-using-chectl/) and login command that is copied to clipboard in Che Dashboard still refer to those commands

### Che version

7.47@latest

### Steps to reproduce

see description

### Expected behavior

command found in documentation or in Dashboard to exists

### Runtime

CodeReady Container

### Installation method

OperatorHub

### Environment

Linux

**Comment by benoitf** [comment]
Hello,
the documentation that you're refering https://www.eclipse.org/che/docs/che-7/administration-guide/collecting-logs-using-chectl/ is for 7.41 (look at the dropdown)

For the current version (stable one)
it's there
https://www.eclipse.org/che/docs/stable/administration-guide/collecting-logs-using-chectl/

**Comment by kadel** [comment]
And what the login command in Che dashboard?

**Comment by benoitf** [comment]
@kadel it's a dup of https://github.com/eclipse/che/issues/21070
