### ISSUE TITLE
Theia should verify that app is listening on endpoint before prompting to open in new tab

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21377]
### Is your enhancement related to a problem? Please describe

Theia has the very useful feature to pop up a toast notification when executing a run command starts a server, e.g. 

> Process nodejs-configmap is now listening on port 8080. Open it?

However, in some cases, clicking the "Open in New Tab" button opens the endpoint before the application is responding to requests, resulting in the "Application not available" page in OpenShift

### Describe the solution you'd like

Once an application starts listening on a port, Theia should poll the endpoint until it returns a non HTTP 503 response.

### Describe alternatives you've considered

Related to CRW issues https://issues.redhat.com/browse/CRW-2968, https://issues.redhat.com/browse/CRW-2963

**Comment by l0rd** [comment]
@amisevsk that affect VS Code too right?

**Comment by amisevsk** [comment]
From what @nickboldt described, it wasn't an issue in VS Code, but the nature of the the problem (waiting 5 seconds to click often resolves the issue) means it could be -- I haven't verified.
