### ISSUE TITLE
MicroK8S OIDC Issue

### ISSUE THREAD

**Issue by elielam** [eclipse/che#21378]
### Describe the bug

Microk8s OIDC not recognized.

### Che version

7.47@latest

### Steps to reproduce

Install Microk8s on debian 11.
Update kubeapi config for oidc.
Run chectl.

### Expected behavior

Chectl must pass the oidc check.

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2022-05-01T16:54:22.475Z Error: Command server:deploy failed. Error log: /home/agent/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1651424061496.
2022-05-01T16:54:22.475Z     at newError (~/.local/share/chectl/client/7.47.0/lib/util.js:199:19)
2022-05-01T16:54:22.475Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.47.0/lib/util.js:195:12)
2022-05-01T16:54:22.475Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.47.0/lib/commands/server/deploy.js:177:35)
2022-05-01T16:54:22.475Z     at Generator.throw (<anonymous>)
2022-05-01T16:54:22.475Z     at rejected (~/.local/share/chectl/client/7.47.0/node_modules/tslib/tslib.js:115:69)
2022-05-01T16:54:22.475Z Cause: Error: API server is not configured with OIDC Identity Provider, see details https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server. To bypass OIDC Provider check, use '--skip-oidc-provider-check' flag
2022-05-01T16:54:22.475Z     at ~/.local/share/chectl/client/7.47.0/lib/commands/server/deploy.js:380:19
2022-05-01T16:54:22.475Z     at Generator.next (<anonymous>)
2022-05-01T16:54:22.475Z     at fulfilled (~/.local/share/chectl/client/7.47.0/node_modules/tslib/tslib.js:114:62)
```

### Additional context

Hello,

I am currently having a problem installing eclipse che via chectl on microk8s.

The problem in question lies in the identification of the OIDC parameters of kubernetes.

I obviously (not without difficulty) took care to activate OIDC via keycloak by adding in `/var/snap/microk8s/current/args/kube-apiserver` the right arguments on my node and it works very well via kubectl.

![image](https://user-images.githubusercontent.com/34446626/166156156-56e100ab-d3fc-4586-95ab-22ed2b6f8315.png)

However chectl fails to pass the verification step of my OIDC configuration.

I initially disabled the check via the `--skip-oidc-provider-check` argument but that only delayed the problem, the process finished on a timeout because the `oauth-proxy` container of the `che-gateway` pod crashed with the following message: "... oidc-issuer-url is required".

Looking closer in the code it appears that in the [file](https://github.com/che-incubator/chectl/blob/main/src/commands/server/deploy.ts)  we are looking in the `kube-system` namespace for a pod with the label `component=kube-apiserver`.

Here :

    function ensureOIDCProviderInstalled(flags: any): Listr.ListrTask {
        ...
        const apiServerPods = await kube.getPodListByLabel('kube-system', 'component=kube-apiserver')

When I check in this namespace this is what I found : 

![image](https://user-images.githubusercontent.com/34446626/166156112-6776f9d2-ac3b-49ad-a44c-0be234676a25.png)

The closest reference I find to what we are looking for is in the `default` namespace on the `kubernetes ` service but i can't find to wich pod is it related.

![image](https://user-images.githubusercontent.com/34446626/166156270-5e11b037-f626-43c6-a61b-dee2655474b7.png)

Search pods with corresponding label : 

![image](https://user-images.githubusercontent.com/34446626/166156287-8820c9fa-3b73-4b27-adda-fbc982c7d834.png)

Is my microk8s installation having a problem or am I missing something on the OIDC or chectl ?

Plateform : `Linux servername 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`
Microk8s : `Microk8s v1.21.11`
Kubectl : `v1.22.4`
Kubernetes : `v1.21.11-3+2bdf0a81ac1652`

Thank you in advance (sorry for my bad english) !

**Comment by tolusha** [comment]
Hello @elielam 

> However chectl fails to pass the verification step of my OIDC configuration.

yes, pls use flag `--skip-oidc-provider-check`  in this case. To be honest I have never tested it with microk8s. I would be nice if you help us to improve OIDC detection here.

>  the process finished on a timeout because the oauth-proxy container of the che-gateway pod crashed with the following message: "... oidc-issuer-url is required".

To make Eclipse Che working, you have to set the following fields in a CheCluster CR:
```
spec:
  auth:
    identityProviderURL: 
    oAuthClientName: 
    oAuthSecret: 
```

I have a look pls also:
* https://github.com/eclipse/che/issues/21049#issuecomment-1022108499
* https://github.com/eclipse/che/issues/21049#issuecomment-1067776895

/cc @sparkoo

**Comment by l0rd** [comment]
Added to the list of [OIDC related issues](https://github.com/eclipse/che/issues/21304)

**Comment by Mbd06b** [comment]
> Hello @elielam
> 
> > However chectl fails to pass the verification step of my OIDC configuration.
> 
> yes, pls use flag `--skip-oidc-provider-check` in this case. To be honest I have never tested it with microk8s. I would be nice if you help us to improve OIDC detection here.
> 
> > the process finished on a timeout because the oauth-proxy container of the che-gateway pod crashed with the following message: "... oidc-issuer-url is required".
> 
> To make Eclipse Che working, you have to set the following fields in a CheCluster CR:
> 
> ```
> spec:
>   auth:
>     identityProviderURL: 
>     oAuthClientName: 
>     oAuthSecret: 
> ```
> 
> I have a look pls also:
> 
> * [Devworkspace native auth on Kubernetes - Unauthorized! Configured service account doesn't have access #21049 (comment)](https://github.com/eclipse/che/issues/21049#issuecomment-1022108499)
> * [Devworkspace native auth on Kubernetes - Unauthorized! Configured service account doesn't have access #21049 (comment)](https://github.com/eclipse/che/issues/21049#issuecomment-1067776895)
> 
> /cc @sparkoo


In addition to the keycloak values added to your checluster.yaml  values spec
I needed to add the CHE_ODIC__USERNAME_CLAIM as follows .... 
```
spec:
  components:
    cheServer:
      extraProperties:
         CHE_OIDC_USERNAME__CLAIM: email
```


Then I edited the API Server Configuration: Locate the configuration file for the Kubernetes API server (under /var/snap/microk8s/current/args/kube-apiserver for microk8s).

Add OIDC Options: Include the following lines (adjusting for your specific Keycloak configuration):

```
--oidc-issuer-url=https://<KEYCLOAK_DOMAIN>/auth/realms/<REALM_NAME>
--oidc-client-id=<CLIENT_ID>
--oidc-username-claim=email
--oidc-groups-claim=groups 
```
