### ISSUE TITLE
Workspace failed to start due to volume name longer than 63 characters

### ISSUE THREAD

**Issue by kadel** [eclipse/che#21370]
### Describe the bug

running on crc 2.0.1., Openshift 4.10.3, Installed Che using OpenShift's build-in OperatorHub.

When I try to start the workspace from the sample (I tried Java SpringBoot, ASP.Net Core web app and NodeJS Express) the workspace won't start and it shows the following error. 

```
Deployment.apps "workspacec1037db896524a46" is invalid: [spec.template.spec.volumes[0].name: Invalid value: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[3].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs", spec.template.spec.containers[1].volumeMounts[1].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs", spec.template.spec.containers[2].volumeMounts[4].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs", spec.template.spec.containers[3].volumeMounts[2].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs", spec.template.spec.initContainers[0].volumeMounts[4].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs", spec.template.spec.initContainers[1].volumeMounts[1].name: Not found: "automount-configmap-eclipse-che-openshift-operators-trusted-ca-certs"]
```

### Che version

7.47@latest

### Steps to reproduce

see bug description

### Expected behavior

working sample

### Runtime

CodeReady Container

### Installation method

OperatorHub

### Environment

Linux

**Comment by benoitf** [comment]
it has been fixed some days ago
references:
https://github.com/eclipse/che/issues/21327
https://issues.redhat.com/browse/CRW-2956

**Comment by ibuziuk** [comment]
@kadel closing. Feel free to reopen if still reproducible against nightly.
