### ISSUE TITLE
Add various mechanisms for preventing Eclipse Che breakages after updates in devfile GitHub org

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21389]
### Is your task related to a problem? Please describe

Eclipse Che is a devfile-centric project. However, the contributions to devfile.io are not verified against Eclipse Che and we adapt reactively to the changes, and sometimes find the issues very late. Examples are in the Additional context. 

### Describe the solution you'd like

every contribution to devfile org should be verified against Eclipse Che https://github.com/devfile using various mechanisms - unit tests, github actions etc.
The goal is to find problems and incompatibilities in devfile repos pro-actively, not reactively

### Describe alternatives you've considered

N/A

### Additional context

Related issues that illustrate the current problems:
- https://github.com/devfile/api/issues/767
- https://github.com/devfile/api/issues/768
- https://github.com/devfile/devworkspace-operator/pull/821
- https://github.com/devfile/devworkspace-operator/issues/816

**Comment by l0rd** [comment]
Related (subtask of) https://github.com/devfile/api/issues/681
