### ISSUE TITLE
Workspaces can not be started on the Eclipse Che instances - failed to process automount resources: auto-mounted volumes from configmap 'che-trusted-ca-certs' and configmap 'eclipse-che-dogfooding-trusted-ca-certs' have the same mount path

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21385]
### Describe the bug

the problem is related to the fix for having shorter cms names to comply with the 63 chars k8s limit - https://github.com/eclipse-che/che-operator/pull/1370
basically, old and new cms mount the same path and workspaces can not be started anymore

### Che version

7.47@latest

### Steps to reproduce

1. create new or start existing workspace
2. ERROR: workspace is failing to start:  failed to process automount resources: auto-mounted volumes from configmap 'che-trusted-ca-certs' and configmap 'eclipse-che-dogfooding-trusted-ca-certs' have the same mount path

### Expected behavior

Workspaces started without problem 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Workaround: manual removal of the old cm `<>-<>-trusted-ca-certs`

**Comment by tolusha** [comment]
The fix is backported to 7.46.x as well
https://github.com/eclipse-che/che-operator/commit/ec83305091925d999bf2d64c0de30de4d40ee30e
