### ISSUE TITLE
Allow admins to change workspaces inactivity and run timeout

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21390]
### Is your enhancement related to a problem? Please describe

Before switching to the DevWorkspace engine, it was possible to specify workspaces timeout through Che server properties `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT` and `CHE_LIMITS_WORKSPACE_RUN_TIMEOUT`.

Currently Che-Theia based workspaces are idled after 15 minutes of inactivity. This is specified in the [editor definition](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L130-L131) and it's not configurable by the user or by an admin (if not by patching the editor definition in the plugin registry or by publishing and using an alternative editor definition).

Note that VS Code and JetBrains IDE based workspaces are never idled and that we want to use a universal idling mechanism (there is a [separate issue for that](https://github.com/eclipse/che/issues/20345)).

### Describe the solution you'd like

`CheCluster` CRD should have:
- `devEnvironments.secondsOfInactivityBeforeIdling`
- `devEnvironments.secondsOfRunBeforeIdling`

That should be propagated as environment variables to the workspace containers:
- `SECONDS_OF_DW_INACTIVITY_BEFORE_IDLING`
- `SECONDS_OF_DW_RUN_BEFORE_IDLING`

Machine exec should parse those variables, if they exist, [when setting the timeout](https://github.com/eclipse-che/che-machine-exec/blob/16038137de6a6438444f2008d5597ae0527d9eb4/cfg/cfg.go#L85).

Machine exec should support `SECONDS_OF_DW_RUN_BEFORE_IDLING`

Theia definition should not specify the `--idle-timeout` parameter for machine exec.

The defaults should be 30 minutes for `secondsOfInactivityBeforeIdling` and `SECONDS_OF_DW_INACTIVITY_BEFORE_IDLING` and -1 for `secondsOfRunBeforeIdling` and `SECONDS_OF_DW_RUN_BEFORE_IDLING`

### Additional context

https://github.com/eclipse/che/issues/21322

### Release notes text

Administrators can specify the timeout for inactivity and running workspaces with the `CheCluster `spec.devEnvironment` fields `secondsOfInactivityBeforeIdling` and `secondsOfRunBeforeIdling` respectively. The default values are 30 minutes and -1 (no timeout) respectively.

**Comment by pdfruth** [comment]
I ran across this enhancement request while searching for any known method of customizing the workspace idle timeout.
It is super annoying to have to restart a workspace after only 15 minutes of idle.

I have searched, and found another suggested workaround [here](https://github.com/eclipse/che/issues/21334).
But, that workaround does not seem to work in my environment (Red Hat OpenShift Dev Spaces Operator V3.0  on Red Hat OpenShift Container Platform V4.10.18)

Questions:
- Is there any news on when this enhancement will be implemented?
- Is there any workaround to customize or disable the idle timeout in the meantime?

**Comment by l0rd** [comment]
Note that here we are talking about Theia, the default editor included in Che workspaces. If instead we specify to use VS Code, IntelliJ or PyCharm instead of Theia, those won't be idled at all (and this can be problematic too). So, @pdfruth, if you prefer no-idling you can refer to this [blog post draft](https://github.com/eclipse/che/issues/21322#issuecomment-1095262422) to use a different editor.

**Comment by l0rd** [comment]
@pdfruth sorry, I have updated the comment above with [the right link](https://docs.google.com/document/d/1pbtok7ajh7tsFOaX0kr2eZwLf3G3jYRkkn95-aZKEaQ/edit?usp=sharing).

**Comment by pdfruth** [comment]
@l0rd Thank you for the updated link to the blog post draft.
I have attempted to follow the instructions by adding .che folder containing a che-editor.yaml file to an existing Git repo.
However, upon creating a new Openshift Dev Spaces workspace, I still see the Theia editor (as seen in this screen-shot)
The Git repo containing my simple Python app is [here](https://github.com/pdfruth/voting-app-py-ds).
Can you see what I might have done wrong?

![2022-06-28_6-30-18](https://user-images.githubusercontent.com/11518334/176179430-a4d7f8c5-e945-48b9-8c7a-2013818fc8db.jpg)

**Comment by l0rd** [comment]
@pdfruth: you need a devfile c.f. https://github.com/pdfruth/voting-app-py-ds/pull/1, thanks for spotting that, I will update the document to mention that.

@olexii4 I have reproduced that upstream too: .che/che-editor.yaml is ignored if there is no devfile.

**Comment by pdfruth** [comment]
Thank You @l0rd.  I can confirm that the addition of a devfile has enabled the che-code editor to load.  And there is no idle timeout!!

**Comment by pdfruth** [comment]
Hi @l0rd 
As you mentioned earlier;

> ... if you prefer no-idling you can refer to this [blog post draft](https://docs.google.com/document/d/1pbtok7ajh7tsFOaX0kr2eZwLf3G3jYRkkn95-aZKEaQ/edit?usp=sharing) to use a different editor.

I have been able to get the che-code editor working in conjunction with the Red Hat OpenShift Dev Spaces V3.0 operator on an OCP cluster on x86 architecture.
I would like to do the same on an OCP cluster on the s390x architecture.  But I do not see container images at `https://quay.io/repository/che-incubator/che-code?tab=tags`.
Questions:
- Is there a place to find che-code images for s390x architecture?
- The blog article indicates the intent to make the VSCode editor = default, with 3Q22 timing.  Is the intent to make it default on all supported architectures where the Red Hat OpenShift Dev Spaces operator is supported today?  And is 3Q22 still valid?
- If there is not s390x images available today, is there instructions somewhere for building from source?

**Comment by l0rd** [comment]
@pdfruth @azatsarynnyy I don't think we have any s390 build yet and I am not sure if we have a plan to build it for 3Q22 (cc @azatsarynnyy @RomanNikitenko @nickboldt. To build it yourself you can have a look at the [PR check GitHub action](https://github.com/che-incubator/che-code/blob/main/.github/workflows/pr-check.yml).

**Comment by l0rd** [comment]
I have updated the description with CheCluster `devEnvironments` section instead of `workspaces` and I have added a note about the default values for the CheCluster fields and the env variables.

**Comment by dkwon17** [comment]
@l0rd , yes this can be closed and included in the 7.51 release notes

**Comment by nickboldt** [comment]
> @pdfruth @azatsarynnyy I don't think we have any s390 build yet and I am not sure if we have a plan to build it for 3Q22 (cc @azatsarynnyy @RomanNikitenko @nickboldt). To build it yourself you can have a look at the [PR check GitHub action](https://github.com/che-incubator/che-code/blob/main/.github/workflows/pr-check.yml).

For S390x support, or to contrubute to the effort, see https://issues.redhat.com/browse/CRW-3171

**Comment by RomanNikitenko** [comment]
Tested on `s390x` platform - yes - there are some problems on `yarn install` step:

```
<img width="760" alt="image" src="https://user-images.githubusercontent.com/5676062/180597843-540a2f55-ad45-4d49-bc3d-379c66d1f52e.png">

```
