### ISSUE TITLE
what is the `secret` attribute in `dex` configmap used for?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21403]
### Summary

in below screenshot, under `staticClients`, there is a `secret` attribute.
What does it indicate and What is it used for?

![image](https://user-images.githubusercontent.com/10482177/168743348-6403527d-a3ab-4dbd-a84c-31dceb4be91b.png)

**Comment by sparkoo** [comment]
https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/
