### ISSUE TITLE
`oidc_issuer_url` is empty in `che-gateway-config-oauth-proxy` configmap while setting up eclipse-che in k8s cluster

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21404]
### Summary

i'm in pursuit of setting up eclipse-che  in a k8s cluster.

i have installed dex in my k8s cluster by following the instructions mentioned [here](https://dexidp.io/docs/kubernetes/https://dexidp.io/docs/kubernetes/). as per the instructions mentioned here , i had to add below configuration in `/etc/kubernetes/manifests/kube-apiserver.yaml` file

```
--oidc-issuer-url=https://dex.example.com:32000
--oidc-client-id=example-app
--oidc-ca-file=/etc/ssl/certs/openid-ca.pem
--oidc-username-claim=email
--oidc-groups-claim=groups
```

After completing the steps to install `dex`. i installed eclipseche using below command. the installation completed.
```
chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/kubeapps/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.banana.click --k8spodreadytimeout=480000
```

i have  configured below 2 urls
```
https://dex.banana.click
https://eclipseche.banana.click/
```

when i hit the url `https://eclipseche.banana.click/` i receive 503 error
![image](https://user-images.githubusercontent.com/10482177/168783711-d8c553c5-a09e-473c-aa4f-8687cda757d1.png)

While analyzing, i found that the `oauth-proxy` container in `che-gateway` pod failed to start
![image](https://user-images.githubusercontent.com/10482177/168784262-a8314438-01fb-4b3b-a780-e4e6566aadca.png)

below error is shown in the `oauth-proxy` container logs of `che-gateway` pod.
![image](https://user-images.githubusercontent.com/10482177/168783877-f2e9747e-61bc-4fe2-ade7-b0f27f712a58.png)

below is detail of `che-gateway-config-oauth-proxy` configmap, in this configmap the `oidc_issuer_url` is empty. is this reason for the `oidc provider requires an oidc issuer URL ` error? 

![image](https://user-images.githubusercontent.com/10482177/168784554-02a45901-b284-41f6-8288-7a9a6930f9f0.png)

Please help me to fix this issue.

**Comment by sparkoo** [comment]
oauth proxy log is quite clear about that. why is the url empty? what's in your `/home/ubuntu/kubeapps/che-operator-cr-patch.yaml`? Can you print out `CheCluster` CR ?

**Comment by Divine1** [comment]
@sparkoo 
sorry for the delayed response.


below is the detail `of /home/ubuntu/kubeapps/che-operator-cr-patch.yaml`
![image](https://user-images.githubusercontent.com/10482177/169451167-c721d10e-b708-439a-9213-202cb7da0925.png)


Please let me know how to print `CheCluster` CR...i'm not aware of how to do it.

**Comment by Divine1** [comment]
CheCluster is updated to v2. i'm not using v1 anymore. v2 is working as per expectation (i think)
