### ISSUE TITLE
GitLab OAuth2 flow doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21413]
### Describe the bug

When trying to clone a private repository from gitlab an error occurs.

### Che version

7.47@latest

### Steps to reproduce

1. [Configure Che OAuth application in Gitlab](https://docs.gitlab.com/ee/integration/oauth_provider.html#authorized-applications), where `Callback URL` is `<che url>/api/oauth/callback`
1. [Configure Gitlab authentication secret](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-gitlab-oauth2-with-devworkspace-engine_che) where `<your_GitLab_service_URL>` is `https://gitlab.com/`.
2. Restart `che` pod.
3. Start a factory with a private gitlab repository.

See: Gitlab throws an error:
![screenshot-gitlab com-2022 05 18-16_06_29](https://user-images.githubusercontent.com/7668752/169045671-083ec442-2b28-4c6e-8b2e-b86e766a0455.png)

### Expected behavior

The factory must start successfully 

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

**Comment by benoitf** [comment]
AFAIK Gitlab SaaS is not supported, only onpremise GitLab

**Comment by vinokurig** [comment]
Ok, thanks closing then
