### ISSUE TITLE
command does not work - Deploy Plugin By Id

### ISSUE THREAD

**Issue by tsadigovAgmail** [eclipse/che#21417]
### Describe the bug

following documentation
https://www.eclipse.org/che/docs/che-7/contributor-guide/publishing-che-theia-plug-ins/
Adding a plug-in at Theia runtime > Visual Studio Code extension link

packages are not installed

### Che version

next (development version)

### Steps to reproduce

In a fresh che installation 
Run Command >Deploy Plugin By Id
Enter value > vscode:extension/redhat.vscode-xml   OR vscode:extension/jessemazzella.vscode-cat-ascii-faces
Check if extension was installed

### Expected behavior

Extension being installed

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/1032344/169626784-dc7ff1ef-aca8-46c5-8855-7744c5ac538f.png)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
which one?
```

**Comment by tsadigovAgmail** [comment]
Ok I see this feature has been removed in 2019
https://github.com/eclipse/che/issues/15054

But still documentation references it. From time to time this becomes frustrating. Not sure what source I can rely on.
Now at least documentation needs to be updated.

**Comment by tsadigovAgmail** [comment]
Will close this one
The documentation I am refering to is old and new documentation does not have details on these topics. At least I could not find.
May be I should open issue for lacking info in docs.

**Comment by l0rd** [comment]
Yes the documentation your are referring to is for Che 7.41 or older 
![image](https://user-images.githubusercontent.com/606959/169869994-c456de44-49b1-4458-a613-1a8f59935ff3.png). Please open a new issue if we want that content to be ported for newer versions of Che.
