### ISSUE TITLE
Unable to create temporary file - tmp_pack_XXXXXX' Permission denied

### ISSUE THREAD

**Issue by Les-Linux** [eclipse/che#21414]
### Summary

Hi,

I am trying to clone a repo on my Openshift instance (v4.9.31) of Che 7.48.0.445 but encounter the following error when I try doing so via the git plugin or the terminal window.

Clone Directory: /projects
Error: Unable to create temporary file '/projects/test/.git/objects/pack/tmp_pack_XXXXXX': Permission denied

I can clone the repo if I use /home/user for example. 

What am I missing here, as I would expect  a clean, new workspace to simply be able to clone a repository.

Les

**Comment by benoitf** [comment]
Hello @Les-Linux are you using a custom image ? If yes probably you may need to setup correct user permissions in /projects directory

Would be nice to have the devfile used
