### ISSUE TITLE
Handling of `olm-suggested-namespace` is strange and unintuitive

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21424]
### Describe the bug

When using `chectl server:deploy` with the `olm` installer on OpenShift, there are two steps:
1. Install the Che Operator on the cluster
2. Create a CheCluster (the operand) to install Che components (managed by the Che Operator).

Normally, installing Che will install the Operator to the `openshift-operators` namespace (the default for 'all-namespaces' operators), and create the CheCluster in the `eclipse-che` namespace. 

However, defining these options in chectl is very strange. The relevant options are

* ```
  -n, --chenamespace=chenamespace
      Eclipse Che Kubernetes namespace. Default to 'eclipse-che'
  ```
* ```
  --[no-]olm-suggested-namespace
      Indicate to deploy Eclipse Che in OLM suggested namespace: 'eclipse-che'.
      Flag 'chenamespace' is ignored in this case
      This parameter is used only when the installer is 'olm'.
  ```

By default, `--olm-suggested-namespace` is assumed, and the `-n` flag is ignored. However, from an OLM perspective, 

* The "suggested namespace" is meant to suggest the namespace for installing the _operator_ itself, not its operands. `chectl` uses the suggested namespace for the CheCluster, not the Operator.
* The actual suggested namespace in OLM is `openshift-operators`, as it is for all 'all-namespaces' operators:
  ```bash
  ❯ oc get packagemanifests eclipse-che -o yaml | yq -y '.status.channels[].currentCSVDesc.annotations."operatorframework.io/suggested-namespace"'
  openshift-operators
  ```

In order to install Eclipse Che so that
1. The Che Operator is installed in `openshift-operators`
2. The CheCluster is installed in an alternate namespace, e.g. `my-namespace`

it's necessary to specify the arguments
```bash
chectl server:deploy -n "my-namespace" --no-olm-suggested-namespace
```
which is confusing as the OLM suggested namespace should have no bearing on where the CheCluster is created.

### Che version

next (development version)

### Steps to reproduce

Execute `chectl server:deploy -p openshift`

### Expected behavior

Now that the Che Operator is an 'all-namespaces' operator, the `--[no-]olm-suggested-namespace` flags should be removed. Chectl does not support installing the Operator itself to a different namespace (to my knowledge) and is currently using this parameter to control where the CheCluster is deployed.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by nickboldt** [comment]
A related change in chectl that affects how downstream dsc behaves is:

https://github.com/che-incubator/chectl/commit/78914cfeb5fec8b1c88163a8682f96d879dd75cc#diff-cd7d31f9ae278a35a9874f61cb1f17509d27a3d98e4b5c59566e578b72e3d537L51
```
-         ctx.operatorNamespace = flags.chenamespace || DEFAULT_CHE_NAMESPACE
          ctx.operatorNamespace = DEFAULT_OPENSHIFT_OPERATORS_NS_NAME
```

So now, with 7.48.1/main version of chectl, it seems that installation with both `--olm-suggested-namespace` and `--no-olm-suggested-namespace` do the same thing. See details in:

https://issues.redhat.com/browse/CRW-2998?focusedCommentId=20329115&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20329115

**Comment by tolusha** [comment]
I removed `olm-suggested-namespace` flag since it make no sense now
