### ISSUE TITLE
Different behavior between repo URL and devfile URL in factory

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21433]
### Describe the bug

The behavior of factory URLs is different depending on if the URL points at e.g. a github repo versus a devfile.

* When a github repo is used as the factory URL, the theia editor is added to the workspace, along with some environment variables and a different container arguments (to run the remote-runtime)
* When the devfile from that same github repo is linked instead, the theia editor is still added, but the environment variables and container arguments are not applied

Adding the `che-theia.eclipse.org/vscode-extensions` attribute to the devfile does not make the behavior the same. 

### Che version

next (development version)

### Steps to reproduce

1. Create workspace using golang sample repo
    ```
    https://<che-host>/#https://github.com/che-samples/golang-example/tree/devfilev2
    ```
2. Create a workspace using the devfile from that repo:
    ```
    https://<che-host>/https://raw.githubusercontent.com/che-samples/golang-example/devfilev2/devfile.yaml?new
    ```
3. Create a workspace using that devfile, but with the project and `vscode-extensions` attribute present:
    ```
    https://<che-host>/#https://gist.githubusercontent.com/amisevsk/ccd62a455c8280f36e21cdeec169a0aa/raw/b17424c111e15bc91acd16a3a5ecd28d6df1135f/golang-sample.devfile.yaml?new
    ```

The diff in DevWorkspace spec between 1) and 2) is
```diff
   components:
-    - attributes:
-        app.kubernetes.io/name: tools
-        che-theia.eclipse.org/vscode-extensions:
-          - https://github.com/golang/vscode-go/releases/download/v0.23.0/go-0.23.0.vsix
-      container:
-        args:
-          - sh
-          - -c
-          - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
+    - container:
         endpoints:
           - exposure: public
             name: 8080-tcp
             protocol: http
             targetPort: 8080
         env:
           - name: GOPATH
             value: /projects:/home/user/go
           - name: GOCACHE
             value: /tmp/.cache
-          - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
-            value: /remote-endpoint/plugin-remote-endpoint
-          - name: THEIA_PLUGINS
-            value: local-dir:///plugins/sidecars/tools
           - name: CHE_DASHBOARD_URL
             value: https://eclipse-che.apps.ci-ln-dpbh8f2-72292.origin-ci-int-gce.dev.rhcloud.com
           - name: CHE_PLUGIN_REGISTRY_URL
             value: https://eclipse-che.apps.ci-ln-dpbh8f2-72292.origin-ci-int-gce.dev.rhcloud.com/plugin-registry/v3
           - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
             value: http://plugin-registry.eclipse-che.svc:8080/v3
         image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
         memoryLimit: 2Gi
         mountSources: true
         sourceMapping: /projects
-        volumeMounts:
-          - name: remote-endpoint
-            path: /remote-endpoint
-          - name: plugins
-            path: /plugins
```

The diff between 1) and 3) is the same, except the attributes are present (including `app.kubernetes.io/name`, which is added)

### Expected behavior

Devfiles should be processed in roughly the same way regardless of whether they're from a github repo or a plain devfile. 

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
AFAUIK it's because in first case Factory is able to check .che / .vscode folders / files while in the gist case there is no context, so it takes only information from the devfile.
This is also why all samples are urls+context and not only a devfile content

**Comment by amisevsk** [comment]
The only additional context I can find in the https://github.com/che-samples/golang-example/tree/devfilev2 repo is
 
* `.vscode/extensions.json`:
    ```jsonc
    {
      // See https://go.microsoft.com/fwlink/?LinkId=827846
      // for the documentation about the extensions.json format
      "recommendations": [
        "golang.go"
      ]
    }
    ```
* `.vscode/launch.json`:
    ```jsonc
    {
      // Use IntelliSense to learn about possible attributes.
      // Hover to view descriptions of existing attributes.
      "version": "0.2.0",
      "configurations": [
        {
          "name": "Debug current file",
          "type": "go",
          "request": "launch",
          "mode": "auto",
          "program": "${fileDirname}"
        }
      ]
    }
    ```

As far as I know, the `extensions.json` is only used to decide which plugins to install (hence the `che-theia.eclipse.org/vscode-extensions` attribute), and `launch.json` is only used while the editor is running. 

Is there a good reason to not add the required fields in the gist case? I don't see anything in the repo itself to tell Che that it's safe to modify that container. This approach makes it impossible to use a devfile that's not part of a repository.

**Comment by benoitf** [comment]
You can inline `.vscode/extensions.json` in the devfile.yaml

**Comment by dkwon17** [comment]
I've set this issue to P2 since I don't think it has a major impact to users today, but please feel free to change it
