### ISSUE TITLE
Processes listening on localhost are not exposed by the gateway

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21430]
### Describe the bug

Although I have defined the following endpoint in my devfile:

```yaml
      - name: tilt
        targetPort: 10350
        exposure: public
        protocol: http
        attributes:
          urlRewriteSupported: false
```

Eclipe Che Port extension ask me if I want to add a redirect to it:

![image](https://user-images.githubusercontent.com/606959/170744183-f47dbcda-23a8-4464-a697-c8e60432a630.png)
 
And although I answer yes to this question then I am not able to access the application using the browser. I get a blank screen:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/606959/171881293-af73745f-abaf-443d-bda0-b2c1c00d53d3.png">

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/606959/171881202-983053f6-750d-462e-b317-6f29d0e778c2.png">

If I start the application to listen to the interface `0.0.0.0` then everything works fine:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/606959/171881642-34ccc0d7-5f75-41d3-9731-3e32a60c81e3.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/606959/171881540-d9fcaca7-3fb0-4455-8752-59b26ce0f2fc.png"> 

### Che version

next (development version)

### Steps to reproduce

Open a workspace [Eclipse Che dogfooding using this link (for Che committers only)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/tilt-example-java/tree/c62ccf40010ace2ea5315417ff7dc7c70f0a93d6) instance.

Open a shell and run `tilt up`:

```sh
cd 201-quarkus-live-update && tilt up -f Tiltfile.buildah
```

### Expected behavior

I was expecting the port to be redirected automatically (without asking).

And in particular I need to set the attribute `urlRewriteSupported: false` on that endpoint and that's not the case with the pre-defined che-code endpoints.

**Comment by l0rd** [comment]
@benoitf do you have any clue?

**Comment by benoitf** [comment]
@l0rd my guess it that tilt is listening to `127.0.0.1` only so while you're saying that this port is reachable from the outside it's still not 'exposed' 

try using `--host 0.0.0.0` on tilt


```bash
tilt up --host 0.0.0.0 -f Tiltfile.buildah
```

**Comment by benoitf** [comment]
should we close the issue then ?

**Comment by l0rd** [comment]
I have updated the description but it still looks like a gateway issue (not a plugin-port issue). We should be able to expose processes listening to localhost too shouldn't we?

**Comment by benoitf** [comment]
yes it should be the role of the gateway to simplify such usecase (do not need to change commands to execute)
