### ISSUE TITLE
Support OAuth flow for Gitlab SaaS

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21435]
### Is your task related to a problem? Please describe

Che supports Gitlab onpremises version only. Add the Saas version suport.

### Describe the solution you'd like

Add the Saas version suport.

### Additional context

https://github.com/eclipse/che/issues/20583

**Comment by vinokurig** [comment]
@benoitf @l0rd
I've tried to apply the gitlab oauth secret as described [here](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-gitlab-oauth2-with-devworkspace-engine_che) with the `che.eclipse.org/scm-server-endpoint` as `https://gitlab.com` and it worked.
So I believe that we can consider that we do support gitlab SAAS oAuth2. The only thing is that in the current state Che doesn't support GitLab SAAS and on-premises versions at the same time. We can configure only SAAS **or** on-premises version with the current oAuth provider. So do we need to support them at the same time? WDYT?

**Comment by l0rd** [comment]
@vinokurig thanks for investigating.
We can ignore supporting both SaaS and on-prem at the same time. 
Please check/update the documentation (we should mention that gitlab.com is supported) before closing this issue.
