### ISSUE TITLE
Automate workspace startup verification against the proxy Openshift cluster

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21446]
### Is your task related to a problem? Please describe

proxy and airgap-related issues are discovered very late during the pre-release testing. Need to automate the basic workspace startup flow against the proxy OpenShift 4.10 cluster

### Describe the solution you'd like

A periodic nightly job that:
- creates the 4.10 proxy cluster
- installs the nightly version of Eclipse Che 
- starts the workspace
- wait till the workspace is in the running state
- execute the build command

### Describe alternatives you've considered

probably we should start the automation with the `che-code` based workspaces

**Comment by tolusha** [comment]
Already done on regular basis in PR checks
