### ISSUE TITLE
Validate full air gap scenario with che-code

### ISSUE THREAD

**Issue by svor** [eclipse/che#21443]
### Is your task related to a problem? Please describe

Before switching to the Che-Code as a default editor we need to make sure that all functionality works on AirGap environment.

AirGap scenario: dependencies download, project samples zip files, git servers behind proxy, untrustesd TLS certs

### Describe the solution you'd like

Setup AirGap environment and validate all scenarios

**Comment by svor** [comment]
depends on https://github.com/eclipse/che/issues/20549

**Comment by svor** [comment]
Related: can't install an extension from the embedded openVSX #21662

**Comment by l0rd** [comment]
@svor can we close this issue?

**Comment by svor** [comment]
@l0rd I didn't test Che on AirGap cluster after https://github.com/eclipse/che/issues/21662
so, I'd like to test it one more time

**Comment by l0rd** [comment]
Ok great, thanks.

**Comment by svor** [comment]
Tested with AirGap DS instance, didn't detect any problem
