### ISSUE TITLE
docs: add more details in the example monitoring stack setup 

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21444]
### Is your enhancement related to a problem? Please describe

In the Prometheus/Grafana docs: https://www.eclipse.org/che/docs/next/administration-guide/monitoring-the-dev-workspace-operator/, we walk the reader through an example Prometheus Grafana setup for monitoring the DWO and Che-Server Java metrics.

There are a few "fill in the blank" sections in the provided yaml files:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/83611742/172472964-8e8e106a-195b-4859-a872-212d48e8a12f.png">

It can be difficult to determine what the correct values are.

### Describe the solution you'd like

Add a few sentences explaining how to fill in these blanks.

It would be nice to mention:
* What namespace Prometheus/Grafana is installed in, for the example setup
* What service account is the Prometheus pod using
* Mention that a route/ingress can be created to access the Prometheus and Grafana dashboards

**Comment by dkwon17** [comment]
I am interested in taking a look at this

**Comment by themr0c** [comment]
Cloned in https://issues.redhat.com/browse/RHDEVDOCS-4196

**Comment by dkwon17** [comment]
Closed thanks to https://github.com/eclipse-che/che-docs/pull/2379 being merged
