### ISSUE TITLE
Blank page after installing Che on minikube

### ISSUE THREAD

**Issue by rigman11** [eclipse/che#21442]
### Describe the bug

I tried an installation of che 7.48.1 on minikube (on virtualbox) but I had an error while installing eclipse che saying : 
`Failed` to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator:7.48.1".` 

Configuration : 

- Ubuntu 20.04.04 
- eclipse che 7.48.1
- chectl 7.48.1
- minikube 1.25.2
- virtualbox 6.1.32_Ubuntu r149290

Then I tried with a minikube on docker, all goes well but in the end I cannot access to the server interface.

Configuration :
docker 20.10.16
- Ubuntu 20.04.04 
- eclipse che 7.48.1
- chectl 7.48.1
- minikube 1.25.2
- docker 20.10.16

### Che version

7.47@latest

### Steps to reproduce

Minikube on virtualbox:
1. $ minikube start --vm-driver=virtualbox --addons=ingress,dashboard --memory=10240 --cpus=4 --disk-size=50GB
2. $ chectl server:deploy --platform minikube --k8spodreadytimeout=500000

Minikube on docker
1. $ minikube start --vm-driver=docker --addons=ingress,dashboard --memory=10240 --cpus=4 --disk-size=50GB
2. $ chectl server:deploy --platform minikube --k8spodreadytimeout=500000
3. Added the certificate cheCA.crt to chrome
4. used the server url

### Expected behavior

When I fallow the install documentation, I expect to have access to the che server at the end of the installation.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

**Comment by l0rd** [comment]
Hi @rigman11, thanks for reporting this issue.

Can you please provide more details about "I cannot access to the server interface". What URL are you trying to open? What's the message you see on your browser? Do you see any error in the developer console? A screenshot will be helpful as well.

> Added the certificate cheCA.crt to chrome
@rigman11 there is no need to add the certificate to chrome
