### ISSUE TITLE
oAuth-proxy enhancements for Azure AKS deployment

### ISSUE THREAD

**Issue by karatkep** [eclipse/che#21450]
### Is your enhancement related to a problem? Please describe

There are several enhancements of **ouath-proxy** configuration (aka oauth-proxy.cfg) for kubernetes:
- To set `pass_access_token` to `true` (default value is `false`) to pass access token to upstream via "X-Forwarded-Access-Token"
- To set `cookie_refresh` to `1h0m0s` to refresh the cookie when duration has elapsed after cookie was initially set.
- To add `whitelist_domains` to whitelist che domain (ie: .yourcompany.com)
- To add `cookie_domains` to set cookie domain to force cookies to (ie: .yourcompany.com)
- To add `OAuthScope` to Che Resource to allow users to configure Access Token Scope.

### Describe the solution you'd like

Update **che-operator** to support addition configuration of **ouath-proxy** for kubernetes

### Release Notes Text 

Enhancements needed to deploy Che on Azure AKS, contributed by @karatkep. Thank you for your contribution!

**Comment by l0rd** [comment]
@karatkep thank you for this issue and the related contribution. Those enhancements were needed to deploy to AKS? And using the instructions in [your repo](https://github.com/karatkep/che-aks-installer) are ment to be used by anyone trying to deploy to AKS? 

I am asking because we are considering to:
1. make this PR as a new and notworkthy addition to include in next release notes
2. proposing you to contribute a blog post that explains how to deploy Che to AKS

**Comment by karatkep** [comment]
Hi Mario,
It's correct, the proposed enhancements were needed to deploy Che to Azure
AKS. My instructions will be slightly updated because we found a more
elegant way to solve reported issue during code review. Thanks to @tolusha
and @sparkoo for the help.

And of course I will be glad to write a blog post and explain what issue we
met and how it has been resolved in the new version of Che.

Best Regards,
Piotr (aka karatkep)

**Comment by karatkep** [comment]
@l0rd Please review https://github.com/eclipse-che/blog/pull/29

**Comment by l0rd** [comment]
Faster than the wind 👍  Will review that later today.

**Comment by l0rd** [comment]
@tolusha @sparkoo it would be great if you have time to have a look at the blog post too.

**Comment by max-cx** [comment]
RN: upstream only

**Comment by nickboldt** [comment]
test
