### ISSUE TITLE
API server is not configured with OIDC Identity Provider

### ISSUE THREAD

**Issue by hellomaybe** [eclipse/che#21453]
### Describe the bug

Administrator@Maybe MINGW64 ~
$ chectl server:deploy --platform docker-desktop
› Installer type is set to: 'operator'
› Current Kubernetes context: 'docker-desktop'
  √ Verify Kubernetes API...[OK]
  √ 👀  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "eclipse-che"...[Not Found]
  × Check if OIDC Provider installed...[Not Found]
    → API server is not configured with OIDC Identity Provider, see details https://kubernetes.io/docs/reference/access-authn-au
t…
    Error: Command server:deploy failed. Error log: C:\Users\Administrator\AppData\Local\chectl\error.log. Eclipse Che logs:
    C:\Users\Administrator\AppData\Local\Temp\chectl-logs\1654761291825.

### Che version

7.47@latest

### Steps to reproduce

$ chectl server:deploy --platform docker-desktop

### Expected behavior

install eclipse-che on docker-desktop 

### Runtime

Docker Desktop

### Installation method

chectl/latest

### Environment

Windows

**Comment by tolusha** [comment]
Hi @hellomaybe 
It it error message about necessity to install OIDC identity provider before deploying Eclipse Che.
You can try on minikube, chectl will deploy OIDC itself for this platform
