### ISSUE TITLE
in k8s platform - received `500 internal server error` after redirecting from `github successful login flow ` to `dex` to `eclipse-che`

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21464]
### Summary

below is my k8s version and chectl version
<img width="1702" alt="image" src="https://user-images.githubusercontent.com/10482177/173581215-cfe9ee91-aa2e-427a-8f8b-70d05b7386c1.png">

i have completed my eclipse installation using below command in k8s cluster.
```
chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/chefiles/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=600000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=600000
```

in the above command i have given domainname as `eclipseche.mangotree.click` but the actual domain exposed via ingress  is`eclipseche.mangotree.click:32181` . the above command doesnot accept `eclipseche.mangotree.click:32181` as a value for domainName

 i have integrated github with dex. After the authentication with `github`, the url is redirected to `dex` and then to `eclipse-che`

but i receive `500 internal server error` as shown in below screenshot 

```
https://eclipseche.mangotree.click:32181/oauth/callback?code=vstnvnqkzeb6kxp2lvs6pvgms&state=PF7h_CQwmg2ibzPxf-BDo5eSUqTR3Py77zEdV4qcOzA%3A%2Fdashboard%2F
```

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/10482177/173569462-7e1d4056-97c2-4f48-ad29-9af35a0475fd.png">

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/10482177/173570140-db6d4a44-7912-440e-ba34-d37508a949c2.png">

below is my `dex.yaml` configuration
<img width="749" alt="image" src="https://user-images.githubusercontent.com/10482177/173582951-5bd7707d-f48c-4df1-8fb7-f64b0bd529f9.png">

please help  me to fix this issue

**Comment by Divine1** [comment]
@tolusha  @sparkoo  please help me on this if you could

**Comment by sparkoo** [comment]
anything in dex logs?

**Comment by Divine1** [comment]
@sparkoo 

dex logs
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/10482177/173594693-50f78080-fdb2-43e4-8351-30b43acc8a3d.png">

**Comment by sparkoo** [comment]
https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app 
I believe that URL in step 8 must match what you set in `redirectURI` https://dexidp.io/docs/connectors/github/#configuration and it must be URL to Dex. I don't think chectl `--domain` parameter has effect in this.

**Comment by tolusha** [comment]
`chectl` uses `--domain` for:
* set `spec.networking.domain` field in a CheCluster CR
* set ingress host [1] (for minikube only)
* set issuer url [2] (for minikube only)

[1] https://github.com/che-incubator/chectl/blob/af390a5f013561456dfd42db652bc663e08178ac/resources/dex/ingress.yaml#L16
[2] https://github.com/che-incubator/chectl/blob/9db79572f099e98da90d6969fd907caac66096bb/resources/dex/configmap.yaml#L10

**Comment by Divine1** [comment]
i'm closing this ticket as i don't think i will be able find out the reason for the issue
