### ISSUE TITLE
It's not possible to run a Task in Che-Code if it's not `che` type

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21466]
### Describe the bug

If `tasks.json` file contains a task of non-che type (e.g. `shell`), it can't be launched.

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace with the Che-Code editor.
2. Run any non-che task defined in the `tasks.json` file.

Test `tasks.json` can be created with `Terminal > Configure Tasks... > Create tasks.json file from template > maven`.

Terminal panel is open, but the task is not run.

### Expected behavior

A task should be run in a default (usually `tools`) container.

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1636395/173622252-32b7aa6a-227a-4cd3-8600-5a6177d17ea1.png)

### Installation method

chectl/next

### Environment

Linux

### Release Notes Text

Tasks included in a `tasks.json` file of a type other than `che` were not loaded in a VS Code running in a Che workspace. This has been fixed in this release and `tasks.json` with tasks of any type are supported and loaded in a Che workspace.

**Comment by azatsarynnyy** [comment]
It's because the task is sent to machine-exec component for execution in a target container.
In the case of non-Che tasks (shell, etc.) the target container can't be specified, so machine-exec doesn't know where to execute it. We need to rework it to execute any non-Che task in a single container or probably ask the user interactively to specify the target container.

**Comment by apupier** [comment]
in my case, i would expect to be executed int he same container than the VS Code extension.

**Comment by l0rd** [comment]
@azatsarynnyy it looks like there is workaround: [the task label should match the container name](https://github.com/abaker-9/dev-pwsh/blob/master/terminal.md#failed-task).

**Comment by l0rd** [comment]
> in my case, i would expect to be executed int he same container than the VS Code extension. (I do not know if it would be a common default expectation but as it is the SV Code extension which is executing the task, it seems quite natural)

@apupier when using a VS Code based workspace the extensions (and VS Code itself) run in the Devfile first container. Running the extensions in sidecar containers (aka running extensions remotely) is not supported with VS Code.

**Comment by l0rd** [comment]
[Downstream issue](https://issues.redhat.com/projects/CRW/issues/CRW-3365)

**Comment by azatsarynnyy** [comment]
@l0rd yes, it's done and we can close it.
We restored the VS Code native terminal in Che-Code (https://github.com/che-incubator/che-code/pull/124).
So, all task types supported by vanilla VS Code can now be run in Che-Code.
