### ISSUE TITLE
Cannot upload some vsix using Code Server

### ISSUE THREAD

**Issue by apupier** [eclipse/che#21468]
### Describe the bug

Trying to install from vsix this extension https://marketplace.visualstudio.com/items?itemName=redhat.atlasmap-viewer

There is  the endless waiting icon.

### Che version

next (development version)

### Steps to reproduce

1. open a workspace with Code Server
2. Go to Extensions view
3. Click on the ... and select intall from .vsix
4. Pick the vscode-atlasmp vsix

### Expected behavior

vsix extension is uploaded.

As intermediary step, at least having an error would be nice.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell
Found no error in log
```

### Additional context

using che dogfooding instance

**Comment by benoitf** [comment]
hello, not sure someone is actively maintaining coder integration
