### ISSUE TITLE
OPTIONS request to "/api/" failed, reason: Internal server error occurs. API is not accessible 

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21476]
### Summary

my chectl version
<img width="430" alt="image" src="https://user-images.githubusercontent.com/10482177/174280286-1ecebefe-2c2e-4f79-9a09-8ad8343debba.png">

i have installed eclipse-che using below command
```
chectl server:deploy --che-operator-cr-patch-yaml=/Users/divine/Documents/office_tasks/TAP-4540/terraformCheJune17/eclipseche_yaml/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=1000000 --domain=eclipseche-dchelladurai-chejune15.calatrava.vmware.com --k8spodreadytimeout=1000000
```
i have integrated `dex` with github connector . i followed the steps mentioned [here](https://dexidp.io/docs/kubernetes/) , to configure `dex` with github connector.

when i hit [eclipse-che dashboard ](https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/)url, the webpage redirects to github login and after successful authentication flow in github, the webpage redirects back to [eclipse-che dashboard](https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/) url, but it fails to completely load the webpage due to below error.

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/api/ ---OPTIONS request-- this api throws errorMessage `500 Internal server error occurs. API is not accessible`

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/api/  --- what does this api do?

below is the output of `che` ingress in `eclipse-che` namespace.  i have installed [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) in the k8s cluster.  
is this error anything related to my ingress configuration?
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/10482177/174295798-7cebb662-e61b-49d1-9cdf-3169fd4738d1.png">

Please help me to fix this error @tolusha  @sparkoo 

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/10482177/174279118-21954d1c-6f93-4b6e-8ae6-0778891635b0.png">

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/10482177/174279377-3574a775-50f4-4d11-9c91-1afdb0d6bcf2.png">

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10482177/174279486-be952766-b505-4f50-9b2d-be110a2d12b0.png">

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/api/

<img width="806" alt="image" src="https://user-images.githubusercontent.com/10482177/174279567-1a2bf715-ca21-43b9-b3f3-52b143752bea.png">

`checluster` output `kubectl get checluster eclipse-che -n eclipse-che -o yaml`

```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  creationTimestamp: "2022-06-17T10:02:53Z"
  finalizers:
  - checluster.che.eclipse.org
  - cheGateway.clusterpermissions.finalizers.che.eclipse.org
  - cheWorkspaces.clusterpermissions.finalizers.che.eclipse.org
  - namespaces-editor.permissions.finalizers.che.eclipse.org
  - devWorkspace.permissions.finalizers.che.eclipse.org
  - dashboard.clusterpermissions.finalizers.che.eclipse.org
  generation: 2
  name: eclipse-che
  namespace: eclipse-che
  resourceVersion: "736485"
  uid: 68fc4e54-e437-497b-a7ee-24264735a6a2
spec:
  components:
    cheServer:
      debug: true
      deployment:
        securityContext: {}
      logLevel: INFO
      proxy: {}
    dashboard:
      deployment:
        securityContext: {}
    database:
      credentialsSecretName: postgres-credentials
      deployment:
        securityContext: {}
      externalDb: true
      postgresDb: dbche
      postgresHostName: database-1-postgres.cq9mxgg86wjj.ap-south-1.rds.amazonaws.com
      postgresPort: "5432"
      pvc: {}
    devWorkspace:
      deployment:
        securityContext: {}
    devfileRegistry:
      deployment:
        securityContext: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      deployment:
        securityContext: {}
  containerRegistry: {}
  devEnvironments:
    defaultNamespace:
      template: <username>-che
    storage:
      pvc: {}
      pvcStrategy: common
    trustedCerts: {}
  networking:
    auth:
      gateway:
        deployment:
          securityContext: {}
      identityProviderURL: https://dex-dchelladurai-chejune15.calatrava.vmware.com
      oAuthClientName: eclipse-che
      oAuthSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    domain: eclipseche-dchelladurai-chejune15.calatrava.vmware.com
    tlsSecretName: che-tls
status:
  chePhase: Active
  cheURL: https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com
  cheVersion: next
  devfileRegistryURL: https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/devfile-registry
  gatewayPhase: Established
  pluginRegistryURL: https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/plugin-registry/v3
  workspaceBaseDomain: eclipseche-dchelladurai-chejune15.calatrava.vmware.com
```

my `dex.yaml` configuration

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex # This is created below
      containers:
      - image: ghcr.io/dexidp/dex:v2.30.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

        ports:
        - name: https
          containerPort: 5556

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls

        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-secret

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: dex.example.com.tls
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex
data:
  config.yaml: |
    issuer: https://dex-dchelladurai-chejune15.calatrava.vmware.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: f5108abcdef
        clientSecret: b193d487a4bfe44abcdef
        redirectURI: https://dex-dchelladurai-chejune15.calatrava.vmware.com/callback
        org: kubernetes
    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: eclipse-che
      redirectURIs:
      - 'https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/oauth/callback'
      name: 'eclipse-che'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
  type: ClusterIP
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex           # Service account assigned to the dex pod, created above
  namespace: dex  # The namespace dex is running in


```

**Comment by sparkoo** [comment]
anything in dex, oauth-proxy or traefik logs ?

**Comment by Divine1** [comment]
@sparkoo thank you for the response



below is my ingress controller logs
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/10482177/174298227-13409931-4577-484b-a1a5-34fbc0eaeed6.png">

oauth-proxy logs
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/10482177/174298500-985c380e-8d2e-46cb-89c7-6ee7805cc383.png">

i didnot find any useful information in traefik logs 
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10482177/174298975-9b0974d7-2583-471c-8f70-fc6aeb66ff77.png">



dex logs shows login successful
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/10482177/174299283-de7cb29e-14ed-4738-b739-0b3d6fee2adc.png">


https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/api/ ---OPTIONS request-- this api throws errorMessage 500 Internal server error occurs. API is not accessible

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/api/ --- what does this api do?

is there any issue with my `che` ingress config?
below is the output of che ingress in eclipse-che namespace. i have installed [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) in the k8s cluster.
is this error anything related to my ingress configuration?
![image](https://user-images.githubusercontent.com/10482177/174299519-f1d618e3-feda-4707-a0e1-b113373ef2a0.png)

**Comment by Divine1** [comment]
@sparkoo 

i have attached logs of `che-7c758bc8d9-7mxdc` pod inside `eclipse-che` namespace.
[che-7c758bc8d9-7mxdc.log](https://github.com/eclipse/che/files/8927532/che-7c758bc8d9-7mxdc.log)

please let me know your feedback

**Comment by Divine1** [comment]
@sparkoo @tolusha 

i have added below OIDC configuration in /etc/kubernetes/manifests/kube-apiserver.yaml .
i referred this [using kubernetes with dex](https://dexidp.io/docs/kubernetes/) documentation and [generated](https://github.com/dexidp/dex/tree/master/examples/k8s) the  openid-ca.pem file, public key , private key using openssl.



```
- --oidc-issuer-url=https://dex-dchelladurai-chejune15.calatrava.vmware.com
- --oidc-client-id=eclipse-che
- --oidc-ca-file=/etc/kubernetes/pki/openid-ca.pem
- --oidc-username-claim=email
- --oidc-groups-claim=groups
```

**Comment by Divine1** [comment]
@tolusha @sparkoo 

i will follow below process present in [the link which you shared](https://www.eclipse.org/che/docs/stable/administration-guide/importing-untrusted-tls-certificates/) and reply the feedback
<img width="634" alt="image" src="https://user-images.githubusercontent.com/10482177/174309466-28d2f2a5-32b7-425b-b72e-6294f72d116a.png">

**Comment by Divine1** [comment]
@tolusha  @sparkoo 

below is the `custom-certs` file which i  created in `eclipse-che` namespace as per the [documentation](https://www.eclipse.org/che/docs/stable/administration-guide/importing-untrusted-tls-certificates/). is this correct?


<img width="615" alt="image" src="https://user-images.githubusercontent.com/10482177/174316044-488d1cbe-837f-4a71-9bc6-03029d324a6e.png">

i used below commands to create it

```
kubectl create configmap custom-certs --from-file=calatrava-ssl/openid-ca.pem -n eclipse-che

kubectl label configmap custom-certs app.kubernetes.io/part-of=che.eclipse.org app.kubernetes.io/component=ca-bundle -n eclipse-che
```
