### ISSUE TITLE
Unable to list devworkspaces: devworkspaces.workspace.devfile.io is forbidden: User  cannot list resource "devworkspaces" in API group "workspace.devfile.io" in the namespace

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21477]
### Summary

my chectl version
![image](https://user-images.githubusercontent.com/10482177/174334535-7b1cd437-9b26-49a6-9b6d-4cfbfa75ea48.png)

i have installed `eclipse-che` on k8s platform using below command
```
chectl server:deploy --che-operator-cr-patch-yaml=/Users/divine/Documents/office_tasks/TAP-4540/terraformCheJune17/eclipseche_yaml/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=1000000 --domain=eclipseche-dchelladurai-chejune15.calatrava.vmware.com --k8spodreadytimeout=1000000
```
i have integrated dex with github connector . i followed the steps mentioned [here](https://dexidp.io/docs/kubernetes/) , to configure dex with github connector.

when i hit [eclipse-che dashboard ](https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/)url, the webpage redirects to github login and after successful authentication flow in github, the webpage redirects back to [eclipse-che dashboard](https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/) url, but it fails to completely load the webpage due to error in below api's.

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/api/namespace/divine-c-che-5j1hbg/devworkspacetemplates --403 - get request

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/api/namespace/divine-c-che-5j1hbg/devworkspaces --403 - get request

https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/api/namespace/divine-c-che-5j1hbg/dockerconfig --403 - get request

below are the detailed information about the error
```
Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: devworkspaces.workspace.devfile.io is forbidden: User "cdivine304@gmail.com" cannot list resource "devworkspaces" in API group "workspace.devfile.io" in the namespace "divine-c-che-5j1hbg"
```

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/10482177/174317370-63d9a003-a24c-4095-84d6-2ec6990238af.png">

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/10482177/174318050-faa5b0af-0e0b-4e35-9f54-ce9972cc91ae.png">

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/10482177/174333421-f45931cf-f9c8-4bb7-bb5d-2382c8a0b005.png">

i'm also receiving `Unsupported OAuth provider github ` error message from `che` pod in `eclipse-che` namespace
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/10482177/174317535-4f8141b3-2d8a-459d-bdc4-1acb3edf312e.png">

please help me to fix this error

**Comment by Divine1** [comment]
@tolusha  please help me on this

**Comment by Divine1** [comment]
@tolusha please help me on this.

I think i have completed 90%of the eclipse-che setup on k8s platform

**Comment by rakeshreddyrg09** [comment]
facing the same issue 
https://github.com/eclipse-che/che-operator/issues/1405
please help out here.

**Comment by sparkoo** [comment]
can you please check `RoleBindings` in your user's namespace? It should be for user `cdivine304@gmail.com`. If it is for different username (it can be something like `<firstname> <lastname>` or `<gh_username>`), the claim used for username is wrong.

**Comment by Divine1** [comment]
@sparkoo thank you for the response


i have followed the exact details mentioned in [install dex on k8s documentation](https://dexidp.io/docs/kubernetes/) , to setup dex with github connector.

below screenshot shows the namespace that got created in my k8s cluster
![image](https://user-images.githubusercontent.com/10482177/174586988-d66a5e76-b892-4df2-9110-9ca647b7bfef.png)


below screenshot shows `rolebindings` in the user namespace `kubectl get rolebindings -n divine-c-che-5j1hbg`
<img width="878" alt="image" src="https://user-images.githubusercontent.com/10482177/174587627-690fef74-3edd-48c4-b19d-ca3cc58fe50c.png">

`kubectl get rolebindings eclipse-che-cheworkspaces-clusterrole -n divine-c-che-5j1hbg -o yaml`
<img width="847" alt="image" src="https://user-images.githubusercontent.com/10482177/174587865-f510b380-12e4-4eca-9ecf-d3031f4b21ab.png">

`kubectl get rolebindings eclipse-che-cheworkspaces-devworkspace-clusterrole -n divine-c-che-5j1hbg -o yaml`
<img width="935" alt="image" src="https://user-images.githubusercontent.com/10482177/174588026-3ac6dad9-a165-4c51-b511-7bb76b5998be.png">

below screenshot shows my github public profile which i used to login in this scenario
<img width="528" alt="image" src="https://user-images.githubusercontent.com/10482177/174587136-dceca466-127a-4d69-92d3-37d1afdbce5a.png">


below is the configuration i have added in my `kube-apiserver` pod in `kube-system` namespace
![image](https://user-images.githubusercontent.com/10482177/174588413-35df92a2-fa07-451a-9862-7bf16c68f2fb.png)


please help me on this

**Comment by sparkoo** [comment]
yes, you can see that kubernetes is using your `email` claim, but Che is using your username. You need to configure them to be the same so you can configure Che to use `email`:

You need to set `che.oidc.username_claim` to `email`. It can be set by env variable for che-server `CHE_OIDC_USERNAME__CLAIM`. @tolusha can you please help how to set it now with CheCluster v2?

Or you can try to use `--oidc-username-claim=name` as you've suggested. However, I'm not sure if that is all what will be needed.

**Comment by tolusha** [comment]
It is needed to update CheCluster CR in the following way:
```
spec:
  components:
    cheServer:
      extraProperties:
         CHE_OIDC_USERNAME__CLAIM: email
```

**Comment by Divine1** [comment]
> It is needed to update CheCluster CR in the following way:
> 
> ```
> spec:
>   components:
>     cheServer:
>       extraProperties:
>          CHE_OIDC_USERNAME__CLAIM: email
> ```

@tolusha @sparkoo 
i will make this change in my CheCluster CR and share you the feedback.

**Comment by sparkoo** [comment]
I'm wondering why 1st way didn't work. But good that it's working for you now.

**Comment by Divine1** [comment]
thanks a lot @sparkoo @tolusha
