### ISSUE TITLE
http request typeHEAD - `che.xxx.js`, `vendors.xxx.js`, `theia.xxx.js` throws 404 while connecting with `static.developers.redhat.com`

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21479]
### Summary

i'm concerned that i may lose the features exposed via below `js` files, so please let me know if these `js` files are required, if these `js` files are required then please let me know how to fix the `404 error`

Below links throws 404 not found error. 

https://static.developers.redhat.com/che/theia_artifacts/che.825a721c1ce24e797699.js - 404 - HTTPMETHOD - HEAD

https://static.developers.redhat.com/che/theia_artifacts/vendors.aa549792a1f1bc0f26ec.js  - 404 - HTTPMETHOD - HEAD

https://static.developers.redhat.com/che/theia_artifacts/theia.091c4dcf4768874dd20d.js  - 404 - HTTPMETHOD - HEAD

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/10482177/174625038-bec3f304-5a3e-4d9f-8947-d4832ad55704.png">

**Comment by tolusha** [comment]
@azatsarynnyy 
Could you help with this pls?

**Comment by azatsarynnyy** [comment]
It shouldn't affect the functionality of Che-Theia. In case the files can't be fetched from the CDN for any reason, they will be fetched from the Che-Theia server.

It requires checking why the Che-Theia files aren't accessible via CDN.
