### ISSUE TITLE
Stops Helm support for che-server.

### ISSUE THREAD

**Issue by monaka** [eclipse/che#21478]
### Is your enhancement related to a problem? Please describe

It looks Helm support on che-server has been stopped.
I suppose the chart on the master branch won't work as lack of dev-workspace supports.
They now can use chectl and che-operator even if they deploy Che to their vanilla K8s cluster.

### Describe the solution you'd like

git rm -r deploy/kuberenets
git commit -m 'Remove Helm support.'

**Comment by tolusha** [comment]
Yes, we've stopped supported those HelmCharts.
But we introduced HelmCharts for `che-operator` https://github.com/eclipse-che/che-operator/tree/main/helmcharts/next
