### ISSUE TITLE
Unable to create workspace from devfile

### ISSUE THREAD

**Issue by patnan** [eclipse/che#21486]
### Describe the bug

When I try to create a workspace from a devfile in a gitrepo by mporting from git (bitbucket) i get this:

`Failed to resolve a devfile. Failed to request factory resolver: Error occurred during creation a workspace from devfile located at https://bitbucket.org/patnan/open-che-test.git. Cause: Neither of apiVersion or schemaVersion found. This is not a valid devfile.
`

I've tried different devfiles, both my own but also files that work, i.e. a copy of the python workspace, where i just copied the devfile content into my repo.

The devfile is avalable in the repo https://bitbucket.org/patnan/open-che-test.git.

### Che version

other (please specify in additional context)

### Steps to reproduce

In the create workspace tab I use "https://bitbucket.org/patnan/open-che-test"

![image](https://user-images.githubusercontent.com/19404665/174956212-1d4ee2cd-755b-402b-80a0-e1d9868a8b6c.png)

The creation startes but ends with this error:
![image](https://user-images.githubusercontent.com/19404665/174956480-e6c800f1-61a2-4ee4-a913-2bfb457cd969.png)

### Expected behavior

Not to get this error

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/19404665/174951779-4b3556c2-9c2c-4a21-b5fc-75ba028853e6.png)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

The devfile is a copy from a working python workspace.

Regarding versions, see the screenshot.

**Comment by amisevsk** [comment]
Hi @patnan thanks for creating an issue. It looks like bitbucket.org is still not supported for the usual factory flow: https://github.com/eclipse/che/issues/18557

To work around this issue, you can pass the devfile itself from the repo rather than the clone URL, e.g. instead of using
```
https://bitbucket.org/patnan/open-che-test.git
```
you can use the link to the raw devfile.yaml from that repo:
```
https://bitbucket.org/patnan/open-che-test/raw/8db913933e76923f42c068b321277c339059d4b5/devfile.yaml
```
This is not an ideal solution, I know, but should cover most cases. Note that in this case, the devfile should contain a `project` for the repo it belongs to:
```diff
    schemaVersion: 2.1.0
    metadata:
      name: python-hello-world
-     namespace: admin-che <--Remove this namespace, as it's defined by the user you use to create the workspace
    projects:
-     - name: python-hello-world
-       zip:
-         location: 'http://devfile-registry.eclipse-che.svc:8080/resources/v2/python-hello-world.zip'
+     - name: open-che-test
+       git:
+         remotes:
+           origin: "https://bitbucket.org/patnan/open-che-test.git"
    components: []
    commands:
      - exec:
          commandLine: python3 hello-world.py
          component: tools
          group:
            kind: run
          label: Run application
          workingDir: '${PROJECT_SOURCE}'
        id: run-application
```
