### ISSUE TITLE
Eclipse che Dashboard issue (devworkspacetemplates and devworkspace 401)

### ISSUE THREAD

**Issue by rakeshreddyrg09** [eclipse/che#21483]
### Describe the bug

Hi All,
I am installing eclipse che on my k3d k8s cluster using helm chart next version.
Install is Successful and able to hit the dashboard URL, but once the oidc authentication is verified and the callback is also successful but I am getting below error
Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: unauthorized

here is my CheCluster manifest

I am using NFS as my storage class.
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    openShiftoAuth: false
    identityProviderURL: "https://test.eu.auth0.com/"   ##  changed for security reasons
    oAuthClientName: "abc"   ##  changed for security reasons
    oAuthSecret: "xyz"   ##  changed for security reasons
  database:
    chePostgresDb: ""
    chePostgresHostName: ""
    chePostgresPort: ""
    chePostgresSecret: ""
    externalDb: false
  devWorkspace:
    enable: true
  k8s:
    ingressClass: kong  ## changed for security reasons
    ingressDomain: "eclipse-che.test-sample.com"    ##  changed for security reasons
    tlsSecretName: che-tls
  metrics:
    enable: true
  server:
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: "email"
    cheClusterRoles: ""
    tlsSupport: true
    # cheLogLevel: "DEBUG"
    cheWorkspaceClusterRole: ""
    gitSelfSignedCert: false
    nonProxyHosts: ""
    proxyPort: ""
    proxySecret: ""
    proxyURL: ""
    workspaceNamespaceDefault: <username>-che
  storage:
    postgresPVCStorageClassName: "nfs"
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    pvcStrategy: common
    workspacePVCStorageClassName: "nfs"




### Che version

next (development version)

### Steps to reproduce

NA

### Expected behavior

NA

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Screenshots

![che-error](https://user-images.githubusercontent.com/48629246/174765810-d494aa47-93ee-40bd-b5c7-da5a80423fb7.png)
![chedashboard](https://user-images.githubusercontent.com/48629246/174766040-63b3b80a-25ff-466c-a7c1-5a575e76fa22.png)



### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

_No response_

### Additional context

_No response_

**Comment by rakeshreddyrg09** [comment]
@Divine1 please have look

**Comment by Divine1** [comment]
@rakeshreddyrg09 

if you take a look at [this question](https://github.com/eclipse/che/issues/21477#event-6840651386) , you will notice the details that are provided for analysis. could you share those information as well?

**Comment by rakeshreddyrg09** [comment]
![gitWARN](https://user-images.githubusercontent.com/48629246/174775440-d01d3cb8-1914-4db5-989e-78ef2dc893dc.png)
![ns](https://user-images.githubusercontent.com/48629246/174775469-8518b603-ae48-4760-8a74-d063ef2ddc26.png)
![rolebidning](https://user-images.githubusercontent.com/48629246/174775499-896d6cc7-79eb-4776-b28f-7d2228563e1c.png)
![roldeb-oyaml](https://user-images.githubusercontent.com/48629246/174775507-82914d23-2fef-4310-899e-fbb6fde6d112.png)
![clusterrole-0yaml](https://user-images.githubusercontent.com/48629246/174775420-33122e4b-7729-4c52-ba33-e21d1a4e9fa4.png)

**Comment by Divine1** [comment]
@rakeshreddyrg09 

in your Checluster manifest, i can see `apiVersion: org.eclipse.che/v1`. 

The latest version is `apiVersion: org.eclipse.che/v2`

i would suggest you to use the latest version. below fix is applicable for `apiVersion: org.eclipse.che/v2`

in your Checluster manifest, i can see `CHE_OIDC_USERNAME__CLAIM: "email"`

i have detailed the observation on adding `CHE_OIDC_USERNAME__CLAIM: "email"` and how i fixed the issue in below link
https://github.com/eclipse/che/issues/21477

i would suggest you to read through all the details present in [the link ](https://github.com/eclipse/che/issues/21477)

**Comment by rakeshreddyrg09** [comment]
When I apply v2 version facing below issue 

**ERROR	controller-runtime.manager.controller.checluster	Reconciler error	{"reconciler group": "org.eclipse.che", "reconciler kind": "CheCluster", "name": "eclipse-che", "namespace": "eclipse-che", "error": "Get \"https://eclipse-che.sample.com\": dial tcp: lookup eclipse-che.sample.com on 10.43.0.10:53: no such host"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem**


Here the manifest i am using

```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  devEnvironments:
    defaultNamespace:
      template: '<username>-che'
    storage:
      pvcStrategy: 'common'
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email
    database:
      externalDb: false
    metrics:
      enable: true
  networking:
    domain: 'eclipse-che.sample.com'
    tlsSecretName: ''
    auth:
      identityProviderURL: 'https://test.org.auth0.com/'
      oAuthClientName: 'abc'
      oAuthSecret: 'xyz'


Thank you.

**Comment by Divine1** [comment]
@rakeshreddyrg09 i think there are some stale files in the k8s cluster. i'm not really sure about that.

is it possible for you to create a new k8s cluster and install eclipse che version `chectl/0.0.20220613-next.df3ae2c darwin-x64 node-v16.13.2` in the new cluster?

**Comment by azatsarynnyy** [comment]
cc @ibuziuk

**Comment by rakeshreddyrg09** [comment]
In v2 version I am not able to find where to give my ingress class name. Can anyone help me.
Thank you

**Comment by rakeshreddyrg09** [comment]
In values file I am passing below way
```
  networking:
    domain: ""
    annotations:
        kubernetes.io/ingress.class:  "prod-kong-ingress"
    auth:
      identityProviderURL: ""
      oAuthClientName: ""
      oAuthSecret: ""
```

This is the command I am using to install eclipse che
> helm install che --create-namespace --namespace eclipse-che --set networking.domain=eclipse-che.sample.com --set networking.auth.oAuthSecret=abc --set networking.auth.oAuthClientName=xyz  --set networking.auth.identityProviderURL=https://test-org-name.auth0.com/ .

But still its not reflecting in my ingress, due to that load balancer ip is not getting allocated to eclipse-che ingress.
so I did a port forward for now and its loading the dashboard, but facing the same issue 

`Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: unauthorized 401`

**Comment by sparkoo** [comment]
is OIDC server, you're using to authenticate Che, same OIDC as Kubernetes is using?

**Comment by rakeshreddyrg09** [comment]
sorry i didn't understand your question, but my OIDC is hosted in organization level and che  is running on local k8s cluster on my laptop.

**Comment by sparkoo** [comment]
Do you have k8s cluster configured with OIDC Authentication? https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

**Comment by sparkoo** [comment]
yes. Che is using OIDC token to talk with Kubernetes API. So Kubernetes has to be configured with same OIDC to understand the token.

**Comment by sparkoo** [comment]
You can get inspired how we're doing that for minikube in chectl https://github.com/che-incubator/chectl/blob/main/src/tasks/platforms/minikube.ts#L135

**Comment by olexii4** [comment]
@rakeshreddyrg09 Do you still have this '401' problem?

**Comment by rakeshreddyrg09** [comment]
yes

**Comment by timosur** [comment]
I am also experieing the same error. I am using Eclipse Che (latest next version) on AKS with Azure AD enabled. I have configured my CheCluster in the following way:
`components:
    cheServer:
      debug: false
      extraProperties:
        CHE_OIDC_AUTH__SERVER__URL: https://login.microsoftonline.com/[HIDDEN]/v2.0/
        CHE_OIDC_EMAIL__CLAIM: unique_name
        CHE_OIDC_OIDC__PROVIDER: https://login.microsoftonline.com/[HIDDEN]/v2.0/
        CHE_OIDC_USERNAME__CLAIM: unique_name
      logLevel: INFO
    dashboard: {}
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: "5432"
      pvc:
        claimSize: 1Gi
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    defaultNamespace:
      template: <username>-che
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    storage:
      pvcStrategy: common
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
      identityProviderURL: https://login.microsoftonline.com/[HIDDEN]/v2.0/
      identityToken: access_token
      oAuthClientName: [HIDDEN]
      oAuthScope: openid email profile api://[HIDDEN]/user.read
      oAuthSecret: [HIDDEN]
    domain: [HIDDEN]
    tlsSecretName: che-tls`

I have followed the following Tutorial in your Blog:
https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html

But still receiving the error described in this bug.

Anyone can help?
Also happy to contribute, but I have no idea where the bug could be located.

**Comment by timosur** [comment]
I just found the code where it is crashing:
https://github.com/eclipse-che/che-dashboard/blob/f934c42c2cccca7ea5b6d36590032ea0d867a52a/packages/dashboard-backend/src/devworkspace-client/services/api/workspaceApi.ts#L36
Problem seems to be, that the request is being declined by the k8s API server. But I am not able to debug the issue any further as debugging level is not configurable for the Dashboard service.
@olexii4 I saw that you have done a lot of stuff in the Dashboard service. Are you maybe able to assist here?

**Comment by tolusha** [comment]
@timosur 
I am not sure if it is needed to both:

```
CHE_OIDC_EMAIL__CLAIM: unique_name
CHE_OIDC_USERNAME__CLAIM: unique_name
```

**Comment by timosur** [comment]
@tolusha I have also tried to only use CHE_OIDC_EMAIL__CLAIM: unique_name, as described in the Blog (https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html#how-did-we-solve-the-third-challenge)
But without any success.

**Comment by tolusha** [comment]
Pls, remove user's namespace before trying a different configuration, since RoleBindings won't be updated automatically.

**Comment by timosur** [comment]
@tolusha 
I have tried a fresh install with only 
`CHE_OIDC_EMAIL__CLAIM: unique_name`
set.
But still receiving 401 for /devworkspaces and /devworkspacetemplates

**Comment by sreeramu** [comment]
I am also getting 401 error for /dashboard/api/namespace/user1-che/devworkspacetemplates , /dashboard/api/namespace/user1-che/devworkspaces   with minikube setup is anyone is able to get the fix for it.?

**Comment by gustavoromerobenitez** [comment]
The errors persist on version 7.54 deployed on GKE via chectl.

**Comment by timosur** [comment]
@Divine1 @tolusha @sparkoo Any update? 
Problem still blocks us from using Eclipse Che in our Azure AKS RBAC Azure AD joined setup.

**Comment by timosur** [comment]
@Divine1 As we are using AKS I am not able to change stuff in the Api server, so this approach does not work.

**Comment by Divine1** [comment]
> @Divine1 As we are using AKS I am not able to change stuff in the Api server, so this approach does not work.
> 

Could you try editing your apiserver in aks while creating the cluster? 
https://stackoverflow.com/a/60203548/3673073


You should have a dedicated k8s cluster just for eclipse-che. Until your eclipse-che installation in aks cluster is successful, you might have to be ready to delete and create the aks cluster multiple times

**Comment by flavienbwk** [comment]
What are saying your "kube-apiserver" pod logs ?

I'm getting a similar symptom with my kube-apiserver saying "Unable to authenticate the request" err=invalid bearer token".
