### ISSUE TITLE
Support OAuth flow for GitHub Enterprise Server

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21485]
### Is your task related to a problem? Please describe

Currently OAuth flow is supported for GitHub SAAS (github.com and GitHub Enterpise Cloud). We need to add the support for the on-premises version ([GitHub Enterprises Server](https://github.com/organizations/enterprise_plan)).

### Describe the solution you'd like

Add a new or modify the existing GitHub OAuth handler.

### Release Notes Text

Administrators can now configure Che instances to automatically connect to GitHub Enteprise Server to retrieve and configure users personal access tokens. Note the [GitHub Enterprise Cloud](https://github.com/organizations/enterprise_plan) was already supported.

**Comment by vinokurig** [comment]
Didn't mangae to start github enterprise instance localy. Need a remote instance: https://enterprise.github.com/releases/3.5.1/download

**Comment by vinokurig** [comment]
OAuth flow for GitHub hosted version of GitHub enterprise works without any changes. To work on the server version need an instance with the application.

**Comment by l0rd** [comment]
We discussed that today with @benoitf and @ibuziuk. On prem GitHub instances have URLs that don't match [this regexp](https://github.com/eclipse-che/che-server/blob/97b7431bdac856f31ac3059c26d07d5aa16fbd95/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java#L65-L67) (the URL is typically something like `https://github.redhat.com`). To address that we should allow to specify the annotation `che.eclipse.org/scm-server-endpoint` for GitHub as well.

And yes, the problem about how to test it isn't solved.

**Comment by l0rd** [comment]
Using a [Git Provider Access Token](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-provider-access-token_che) may be a workaround.

**Comment by vinokurig** [comment]
@l0rd
> Using a [Git Provider Access Token](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-provider-access-token_che) may be a workaround.

I don't think so. We would still need to an endpoint to test the feature.

**Comment by l0rd** [comment]
> I don't think so. We would still need an endpoint to test the feature.

@vinokurig but with the [PAT secret a user can specifies the `che.eclipse.org/scm-url`](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-provider-access-token_che), why do you think that's not going to work?

**Comment by vinokurig** [comment]
@l0rd You are right that [Git Provider Access Token](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-provider-access-token_che) can be a workaround for a user, but not for us to work on this issue.

**Comment by ibuziuk** [comment]
@vinokurig added this issue to the next sprint as a highly important case to resolve. Just wondering if you have tried - https://docs.github.com/en/get-started/signing-up-for-github/setting-up-a-trial-of-github-enterprise-cloud ? (it has 30 days trial )

**Comment by benoitf** [comment]
and https://docs.github.com/en/get-started/signing-up-for-github/setting-up-a-trial-of-github-enterprise-server is 45 days trial as well

**Comment by vinokurig** [comment]
@ibuziuk
> @vinokurig added this issue to the next sprint as a highly important case to resolve. Just wondering if you have tried - https://docs.github.com/en/get-started/signing-up-for-github/setting-up-a-trial-of-github-enterprise-cloud ? (it has 30 days trial )

The link refers to a cloud version of GitHub enterprise whis is already supported by Che. The issue is to support the server version of GitHub enterprise.

**Comment by vinokurig** [comment]
@benoitf
> and https://docs.github.com/en/get-started/signing-up-for-github/setting-up-a-trial-of-github-enterprise-server is 45 days trial as well

Yes but it requires a spcific environment to setup: https://docs.github.com/en/enterprise-server@3.6/admin/overview/about-github-enterprise-server#supported-environments-for-deployment

**Comment by benoitf** [comment]
@vinokurig you can get credits on Azure as well (trial) to deploy it
https://azure.microsoft.com/en-us/free/

**Comment by vinokurig** [comment]
@benoitf 
> @vinokurig you can get credits on Azure as well (trial) to deploy it
https://azure.microsoft.com/en-us/free/

The free subscription is too weak for the github-server application:
![screenshot-20 100 174 210_8443-2022 08 26-15_54_41](https://user-images.githubusercontent.com/7668752/186908404-b96911b3-4254-4ac2-9f1e-010443987f57.png)

**Comment by benoitf** [comment]
I think you need to use the $ credits, not the free instance

https://docs.gitlab.com/ee/install/azure/ (I know it's gitlab but it shows you how to use free credits $ to setup the machines on azure, gcp or amazon)

**Comment by spuranam** [comment]
@RickJWagner It does not looks like using GHE PAT workaroud described above does not either ... please find the details around our usecase @ https://gist.github.com/spuranam/f47d985ada94a7c0c1ee1c8553579119

**Comment by spuranam** [comment]
@RickJWagner i am testsing with:

OpenShift: v4.11.1
DevSpace: v3.1.0
GitHub Enterpirse: v3.5.3

**Comment by vinokurig** [comment]
@l0rd @RickJWagner @spuranam The PR has been opened, see the link above. Please note that this just extends the current GitHub provider. It means that if the provider is configured to an Enterprise Server endpoint, the Cloud support won't be available, and vice versa.
So do we need a separate OAuth provider to support both versions at the same time?

**Comment by vinokurig** [comment]
@l0rd
> @RickJWagner It does not looks like using GHE PAT workaroud described above does not either ... please find the details around our usecase @ https://gist.github.com/spuranam/f47d985ada94a7c0c1ee1c8553579119

I confirm that the manual PAT flow doesn't work for GitHub Enterprise server case, even with my PR. Do we need to support it?

**Comment by l0rd** [comment]
> t means that if the provider is configured to an Enterprise Server endpoint, the Cloud support won't be available, and vice versa. So do we need a separate OAuth provider to support both versions at the same time?

Supporting only either GitHub enterprise server or `github.com` (but not both at the same time) is an acceptable compromise.

> I confirm that the manual PAT flow doesn't work for GitHub Enterprise server case, even with my PR. Do we need to support it?

We don't need to support it right now.

**Comment by nickboldt** [comment]
Backported to 7.52 / 3.2 in https://github.com/eclipse-che/che-server/commit/b35291d762a3c1386d742dca07494c6e9c4c25e1
