### ISSUE TITLE
http statusCode 500 - Could not add kubeconfig into containers in `user` namespace for dashboardApi

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21480]
### Summary

i have installed `eclipse-che` in k8s platform using `chectl server:deploy`

below are the namespace details in my k8s cluster 
![image](https://user-images.githubusercontent.com/10482177/174638749-0b34416b-a27a-4bc4-b05e-71caf3d40248.png)

below HTTP Post api - throws 500 http status code with message `Could not add kubeconfig into containers in divine-c-che-5j1hbg`
https://eclipseche-dchelladurai-chejune15.calatrava.vmware.com/dashboard/api/namespace/divine-c-che-5j1hbg/devworkspaceId/workspaced8c5d6e306a2448e/kubeconfig

<img width="545" alt="image" src="https://user-images.githubusercontent.com/10482177/174639341-fbe0abde-132f-40b8-9eab-ddf35433afdc.png">

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/10482177/174639011-ee3380b4-b68a-47e5-8df6-f5cf24ed0cb6.png">

Please let me know how to fix this error

**Comment by tolusha** [comment]
@Divine1 
Pls, check Eclipse Che logs for detailed error (probably che-server or dashboard containers)

**Comment by Divine1** [comment]
@tolusha 

below is the` che-dashboard` logs `kubectl logs che-dashboard-76d9859444-z8dt9  -f -n eclipse-che`
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/10482177/174735590-bfd00b9d-ff6b-4abe-a306-7ae23511b589.png">

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/10482177/174736220-60b63347-1b24-42e4-b214-0604aa3dfb7b.png">



there are no error information in `che` logs

**Comment by tolusha** [comment]
@olexii4 
Could you have a look pls?
