### ISSUE TITLE
Search box in Che Docs does not appear to be working

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21498]
### Describe the bug

The search box in the Che documentation page (https://www.eclipse.org/che/docs/stable/overview/introduction-to-eclipse-che/) does not seem to work -- I do not get autocomplete or search results when pressing enter.

Tested in Chromium 100.0.4896.127 and Firefox 101.1

### Che version

next (development version)

### Steps to reproduce

1. Navigate to https://www.eclipse.org/che/docs/stable/overview/introduction-to-eclipse-che/
2. Attempt to search for a term, e.g. devfile

### Expected behavior

Search should work

### Runtime

other (please specify in additional context)

### Screenshots

![che-docs-search](https://user-images.githubusercontent.com/16168279/175667653-7cd4d1a2-6620-4ee9-8261-a00551baad14.gif)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by themr0c** [comment]
Probably related to the che-docs container update.

**Comment by themr0c** [comment]
Cloned in https://issues.redhat.com/browse/RHDEVDOCS-4196

**Comment by themr0c** [comment]
This was caused by an update of the Antora lunr search extension. It doesn't require additional CSS and JavaScript anymore, quite the contrary.

**Comment by themr0c** [comment]
Note that you may need to force-refresh the page in your browser to load the latest version of the `search-ui.js` file.
