### ISSUE TITLE
ssh plugin cannot use private key with passphrase and host name properly

### ISSUE THREAD

**Issue by william-xiang** [eclipse/che#21507]
### Describe the bug

Upload the ssh private with passphrase and specify the host name, the built-in git clone command can be used before restarting the workspace. 
After restarting the workspace, that private key cannot be used by the built-in git clone command anymore, and it shows this error:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/24379419/176013043-5dd40014-8a98-40e5-a16c-6e12c041c505.png">

### Che version

7.49@latest

### Steps to reproduce

Upload the ssh private with passphrase and specify the host name, then restart the workspace. After that use the built-in git clone command to clone a repo using `SSH`. 

### Expected behavior

The git clone command should be able to use the uploaded ssh private key. 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

**Comment by azatsarynnyy** [comment]
@svor @vinokurig can you look at it?
 Probably, it's related to the Git plug-in.

**Comment by vinokurig** [comment]
Managed to reproduce the bug, @svor I think we need to consider adding this issur to a sprint.
