### ISSUE TITLE
Add a VS Code extension to report if the editor is actively used

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21513]
### Is your task related to a problem? Please describe

Che-Theia activity tracker has been implemented as part of https://github.com/eclipse/che/issues/20460
We need to have the same mechanism for Che-code

### Describe the solution you'd like

Adapt Che-Theia activity tracker extension for Che-Code

### Describe alternatives you've considered

The alternative for this would be universal idling, but we want to investigate this approach once we have an activity extension for Che-Code in place - https://github.com/eclipse/che/issues/20345

### Release Notes Text

The Che workspaces VS Code now includes an extension that tracks and report the IDE activity. That can be used by che-machine-exec to automatically stop a workspace for inactivity/run timeout.

**Comment by l0rd** [comment]
@dkwon17 @ibuziuk is that completed or is there something else that we need to wait before closing this issue?

**Comment by dkwon17** [comment]
Oops, forgot to close. This issue is fixed by https://github.com/che-incubator/che-code/pull/65
