### ISSUE TITLE
Error: MiniBrowserEnvironment is not finished initializing

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21519]
### Summary

i'm trying to open a image in preview mode within the theia 
Please let me know how can i open a image with the theia

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/10482177/176374770-73299fe5-4717-4ead-a08b-f583f409a48e.png">

**Comment by benoitf** [comment]
it's a dup of https://github.com/eclipse/che/issues/21510

pending PR: https://github.com/eclipse-che/che-theia/pull/1358
