### ISSUE TITLE
Support OAuth flow for Bitbucket SaaS

### ISSUE THREAD

**Issue by svor** [eclipse/che#21517]
### Is your task related to a problem? Please describe

Che OAuth flow should support Bitbucket SaaS

### Describe the solution you'd like

Need to verify if current OAuth flow provides support for Bitbucket SaaS and implement it if it doesn't.

**Comment by nils-mosbach** [comment]
We're currently having issues with GitLabs token expiration time of 2 hours. Based on the Documentation of BitBucket, tokens might expire after 2 hours as well. See https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/#OAuthonBitbucketCloud-Refreshtokens

I've created an issue for refreshing tokens on GitLab and Bitbucket.
https://github.com/eclipse/che/issues/21291#issuecomment-1196627049 Periodically refresh git OAuth2-tokens for GitLab and Bitbucket (expiration 2h)
