### ISSUE TITLE
dex eclipse che dashboard throws 500 Internal Error on successful login

### ISSUE THREAD

**Issue by prasanthmvp** [eclipse/che#21520]
### Summary

We tried to install eclipse che on minikube and we are facing internal server error on successful login
![222](https://user-images.githubusercontent.com/73928285/176445314-ecea6134-815f-44ed-9a35-68c2a4482d7d.PNG)

**Comment by benoitf** [comment]
@prasanthmvp do you have something in the "More info" toggle ?

also what is your minikube version ?

**Comment by prasanthmvp** [comment]
@benoitf 

![221](https://user-images.githubusercontent.com/73928285/176594547-701996ef-08fe-4aba-a64b-de479af16d14.PNG)
![220](https://user-images.githubusercontent.com/73928285/176594558-6123d583-b0af-430a-b8d4-50d5bf2f30a7.PNG)

Minikube Version: v1.26.0

**Comment by prasanthmvp** [comment]
@benoitf  you could find similar issue on https://github.com/eclipse/che/issues/21125

**Comment by benoitf** [comment]
@prasanthmvp did you try with more memory for your minikube instance ?

Something like

```
minikube start --cpus 4 --memory 8192 --disk-size=50GB
```

(and please delete the minikube instance before starting it as AFAIK it's only at the first start that it provides settings)

**Comment by prasanthmvp** [comment]
@benoitf  Yes we have increased the resources to 12GB and 6 Cores and started but still the same error 500 persists. All others are Running and working Fine.

![IMG_20220630_123726](https://user-images.githubusercontent.com/73928285/176615639-2ea052a6-12b1-4cc5-af6b-0d6cfea35a9d.jpg)

**Comment by debovema** [comment]
Do you have any error in oauth-proxy container in che-gateway pod ?

```
kubectl logs -n eclipse-che -l component=che-gateway -c oauth-proxy
```

**Comment by tolusha** [comment]
It seems like duplicate https://github.com/eclipse/che/issues/21125

**Comment by prasanthmvp** [comment]
@debovema @tolusha We had seen the script and kindly guide how to use it in the following environment.

Minikube Version: v1.26.0
Docker version 20.10.17, build 100c701
OS : AlmaLinux release 9.0 (Emerald Puma)

minikube start --addons=ingress,dashboard --driver=docker --memory=12288 --cpus=6

Due to the *.nip.io restricted in our Network, We modified the /etc/hosts file as follows.,
192.168.49.2  192.168.49.2.nip.io dex.192.168.49.2.nip.io *.192.168.49.2.nip.io

**Comment by ywd1988** [comment]
> 
![image](https://github.com/eclipse/che/assets/92080991/d3bd03de-a7e2-48a6-8bb7-0f519d970fc4)

My problem is the same. How should we solve it

**Comment by ywd1988** [comment]
> che-gateway pod 中的 oauth-proxy 容器是否有任何错误？
> 
> ```
> kubectl logs -n eclipse-che -l component=che-gateway -c oauth-proxy
> ```



> che-gateway pod 中的 oauth-proxy 容器是否有任何错误？
> 
> ```
> kubectl logs -n eclipse-che -l component=che-gateway -c oauth-proxy
> ```

![image](https://github.com/eclipse/che/assets/92080991/dbc8444a-c549-4040-a77f-dba7ca6725e3)
My problem is the same. How should we solve it

**Comment by ywd1988** [comment]
> che-gateway pod 中的 oauth-proxy 容器是否有任何错误？
> 
> ```
> kubectl logs -n eclipse-che -l component=che-gateway -c oauth-proxy
> ```
![image](https://github.com/eclipse/che/assets/92080991/98e4b70d-dfef-4f7b-a424-67dd741ba085)

My problem is the same. How should we solve it
