### ISSUE TITLE
how to update a CA signed(by verified organizations) https certificate in eclipse-che?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21534]
### Summary

i have setup `eclipse-che` on k8s cluster with `dex` as OIDC provider

i'm using below version of `eclipse-che` 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/10482177/177683894-e5bfb40e-6c43-4c3d-a1b2-eb63f7c10119.png">

i used below command to install `eclipse-che`
```
chectl server:deploy --che-operator-cr-patch-yaml=/Users/divine/Documents/office_tasks/TAP-4540/terraformCheJune17/eclipseche_yaml/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=1000000 --domain=eclipseche-dchelladurai-chejune15.calatrava.vmware.com --k8spodreadytimeout=1000000
```

As of now, the domain used for `dex` and `eclipse-che` has Self generated SSL certificates , so i have to view the below `certificate warning` page and then proceed to `eclipse-che`. i should remove this warning by using a CA signed(by verified organizations) SSL certificate for the domains used in `dex` and `eclipse-che`
<img width="702" alt="image" src="https://user-images.githubusercontent.com/10482177/177684321-49e13354-725c-41ac-bf9d-60f2df3fdec8.png">

incase of `dex`, i will be receiving a `private key`, `public key`, `CSR` and i can follow the steps mentioned [here](https://github.com/dexidp/dex/tree/master/examples/k8s) (in dex.yaml) to add a CA signed(by verified organizations) SSL certificate to`dex`

But i'm not sure in which components in `eclipse-che namespace` should i add the CA signed(by verified organizations) SSL certificate  for `eclipse-che` domain. 

Please let me know what steps should be followed to successfully make this change

**Comment by tolusha** [comment]
Certificates to secure Eclipse Che url are store in 2 secrets in `eclipse-che` namespace
- `self-signed-certificate` (CA certificate)
- `che-tls` (server private and public key pair)

To replace them, I suggest the following way
```bash
kubectl scale deploy che-operator --replicas=0 -n eclipse-che

kubectl delete secret self-signed-certificate -n eclipse-che
kubectl delete secret che-tls -n eclipse-che

kubectl create secret generic self-signed-certificate --from-file=ca.crt=ca.crt -n eclipse-che
kubectl label secret self-signed-certificate app.kubernetes.io/part-of=che.eclipse.org -n eclipse-che

kubectl create secret tls che-tls --cert=tls.crt --key=tls.key -n eclipse-che
kubectl label secret che-tls app.kubernetes.io/part-of=che.eclipse.org -n eclipse-che

kubectl scale deploy che-operator --replicas=1 -n eclipse-che
kubectl logs -l app.kubernetes.io/component=che-operator -n eclipse-che -f
```

**Comment by Divine1** [comment]
@tolusha  thank you for this detail. i'm yet to receive a valid certificate, i will share the feedback once i try it out

**Comment by tolusha** [comment]
@Divine1 
Did it solve your issue?

**Comment by Divine1** [comment]
@tolusha 

i have submitted a request to my organization to provide  a verified privatekey,publickey,csr. they haven't got back to me yet.
SO i havenot verified the instructions you have shared. i apologize for this.
