### ISSUE TITLE
VS Code built-in markdown extension doesn't work (requires update)

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21538]
### Describe the bug

If I try to open the markdown preview I get an error:

```
command 'markdown.showPreviewToSide' not found
```

The "Markdown Language" extension (built-in) gets updated automatically after a few seconds and I am able to preview Markdown documents then.

![markdown-vscode](https://user-images.githubusercontent.com/606959/177884285-f5ae8b24-9c32-4c3b-ae6b-1eefd94b2443.gif)

### Che version

next (development version)

### Steps to reproduce

Start a VS Code based workspace and open a Markdown file.

### Expected behavior

The markdown preview should work the first time I open a file.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by azatsarynnyy** [comment]
I can't reproduce this issue anymore on Che-Code `next` image.
I'm able to open the markdown preview in a newly created workspace.

@l0rd if you still can reproduce this issue, could you please share your test project? Maybe it's reproducible with the specific Markdown content only...

**Comment by l0rd** [comment]
Thanks @azatsarynnyy. I cannot reproduce that neither. Closing this issue.
