### ISSUE TITLE
Can we replace postgresDB with someother DB like mysql or sqlserver in Eclipse-che 7.41.2

### ISSUE THREAD

**Issue by gidduhome** [eclipse/che#21536]
### Summary

Hi,

Would it be possible to point eclipse che DB to othe DBs like MySQL instead of postgres?
We are thinking  to do this on 7.41.2 version.
Appreciate your response,

### Relevant information

Would it be possible to point eclipse che DB to othe DBs like MySQL instead of postgres?
We are thinking  to do this on 7.41.2 version.

**Comment by tolusha** [comment]
Hello @gidduhome 

Unfortunately that's not possible.
We have sql scripts heavily tied to PostgreSQL. For instance:
https://github.com/eclipse-che/che-operator/blob/3262a5acc1d79a92d1c7c466d0c5bc4779155977/pkg/deploy/postgres/postgres.go#L172
https://github.com/eclipse-che/che-operator/blob/608bff018771618bef4ff250d1776219c05cede1/pkg/deploy/identity-provider/deployment_keycloak.go#L36

**Comment by ibuziuk** [comment]
Also, please note that we plan to remove the db completely in the upcoming releases
