### ISSUE TITLE
is it possible to authorize only selected users to use `eclipse-che` dashboard website?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21539]
### Summary

i have installed `eclipse-che` in k8s cluster. i have used `dex` as the OIDC provider and i have integrated `dex` with my `organization's gitlab` login.

currently anyusers who has access to the my organization's gitlab login credentials are able to use the `eclipse-che` dashboard webpage after successful authentication/authorization via `dex-gitlab`. 

i dont want to allow access to all the users who has access to myorganization's `gitlab` to use `eclipse-che` dashboard webpage

Please let me know how to restrict/blacklist/whitelist users from using the `eclipse-che` dashboard?

**Comment by tolusha** [comment]
/cc @sparkoo @karatkep
Do you know if it is possible? Have you ever faced such an issue?

**Comment by karatkep** [comment]
I think there is only one way to restrict access to Che - restrict access
to k8s api server for the user...

пт, 8 июл. 2022 г., 11:34 Anatolii Bazko ***@***.***>:

**Comment by Divine1** [comment]
@tolusha @karatkep 

is there any feature that can be used to blacklist/whistelist/restrict access to below `eclipse-che` dashboard page, after successful login via dex ? 
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/10482177/178006247-fcd95c43-01f0-4b8f-a7ac-5c298ec5f1d8.png">

**Comment by sparkoo** [comment]
I don't think there's clean way how to do that. You can maybe update rolebinding in user's namespace, removing permissions to Che resources. But I'm not sure it won't be reconciled back. Also new users will still be able to login to Che. I don't think there was ever such requirement.
