### ISSUE TITLE
Configure the oauth-proxy cookies timeouts

### ISSUE THREAD

**Issue by karatkep** [eclipse/che#21530]
### Is your enhancement related to a problem? Please describe

The purpose of this enhancement is to add ability to configure oauth-proxy cookies timeouts (both `cookie_refresh` and `cookie_expire`) via CheCluster CR. It's not allowed to configure them in current version:
* `cookie_expire` is [hardcoded](https://github.com/eclipse-che/che-operator/blob/c4b34810cff62c82c9d1a0b3098896c31fef58d4/pkg/deploy/gateway/oauth_proxy.go#L115) to `24h`
* `cookie_refresh` is missing; it means default value `0` (aka disabled) is in use

### Describe the solution you'd like

It would be great to reuse `oAuthAccessTokenInactivityTimeoutSeconds` and `oAuthAccessTokenMaxAgeSeconds` properties to manage `cookie_refresh` and `cookie_expire` accordingly. So user will be able to configure them.

### Describe alternatives you've considered

Please feel free to use other (introduce new) properties to manage oauth-proxy cookies timeouts.

**Comment by tolusha** [comment]
@sparkoo What do you think about this?

**Comment by sparkoo** [comment]
It make sense to me, because various cluster configurations might require specific oauth-proxy configuration.
However, we have to be careful here to not spam CheCluster CR with all possible options for all components. I would consider some generic `map[string]string` field, something like `extraProperties` for che-server. For example:

```
oauthProxyExtraProperties:
  cookie_expire: "12h"
```

Code would then add or replace default configuration options.

**Comment by karatkep** [comment]
Hi @sparkoo and @tolusha .
I opened https://github.com/eclipse-che/che-operator/pull/1444 to address this issue. Please review.

NOTE: oauth2-proxy can be configured via [command line options](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options), [environment variables](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#environment-variables) or [config file](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#config-file) (in decreasing order of precedence, i.e. command line options will overwrite environment variables and environment variables will overwrite configuration file settings).

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse-che/che-operator/pull/1468
