### ISSUE TITLE
Simplify Che dashboard user interface

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21546]
### Is your enhancement related to a problem? Please describe

Che dashboard has a lot of redundant information at the moment that does make the user interface quite "advanced" from my point of view.

Specially the sidebar in its current state isn't really necessary. Recent workspaces are part of the workspaces list and the "Create Workspace" Menu option is a button in the workspaces list as well. There was a really benefit as theia was the only editor and was integrated nicely as an iframe. With Che-Code and IntelliJ Editors as an option, navigation items just open new tabs (at least for these two).

![image](https://user-images.githubusercontent.com/15126675/178561824-23673942-6170-4adf-acdd-34246f37d04f.png)

GitPod on the other hand comes with a really simple interface displaying a list of all workspaces and an option that allows starting a new one. Which does exactly the same but looks quite sleek.

![image](https://user-images.githubusercontent.com/15126675/178562626-c2e7a8b1-e999-46c7-9167-f75e4e34c4d9.png)

### Describe the solution you'd like

As for a discussion, I created two mockups based on examples of the patternfly documentation just to give an idea what's in my mind. (Not perfect, since some information is missing, e.g. workspace status or checkboxes, ...)

![image](https://user-images.githubusercontent.com/15126675/178570347-1a23d315-d130-4ef7-a045-e637353efbda.png)

If a user clicks "Add workspace" the new page could be packed in a modal.

![image](https://user-images.githubusercontent.com/15126675/178570427-d3ad340d-15a2-43e5-9f74-96bf9133f87e.png)

Summarized:

* Git-Project could be a link that opens GitHub, etc.
* Remove left navigation menu since information is redundant.
* Add Workspace is a modal

### Additional context

I'm not sure what the future roadmap is. A lot of options got removed from che 6 to devworkspaces. Feel free to share toughts.

**Comment by ibuziuk** [comment]
@beaumorley hi, could you please review the proposal
