### ISSUE TITLE
Rust 'Getting Started' devfile fails to start

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21543]
### Describe the bug

Rust 'Getting Started' devfile fails to start on the dogfooding instance

### Che version

7.50@latest

### Steps to reproduce

1. Open the dashboard
2. Click on the "Rust" devfile
3. ERROR:  Container tools has state CreateContainerError

### Expected behavior

Workspace is started correctly 

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/178500919-9b48b090-4a6f-42c4-83db-0fa670c50fc7.png)

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Reproduced against the dogfooding instance

**Comment by ibuziuk** [comment]
@svor hi, do you happen to know about any recent changes that might cause this issue?

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy folks, could you please take a look?

**Comment by ibuziuk** [comment]
cc: @benoitf

**Comment by svor** [comment]
This problem is not reproducible with more recent version of che-code-devworkspace-handler library. I've updated the version, now devfile registry uses the same version as dashboard.

**Comment by svor** [comment]
It should be good now: https://eclipse-che.github.io/che-devfile-registry/main/devfiles/rust/devworkspace-che-code-insiders.yaml
