### ISSUE TITLE
Cannot deploy with chectl with custom catalog source file

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21542]
### Describe the bug

I am having some problems when trying to follow these steps to deploy Che Operator with `--installer olm`:
https://github.com/eclipse-che/che-operator#deploy-che-operator-with-chectl-using---installer-olm-flag

When providing my own catalog source file to chectl, I get this error:
`chectl server:deploy` fails with this message:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/83611742/178355958-0ead5d95-b578-4c7d-9d4d-438f6e977d97.png">

### Che version

next (development version)

### Steps to reproduce

Run:
```
chectl server:deploy --installer=olm --platform=openshift --catalog-source-yaml ./my_cs.yaml --olm-channel=next --package-manifest-name=eclipse-che-preview-openshift
```
where `my_cs.yaml` is:
```
apiVersion:  operators.coreos.com/v1alpha1
kind:         CatalogSource
metadata:
  name:         eclipse-che-custom-catalog
  namespace:    eclipse-che
spec:
  image:       quay.io/dkwon17/eclipse-che-openshift-opm-catalog:next
  sourceType:  grpc
  updateStrategy:
    registryPoll:
      interval: 5m
```

This seems to because the catalog source is created in the `eclipse-che` namespace instead of the `openshift-operators` namespace, since the `eclipse-che-subscription` subscription has the following conditions (see message with `no operators found from catalog eclipse-che-custom-catalog-source in namespace openshift-operators`):
![image](https://user-images.githubusercontent.com/83611742/178356397-c6ea6bb4-32b7-4eb7-999f-857d76c08bae.png)

But, even if I change my `my_cs.yaml`'s `metadata.namespace` to `openshift-operators`, chectl creates the catalog source in the `eclipse-che` namespace.

## Workaround
When chectl is at the `Wait while subscription is ready` step, manually create the catalog source in the `openshift-operators` namespace. After manually creating the catalog source, chectl should proceed to the next step.

### Expected behavior

Che should be deployed successfully

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

**Comment by tolusha** [comment]
Fix https://github.com/che-incubator/chectl/pull/2177
