### ISSUE TITLE
OIDC configuration for Che 7.41

### ISSUE THREAD

**Issue by MeghanaSrinath** [eclipse/che#21547]
### Describe the bug

I have followed the [documentation ](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/)for installing Che v7.41 on Azure cloud on a AKS cluster. After installation via `chectl`, the che-server pod is not coming up and on inspecting the pod logs, I can see the below error:
```
1) [Guice/ErrorInCustomProvider]: RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://mysubdomain.example.com:5050/auth/.well-known/openid-configuration
  while locating OIDCInfoProvider
  at WsMasterModule.configureMultiUserMode(WsMasterModule.java:398)
  while locating OIDCInfo
  
```
```
$ kubectl get pods -n eclipse-che
NAME                               READY   STATUS             RESTARTS   AGE
che-7c7bf59cf-l6gf2                0/1     Running            2          22m
che-dashboard-5f94c6fc79-s2t4w     1/1     Running            0          22m
che-gateway-6758d74656-zqvf4       3/4     CrashLoopBackOff   9          22m
che-operator-67484df59c-8xzx9      1/1     Running            1          25m
devfile-registry-5756b4d6b-777d7   1/1     Running            0          23m
plugin-registry-6d74cb8bb5-xqc64   1/1     Running            0          22m
postgres-66c99564f5-m9wws          1/1     Running            0          23m

```
My DNS is created as `mysubdomain.example.com`. But I do not see any keycloak/dex related pods in `eclipse-che` namespace. As I understand from the other issues, keycloak should get automatically configured on the cluster with Che v7.41. Please let us know what could be the reason for this error and if we need to setup keycloak manually for this version of Che as well.

### Che version

7.41

### Steps to reproduce

1. Created nginx ingress
2. Created certificate for *.<dominname> using cert-manager
3. Install using chetl command

### Expected behavior

Che should get installed on AKS cluster

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by tolusha** [comment]
@MeghanaSrinath 
I don't see keycloak pod, so I assume that you used the latest chectl version.
What does `chectl version` prints?
Probably you faced auto-update chectl issue, pls use the hint from https://github.com/eclipse/che/issues/18680#issuecomment-749485107

**Comment by MeghanaSrinath** [comment]
Thanks @tolusha , I had  indeed downloaded the latest chectl and that caused this issue. I downloaded v7.41 and evything is working fine now. Thank you.
