### ISSUE TITLE
keycloak integration with new che helm chart

### ISSUE THREAD

**Issue by rakeshreddyrg09** [eclipse/che#21541]
### Summary

Hello team,

Can anyone share the documentation flow for how to set up eclipse-che oidc is configured with keycloak which is installed in same k8s cluster.

this is how currently passing details through values file.
![OIDC-che](https://user-images.githubusercontent.com/48629246/178000338-e7d7d5be-5687-44b9-85c7-b8c0261376c3.png)
![client-test-keycloak](https://user-images.githubusercontent.com/48629246/178000872-c4814ef1-ec24-4dce-99c8-e2214915343a.png)

also i have tried with different keycloak issuer URLs like below
```
http://keycloak-discovery/auth/realms/TEST_DEV/.well-known/openid-configuration
http://keycloak-discovery/auth/realms/TEST_DEV/protocol/openid-connect/token/introspect
```
error in oauth-proxy:
```
[2022/07/08 13:27:12] [options.go:72] Performing OIDC Discovery...
[2022/07/08 13:27:12] [options.go:80] error: failed to discover OIDC configuration: error performing request: Get "http://keycloak-discovery/auth/realms/TEST_DEV/protocol/openid-connect/auth/.well-known/openid-configuration": dial tcp: lookup keycloak-discovery on 10.43.0.10:53: no such host
[2022/07/08 13:27:12] [main.go:54] Get "http://keycloak-discovery/auth/realms/TEST_DEV/protocol/openid-connect/auth/.well-known/openid-configuration": dial tcp: lookup keycloak-discovery on 10.43.0.10:53: no such host
```
FOR ALL THE 3 DIFFERENT URLs i am getting the same error. can anyone help me out what i am missing here.
  
Thank you eclipse-che team.

**Comment by amisevsk** [comment]
Hi @rakeshreddyrg09, thanks for opening an issue. I'm a little confused by the `identityProviderURL` here -- does `http://keycloak-discovery` resolve in your DNS to the keycloak pod in-cluster?

cc: @tolusha you're more familiar with OIDC setup in Che. I'd appreciate your help here if you're available.

**Comment by rakeshreddyrg09** [comment]
hello @amisevsk thank you for reply,
here is my keycloak ingress, other components in my cluster are able to do the OIDC OAUTH successfully. 
![image](https://user-images.githubusercontent.com/48629246/178088419-3231649b-71d7-48a0-bf99-23aa91da893a.png)
i have tried with my other host too but same result. 
![image](https://user-images.githubusercontent.com/48629246/178088502-93a9817a-4f2a-479f-bdb2-58190e7887d9.png)

**Comment by tolusha** [comment]
I think the correct issuer url must be the following:
`https://<KEYCLOAK_ADDR>/realms/<REALM_NAME>`
for instance `https://keycloak.192.168.59.253.nip.io/realms/che`

**Comment by rakeshreddyrg09** [comment]
Hi @tolusha 
I tried the above configuration, but still getting the same error.

**Comment by tolusha** [comment]
I've prepared a draft script how to setup keycloak as OIDC provider on minikube and deploy Eclipse Che.
Could you check if it can shed a light on your problem?

[1] https://gist.github.com/tolusha/345c59eb36a136ffdbce61acbee9c50a

**Comment by rakeshreddyrg09** [comment]
Hi @tolusha, Thank you for your reply.
Actually I am using a k3d cluster.
