### ISSUE TITLE
EclipseChe latest version installation on managed clusters

### ISSUE THREAD

**Issue by MeghanaSrinath** [eclipse/che#21556]
### Summary

I'm trying to install latest stable version of Che on my managed kubernetes cluster (GKE/AKS/EKS). As per the documents and other issues on this repository, I can see that keycloak and all relevant OIDC setup for the k8s cluster is included as part of the installation through chectl for versions <= 7.41. With higher versions of Che, I see that OIDC configuration needs to be manually setup from cluster admin side and dex is given as the identity provider. Though there is an option to add external keycloak, the steps mentioned to integrate are not very clear. Also, for setting up the OIDC endpoint for the clusters, each cloud has its own way. Is there any clear documentation or steps that we can follow to get the latest version of che up and running on a managed cluster with all the OIDC and keycloak configurations done? The installation method upto version 7.41 was very friendly and fast and I'm having multiple blockers in getting the newer versions installed. Any help is appreciated.

**Comment by l0rd** [comment]
@MeghanaSrinath we (Che maintainers) are a small team with limited resources and we do not have access to GKE/AKS/EKS clusters so all our tests happen on Red Hat OpenShift clusters (those include an OAuth service and don't need extra OIDC provider configuration) or minkube (where we automatically install and configure Dex using chectl). 

Recently we got a contribution from @karatkep that has worked on the installation of Che on an AKS cluster ([here is the blog post article he has submitted](https://github.com/eclipse-che/blog/pull/29)) and @tolusha is [working on documenting the steps to configure Che to use and already existing Keycloak instance on minikube](https://github.com/eclipse/che/issues/21541). And you can find more information [in this issue](https://github.com/eclipse/che/issues/21304). Hope that helps.
