### ISSUE TITLE
Error response from daemon: manifest for eclipse/che:latest not found: manifest unknow: manifest unknown

### ISSUE THREAD

**Issue by donhuvy** [eclipse/che#21553]
### Describe the bug

Error response from daemon: manifest for eclipse/che:latest not found: manifest unknow: manifest unknown

### Che version

7.50@latest

### Steps to reproduce

```
docker pull eclipse/che
docker run eclipse/che start
```

```
D:\dockervy\pgadmin>docker run eclipse/che start
Unable to find image 'eclipse/che:latest' locally
docker: Error response from daemon: manifest for eclipse/che:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

D:\dockervy\pgadmin>docker pull eclipse/che
Using default tag: latest
Error response from daemon: manifest for eclipse/che:latest not found: manifest unknown: manifest unknown

D:\dockervy\pgadmin>docker pull eclipse/che:latest
Error response from daemon: manifest for eclipse/che:latest not found: manifest unknown: manifest unknown

D:\dockervy\pgadmin>docker pull eclipse/che
Using default tag: latest
Error response from daemon: manifest for eclipse/che:latest not found: manifest unknown: manifest unknown

D:\dockervy\pgadmin>
```

### Expected behavior

run success

### Runtime

Docker Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/1328316/179343062-023e29d6-2a4f-4999-a5f1-f5916455f1ae.png)

### Installation method

other (please specify in additional context)

### Environment

Windows

**Comment by tolusha** [comment]
Pls use `chectl` [1] to deploy Eclipse Che on k8s instance.
For instance, you can use minikube [2]

[1] https://github.com/che-incubator/chectl/
[2] https://minikube.sigs.k8s.io/docs/start/

**Comment by l0rd** [comment]
@donhuvy you can find instructions to install Che [are here](https://www.eclipse.org/che/docs/stable/administration-guide/installing-che/). 

Closing this issue.
