### ISSUE TITLE
Add an IDE-only workspace sample in the Dashboard getting started (without project)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21554]
### Is your task related to a problem? Please describe

Currently from the UD, it is not possible to start an empty workspace. This story should target the following flow:

- As a user, I create an empty workspace from the dashboard UI
- Workspace is empty and I can clone any repository from the terminal 
- Once the workspace is cloned I can generate a minimal devfile using the dedicated command e.g. "Generate Devfile"
- As I work on the project from the workspace I can update devfile accordingly, e.g. add extra commands and push it to the remote
- Once the changes are pushed I can share the repository with another user that would be able to replicate the same development environment

### Describe the solution you'd like

There should be a dedicated "Blank / Empty / Scratch" devfile or a button "Start from scratch" / "Empty workspace" that would:

1. Create a workspace without any project based on the UDI image
2. Had the command for generating a minimal devfile v2 using the "Generate Devfile" command 

### Release Notes Text

A new example has been added in the Getting Started section of Eclipse Che Dashboard that allows users to start the IDE without any source code project. Git repositories can be opened from the IDE once the workspace is started.

**Comment by l0rd** [comment]
Starting from scratch could also be a good first use case for a [chrome/firefox extension](https://github.com/eclipse/che/issues/11584).

**Comment by ibuziuk** [comment]
@l0rd wdyt if we simply contribute a new empty / scratch devfile to the registry (both che and devfile.io for future) with the following content:

```
schemaVersion: 2.2.0
metadata:
  generateName: scratch
```
 
On the dashboard level we will always display it as the very first one on the Getting Started

**Comment by l0rd** [comment]
We can do that but that would not be in `che-samples` right? Because today all samples in the devfile registry come from the devfiles.yaml in the `che-samples` organization repositories. For this special case I think it makes sense to have the definition in the dashboard or in the devfile registry repositories.

**Comment by ibuziuk** [comment]
> We can do that but that would not be in che-samples right?

 @svor do you happen to know if we can reference the raw definition of the devfile v2 from the registry e.g.

```
---
displayName: Empty Workspace
description: Empty Workspace
tags: ["Community", "Empty"]
icon: /images/empty.svg
links:
  v2: /devfiles/empty.yaml
```

in general, we would really like to avoid embedding the devfile in dashboard as much as possible.

Another idea would be contributing the empty devfile to https://registry.devfile.io/viewer and storing it there. From the dashboard side, we would just get it by name from the devfile.io registry and display it in the first place on "Getting Started". This could be also treated as the first step of switching to devfile.io registry

**Comment by l0rd** [comment]
I would prefer to embed it in the Dashboard to be honest. I don't think that the empty workspace should be managed as a sample. Adding it in the devfile registry is a shortcut that I am afraid will introduce new technical debt as that's an "exceptional" sample. Moreover there is no such a devfile in the devfile.io registry and we need to have a discussion with devfile services, openshift console and odo teams about the value of an empty stack/sample.

**Comment by ibuziuk** [comment]
> I would prefer to embed it in the Dashboard to be honest.

Ok, let's proceed that way for now and embed it in Dashboard

> Moreover there is no such a devfile in the devfile.io registry and we need to have a discussion with devfile services, openshift console, and odo teams about the value of an empty stack/sample.

I opened the PR to start this discussion https://github.com/devfile/registry/pull/118
