### ISSUE TITLE
is it possible to add an extension by adding the extension details in file=.che/che-theia-plugins.yaml?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21565]
### Summary

i have deployed my plugin in https://open-vsx.org/api/harmony/harmony-assist/0.0.1/file/harmony.harmony-assist-0.0.1.vsix

i have to use this plugin in `che-theia` ide opened via workspace using `eclipse-che dashboard`. 
i noticed 3 requests triggering from `eclipse-che` dashboard (as shown in below screenshot) 
```
https://github.com/Divine1/demochenodejs.git&file=.vscode/extensions.json
https://github.com/Divine1/demochenodejs.git&file=.che/che-theia-plugins.yaml
https://github.com/Divine1/demochenodejs.git&file=.che/che-editor.yaml
```

is it possible to allow my plugin to be installed  by specifying  the plugin details in `.che/che-theia-plugins.yaml` in my gitrepo ? if yes, could you please share me the details on how to do it?

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/10482177/179898744-8f6f902f-7d60-4132-a142-f6c3ab15c1de.png">

in this [doclink](https://www.eclipse.org/che/docs/stable/end-user-guide/adding-a-vscode-extension/#_inlining_cheche_theia_plugins_yaml_file) below detail is mentioned , its mentioned that "i can add/update new files/folders in my git repo. so please help me on what details i have to add in `.che/che-theia-plugins.yaml`

<img width="724" alt="image" src="https://user-images.githubusercontent.com/10482177/179906901-a8af2fbf-cedb-435b-85ba-c06dcf20e50b.png">

	
i have also received a solution to install extension in `che-theia` ide from @svor  https://mattermost.eclipse.org/eclipse/pl/e87z5uk69bfu8kk34ndt4rcz4e , i'm yet to test it as i ran into [another issue with starting the workspace](https://github.com/eclipse/che/issues/21558)

**Comment by Divine1** [comment]
@svor 

thank you for the response.
my plugin is published at https://open-vsx.org/api/harmony/harmony-assist/0.0.1/file/harmony.harmony-assist-0.0.1.vsix

below doc shows id `- id: redhat/java/latest`.
Where can i find the `id` for my plugin? 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/10482177/179927136-3191b82c-4700-408f-9953-1fc7b44126a4.png">

**Comment by svor** [comment]
id=publisher/name/version

if you use Che-Theia editor, your plugin should be in the che plugin registry as well. Then in the .che/che-theia-plugins.yaml you have to add:
`- id: harmony/harmony-assist/latest`
or you can add it into the .vscode/extensions.json file like:
```
  {
    "recommendations": [
      "harmony.harmony-assist"
    ]
  }
```

**Comment by Divine1** [comment]
facing issue while installing plugin in che-theia editor. below ticket has details of the issue

https://github.com/eclipse/che/issues/21585
