### ISSUE TITLE
Can not start a workspace with `&storageType=ephemeral ` attribute 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21569]
### Describe the bug

![image](https://user-images.githubusercontent.com/1461122/179981778-d15d2c88-7c2e-4067-af9f-b037b3105cea.png)

### Che version

7.50@latest

### Steps to reproduce

Reproducer - [https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com#https://github.com/che-incubator/quarkus-api-example&storageType=ephemeral](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/che-incubator/quarkus-api-example&storageType=ephemeral)

### Expected behavior

Epemeral workspace is started

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

**Comment by l0rd** [comment]
This is great. Thank you @olexii4 for fixing it but I am reopening the issue because if we don't document that https://www.eclipse.org/che/docs/stable/end-user-guide/optional-parameters-for-the-urls-for-starting-a-new-workspace/ nobody will be able to use it.

**Comment by ibuziuk** [comment]
Marking this issue as a blocker for 3.2 DevSpaces release, so we need to backport all the fixes in 7.52.x if needed

**Comment by ibuziuk** [comment]
Temporary removed the ephemeral attribute from the getting started samples - https://github.com/eclipse-che/che-website/pull/68

**Comment by ibuziuk** [comment]
Opened a separate issue for getting started samples - https://github.com/eclipse/che/issues/21655

**Comment by max-cx** [comment]
Merged https://github.com/eclipse-che/che-docs/pull/2462 into `main` and cherry-picked into `7.52.x` and `7.53.x`.
Closing this issue as requested by Ilya.
