### ISSUE TITLE
`che-editor` URL parameter should have higher priority than `.che/che-editor.yaml`

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21563]
### Describe the bug

If I specify [`che-editor` URL parameter ](https://www.eclipse.org/che/docs/stable/end-user-guide/optional-parameters-for-the-urls-for-starting-a-new-workspace/#_url_parameter_for_the_workspace_ide) I expect it to have higher priority compared to the editor specified in the git repository `.che/che-editor.yaml`.

### Che version

next (development version)

### Steps to reproduce

Start a workspace specifying the `che-editor` URL parameter using a git repository that contains a `.che/che-editor.yaml`.

For example, using the dogfooding Che instance, a repository that has a `.che/che-editor.yaml` where che-code is specified and the parameter `che-editor=eclipse/che-theia/next`:

`https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/tilt-example-java/?che-editor=eclipse/che-theia/next` 

### Expected behavior

The editor specified in the URL parameter should be used, not the one in the `.che/che-editor.yaml` file.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Amazon

**Comment by azatsarynnyy** [comment]
I've tried the provided factory link
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/tilt-example-java/?che-editor=eclipse/che-theia/next. For me, it spinned up a Che-Theia-based workspace.
At first sight, it looks like expected behavior. But actually, it works like that because the content of the `.che/che-editor.yaml` file is ignored. I've described that problem in https://github.com/eclipse/che/issues/21639

**Comment by ibuziuk** [comment]
@akurinnoy reopened for verification, the expected priority
- URL parameter
- .che/che-editor.yaml
- CR property

**Comment by dipakkarde** [comment]
Hello Team,
![defaultEditor](https://user-images.githubusercontent.com/88081595/216635717-d280a753-c0f3-4d97-a41d-8e4d5931e3eb.png)
![che-editor-yaml](https://user-images.githubusercontent.com/88081595/216635731-6d773df6-3c74-4504-9e59-9324bddb7b8c.png)
![my-project-devfile](https://user-images.githubusercontent.com/88081595/216635737-83a48f0f-eee7-4d19-acfa-7978004ed376.png)
![myproject-workspace](https://user-images.githubusercontent.com/88081595/216635745-13f5a6d7-0a4f-49d8-8b45-02c4bb2a2058.png)
![my-project](https://user-images.githubusercontent.com/88081595/216635749-6d0369df-3cb3-44ee-bb3f-3cd5db2d5a29.png)

I tried to reproduce this issue with below steps :

**Step 1]** Set the `defaultEditor` to theia in checluster CR and was able to create a workspace with theia IDE by default :

`defaultEditor: eclipse/che-theia/latest `
 

**Step 2]** Then created a repo with `".che/che-editor.yaml"` and set :

`id: che-incubator/che-code/insiders`

Workspaces gets created with VScode IDE by default.

So found that option `".che/che-editor.yaml"` has higher priority than setting `"defaultEditor"` parameter in checluster CR

**Step 3]** To check the priority of option "URL parameter for the workspace IDE" followed below steps :

- Set `defaultEditor` to theia in checluster CR
- Set `".che/che-editor.yaml"` to eclipse/che-theia/latest 
- Next tried to start workspace as per the below format : 

`https://devspaces-&lt;openshift_deployment_name&gt;.&lt;domain_name&gt;"#<git_repository_url>?che-editor=<editor_key>`

Trying with URL paratmeter : `che-editor=<editor_key>:`

`https://devspaces.apps.raunakbocp4.india.aws.cee.support#https://github.com/dipakkarde/che-demo?che-editor=che-incubator/che-code/insiders`

But I found that workspace is getting created with "Theia" IDE only.

Further I also tried setting `"defaultEditor"` to VScode in checluster CR, But still workspace gets created with Theia IDE only.

So found `".che/che-editor.yaml"` only having higher priority than other two options.

Attaching here some screenshots for reference. Let me know if any details required.

Let me know if in case I am missing anything.

**Comment by ibuziuk** [comment]
need to make sure that we backport the fix to 7.60.x so that it would land in 3.5
