### ISSUE TITLE
[Che-code] Extensions panel load is failing in the dogfooding instanse

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21576]
### Describe the bug

Extensions list can't be loaded in the extension panel:
![ezgif-4-045583b964](https://user-images.githubusercontent.com/7668752/180388230-569e0626-d9d4-4614-888b-7352e2af4e2a.gif)
an error appeares:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 07 22-09_29_07](https://user-images.githubusercontent.com/7668752/180388293-4420096a-d424-4c16-abe8-1784bc53afce.png)

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace.
2. Go to the Extensions panel.
3. Type something e.g. github in the extensions search.

See: The panel doesn't respond. 

### Expected behavior

Extensions panel must show the extensions list.

### Runtime

OpenShift

### Installation method

OperatorHub, other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
looks like fixed - https://github.com/eclipse/openvsx/issues/497
closing
