### ISSUE TITLE
Che installation with domain created in cross clouds

### ISSUE THREAD

**Issue by MeghanaSrinath** [eclipse/che#21580]
### Summary

I have been referring to [this](eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/) guide for installing Che v7.41 on an AKS cluster. As per this, we need to create DNS in Azure and provide DNS zone access to the service principal that is being used. Similarly, there are requirements to provide access to Route53(AWS) and to DNS zones(GCP). In case I want to install che on cloud, is there a pre-requisite that the domains have to be created in the particular cloud chosen? For example, is it possible to have Che installed in Azure and domain configured in other clouds like GCP or AWS?

**Comment by ibuziuk** [comment]
Just today we got the blog published from the community about installing Eclipse Che on AKS 
 that should be very helpful for installation - https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html

I'm not aware of the particular requirement for domains, so technically it should work cc: 
@karatkep maybe you have some input on that matter? Thanks
