### ISSUE TITLE
Happy Path tests for che-plugin-registry do not work, as `chectl` no longer supports `workspace:create`

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21591]
### Describe the bug

Alpine based HP tests for che plugin registry PRs are failing because `chectl workspace:create` is an invalid command.

For example: https://github.com/eclipse-che/che-plugin-registry/pull/1353

![image](https://user-images.githubusercontent.com/227597/181276707-a194849c-72c2-49ba-a247-75bd976f77c8.png)

Digging into the GH action, I see: 

```
DevFile Path selected to /home/runner/work/che-plugin-registry/che-plugin-registry/che/tests/e2e/files/happy-path/happy-path-workspace.yaml
stack=Error: Command failed with exit code 2: chectl workspace:create --start --devfile=/home/runner/work/che-plugin-registry/che-plugin-registry/che/tests/e2e/files/happy-path/happy-path-workspace.yaml
 ›   Error: command workspace:create not found
    at makeError (/home/runner/work/_actions/che-incubator/happy-path-tests-action/next/lib/index.js:146111:11)
    at handlePromise (/home/runner/work/_actions/che-incubator/happy-path-tests-action/next/lib/index.js:145860:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Unable to start Error: Command failed with exit code 2: chectl workspace:create --start --devfile=/home/runner/work/che-plugin-registry/che-plugin-registry/che/tests/e2e/files/happy-path/happy-path-workspace.yaml
```

### Che version

next (development version)

### Steps to reproduce

1. Submit a PR.
2. watch as it fails the `Happy Path` pull_request and push tests
3. look at https://github.com/eclipse-che/che-plugin-registry/actions/workflows/happy-path.yaml ?

### Expected behavior

Tests should be rewritten to use oc or kubectl commands for starting a workspace. Or hell, just curl the factory URL ? 

### Runtime

other (please specify in additional context)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by benoitf** [comment]
dup of https://github.com/eclipse/che/issues/20986
