### ISSUE TITLE
Add new fields in CheCluster CR to configure VS Code marketplace

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21598]
### Is your enhancement related to a problem? Please describe

Currently che is using https://open-vsx.org but as for Airgapped mode, offline, etc we have a way to use OpenVSX instance embedded in the plug-in registry.

Then Admin should be able to configure the registry to use

so , che-code is able to get the value and see if it configures the registry to open-vsx.org or a corporate OpenVSX or something else

Part of https://github.com/eclipse/che/issues/20549

### Describe the solution you'd like

```diff
spec:
   components:
     devWorkspace
     cheServer
     pluginRegistry:
       deployment
       disableInternalRegistry
       externalPluginRegistries
+      OpenVSXURL: https://openvsx.org # If not set use the embedded one
     devfileRegistry
     database
     dashboard
     imagePuller
     metrics
   containerRegistry
   gitServices
   devEnvironments
   networking
```

### Describe alternatives you've considered

any change/suggestion is welcomed

we only need to know when cheCode is booting the URL to use to fetch the VSIX files :-)

**Comment by benoitf** [comment]
cc @l0rd you can specify the CR fields that you would like

**Comment by l0rd** [comment]
```diff
spec:
   components:
     devWorkspace
     cheServer
     pluginRegistry:
       deployment
       disableInternalRegistry
       externalPluginRegistries
+      externalOpenVSXRegistryURL: https://openvsx.org # If not set use the embedded one
     devfileRegistry
     database
     dashboard
     imagePuller
     metrics
   containerRegistry
   gitServices
   devEnvironments
   networking
```

**Comment by tolusha** [comment]
Do we need to put `https://openvsx.org` as a default value in `externalOpenVSXRegistryURL` field?
Or maybe left as empty?

**Comment by benoitf** [comment]
from what I understand, it should be empty by default (then it'll use the one from plugin registry)

**Comment by l0rd** [comment]
Yes, if the field is missing or left empty we should use the openvsx embedded in the plug-in registry.

**Comment by tolusha** [comment]
I suggest to use list of urls in configuring open VSC registries.
Does it make sense?

```go

	// External open VSC registries.
	// +optional
	ExternalOpenVSXRegistries []ExternalOpenVSXRegistries `json:"externalOpenVSXRegistries,omitempty"`

type ExternalOpenVSXRegistries struct {
	Url string `json:"url,omitempty"`
}

```

**Comment by l0rd** [comment]
Something that becomes critical is providing to customers an easy way to customize and update the embedded openvsx registry:

How do I add or remove a vsx?
How do I update the embedded vsxs to the latest version?

**Comment by benoitf** [comment]
@tolusha about the list, VS Code is only working with one registry for now (and since the beginning) so I'm not sure a list will work there (or it will always be a list of zero or one)

**Comment by l0rd** [comment]
After discussing with @benoitf we concluded that the simpler is to just have:

```diff
spec:
   components:
     devWorkspace
     cheServer
     pluginRegistry:
       deployment
       disableInternalRegistry
       externalPluginRegistries
+      openVSXRegistryURL: https://openvsx.org/ # If not set or empty use the URL of the one embedded with the plugin reg
     devfileRegistry
     database
     dashboard
     imagePuller
     metrics
   containerRegistry
   gitServices
   devEnvironments
   networking
```

**Comment by tolusha** [comment]
https://github.com/eclipse-che/che-operator/pull/1466
