### ISSUE TITLE
Add "Git Services" tab to the User Preferences

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21595]
### Is your task related to a problem? Please describe

![image](https://user-images.githubusercontent.com/1461122/181503850-9950ace9-fc96-4d21-ad4d-9f2c0087753c.png)

Currently, the account page is outdated and fetches the user information from db that is planned to be removed as part of  https://github.com/eclipse/che/issues/21374

The data provided on the Account page is irrelevant and should be removed

### Describe the solution you'd like

As part of this issue, we should only have the  login / logout buttons to the main Git providers GitHub, Gitlab, and Bitbucketlogin/logout

Sub-tasks

- [ ] remove dependecy on /user and /profile API (display only username from k8s as the first step)
    - [ ] hide 'Account' view 
- [ ] 

### Describe alternatives you've considered

Potentially we should remove Account page completely and add Git Services Tab to the User Preferences:

![image](https://user-images.githubusercontent.com/1461122/181508416-0f79da2f-c4f0-4950-983c-362e78038f2e.png)

### Additional context

The information about the configuration of the particular Git provider should be fetched from the Eclipse Che CR - https://github.com/eclipse/che/issues/21577

The issue is part of the Git Zero Config epic - https://github.com/eclipse/che/issues/20583

Open Questions:
- login / logout URLs should be provided by the Che CR
- how should we track the login / logout state for a particular user

### Release Notes Text

Eclipse Che User Preferences page includes a new tab: "Git Services" (before, the only tab was "Container Registries"). This tab shows the list of git services the user has granted access to. User can revoke access to any of the git services from this tab. Supported services are GitHub (github.com or Enterprise), GitLab (SaaS and Server) or Bitbucket (Cloud and Server).

**Comment by ibuziuk** [comment]
As the first step, it would be great to remove the dependency on the server /user API

![image](https://user-images.githubusercontent.com/1461122/196374564-c2e64218-c5b9-4f23-9977-bdb3d70c1b90.png)

**Comment by ibuziuk** [comment]
@l0rd @akurinnoy @olexii4 please, find the proposed UX for Git Services
![image](https://user-images.githubusercontent.com/1461122/201940599-77905574-ad7a-4f86-9640-5cb3e80aa867.png)

![Git Services](https://user-images.githubusercontent.com/1461122/201947197-2dfc3e77-bdaf-4783-83e8-a66f93628a0e.png)

Basically, the idea is that a particular icon is shown only if the admin configured the git service on the CR level accordingly - https://github.com/eclipse/che/issues/21577 

The only possible options would be login / logout

**Comment by l0rd** [comment]
When implementing this we should address the bug described [in this Dev Spaces issue](https://issues.redhat.com/browse/CRW-3505) too.

**Comment by nickboldt** [comment]
add a comment to reset timestamp so a fresh comment should appear

**Comment by nickboldt** [comment]
comment
