### ISSUE TITLE
Provides OpenVSX CheCluster URL to user containers

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21600]
### Is your task related to a problem? Please describe

Part of https://github.com/eclipse/che/issues/20549
Plugin-Registry will include an OpenVSX instance.
Admin will have a choice to say to either use 'OpenVSX.org' or 'plugin-registry OpenVSX' with the CheCluster https://github.com/eclipse/che/issues/21598

And then, CheCode(our VS Code) needs to know when booting if registry needs to be OpenVSX.org or another URL
https://github.com/che-incubator/che-code/pull/85

But to know what to do, CheCode needs to get the value specified in the CheCluster CR but a user container has no access to the CheCluster object, so it's the Dashboard that needs to propagate this information 

### Describe the solution you'd like

depends on https://github.com/eclipse/che/issues/21598
Adds `OPENVSX_URL` with value coming from  `components.devWorkspace.cheServer.pluginRegistry.OpenVSXURL`

**Comment by l0rd** [comment]
I would use `OPENVSX_REGISTRY_URL` as the name of the env variable. Added the comment to the [CheCluster issue too](https://github.com/eclipse/che/issues/21598#issuecomment-1202249028).
