### ISSUE TITLE
Handle idling in VS Code correctly instead of attempting to reconnect in x seconds

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21610]
### Is your enhancement related to a problem? Please describe

Today if a VS Code workspace is idled the users sees a connection error with a timer that tries to reconnect every x seconds.

![image](https://user-images.githubusercontent.com/606959/182848826-2ac89fc6-31e0-4c14-ac54-aa8955d96356.png)

It's only after refreshing the web page that the user gets redirected to the page that informs about what happened:

![image](https://user-images.githubusercontent.com/83611742/176222545-4b4e4e9e-9e58-4c4e-903c-2446fe545a6c.png)

### Describe the solution you'd like

VS Code should able to detect that the workspace has been idled and should prompt the user:

![your-dev-env-has-been-stopped](https://user-images.githubusercontent.com/606959/182850971-e9ad8cb1-c518-41c6-a327-3fa08343dec4.png)

Note that the workspace can be stopped for multiple reason and we should show a different message each time: https://github.com/eclipse-che/che-dashboard/pull/595

### Additional Context

This is a follow up of https://github.com/eclipse/che/issues/20599 and the important PRs provided by @dkwon17

### Release Notes Text

**Title** VS Code notification to inform a developer that his workspace has been stopped and why
When a workspace is stopped (voluntary or not) the user is informed with an explanation of the cause (inactivity, run timeout, error, stopped). The user is also prompted to restart the workspace or to go back to the dashboard.

**Comment by l0rd** [comment]
cc @ibuziuk @dkwon17 @azatsarynnyy

**Comment by RomanNikitenko** [comment]
The PR is ready for review: https://github.com/che-incubator/che-code/pull/163

**Comment by azatsarynnyy** [comment]
From https://github.com/eclipse/che/issues/22287, it seems became relevant again.
