### ISSUE TITLE
Update to newer `RELATED_IMAGE_gateway_authentication_sidecar` and `RELATED_IMAGE_gateway_authorization_sidecar` images in CSV?

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21617]
### Is your task related to a problem? Please describe

I noticed today that in Che-operator main branch, we still use:

```
- name: RELATED_IMAGE_gateway_authentication_sidecar
  value: quay.io/openshift/origin-oauth-proxy:4.7
- name: RELATED_IMAGE_gateway_authorization_sidecar
  value: quay.io/openshift/origin-kube-rbac-proxy:4.7
```
-- ./config/manager/manager.yaml
-- ./bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
-- ./deploy/deployment/openshift/combined.yaml
-- ./deploy/deployment/openshift/objects/che-operator.Deployment.yaml
(plus the helmcharts and k8s files too)

While downstream we have: 

```
- name: RELATED_IMAGE_gateway_authentication_sidecar
  value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.8
- name: RELATED_IMAGE_gateway_authorization_sidecar
  value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8
```
-- ./manifests/devspaces.csv.yaml

### Describe the solution you'd like

Given that Openshift v4.10 is out, and it's a prereq for using Dev Spaces, and that Openshift v4.11 is out soon, should we update to v4.11 when it's live? 

### Describe alternatives you've considered

Or is there some reason we're still on 4.7/4.8?

**Comment by tolusha** [comment]
I don't think we can use `registry.redhat.io/openshift4` registry in upstream.
But we can switch to `4.8` or even `4.9` in `quay.io/openshift`

@amisevsk @sparkoo 
Do you think it is safe enough to switch to a higher version? Any specific tests?

**Comment by tolusha** [comment]
So, we have to do:
1. Update [1] to [2] & [3]
2. Launch `make update-dev-resources` to propagate these changes to all related resources including olm bundle
3. Spin up OpenShift cluster and launch `make run` to deploy Eclipse Che
4. Test if use can log in and create workspace

[1] https://github.com/eclipse-che/che-operator/blob/152c8211a673348ebc60aa260e2fb6eecaeff81b/config/manager/manager.yaml#L84-L87
[2] https://quay.io/repository/openshift/origin-oauth-proxy?tab=tags&tag=4.9
[3] https://quay.io/repository/openshift/origin-kube-rbac-proxy?tab=tags&tag=4.9
