### ISSUE TITLE
the API version in the data (org.eclipse.che/v2chect) does not match the expected API version (org.eclipse.che/v2)

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21612]
### Summary

i updated my chectl to `chectl/0.0.20220801-next.24265f6 darwin-x64 node-v16.13.2`
i deleted the setup `chectl server:delete`

then i created using below command
```
chectl server:deploy --che-operator-cr-patch-yaml=/Users/divine/Documents/office_tasks/TAP-4540/terraformCheJune17/eclipseche_yaml/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=1500000 --domain=eclipseche-dchelladurai-chejune15.calatrava.vmware.com --k8spodreadytimeout=1500000
```

i receive below error `the API version in the data (org.eclipse.che/v2chect) does not match the expected API version`.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/10482177/182996647-79804249-fd3b-41c2-9f8d-0079373d3c3d.png">

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/10482177/182999282-9f27ae7d-131f-4faa-b9cb-8a4712ce6f4c.png">

below is my kubectl version
<img width="975" alt="image" src="https://user-images.githubusercontent.com/10482177/182996761-44e6bba2-77a8-4481-a23d-5ace07716c07.png">

the setup worked fine until the previous version of chectl. 
please let me know how can i fix this issue.

**Comment by tolusha** [comment]
@Divine1 
Pls, check you patch file `che-operator-cr-patch.yaml`
Any occurrence of `v2chect` string?

**Comment by Divine1** [comment]
@tolusha  yes, its a mistake from my end. thank you for looking into this.
this is fixed.
