### ISSUE TITLE
The default VSX registry should be openvsx.org

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21637]
### Is your enhancement related to a problem? Please describe

We [are about to embed an OpenVSX registry in Che plugin registry](https://github.com/eclipse-che/che-plugin-registry/pull/1324) but that hasn't be tested thoroughly yet and we still want to use `openvsx.org` as the default registry to retrieve VS Code extensions. 

### Describe the solution you'd like

When installing Che (via OLM or yaml manifests), the default CheCluster should have `pluginRegistry.openVSXURL` set to [https://openvsx.org](https://openvsx.org).
 
When updating Che v7.51 or earlier, if `pluginRegistry.openVSXURL` is NOT set then we should set it to [https://openvsx.org](https://openvsx.org).

When updating Che v7.52 or later, if `pluginRegistry.openVSXURL` is NOT set then we should not modify it.

### Additional context

We introduced the `pluginRegistry.openVSXURL` with this [PR](https://github.com/eclipse-che/che-operator/pull/1466) but that field is empty by default (meaning that the embedded registry will be used). 

OpenVSX is [greedy in terms of memory requirements](https://github.com/eclipse/che/issues/21620).

**Comment by svor** [comment]
> When updating Che v7.52 or later, if pluginRegistry.openVSXURL is NOT set then we should not modify it.

@l0rd @tolusha it means that updated Che v7.53 will have empty value of `openVSXURL` and will use the embedded registry. It changes the previous state that was in v7.52 were we use online registry.

maybe we should: 
When updating Che **v7.52** or earlier, if pluginRegistry.openVSXURL is NOT set then we should set it to https://openvsx.org/.
When update Che **v7.53** or later, if pluginRegistry.openVSXURL is NOT set then we should not modify it.
