### ISSUE TITLE
Container tools has state ImagePullBackOff [Windows 10, Hyper-V, Minikube]

### ISSUE THREAD

**Issue by filipthoen2** [eclipse/che#21636]
### Describe the bug

I successfully deployed Che on Minikube (after some initial hickups with insufficient CPU resources assigned to the Minikube cluster, see https://github.com/eclipse/che/issues/21633)

The Che dashboard now comes up & I can deploy workspaces.

I tried both 'cpp', 'bash' & 'apache-camel-c', all fail with the same error:

  _Container tools has state ImagePullBackOff_

See attached screenshot. Looks like this has to do with K8s not being able to download one or more of the required container images.

I've attached the Che logs, which don't show an error except for the 'che-operator' pod:

```
> 2022-08-15T17:44:22.893Z ERROR controller-runtime.manager.controller.devworkspacerouting Reconciler error {"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouti
> [eclipse-c](https://github.com/eclipse/che/files/9339055/eclipse-che.zip)
> ng", "name": "routing-workspace49a70a39f20c4107", "namespace": "admin-che", "error": "Operation cannot be fulfilled on devworkspaceroutings.controller.devfile.io "routing-workspace49a70a39f20c4107": the object has been modified; please apply your changes to the latest version and try again"}
> 
```

Not sure how to resolve this (checked the Che support), and whether this is the culprit.

I clicked on the 'Devfile' tab in the failed workspace in the Che Dashboard, and for instance for 'bash' workspace, I see the following 'project' mentioned:

```
_projects:

name: bash
zip:
location: 'http://devfile-registry.eclipse-che.svc:8080/resources/v2/bash.zip'_

```
When I try 'curl http://devfile-registry.eclipse-che.svc:8080/resources/v2/bash.zip' I get:

   Trying 23.217.138.110:8080...

and curl times out. Using 'http://devfile-registry.eclipse-che.svc/' instead of 'http://devfile-registry.eclipse-che.svc:8080/' in curl works fine.

So is this an error in devfile specification?

Thanks!

Filip

[eclipse-che.zip](https://github.com/eclipse/che/files/9348618/eclipse-che.zip)

![Che error -  ImagePullBackOff](https://user-images.githubusercontent.com/36936974/184819614-8264e68f-b3fd-4486-93e1-352bbd46c37d.PNG)

### Che version

7.51@latest

### Steps to reproduce

**Versions**

- Windows 10 Enterprise
- Machine: Intel x86, 16 GB RAM
- Hyper-V
- Kubectl: Client Version: v1.24.0
- Kustomize Version: v4.5.4
- Server Version: v1.24.3
- Minikube: minikube version: v1.26.1 commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
- Chectl: chectl/7.52.0 win32-x6
- Che: v7.52.0 (latest

### Expected behavior

I expected the 'bash' workspace to be created successfully.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Windows

**Comment by tolusha** [comment]
I faced the same issue. It seems image is failed to pull because it quite large.
I've tried to reconfigure minikube cluster to increase timeout, but without success:

`minikube start --extra-config=kubelet.runtime-request-timeout=20m0s`

As workaround we can prepull image locally and copy to a minikube cluster

```bash
docker pull quay.io/devfile/universal-developer-image:ubi8-0e189d9
docker save "quay.io/devfile/universal-developer-image:ubi8-0e189d9" > universal-developer-image.tar
eval $(minikube docker-env) && docker load -i  universal-developer-image.tar
```

**Comment by filipthoen2** [comment]
@tolusha thanks for the help! I also tried to reconfigure minikube to increase timeout, but no success either.

I'm not using Docker but Hyper-V (don't have a docker subscription) so I can't use the 'docker pull' workaround... Is there an equivalent for Hyper-V?

Thanks again,
Filip

**Comment by tolusha** [comment]
Can you use `podman` ?

**Comment by tolusha** [comment]
It seems there is an issue with an underlying kubernetes version.
I fixed the problem by creating a minikube cluster with the additional option `--kubernetes-version=v1.23.9`

**Comment by filipthoen2** [comment]
Wow, it (finally) works! I can create workspaces successfully now, and interact with the Theia editor.

@tolusha - Thanks again for the extensive help!

Filip
