### ISSUE TITLE
503 Service Temporarily Unavailable - nginx [Windows 10, Hyper-V, Minikube]

### ISSUE THREAD

**Issue by filipthoen2** [eclipse/che#21633]
Happy Friday all!

I'm trying to go through a first install of Che, using my laptop / Minikube / Hyper-V.

The installation succeeds without hiccups & the installer prompts me to open:

  https://172.17.71.84.nip.io/dashboard/

I get the following error:

  "503 Service Temporarily Unavailable - nginx"

I tried stopping Che, deleting the minikube cluster, create a new cluser & re-deply Che -- same issue...

I did start Minikube with the recommended 8GB memory allocation ("minikube start --driver=hyperv --addons=ingress --vm=true --memory=8192"), so I don't think is a resource availability issue (my laptop has 16 GB...).

Any tips? Info & logs & installations steps below...

Thanks much!

Filip

Versions
----------

- Windows 10 Enterprise
- Machine: Intel x86, 16 GB RAM
- Hyper-V
- Kubectl: Client Version: v1.24.0
                Kustomize Version: v4.5.4
                Server Version: v1.24.3
- Minikube: minikube version: v1.26.1  commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
- Chectl: chectl/7.52.0 win32-x64 node-v16.13.2
- Che: v7.52.0 (latest)

Logs
------

- Che logs: [1660344271242.zip](https://github.com/eclipse/che/files/9330178/1660344271242.zip)
- installation output:  [Che installation output.txt](https://github.com/eclipse/che/files/9330196/Che.installation.output.txt)
- installation steps:  [install CHE.txt](https://github.com/eclipse/che/files/9330197/install.CHE.txt)

**Comment by tolusha** [comment]
1. Try to add more CPU to minikube cluster `--cpus 4`
2. Here is the similar issue https://github.com/eclipse/che/issues/21125 and possible solution
https://github.com/eclipse/che/issues/21125#issuecomment-1170863395

**Comment by filipthoen2** [comment]
Thanks, @tolusha -- this solved the problem! The dashboard now comes up & I can deploy workspaces. 

I tried both 'cpp', 'bash' & 'apache-camel-c', all fail with the same error:

  Container tools has state ImagePullBackOff

Looks like this has to do with K8s not being able to download one or more of the required container images.

I've attached the Che logs, which don't show an error except for the 'che-operator' pod:

2022-08-15T17:44:22.893Z	ERROR	controller-runtime.manager.controller.devworkspacerouting	Reconciler error	{"reconciler group": "controller.devfile.io", "reconciler kind": "DevWorkspaceRouti
[eclipse-che.zip](https://github.com/eclipse/che/files/9339055/eclipse-che.zip)
ng", "name": "routing-workspace49a70a39f20c4107", "namespace": "admin-che", "error": "Operation cannot be fulfilled on devworkspaceroutings.controller.devfile.io \"routing-workspace49a70a39f20c4107\": the object has been modified; please apply your changes to the latest version and try again"}

Not sure how to resolve this (checked the Che support), and whether this is the culprit.

I clicked on the 'Devfile' tab in the failed workspace in the Che Dashboard, and for instance for 'bash' workspace, I see the following 'project' mentioned:

  projects:
  - name: bash
    zip:
      location: 'http://devfile-registry.eclipse-che.svc:8080/resources/v2/bash.zip'

When I try 'curl http://devfile-registry.eclipse-che.svc:8080/resources/v2/bash.zip' I get:

  Trying 23.217.138.110:8080...

and curl times out.  Using 'http://devfile-registry.eclipse-che.svc' instead of 'http://devfile-registry.eclipse-che.svc:8080' in curl works fine.

So is this an error in devfile specification?

Thanks again!

Filip

**Comment by filipthoen2** [comment]
Issue resolved by starting minikube with 4 CPU resources

**Comment by filipthoen2** [comment]
Issue resolved by starting minikube with 4 CPU resources
