### ISSUE TITLE
Che-Code editor should be selected and opened by default in the dogfooding instance 

### ISSUE THREAD

**Issue by svor** [eclipse/che#21631]
### Describe the bug

After creating a workspace on the dogfooding instance, Theia editor will be opened by default

### Che version

next (development version)

### Steps to reproduce

1. Create any workspace on the [dogfooding](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/) instance

### Expected behavior

Che-Code should be opened by default

### Runtime

OpenShift

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 08 11-15_09_32](https://user-images.githubusercontent.com/1271546/184130404-bc4fd4aa-9019-4501-bd40-0444b2492010.png)

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 08 11-15_12_57](https://user-images.githubusercontent.com/1271546/184130765-80b93f61-dcf1-405d-82e0-da9723e9086f.png)

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
@svor I can not reproduce anymore? Seems to be some glitch after the rollout update. Che-Code is the default on dogfooding. Please, reopen if still reproducible
