### ISSUE TITLE
`.che/che-editor.yaml` content is not taken into account when running a workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21639]
### Describe the bug

I noticed that the content of the `.che/che-editor.yaml` file is ignored when starting a new workspace.
The default editor is used. For our dogfooding instance, it's always `che-code:insider`.

### Che version

next (development version)

### Steps to reproduce

Spinup a new workpace from the following factory link:
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/azatsarynnyy/java-spring-petclinic/tree/issue-demo?che-editor=eclipse/che-theia/next

Notice, that the `che-code:insider` editor is running.

### Expected behavior

It should run either `che-theia:next` editor, as it's specified via the URL parameter (`?che-editor=eclipse/che-theia/next`),
or `che-idea:next` editor should be used, as it's specified in the [`.che/che-editor.yaml` file](https://github.com/azatsarynnyy/java-spring-petclinic/blob/issue-demo/.che/che-editor.yaml).

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by azatsarynnyy** [comment]
Might be a related issue https://github.com/eclipse/che/issues/21635

**Comment by vitaliy-guliy** [comment]
> Might be a related issue #21635

Those issues have the same cause.
There is a [pull request](https://github.com/eclipse-che/che-server/pull/351) to fix the problem

![Screenshot from 2022-09-07 19-09-40](https://user-images.githubusercontent.com/1655894/188927642-de07e33b-0a73-4e24-ad0d-bd5d2465a604.png)

**Comment by azatsarynnyy** [comment]
I've tested it and I'm not able to reproduce the bug anymore. 
Thanks @vitaliy-guliy for fixing it.
