### ISSUE TITLE
Check OAuth tokens validity when workspace restarts

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21640]
### Is your enhancement related to a problem? Please describe

The validity of the GitHub/Bitbucket/Gitlab personal access tokens (that Che generates and stores as a secret in a developer namespace) are checked only when a workspace is started for the first time. 

If the token expires and an existing workspace is restarted the developer won't be able to use the git service. 

### Describe the solution you'd like

Check if the token is valid at workspace startup (it would be useful if a message mentioning that a token was found and is being verified is logged in the dashboard workspace startup progress page).

If the token is invalid generate a new one as it's done when a workspace is started for the first time.

### Additional context

https://github.com/eclipse/che/issues/21291

**Comment by vinokurig** [comment]
is fixed by 
https://github.com/eclipse-che/che-server/pull/356
https://github.com/eclipse-che/che-server/pull/359
https://github.com/eclipse-che/che-dashboard/pull/640
