### ISSUE TITLE
Verify installation on an OCP 4.12 instance without the Console

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21642]
### Is your task related to a problem? Please describe

With 4.12 OpenShift console will be an optional component (part of the [composable OpenShift effort](https://docs.google.com/document/d/1srswUYYHIbKT5PAC5ZuVos9T2rBnf7k0F1WV2zKUTrA/edit#heading=h.mduog8qznwz) / [CONSOLE-3160](https://issues.redhat.com/browse/CONSOLE-3160)). When it’s not installed, console CRDs like ConsoleLink, ConsoleCLIDownload, ConsoleYAMLSample, and ConsoleQuickStart won’t be available on the cluster. 

### Describe the solution you'd like

Make sure operators don’t fail when the CRD is missing.

**Comment by tolusha** [comment]
Should not have any problems because we already have this check
https://github.com/eclipse-che/che-operator/blob/71a5ba500c59199c28e29e6845bdf7cfe9c7df93/pkg/deploy/consolelink/consolelink.go#L49

**Comment by l0rd** [comment]
@tolusha great. If you believe that's not worth testing let's close this issue then.
