### ISSUE TITLE
Add missing recommended extensions to .vscode/extensions.json in all che-samples

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#21644]
### Is your enhancement related to a problem? Please describe

I noticed, that not all the plugins appeared to be installed after creating a workspace from quarkus sample.

[`.vscode/extensions.json`](https://github.com/che-samples/quarkus-quickstarts/blob/devfilev2/.vscode/extensions.json) for quarkus sample contains only one `redhat.vscode-quarkus` recommendation.
Che-Theia performs the plugin installation properly. It opens [redhat/vscode-quarkus/latest/che-theia-plugin.yaml](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/redhat/vscode-quarkus/latest/che-theia-plugin.yaml), downloads all the extensions from `extensions:` block and does the same for all the dependencies from `dependencies:`.

When che-code handles `.vscode/extensions.json` file, it does not aware about [`redhat/vscode-quarkus/latest/che-theia-plugin.yaml`](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/redhat/vscode-quarkus/latest/che-theia-plugin.yaml) and does not install dependencies, that are described in `dependencies:` block
```
dependencies:
  - redhat/java
  - redhat/vscode-microprofile
  - vscjava/vscode-java-debug
  - vscjava/vscode-java-test
```

This is what I have after installing the recommendations for quarkus

![Screenshot from 2022-08-19 17-35-42](https://user-images.githubusercontent.com/1655894/185659826-2e509285-f8ca-4371-ad12-e6e8b851ae0a.png)

Che-code does not touch [redhat/vscode-quarkus/latest/che-theia-plugin.yaml](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/redhat/vscode-quarkus/latest/che-theia-plugin.yaml), but installs all the dependencies, that are described in [package.json of quarkus plugin](https://github.com/redhat-developer/vscode-quarkus/blob/master/package.json#L53-L58).

```
  "extensionDependencies": [
    "redhat.vscode-microprofile",
    "redhat.java",
    "vscjava.vscode-java-debug",
    "vscode.html-language-features"
  ],
```

### Describe the solution you'd like

Review all che-samples, that we use for workspace creation, and add missing extensions to `.vscode/extensions.json`

**Comment by vitaliy-guliy** [comment]
Pull Request to merge

- [ ] [apache-camel-k](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/apache-camel-k) :: up to date
- [ ] [apache-camel-springboot](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/apache-camel-springboot) :: [Pull Request](https://github.com/che-samples/fuse-rest-http-booster/pull/4)
- [ ] [bash](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/bash) :: up to date
- [ ] [cpp](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/cpp) :: [Pull Request](https://github.com/che-samples/cpp-hello-world/pull/6)
...

**Comment by svor** [comment]
downstream issue: https://issues.redhat.com/browse/CRW-3302
