### ISSUE TITLE
Dashboard does not respect CheCluster CR changes

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21654]
### Describe the bug

Dashboard does not respect CheCluster CR changes

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che
2. Update CheCluster CR to set openVSXURL
3. Dashboard still uses an old value

### Expected behavior

Dashboard uses a new openVSXURL field value

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
Here my workaround was to delete dashboard pod (so it's started again and fetch/keep in its cache the good value)
But yes I was expected that on CheCluster change the value is updated/cache invalidated

**Comment by olexii4** [comment]
@benoitf  I cannot reproduce this issue
https://youtu.be/AVGG1STrvrQ

**Comment by benoitf** [comment]
It's still actual

![image](https://user-images.githubusercontent.com/436777/187934874-9d7d97d4-0dca-45db-86b1-87fe6746637c.png)


![image](https://user-images.githubusercontent.com/436777/187934905-604634a7-2f79-46fa-95e3-7f120d16a48c.png)


we can clearly see that plug-in registry pod has been restarted but not the dashboard and we still have the previous value of the CheCluster 

![image](https://user-images.githubusercontent.com/436777/187935179-3c8a7d0c-3c8f-412f-adaf-6617327a7e48.png)


so dashboard is still applying the wrong value

**Comment by olexii4** [comment]
> It's still actual
> 
> ![image](https://user-images.githubusercontent.com/436777/187934874-9d7d97d4-0dca-45db-86b1-87fe6746637c.png)
> 
> ![image](https://user-images.githubusercontent.com/436777/187934905-604634a7-2f79-46fa-95e3-7f120d16a48c.png)
> 
> we can clearly see that plug-in registry pod has been restarted but not the dashboard and we still have the previous value of the CheCluster
> 
> ![image](https://user-images.githubusercontent.com/436777/187935179-3c8a7d0c-3c8f-412f-adaf-6617327a7e48.png)
> 
> so dashboard is still applying the wrong value

@benoitf I created the video on how the dashboard used and applied the new openVSXURL during the creation of new workspaces.

Do you expect the dashboard should check and update the environment variables on all created workspaces? 

Could you clarify the steps to reproduce?
