### ISSUE TITLE
How can I identify that my devfile is incompatible with some editors / can only be opened with some editors? 

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21658]
### Summary

With the new UI in Che 7.53 that allows you to choose which editor to use when opening a sample project ... 

![image](https://user-images.githubusercontent.com/227597/186725694-89a67b49-c86c-40de-a901-1a06916fcaa9.png)

I'm wondering if there's a way to specify that a given sample only supports vscode, or theia, or pycharm, or idea. 

Could this be done via meta.yaml in via a new property for "`editors`"?

https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/dotnet-asp.net/meta.yaml

for example, could we do something like this to prevent the sample from being loaded into theia or pycharm, with only vscode and idea supported?

```
displayName: "ASP.NET Core Web Application"
description: Stack for developing ASP.NET Core Web Application
tags: ["Community", "Debian", "Dotnet", "C#", "ASP.NET"]
editors: ["che-incubator/che-code/insiders", "che-incubator/che-idea/latest"]
icon: /images/dotnetcore.svg
links:
  v2: https://github.com/che-samples/aspnetcore-realworld-example-app/tree/devfilev2
```

### Relevant information

Downstream context is that I'm wondering if we can disable a sample from being available on Theia, while supporting it on VSCode only. 

See also:
* https://issues.redhat.com/browse/CRW-2456 (dotnet doesn't work in theia, suggestion is to move to vscode and use dotnet vscode extension)
* https://issues.redhat.com/browse/CRW-3288 (notion of removing the bad plugins from theia so the project can load w/o errors ... but also without the lang support)

**Comment by benoitf** [comment]
I don't know what you mean about 'incompatible' as all IDEs will open the project and will provide the tasks to run the project

**Comment by nickboldt** [comment]
incompatible = "opening this with theia won't work; please use vscode instead"

**Comment by l0rd** [comment]
It makes sense to omit some editors on some samples. For example it may be surprising to see IntelliJ for a .NET sample.

But coupling samples with editors is not ideal: if a new editor is added all samples meta.yaml should be reviewed, same if an editor is removed. 

Instead we could use tags to decide if an editor is "compatible" with samples (for example we could specify in IntellJ definition that it's compatible with "Java", "Scala" etc...). 

But today that looks like a low priority problem: it's just about samples (not a core functionality) and it's a small detail that a few will notice. Theia case should be addressed as VS Code becomes the default.

**Comment by nickboldt** [comment]
As VSCode is now the default... should we consider this for a future release?
