### ISSUE TITLE
How can I enable a vscode extension for one editor, but disable it for a second?

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21659]
### Summary

Having read thru the Che Docs about configuring per-editor plugins, it's unclear if we can completely override/ignore plugins installed for VSCode when launching Theia.

https://www.eclipse.org/che/docs/stable/end-user-guide/adding-a-vscode-extension/#visual-studio-code-extensions-json

> The easiest way to add a Visual Studio Code extension to a workspace is to add it to the `.vscode/extensions.json` file. The main advantage of this method is that it works with all supported Che IDEs.

For example:

The netcoredbg-theia-plguin and omnisharp-theia-plugin fail to load in Theia, but work in VSCode. 

But if I include a `.vscode/recommendations.json` file in my project repo, like:

https://github.com/devspaces-samples/dotnet-web-simple/blob/devspaces-3-rhel-8/.vscode/extensions.json

Then those same plugins are loaded into Theia (and fail, as noted in https://issues.redhat.com/browse/CRW-2456 and https://issues.redhat.com/browse/CRW-3288). 

Would including a blank `.che/che-theia-plugins.yaml` file prevent this? Or inlining both a `.che/che-theia-plugins.yaml` and a `.vscode/recommendations.json` so the default load behaviour is overridden? 

### Relevant information

Downstream context is that I'm wondering if we can disable a plugin from loading in Theia, while recommending it be installed into VSCode only.

See also:

https://issues.redhat.com/browse/CRW-2456 (dotnet doesn't work in theia, suggestion is to move to vscode and use dotnet vscode extension)
https://issues.redhat.com/browse/CRW-3288 (notion of removing the bad plugins from theia so the project can load w/o errors ... but also without the lang support)

**Comment by benoitf** [comment]
if you add a che-theia-plugins.yaml it will be specific to che-theia

There is no specific che-code.yaml file

And bot will read the .vscode/extensions.json file

**Comment by nickboldt** [comment]
So you're saying to use `.vscode/recommendations.json` for ONLY vscode, you can also add an empty `che-theia-plugins.yaml` file?

**Comment by nickboldt** [comment]
Closing as I'm no longer worried about this... theia has its list of plugins, vscode has its NEWER list
