### ISSUE TITLE
Don't show the problem matcher prompt for Devfile commands in Che-Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21651]
### Is your enhancement related to a problem? Please describe

Every time the user runs a Devfile Command in Che-Code, they are asked for choosing a problem matcher for scanning an output.
![image](https://user-images.githubusercontent.com/1636395/186145268-270c6e95-6c43-4979-a34a-3e56990fc34d.png)

That extra step is annoying and it is redundant in 99% of cases.

### Describe the solution you'd like

When running a Devfile Command, Che-Code should use an empty problem matches list:
`problemMatcher: []`

So, the user won't be asked for choosing it manually.

### Describe alternatives you've considered

It can be configured by the user. See the `"task.problemMatchers.neverPrompt": true` setting.

### Release Notes Text

Every time a user runs a Devfile command in Che-Code they need to choose a problem matcher for scanning an output. This extra step is annoying and it is redundant in 99% of cases so it has been removed.

**Comment by azatsarynnyy** [comment]
Now, VS Code won't ask the user to choose a problem matcher for parsing the output of the running Task if it represents a Devfile Command.
If one wants to specify a problem matcher for such a Task, it's still possible to customize the Task with the `Configure Task` feature.

**Comment by max-cx** [comment]
Sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-3636
