### ISSUE TITLE
Revert the Custom Workspace tab removal

### ISSUE THREAD

**Issue by amomra** [eclipse/che#21656]
### Is your enhancement related to a problem? Please describe

As described in PR [#377]( https://github.com/eclipse-che/che-dashboard/pull/377) of che-dashboard, it was removed because users must use a GIT repo with a devfile when creating a new workspace. This is fine when the workspace's devfile is already created but it would be nice to be able to create a new devfile using the Custom Workspace tab as it was in the pre-DW clusters.

You still can edit the workspace devfile using Eclipse Che UI but you can't rename it, making impossible to create multiples test workspaces using the quick add samples. Also you can't create a blank workspace to test the configuration before creating the project repository.

Since this was a feature that already existed it would be nice to revert this removal.

### Describe the solution you'd like

Revert the Custom Workspace tab removal at workspace creation screen.

**Comment by Deel96** [comment]
I'm also sad that the feature was removed. If you want to change one little aspect of a existing workspace it was very handy and as you mentioned is useful for testing purposes.
