### ISSUE TITLE
Can't install an extension from the embedded openVSX 

### ISSUE THREAD

**Issue by svor** [eclipse/che#21662]
### Describe the bug

After switching to the local plugin registry it's not possible to install any extension into Che-Code.
The error message is:

```
Error while installing 'Go' extension. Please check the log for more details.
onDidChangeNotification @ workbench.web.main.js:808
(anonymous) @ workbench.web.main.js:808
invoke @ workbench.web.main.js:80
deliver @ workbench.web.main.js:80
fire @ workbench.web.main.js:80
addNotification @ workbench.web.main.js:808
notify @ workbench.web.main.js:1996
prompt @ workbench.web.main.js:1996
run @ workbench.web.main.js:3126
install @ workbench.web.main.js:3126
await in install (async)
run @ workbench.web.main.js:3126
run @ workbench.web.main.js:3126
runAction @ workbench.web.main.js:80
run @ workbench.web.main.js:80
onClick @ workbench.web.main.js:174
(anonymous) @ workbench.web.main.js:174
workbench.web.main.js:600   ERR self signed certificate in certificate chain: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
```

### Che version

next (development version)

### Steps to reproduce

1. Update Che CR by setting openVSXURL with empty value to use the embedded plugin registry: 
```
    pluginRegistry:
      openVSXURL: ''
```
2. Delete dashboard pod because of https://github.com/eclipse/che/issues/21654
3. Start any workspace with Che-Code
4. Try to install any extension

### Expected behavior

The extension should be installed

### Runtime

OpenShift

### Screenshots

![screenshot-eclipse-che apps ci-ln-8wx7y9b-72292 origin-ci-int-gce dev rhcloud com-2022 08 26-14_01_04](https://user-images.githubusercontent.com/1271546/186889947-e57cfefc-af6a-42e2-93f8-409cceb9b4d0.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
looks like an issue on certificates not being trusted

**Comment by svor** [comment]
@benoitf maybe it'll solve the problem: https://github.com/che-incubator/che-code/pull/96 
to use internal plugin registry URL
