### ISSUE TITLE
Explain how to develop che-dashboard with Eclipse Che

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21667]
### Is your task related to a problem? Please describe

There is now a devfile v2 for the che-dashboard repository: https://github.com/eclipse-che/che-dashboard/blob/main/devfile.yaml.

It would be great if there was a section in the che-dashboard README that explains how to develop dashboard with the devfile v2 on Eclipse Che / workspaces.openshift.com.

### Describe the solution you'd like

Maybe a `Contributing` section, or a `How to develop using Che` section in the README would suffice.

It could cover:
* starting the workspace
* downloading dependencies and building with the tasks defined in the devfile
* pushing to remote, making a PR

### Describe alternatives you've considered

An alternative could be a CONTRIBUTING.md file instead, which is linked in the README

**Comment by ibuziuk** [comment]
@dkwon17 https://github.com/eclipse-che/che-dashboard/pull/617 has been merged, can we close the issue?

**Comment by dkwon17** [comment]
Yes, this issue can be closed
