### ISSUE TITLE
Faster workspace startup as a result of avoiding changes to DevWorkspace CR after it has started

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21664]
### Describe the bug

During startup looks like dashboard is patching DevWorkspace which results in replica set being scaled down resulting in a much slower workspace startup
![image](https://user-images.githubusercontent.com/1461122/186893414-6bf5e931-c405-4662-bdf9-a4b23dfa6954.png)
the 

### Che version

7.50

### Steps to reproduce

1. Go to workspaces.openshift.com
2. Start a workspace from getting started samples of via factory
3. open OpenShift events 
4. ERROR: see that replica set is scaled up and down within a short time frame (less than 1 minute)

### Expected behavior

replica set is scaled up once during workspace startup

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

### Release Notes Text

The startup times of workspaces that have a persistent volume attached (the default) has been significantly improved.

**Comment by ibuziuk** [comment]
@olexii4 I was able to reproduce the issue on Dev Spaces 3.2 even though the fix was backported - https://github.com/eclipse-che/che-dashboard/pull/626

Please, find the events when an alternative editor (VSCode) is selected for Getting Started samples

![image](https://user-images.githubusercontent.com/1461122/197224239-1868a51a-595e-4335-b627-0cc3aed39a49.png)

**Comment by olexii4** [comment]
@ibuziuk I cannot reproduce it.
I have checked all requests from the UD and they are fine:
![Знімок екрана 2022-11-27 о 14 25 06](https://user-images.githubusercontent.com/6310786/204136077-8e72125d-5246-489a-a463-e428a83447ae.png)
![Знімок екрана 2022-11-27 о 14 24 07](https://user-images.githubusercontent.com/6310786/204136092-7907df1b-b849-4b23-94e2-cae96ea11de4.png)
![Знімок екрана 2022-11-27 о 14 23 24](https://user-images.githubusercontent.com/6310786/204136152-08372a50-6c95-4f48-b820-0df381975c7e.png)
![Знімок екрана 2022-11-27 о 14 21 59](https://user-images.githubusercontent.com/6310786/204136173-e4e0740c-b608-4151-9e59-5e3c03118837.png)
![Знімок екрана 2022-11-27 о 14 20 55](https://user-images.githubusercontent.com/6310786/204136302-419f43a8-283b-49bf-9da2-c90cf8283014.png)
Events are good too:
![Знімок екрана 2022-11-27 о 14 44 04](https://user-images.githubusercontent.com/6310786/204136399-48697916-f553-4ce0-83f1-4dc2ae0a24f8.png)
![Знімок екрана 2022-11-27 о 14 44 35](https://user-images.githubusercontent.com/6310786/204136403-d7ad2e6e-3853-4ce5-aa4f-4691222623b4.png)
![Знімок екрана 2022-11-27 о 14 44 57](https://user-images.githubusercontent.com/6310786/204136416-9409668e-5800-4a5d-bff7-2e53575810ca.png)
My created workspace:
![Знімок екрана 2022-11-27 о 14 45 54](https://user-images.githubusercontent.com/6310786/204136447-f7c1b3b9-999b-43ee-9ea9-0c24c0750f66.png)

**Comment by ibuziuk** [comment]
@olexii4 it seems that in 3.3 on workspaces.openshift.com we still have this behavior when starting getting-started samples:

![image](https://user-images.githubusercontent.com/1461122/207831445-e33b4042-7c92-485e-9c9a-4d53d02e5070.png)

Reproduced with NodeJs MongoDB

**Comment by ibuziuk** [comment]
Need to verify again after workspaces.openshift.com upgrades to 3.5 and close if not reproducible

**Comment by ibuziuk** [comment]
Verified against workspaces.openshift.com Closing
