### ISSUE TITLE
Display current runningLimit on the Dashboard when workspaces runningLimit reached

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21669]
### Is your enhancement related to a problem? Please describe

By default, the workspace runningLimit is 1. When there is already a running workspace, and if another workspace has been started via the dashboard, this error message appears:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/83611742/187288382-44c85a7f-ec44-4071-aaa3-a06e58d20e8a.png">

### Describe the solution you'd like

It would be great if the error message also specified what the workspace runningLimit is.

Instead of `You are not allowed to start more workspaces`, something like:
* `You can only run 1 workspace at a time` or
* `Only 1 workspace can be running at a time`

could be more helpful

**Comment by dkwon17** [comment]
This seems quite straight-forward to implement, probably only need to update a string here:
https://github.com/eclipse-che/che-dashboard/blob/6f0c322c9ba0baf2a13c8e93a64e1b14b64df91d/packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts#L298

**Comment by ibuziuk** [comment]
@dkwon17 looks like this issue has been fixed with https://github.com/eclipse-che/che-dashboard/pull/620 
can we close it now?
