### ISSUE TITLE
The dashboard 'Not allowed to start more workspace' message could be confusing if workspace creation step is completed

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21672]
### Is your enhancement related to a problem? Please describe

Currently, when the user tries to start a new workspace when the user already has the maximum allowable number of concurrent running workspaces (set by admin by setting `spec.components.devWorkspace.runningLimit` in the Che CR), the user will see this message from the dashboard:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/83611742/187450599-faf7ecc5-3e91-4ee7-8541-a6a3cc28ca19.png">

### Describe the solution you'd like

This message might be a bit confusing because we can see in the UI that step 2 `Creating a workspace` has been completed. Workspace creation might imply that the workspace/editor exists and is accessible, when it is not (since the workspace has not started).

A possible solution is to make it clear that workspace creation and workspace startup are separate actions from the error message.

For example, instead of `You are not allowed to start more workspaces`, it could be `The workspace was created, but it cannot be started because you have reached the maximum running workspaces limit`.

It is important to note that this new message would only make sense when the user starts a new workspace, not an existing one. 

### Describe alternatives you've considered

A different solution could be to not create the workspace at all if the running workspaces limit is reached. 

### Additional context

Would be great if the error message also displayed what the maximum workspace running limit is: https://github.com/eclipse/che/issues/21669

**Comment by akurinnoy** [comment]
This issue was fixed in https://github.com/eclipse-che/che-dashboard/pull/841

Screenshot from the dogfooding cluster:

![Screenshot 2024-02-21 at 10 41 08](https://github.com/eclipse/che/assets/16220722/a48c44e5-4a01-446f-9eca-e057e8827561)
