### ISSUE TITLE
FAQ / Known issues devfile v2 migration links are broken

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21670]
### Describe the bug

https://devfile.io/docs/devfile/2.2.0/user-guide/migrating-to-devfile-v2/ is no longer working 

### Che version

7.52@latest

### Steps to reproduce

![broken FAQ links ](https://user-images.githubusercontent.com/1461122/187450673-4a06888d-d913-47bd-a1fe-41c678c8dcf9.gif)

### Expected behavior

Link redirects to https://devfile.io/docs/2.2.0-alpha/migrating-to-devfile-v2

### Runtime

Kubernetes (vanilla)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
@elsony all the 3.x instances are affected, would it be possible to setup redirect from https://devfile.io/docs/devfile/2.2.0/user-guide/migrating-to-devfile-v2/ to https://devfile.io/docs/2.2.0-alpha/migrating-to-devfile-v2 ?

**Comment by ibuziuk** [comment]
PR for fixing link on the dashboard end https://github.com/eclipse-che/che-dashboard/pull/611 (should be also backported to 7.52.x)

**Comment by ibuziuk** [comment]
PRs have been merged including the backport to 7.52.x (Dev Spaces 3.2) - https://github.com/eclipse-che/che-dashboard/pull/613 

@elsony could you please set up redirect for https://devfile.io/docs/devfile/2.2.0/user-guide/migrating-to-devfile-v2/ ?

**Comment by elsony** [comment]
@schultzp2020 is currently investigating if we can do the redirect. We'll keep this item up-to-date

**Comment by elsony** [comment]
The redirect has been implemented.

**Comment by ibuziuk** [comment]
thank you. Closing
