### ISSUE TITLE
Che 7.41 documentation no longer available

### ISSUE THREAD

**Issue by gustavoromerobenitez** [eclipse/che#21688]
### Describe the bug

Since the 7.53 release, approximately, the Che 7.41 documentation redirects to version 7.53.

In general, any URL with /che-7/ in it, redirects to version 'stable', for instance:

This URL: https://www.eclipse.org/che/docs/che-7/installation-guide/checluster-custom-resource-fields-reference/
redirects to: https://www.eclipse.org/che/docs/stable/overview/introduction-to-eclipse-che/

### Che version

7.53@latest

### Steps to reproduce

Using Firefox or Edge, latest versions

1. Open the Che Documentation page on your browser
2. From the drop-down list on the right hand side, select '(old) 7.41'
3. The browser is redirected again to version '7.53.x' and the drop-down resets.

Also try using a link that contains /che-7/ in its URL,. Your browser will be redirected as indicated above.

### Expected behavior

The valuable 7.41 documentation should still be available, especially for users that haven't been able to upgrade. 

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by max-cx** [comment]
Downstream issue: https://issues.redhat.com/browse/RHDEVDOCS-4649

**Comment by themr0c** [comment]
The projects is maintaining live only two versions of the documentation: 
* stable
* next

**Comment by l0rd** [comment]
@themr0c if we don't support it anymore we should remove the link to `old (7.42)`:

<img width="133" alt="image" src="https://user-images.githubusercontent.com/606959/218582769-758a2304-895b-4155-8d58-e0c79bda65a4.png">
