### ISSUE TITLE
Update che-theia to Theia's latest version

### ISSUE THREAD

**Issue by luxingxiao** [eclipse/che#21687]
### Is your enhancement related to a problem? Please describe

The latest version 1.29 of Theia has a lot of new features and fixes a lot of issues. Che-theia che-theia is still using version 1.18 of thiea.

### Describe the solution you'd like

Update che-theia to Theia's latest version 1.29.  We tried to do the upgrade, but encountered a lot of problems.

**Comment by azatsarynnyy** [comment]
Hi @luxingxiao 
currently, we're focused on VS Code as the default IDE for Eclipse Che. I can recommend you to look at the VS Code assembly that is used in Che https://github.com/che-incubator/che-code

**Comment by Deel96** [comment]
Would it be possible to give some information why the focus lies at the moment on VS Code? It seems odd at first since Theia is also a Eclipse project.

**Comment by l0rd** [comment]
@Deel96 we have created this issue to provide more details https://github.com/eclipse/che/issues/21771
