### ISSUE TITLE
Constantly redirecting between two auth pages

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21685]
### Describe the bug

When I'm trying to log in to the [dogfooding instance](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/) my browser is constantly redirecting between two auth pages. See the attached screencast. 

### Che version

next (development version)

### Steps to reproduce

Try to log in to the [dogfooding instance](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/).

### Expected behavior

The user should be able to log in to Che.

### Runtime

OpenShift

### Screenshots

![login](https://user-images.githubusercontent.com/1636395/188589459-57d493f1-28e0-42dd-82ce-b3e436440145.gif)

### Installation method

OperatorHub

### Environment

Linux

**Comment by amisevsk** [comment]
Updating the restart job to stagger restarting pods appears to have fixed the issue. Cronjob was updated to have command 
```diff
   - command:
     - /bin/sh
     - -c
-    - kubectl delete pods -l app=che -n dogfooding
+    - |
+      kubectl delete pods -n dogfooding -l 'app=che,component!=che' --wait=false
+      kubectl rollout status -n dogfooding deploy/che-gateway
+      kubectl rollout status -n dogfooding deploy/che-dashboard
+      kubectl rollout status -n dogfooding deploy/postgres
+      kubectl delete pods -n dogfooding -l 'app=che,component=che'
+      kubectl rollout status -n dogfooding deploy/che
```
and get/list/watch deployments permissions were added to the ServiceAccount to enable `kubectl rollout status`.

**Comment by azatsarynnyy** [comment]
I'm facing this issue again on the dogfooding cluster.

**Comment by ibuziuk** [comment]
Still under investigation but the culprit was CrashLoopBackOff of the postgres pod. This seems to be a known issue from 2020 documented as part of https://access.redhat.com/solutions/5668581 but we have never faced it before. After running the steps from 'Resolution' Postgres pod started successfully

**Comment by ibuziuk** [comment]
Closing the issue - for the last  10 days there were no problems with the nightly updates on the dogfooding cluster + in the short run we are going to switch to the OpenShift 11 fast update channel. Feel free to reopen in case of any problems
