### ISSUE TITLE
Document how to apply a custom branding to Che-Code editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21682]
### Is your task related to a problem? Please describe

There's a white-labeling feature in Che-Code - https://github.com/che-incubator/che-code/pull/97
It's possible to apply custom branding for the Che-Code editor, but there's no documentation on how to do that.

### Describe the solution you'd like

We need to add a dedicated topic to Che documentation with the steps required for applying custom branding.

https://www.eclipse.org/che/docs/stable/administration-guide/branding/

**Comment by max-cx** [comment]
Downstream issue link: https://issues.redhat.com/browse/RHDEVDOCS-4586

**Comment by azatsarynnyy** [comment]
Che-Code's README.md has been updated by https://github.com/che-incubator/che-code/pull/99.
Che docs site update is tracked in the downstream issue mentioned above.
