### ISSUE TITLE
Update UDI to allow using fuse-overlay rather than VFS with podman/buildah

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21693]
### Is your enhancement related to a problem? Please describe

VFS is slow and building an image using Eclispe Che may take minutes when the same build takes seconds on a local machine.

### Describe the solution you'd like

Configure docker/podman in the Universal Developer Image to use Fuse instead of VFS and test to build and image on OpenShift.

### Additional context

[It's recommended to use fuse-overlayfs rather than VFS when using podman/buildah/docker](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#ensure-fuse-overlayfs-is-installed)
[There was an initiative to use Fuse overlay by default](https://github.com/openshift/enhancements/issues/362)

**Comment by l0rd** [comment]
[Downstream issue](https://issues.redhat.com/browse/CRW-3397)

**Comment by cgruver** [comment]
@l0rd Try this, it works.

Create a MachineConfig to enable containers to use `/dev/fuse`

```bash
cat << EOF | butane | oc apply -f -
variant: openshift
version: 4.13.0
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: nested-podman
storage:
  files:
  - path: /etc/crio/crio.conf.d/99-nested-podman
    mode: 0644
    overwrite: true
    contents:
      inline: |
        [crio.runtime.workloads.nested-podman]
        activation_annotation = "io.openshift.nested-podman"
        allowed_annotations = [
          "io.kubernetes.cri-o.Devices"
        ]
        [crio.runtime]
        allowed_devices=["/dev/fuse"]
EOF
```

__Note:__ Use `machineconfiguration.openshift.io/role: master` on SNO

Next, create a Dev Spaces workspace with a Podman enabled image.

Remove the `vfs` configuration if it has been set in `~/.config/containers/storage.conf`

Then run a `podman build`
