### ISSUE TITLE
launch.json configuration not loaded properly after refreshing the page with IDE

### ISSUE THREAD

**Issue by lexiv0re** [eclipse/che#21690]
### Describe the bug

For a workspace with 2 projects it is not picking the existing launch configuration if launch.json is created in the second workspace.

### Che version

7.50

### Steps to reproduce

1. Create a workspace with two projects.
2. Create a file to be run in the second project.
3. Open the file and select `Run -> Start Without Debugging`. <img width="618" alt="Start" src="https://user-images.githubusercontent.com/20221821/189131144-8442e4ba-62cb-4ac4-a0e8-e1259b300f92.png">
4. It asks for the environment and debug configuration and creates `.theia/launch.json` in the second project. <img width="823" alt="LaunchConfig" src="https://user-images.githubusercontent.com/20221821/189131164-5406c196-5928-4a89-aad9-ac8b9db4dcff.png">
5. The file can now be run successfully with `Run -> Start Without Debugging` without any prompts.
6. Refresh the page, close `Getting Started` tab so the same file is focused. Note, that `launch.json` is present. <img width="946" alt="RunAgain" src="https://user-images.githubusercontent.com/20221821/189132135-7b7b5ed5-2622-48e6-ad64-2592be34daec.png">
8. Try `Run -> Start Without Debugging` again. Instead of executing the file it opens the existing `launch.json` and expects for more launch configurations to be added.
<img width="877" alt="Prompt" src="https://user-images.githubusercontent.com/20221821/189132716-e5ea6444-c86d-4396-b650-45307c5d21a9.png">

### Expected behavior

On the step 7 it is expected to use the existing configuration and run without any additional prompts.

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Linux

### Additional context

microK8s
chectl 7.50.0

Note: If I try to run all the same steps but for the first project in the workspace the problem doesn't reproduce.

**Comment by azatsarynnyy** [comment]
@lexiv0re I suggest checking the described use case in the [upstream Eclipse Theia project](https://github.com/eclipse-theia/theia). To me, it looks like an upstream issue.
Also, take into account https://github.com/eclipse/che/issues/21771

**Comment by lexiv0re** [comment]
@azatsarynnyy thank you for the heads up.

I tested it on the upstream `Theia` with multi-root workspace and it's not reproducible there. That might be because
* It has been already fixed there by now
* It's specific to `che-theia`
