### ISSUE TITLE
Night Che Code fails to start

### ISSUE THREAD

**Issue by ebramirez** [eclipse/che#21708]
### Describe the bug

In the Developer Sandbox, a Workspace using Che Code nightly fails to start with the error: `devworkspace failed to progress past phase 'Starting' for longer than timeout (5m)`.

### Che version

7.50

### Steps to reproduce

1. Create a workspace using Che Code nightly in the Developer Sandbox. For example https://github.com/RedHatTraining/DO378-apps/tree/research-devspaces/
2. Try to open the Workspace

### Expected behavior

Workspace opens normally.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by azatsarynnyy** [comment]
Thank you @ebramirez for reporting it. We're already investigating it.

**Comment by azatsarynnyy** [comment]
From the editor's container logs I see that VS Code is started successfully:
```
[GIN-debug] Listening and serving HTTP on 0.0.0.0:3333
using OPENVSX_URL=https://open-vsx.org/vscode
Server bound to 127.0.0.1:8000 (IPv4)
Extension host agent listening on 8000
Web UI available at http://localhost:8000/
[12:43:49] Extension host agent started.
[GIN] 2022/09/16 - 12:43:49 | 200 |      345.11µs |       127.0.0.1 | GET      /connect
```

But Dashboard shows:

![image](https://user-images.githubusercontent.com/1636395/190641192-190c8d79-5989-4b67-8077-105f50bf9c66.png)

**Comment by RomanNikitenko** [comment]
yes, I noticed it as well...

**Comment by benoitf** [comment]
it seems entrypoint specify port listening number to be 3100 (with --port 3100) but real listening port is on 8000 (so either flag is ignored or skipped)

**Comment by azatsarynnyy** [comment]
The problem is that before the last changes from upstream VS Code run on port 3100:
```
[GIN-debug] Listening and serving HTTP on 0.0.0.0:3333
using OPENVSX_URL=https://open-vsx.org/vscode
Server bound to 127.0.0.1:3100 (IPv4)
Extension host agent listening on 3100
```

but now it's on port 8000

**Comment by azatsarynnyy** [comment]
> it seems entrypoint specify port listening number to be 3100 (with --port 3100) but real listening port is on 8000 (so either flag is ignored or skipped)

yes, I've just noticed that

**Comment by benoitf** [comment]
executing command `socat tcp-l:3100,fork,reuseaddr tcp:127.0.0.1:8000` in the terminal of UDI for example allows to boot the workspace

**Comment by azatsarynnyy** [comment]
While we're investigating it, it's possible to start VS Code in Che from one of the previous images,
e.g.: `quay.io/che-incubator/che-code:insiders-69b69eb`

**Comment by azatsarynnyy** [comment]
The suspicious commit: https://github.com/microsoft/vscode/commit/519b06e4cb7322fc93185e99db1bf38141b61b7b

**Comment by azatsarynnyy** [comment]
fixed
