### ISSUE TITLE
Dashboard IDE selection and devworkspace creation should not use the same displayName variable

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21704]
### Is your enhancement related to a problem? Please describe

As discovered in [CRW-3098](https://issues.redhat.com/browse/CRW-3098) and [CRW-3327](https://issues.redhat.com/browse/CRW-3327), the Dashboard (as of 7.52.x = 3.2) presents a list of availale IDEs for a given sample project using the `displayName` fields in the che-editors.yaml file, then converts the found string to Title Case.

Here's how the IDE selection looks upstream in Che:

![image](https://user-images.githubusercontent.com/227597/190394216-27a931c7-dcac-4168-8b9b-ac302da83c6e.png)

Note that the names shown are inconsistent (IDEA has a full name, where the other two do not), and "che-code" is not an official trademark-compliant name. Also "Theia-Ide" is less descriptive than "Eclipse Theia" and weirdly cased as "Ide" does not look like an acronym -- it should be "IDE".

I attempted to clean up the displayed names to comply with trademark/legal requirements: 

![image](https://user-images.githubusercontent.com/227597/190394362-b41defb1-df46-48d5-91b3-4006266e587d.png)

But this broke the Dashboard and Factory's ability to launch workspaces w/ theia and vscode as the same displayName is used to create the devworkspace*.yaml files in the offline devfile registry.

So, this is problematic for a number of reasons:

* spaces and uppercase letters in the IDE's `displayName` result in non-compliant subdomain values for the workspaces (workspaces won't open)
* NOT having spaces and uppercase letters in the IDE selection UI means we have `Vscode` instead of `VS Code` which is embarrassing and doesn't comply with trademark rules

![image](https://user-images.githubusercontent.com/227597/190394849-cb66304c-351f-4016-9683-b474e4f6ba76.png)

### Describe the solution you'd like

1. We could add a new field to the che-editors.yaml that can be used to generate the workspace subdomain prefix, eg., `workspacePrefix` = {idea, theia, vscode}
2. We could add a new field for the Dashboard to use when displaying the IDE list, eg., `selectionName` = {"IntelliJ IDEA Community", "Eclipse Theia", "VS Code - Open Source"}

**Comment by svor** [comment]
Probably as an another solution we can improve libraries that generate DevWorkspace templates to check that DevWorkspaceTemplate metadata.name contains only lower case alphanumeric characters, '-' or '.'
In that case we won't need to add new fields

**Comment by ibuziuk** [comment]
The dashboard displays the values coming from https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml as-is. If anything need to be changed there please provide a fix and let us know. On the dashboard end we are not going to add any extra logic related to editor names - all the metadata should come from the registry

**Comment by nickboldt** [comment]
First two PRs:
* https://github.com/eclipse-che/che-plugin-registry/pull/1441
* https://github.com/redhat-developer/devspaces/pull/829

Once merged, will need a PR for Dashboard too.

**Comment by nickboldt** [comment]
I think we can resolve this as we have updated the display names in the dashboard and can still open workspaces. See https://issues.redhat.com/browse/CRW-3098
