### ISSUE TITLE
Unable to update config yaml for che deployment on minikube

### ISSUE THREAD

**Issue by sreeramu** [eclipse/che#21709]
### Summary

I am trying to update some configurations of yaml of che-dashboard deployment but not able to update it is resetting back.

`kubectl patch -n eclipse-che deployment che-dashboard -p '{"spec":{"template":{"spec":{"containers":[{"name":"che-dashboard","imagePullPolicy":"IfNotPresent"}]}}}}'`

I had try with "kubectl patch" & "kubectl apply" also the configurations are not getting updated it is setting back to the original values.

Any help on this will be more helpful.

Che version :

Dashboard Version
7.54.0-next
Server Version
7.54.0-SNAPSHOT

**Comment by tolusha** [comment]
CheCluster CR is a single point to configure Eclipse Che instance.
Use the following command to update pull policy:
`kubectl patch checluster/eclipse-che --patch '{"spec": {"components": {"dashboard": {"deployment": {"containers": [{"imagePullPolicy": "IfNotPresent"}]}}}}}' --type=merge -n eclipse-che`

**Comment by sreeramu** [comment]
@tolusha thank you , it worked , will read more about this.
