### ISSUE TITLE
Devfile could not be found in the branch which name contains '/' sign

### ISSUE THREAD

**Issue by svor** [eclipse/che#21706]
### Describe the bug

In some cases users could have **devfile.yaml** file in the branch that contains `/` sign. 
The problem is that it is not possible to create a workspace via factory by using this **devfile.yaml**. 

In the dashboard I see a message like: "Devfile could not be found in repo. Applying the default configuration"

### Che version

next (development version)

### Steps to reproduce

1. Create a branch with `/` sign in your repository with `devfile.yaml`
2. Try to create a workspace by factory using this branch

OR

try this factory: https://che-host/#/https://github.com/svor/quarkus-api-example/tree/new/branch
in the dogfooding instance it's https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#/https://github.com/svor/quarkus-api-example/tree/new/branch

### Expected behavior

The workspace should be started from the existing devfile

### Runtime

OpenShift

### Screenshots

![screenshot-devspaces apps sandbox-m2 ll9k p1 openshiftapps com-2022 09 16-10_28_19](https://user-images.githubusercontent.com/1271546/190583317-42a86829-1442-42ad-930a-d6873d288eb2.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by l0rd** [comment]
There are a couple of workarounds for this issue. Although they are not ideal I am adding them here for information:

**First workaround**

Making the branch the default branch

**Second workaround**
Explicitly add the project in the devfile and use the raw devfile link to start the workspace. 

This is the devfile in branch `new/branch` of the repo [github.com/l0rd/quarkus](https://github.com/l0rd/inventory-quarkus):
```yaml
...
projects:
  - name: inventory-quarkus
    git:
      remotes:
        origin: 'https://github.com/l0rd/inventory-quarkus'
      checkoutFrom:
        revision: new/branch
...
```
And it can be started using URL `https://<che-host>/#https://raw.githubusercontent.com/l0rd/inventory-quarkus/new/branch/.devfile.yaml`
