### ISSUE TITLE
Auto-install VS Code extensions specified in `.vscode/extensions.json`

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21701]
### Is your enhancement related to a problem? Please describe

VS Code allows providing the extensions list (`.vscode/extensions.json`) that will be recommended for installation. The user needs to confirm that she really wants to install the recommended extensions set once VS Code starts ([docs link](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)).

While it looks great when running VS Code as a desktop application (Electron), it looks more like a redundant step when using VS Code in the cloud context.

Considering that one of the main goals of Che is to provide a **fully ready environment** for the developers, we can automate the step when the user needs to confirm what is already declared in the project's config file. Not to bother the user by accepting pop-ups. Note, that in some cases there might be a few suggestions to install the extensions.

Everything described above might not be a big problem for the experienced VS Code user. But we see from the internal feedback that it is a problem for those who have no previous experience with VS Code. For people, it's not obvious why the extensions declared in the `.vscode/extensions.json` config file are not actually installed in the running VS Code OOTB. Also, it turned out that for some users the relatively tiny notification in the window corner does not attract much attention:
![image](https://user-images.githubusercontent.com/1636395/203568906-8b0f760b-fcda-45c5-a8f9-8ca5d20a95fe.png)

### Describe the solution you'd like

With the VS Code CLI, it's possible to install the extensions set forcibly, without the user's confirmation ([docs link](https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management)).

One of the options: the user can provide a dedicated attribute in the Devfile to tell VS Code that the recommended extensions, provided in the `.vscode/extensions.json`, are actually mandatory and must be installed without the user's confirmation.

### Release Notes Text

Recommended extensions in file `.vscode/extensions.json` are automatically installed by che-code at workspace startup. Before the developer get prompted to install them. This is the behavior we had in che-theia as well.

**Comment by azatsarynnyy** [comment]
There are a couple of VS Code Server startup parameters that should help to solve the problem:
- [`--install-extension`](https://github.com/che-incubator/che-code/blob/8bebcc1086a09e74a4f43c5bfb5b1867a2b36d79/code/src/vs/server/node/serverEnvironmentService.ts#L174)
- [`--force`](https://github.com/che-incubator/che-code/blob/8bebcc1086a09e74a4f43c5bfb5b1867a2b36d79/code/src/vs/server/node/serverEnvironmentService.ts#L181)

**Comment by l0rd** [comment]
In general we try to avoid adding editor-specific instructions in a Devfile because that makes the devfile less portable. A file in `.che` folder may be more adapted in this case or an environment variable in the vs code definition that can be overridden using `.che/che-editor.yaml`.

Anyway in general I would say that this should become the default behavior and that users should be able to opt out.

**Comment by l0rd** [comment]
Downstream [issue link](https://issues.redhat.com/browse/CRW-3483)

**Comment by azatsarynnyy** [comment]
Executing
```bash
bash-4.4$ /checode/checode-linux-libc/node out/server-main.js --install-extension redhat.vscode-yaml
Installing extensions...
Installing extension 'redhat.vscode-yaml'...
Extension 'redhat.vscode-yaml' v1.10.1 was successfully installed.
```
says that the extension is installed.
But actually, it is not:

![image](https://user-images.githubusercontent.com/1636395/200374551-562ebb8d-653c-4bf9-bbf5-4d459858370c.png)

Continue investigating what `--install-extension` actually does.

**Comment by jonnyczi** [comment]
@azatsarynnyy 

I've figured it out after being stuck on it for a while.

- The extensions need to be installed to `/checode/remote/extensions` using the argument `--extensions-dir`
- The installation of the extensions need to happen before che-code starts for the first time. If it happens in the wrong order it will look like the extension is working but it actually isn't.

**Comment by azatsarynnyy** [comment]
I've found there is an internal VS Code command `workbench.extensions.action.installWorkspaceRecommendedExtensions` that does everything needed for installing the recommended extensions. But it requires the `Extensions` view to be opened as it's supposed to be called from the UI.
I want to look if it's possible to introduce another command like that, but that wouldn't depend on the opened `Extensions` view. So, we could just call that command from an extension after Che-Code is started.

**Comment by jonnyczi** [comment]
@azatsarynnyy 

Thank you this is very helpful.

I was able to install some plugins such as `redhat.vscode-yaml` and have them working while VS Code is running.

Some plugins such as `PKief.material-icon-theme` being installed while VS Code is running don't work unfortunately, even after a restart. This particular plugin works if I install it before the first start of VS Code.

Installing this plugin does work when I install it though the Extensions View UI.

**Comment by azatsarynnyy** [comment]
Probably, there're some differences in how VS Code activates the extensions that are installed through the CLI and requested from UI.

**Comment by azatsarynnyy** [comment]
> Some plugins such as PKief.material-icon-theme being installed while VS Code is running don't work unfortunately, even after a restart. This particular plugin works if I install it before the first start of VS Code.

@jonnyczi just FYI: it works well for me when installing with the CLI command

**Comment by azatsarynnyy** [comment]
I updated the issue description to better describe the motivation of this work, based on the users' feedback I've got.

**Comment by azatsarynnyy** [comment]
okay, to sum up, what I've come to at this point.
It's mostly a note for myself, but probably might be useful for others as well.

While looking for a suitable solution for Che, I experimented with a few approaches. Probably, all my experiments deserve a blog post :slightly_smiling_face: 
- installing the extensions with the VS Code CLI switch `--install-extension`;
- calling the VS Code's internal commands from a VS Code extension;
- adapting VS Code's internal command or introducing a dedicated one that could be called from an extension and do all the required work;
- adapt the VS Code's internal mechanism of detecting and installing the recommendations.


**The 1st approach** I tried was reading the extensions' IDs from the `.vscode/extensions.json` file and installing all of them with the [VS Code CLI switch `--install-extension`](https://github.com/che-incubator/che-code/blob/8bebcc1086a09e74a4f43c5bfb5b1867a2b36d79/code/src/vs/server/node/serverEnvironmentService.ts#L174). While it seemed work well when testing it at the beginning, it turned out such approach might break the VS Code's mechanism of the recommendations. At least, it will conflict with the VS Code OOTB experience.
VS Code does much much more useful work related to the topic than just reading the content of the `.vscode/extensions.json` file and installing the extensions. Here are just some of the important aspects:
- VS Code workspace may be a single folder or multi-root. For multi-root, the extensions may be declared in the `.code-workspace` file. But may also be declared in individual folders as well;
- VS Code validates the extensions' IDs and tries to resolve them on a marketplace;
- VS Code checks if some extensions were not added by the user to the unwanted list to ignore and do not recommend;
- etc.

**The 2nd approach** I've described in the comment above (https://github.com/eclipse/che/issues/21701#issuecomment-1310584719). The idea was to call a couple of VS Code's internal commands from an extension to perform the same actions as the user if they agree to install the recommended extensions. The commands are:
- `workbench.extensions.action.showRecommendedExtensions`
- `workbench.extensions.action.installWorkspaceRecommendedExtensions`

The main command here is the second one. But it requires the `Extensions` view to be opened. So, we need the first one as well. The biggest challenge here is that there's no way to be notified when the view is actually opened and if there are any recommendations present.

**The 3rd idea** was to introduce a new internal command that would do the required steps (similar to `workbench.extensions.action.installWorkspaceRecommendedExtensions`) but without the dependency to an opened `Extensions` view. When I started implementing it, I better investigated the VS Code internals and found an even simpler approach (:arrow_down:).

**The 4th one**. I intercepted the VS Code's default flow of suggesting the recommendations to install and called the installation of each verified recommendation in a way that all of them are installed just after the VS Code starts. The installation process goes silently, in the background, with no interaction with the user. After the installation is finished VS Code updates the workspace storage with the special value which means the user should not be asked for installing the recommendations on the next VS Code startup.

The main advantage of the last approach is that it **preserves** the VS Code's default flow and **eliminates** any user interaction. This brings Che closer to an even more _fully ready environment for the developers_ :slightly_smiling_face: 
This new behavior will be enabled default with the possibility to opt-out in the settings.

**Comment by jonnyczi-codegiant** [comment]
This new feature for automatic installation of extensions will be very useful. I will give this a try.

@azatsarynnyy Thank you. I must have an issue with the environment I'm using to host che-code.

**Comment by jonnyczi** [comment]
This new feature for automatic installation of extensions will be very useful. I will give this a try.

@azatsarynnyy  Thank you. I must have an issue with the environment I'm using to host che-code.

**Comment by azatsarynnyy** [comment]
The feature is contributed by https://github.com/che-incubator/che-code/pull/153
and already built in the image `quay.io/che-incubator/che-code:next`.

The recommended extensions are installed silently in the background once VS Code is started.
Now, it's a default behavior that can be disabled with the `extensions.autoInstallRecommendations` setting.

**Comment by nickboldt** [comment]
building in 3.3:
* https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/code_3.3/10/
* https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.3/131/
