### ISSUE TITLE
Che should not update storage-type for existing workspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21714]
### Is your enhancement related to a problem? Please describe

When setting a storage-type using the checluster `.spec.devEnvironments.storage.pvcStrategy` field, Che attempts to apply the value to all workspaces when they are started. However, there are issues with this approach:

* If a workspace has been previously started/used, changing the storage type will result in a loss of data as a different PVC will be used for the next workspace start. Any changes made in the workspace before the storage type was changed will no longer be accessible.
* If switching from the `common`/`per-user` storage type to another, any data stored by the workspace will be orphaned on the cluster. For example, if the workspace clones 500MB of data in a repo, that 500MB will be left on the common PVC even after the workspace is deleted. It will also prevent automatic deletion of the common PVC, as that only happens when the last common/per-user DevWorkspace is deleted.
* Setting the storage type on every start prevents using a non-default storage class; if the CheCluster specifies `per-user`, then `per-user` is the only supported storage type for DevWorkspaces started by Che, and it's not possible to e.g. start an ephemeral workspace through the dashboard UI.

Normally, the DevWorkspace Operator has webhooks to prevent switching the storage-type when one of the issues above could occur. However, for compatibility, we may need to temporarily disable those webhooks to support current dashboard functionality.

### Describe the solution you'd like

The dashboard should only apply the default storage class to new workspaces as they are created. This would allow using non-default storage classes for workspaces and ensure that existing workspaces remain unchanged after updating the CheCluster storage class property. Once a workspace has been created, the storage-type defined in the Devfile should be used.

In general, since switching storage type results in losing data stored in the previous storage type anyways, the general advice should be to re-create the workspace with the new storage type from the get-go; updating existing workspaces has the same user-facing effect but also causes complications internally.

### Describe alternatives you've considered

The dashboard could attempt to follow similar heuristics to the DevWorkspace Operator to decide if it is safe to update the storage type, though these are more complicated:

* Switching from ephemeral to another storage type is permitted, as data is lost when the workspace stops anyways. However, this may not be what the user wants if they've explicitly started an ephemeral workspace.
* Switching between `""` (empty/not defined), `common` and `per-user` is permitted as these storage types use the same PVC
* Switching between storage types in general is permitted as long as the `storage.controller.devfile.io` finalizer is not present. This finalizer is added when a workspace begins using storage in the `common/per-user` and `async` cases and signifies that storage cleanup needs to be performed.

The full check is defined [here](https://github.com/devfile/devworkspace-operator/blob/55eaa3cce755e1de39388f8ce7afc9f9b93feff5/webhook/workspace/handler/workspace.go#L113-L135).

If additional information would help the dashboard use this heuristic, it can be added to the DevWorkspace Operator.

### Additional context

Related issue: https://github.com/eclipse/che/issues/21405

**Comment by l0rd** [comment]
Removing `blocker` as it's possible to start ephemeral workspaces even if this particular issue hasn't been fixed. cc @mkuznyetsov

**Comment by amisevsk** [comment]
Looking at the PR mentioned by Olexii in #21716, I think this issue can maybe also be closed by PR https://github.com/eclipse-che/che-dashboard/pull/631#pullrequestreview-1117591707

I'll try to find time to re-test, but from reading that PR it seems like at this point
* Che uses the configured PVC storage type when creating new workspaces
* It does not automatically change the storage type for existing workspaces (avoiding the issues listed in the description above)
* Users are allowed to choose a storage type different from the default, and ephemeral workspaces are available again

The only remaining piece is that individual users can change their storage types. However, this is in my opinion not an issue, as:
* The PVC storage-type selector in the dashboard is basically a wrapper around editing the attribute in the DevWorkspace, which is something the user can always do manually
* The storage-type selector features a warning that switching storage type may result in loss of data, and the action of switching storage type is performed by the user themselves rather than applied to all users without warning
