### ISSUE TITLE
It's no longer possible to use ephemeral storage for workspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21716]
### Describe the bug

It's not possible to start a workspace that uses ephemeral storage by using either the "Temporary storage" toggle when creating the workspace, or by setting the "Storage type" in the overview page. The value gets overwritten on the next workspace start using whatever is set in `.spec.devEnvironments.storage.pvcStrategy`, which has the default value of `per-user` -- i.e. it cannot be unset.

### Che version

next (development version)

### Steps to reproduce

From "Create Workspace" page:
1. Set the "Temporary Storage" toggle to on
2. Click a tile to start a workspace
3. Navigate to "Workspaces" -> name of created workspace
4. Note that storage type is "persistent", and devfile `.attributes.controller.devfile.io/storage-type` is `per-user`

### Expected behavior

Setting a workspace to use temporary storage should use the `ephemeral` storage-type.

### Runtime

OpenShift

### Screenshots

![use-temp](https://user-images.githubusercontent.com/16168279/191092662-983af0c1-b130-4ab2-bb8d-7c91aeed0d28.png)
![temp-not-set](https://user-images.githubusercontent.com/16168279/191092661-6e89f849-1e4b-456d-8e94-5e62079f70f0.png)
![2022-09-19-14:43:55](https://user-images.githubusercontent.com/16168279/191092656-785e237d-d9f3-4708-b884-af7e32e9bbb2.png)

### Installation method

chectl/next

### Environment

Linux

### Additional context

Underlying cause: https://github.com/eclipse/che/issues/21714

**Comment by olexii4** [comment]
This was fixed with https://github.com/eclipse-che/che-dashboard/pull/631

PS
These changes backported in [7.52.x](https://github.com/eclipse-che/che-dashboard/tree/7.52.x) with this PR https://github.com/eclipse-che/che-dashboard/pull/635
