### ISSUE TITLE
Not possible to deploy Theia plugins with sidecar container

### ISSUE THREAD

**Issue by davidgarcia-kairosds** [eclipse/che#21715]
### Describe the bug

I am trying to deploy a custom Theia plugin on a Che workspace. The plugin is intended to execute a task on the hosting system to generate some code. So it will ask the user for some input parameters (a REST service specification file, and a destination folder in which to generate the output), then create a system task and pass to it the parameters for execution.
The plugin has an external dependency on java, and according to the documentation I should define a sidecar container providing the external dependencies needed. However, when I add the `containers` part in the yaml, the Che workspace loads the sidecar container but _ignores completely the Theia plugin_.

### Che version

other (please specify in additional context)

### Steps to reproduce

Start a workspace from this ***devfile*** (the failing plugin is `perftestgen_plugin`, second from the end):
``` lang-yaml
apiVersion: 1.0.0
metadata:
  name: david-custom-theia-imagef6hsw
projects:
  - name: smartclide-devfiles
    source:
      location: 'https://github.com/eclipse-researchlabs/smartclide-devfiles.git'
      type: git
      branch: v0.0.9
components:
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/eclipse-researchlabs/smartclide-devfiles/test/plugins_meta.yaml'
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/eclipse-researchlabs/smartclide-devfiles/test/perfTestGen-plugin.yaml'
    alias: perftestgen_plugin
  - type: cheEditor
    reference: 'https://github.com/eclipse-researchlabs/smartclide-devfiles/raw/4bd4a0dc7a40665086c92ca5fcebd086f5e39009/editor_meta.yaml'

``` 
The plugin's ***meta.yaml***  is as follows:
``` lang-yaml
apiVersion: v2
publisher: Kairos Digital Solutions
name: smartclide-perftest-plugin
version: 0.0.3-rc6
type: Theia plugin
displayName: SmartCLIDE Performance Tests Generator
title: SmartCLIDE Performance Tests Generator Plugin
description: Che Plug-in to generate performance tests for a given OpenAPI endpoint spec.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse-researchlabs/smartclide-perftestgen-theia
firstPublicationDate: "2021-04-27"
category: Other
spec:
  containers:
    - image: quay.io/eclipse/che-java11-maven:7.32.1  
  extensions:
    - https://github.com/eclipse-researchlabs/smartclide-perftestgen-theia/releases/download/v0.0.3-rc6/smartclide_perftestgen_theia.theia
``` 

### Expected behavior

Start of sidecar container and front-end plugin at the same time. Communication between them

### Runtime

Kubernetes (vanilla)

### Installation method

other (please specify in additional context)

### Environment

Amazon

**Comment by davidgarcia-kairosds** [comment]
Hello @dkwon17, 
would it be possible to give a quick look into this? I assume you are busy and that obviously there is a procedure and things take time, but we are collaborating into an european commission project with some hard deadlines which unfortunately are quite close and this issue has us _completely blocked_.
I would really appreciate if someone could tell if there is something wrong with our devfile or with the meta.yaml file of the plugin, so that we could know for sure whether we have to change some things or it is something in the platform.

Thanks for your understanding

**Comment by dkwon17** [comment]
Hello @davidgarcia-kairosds , thank you for reporting the issue. What version of Eclipse Che did you experience this issue for?

**Comment by davidgarcia-kairosds** [comment]
Hello @dkwon17, thanks for attending this. We are using v7.32.1

**Comment by l0rd** [comment]
@davidgarcia-kairosds you are using a version of Che that is more than a year old, a lot of things have changed in the meantime and I am not sure that we will be able to help you. The recommendation would be to use a more recent version of Che. That said I have a couple of comments:
- I am not sure we support referencing Theia plugins (we only support vsix) cc @azatsarynnyy 
- If you need to get some input from the user and then execute a command, why don't you just use a devfile command?

**Comment by azatsarynnyy** [comment]
> I am not sure we support referencing Theia plugins (we only support vsix) 

According to [the plugin-registry 7.32.1 documentation](https://github.com/eclipse-che/che-plugin-registry/blob/7.32.1/README.md), referencing Theia plugins were supported.

**Comment by azatsarynnyy** [comment]
> when I add the containers part in the yaml, the Che workspace loads the sidecar container but ignores completely the Theia plugin

@davidgarcia-kairosds does that mean your Theia plugin starts successfully if you launch it in an editor container, but not in a dedicated sidecar?

**Comment by davidgarcia-kairosds** [comment]
@l0rd I have been trying with the latest RH Openshift Devspaces, but the devfile editor there is not accepting this devfile (it won't let me save the file, without error msg. There must be something somewhere, but this is another story I guess). Nevertheless, our Che version should be able to handle this script, shouldn't it? As commented earlier, this is for an EU-funded project and if possible it would be better to not force the whole project to update.
> If you need to get some input from the user and then execute a command, why don't you just use a devfile command?
aren't devfile commands intended for executing "canned" tasks? I mean, as far as I know, these commands do not allow any user interaction, they execute pre-configured actions described in the devfile. The plugin intention is to collect required user data (like where to generate the output) before executing the action. Can this be done through devfile commands?

@azatsarynnyy 

> does that mean your Theia plugin starts successfully if you launch it in an editor container, but not in a dedicated sidecar?
Yes, that's exactly the behavior. Does that ring a bell for you? Something that I could do to work around it?

**Comment by azatsarynnyy** [comment]
@davidgarcia-kairosds 

> Yes, that's exactly the behavior. Does that ring a bell for you? Something that I could do to work around it?

For me, it means that referencing Theia plugins works well in general.
Are there any suspicious logs in the sidecar? Maybe, there are some problems with the sidecar itself...

**Comment by davidgarcia-kairosds** [comment]
> Are there any suspicious logs in the sidecar?

@azatsarynnyy that's a good point. Currently I have no (known) way of getting them, I only have access to the Che dashboard. Is there any way of getting such logs through Che dashboard? Or maybe from inside the Theia instance once it loads?
I assume there is something wrong with the sidecar setup, but I am afraid I am unable to find out relevant documentation or examples on how to configure a sidecar to allow remote plugin execution in my plugin's meta.yaml, especially with the somewhat recent update to devfile v2. Maybe you know of an example I could look at?

**Comment by davidgarcia-kairosds** [comment]
@l0rd thank you very much for the suggestion, I didn't know of it. However, even using this format the problem would still persist since the command depends on something that the sidecar must provide. So, the problem here, IMHO, seems to be how to invoke a remote che-theia plugin

**Comment by azatsarynnyy** [comment]
> I am afraid I am unable to find out relevant documentation or examples on how to configure a sidecar to allow remote plugin execution in my plugin's meta.yaml

@davidgarcia-kairosds 
There are no docs publicly available for Che 7.32.1. Current docs are for 7.53 https://www.eclipse.org/che/docs/stable/overview/introduction-to-eclipse-che/

However, I've found the old docs of the downstream product Red Hat CodeReady Workspaces 2.10. It was based on Che 7.32.x. So, it may help you. Here's the link to the chapter that describes the subject we're discussing there:
https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.10/html/end-user_guide/customizing-developer-environments_crw#defining-a-launch-remote-plug-in-endpoint-using-dockerfile_crw

Also, you can look at the plugin-registry sources 7.32.1:
https://github.com/eclipse-che/che-plugin-registry/tree/7.32.1/sidecars

There're a lot of examples. One of the simplest is for `shellcheck` plugin:
https://github.com/eclipse-che/che-plugin-registry/tree/7.32.1/sidecars/shellcheck

**Comment by l0rd** [comment]
> @l0rd thank you very much for the suggestion, I didn't know of it. However, even using this format the problem would still persist since the command depends on something that the sidecar must provide. So, the problem here, IMHO, seems to be how to invoke a remote che-theia plugin

You can specify in which component of your devfile you want to execute the command:

```yaml
    actions:
      - type: exec
        component: mavencontainer  # <=== the sidecar where the command will be executed
        command: 'mvn clean install'
```

**Comment by davidgarcia-kairosds** [comment]
@l0rd @azatsarynnyy Thank you very much for all the links and info. Reviewing the samples and the docs, I added the some missing configurations in the plugin's meta.yaml (mountsources + args for executing the plugin entrypoint) and apparently something happened since at least now the theia instance is effectively trying to launch my plugin while the sidecar is also running. So small step ahead, yay!
However now I get the following error message:
```
Activating extension 'smartclide-perftestgen-theia' failed: Cannot find module '@theia/plugin' Require stack: 
- /tmp/theia-unpacked/Kairos Digital Solutions.smartclide-perftest-plugin.latest.awefncvxnj.smartclide_perftestgen_theia.t/lib/perfTestGen-backend.js 
- /remote-endpoint/node_modules/@theia/core/lib/node/dynamic-require.js 
- /remote-endpoint/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js 
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote-init.js 
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js
```
I have tried mounting volumes in the sidecar with the theia instance and the plugins folder but no way. In the documentation does not mention (or at least I haven't seen it) needing anything else apart from the entrypoint commands.
Any ideas...?

**Comment by azatsarynnyy** [comment]
@davidgarcia-kairosds I'm glad you were able to move a bit forward with running your extension in a sidecar.
Regarding `Cannot find module `@theia/plugin`, if the `@theia/plugin` dependency is declared as `devDependencies` try to declare it as a regular one.

**Comment by davidgarcia-kairosds** [comment]
Hi @azatsarynnyy I found out there is an interference somehow with the configuration we have for the theia frontend itself which actually causes the `Cannot find module @theia/plugin` issue. So I took my plugin into a completely new, empty workspace where the only plugin referenced is mine, and there the plugin loads just fine.
So I would say this issue can be closed since there really is no bug. However, before closing the thing, I would like to ask a final question (please tell me if I should place it in a separate issue or maybe in a different forum):
- when executing my plugin, I am now getting an error saying `Task has exited with code 127.` which apparently means that the executable I want to invoke (java) is not there. I know for sure that my sidecar is in place (theia allows me to open a terminal to it) and that it contains everything needed to run. In fact, if I manually execute the command on that terminal, the execution is successful. This can only mean that the task I programmatically generate in my plugin is not being executed on the sidecar. @l0rd mentioned that on the devfile I can configure on what component (i.e. sidecar) a command will be executed. Is there a way of specifying that for a theia task?
- is there any way to execute a shell command on a sidecar container?

Again, thank you for your attention and support!

**Comment by azatsarynnyy** [comment]
> when executing my plugin, I am now getting an error saying Task has exited with code 127.

@davidgarcia-kairosds 
Most likely, it's because the task is executed in the main theia container, but not in the sidecar.
You can specify a sidecar in the command definition in your Devfile. See [the examples here](https://github.com/eclipse-che/che-devfile-registry/blob/c438555edaef528891ee93ed79d510e455961ae7/devfiles/go/devfile.yaml#L46).
Note, the `component` propery corresponds to [the component's `alias`](https://github.com/eclipse-che/che-devfile-registry/blob/c438555edaef528891ee93ed79d510e455961ae7/devfiles/go/devfile.yaml#L32).
