### ISSUE TITLE
Error provisioning storage: configured storage type not supported

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21729]
### Describe the bug

Error provisioning storage: configured storage type not supported

### Che version

7.53@latest

### Steps to reproduce

1. Deploy Eclipse Che 7.54.0 on OpenShift cluster
2. Try start a workspace

### Expected behavior

Workspace is up and running

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

The latest available DevWorkspace version is `0.15.2` but must be `0.16.0`

**Comment by amisevsk** [comment]
Potentially still an issue in Che due to https://github.com/eclipse/che/issues/21766

**Comment by ibuziuk** [comment]
closing since 0.16.0 has been released (both upstream and downstream)
