### ISSUE TITLE
Che-Code's PR check doesn't comment on a PR when the image is built

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21723]
### Is your task related to a problem? Please describe

There's a PR check in the Che-Code repository that is supposed to build the images with the PR changes:
https://github.com/che-incubator/che-code/blob/main/.github/workflows/pr-check-image-publish.yml

It used to comment on a PR once the changes are built and published to quay, e.g.:
https://github.com/che-incubator/che-code/pull/90#issuecomment-1206706509

Currently, not all the steps work as expected:
https://github.com/che-incubator/che-code/actions/runs/3283453882/jobs/5408188099

### Describe the solution you'd like

Need to investigate what causes the error in the GitHub Workflow.

### Describe alternatives you've considered

As a workaround, it's possible to wait for passing all the checks on a PR and looking at
https://quay.io/repository/che-incubator-pull-requests/che-code?tab=tags
to check if the test image is already published.

**Comment by azatsarynnyy** [comment]
The page when the Workflow started failing: https://github.com/che-incubator/che-code/actions/workflows/pr-check-image-publish.yml?page=7

Unfortunately, the logs of these jobs aren't available anymore. But I remember last time when I was investigating it, I noticed a suspicious change in the `dev-image.zip` image size, on the `Download dev image` step:

![image](https://user-images.githubusercontent.com/1636395/197164447-ccbb82ad-de96-426d-8771-fc97bf14b559.png)

The last time, the Workflow finished successfully, the image size was significantly smaller compared to the size when the Workflow started failing continuously:

![image](https://user-images.githubusercontent.com/1636395/197165194-3240fd74-c446-40ea-ae0d-2029517ef71e.png)

**Comment by RomanNikitenko** [comment]
I enabled debug logging and found the following:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/5676062/197717071-919a8ece-ae91-4be0-9eea-5bd7f5d64979.png">

It looks like there isn’t enough memory for the command execution: `docker load -i dev-pr.tgz`.

I think we could try to pass `--memory-swap` key for the command to resolve the problem.

**Comment by RomanNikitenko** [comment]
The problem was fixed - the corresponding image was published and there was a comment about it: https://github.com/che-incubator/che-code/pull/139#issuecomment-1297195065
