### ISSUE TITLE
che-theia generator is not working properly

### ISSUE THREAD

**Issue by cj-rajat** [eclipse/che#21726]
I am using che-theia generator to create che-theia over a base theia-ide. When I run che-theia init command in root directory of theia repo. Generator adds some packages and plugins. In plugins I found a [issue](https://github.com/eclipse-che/che-theia/blob/main/plugins/workspace-plugin/package.json) , here in extensionDependencies it is using "Eclipse Che.@eclipse-che/theia-ssh-plugin" and "@eclipse-che.ext-plugin", but these plugins does not exit at all, the correct package name is "@eclipse-che/theia-ssh-plugin" and "@eclipse-che.ext-plugin". Due to this plugins are not able to run and I am getting error extension dependencies that can't be resolved.
Also when I run yarn in root directory of theia(version-> 1.29.0), I am getting typescript errors. please update the generator code that is compatible with the typescript version of theia.

**Comment by azatsarynnyy** [comment]
@rajattyagi200 currently, Che-Theia isn't adapted to the latest Theia. So, make sure Eclipse Theia is checked out to a specific commit SHA 
https://github.com/eclipse-che/che-theia/blob/8bef58f2223607312e09d7cca62d6df0c00f0ca6/build.include#L17
before running the Che-Theia generator.

Also, please find the mentioned plugins:
`@eclipse-che/theia-ssh-plugin` https://github.com/eclipse-che/che-theia/blob/main/plugins/ssh-plugin/package.json
`@eclipse-che.ext-plugin` https://github.com/eclipse-che/che-theia/blob/main/plugins/ext-plugin/package.json
