### ISSUE TITLE
Add autocomplete for oc and kubectl in UDI image

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21735]
### Is your enhancement related to a problem? Please describe

When starting a workspace that uses the universal developer image, I'm able to open a terminal and use `oc` and `kubectl` to interact with the cluster. However, autocomplete is not available for these commands, making it tedious to use them.

### Describe the solution you'd like

1. Install `bash-completion` and related packages in the UDI image
2. Add entries for `oc` and `kubectl` autocomplete

### Additional context

The [`web-terminal-tooling` container](https://github.com/redhat-developer/web-terminal-tooling/blob/main/build/template.Dockerfile) supports autocomplete, as an example.

**Comment by AObuchow** [comment]
The oc completion side of this task was resolved in https://github.com/devfile/developer-images/pull/88, but the kubectl autocompletion is still missing.
