### ISSUE TITLE
Use DevWorkspace Operator contributions attributes to inject editors into Devfile containers

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21738]
### Is your enhancement related to a problem? Please describe

Currently, the dashboard uses a library to inject editors into devfiles, which results in modifying the original devfile in the process of converting it into a DevWorkspace. DevWorkspace Operator PR https://github.com/devfile/devworkspace-operator/pull/844 adds attributes on components that hopefully remove the need for this process:
* `controller.devfile.io/container-contribution: true` defines a container component as a "container contribution"
* `controller.devfile.io/merge-contribution: true` defines a container as a target for merging a "container contribution"

When present, these attributes define a component as a "contribution" that gets merged into the target, replicating the process performed by the dashboard in a (hopefully) simpler way. See details on original PR for how this works.

### Describe the solution you'd like

1. Apply `controller.devfile.io/merge-contribution: true` attribute to the Devfile component we currently inject editors into (e.g. `tools`)
2. Deprecate dashboard-side injection of editors into workspace components, leaving Devfile-defined components unchanged when converting to DevWorkspace

### Describe alternatives you've considered

It may be possible to do the steps above separately, i.e. begin adding the attribute but continuing to use the merge functionality as well. This would need to be tested but would reduce the coordination necessary between registries/dashboard/DWO to make everything work as intended without breaking an edge case.

### Additional context

Relevant DWO PRs: 
* https://github.com/devfile/devworkspace-operator/pull/844
* https://github.com/devfile/devworkspace-operator/pull/939

This issue is part of https://github.com/eclipse/che/issues/21736

**Comment by svor** [comment]
@olexii4 I think you can reuse [che-devworkspace-generator](https://www.npmjs.com/package/@eclipse-che/che-devworkspace-generator/) npm library to prepare DevWorkspaces with container contributions attributes as i was done in the [che-devfile registry](https://github.com/eclipse-che/che-devfile-registry/blob/main/build/scripts/generate_devworkspace_templates.sh#L25-L41)

**Comment by svor** [comment]
Probably it's not finished yet

**Comment by nickboldt** [comment]
did all the changes to che-plugin-reg upstream get ported downstream fork too? Not seeing matching changes in https://github.com/redhat-developer/devspaces/commits/devspaces-3-rhel-8/dependencies/che-plugin-registry ...

please throw PRs at that repo and if no one is responding, ping in Slack for more 👀
