### ISSUE TITLE
[epic] Begin using DevWorkspace Operator container contributions functionality

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21736]
### Is your enhancement related to a problem? Please describe

DevWorkspace Operator PRs
* https://github.com/devfile/devworkspace-operator/pull/844
* https://github.com/devfile/devworkspace-operator/pull/939
Add a new field to DevWorkspaces and functionality to allow automatic merging of components in a DevWorkspace. This issue is to track the semi-coordinated work required across the dashboard and devfile registry to begin using this feature in DWO.

### Describe the solution you'd like

The following tasks need to be semi-coordinated between dashboard and devfile registry. In addition, these changes should wait until the next DevWorkspace Operator release to ensure the functionality is available on the DWO side. DevWorkspace Operator v0.17.0 will be the first release to include `.spec.contributions` and the merge functionality.

- #21737
- #21739
- #21738
- #21832
- #21837
- #21878

**Comment by azatsarynnyy** [comment]
added the sub-task #21837

**Comment by l0rd** [comment]
added sub-task #21878

**Comment by l0rd** [comment]
Closing as complete
