### ISSUE TITLE
Eclipse che on Plain Kubernetes - Is it possible if so, detailed steps required. Minikube is NOT ideal 

### ISSUE THREAD

**Issue by ShravanAmrita** [eclipse/che#21743]
### Summary

Eclipse che on Plain Kubernetes - Is it possible if so, detailed steps required. Minikube is NOT ideal

**Comment by davidxwwang** [comment]
@pwillis-eiq hi, can you give some tips how to deploy che on Plain Kubernetes，l  also encounter such dilemma. thanks a lot.
