### ISSUE TITLE
How to Install Eclipse Che 7 on EKS cluster with Azure Ad as OIDC

### ISSUE THREAD

**Issue by abhijeetka** [eclipse/che#21749]
### Summary

I am looking for Eclipse Che Installation Instructions on Amazon EKS cluster with Azure AD configured as OIDC provider.
Since the change in Eclipse che has pushed us to update it. Our production is failing.

We need support on Installing Eclipse Che on EKS with Azure ad as OIDC provider. We also tried to check the documentation, earlier there was a section to target installation on different Cloud providers. But now it is removed.

Any help would be appreciated.

### Relevant information

Eclipse Che Version: 7.54.0

**Comment by ibuziuk** [comment]
Hello, we had a great article from the community about installing Eclipse Che on the Azure Kubernetes Service that should be very helpful - https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html

In the article above Azure Kubernetes Service AAD Server is used as the OIDC provider. 

> We also tried to check the documentation, earlier there was a section to target installation on different Cloud providers. But now it is removed.

I believe this is a great chance for the community to kick in and provide the relevant docs for various cloud and OIDC providers. The main reason why we do not have those docs is the fact that Setting up Users' Authentication is required for deploying Che on Kubernetes infrastructures which can vary - https://kubernetes.io/docs/reference/access-authn-authz/authentication/

PRs to the docs and blog post from the community are most welcome
