### ISSUE TITLE
Testing Git zero-config flow as PR checks

### ISSUE THREAD

**Issue by svor** [eclipse/che#21753]
### Is your task related to a problem? Please describe

As a result of https://github.com/eclipse/che/issues/20583, we've added a support for many git services (GitHub, BitBucket, GitLab)
It would be good to test the existing git flow as much as possible. 

### Describe the solution you'd like

Unit Test:
- [x]  Add unit tests into che-server to cover git providers functionality

Add instructions how to prepare Git servers to work with Che, it could be a part of https://github.com/eclipse-che/che-server repository or a new repo in https://github.com/che-incubator:

- [x] BitBucket server (need to verify instructions described in https://github.com/skabashnyuk/gitsrv/tree/main/bitbucket)
- [x] GitLab server
- [x] GitHub server 

Add GitHub action to get `che-server` image with a current PR number:
- [x] Build and pull `che-server` image to `quay.io/repository/eclipse/che-server` with a curent PR number

Configure OpenShift CI infrastructure to run git functional tests as PR check:
- tests without PAT/OAuth setup flow:
- [x] Bitbucket.org
- [x] GitHub.com
- [x] GitLab.com

- tests with PAT setup flow
- [x] GitHub.com
- [x] GitLab.com

**Comment by dmytro-ndp** [comment]
@svor, @vinokurig : there is downstream repo with working bitbucket server automation: https://gitlab.cee.redhat.com/codeready-workspaces/git-servers/-/tree/main/bitbucket

**Comment by svor** [comment]
Thanks @dmytro-ndp for the links!

**Comment by l0rd** [comment]
This is useful for contributors so my proposal is to add the link in a section of [the contributing.md](https://github.com/eclipse/che/blob/main/CONTRIBUTING.md).

**Comment by vinokurig** [comment]
While investigating the GitHub action test flow I've faced a problem:
The initial idea is to send a Che API request and check the result. The Che Api is available only through the oAuth step. In case of Openshift it is the [OpenShift oauth-proxy](https://github.com/openshift/oauth-proxy#oauth2_proxy) and in case of minikube it is Dax. So when I request Che API directly by curl it returns an authorisation html. So I don't see a way how to make an API request to Che to test the Che oAuth flow without using UI.

**Comment by artaleks9** [comment]
* I think, this issue can be closed considering to merged  PR's, see above.
* I'll create another issue where try to implement setup git provider/s OAuth to expand exist tests for Git-zero flow.
