### ISSUE TITLE
Fail to clone git repository if `githost` is omitted in `che-git-self-signed-cert` ConfigMap

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21754]
### Describe the bug

In [docs we mention](https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/):

> When githost is not specified, the given certificate is used for all HTTPS repositories

But when trying this out, the git clone fails. The resulting `gitconfig` has a section `[http ""]`:

```
[http ""]
sslCAInfo = /etc/che/git/cert/ca.crt
```

### Che version

next (development version)

### Steps to reproduce

Deploy Che and create a [`che-git-self-signed-cert` secret without githost](https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/) that points to a git server using an untrusted TLS certificate.

I have tested with DevSpaces 3.3 on OCP 4.10

### Expected behavior

The gitconfig should have an `[http]` section rather than `[http ""]`:

```
[http]
sslCAInfo = /etc/che/git/cert/ca.crt
```

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Release Notes Text

When a git service uses a self-signed TLS certificate and Eclipse Che is configured to trust that certificate but the `che-git-self-signed-cert` doesn't include a githost section, workspaces creation failed. This has been fixed in current release.

**Comment by max-cx** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-3622
