### ISSUE TITLE
tolerations and nodeSelector annotations not added to namespace

### ISSUE THREAD

**Issue by xfreeg0** [eclipse/che#21755]
### Describe the bug

We added to CheServer CRD the Nodeselector and Pod Tolerations specifications:

workspacePodNodeSelector:
  load-type: che-worker
workspacePodTolerations:
  - effect: NoSchedule
    key: workspace-taint
    operator: Exists

and then we call the Che api to create user's namespace:

/api/kubernetes/namespace/provision

the resultant namespace not have the annotations used by devworkspace operator to propagate informations to relative Deployment and Pod specification: 

controller.devfile.io/node-selector: '{"load-type":"che-worker"}'
controller.devfile.io/pod-tolerations: '[{"key":"workspace-taint","operator":"Exists","effect":"NoSchedule"}]'

if we call API consecutively for 2 times :

/api/kubernetes/namespace/provision
/api/kubernetes/namespace/provision

all works a expected

### Che version

7.49

### Steps to reproduce

1. Define nodeselector or tolerations in CheServer CRD
2. Call api "/api/kubernetes/namespace/provision"
3. Check created namespace

### Expected behavior

The user's namespace created with api:

must have the annotations:

controller.devfile.io/node-selector: '{"load-type":"che-worker"}'
controller.devfile.io/pod-tolerations: '[{"key":"workspace-taint","operator":"Exists","effect":"NoSchedule"}]'

defined in CheServer CRD

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Amazon

### Additional context

Installation Method: che-operator
Runtime: AWS EKS

**Comment by tolusha** [comment]
@xfreeg0 
Should be fixed in 7.52.0 by https://github.com/eclipse-che/che-operator/pull/1473
