### ISSUE TITLE
Update GH actions to use Node 16 tasks

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21763]
### Is your task related to a problem? Please describe

```
Node.js 12 actions are deprecated. For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: 
actions/checkout, docker/login-action, docker/login-action, actions/setup-python, 
actions/setup-java, actions/setup-java, actions/setup-python, docker/login-action, 
docker/login-action, actions/checkout
```
-- https://github.com/eclipse-che/che-release/actions/runs/3233426139

So, anywhere we have GHA scripts that use old versions of the above actions, we should update to the latst node16 based versions.

* eclipse/che* repos
* eclipse-che/* repos
* che-incubator/* repos
* che-release repo
* etc.

### Describe the solution you'd like

So, anywherer we have GHA scripts that use old versions of the above actions, we should update to the latst node16 based versions.

### Additional context

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by SDawley** [comment]
Ongoing list of actions that I've found could not be updated because they don't have a node16 version:

- https://github.com/che-incubator/setup-minikube-action
- https://github.com/che-incubator/che-deploy-action
- https://github.com/che-incubator/happy-path-tests-action
- mattermost/action-mattermost-notify
- https://github.com/redhat-actions/try-in-web-ide

**Comment by nickboldt** [comment]
Seems that after this update, some taks require additional configuration:

* actions/setup-java@v3 - requires a `distribution: adopt`
* actions/setup-python@v3 - no longer works with python 3.6 (so switch to 3.9)

**Comment by nickboldt** [comment]
PRs:
* https://github.com/eclipse-che/che-server/pull/413
* https://github.com/eclipse-che/che-operator/pull/1591
* https://github.com/eclipse/che/pull/21910

Note that some Che projects uses Temurin and some use Adopt. Not sure why the discrepancy, but here we are.

**Comment by SDawley** [comment]
I think every repo has been updated now, closing.

**Comment by azatsarynnyy** [comment]
and one more https://github.com/che-incubator/che-code/pull/175 :wink:
