### ISSUE TITLE
Install DevWorkspace Operator catalog when deploying stable Che version with chectl

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21766]
### Is your enhancement related to a problem? Please describe

When installing Che `next`, chectl will install the `next` DevWorkspace Operator catalog and install the DevWorkspace Operator from there before installing the Che Operator. This means that both the Che and DevWorkspace Operators use the expected `next` version. 

However, when installing the stable version of Che, chectl will install the DevWorkspace Operator from the OperatorHub catalog instead. This can cause issues as the DevWorkspace Operator version in the default catalog may not be the latest released upstream (e.g. DWO 0.16.0 was released 23 days ago and is still not available in OperatorHub). 

This can cause issues such as https://github.com/eclipse/che/issues/21710, where the released version of Che expects a certain version of the DevWorkspace Operator.

### Describe the solution you'd like

`chectl` should always install the DevWorkspace Operator from upstream sources. This means

* When installing Che `next`, chectl should create a catalogsource using `quay.io/devfile/devworkspace-operator-index:next` and a subscription for the DevWorkspace Operator using that catalogsource (*this is the current functionality*)
* When installing Che `stable`, chectl should create a catalogsource using `quay.io/devfile/devworkspace-operator-index:release` and install the DevWorkspace Operator using that catalogsource (this would be new functionality)

**Comment by tolusha** [comment]
I checked, chectl installs upstream version of DWO for a stable Eclipse Che version
![screenshot-console-openshift-console apps ci-ln-9ky8m3k-76ef8 aws-2 ci openshift org-2022 10 14-10_45_37](https://user-images.githubusercontent.com/1640675/195791784-c1e01f97-fa88-4c81-93e1-3aa2be91677d.png)

**Comment by amisevsk** [comment]
Hmm I'll recheck again today.

**Comment by tolusha** [comment]
Do you think we can close the issue?

**Comment by amisevsk** [comment]
Yup, just verified. I don't know what went wrong earlier.
