### ISSUE TITLE
Running `chectl` update makes it impossible to have two versions of chectl installed

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21767]
### Describe the bug

Running `chectl update` installs the updated version of chectl to `~/.local/share/chectl`. It appears that if chectl is available from this directory, it is always used regardless of the directory chectl has been manually installed to, breaking the use case of having both `next` and `stable` channels installed. 

I generally run chectl `next` installed manually to aid in testing changes in Che while developing. Today I needed to test behavior of chectl stable, so I manually installed the chectl stable release as documented to `~/bin/chectl-stable/`:
1. Download tar for 7.55.0 release
2. Extract to `~/bin/chectl-stable`
3. Add alias `chectl=~/bin/chectl-stable/bin/chectl`

After doing this, running `chectl version` shows the `next` version that had been installed previously; it is impossible to run chectl 7.55.0 in this state.

To fix this, I had to figure out, on my own, that I needed to delete `~/.local/share/chectl` in order to make chectl work as expected. It's very strange to set an alias/path up only to have the binary execute from a completely different, hidden directory. 

### Che version

7.55@latest

### Steps to reproduce

Assuming chectl is not currently installed, the following script reproduces the issue
```bash
#!/bin/bash
shopt -s expand_aliases

# Install chectl 7.53.0 to temporary directory
cd $(mktemp -d)
wget -q https://github.com/che-incubator/chectl/releases/download/7.53.0/chectl-linux-x64.tar.gz
tar -xf chectl-linux-x64.tar.gz
alias chectl-stable=$(pwd)/chectl/bin/chectl

# Install older version of chectl `next` to temporary directory
cd $(mktemp -d)
wget -q https://github.com/che-incubator/chectl/releases/download/20220928063245/chectl-linux-x64.tar.gz
tar -xf chectl-linux-x64.tar.gz
alias chectl-next=$(pwd)/chectl/bin/chectl

# Check that we can use both versions:
echo "Version of chectl-stable is: $(chectl-stable version)"
echo "Version of chectl-next is: $(chectl-next version)"

# Update chectl-next (alternatively, update chectl-stable for the same result)
chectl-next update

# Versions are now both `next`
echo "Version of chectl-stable is: $(chectl-stable version)"
echo "Version of chectl-next is: $(chectl-next version)"
```
Output is 
```
Version of chectl-stable is: chectl/7.53.0 linux-x64 node-v16.13.2
Version of chectl-next is: chectl/0.0.20220928-next.212880a linux-x64 node-v16.13.2
chectl: Updating CLI from 0.0.20220928-next.212880a to 0.0.20221012-next.a3df1c3 (next)... done
chectl: Updating CLI... done
Version of chectl-stable is: chectl/0.0.20221012-next.a3df1c3 linux-x64 node-v16.13.2
Version of chectl-next is: chectl/0.0.20221012-next.a3df1c3 linux-x64 node-v16.13.2
```

### Expected behavior

It should at least be possible to run `stable` and `next` chectl on the same machine. Ideally, manually installing to a particular directory doesn't behave confusingly by also installing chectl to `~/.local/share`.

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by tolusha** [comment]
There is an easier way to switch between versions:
* `chectl update` - updates chectl for a current channel
* `chectl update next` - updates and switches to a next channel
* `chectl update stable` - updates and switches to a stable channel
* `chectl udpate --from-local` - updates from a local copy

I hope this solves the issue.
