### ISSUE TITLE
Update Theia image to the newer version

### ISSUE THREAD

**Issue by william-xiang** [eclipse/che#21777]
The latest `che-theia 7.55.0` still uses `theia 1.18` which was released last year. While we use it, we found some bugs in that version of theia and already fixed in the newer versions. 
It would be better to get a new theia.

**Comment by azatsarynnyy** [comment]
Please, find the related info in https://www.eclipse.org/lists/che-dev/msg04439.html and https://github.com/eclipse/che/issues/21771
