### ISSUE TITLE
Setting CRD Scope: Cluster

### ISSUE THREAD

**Issue by ArvinB** [eclipse/che#21786]
### Summary

Can we change the scope for the `che-operator` CRD to be `Cluster`?

### Relevant information

" If cluster-scoped RBAC resources are used for namespace-scoped operators, then the operator will run with more privileges than it needs." Basically, since the Operator is installed into All-namespaces with Cluster Permissions, then really the CRD should be scoped to be `Cluster`. Right?

**CRD Scope**
https://github.com/eclipse-che/che-operator/blob/main/bundle/next/eclipse-che-preview-openshift/manifests/org.eclipse.che_checlusters.yaml#L43

**CSV Cluster Permissions**
https://github.com/eclipse-che/che-operator/blob/main/bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L492

**CSV All Namespaces**
https://github.com/eclipse-che/che-operator/blob/main/bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L1221-L1222

@benoitf @nickboldt FYI

**Comment by ArvinB** [comment]
@tolusha Thanks for the comment. What are the next steps to perhaps consider making such a change?

**Comment by amisevsk** [comment]
It's not possible to switch an existing CRD's scope, it would have to be an entirely new CRD (that potentially manages existing CheCluster CRDs).

While CheClusters are namespace-scoped and only operate in a single namespace, the operator still requires cluster-wide permissions as it manages networking for DevWorkspaces, which appear in multiple namespaces. The benefit of having the Che installation CRD being cluster scoped would be easier discoverability (you don't need to know the namespace) and potentially simpler management of installs (you don't have to worry about creating two CheClusters by accident), but permissions-wise, not a lot would change.

**Comment by ArvinB** [comment]
@amisevsk The permissions for the operator are required at a cluster scope level. So, is there a migration that we can do to make the CRD cluster scoped as well? You have pointed out the benefits of this, which is exactly why I am bringing this up to see if we can move things in this direction for consistency and simpler management. Perhaps we may have a pain point during the transition where it is not backwards compatible?

What do you think of the feasibility here?

**Comment by ArvinB** [comment]
Thanks for the clear explanation. I am going to close this, since my question has been answered.

Just an FYI, by default the Operator SDK generates artifacts that are namespace scoped. Meaning that in the CSV permissions are not cluster wide and uses Roles/RoleBindings by default (as you mentioned these would need to change). The Eclipse Che Operator is setting permissions outside its namespace and has for a while. Recently the install mode has moved to be installed in `All Namespaces`, further solidifying it's requirement for Cluster scoped permissions. This is what I was trying to communicate.

Reference: https://github.com/eclipse-che/che-operator/blob/main/bundle/next/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L492
