### ISSUE TITLE
Outdated instructions for deploying Che-Operator via Make in Che-Operator README

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#21784]
### Describe the bug

In the README for Che-Operator, it [mentions](https://github.com/eclipse-che/che-operator#deploy-che-operator-using-make) that you can deploy Che-Operator using `make deploy ...` however, there's no recipe called `deploy`.

```bash
$ make help | grep "deploy"
  gen-deployment             Generate Eclipse Che k8s deployment resources
  update-helmcharts          Update Helm Charts based on deployment resources
  gen-chectl-tmpl            Generate Eclipse Che k8s deployment resources used by chectl
```
It seems the recipe was removed [here](https://github.com/eclipse-che/che-operator/commit/0bc10490177c5d90867459e52ee7e1686cb97ff2#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L204) 

I have just been using chectl to deploy che-operator, but it would probably be best to either remove the mention of using make to deploy che-operator, or to re-add the recipe. 

### Che version

next (development version)

### Steps to reproduce

Follow the instructions for deploying via Make:

```bash
$ make deploy IMG=\"${IMAGE_REGISTRY_HOST}/${IMAGE_REGISTRY_USER_NAME}/che-operator:next\"
$ kubectl apply -f config/samples/org_v2_checluster.yaml -n eclipse-che
error: unable to recognize "config/samples/org_v2_checluster.yaml": no matches for kind "CheCluster" in version "org.eclipse.che/v2"
```

### Expected behavior

Your image of Che-operator is deployed to your cluster.

### Runtime

minikube

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse-che/che-operator/pull/1552
