### ISSUE TITLE
Add Che Smoke Test PR check for Che-Code repository

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21789]
### Is your task related to a problem? Please describe

Currently, there're PR checks in the Che-Code repository that run the upstream tests. But there's no PR check that would run the Happy Path tests for testing Che-specific functionality. So, the developer needs to check by hand if they didn't break anything Che-specific.

### Describe the solution you'd like

Need to add a PR check that would run Happy Path Tests against the opened PR. It should be a required check to prevent merging the code introduces some regression.

### Additional context
- #22031

**Comment by dmytro-ndp** [comment]
@azatsarynnyy : there is a plan to switch existed Che-Theia Happy path tests to VS Code Editor using https://github.com/redhat-developer/vscode-extension-tester library: https://github.com/eclipse/che/issues/21463

PR: https://github.com/eclipse/che/pull/21684

**Comment by dmytro-ndp** [comment]
There is Che-Code editor smoke test available for running: https://github.com/eclipse/che/blob/main/tests/e2e/specs/SmokeTest.spec.ts

Here an example of usage: https://github.com/eclipse-che/che-operator/blob/main/build/scripts/oc-tests/oc-test-happy-path.sh
(just need to replace EmptyWorkspace with SmokeTest)

**Comment by dmytro-ndp** [comment]
https://github.com/eclipse-che/che-operator/blob/main/build/scripts/oc-tests/oc-test-happy-path.sh is the script to run smoke test on [OpenShift CI](https://prow.ci.openshift.org/) - an alternative to GitHub Actions where minikube is available for deploy Eclipse Che to only. 

There is also GitHub Action to deploy Eclipse Che to minikube, but I am not sure if there is enough resources in there to start Eclipse Che workspace with VS Code Editor on board.
