### ISSUE TITLE
Error "operation is insecure" raised when trying to preview a markdown file in VS Code

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21782]
### Describe the bug

The following error is shown when trying to open a Markdown file

<img width="620" alt="image" src="https://user-images.githubusercontent.com/606959/197609906-a868c823-54c9-4d01-9e78-9a4ee512d207.png">

### Che version

next (development version)

### Steps to reproduce

I am using the dogfooding instance.
Open a project that includes a markdown file using a factory link.
Open the markdown file and click on the preview icon:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/606959/197729771-69e8905d-1c53-4fc0-8525-546e4335cb77.png">

### Expected behavior

See the html rendered markdown version of the file I am editing.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

**Comment by l0rd** [comment]
cc @azatsarynnyy

**Comment by l0rd** [comment]
Setting `> Markdown > Change Preview Settings Security > Disable` doesn't seem to help:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/606959/197731304-244371b8-cdd5-47bd-a141-a5c0d8dc87e3.png">

**Comment by azatsarynnyy** [comment]
@l0rd could you attach some test project to reproduce the issue? Maybe there's some specific content that can't be rendered.
As it is not reproduced for any markdown file.
![md](https://user-images.githubusercontent.com/1636395/197811843-1f9c3db4-c8ab-4eda-a98b-71660c017bee.gif)

**Comment by l0rd** [comment]
I was able to reproduce it on 3 different repos I have opened today:

- [cri-o](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/cri-o/cri-o)
- [devspaces-demo](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/che-incubator/devspaces-demo)
- [docker-hello](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/dockerfile-hello-world)
![markdow-preview-insecure](https://user-images.githubusercontent.com/606959/197887677-77a05a1d-31bd-4006-acec-bc198b3db341.gif)

**Comment by l0rd** [comment]
I am using Firefox.

**Comment by l0rd** [comment]
I am reducing the severity considered that it's only reproducible on Firefox on a mac (or maybe it's the version? Mine is different from Artem's and it is version 102.04.0esr).

**Comment by RomanNikitenko** [comment]
About version - I use the following:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/5676062/199498863-469d5a2e-5929-48b9-9706-2b5ef20e7ba7.png">

**Comment by azatsarynnyy** [comment]
Thank you @RomanNikitenko for verifying the issue on Mac.

**Comment by RomanNikitenko** [comment]
Today I checked it for the `Codespaces`- the issue is not actual for the `Codespaces`.
But now I can not reproduce the problem for the `Che-Code` on the `dogfooding` instance as well.

So, maybe it was fixed recently in the upstream.
But it would be nice if someone could double-check it to confirm.

**Comment by azatsarynnyy** [comment]
> So, maybe it was fixed recently in the upstream.

I see there were several WebView-related patches upstream last week.

@l0rd could you please recheck it to confirm if the issue is still relevant for you?

**Comment by azatsarynnyy** [comment]
https://github.com/eclipse/che/issues/21852#issuecomment-1333509295
