### ISSUE TITLE
Che-Code shouldn't suggests updating the built-in extensions

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21787]
### Is your task related to a problem? Please describe

When the user launches Che-Code, it always includes the same versions of all the VS Code built-ins - `v1.0.0`. E.g.:

![image](https://user-images.githubusercontent.com/1636395/198209605-aaff0aee-a580-40ff-a41f-35edb2a10560.png)

So, Che-Code suggests the user update the built-ins:

![image](https://user-images.githubusercontent.com/1636395/198216226-e40677a7-499c-431e-a261-410497d7e44d.png)

The **updated** extensions are version `v1.64.0-next.68976705968`:

![image](https://user-images.githubusercontent.com/1636395/198244616-961ec3f5-9814-4822-9756-95b881073540.png)

See more details at the https://github.com/eclipse/che/issues/21787#issuecomment-1310553820 below.

### Describe the solution you'd like

Need to figure out how we can include the latest versions of the VS Code built-ins into Che-Code without suggesting the user update all the extensions.

### Additional context

Note, that VS Code (Electron) includes the built-ins of version `v1.0.0` and doesn't suggest the user update it.
![image](https://user-images.githubusercontent.com/1636395/198221461-d01cee27-bc63-429a-a6a3-8bafa4f4276e.png)

**Comment by azatsarynnyy** [comment]
Sharing some of my findings, related to the topic of this issue, I've noticed while investigating [another issue](https://github.com/eclipse/che/issues/21701).
VS Code is running with the built-in extensions bundled with the sources: https://github.com/che-incubator/che-code/tree/main/code/extensions. In the running container, they can be found in the folder `/checode/checode-linux-libc/extensions`.
VS Code starts checking for the latest versions of the built-ins available on the OpenVSX registry. As the bundled extensions have versions like `1.0.0`, VS Code tries to install them from the OpenVSX registry since they have a higher version, e.g.: `1.64.0-next.68976705968`. It installs the downloaded extensions into `/checode/remote/extensions` folder. It's computed based on:
- https://github.com/che-incubator/che-code/blob/24fe02b97f9eeb829a489e9d5c10f96c424fa3a0/build/scripts/entrypoint-volume.sh#L42
- and https://github.com/che-incubator/che-code/blob/24fe02b97f9eeb829a489e9d5c10f96c424fa3a0/code/src/vs/server/node/server.main.ts#L49.

I believe the best option would be to disable checking for the built-in extensions updates.
If it's not possible, we can disable it for all extensions:

![image](https://user-images.githubusercontent.com/1636395/200850183-a0037dd3-85b8-491f-8e9d-65829a08f570.png)

**Comment by RomanNikitenko** [comment]
I'm not able to reproduce the issue anymore on the `dogfooding` instance...

**Comment by azatsarynnyy** [comment]
I've just found there is a closed OpenVSX issue https://github.com/eclipse/openvsx/issues/446 that was fixed by https://github.com/eclipse/openvsx/pull/449.
It seems that the patch has been deployed recently to the production registry instance.
Now, all the extensions from the `vscode` namespace shouldn't be returned by OpenVSX API.
For more details, see https://github.com/eclipse/openvsx/blob/ee6eb3b102dfd75c126cc1ef74a228bc8b999fff/server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java#L48

I'm closing this issue as not reproducible anymore.
