### ISSUE TITLE
How to create a cheCluster running with che-server, but not devworkspace

### ISSUE THREAD

**Issue by LiJunBJZhu** [eclipse/che#21794]
### Describe the bug

I installed devspaces 3.1.0 which is based on Eclipse che 7.52.0, and in CSV I changed the CHE_FLAVOR to 'che', not 'devspaces'. However, the components of a created workspace were created by devWorkspace Operator. 

I am wondering on 7.52.x or 7.55.x is there a way to use che-server as the engine so that all components of workspaces are created by che-server? 

I understand devspaces is the trend, but we can't switch to it shortly. And we'd like to use VS code as the editor so we can't stay at 7.4x.

### Che version

7.52

### Steps to reproduce

Steps are described above.

### Expected behavior

Use che-server as the engine.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

### Additional context

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/13618961/199024563-9aad0b46-a98c-41e9-a66d-c04f2e4d164d.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/13618961/199024722-aca94197-5729-4bd9-8326-a1f64d3e3ea2.png">

**Comment by tolusha** [comment]
There is no way to switch to che server engine.
