### ISSUE TITLE
Failed to install che 7.55 on Openshift

### ISSUE THREAD

**Issue by LiJunBJZhu** [eclipse/che#21792]
### Describe the bug

The error "Operator failed intersecting operatorgroups provide the same apis" is reported.

I see the state of Che operator is 'Failed', however, DevWorkspaces Operator is 'Succeeded'。

### Che version

7.55@latest

### Steps to reproduce

1. Go to OperatorHub
2. Find 'Eclipse Che'
3. Install it

### Expected behavior

No error is reported.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by tolusha** [comment]
![screenshot-console-openshift-console apps ci-ln-clbj8fb-76ef8 origin-ci-int-aws dev rhcloud com-2022 10 31-14_12_55](https://user-images.githubusercontent.com/1640675/199005332-5d2fc326-dfbd-4252-83fa-e2b752636930.png)

**Comment by tolusha** [comment]
Could you provide more detailed steps to reproduce? 
Have you installed any other operators before che?

**Comment by LiJunBJZhu** [comment]
I installed it on Openshift Local 4.10.14. Previously CodeReady workspace 2.10 was installed on the environment. Then I deleted the checluster, operator, CRD. And installed Eclipse Che from OperatorHub. 

A worse thing is that I can't uninstall the failed Eclipse Che from the namespace 'Openshift-Operators' any more. Its state stuck on 'Cannot update'.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/13618961/199019435-df06adaa-9718-4feb-b6cf-824099589cdf.png">

**Comment by tolusha** [comment]
Could you check if there is any related Subscription or ClusterServiceVersion resources related to Eclipse Che on the cluster?
If so, could you delete them?

**Comment by tolusha** [comment]
I recommend to download the latest [chectl](https://github.com/che-incubator/chectl/) 7.56.0 and run:
1. `chectl server:delete --delete-all --delete-namespace`
2. `chectl server:deploy --platform openshift`

**Comment by LiJunBJZhu** [comment]
Cool. The issue can't be recreated on 7.56.0. Closing.
