### ISSUE TITLE
Extension UI does not work on 1.73.0

### ISSUE THREAD

**Issue by mgubaidullin** [eclipse/che#21798]
### Describe the bug

Apache Camel Karavan extension 3.18.4 from [open-vsx.org](https://open-vsx.org/) does not work on 1.73.0
Same extension worked fine on 1.72.0

### Che version

other (please specify in additional context)

### Steps to reproduce

1. Install extension
2. right click on explorer and select Karavan: Create Integration
3. input name
4. empty screen instead of extension UI

### Expected behavior

Extension UI should work

### Runtime

OpenShift

### Screenshots

<img width="817" alt="Screen Shot 2022-11-01 at 10 43 27 AM" src="https://user-images.githubusercontent.com/1379213/199262998-17939d54-c881-42f8-aaf6-71ff06d0e298.png">

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Red Hat OpenShift Dev Spaces with Microsoft Visual Studio Code: 1.73.0

**Comment by mgubaidullin** [comment]
Same issue on Red Hat OpenShift Dev Spaces with Microsoft Visual Studio Code: 1.74.0

**Comment by azatsarynnyy** [comment]
I've just verified it on other public services providing VS Code and there are the same errors with fetching the resources as it's shown on the attached screenshot.
It seems other VS Code extensions that utilize Webview don't have such problems.

It's unlikely, but ATM it looks like a breaking change in the VS Code 1.73.
Everything that's mentioned in their release notes for 1.73 is https://code.visualstudio.com/updates/v1_73#_consistent-origin-for-webviews-and-webview-views
