### ISSUE TITLE
Workspaces are stopped unexpectedly during startup

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21809]
### Describe the bug

Try starting a workspace with `#https://github.com/agiertli/dev-spaces-test.git?new` against dogfooding 

![image](https://user-images.githubusercontent.com/1461122/200561982-26c66424-29af-4993-a6c5-49765e412c20.png)

Another reproducer is https://workspaces.openshift.com/#https://github.com/che-incubator/quarkus-api-example

![image](https://user-images.githubusercontent.com/1461122/200586672-eb733a2b-2ff5-4e57-927c-8e2a007c3a48.png)

As part of this issue we need to make sure that 

- [ ] `?new` parameter works as expected
- [ ] workspaces with intelij editor start correctly
- [ ] `generateName` devfile attribute works as expected

### Che version

7.56@latest

### Steps to reproduce

See description

### Expected behavior

Workspace is started correctly

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

Workspace is started correctly after clicking open in Verbose mode after failure

**Comment by nickboldt** [comment]
Built in https://quay.io/repository/devspaces/dashboard-rhel8?tab=tags&tag=3.3-64 about 5 hrs ago

But the downstream operator-bundle and IIB builds have not happened due to a problem with crwjen-3 builder node.

https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.3/157/ triggered by hand

**Comment by nickboldt** [comment]
available in:
* [quay.io/devspaces/devspaces-operator-bundle:3.4-57](https://quay.io/devspaces/devspaces-operator-bundle:3.4-57)
* [quay.io/devspaces/devspaces-operator-bundle:3.3-238](https://quay.io/devspaces/devspaces-operator-bundle:3.3-238)

**Comment by dmytro-ndp** [comment]
Downstream issue: https://issues.redhat.com/browse/CRW-3559

**Comment by dmytro-ndp** [comment]
The issue is reproduced with Dev Spaces 3.3.0: https://issues.redhat.com/browse/CRW-3559?focusedCommentId=21337704&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21337704
