### ISSUE TITLE
Remove auto-generated che-server advanced configuration options from the docs

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21804]
### Is your task related to a problem? Please describe

Docs from https://www.eclipse.org/che/docs/stable/administration-guide/advanced-configuration-options-for-the-che-server-component/ are outdated and should be removed both upstream and downstream

### Describe the solution you'd like

removal of the advanced configuration Che Server options from the docs

**Comment by nickboldt** [comment]
As part of this issue, we should replace the invalid example in https://www.eclipse.org/che/docs/stable/administration-guide/advanced-configuration-options-for-the-che-server-component/#understanding-che-server-advanced-configuration to use a valid example instead of obsolete env var CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB. 

@ibuziuk can you provide a better example to use there?

**Comment by ibuziuk** [comment]
@nickboldt @themr0c We can use `CHE_LOGS_APPENDERS_IMPL` as an exampled
which is still relevant:

```  
 server:
      cheLogLevel: INFO
      customCheProperties:
        CHE_LOGS_APPENDERS_IMPL: 'json'
```

the logs will be streamed in the json format once configured:

```
{"@timestamp":"2022-11-04T16:04:40.105Z","@version":"1","message":"Configured factories for environments: '[openshift, kubernetes, no-environment]'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-11-04T16:04:40.106Z","@version":"1","message":"Registered infrastructure 'openshift'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-11-04T16:04:40.194Z","@version":"1","message":"Infrastructure is tracking 0 active runtimes that need to be stopped","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-11-04T16:04:40.279Z","@version":"1","message":"Eclipse Che Api Core: Build info '7.52.1-SNAPSHOT' scmRevision '612f2c8c5e34e3c69cd4ad9e15d45a2da46f6ae3' implementationVersion '7.52.1-SNAPSHOT'","logger_name":"org.eclipse.che.api.core.util.ApiInfoLogInformer","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-11-04T16:04:40.332Z","@version":"1","message":"Metrics server started at port 8087 successfully ","logger_name":"org.eclipse.che.core.metrics.MetricsServer","thread_name":"main","level":"INFO","level_value":20000}
```

This is a very useful functionality since many log aggregators expect this format for processing

**Comment by nickboldt** [comment]
> @nickboldt @themr0c We can use `CHE_LOGS_APPENDERS_IMPL` as an example:
> ```
>  server:
>       cheLogLevel: INFO
>       customCheProperties:
>         CHE_LOGS_APPENDERS_IMPL: 'json'
> ```
> This is a very useful functionality since many log aggregators expect this format for processing

Is this the correct change?

https://github.com/eclipse-che/che-docs/pull/2494/files
