### ISSUE TITLE
[docs] Managing workspaces via kubectl 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21808]
List of the functionality that is expected to be documented as part of new section `Managing workspaces via kubectl` - https://www.eclipse.org/che/docs/stable/end-user-guide/integrating-with-kubernetes/

- [ ] Managing users' workspaces with OpenShift APIs* *(and/or Kubernetes API server)*

- [ ] Listing workspaces*

- [ ]  Creating workspaces*

- [ ] Restarting workspaces*

- [ ] Stopping workspaces*

- [ ] Starting stopped workspaces*

- [ ] Removing workspaces

Downstream issue - https://issues.redhat.com/browse/CRW-2160

**Comment by max-cx** [comment]
I got as far as testing `$ chectl/oc get devworkspace --all-namespaces` (TIP: `--watch`), but the rest of the commands don't have a clearcut presence in the `kubectl/oc` docs, so I'd better rely on a developer to come up with info that customers/users can confidently use in production.

Advice for the assignee developer: please first read the downstream issue (linked above) and then add your content to https://github.com/eclipse-che/che-docs/pull/2487. (I just need the technical info from you, and I'll take care of writing the final PR text with your engineering reviews.)

**Comment by tolusha** [comment]
Here is some examples
https://github.com/eclipse/che/issues/20671#issuecomment-993051102

I think we can ask either QE team @dmytro-ndp if they have those commands in some internal docs

**Comment by dmytro-ndp** [comment]
@tolusha : that was a good assumption.

There are test scripts developed by @artaleks9 : 
- create and start workspace: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/vars/dsUtil.groovy#L98
- stop workspace: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/vars/dsUtil.groovy#L201
- delete workspace: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/vars/dsUtil.groovy#L214

An example of create, start, stop, delete commands for NodeJsExpressWebApplication sample workspace with VS Code Editor: https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/api-tests/672/consoleFull

**Comment by themr0c** [comment]
Reference in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3216

**Comment by dkwon17** [comment]
Hello @max-cx @tolusha @dmytro-ndp, if no one has done so already, I am interested in working on this issue (adding content to https://github.com/eclipse-che/che-docs/pull/2487 based on examples from https://github.com/eclipse/che/issues/21808#issuecomment-1308231313 and https://github.com/eclipse/che/issues/21808#issuecomment-1308662826)

**Comment by max-cx** [comment]
@dkwon17 , thank you. I'm very much looking forward to working with you on this. I've assigned this issue to you now (my handle was just a placeholder). FYI, there's also the downstream issue (I've made you the assignee there too just for clarity): https://issues.redhat.com/browse/CRW-2160.

**Comment by ibuziuk** [comment]
@max-cx PR has been opened and waiting for review - https://github.com/eclipse-che/che-docs/pull/2510

**Comment by max-cx** [comment]
@ibuziuk, thank you for the reminder. I am well aware of https://github.com/eclipse-che/che-docs/pull/2510. I currently have no bandwidth to work on it before the holidays. This will be my priority when I'm back in January. I'm very much looking forward to working on the content that David has drafted and doing my review, testing, and editing.

**Comment by ibuziuk** [comment]
thank you. Closing
