### ISSUE TITLE
"Publish Image PR check" github action fails for the Che-Code

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#21806]
### Is your task related to a problem? Please describe

`Publish Image PR check` github action started to fail for the `Che-Code`.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/5676062/200031654-4b44a9ae-844f-4ea7-b1ae-f439a617dddb.png">

### Describe the solution you'd like

The action should work correctly within the Github Workflow

### Describe alternatives you've considered

The workaround is:
it's possible to find the corresponding images [here](https://quay.io/repository/che-incubator-pull-requests/che-code?tab=tags)

### Additional context

It looks like the problem is related to the `Dev` image size:

<img width="829" alt="Screenshot 2022-11-04 at 18 54 29" src="https://user-images.githubusercontent.com/5676062/200032306-01226aa9-c357-4467-b1f7-4d57ae82ccb0.png">

**Comment by azatsarynnyy** [comment]
I think this issue can be closed as the problem should have been already resolved by https://github.com/che-incubator/che-code/pull/174. 
Since the PR is merged, I haven't noticed the mentioned problem for the [`workflows/pr-check-image-publish`](https://github.com/che-incubator/che-code/actions/workflows/pr-check-image-publish.yml).

**Comment by RomanNikitenko** [comment]
It's still unclear how adding github token decreased dev-image size 

<img width="405" alt="Screenshot 2023-02-08 at 12 00 44" src="https://user-images.githubusercontent.com/5676062/217498434-45927ead-0db2-4e28-9c6d-d1f7feec293d.png">

But you are right - the problem is gone, so let's close the issue.
