### ISSUE TITLE
Describe how to switch from online OS cluster to offline/AirGap one

### ISSUE THREAD

**Issue by svor** [eclipse/che#21819]
### Is your task related to a problem? Please describe

Time to time we need to verify some Che/DS functionality on the offline or AirGap cluster and it's not clear enough and takes to much time to prepare such cluster with Che or DS instance. 
It would be nice to have some scripts/instructions that will help to prepare such instance.

### Describe the solution you'd like

Create scripts with instructions how to prepare AirGap cluster and deploy Che into it. It could be part of https://github.com/eclipse-che/che-docs.

### Additional context

Related issue https://issues.redhat.com/browse/RHDEVDOCS-4599

**Comment by tolusha** [comment]
Put in internal doc
