### ISSUE TITLE
blank page after install che using minikube {"message":"Route GET:/oauth/sign_in not found","error":"Not Found","statusCode":404}

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#21816]
### Describe the bug
l use `chectl server:status` commnd -->
          Eclipse Che Version    : next
          Eclipse Che Url        : https://192.168.49.2.nip.io/dashboard/
then l open [https://192.168.49.2.nip.io/dashboard/](url) , it is just a blank page

then l  use `chectl dashboard:open` can not see the che-dashoard, so l use `minikube service  che-dashboard -n eclipse-che --url` , the brower rediret to http://[127.0.0.1:58364/oauth/sign_in#/](http://127.0.0.1:58364/oauth/sign_in#/), and say  {"message":"Route GET:/oauth/sign_in not found","error":"Not Found","statusCode":404} , so l confused, how can l do to see the che-dashboard in my brower, thanks!

### Che version

7.56@latest

### Steps to reproduce
1, install che following https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-on-minikube/
2.l use `chectl dashboard:open`, it syas "Opening ... https://192.168.49.2.nip.io/dashboard/" l  can not see the che-dashoard, 
3. l use `minikube service list` , then l see  "che-dashboard",   then l use `minikube service  che-dashboard -n eclipse-che --url` , ---> * service eclipse-che/che-dashboard has no node port http://127.0.0.1:58364
4.  l open http://127.0.0.1:58364 in brower, ---> {"message":"Route GET:/oauth/sign_in not found","error":"Not Found","statusCode":404}

### Expected behavior

see the che-dashboard in my brower

### Runtime

minikube

## Screenshots

#
![Screenshot_20221115_103608](https://user-images.githubusercontent.com/13027592/201818652-57fc4e1d-28da-43dc-8b87-7d94082b60e0.png)

### Installation method

chectl/latest

### Environment

Windows

**Comment by dkwon17** [comment]
Hello @davidxwwang , when opening  https://192.168.49.2.nip.io/dashboard, are there any logs/error messages in the developer console (Control+Shift+J)?

**Comment by tolusha** [comment]
@davidxwwang 
It would be very helpful to inspect `chectl server:deploy` output command, but I hope it completed successfully.
If you uses Windows, then it can help you [1], specifically [2].

[1] https://github.com/eclipse/che/issues/21125#issuecomment-1170863395
[2] https://gist.github.com/debovema/783f29040059f8b2b784a246dbd96365

**Comment by davidxwwang** [comment]
> @davidxwwang It would be very helpful to inspect `chectl server:deploy` output command, but I hope it completed successfully. If you uses Windows, then it can help you [1], specifically [2].
> 
> [1] [#21125 (comment)](https://github.com/eclipse/che/issues/21125#issuecomment-1170863395) [2] https://gist.github.com/debovema/783f29040059f8b2b784a246dbd96365

thanks!
