### ISSUE TITLE
Improper handling on CPU request/limit in dashboard

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21811]
### Describe the bug

When using devfiles that specify certain CPU limits/requests, Che returns invalid values for the CPU resource after adding the limit/request for the injected editor. Starting a workspace with a memory request of `4000m`, for example, results in the injected devfile requesting `4030.0000000000005m` instead of `4030m`. This occurs because the injected CPU request is `30m`, which internally gets parsed to
```
(4.0 + 0.03) * 1000
```

The CPU virtual resource in Kubernetes uses `m` as the smallest unit, so fractional `m` values are invalid.

### Che version

7.56@latest

### Steps to reproduce

1. Start workspace from devfile https://gist.githubusercontent.com/l0rd/a200cc8a036a3564278e9bdb3e44cfe1/raw/2a9a7d1fb8275ce0c72407f3eed73d3fe4b03f2e/big-workspace.yaml
2. After workspace is applied to the cluster, check the devfile in the dashboard for an invalid CPU request value.

### Expected behavior

CPU request should be floored before returning to avoid fractional parts.

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

**Comment by l0rd** [comment]
Already fixed
