### ISSUE TITLE
VS Code shows wrong commands and files (restored from a previous workspace)

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21813]
### Describe the bug

Sometimes, when the user starts a **new** DevWorkspace, VS Code tries to restore its state. It looks odd to the user as the DevWorkspace is newly created so there must be no previous state.

It has a bad effect on the overall UX. For example:
- VS Code may show an errors that some files couldn't be reopened because they don't exist;
- Command Palette may contain some recently running Tasks that the user has never executed;
- VS Code doesn't suggest the user install the recommended extensions;
- etc.

### Che version

next (development version)

### Steps to reproduce

1. Start a new DevWorkspace with some project.
2. Try to open a few files and run some Tasks.
3. When you restart your DevWorkspace, VS Code will store its state (e.g. reopen the files) which is expected.
4. Remove the DevWorkspace.
5. Start a new DevWorkspace with a completely different project that has the same name as the previous one.
6. VS Code shows an error that it can’t find the files to reopen. In the Command Palette, some Tasks are shown as recently running.

### Expected behavior
The state of the VS Code Workspace should be restored across restarts of the **same** DevWorkspace only. Even if it's named the same as some previously deleted ones.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

### Release Notes Text

When starting a new workspace VS Code may restore the state of a previous workspace showing commands and files that do not exist in the new workspace.

**Comment by dmytro-ndp** [comment]
Downstream issue: https://issues.redhat.com/browse/CRW-3421

**Comment by azatsarynnyy** [comment]
Sharing below the results of my Friday's investigation :eyes: 

VS Code stores its state in three scopes:
- Application;
- Workspace;
- Profile.

This issue is related to VS Code's Workspace Storage.
:warning: Keep in mind: `VS Code's Workspace` != `DevWorkspace`.

The actual implementation of the physical storage depends on the environment/context VS Code is running in.
In the Web mode, VS Code uses in-browser IndexedDB as a Workspace Storage. For each VS Code Workspace it creates a separate Database to persist the Workspace-related data.

![image](https://user-images.githubusercontent.com/1636395/201522079-4113fe6d-6053-490d-b2b5-8ccf601836fa.png)

The Database name is suffixed with the VS Code Workspace's ID, which is calculated as a hash of the Worksapces URI (e.g.: `vscode-remote:/projects/java-spring-petclinic`).
So, when VS Code is running in two different DevWorkspaces, it may use the same physical Workspace Storage to persist/resore the Workspaces' states in case both cloned projects have the same name (so the same URI), e.g.: `java-spring-petclinic`, `my-web-app`, etc.

It explains an odd UX when the user runs a newly created DevWorkspace cloning the project which name has already been present in another DevWorkspace.

**Comment by azatsarynnyy** [comment]
I'm raising the issue's priority to P1, as it turned out it's reproduced more often than I thought. For example, if I'm reviewing different PRs from some repository I need to spin up the one-time DevWorkspaces with the same cloned project. So, with the same name. These are precisely the conditions for reproducing this problem, resulting in poor UX.

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/che-incubator/che-code/pull/148
