### ISSUE TITLE
As a user, I want to have the possibility to navigate from the IDE to the Kubernetes / OpenShift cluster where the instance is running

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21822]
### Is your task related to a problem? Please describe

Currently, there is no way to navigate to the k8s / openshift cluster from IDE UI
As a user, I want to have the possibility to navigate to the Kubernetes / OpenShift cluster where the instance is running. At this moment I need to run a command from the terminal e.g. `oc whoami --show-console`

### Describe the solution you'd like

Would be nice to see the cluster URL in the status bar with a possibility of one click navigation or as part of the `Eclipse Che` / `Dev Spaces` badge

![image](https://user-images.githubusercontent.com/1461122/202389704-e0b7e2c6-69d4-46bb-b33f-dd0233881cf2.png)

### Additional context

similar functionality present on the User Dashboard - https://github.com/eclipse/che/issues/20106

**Comment by RomanNikitenko** [comment]
I implemented the simplest solution for the current issue. The `Open OpenShift console` command is enabled only if VS Code is running on the `OpenShift`. About the Kubernetes GUIs case please see https://github.com/che-incubator/che-code/pull/191#discussion_r1142414458

There are two PRs to provide `Open OpenShift console` command:
- on the `dashboard` side: https://github.com/eclipse-che/che-dashboard/pull/758
- on the `che-code` side: https://github.com/che-incubator/che-code/pull/191

The first one already merged, the second one is under review.
