### ISSUE TITLE
[docs] Document unsupported Devfile 2.x features

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21829]
As part of this issue, we need to document unsupported Devfile 2.x features which are part of the spec [1] but not supported by Eclipse Che / DevWorkspace Operator. Related epic for full support of the spec - https://github.com/eclipse/che/issues/17883

As the first step the docs could be in https://github.com/devfile/devworkspace-operator/tree/main/docs

[1] https://raw.githubusercontent.com/devfile/api/2.2.x/schemas/latest/ide-targeted/devfile.json

**Comment by themr0c** [comment]
Reference in Jira: https://issues.redhat.com/browse/RHDEVDOCS-4759

**Comment by AObuchow** [comment]
DWO Issue: https://github.com/devfile/devworkspace-operator/issues/983

**Comment by ibuziuk** [comment]
upstream issue has been resolved @themr0c @max-cx folks, can we close the issue since the downstream part is tracked on Jira
