### ISSUE TITLE
Typo in the readme of of the che plugin registry

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#21821]
### Is your task related to a problem? Please describe

The readme of the che plugin registry contains a typo which may be hard to spot.

### Describe the solution you'd like

Fixing the typo.

### Additional context

I tried to deploy a custom che plugin registry and noticed that the readme file for deploying in via helm on minikube contains a typo, which results in a failed deployment. I didn't saw that the typo was the problem for the failed deployment and it may save frustration for other people trying the same.

**Comment by ibuziuk** [comment]
@Deel96 thanks for the contribution, can we close the issue now? PR has been merged
