### ISSUE TITLE
Allow configuring workspace start timeout via CheCluster spec

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21820]
### Is your enhancement related to a problem? Please describe

Since workspace start is managed by the DevWorkspace Operator, the timeout before a starting workspace is marked as failed is now configured through the DevWorkspace Operator Config (DWOC) CR, deprecating older Che properties. 

For certain CheCluster fields (e.g. PVC configuration), the Che Operator manages these fields by creating a custom DWOC that is used for all workspaces. This should be extended to allow setting `.config.workspace.progressTimeout` in the DWOC based on a CheCluster field as well.

### Describe the solution you'd like

Start timeout for DevWorkspaces can be configured through the CheCluster spec

### Describe alternatives you've considered

It's currently possible to work around this by setting the field in the CheCluster-owned DWOC in the install namespace. As this field is not managed by Che, its value is not reverted by the Che Operator.

### Release Notes Text

The timeout to consider workspaces startup as failed was hardcoded and could not be configured by administrators. With this new feature Che administrators can specify the workspaces startup timeout in the CheCluster custom resource.

**Comment by tolusha** [comment]
I think `startTimeout` field is not introduced in operator config yeat.

**Comment by amisevsk** [comment]
My bad -- the field in DWOC is `progressTimeout` (i.e. `.config.workspace.progressTimeout`) since it applies to both starting and failing workspaces. I've updated the description above to reflect this.

Probably makes sense to use `startTimeout` in the Che config either way -- WDYT?

**Comment by tolusha** [comment]
> Probably makes sense to use startTimeout in the Che config either way -- WDYT?

Make sense for me as well.
