### ISSUE TITLE
Remove the DevWorkspace handler code from the Che-Code repository

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21837]
### Is your task related to a problem? Please describe

Once we are done with the migration to [DevWorkspace Operator container contributions](https://github.com/eclipse/che/issues/21736) we can remove the DevWorkspace handler-related code from [the Che-Code repository](https://github.com/che-incubator/che-code/tree/main/tools/devworkspace-handler) as it will become not used anymore.

### Describe the solution you'd like

1. Make sure there are no consumers of the [`eclipse-che/che-code-devworkspace-handler`](https://www.npmjs.com/package/@eclipse-che/che-code-devworkspace-handler) npm library.
Currently, the known consumers are:
- [Che Dashboard](https://github.com/eclipse-che/che-dashboard/blob/07a6e5a8c9cc43b9ea644ef1a46e46862e219459/packages/dashboard-frontend/package.json#L36)
- [Che Devfile Registry](https://github.com/eclipse-che/che-devfile-registry/blob/ac70c9d0f416d8f09f2a7c6da9b565ce2bdf9754/build/scripts/generate_devworkspace_templates.sh#L35)
2. Remove the [GitHub Workflow](https://github.com/che-incubator/che-code/actions/workflows/devworkspace-handler-publish-next.yml) publishing the new versions of the npm package to the public npmjs registry.
3. Remove the [devworkspace-handler code](https://github.com/che-incubator/che-code/tree/main/tools/devworkspace-handler).

### Additional context
The issue is a part of epic https://github.com/eclipse/che/issues/21736

**Comment by ibuziuk** [comment]
@l0rd @azatsarynnyy could you please prioritize it for the next sprint to finalize the epic - https://github.com/eclipse/che/issues/21736

**Comment by azatsarynnyy** [comment]
Before this clean-up, we should wait for [this handler usage](https://github.com/eclipse-che/che-dashboard/blob/758bd74ee1a4f36c5c30332ab88a2701794a3466/packages/dashboard-frontend/package.json#L36-L37) to be removed from the Dashboard. We've already discussed that with @ibuziuk and @olexii4 
The Dashboard part is tracked at https://github.com/eclipse/che/issues/21738

**Comment by azatsarynnyy** [comment]
The DevWorkspace handler [dependency is removed](https://github.com/eclipse-che/che-dashboard/pull/716/files#diff-9fd93c82f640808aaf212c2a876ebe002bd75def43e23ee61cc1544e8a9cf857L36) on the Dashboard side.

@vitaliy-guliy I think we can merge the Che-Code PR https://github.com/che-incubator/che-code/pull/169.
