### ISSUE TITLE
Document the Che-specific features we've added to Che's VS Code editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21835]
### Is your task related to a problem? Please describe

In [the Che-Code project](https://github.com/che-incubator/che-code), we extended the vanilla VS Code with the Che-specific features and made some adaptations of VS Code's internals to the Che environment.

While it does everything the user might expect from VS Code running in Che, there's no way to read the details of using the particular feature and learn about some important aspects of its behavior.

### Describe the solution you'd like

We need to document all the Che-specific features, we've added to our VS Code assembly, on [the Che documentation website](https://www.eclipse.org/che/docs/stable/overview/introduction-to-eclipse-che/).

### Additional context

Below is the list of the features we can consider to document:

- running the Devfile Commands as VS Code Tasks with the possibility to run them in any container
- opening VS Code terminals to DevWorkspace containers
- detection of the opened ports and suggestions exposing corresponding apps' URLs
- monitoring the system resources of the DevWorkspace containers
- authentication on GitHub
- sending the user's activities to prevent a DevWorkspace from stopping by an idle timeout
- added the helper extension to interact with DevWorkspace. It may be used by the custom extensions which need to work with DevWorkspace directly
- navigating to Che Dashboard from the IDE

Some low-level adaptations to make VS Code work in Che smoothly:

- auto-install the recommended extensions
- idled DevWorkspace detection (in progress)
- the white-labeling capabilities

**Comment by l0rd** [comment]
> added the helper extension to interact with DevWorkspace. It may be used by the custom extensions which need to work with DevWorkspace directly

Is the helper related to the [vscode handler](https://github.com/che-incubator/che-code/tree/main/tools/devworkspace-handler)? The handler is not required to inject information about the IDE in the tooling container anymore (see [container contributions epic](https://github.com/eclipse/che/issues/21736)) so I am wondering if we can remove it completly from che-code repo (and add a subtask to #21736) or if we still need it.

**Comment by azatsarynnyy** [comment]
> Is the helper related to the [vscode handler](https://github.com/che-incubator/che-code/tree/main/tools/devworkspace-handler)?

@l0rd it isn't related to a DevWorkspace handler, but it's mostly to simplify fetching some information from a DevWorksapce. Probably, something not worth documenting, as it's more internal stuff.

As for getting rid of the Che-Code DevWorkspace handler, I've just filed
- https://github.com/eclipse/che/issues/21837
and included it in the epic
- https://github.com/eclipse/che/issues/21736

I believe we do not need a dedicated issue for Che-Theia's DevWorkspace handler, as it will be part of 
- https://github.com/eclipse/che/issues/21771

**Comment by max-cx** [comment]
@azatsarynnyy and @l0rd, how would you compare the expected docs content between the VS Code and the IntelliJ editors (like for any editor Che supports)? I mean should we be expecting a similar issue with a similar scope of documentation for an IntelliJ editor in the future? Or is this docs focus just on VS Code?

**Comment by azatsarynnyy** [comment]
@max-cx these docs focus just on VS Code

**Comment by l0rd** [comment]
> @max-cx these docs focus just on VS Code

ok, these are just for VS Code. But we have worked on similar features (such as devfile command support) for JetBrains IDE and we should document that.

**Comment by azatsarynnyy** [comment]
> > @max-cx these docs focus just on VS Code
> 
> ok, these are just for VS Code. But we have worked on similar features (such as devfile command support) for JetBrains IDE and we should document that.

okay, then here's the corresponding issue for the IDEA editor:
- #21841

**Comment by bdwyertech** [comment]
Is there still a concept of directly specifying plugins like theia had via `.che/che-theia-plugins.yaml` attribute?  I do not see any of that logic in the [devworkspace-handler for che-code]([vscode handler](https://github.com/che-incubator/che-code/tree/main/tools/devworkspace-handler)).

```yaml
schemaVersion: 2.1.0
attributes:
  .che/che-theia-plugins.yaml: |
    - repository:
        url: 'https://github.com/chef/vscode-chef'
        revision: 2.1.0
      extension: https://github.com/bdwyertech/vscode-chef/releases/download/che/chef-software.Chef-2.1.0.vsix
```

**Comment by azatsarynnyy** [comment]
@bdwyertech you can declare the VS Code extensions in the `.vscode/extensions.json` file and they will be installed automatically in Che-Code. 
E.g.: https://github.com/eclipse-che/che-docs/blob/main/.vscode/extensions.json

**Comment by max-cx** [comment]
I opened [RHDEVDOCS-5026](https://issues.redhat.com/browse/RHDEVDOCS-5026) to assign a technical writer when the developers are ready to start preparing more content on this topic.
