### ISSUE TITLE
prow/v11 happy path test failing: testCatalogFromSources.sh: No such file or directory

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21836]
### Describe the bug

**ci/prow/v11-devworkspace-happy-path** testing failing - `testCatalogFromSources.sh: No such file or directory`:

![image](https://user-images.githubusercontent.com/227597/203649478-0ca0f310-f065-41c0-b286-00a3968e2adf.png)

```
  * could not run steps: step devworkspace-happy-path failed: "devworkspace-happy-path" test steps failed: "devworkspace-happy-path" pod "devworkspace-happy-path-devworkspace-happy-path" failed: the pod ci-op-ncmkv9pq/devworkspace-happy-path-devworkspace-happy-path failed after 26s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
/bin/bash: build/scripts/olm/testCatalogFromSources.sh: No such file or directory
{"component":"entrypoint","error":"wrapped process failed: exit status 127","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-11-23T19:44:46Z"}
error: failed to execute wrapped command: exit status 127
```
-- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1568/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1595492550372757504

### Steps to reproduce

1. generate a PR https://github.com/eclipse-che/che-operator/pull/1568
2. watch it fail 

In 7.57.x and main we have these renamed scripts:
```
$➔ ls -1 build/scripts/olm/
release-catalog.sh
test-catalog-from-sources.sh
test-catalog.sh
test-update.sh
```

But in 7.56.x branch we have these other names. Did we miss a refactoring step somewhere? 
```
$➔ ls -1 build/scripts/olm/
buildCatalog.sh
testCatalogFromSources.sh
testCatalog.sh
testUpdate.sh
```

**Comment by nickboldt** [comment]
Other recent PRs with teh same failure include:
* https://github.com/eclipse-che/che-operator/pull/1549 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1549/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1590728292690825216 -> timeouts
* https://github.com/eclipse-che/che-operator/pull/1557 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1557/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1588437534801661952 -> timeouts

**Comment by nickboldt** [comment]
Possible fix: https://github.com/openshift/release/pull/34307

**Comment by nickboldt** [comment]
well, we're better:

Before:

```
{  /bin/bash: build/scripts/olm/testCatalogFromSources.sh: No such file or directory
```
-- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1568/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1595492550372757504

Now:

```
Error from server (ServiceUnavailable): the server is currently unable to handle the request (post buildconfigs.build.openshift.io eclipse-che-operator)
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-12-14T20:44:08Z"}
error: failed to execute wrapped command: exit status 1
```

-- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1582/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1603116812780703744

**Comment by tolusha** [comment]
It was OpenShift issue. Another try showed problem with starting HappyPath tests 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1582/pull-ci-eclipse-che-che-operator-main-v11-devworkspace-happy-path/1603281268777160704

**Comment by tolusha** [comment]
I think we need @dmytro-ndp help to figure what is wrong with tests.
