### ISSUE TITLE
[Dashboard] Document the usage of the che-server API

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21848]
### Is your task related to a problem? Please describe

Currently, the dashboard is the only component that uses che-server REST API. The vast majority of the endpoints are not used anymore with the DevWorkspace flow, and will be removed in the upcoming versions of the project see:
- https://github.com/eclipse/che/issues/21846
- https://github.com/eclipse/che/issues/21845

As part of this issue in the the-dashboard README.md we need to document which endpoints are still used and are not planned to be deprecated e.g. factory / kubernetes-namespace

### Describe the solution you'd like

README.md should contain a section with info about the che-server endpoints that are still used 

### Describe alternatives you've considered

N/A

**Comment by ibuziuk** [comment]
@azatsarynnyy @svor @tolusha folks, could you please confirm that the dashboard is the only operand that still uses Che-Server API

**Comment by azatsarynnyy** [comment]
@ibuziuk None of the Che-Server APIs are used by the Che editors: Theia, IDEA, VS Code.

**Comment by tolusha** [comment]
`chectl` uses `system/state` request to check che-server state.
But it can be easily removed
