### ISSUE TITLE
[Dashboard] Remove dependency on Workspace API provided by che-server

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21846]
### Is your task related to a problem? Please describe

Starting from version 7.59.0 Dashboard should have no dependencies on the Workspace API
Note, that starting from this version it would not be possible to preview old devfile v1 workspaces and convert them to v2 version from the User Dashboard

![image](https://user-images.githubusercontent.com/1461122/204498309-0736bd3d-e8ca-4f8c-b57f-edf75a63b76c.png)

### Describe the solution you'd like

Remove dependency on Workspace API provided by che-server

### Describe alternatives you've considered

N/A

### Additional context

The issue is related to the Decommissioning PostgreSQL database #21374 epic

**Comment by ibuziuk** [comment]
@mario @Kasturi1820 Please, take a look 
if you think that we should shift the date when UD would not support devfile v1 workspaces convertion from the database let me know. The current target is 7.59.0

**Comment by l0rd** [comment]
7.59 is perfectly fine

**Comment by Kasturi1820** [comment]
7.59 is fine @ibuziuk

**Comment by ibuziuk** [comment]
Resolving this issue is pre-req for merging https://github.com/eclipse-che/che-server/pull/398
