### ISSUE TITLE
[Dashboard] Remove dependency on Devfile API provided by che-server

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21845]
### Is your task related to a problem? Please describe

Remove dependency on Devfile API provided by che-server:

![image](https://user-images.githubusercontent.com/1461122/204497138-afffa05e-db50-4105-bdcf-0b1a41694b9d.png)

### Describe the solution you'd like

The dashboard should not depend on the Devfile API starting from version 7.59.0  Currently, the only dependency is related to retrieving and validating devfile schemas of different versions, which is planned to be part of the dashboard -https://github.com/eclipse-che/che-dashboard/pull/671

### Additional context

Related PRs:
- https://github.com/eclipse-che/che-dashboard/pull/671
- https://github.com/eclipse-che/che-server/pull/386

**Comment by olexii4** [comment]
Fixed in https://github.com/eclipse-che/che-dashboard/pull/671
