### ISSUE TITLE
"Adding of workspace folder was canceled by timeout" in a large multi-root workspace

### ISSUE THREAD

**Issue by fyudanov** [eclipse/che#21844]
### Describe the bug

The 7 seconds timeout in code of workspace-folder-updater.ts doesn't look sufficient for a large multi-root workspace 

```
export class WorkspaceFolderUpdaterImpl {
  promiseChain: Promise<void> = Promise.resolve();

  constructor(protected readonly timeout = 7000) {}

```

### Che version

7.57@latest

### Steps to reproduce

1. Create a workspace from Devfile attached [large.devfile.txt](https://github.com/eclipse/che/files/10104707/large.devfile.txt)
2. Wait for IDE to start
3. See only some of 13 projects are added to workspace with the lines logged in output:
`
Extension-Host:Promise rejection not handled in one second: Error: Adding of workspace folder /projects/textual was canceled by timeout , reason: Error: Adding of workspace folder /projects/textual was canceled by timeout
With stack trace: Error: Adding of workspace folder /projects/textual was canceled by timeout
    at Timeout._onTimeout (/default-theia-plugins/eclipse_che_workspace_plugin/lib/workspace-folder-updater.js:38:28)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
`

### Expected behavior

13 projects are added to workspace after IDE started

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Linux

### Additional context

Custom deployment on microk8s with chectl 7.50, but expected to be reproducible on other flavors too.
Reproducible with Che-Theia 7.57

**Comment by azatsarynnyy** [comment]
Hello @fyudanov 
Please, find the latest updates update related to Che-Theia at https://www.eclipse.org/lists/che-dev/msg04439.html and https://github.com/eclipse/che/issues/21771
Also, AFAIK, the `projects` field is going to be removed from the next version of the  Devfile specification.
So, I'd recommend storing a specific Devfile with each project source.

**Comment by fyudanov** [comment]
@azatsarynnyy Thanks for information, sounds really important for our Che-based project development.
