### ISSUE TITLE
Devfile could not found,but it does exist

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#21855]
### Describe the bug

when l Import from a Git repository to create my first workspace using  [https://github.com/che-samples/cpp-hello-world/tree/devfilev2](url) , it has tips : “Devfile could not found” ,but the devfile.yaml is present in the repo.

!che version :  7.58.0-SNAPSHOT

### Che version

next (development version)

### Steps to reproduce

1. import from git ,enter [https://github.com/che-samples/cpp-hello-world/tree/devfilev2](url)
2. click the "create & open" bottun on the right
3. the che brower tips: Devfile could not found

### Expected behavior

could open a  workspace based on git 

### Runtime

Kubernetes (vanilla)

### Screenshots

![che3](https://user-images.githubusercontent.com/13027592/205076153-3897a5c6-7d28-42e7-8500-9b1469805fc3.PNG)

![che01](https://user-images.githubusercontent.com/13027592/205073117-ede00239-39f1-48a9-a9c2-1ce70b46887e.PNG)

![che02](https://user-images.githubusercontent.com/13027592/205073199-db81f2a8-5bd5-4d53-86d8-3eb2f79a39e7.PNG)

### Installation method

chectl/latest

### Environment

Windows

**Comment by ibuziuk** [comment]
hi, which version of Eclipse Che are you using. I can not reproduce on the nightly

**Comment by davidxwwang** [comment]
> hi, which version of Eclipse Che are you using? I can not reproduce it on the nightly

![che4](https://user-images.githubusercontent.com/13027592/205192726-a9e36289-05a8-435e-9070-c4adfaabd4b1.PNG)

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy folks, could you please take a look, I can not reproduce on dogfooding

**Comment by davidxwwang** [comment]
@ibuziuk @olexii4 @akurinnoy thanks for your quick response, l guess maybe it caused by the network, bacause sometimes it says "find the davfile.yaml" and sometimes it fail, becasue the network connect to github is unstable(ping timeout!) ----> only guess!
