### ISSUE TITLE
Document the known issues related to cookie blocking by different browsers

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21853]
### Is your task related to a problem? Please describe

Upstream VS Code has a known issue with the correct WebView work depending on the browser's settings related to the Third-Party Cookies blocking. ATM, it is not documented on the VS Code docs.

The Che user may face such an issue very easily when opening Che in Firefox on Mac OS.
The problem appears as an empty WebView-based page in VS Code UI. Also, the user gets a notification saying:
![image](https://user-images.githubusercontent.com/1636395/205049646-ed6b46d2-fddd-4783-b063-6c2d93f5b1c1.png)

### Describe the solution you'd like

We should document this upstream problem as a known issue and describe the possible options for how the user can work it around by changing the browser's settings.
The details I've described in https://github.com/eclipse/che/issues/21852#issuecomment-1333509295.

### Describe alternatives you've considered

As a more general solution, we could create a dedicated page in Che docs describing:
- the supported browsers;
- the known issues which are browser-specific;
- particular browser's settings need to be changed in order to ensure stable work;
- collect other browser-specific notes.

### Additional context

- #21852
- [Firefox rolls out Total Cookie Protection by default to all users worldwide](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/)
- [How to turn off Enhanced Tracking Protection in Firefox](https://support.mozilla.org/en-US/kb/introducing-total-cookie-protection-standard-mode?as=u&utm_source=inproduct#firefox:mac:fx108)

**Comment by max-cx** [comment]
@azatsarynnyy, if possible, please ask the assignee to reach out to the docs team, ideally before opening a PR to the docs repo, so that we can figure out together where to incorporate this new content in the docs. Here's the docs issue: https://issues.redhat.com/browse/RHDEVDOCS-4803.

**Comment by azatsarynnyy** [comment]
@max-cx I wrote some notes here https://gist.github.com/azatsarynnyy/bb2947b2fef01b2776162713add33505
It can be used as a base for a new docs chapter, probably.

@RomanNikitenko can you please help me to verify how the [suggested workaround](https://gist.github.com/azatsarynnyy/bb2947b2fef01b2776162713add33505#to-work-this-problem-around-in-firefox-standart-mode-on-macos) works on macOS? It would be great if you could check which of the described option works for you.

**Comment by RomanNikitenko** [comment]
`Allow all cookies` helped me for the Chrome Incognito mode.
Note: the workaround doesn't help for the existing Chrome window, reloading doesn't help, user should **first** apply `Allow all cookies` option and then create a window in Incognito mode and start a workspace.
 
<img width="1729" alt="image" src="https://user-images.githubusercontent.com/5676062/214009597-dee20dfb-2455-498f-a284-1ea352996e7f.png">

**Comment by RomanNikitenko** [comment]
About Firefox

I can not reproduce the problem - it works fine for me without any workarounds.
I mentioned it [here](https://github.com/eclipse/che/issues/21782#issuecomment-1305511938)

Today I tested it for:
- [object-detection-rest.git](https://github.com/rh-aiservices-bu/object-detection-rest.git),
 see https://github.com/eclipse/che/issues/21852
and
- [dockerfile-hello-world](https://github.com/l0rd/dockerfile-hello-world), 
see  https://github.com/eclipse/che/issues/21782#issuecomment-1291179703 

<img width="1729" alt="image" src="https://user-images.githubusercontent.com/5676062/214013184-c7aee536-42c3-420b-a411-62add68045c2.png">

<img width="1729" alt="image" src="https://user-images.githubusercontent.com/5676062/214014840-7364b383-65d8-4b34-b109-7a53dea39af3.png">

My settings you can see here:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/5676062/214014299-5d051852-2808-480f-b0d7-f92b0158e9e3.png">

**Comment by azatsarynnyy** [comment]
Thanks, @RomanNikitenko for verifying it.
So, there's nothing specific for Mac users anymore.
I've updated https://gist.github.com/azatsarynnyy/bb2947b2fef01b2776162713add33505

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy, if possible, please ask the assignee to reach out to the docs team, ideally before opening a PR to the docs repo, so that we can figure out together where to incorporate this new content in the docs. Here's the docs issue: https://issues.redhat.com/browse/RHDEVDOCS-4803.

@max-cx I've drafted content related to this issue. Please, find it here https://gist.github.com/azatsarynnyy/bb2947b2fef01b2776162713add33505
Do you have an idea what would be the best place for new content?
