### ISSUE TITLE
Not possible to limit the number of workspaces per user

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21860]
### Describe the bug

```
spec:
  components:
    cheServer:
      extraProperties:
        CHE_LIMITS_USER_WORKSPACES_COUNT: "<kept_workspaces_limit>" 
```

configuration does not work

### Che version

7.57@latest

### Steps to reproduce

Follow the docs for Limiting the number of workspaces that a user can keep https://www.eclipse.org/che/docs/stable/administration-guide/limiting-the-number-of-workspaces-that-a-user-can-keep/

ERROR: the procedure does not work, user can create unlimited number of workspaces

### Expected behavior

Introduce new CR property, since it is not expected to configure the limit of DevWorkspace using che-server extraProperties

   devWorkspace:
      totalLimitPerUser: '5'
      runningLimit: '2'
      
In general, I believe we need to consider deprecation and removal of the DevWorksace field from the CR and have the workspace limits configured in DevEnvironments

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

Outdated docs - https://www.eclipse.org/che/docs/stable/administration-guide/limiting-the-number-of-workspaces-that-a-user-can-keep/

In general, I believe we need to consider deprecation and removal of the DevWorksace field from the CR and have the workspace limits configured in DevEnvironments

### Release Notes Text

**Title:** The maximum number of running workspace per user is configurable
A new `CheCluster` parameter allows administrators to specify the maximum number or running workspaces per user. It can be configured editing the value `spec.devEnvironments.maxNumberOfRunningWorkspacesPerUser` of `CheCluster` custom resource.

**Comment by l0rd** [comment]
We need to update the [doc](https://www.eclipse.org/che/docs/stable/administration-guide/limiting-the-number-of-workspaces-that-a-user-can-keep/)

**Comment by l0rd** [comment]
@tolusha sorry about that, we were looking at the wrong version of the doc

**Comment by dmytro-ndp** [comment]
@ibuziuk : I was able to create 5 workspaces in DS 3.5.0.RC-03-10 having `CHE_LIMITS_USER_WORKSPACES_COUNT: '3'` in CheCluster config:
```
spec:
  components:
    devWorkspace:
      runningLimit: '2'
    cheServer:
      debug: false
      logLevel: INFO
      extraProperties:
        CHE_LIMITS_USER_WORKSPACES_COUNT: '3'
```
![Screenshot from 2023-03-14 19-27-22](https://user-images.githubusercontent.com/1197777/225088428-860a721d-7ffc-47a4-a60a-c9fe83fcbaf1.png)

**Comment by l0rd** [comment]
@dmytro-ndp this is not the right field. Please refer to the [doc](https://www.eclipse.org/che/docs/stable/administration-guide/limiting-the-number-of-workspaces-that-a-user-can-keep/)

**Comment by dmytro-ndp** [comment]
@l0rd: thanks for the hint.
It worked as expected in DS 3.5.0.RC-03-10 following the article you shared:
```
spec:
  devEnvironments:
    maxNumberOfWorkspacesPerUser: 3
```
![Screenshot from 2023-03-15 00-46-59](https://user-images.githubusercontent.com/1197777/225159266-518b5e53-62dc-4261-a7c6-076a1aee844a.png)
