### ISSUE TITLE
Remove "browser you are using is not supported" warning 

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21866]
### Is your enhancement related to a problem? Please describe

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/606959/205930630-07c9c36b-14ad-4530-bd59-7c76683d345a.png">

Although current default editor (VS Code) works perfectly fine on Safari and Edge browsers we are warning users to switch to Chrome instead.

### Describe the solution you'd like

- [ ] Stop showing this warning message.
- [ ] Stop mentioning Chrome and Firefox as the only supported browsers in documentation

**Comment by ibuziuk** [comment]
@max-cx in the next sprint we are going to delete the warning, Please check and update the docs related to the supported browsers section accordingly

**Comment by ibuziuk** [comment]
@akurinnoy once the warning is removed could you please backport in 7.58.x

**Comment by max-cx** [comment]
@osslate, this is the upstream issue for https://issues.redhat.com/browse/RHDEVDOCS-4754. I'm

**Comment by ibuziuk** [comment]
@max-cx PRs for dashboard have been sent and are going to be merged today
- https://github.com/eclipse-che/che-dashboard/pull/701
- https://github.com/eclipse-che/che-dashboard/pull/702

could you please make sure that the docs are updated accordingly for 3.4 ?

**Comment by max-cx** [comment]
The docs were successfully updated on this subject in https://github.com/eclipse-che/che-docs/pull/2534. No explicit mentions of the warning UI element found in the docs. This docs side of this issue is resolved.

**Comment by ibuziuk** [comment]
thank you. closing as done
