### ISSUE TITLE
Invalid CSRF token error during authentication: OAuth2 Proxy update needed

### ISSUE THREAD

**Issue by timurkhis** [eclipse/che#21861]
### Describe the bug

Che operator depends on deprecated version of oauth2-proxy which causes SSO issues with csrf token.

Here is a well known third-party bug coming from oauth2-proxy 7.2.0 (currently used by che-operator):
https://github.com/oauth2-proxy/oauth2-proxy/issues/817

The fix is merged and included in version 7.4.0:
https://github.com/oauth2-proxy/oauth2-proxy/pull/1708

Could you please upgrade the oauth2-proxy dependency version?

Original issue:

1. Configure the Che instance to use and SSO authentication service (for example Okta);
2. Open one tab to the Che address and wait for the login form to appear;
3. Open a second tab to the same Che;
4. Log in in one of the tabs;

Expected result: the login process is successful
Actual result: unhandled error is returned: Login Failed: Unable to find a valid CSRF token. Please try again

### Che version

7.57@latest

### Steps to reproduce

1. Configure the Che instance to use and SSO authentication service (for example Okta);
2. Open one tab to the Che address and wait for the login form to appear;
3. Open a second tab to the same Che;
4. Log in in one of the tabs;

Expected result: the login process is successful
Actual result: unhandled error is returned: Login Failed: Unable to find a valid CSRF token. Please try again

### Expected behavior

Login success

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

microk8s

**Comment by tolusha** [comment]
@timurkhis 
Pls, have a look https://github.com/eclipse-che/che-operator/pull/1574
