### ISSUE TITLE
Confusing error message when creating a workspace from an unsupported git service (Gitee)

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#21863]
### Describe the bug

When l open a workspace based git server (https://gitee.com/greenTao/test-che/tree/master) it tips : 'Cannot build factory with any of the provided parameters. Please check parameters correctness, and resend query.'

### Che version

7.58.0-SNAPSHOT

### Steps to reproduce

see in screenshots 

### Expected behavior

open a workspace

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/13027592/205611631-5f54c0f9-2ac6-40ac-8608-7a80a4df4d2b.png)

![image](https://user-images.githubusercontent.com/13027592/205611693-d3a20266-3cc2-44e3-b9c1-fa72b327618f.png)

![image](https://user-images.githubusercontent.com/13027592/205611744-7c2dee3b-2828-4d64-a769-d5e11ab466d4.png)

### Installation method

chectl/latest

### Environment

Windows

**Comment by l0rd** [comment]
@davidxwwang only github, bitbucket and gitlab are fully supported. 

For other git providers the recommendation is to use an external devfile like this:

```yaml
schemaVersion: 2.1.0
metadata:
  name: test-che
projects:
 - name: test-che
   git:
     remotes:
       origin: https://gitee.com/greenTao/test-che/tree/master
```

For example, in your case, using `<che-hostname>/#https://pastebin.com/raw/4b0FYFRs` will start a workspace.

The second problem that you are going to face is that `git clone` will fail as non authorized (since you repository requires authentication and is not hosted on github/gitlab/bitbucket for which we support OAuth flow). To solve that you should use a [git credential store](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-credentials-store).

**Comment by l0rd** [comment]
cc @max-cx I don't think we document how to use git services other than GitHub, Gitlab and Bitbucket. This kind of question comes up often. 

cc @olexii4 @vinokurig we should provide a better error message that explains the problem (gitee.com is not fully supported) and the workaround (use an external devfile) with a link to the documentation.

**Comment by davidxwwang** [comment]
> cc @max-cx I don't think we document how to use git services other than GitHub, Gitlab and Bitbucket. This kind of question comes up often.
> 
> cc @olexii4 @vinokurig we should provide a better error message that explains the problem (gitee.com is not fully supported) and the workaround (use an external devfile) with a link to the documentation.

hi @l0rd ，thanks your answer， l also have another question， when l open [https://192.168.49.2.nip.io/#https://pastebin.com/raw/Dsn95STF](url)， the workspace can open successfully，
then l want a customed  ide， so l open [https://192.168.49.2.nip.io/#https://pastebin.com/raw/Dsn95STF?che-editor=https://pastebin.com/raw/4HyaMKNY](url)， the workspace cannot generate, and tips : The new Workspace couldn't be created from the Devfile in the git repository ..., so did l do something wrong，thanks！


![e](https://user-images.githubusercontent.com/13027592/205932302-b35809b8-d7b0-4531-871e-1cee67f99fef.PNG)

**Comment by davidxwwang** [comment]
> ```yaml
> schemaVersion: 2.1.0
> metadata:
>   name: test-che
> projects:
>  - name: test-che
>    git:
>      remotes:
>        origin: https://gitee.com/greenTao/test-che/tree/master
> ```
> 
> For example, in your case, using `https://<che-hostname>/#https://pastebin.com/raw/4b0FYFRs` will start a workspace.
> 
> The second problem that you are going to face is that `git clone` will fail as non authorized (since you repository requires authentication and is not hosted on github/gitlab/bitbucket for which we support OAuth flow). VS Code will start but the source code won't be cloned at startup. To solve that you should use a [git credential store](https://www.eclipse.org/che/docs/stable/end-user-guide/using-git-credentials/#using-a-git-credentials-store) and git clone will work at startup.

@l0rd
