### ISSUE TITLE
Update Traefik to 2.9.6 version

### ISSUE THREAD

**Issue by framar89** [eclipse/che#21869]
### Summary

Currently the default image version used for traefik is quay.io/eclipse/che--traefik:v2.8.1-4e52a5e2495484f5e19a49edfd2f652b0bce7b3603fa0df545ed90168ffae1c3 which has a critical vulnerability as showed in https://quay.io/repository/eclipse/che--traefik?tab=tags
I ran a security scan using Trivy (https://trivy.dev/results/?image=traefik:v2.8.2) for the Dockerhub image traefik:v2.8.2 and it tells that there are no vulnerabilities.

So my questions are:
- Can traefik be updated to at least 2.8.2? It's a build update, so I don't expect any breaking changes.
- I saw that the image can be customized in Eclipse Che CRD so that I can temporarily use the one provided by Dockerhub (traefik:v2.8.2). Is it compatible? Do I need to change anything else?
- Are there any differences from the images in https://quay.io/repository/eclipse/che--traefik and the corresponding traefik in Dockerhub?

Thanks

**Comment by framar89** [comment]
Unfortunately traefik:v2.8.2 does not work but I tried traefik:v2.9.5 (released 20 days ago) and it worked.

So, I think you can update to v2.9.5.

**Comment by tolusha** [comment]
Any particular issue did you face?
I've tried with`traefik:v2.8.2` image on OpenShift v4.11 cluster and successfully logged in and created a workspace.

**Comment by tolusha** [comment]
`traefik:v2.8.2` does not work for me either.
The latest greates `traefik:v2.9.6` works fine for me. I will open a PR to switch to the new image.

**Comment by nickboldt** [comment]
Upstream steps:
* configure https://github.com/eclipse-che/che-release/blob/main/utils/copyImagesToQuay.txt, run https://github.com/eclipse-che/che-release/blob/main/utils/copyImagesToQuay.sh
* update refs to traefik in operator csv, docs, etc.

Downstream steps:
* update https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-traefik/container.yaml and forked traefik content in https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-traefik/ from latest
* see if it builds
* iterate
* get an SME in what traefik actually does (@tolusha ?) to verify the resulting 3.4 build does what it's expected to do with respect to what Traefik did before/after the change.
