### ISSUE TITLE
Update oauth2-proxy image to `quay.io/oauth2-proxy/oauth2-proxy:v7.4.0`

### ISSUE THREAD

**Issue by framar89** [eclipse/che#21876]
### Summary

Currently the default image version used for oauth2-proxy is quay.io/oauth2-proxy/oauth2-proxy:v7.2.0 which has a critical vulnerability as shown in https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags

In quay.io there is also version 7.4.0 which is the latest version released and has no vulnerabilities (https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags).

There are no breaking changes from 7.2 and 7.4 (https://github.com/oauth2-proxy/oauth2-proxy/releases), I also tested it and it worked the same as v7.2.0.

Oauth-proxy is an important component for Eclipse-Che because it handles the authentication, so can it be updated?

Thanks

**Comment by ibuziuk** [comment]
@tolusha could you please take a look?

**Comment by tolusha** [comment]
Already updated to v7.4.0
https://github.com/eclipse-che/che-operator/blob/8ef15f948908e1e11b3ba1ba020c836fbf7d894d/config/manager/manager.yaml#L86-L87
