### ISSUE TITLE
custom ide using url parameter fail with ‘CORS error’

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#21871]
### Describe the bug

when  using url parameter to custom a theia-based IDE  [https://192.168.49.2.nip.io/#https://pastebin.com/raw/Dsn95STF?che-editor=https://pastebin.com/raw/ZDNU2tkr](url)  , but fail with ‘CORS error’

### Che version

next (development version)

### Steps to reproduce

1. deploy che successfully.
2. open [https://192.168.49.2.nip.io/#https://pastebin.com/raw/Dsn95STF?che-editor=https://pastebin.com/raw/ZDNU2tkr](url)
3. **get CORS error**

### Expected behavior

could open a workspce

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/13027592/206350921-3492459c-cfc8-467f-a70d-c1bdbf70ecf5.png)

![image](https://user-images.githubusercontent.com/13027592/206350922-f5ab83ea-a438-426c-a296-0bc76188ee7a.png)

### Installation method

chectl/next

### Environment

Windows

**Comment by nickboldt** [comment]
See https://www.bannerbear.com/blog/what-is-a-cors-error-and-how-to-fix-it-3-ways/

Coud be because you're using pastebin to serve a reference to https://gitee.com/ instead of just putting your devfile in the gitee project.

**Comment by ibuziuk** [comment]
@davidxwwang thanks for reporting the issue? can you start a workspace using the same devfile but stored on [gist](https://gist.github.com/) ? According to the screenshot dashboard loaded devfile correctly from pastebin, so wondering maybe the problem is with devfile itself

**Comment by davidxwwang** [comment]
hi , you are right,the url is:https://192.168.49.2.nip.io/#https://pastebin.com/raw/Dsn95STF?che-editor=https://pastebin.com/raw/ZDNU2tkr
and the content of https://pastebin.com/raw/ZDNU2tkr begins with "inline"（l store the some content in gist）, l guess may be caused by this, l will check
laster, but l am confused why the brower tips: CORS，thanks for your reply！
it later,e




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Ilya ***@***.***&gt;;
Send time:&nbsp;Tuesday, Dec 13, 2022 1:08 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [eclipse/che] custom ide using url parameter fail with ‘CORS error’ (Issue #21871)





 
@davidxwwang thanks for reporting the issue? can you start a workspace using the same devfile but stored on gist ? According to the screenshot dashboard loaded devfile correctly from pastebin, so wondering maybe the problem is with devfile itself
