### ISSUE TITLE
the workspace running but cannot open a IDE using a custom ide url parameters

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#21872]
### Describe the bug

when opening `https://192.168.49.2.nip.io/#https://pastebin.com/raw/NBN7iGDN?che-editor=https://gist.githubusercontent.com/davidxwwang/c9c52be4c4f4a55d9376c3764a567d27/raw/3ace5b494fe035fadc30dadc60c2836b92cdbbe4/demoIDE.yaml` ， the workspace status is running but cannot open a custome IDE ，and tip : the workspace has not received a ide URL ...

### Che version

next (development version)

### Steps to reproduce

1. deploy che
2. open `https://192.168.49.2.nip.io/#https://pastebin.com/raw/NBN7iGDN?che-editor=https://gist.githubusercontent.com/davidxwwang/c9c52be4c4f4a55d9376c3764a567d27/raw/3ace5b494fe035fadc30dadc60c2836b92cdbbe4/demoIDE.yaml` 

### Expected behavior

open a IDE

### Runtime

minikube

### Screenshots

![bb](https://user-images.githubusercontent.com/13027592/206371862-49a9c1ba-70a2-4df5-b2ed-6eb1082da563.png)

### Installation method

chectl/next

### Environment

Windows

**Comment by davidxwwang** [comment]
@azatsarynnyy the content of `https://gist.githubusercontent.com/davidxwwang/c9c52be4c4f4a55d9376c3764a567d27/raw/3ace5b494fe035fadc30dadc60c2836b92cdbbe4/demoIDE.yaml` is coped from [https://github.com/azatsarynnyy/java-spring-petclinic/blob/cf26cfe40c52026c5ebe2021b032774b96f81801/.che/che-editor.yaml](url) can you help me check if l make some mistakens somewhere， thanks！

**Comment by azatsarynnyy** [comment]
@davidxwwang I'd say in 99% of the cases you can see that message because pulling the image takes too much time. 
You can pre-pull the images declared in your yaml file by something like:
```
$ eval $(minikube docker-env)
$ docker pull ...
```

**Comment by davidxwwang** [comment]
> 

@azatsarynnyy l thought l already pre-pull all requred images(see below) by checkout the workspace pod in user workspace,so is something wrong with the custom ide( l can run docker container with  the custem ide image success in the 127.0.0.0:3000 in my computer), so l donot know how to fix it as l am a newer of che and k8s, thanks!

![Screenshot 2022-12-09 110428](https://user-images.githubusercontent.com/13027592/206615075-2da897cd-0f6c-46ea-a045-7568c197ee68.png)

**Comment by davidxwwang** [comment]
> Can you clarify why you're using `quay.io/azatsary/che-theia:filter` instead of an official image?
> 
> Perhaps try https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml as your devfile, which pulls official Che images.
> 
> Also I'm not sure if `che-editor=` works with any arbitrary URL, only with keys:
> 
> * https://www.eclipse.org/che/docs/stable/end-user-guide/url-parameter-for-the-workspace-ide/
> * https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.2/html-single/user_guide/index#url-parameter-for-the-workspace-ide
> 
> So the simpler path would be:
> 
> * create up a git project with the sources you want to open - https://gitee.com/greenTao/test-che.git
> * put a devfile.yaml file in its root folder - https://gitee.com/greenTao/test-che/tree/main/devfile.yaml
> * add a .che/che-editor.yaml file https://www.eclipse.org/che/docs/stable/end-user-guide/selecting-a-workspace-ide/
> * commit changes - https://gitee.com/greenTao/test-che/tree/main/.che/che-editor.yaml
> * point your cluster at the project, eg., https://192.168.49.2.nip.io/#https://gitee.com/greenTao/test-che.git

@nickboldt beacuse l want to use my custom theia-base IDE,not the default. it works for me using che-editor=<editor_key> (editor_key is pre-defined)， when l try to open https://gitee.com/greenTao/test-che.git in https://192.168.49.2.nip.io/dashboard/#/create-workspace, 
it tips : Cannot build factory with any of the provided parameters. Please check parameters correctness, and resend query. and the Git credentials already set(l can open a IDE 
 using https://192.168.49.2.nip.io/#https://pastebin.com/raw/NBN7iGDN, which refer to https://gitee.com/greenTao/test-che.git) ,so l donot know how to fix it. thanks
