### ISSUE TITLE
Add scripts to prepare test GitHub Enterprise Server on AWS

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21875]
### Is your task related to a problem? Please describe

https://github.com/che-incubator/git-srv/blob/main/github/deploy_github.adoc is actually describing steps to install GitHub Enterprise Server using VirtualBox on local machine, which can't be used in automated PR check using GitHub action.

Also, installation using VirtualBox is flaky and resource consuming + requires support of public IP and DNS server to configure subdomain isolation.

### Describe the solution you'd like

Add automation scripts to repo [1] to install GitHub Enterprise Server on AWS for testing purpose.

[1] https://github.com/che-incubator/git-srv/blob/main/github/deploy_github.adoc

### Additional context

Related issues: 
- https://github.com/eclipse/che/issues/21753
- https://issues.redhat.com/browse/CRW-3509

**Comment by vinokurig** [comment]
The instructions are already written by GitHub https://docs.github.com/en/enterprise-server@3.7/admin/installation/setting-up-a-github-enterprise-server-instance/installing-github-enterprise-server-on-aws

**Comment by vinokurig** [comment]
I don't think so, the che-incubator instructions describe a way to install the server on virtualbox environment.

**Comment by dmytro-ndp** [comment]
@vinokurig: got it.

The issue is renamed correspondingly.
