### ISSUE TITLE
Update default Postgresql version

### ISSUE THREAD

**Issue by framar89** [eclipse/che#21881]
### Summary

The default Postgresql installed with Eclipse Che is
quay.io/eclipse/che--centos--postgresql-13-centos7:1-71b24684d64da46f960682cc4216222a7e4ed8b1a31dd5a865b3e71afdea20d2 which has a lot of critical and high vulnerabilities (see scans https://quay.io/repository/eclipse/che--centos--postgresql-13-centos7?tab=tags&tag=latest and https://trivy.dev/results/?image=quay.io/eclipse/che--centos--postgresql-13-centos7:1-71b24684d64da46f960682cc4216222a7e4ed8b1a31dd5a865b3e71afdea20d2).

Can it be updated?

I can temporarily set the container image in Eclipse Che CR. Is there an image you can suggest (something compatible with the current env variables, volumes, etc)?
I'm also considering creating a new managed DB (AWS) and connecting Eclipse Che to it. What happens to the data already present in the internal DB? Is the change transparent to the user?

Thank you.

**Comment by ibuziuk** [comment]
@framar89 thanks for reporting the issue. In general, the plan is to remove Postgres completely in a few releases as part of https://github.com/eclipse/che/issues/21864 PR for the first phase has been opened already - https://github.com/eclipse-che/che-server/pull/398
@tolusha in the meantime wdyt can we update the image?

**Comment by tolusha** [comment]
@ibuziuk 
I won't invest into that, since PostgreSQL component will be removed eventually.

**Comment by ibuziuk** [comment]
fair enough @framar89 for the time being we plan to fully remove the database operand in `7.61` upstream version

**Comment by tolusha** [comment]
Closed as won't fix since PostgreSQL component is going to be removed in future versions.
