### ISSUE TITLE
Allow configuring ephemeral storage strategy in CheCluster

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#21885]
### Is your enhancement related to a problem? Please describe

Currently it is not possible to configure the use of the Ephemeral storage strategy as the default storage strategy for Che workspaces through the Che Cluster CR.

### Describe the solution you'd like

The Che Cluster CR `devEnvironments.storage.pvcStrategy` should allow for the `ephemeral` storage strategy.

The Dashboard already supports reading the configured storage type from the Che Cluster CR, and I believe there is already code in place that would allow support for the ephemeral storage strategy (I may be mistaken however).

### Describe alternatives you've considered

Currently, it is only possible to use the ephemeral storage strategy on a per-workspace basis by changing the storage-type settings in the dashboard. 
![image](https://user-images.githubusercontent.com/10300119/207390662-19296067-b341-4579-8a6c-7e719f0d29d3.png)

There is no way to set the ephemeral storage strategy to be used by all newly created workspaces. 

### Release Notes Text

It's now possible to specify ephemeral as the default storage strategy for every workspace through the CheCluster custom resource.

**Comment by tolusha** [comment]
Should be fixed by https://github.com/eclipse-che/che-operator/pull/1580

**Comment by l0rd** [comment]
@AObuchow if you haven't yet can you double check if we need to update some documentation articles that mentions storage strategies?

**Comment by AObuchow** [comment]
@l0rd It seems the Che administration documentation needs to be updated to mention storage strategies: https://www.eclipse.org/che/docs/stable/administration-guide/configuring-storage/

Additionally, the section on [configuring storage classes](https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-using-storage-classes/) needs to be updated as well: it mentions that the Che Server is in charge of creating persistent volume claims (this is now handled by DWO), and also points to slightly outdated fields in the Che Cluster CR (`devEnvironments.storage.pvc.storageClass` instead of `devEnvironments.storage.perWorkspaceStrategyPvcConfig.storageClass` or `devEnvironments.storage.perUserStrategyPvcConfig.storageClass`)

I will work on a PR to update this section of the documentation. Let me know if there are any procedures I should follow or if there are members of the documentation team that I should contact, as this is my first time updating the Che Docs.

**Comment by max-cx** [comment]
ACK. Thank you for the PR to the docs repo, Andrew. A technical writer will self-assign it to review it toward [RHDEVDOCS-4870](https://issues.redhat.com/browse/RHDEVDOCS-4870).

**Comment by max-cx** [comment]
RN sync'd to Red Hat Jira https://issues.redhat.com/browse/CRW-4183
