### ISSUE TITLE
DeleteOAuthToken API method doesn't work properly

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21890]
### Describe the bug

The deleteOAuthToken API method doesn't work properly. 

```
https://github.com/eclipse-che/che-server/blob/main/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java#L334
```

### Che version

7.57@latest

### Steps to reproduce

1. Deploy CHE.
2. [Added OAuth for GitHub, GitLab, and Bitbucket](https://www.eclipse.org/che/docs/stable/administration-guide/oauth-for-github-gitlab-or-bitbucket/ ).
3. Create a new workspace from the private repository.
4. Delete the created workspace.
5. Open che-server swagger {CHE-host}/swagger and delete OAuth token.
![Знімок екрана 2022-12-15 о 16 33 57](https://user-images.githubusercontent.com/6310786/207889765-39db1a3a-fef8-44b3-a1cd-f6934949eee0.png)
6.  Create a new workspace from the same private repo. You should be redirected to the login flow again.

### Expected behavior

The current git session should be expired after deleting the OAuth token.

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS

**Comment by vinokurig** [comment]
The PR is relevant only for GitHub case. GitLab and Bitbucket don't have the necessary API to revoke oAuth app token. An exception is thrown for the unsupported providers, so dashboard can handle it by viewing a notification.
