### ISSUE TITLE
Checode is failing to run with a custom image without libbrotlidec.so.1 and libcrypto.so.1.1 

### ISSUE THREAD

**Issue by sunix** [eclipse/che#21895]
### Describe the bug

I could not run my workspace that was using a custom image based on ubuntu.
The container log:
```
nohup: appending output to 'nohup.out'
using OPENVSX_URL=https://devspaces.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/openvsx/vscode
Node.js dir for running VS Code: /checode/checode-linux-libc
/checode/checode-linux-libc/node: error while loading shared libraries: libbrotlidec.so.1: cannot open shared object file: No such file or directory
```
I then installed libbrotlidec but got another missing lib:  libcrypto.so.1.1

It seems that there is a workaround with https://github.com/eclipse/che/issues/21629 but it was not easy to find it. The only error that Che is showing is a CrashLoopBackError which is not helping. It needs some expertise and investigation to find the problem

### Che version

7.56

### Steps to reproduce

1. start a devfile with `ubuntu` as main container
2. observe CrashLoopBackOff error

### Expected behavior

To me there are 2 things to fix:

1. Che should in the log display the error container log with the current the embedded nodejs used. At the moment it doesn't show anything even in verbose mode ... (see screenshot)

2. Che should also help the user with a resolution hint message, like
    > The Nodejs embeded with checode could not start because of missing libraries. Please include these libraries to your contaner image or tell CheCode to use a nodejs 16  binary installed in the container image with the environment variable VSCODE_NODEJS_RUNTIME_DIR. See https://github.com/che-incubator/che-code/pull/120
    
    (maybe could be display by the script /checode/entrypoint-volume.sh)

### Runtime

OpenShift

### Screenshots

 ![Selection_781](https://user-images.githubusercontent.com/650571/208453256-1dd805ce-1ee6-4d0a-aa0a-c75bf098d1ba.png)

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by meanderix** [comment]
I could reproduce this bug by using the image `docker.io/debian:bullseye`.
