### ISSUE TITLE
Che-server: Increase the maximum size of the request and response HTTP header to 32 KB

### ISSUE THREAD

**Issue by karatkep** [eclipse/che#21898]
### Is your enhancement related to a problem? Please describe

Tomcat restricts the maximum size of the request and response HTTP header. Default value is set to 8192 (8 KB). 
But in some cases we need to send more than 8 KB in HTTP request header. For example, this is actual in case Azure Active Directory when oauth token is quite big.

### Describe the solution you'd like

Adjust tomcat configuration to increase the maximum size of the request and response HTTP header to 32 KB.

**Comment by ibuziuk** [comment]
PR has been merged and the fix would be part of the 7.59.0 release. Closing
