### ISSUE TITLE
Image Puller Operator is failing on large clusters

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21899]
### Describe the bug

Image Puller Operator is failing on large clusters after installation

### Che version

7.58@latest

### Steps to reproduce

1. Setup a cluster with 3K+ namespaces
2. install the image puller operator 
3. ERROR: operator pod keeps restarting 

### Expected behavior

Image puller operator installs without problems on clusters with 5K namespaces

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Eclipse Che Logs

```shell
container logs


I1220 11:33:26.732542 1 trace.go:205] Trace[1120032457]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167 (20-Dec-2022 11:32:25.374) (total time: 61357ms):
Trace[1120032457]: [1m1.357796456s] [1m1.357796456s] END
E1220 11:33:26.732564 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 329; INTERNAL_ERROR
```
```


### Additional context

_No response_

**Comment by tolusha** [comment]
Fixed in Kubernetes Image Puller 1.0.4
