### ISSUE TITLE
'Limiting the number of workspaces that a user can keep' is not working

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21912]
### Describe the bug

According to the documentation, the maximum number of workspaces a user can keep can be set by the admin in the checluster CR:https://www.eclipse.org/che/docs/stable/administration-guide/limiting-the-number-of-workspaces-that-a-user-can-keep/

When following the steps on the documentation, users are still able to have more workspaces than the limit set by the admin.

### Che version

next (development version)

### Steps to reproduce

Reproduced on minikube and openshift

For minikube:
1. Run `chectl server:deploy -p minikube`
2. Set the workspaces limit to 2 by running `kubectl patch checluster/eclipse-che -n eclipse-che --type='merge' -p '{"spec":{"components":{"cheServer":{"extraProperties":{"CHE_LIMITS_USER_WORKSPACES_COUNT": "2"}}}}}'`
3. Open the che dashboard `chectl dashboard:open` and log in as user: `userN@che` password: `password`
4. Create three workspaces

### Expected behavior

I'm not quite sure, but either
* this feature is deprecated since the DWO manages the workspace lifecycle, therefore the page from the docs should be removed, or
* this feature should still work, and should prevent the user from having more than 2 workspaces.

In the che-server repository, there is code that seems to check if the current workspace can be created ([PR](https://github.com/eclipse-che/che-server/pull/78/files), [on main branch](https://github.com/eclipse-che/che-server/blob/a97e6eec909b2ee156b2f4b6d748676ea87c0134/multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java#L107-L135)) 

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/next

### Environment

macOS

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/21860
