### ISSUE TITLE
Unlimit the number of workspace that use can run by default

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21933]
### Is your task related to a problem? Please describe

Currently user can run only 1 workspace.
It is not handy and users always ask how to increase this value.
I believe we have to unlimit the number of workspace that use can run by default.

### Describe the solution you'd like

Unlimit the number of workspace that use can run by default

**Comment by ibuziuk** [comment]
the problem is that with the default 'common' PVC strategy and RWO volumes, one can not reliably run multiple workspaces simultaneously
