### ISSUE TITLE
How to run customized che-theia

### ISSUE THREAD

**Issue by OseYuuto** [eclipse/che#21934]
### Summary

I'm Trying to run customized che-theia.
but, the commands in [this](https://github.com/eclipse-che/che-theia/blob/main/CONTRIBUTING.md) do not found.
`chectl workspace:start -f devfiles/che-theia-dev.devfile.yaml`

What is the best way to customize and run che-theia?
Or, is the documentation available somewhere?

### Relevant information

Local minikube version: v1.28.0 (Windows Hyper-V)
chectl/0.0.20230109-next.ad40405 win32-x64 node-v16.13.2

**Comment by tolusha** [comment]
@OseYuuto 
Workspace commands have been removed after switching to Dev Workspace engine.
There is a draft PR [1], that describes how to manage workspaces with kubectl

[1] https://github.com/eclipse-che/che-docs/pull/2510
