### ISSUE TITLE
Documentation Missing for "Add Che specific attributes in addition to the generic devfile specification."

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#21932]
### Summary

Is there somewhere that we can go to learn about "Add Che specific attributes in addition to the generic devfile specification"?

Even if it's source code, I'd like to explore the Che specific customizations/configurations available in a devfile.

### Relevant information

The link: [https://www.eclipse.org/che/docs/stable/end-user-guide/customizing-workspace-components/](https://www.eclipse.org/che/docs/stable/end-user-guide/customizing-workspace-components/) contains an inactive reference to a future document: "Add Che specific attributes in addition to the generic devfile specification."

**Comment by tolusha** [comment]
@cgruver 

Pls, have a look if it can help you
[1] https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-devEnvironments-settings

**Comment by cgruver** [comment]
Thanks @tolusha 

I'm familiar with the configuration that can be applied to the CheCluster CR.  I'm specifically interested in Che specific configurations that a user can apply from within their devfile.yaml.
