### ISSUE TITLE
Mention, in che-incubator org, that Eclipse Che is a registered trademark of the Eclipse Foundation

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21944]
### Is your task related to a problem? Please describe

The che-incubator GitHub organization is not managed by the Eclispe Foundation hence we should clearly mention that "Eclipse Che" is a registered trademark.

### Describe the solution you'd like

- Add a line in the organisation comment that states "Che" is a registered trademark of the Eclipse Foundation;
- Add the same trademark statement in the README for each repository;
- Add an "®" after the word "Che" in the title; and
- Change "Che" to "Eclipse Che®" in the first, and all prominent occurrences in the org and all repositories.

**Comment by l0rd** [comment]
`"Che" is a trademark of the Eclipse Foundation` in a ["Trademark" section as done for Theia](https://github.com/eclipse-theia/theia#trademark) should work.

**Comment by nickboldt** [comment]
> `"Che" is a trademark of the Eclipse Foundation` in a ["Trademark" section as done for Theia](https://github.com/eclipse-theia/theia#trademark) should work.

Isn't the project name "Eclipse Che", not just "Che" ? 

![image](https://user-images.githubusercontent.com/227597/234882313-f1d167e0-c865-4d5f-889b-96c10bffbec8.png)


https://www.eclipse.org/che/

I am not a lawyer or a trademark expert, but seems weird to just say "Che is a trademark" ... are we sure that's the string that was trademarked, and not the full name "Eclipse Che" ?
