### ISSUE TITLE
Failed to open the workspace

### ISSUE THREAD

**Issue by OseYuuto** [eclipse/che#21945]
### Summary

I deployed che at local minikube.

I get an error when I create a workspace from the dashboard.
The error varies depending on the sample selected.

Starting workspace empty
```
Initializing DevWorkspace
Preparing networking
Waiting for workspace deployment
Container universal-developer-image has state ImagePullBackOff
```

spring-petclinic
```
Container mariadb has state CrashLoopBackOff
Initializing DevWorkspace
Preparing networking
Waiting for workspace deployment
Init Container remote-runtime-injector has state CrashLoopBackOff
```

Starting workspace react
```
Initializing DevWorkspace
Storage ready
Preparing networking
Preparing services
Preparing ingresses
Networking ready
Waiting for DevWorkspace ServiceAccount
Waiting for workspace deployment
Init Container remote-runtime-injector has state CrashLoopBackOff
```

Is there a problem with che deploy?

### Relevant information

Local minikube version: v1.28.0 (Windows Hyper-V)
chectl/0.0.20230109-next.ad40405 win32-x64 node-v16.13.2

**Comment by ibuziuk** [comment]
@tolusha could you please take a look?

**Comment by tolusha** [comment]
@OseYuuto 
* Could you provide a command line how did you start your minikube cluster?
* Try to update `chectl` to the latest version with `chectl update` command.

**Comment by OseYuuto** [comment]
@tolusha 
minikube start
`minikube start --addons=ingress,dashboard --vm=true --memory=8192 --cpus=8 --disk-size=20GB --kubernetes-version=v1.23.9 --driver=hyperv`

che deploy
```
 chectl server:deploy -p minikube --k8spodreadytimeout=120000
```

**Comment by OseYuuto** [comment]
@tolusha 
I try `chectl update`
chectl/0.0.20230119-next.0b3e50c win32-x64 node-v16.13.2

but the result is same error.

**Comment by OseYuuto** [comment]
@tolusha 
After several runs, the following error may have occurred.
```
The workspace status remains "Starting" in the last 300 seconds.
```

**Comment by tolusha** [comment]
I wasn't able to reproduce `ImagePullBackOff` issue.  It can be related to networking or quay.io.
With regard to `The workspace status remains "Starting" in the last 300 seconds.`, increase workspace startup timeout with the following command:
 
`kubectl patch checluster eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devEnvironments/startTimeoutSeconds", "value": 3000}]'`

I try to increase that value by default for minikube platform: https://github.com/che-incubator/chectl/pull/2498

**Comment by OseYuuto** [comment]
@tolusha 
I was able to pull from `quay.io/devfile/universal-developer-image` in minikube.
`docker pull quay.io/devfile/universal-developer-image`
Probably not a network problem.

**Comment by tolusha** [comment]
@OseYuuto
What about `The workspace status remains "Starting" in the last 300 seconds.` problem?
Were you able to solve it?

**Comment by OseYuuto** [comment]
@tolusha 
I change to `--disk-size=50GB` and run `minikube ssh docker pull quay.io/devfile/universal-developer-image:ubi8-38da5c2`
It works.

**Comment by ibuziuk** [comment]
@OseYuuto glad that it worked for you. Can we close the issue now?
