### ISSUE TITLE
Support reading devfiles from private repos other than GitHub/GitLab/Bitbucket/Azure

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21951]
### Is your enhancement related to a problem? Please describe

When the developer provides a **private git repo** HTTP URL (i.e. `https://<che-host>/#<git-repo-http-url>`), Eclipse Che looks for a `devfile.yaml` at the root of it and creates the corresponding `DevWorkspace`. 

But that works only for GitHub, GitLab or Bitbucket and only if the git service has been previously configured (OAuth App or PAT). For other git services such as:
- [gerrit](https://www.gerritcodereview.com/)
- [gogs](https://gogs.io/)
- [gitea](https://gitea.io/)
- [gitolite](https://gitolite.com)
- [sourcehut](https://sourcehut.org/)

~the `devfile.yaml` will be ignored~ the workspace will fail to start.

### Describe the solution you'd like

- 🟣 [support AzureDevOps OAuth flow](https://issues.redhat.com/browse/CRW-3927)
- #21998
- #21997 
- eclipse-che/che-docs#2566
- #22025
- #22356
- #22488
- #22491
- #22111

### Describe alternatives you've considered

Add OAuth and PAT support for other git services too.

### Additional context

That's an issue for public repos too. But in the case of public repos there is a workaround. Instead of using the common workspace URL (`https://<che-host>/#<git-repo-url>`) the developer should use `https://<che-host>/#<devfile-url>?remotes={<git-repo-url>}`.

**Comment by l0rd** [comment]
related Dev Spaces issue https://issues.redhat.com/browse/CRW-3927

**Comment by ibuziuk** [comment]
@l0rd given that we now support azure and basic OAuth I believe in order to resolve this issue we need to still fix:
- https://github.com/eclipse/che/issues/21997
- update docs with the flow of having token in URL + remote attribute - https://github.com/eclipse-che/che-docs/pull/2566/files#r1122111228

**Comment by l0rd** [comment]
Resolving the devfile using the user git credentials or SSH key is important too (today we can only do that with the PAT). 

But we can focus on those last 2 issues you mentioned, making things more stable and well documented, and use a separate issue for the resolver that uses git credentials or SSH key.

**Comment by l0rd** [comment]
I have created the last issue https://github.com/eclipse/che/issues/22356 (documentation) for this epic.
Note that devfile resolution in the case of SSH+GIT URLs has been moved to a separate issue (it had lower priority compared to the rest).

**Comment by l0rd** [comment]
This issue has been fixed
