### ISSUE TITLE
Do not set priority on container-build SCC when container-build is enabled

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21959]
### Describe the bug

When container builds are enabled for workspaces, the Che Operator will create an SCC to be used by workspace containers. This SCC is [created with a priority of 20](https://github.com/eclipse-che/che-operator/blob/578e9537b7141f5ce2a67d31c9d09af5b0a5c266/pkg/deploy/container-build/container_build.go#L263), which can cause issues in clusters (if the container-build SCC is chosen over an intended SCC).

Initially, the container build functionality required the higher priority SCC in order to correctly associate the SCC with workspace continers. However, since https://github.com/eclipse/che/issues/21770 is resolved, this should no longer be required.

### Che version

7.60@latest

### Steps to reproduce

1. Enable container build functionality by setting `.devEnvironments.disableContainerBuildCapabilites: false` in the CheCluster
2. Start a workspace
3. Check the priority field on the `container-build` SCC

### Expected behavior

SCC should have priority 0 so as to not override other SCCs inadvertently. 

### Runtime

OpenShift

### Installation method

chectl/next, OperatorHub

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
fixed in https://github.com/eclipse-che/che-operator/pull/1606 
Closing
