### ISSUE TITLE
Message "Devfile version 1 found" is shown although project has no Devfile

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21957]
### Is your task related to a problem? Please describe

There's a message reported when a project is loaded with no devfile, which states that:

* Devfile could not be found
* Applying the default config
* Devfile version 1 found, converting it to devfile version 2.1.0.

![image](https://user-images.githubusercontent.com/227597/214902282-303ccae1-f8b1-4bf7-ba81-fbc150110b60.png)

### Describe the solution you'd like

If v2.1 is the curent default, then why are we using a v1 default for workspaces without a devfile, then converting it to 2.1?

Surely we should use a v2.1 devfile from the start and avoid the dependency on the devfile converter API?

### Describe alternatives you've considered

If in fact this is just a bad status message, we could simply remove the note about conversion.

But it's worth making sure we use a default devfile that's already v2.1

### Additional context

screenshot is from dev sandbox, Dev Spaces 3.3.0: https://devspaces.apps.sandbox.x8i5.p1.openshiftapps.com/dashboard/#/load-factory?url=https%3A%2F%2Fgithub.com%2Fnickboldt%2Fwin10-bluetooth-headphones%2F 

Error icon is because I already had this same project open, so ignore that.

**Comment by l0rd** [comment]
Thanks for opening this @nickboldt. I am raising the sev to P1 as this misleading message is shown systematically to new users that are trying Che on their git repository (where they didn't had the chance to include a devfile, yet).

And considered that we support v2.2 of the devfile spec we should say "converting to devfile version 2" (although here there is nothing to convert so the converting message doesn't make any sense).

**Comment by nickboldt** [comment]
I've also seen a similar message when devfile v2.1 is found (?) and loaded from a branch. 

https://devspaces.apps.sandbox.x8i5.p1.openshiftapps.com/dashboard/#/load-factory?url=https%3A%2F%2Fgithub.com%2Fdevspaces-samples%2Fphp-hello-world%2Ftree%2Fdevspaces-3.3-rhel-8

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy folks, just a heads-up we would need to take this issue in the next sprint and backport to 7.60.x

**Comment by nickboldt** [comment]
Seems like a simple thing to fix...

https://github.com/eclipse-che/che-dashboard/pull/714

**Comment by nickboldt** [comment]
I moved the second half of the comment up inside the if block so that it won't echo unless a conversion is actually happening.

But if you have a better solution, happy to review your PR. Was just looking for a simple fix to a confusing error message.
