### ISSUE TITLE
OAuth for Github Enterprise: How to configure subdomain isolation by annotation to the OAuth Secret?

### ISSUE THREAD

**Issue by miboettc** [eclipse/che#21964]
### Summary

The documentation on how to configure OAuth for Github Enterprise without subdomain isolation is missing.

For the configuration of OAuth, the [documentation](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/#applying-the-github-oauth-app-secret) describes how to create a secret with the annotation:

```
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: <github_server_url>
```

However, it is not described how to specify whether the GH Enterprise server runs with or without subdomain isolation. Also the  [documentation](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/#applying-the-github-oauth-app-secret) provides no hint at all.

The documentation does not mention that Github can also be configured through the [CheCluster CR](https://github.com/eclipse-che/che-operator/blob/978a2d39a0af5b9067b18e52e32f1b467a314227/config/crd/bases/org.eclipse.che_checlusters.yaml#L6983) which was introduced with pull request #21724 :
 
```
spec:
  gitServices:
    github:
      - endpoint: 'https://github.com'
        secretName: github-oauth-config
        disableSubdomainIsolation: true 
```

Is `disableSubdomainIsolation` also available as an annotation to the OAuth Secret? 

How do annotation and the fields in the CheCluster CR relate? For example, if in the CheCluster CR a secret is referenced whose annotated endpoint differs from those in the CheCluster CR, which one has precedence?

**Comment by l0rd** [comment]
Thank you @miboettc. You have good points here.

> Is `disableSubdomainIsolation` also available as an annotation to the OAuth Secret?

No, I don't think so. But you are right: other properties are configured with secret annotation so it's confusing to configure `disableSubdomainIsolation` in CheCluster. I would make that property available as annotation in the secret too. @vinokurig what do you think? 

> if in the CheCluster CR a secret is referenced whose annotated endpoint differs from those in the CheCluster CR, which one has precedence?

I would consider that as a configuration error. But that's an error that an admin can easily make and, instead, we should help admins to avoid making mistakes. Hence we should remove `endpoint` and  `disableSubdomainIsolation` from CheCluster `spec.gitServices` and live them in the secret annotations only. @tolusha are you ok with that?

> Also the [documentation](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/#applying-the-github-oauth-app-secret) provides no hint at all.

There should be the documentation for [`spec.gitServices`](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.60.0#spec-gitServices) in the [CheCluster reference](https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/) but for some reason that's not the case cc @tolusha. When we address that we should reference it in the [OAuth secrets doc](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/#applying-the-github-oauth-app-secret) cc  @max-cx

**Comment by tolusha** [comment]
`endpoint` configuration from CheCluster takes precedence by overriding the value in a secret.

> I would consider that as a configuration error. But that's an error that an admin can easily make and, instead, we should help admins to avoid making mistakes. Hence we should remove endpoint and disableSubdomainIsolation from CheCluster spec.gitServices and live them in the secret annotations only. @tolusha are you ok with that?

I  am ok with that. 

> There should be the documentation for [spec.gitServices](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.60.0#spec-gitServices) in the [CheCluster reference](https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/) but for some reason that's not the case

https://github.com/eclipse/che/issues/21970

**Comment by vinokurig** [comment]
>  I would make that property available as annotation in the secret too
We can have it as an optional annotation, created an issue for that https://github.com/eclipse/che/issues/21986

**Comment by tolusha** [comment]
1. `endpoint` field is marked as deprecated and will be removed in a future version.
2. `che.eclipse.org/scm-github-disableSubdomainIsolation` annotation is documented https://github.com/eclipse/che/issues/21986
3. [spec.gitServices](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.60.0#spec-gitServices) is documented here[CheCluster reference](https://eclipse.dev/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-gitServices-settings)

I am closing this issue.
