### ISSUE TITLE
Update dwo samples, tests data, and readme to use vscode instead of theia

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21973]
### Is your task related to a problem? Please describe

As reported in https://issues.redhat.com/browse/CRW-3903 the pod-override sample doesn't work in airgap as is.

But I also noticed that the sample itself uses theia instead of vscode. 

So that sample (and any others using theia) should be updated to use vscode, as we're removing theia support in a future release, and providing examples for how to use an IDE that's no longer shipped w/ Che won't be very helpful to users.

### Describe the solution you'd like

1. Fix the following lines:
https://github.com/devfile/devworkspace-operator/blob/main/samples/pod-overrides.yaml#L4
https://github.com/devfile/devworkspace-operator/blob/main/samples/pod-overrides.yaml#L26-L38

2. check for any other code in the samples folder that refers to theia, and update it too

- [ ] ephemeral-storage.yaml
- [ ] git-clone-sample.yaml 
- [ ] per-workspace-storage.yaml 
- [ ] pod-overrides.yaml 
- [ ] theia-latest-contributions.yaml 
- [ ] theia-latest.yaml 

3. update readme

- [ ] https://github.com/devfile/devworkspace-operator/blob/main/README.md#test-run-controller

4. update test data 

- [ ] pkg/library/flatten/testdata/container-contributions/
- [ ] pkg/library/flatten/testdata/implicit-container-contributions/
- [ ] pkg/library/flatten/testdata/implicit-spec-contributions/
- [ ] pkg/library/flatten/testdata/k8s-ref/
- [ ] pkg/library/flatten/testdata/spec-contributions/
- [ ] pkg/library/lifecycle/testdata/postStart/

**Comment by AObuchow** [comment]
@amisevsk has opened a PR for this topic: https://github.com/devfile/devworkspace-operator/pull/1025

>     1. Fix the following lines:
>        [devfile/devworkspace-operator@`main`/samples/pod-overrides.yaml#L4](https://github.com/devfile/devworkspace-operator/blob/main/samples/pod-overrides.yaml?rgh-link-date=2023-01-31T13%3A05%3A27Z#L4)
>        [devfile/devworkspace-operator@`main`/samples/pod-overrides.yaml#L26-L38](https://github.com/devfile/devworkspace-operator/blob/main/samples/pod-overrides.yaml?rgh-link-date=2023-01-31T13%3A05%3A27Z#L26-L38)

Done: https://github.com/devfile/devworkspace-operator/pull/1025/files#diff-a78b83e95dcfcec43b9928264da752c9bae64bc5a6e8cc2b0194587e03f4b447

>     2. check for any other code in the samples folder that refers to theia, and update it too
* [x]  ephemeral-storage.yaml
* [x]  git-clone-sample.yaml
* [x]  per-workspace-storage.yaml
* [x]  pod-overrides.yaml
* [x]  theia-latest-contributions.yaml
* [ ]  theia-latest.yaml

These have all been modified to use Che Code with the exception of `theia-latest.yaml` (as it is a sample for explicitly using Theia, even if it is no longer supported).


>     3. update readme
>     4. update test data

I've opened 2 issues in the DWO repo for these tasks: https://github.com/devfile/devworkspace-operator/issues/1027 & https://github.com/devfile/devworkspace-operator/issues/1028
