### ISSUE TITLE
Happy path prow v11 test failing consistently for che-dashboard PRs

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21975]
### Is your task related to a problem? Please describe

See test failures here:

https://github.com/eclipse-che/che-dashboard/pull/714
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-dashboard/714/pull-ci-eclipse-che-che-dashboard-main-v11-dashboard-happy-path/1620108652075552768

https://github.com/eclipse-che/che-dashboard/pull/715
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-dashboard/715/pull-ci-eclipse-che-che-dashboard-main-v11-dashboard-happy-path/1620080587312205824

### Describe the solution you'd like

Tests should pass for a trivial change like https://github.com/eclipse-che/che-dashboard/pull/715
 (updating copytright dates)

### Describe alternatives you've considered

disable tests / ignore test failures  (aka "a bad idea")

### Additional context

Discovered while testing PRs for #21957

**Comment by AObuchow** [comment]
Doesn't seem to be a duplicate of https://github.com/eclipse/che/issues/21728 as their error logs seem to differ.

I noticed the following in the CI logs, not sure if this is related to the test failing:
```
 [INFO] Waiting for htpasswd auth to be working up to 5 minutes
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority
error: x509: certificate signed by unknown authority 
```
