### ISSUE TITLE
Workspaces are using old UDI images

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21979]
### Describe the bug

Workspaces end up using very old UDI images. This may be due to switching to using container-contributions, as it means that the original devfile's container is used.

Examples:

* Go sample: Uses `quay.io/devfile/universal-developer-image:ubi8-0e189d9`, which is over a year old ([devfile.yaml](https://github.com/che-samples/golang-example/blob/devfilev2/devfile.yaml))
* Empty workspace: Uses `quay.io/devfile/universal-developer-image:ubi8-38da5c2`, which is 6 months old

Further, the plugin registry contains editor definitions that use out-of-date UDI images as well ([che-editors.yaml](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml)):

* `quay.io/devfile/universal-developer-image:ubi8-13008af` - 3 months old
* `quay.io/devfile/universal-developer-image:ubi8-9436df2` - 9 months old

These images are used for the 'main' container for workspaces which do not specify an image

Finally, installing Che `next` via chectl creates a checluster with 
```
  devEnvironments:
    defaultComponents:
    - container:
        image: quay.io/devfile/universal-developer-image:ubi8-38da5c2
        sourceMapping: /projects
      name: universal-developer-image
```

### Che version

next (development version)

### Steps to reproduce

Start workspaces via the dashboard samples

### Expected behavior

Workspaces should either use UDI images matching the currently installed version of Che (tagged accordingly) or use the `latest` UDI images. We should either

* Add automation to keep UDI tags up to date across all repositories (including sample repositories)
* Use `latest` tags for images in sample repositories
* Add functionality to dashboard to automatically select correct UDI image for currently installed version of Che

Areas that need updating
* UDI images should be built + tagged matching Che releases. Currently, only `ubi8-<commit-hash>` images are available, which makes updating difficult + manual
* Sample repositories (e.g. https://github.com/che-samples/golang-example/blob/devfilev2/devfile.yaml) should use `ubi8-latest` images in their devfiles to avoid needing to constantly update them, or we should add automation to keep these images up to date.
* Chectl needs to automatically get the correct UDI image tag for the current release and use it as the default component
* Plugin registry should get the correct UDI image and use that everywhere

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by nickboldt** [comment]
Sounds like you're looking for an upstream implementation of these two bits of automation/orchestration:

* https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/updateVersionAndRegistryTags.sh#L421-L422

* https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/tagRelease.sh#L176-L186

**Comment by amisevsk** [comment]
That automation would help, but there are some additional issues:

* CheCluster gets old UDI version in default component (would need to update che-operator it seems)
* _All_ repos used for samples need their devfiles to be maintained to grab newer UDI images (or just go with latest?)

**Comment by nickboldt** [comment]
* every 6 weeks we drop a new operator-bundle which points to new udi image (3.5, 3.6, 3.7...) - https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/updateVersionAndRegistryTags.sh
* every 6 weeks we update samples to use new UDI tags - https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/tagRelease.sh#L107-L146

So yeah, you're saying "bring downstream back upstream" :D  


If samples were moved INTO the same devfile registry repo, that would make things simpler... and I'm working on a way to achieve "build my devfile registry from LOCAL devfiles in a folder" rather than "build my devfile registry by parsing meta.yaml to find the other GH repo in which the sample project lives" because that's a use case we essentially have to support in Brew.

**Comment by svor** [comment]
che-samples, che-plugin registry and che-operator were updated to use UDI:latest
