### ISSUE TITLE
Workspaces page blinking on Dashboard

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#21972]
### Describe the bug

There is blinking of the Workspaces page on the dashboard when going to the page from another page.
Please see a short video.

### Che version

7.60@latest

### Steps to reproduce

1. Go to the `Create Workspace` page on the dashboard, for example.
2. Come back to the `Workspaces` page.

### Expected behavior

There is no blinking when going to the `Workspaces` page.

### Screenshots

https://user-images.githubusercontent.com/5676062/215745744-6ac330ca-54e1-47c8-a391-57d5b7d13adf.mp4

### Additional context

I tested it on the dogfooding instance.

**Comment by AObuchow** [comment]
I was also able to reproduce this on the dogfooding instance.

**Comment by RomanNikitenko** [comment]
This is a very annoying bug in daily use...

@olexii4 @akurinnoy 
why does the issue have the `analyzing` status?
is it required significant efforts to fix it?

**Comment by akurinnoy** [comment]
@RomanNikitenko Hi, 

I've added the issue to the backlog. I believe it won't take much time to fix it.
