### ISSUE TITLE
Add .NET 6.0 (LTS) to Universal Developer Image 

### ISSUE THREAD

**Issue by kadel** [eclipse/che#21978]
### Is your enhancement related to a problem? Please describe

I'm always frustrated when I can't run my project  because of the missing runtime :-) 

### Describe the solution you'd like

The UDI should always contain at least the latest LTS versions of tools/runtimes.

Ideally, I should be able to pick what runtime version should be used.

**Comment by svor** [comment]
.Net 6.0 was installed in UDI and should be available with `quay.io/devfile/universal-developer-image:ubi8-a4b664c`
