### ISSUE TITLE
Having issue in accessing Eclipse-che on browser

### ISSUE THREAD

**Issue by Mehmoodhassan** [eclipse/che#21981]
### Summary

Hi Everyone,
Status: new to Eclipse-che
Hardware: Ubuntu VM server
Environment minikube
I have deployed Eclipse che on minkube at ubuntu VM server and Everything seems to be working fine inside that server.

But I want to access this outside from everywhere.

I will be very thankful to you and welcome in advance for your suggestions.

**Comment by nickboldt** [comment]
sounds more like a question about exposing ports / IP address of your minikube instance. https://stackoverflow.com/questions/66088041/how-to-expose-minikube-cluster-to-internet or something?

**Comment by Mehmoodhassan** [comment]
Thanks for your reply @mkuznyetsov  As you know when we deploy eclipse che in minikube it automatically assign a DNS like 192.168.0.1.nip.io . 

In my case as I mentioned I am using ubuntu server I can access this inside that server but need to know I want to access this address https://192.168.0.1.nip.io from from anywhere how can I access this.

**Comment by amisevsk** [comment]
@Mehmoodhassan the address https://192.168.0.1.nip.io is a DNS name for the IP address `192.168.0.1` on your local machine -- see https://nip.io/ for details.

Minikube is intended to be deployed and accessed on one machine. If you are attempting to install Kubernetes to a remote machine (even if it's only isolated by a VM) you will need a different approach to installing Kubernetes, including setting up DNS, etc. You could potentially make it work by running proxy in the VM, but this is not supported in general; see e.g. [this doc](https://faun.pub/accessing-a-remote-minikube-from-a-local-computer-fd6180dd66dd) for potential steps.
