### ISSUE TITLE
Github actions fail for Che-Code on the downloading ripgrep step

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#21982]
### Describe the bug

Github actions fail for Che-Code on the downloading ripgrep

### Che version

7.60@latest

### Steps to reproduce

See [here](https://github.com/che-incubator/che-code/actions/runs/4075780854/jobs/7025141393), for example.

### Expected behavior

Github actions pass successfully.

### Screenshots

<img width="987" alt="image" src="https://user-images.githubusercontent.com/5676062/216401138-0da98bee-e49f-42a6-ada0-b9df3baa04ca.png">

**Comment by azatsarynnyy** [comment]
Should be fixed by setting `GITHUB_TOKEN`
- https://github.com/che-incubator/che-code/pull/170

**Comment by azatsarynnyy** [comment]
Since [the fix](https://github.com/che-incubator/che-code/pull/170) is merged 100% of all [builds are completed successfully](https://github.com/che-incubator/che-code/actions/workflows/image-publish.yml) on the first try :tada:

**Comment by RomanNikitenko** [comment]
Unfortunately I've faced with the same problem again: https://github.com/che-incubator/che-code/actions/runs/4102911504/jobs/7076459122

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/5676062/216955888-336f9c30-380e-4546-85b5-cddc50fec6b2.png">

**Comment by azatsarynnyy** [comment]
I think it's expected, as the job is run against the fork https://github.com/RomanNikitenko/che-code/tree/restartWorkspaceAction
and
> ...workflows from forks do not have access to sensitive data such as secrets...

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by azatsarynnyy** [comment]
Anyway, it would be nice to investigate how to fix it for the jobs running on the PRs opened from the forks.
@RomanNikitenko if you can file a low-priority issue for such case that would be great.

**Comment by azatsarynnyy** [comment]
I see a few more jobs where setting the `GITHUB_TOKEN` should solve the `Request failed: 403` problem.
Provied https://github.com/che-incubator/che-code/pull/174
