### ISSUE TITLE
Implementing a VS Code walkthrough extension for the creation of Devfiles

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#21987]
### Is your task related to a problem? Please describe

In case a user is not familiar with Devfile, the extension should help him to create it.
The extension should  be marketplace oriented, not only being specific to run in Che environment and should work well on the VS Code desktop.

For Che-Code, the extension should be built-in and being ready to use out of the box.

### Describe the solution you'd like

The extension should provide the user something like a wizard ( based on `walkthroughs` contribution ) to help him to:
- create a minimal Devfile, ask the user for the workspace name

- add a container component
  - with specifying the container image
  - with providing CPU and Memory limitations
  - being able to expose ports with specifying protocol
  - being able to specify environment variables
  - with attaching one or more volumes

- add volume component, specify its size; this step probably needs to be shown before adding a container component, as the container is using already defined volume

- add a command with specifying the component in which the command will be run

The last wizard page / the last walkthrough step should be completed with geerating of `devfile.yaml` (or `.devfile.yaml` ) file at the root of the active project and opening it in the editor. If the Devfile is already exists, the user is prompted to override or rename it.

It should be always possible to open the wizard / walkthrough by a command from the command palette.

### Describe alternatives you've considered

If the walkthrough plugin API is not so rich to be able to implement such complex wizard, then may have to use webviews https://code.visualstudio.com/api/extension-guides/webview

### Additional context

As an addition, see
- [walkthrough plugin API](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs)
- [TS devfile API](https://www.npmjs.com/package/@devfile/api)
- [webview plugin API](https://code.visualstudio.com/api/extension-guides/webview)

**Comment by l0rd** [comment]
some notes from our yesterday discussion and other things that came to my mind:
- the walkthrough should help creating a new devfile (editing an existing devfile is out of scope)
- a user should be able to start the walkthrough from the command palette or from the welcome panel (prompting the user if there is no devfile in the project should is out of scope)
- the walkthrough should guide the user adding [container components](https://devfile.io/docs/2.2.0/adding-a-container-component) and [commands](https://devfile.io/docs/2.2.0/adding-commands) (other components type, events and projects are out of scope)
- the walkthrough should not show any `YAML` code, it should generate a `.devfile.yaml` at the root of the active project. If the user wants can
- the schemaVersion of the generated devfile should be `2.2.0` and in general it would be helpful to use [TS devfile API](https://www.npmjs.com/package/@devfile/api)

**Comment by vitaliy-guliy** [comment]
Source code repository https://github.com/vitaliy-guliy/vscode-devfile
The extension binary can be found in Releases section.
 
To test it in your Che workspace
- create a workpace
- open a terminal, using `curl` / `wget` download the binary to your project directory
- in the Explorer view right click on the extension, pick 'Install extension from VSIX'
- open Welcome view, follow Create a Devfile walkthrough

**Comment by l0rd** [comment]
/remove-lifecycle stale

Next steps:
- [ ] Review wording
- [ ] Move to devfile org (require LICENSE change)
- [ ] Publish on open-vsx.org and microsoft marketplace
- [ ] Setup GitHub actions to build vsx and publish it
- [ ] Add it as a built-in extension in che-code

**Comment by ibuziuk** [comment]
Closing extension has been published https://open-vsx.org/extension/Devfile/vscode-devfile
