### ISSUE TITLE
Support URLs with basic authentication when resolving a devfile

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21998]
### Is your enhancement related to a problem? Please describe

There are [git services for which Che cannot resolve the Devfile](https://github.com/eclipse/che/issues/21951).
 
A workaround is to use the raw URL to the devfile. For example for azure devops the following public URL worked:

```
https://dev.azure.com/marioloriedo/a5c3e8ae-6db1-4a4f-8b81-0a8ef12f154b/_apis/git/repositories/317bf9fc-90a2-42d2-884a-2766575892e8/items?path=/.devfile.yaml&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&%24format=octetStream&api-version=5.0&download=true
```

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/606959/218344617-f8c65e4f-c964-4c42-840f-90d4d46ab93b.png">

For private repositories a developer could still use the same workaround but in this case he should include the personal access token in the URL. For example: 

```
https://${PAT}@dev.azure.com/marioloriedo/marioloriedo/_apis/sourceProviders/TfsGit/filecontents?repository=private-repo&commitOrBranch=main&path=/.devfile.yaml&api-version=7.0
```

But the che-server fails to resolve the devfile in this case:

![image](https://github.com/user-attachments/assets/5db43b6e-2afb-4b03-8742-0623b08e3766)

The same URL works fine with `cURL`:

![image](https://github.com/user-attachments/assets/0703ab10-f3c1-4636-bdd7-b252113cf210)

### Describe the solution you'd like

The che-server should be able to resolve the file.

### Additional context

I have also tested with a github.com private repository and the message is different:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/606959/218346053-4768151a-8794-487c-9930-9f6cc34f3962.png">

The URL used was:

```
https://$GH_PAT@raw.githubusercontent.com/<user or organization>/<repo name>/<branch>/.devfile.yaml
```

Che-server should resolve the file In this case too but it doesn't work.

**Comment by netomi** [comment]
@l0rd you added an Azure DevOps Personal Access Token in one of your comments, I would highly suggest to revoke it if its still in use.

**Comment by l0rd** [comment]
Thank you @netomi. The PAT was revoked before I created the issue. But anyway I have updated the description to hide PAT to avoid any security alert.
