### ISSUE TITLE
release che-code builds with every sprint, mapping a :latest tag for each :7.yy.z tag

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21992]
### Is your task related to a problem? Please describe

As we switch to using /latest instead of /insiders as the default version of vscode in Che and DS, we need to have :latest tags in quay.

### Describe the solution you'd like

once per sprint we need to release a :latest image (and a :7.yy.0 image) as we do for all the other che containers. 

Today we only have next and insiders tags:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/227597/217832758-7a3cb704-1e45-47c9-88b1-8e62690a947f.png">

**Comment by svor** [comment]
>Today we only have next and insiders tags:

We have a tag for each released version:
![12](https://user-images.githubusercontent.com/1271546/217839122-b32f7736-e543-4321-a934-ab424e48756c.png)

**Comment by nickboldt** [comment]
PR https://github.com/che-incubator/che-code/pull/181 turned out to be much simpler than I expected :D
