### ISSUE TITLE
The workspace should start even if che-server fails to resolve the devfile

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21997]
### Is your enhancement related to a problem? Please describe

If I try to start a workspace from a private repository but OAuth is not supported (e.g. the repo is AzureDevOps) and I get the following error:

```
Error occurred during creation a workspace from devfile located at `<repo-url>`. Cause: Neither of `apiVersion` or `schemaVersion` found. This is not a valid devfile.
```

The message is confusing because it looks like Che was able to retrieve a Devfile but it was invalid.
And it's not possible to start the workspace although 

### Describe the solution you'd like

The message should rather be something like:

```
::Warning::
Looking for a Devfile in the git repository failed. The git server API may not supported by Eclipse Che (or the git server hasn't been configured appropriately).

Note that the git cloning of the repository will succeed if it's public or it's private and the developer git credentials secret has been configured.

Click to continue
```

### Additional context

<img width="2014" alt="image" src="https://user-images.githubusercontent.com/606959/218342904-1b8ff103-b8da-4ca2-8b87-09a9576c34c1.png">

**Comment by vinokurig** [comment]
@l0rd 
What should we do on the `Click to continue` link?

**Comment by vinokurig** [comment]
@l0rd 
> Note that the git cloning of the repository will succeed if it's public or it's private and the developer git credentials secret has been configured.

Do you mean that if the git provider of the provided git repo url is not supported by Che, and it is a public repo we should apply the default devfile?

**Comment by amisevsk** [comment]
One option to consider is using a fallback option where we

1. Start a special workspace with the configured project
2. This workspace clones the repo (which should succeed as long as credentials are set up and the repo is a git repo)
3. The workspace patches itself to use the content from the in-repo devfile and restarts

It's a slower way of starting workspaces, but would also work even when Che server fails to resolve a devfile (e.g. if SSH keys are used, IIRC). I toyed with this idea in the early days and came up with this: https://github.com/amisevsk/workspace-bootstrap, though it is likely out of date and would need to be updated for Che workspaces.

**Comment by ibuziuk** [comment]
@vinokurig could you please sync with @olexii4 and @akurinnoy regarding this issue. I believe the flow should be similar to what we have for repositories when there is no devfile in the project. 

> What should we do on the Click to continue link?

We should start a workspace using the default devfile and ignore the one that we fail to resolve (btw I think on che-server side the default is still v1 and we should replace it with v2)
