### ISSUE TITLE
Allow to deploy DWO in disconnected environment

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21994]
### Is your task related to a problem? Please describe

It is not possible to deploy DWO in disconnected environment.
In order to achieve that we have to mirror images with digests, but currently they are referenced by tags.

We have couple of tries here:
https://github.com/amisevsk/devworkspace-operator/tree/use-digests-in-olm-release-wip
https://github.com/devfile/devworkspace-operator/pull/1035

### Describe the solution you'd like

Reference images by digests instead of tags.

### Additional context

* https://github.com/eclipse/che/issues/21445
* https://github.com/eclipse/che/issues/19659

**Comment by ibuziuk** [comment]
@l0rd @amisevsk folks, would it be possible to prioritize this issue since it blocks - https://github.com/eclipse/che/issues/21445 ?

**Comment by amisevsk** [comment]
PR open: https://github.com/devfile/devworkspace-operator/pull/1120

Currently, `quay.io/devfile/devworkspace-operator-index:release-digest` should be available for testing/use, allowing for the installation of DWO v0.21.1 in disconnected environments.

**Comment by amisevsk** [comment]
All PRs are merged, the DevWorkspace Operator can now be installed in disconnected environments:

* Image `quay.io/devfile/devworkspace-operator-index:release-digest` for DWO release versions
* Image `quay.io/devfile/devworkspace-operator-index:next-digest` for `next` builds.
