### ISSUE TITLE
che-code CI build fails about 1/2 the time

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21995]
### Describe the bug

In the GH action https://github.com/che-incubator/che-code/actions/workflows/image-publish.yml we can see that the release of nightly/CI/next builds fails about half the time:

![image](https://user-images.githubusercontent.com/227597/218123251-176af885-44ca-4fce-b73d-a7895cbcff79.png)

In the past 2 days:

* 8 failures
* 9 successes

### Che version

next (development version)

### Steps to reproduce

Push a commit. Flip a coin, maybe you'll get a green build, or maybe one of the two branches will fail (musl, libc)

* https://github.com/che-incubator/che-code/actions/runs/4144232978 (libc fail: `gyp ERR! stack FetchError: request to https://www.electronjs.org/headers/v19.1.9/SHASUMS256.txt failed, reason: read ECONNRESET`)
* https://github.com/che-incubator/che-code/actions/runs/4140287034 (musl fail: `Downloading ripgrep failed: Error: Request failed: 403`)
* https://github.com/che-incubator/che-code/actions/runs/4137364796 (libc fail)
* https://github.com/che-incubator/che-code/actions/runs/4134602819 (musl fail)
* https://github.com/che-incubator/che-code/actions/runs/4132556879/jobs/7141394019 (libc and musl pass, but then `gyp ERR! stack FetchError: request to https://www.electronjs.org/headers/v19.1.9/node-v19.1.9-headers.tar.gz failed, reason: read ECONNRESET` during the dev build)
* ...

### Expected behavior

we shouldn't have timeouts and disconnnects fetching content from dependency sites like electronjs.org

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by azatsarynnyy** [comment]
It looks like most of the unstable builds are related to fetching errors:
`FetchError: request to https://www.electronjs.org/headers/v19.1.9/SHASUMS256.txt failed, reason: read ECONNRESET`

Need to find a way how to make this fetching more reliable.

**Comment by azatsarynnyy** [comment]
We can consider it for the next sprint.

**Comment by azatsarynnyy** [comment]
I opened the dedicated issues for solving the two most common problems of the Che-Code CI build:
- #22003
- #22004
