### ISSUE TITLE
Upgrade Eclipse Che from 7.39.2 to 7.60.1

### ISSUE THREAD

**Issue by pgirishibm** [eclipse/che#21999]
### Summary

What is the best way to upgrade eclipse che from 7.39.2 to 7.60.1 using the chectl CLI? We have a deployment of 7.39.2 which has many users logged in and needs to upgraded

To simulate the same scenario, I downloaded 7.39.2 version of chectl and I installed 7.39.2 on Open Shift using the command
chectl server:deploy --platform=openshift --installer=operator --chenamespace=eclipse-che

I then tried to upgrade chectl using the command chectl:update, but i got this error
chectl: Updating CLI... not updatable

I then downloaded chectl version 7.60.1 and used the below command to upgrade
chectl server:update -n eclipse-che
Now I got this error.
› Current Kubernetes context: 'default/<domain>:6443/kube:admin'
  ✔ Verify Kubernetes API...[1.25]
  ❯ Eclipse Che operator pre-update check
    ✖ Check InstallPlan approval strategy
      → Subscription eclipse-che not found.
    Error: Command server:update failed with the error: Subscription eclipse-che not found. See details: /Users/pgirish/Library/Caches/chectl/error.log.

### Relevant information

7.39.2 is still using keycloak for authentication. But I suppose the later versions have stopped using keycloak and use Dex right? Can this be an issue with upgrade from 7.39.2 to 7.60.1?  Should i be first upgrading to a nearer version before going to the latest?

**Comment by pgirishibm** [comment]
Just tried this.  I upgrade from 7.39.2 to 7.40.0 and it worked.. 
I then tried to upgrade from 7.40.0 to 7.50.0 and got this error
pgirish@Girishs-MacBook-Pro Downloads % chectl server:update -n eclipse-che
A more recent version of chectl is available. To deploy the latest version of Eclipse Che, update the chectl tool first.
Do you want to update chectl now? [y/n]: n
› Installer type is set to: 'operator'
› Current Kubernetes context: 'default/api-ocp-060000vub3-17q9-cloud-techzone-ibm-com:6443/kube:admin'
  ✔ Verify Kubernetes API...[OK] [OpenShift]
  ❯ 🏃‍  Running the Eclipse Che operator Update
    ✔ Checking if operator deployment exists...[Found]
    ✔ Detecting existing version... 7.40.0 -> 7.40.0
    ✖ Check workspace engine compatibility...
      → Unsupported operation: it is not possible to update current Che installation to new version with enabled 'devWorkspace' engine.
    Error: Command server:update failed. Error log: /Users/pgirish/Library/Caches/chectl/error.log. Eclipse Che logs: 
    /var/folders/ht/kp2r6p4x0v526stcpj9dp5f00000gn/T/chectl-logs/1676303353009.
pgirish@Girishs-MacBook-Pro Downloads %


I suppose the upgrade to a version which has devworkspaces is enabled will not work from a old version.  Is this possible to keep devworkspaces disabled in the latest version during an upgrade from 7.39.2?

**Comment by l0rd** [comment]
Hi @pgirishibm A lot of things have changed in the meantime and to be able to upgrade from 7.39 to 7.60 you will need to migrate to 7.42 first.

v7.42 is the first version based on [current architecture](https://newsroom.eclipse.org/eclipse-newsletter/2022/may/eclipse-che-gets-new-dev-environments-engine). Once you have migrated to that you should be able to move to 7.60. 

The 7.41 to 7.42 migration guide [has unfortunately disappeared](https://github.com/eclipse/che/issues/21688). The only thing I am able to share is [this CodeReady Workspaces 2.15 to OpenShift Dev Spaces 3.0 guide](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.0/html/administration_guide/upgrading-devspaces#upgrading-crw-2.15-on-openshift) that should give you an idea. 

cc @tolusha that may have some additional recommendation
