### ISSUE TITLE
Support more easily switching default shells in Che workspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22009]
### Is your enhancement related to a problem? Please describe

It would be useful to be able to select the shell used for workspace terminal sessions. From brief testing, it appears the Che Code editor will default to using the login shell for the current user in `/etc/passwd`, but this can be overridden by using the `$SHELL` environment variable.

### Describe the solution you'd like

Assuming it doesn't bloat the image size too much, the UDI image should include multiple shells (bash, zsh at minimum) with basic configurations (`.bashrc`, `.zshrc`, etc). Then, users could select their preferred shell by setting the `$SHELL` environment variable in their devfile.

A further step could be to enable selecting the shell prompt when creating the workspace, e.g. via factory parameter or dashboard UI element.

Note, in my testing, `zsh` requires a `~/.zshrc` to exist on startup, or it will prompt the user to set one up on launch.

### Describe alternatives you've considered

It's not necessary to do anything here; if the development image includes the desired shell, it's sufficient to set the `$SHELL` environment variable. This issue is more about making it convenient in default workspaces.

### Additional context

To aid in testing, I've built `quay.io/amisevsk/web-terminal-tooling:zsh` as an image that includes both `bash` and `zsh`. Switching shells for Che Code can be tested by applying the following [DevWorkspace](https://gist.github.com/amisevsk/986b628d26a61427fd2f679ddd414ee1) to a cluster with Che installed:
```
kubectl apply -f https://gist.githubusercontent.com/amisevsk/986b628d26a61427fd2f679ddd414ee1/raw/8ee302f8ee4cece8787809e82229b289257c4521/shell-test.devworkspace.yaml
```

**Comment by l0rd** [comment]
Added to #20799
