### ISSUE TITLE
[dashboard] Restart button doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse/che#22011]
### Describe the bug

Restart button on the dashboard doesn't work properly. When click the button run workspace will stop but won't run again.

### Che version

next (development version)

### Steps to reproduce

1. Start any workspace from the dashboard
2. Go to the Workspaces view and click Restart button
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2023 02 17-18_54_48](https://user-images.githubusercontent.com/1271546/219715540-0c2e48f9-e27c-4207-a8b8-c52385ab5147.png)
3. See that the warkspace won't start again

### Expected behavior

Workspace should start again

### Runtime

OpenShift

### Screenshots

https://user-images.githubusercontent.com/1271546/219715911-7a30a378-8d4f-4851-8f46-ad8faf0ce02a.mp4

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
"Restart" button worked as expected in Eclipse Che dogfooding instance with Dashboard 7.64.0-next on board, and started workspace as the end:
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.04.11-19_14_09.webm](https://user-images.githubusercontent.com/1197777/231225833-1bb0f672-666b-4b5e-aed8-ec12c156443c.webm)

Good job!
