### ISSUE TITLE
Certificates are not propagated on some OpenShift clusters which results in workspace startup failures

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22026]
### Describe the bug

Certificates are not propagated on some OpenShift clusters which results in workspace startup failures

### Che version

7.61@latest

### Steps to reproduce

1. provision 4.12 cluster using cluster bot `launch 4.12` 
2. use next version of chectl `chectl version update` / `chectl update next`
3. deploy latest Eclipse Che `chectl server:deploy --platform openshift`
4. once operators are provisioned create a workspace using https://github.com/che-incubator/quarkus-api-example
5. ERROR workspace failed to start 

![image](https://user-images.githubusercontent.com/1461122/222452130-b2a8000a-abcc-4430-86ce-f5df0350d18d.png)

go to the dashboard pod and check `public-certs` folder - it is empty (no certificate is propagated to the pod):
```
sh-4.4$ ls
bin  boot  data  dev  entrypoint.sh  etc  home  lib  lib64  logs  lost+found  media  mnt  opt  proc  public-certs  root  run  sbin  srv  sys  tmp  usr  var
sh-4.4$ cd public-certs/
sh-4.4$ ls
sh-4.4$ 
```

### Expected behavior

the certificate is propagated to all operands including dashboard

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Amazon

### Additional context

NOTE that the issue is NOT reproducible with `launch 4.12 aws` only with `launch 4.12` hypershift cluster

**Comment by azatsarynnyy** [comment]
Shouldn't a certificate be at `/tmp/che/secret/ca.crt`?
