### ISSUE TITLE
Pre-create common tooling config directories for installed tools in UDI image

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22029]
### Is your enhancement related to a problem? Please describe

Che includes functionality for mounting files into DevWorkspaces for common configuration tasks, e.g. sharing a common maven `settings.xml` across different Java-based workspaces (automounting configmaps/secrets). However, since the UDI image does not come with a `/home/user/.m2` folder pre-created, users can run into confusion:

* If their devfile mounts a volume to `/home/user/.m2` (as it does in our samples), everything works as expected
* If their devfile does not include a `m2` volume, Kubernetes/OpenShift will create the directory in order to store the `settings.xml` file when the pod is started

In the latter case, the directory will be created with 755 permissions and root ownership, meaning the workspace will not be able to write to the directory. In the case of maven workspaces on OpenShift, this causes builds to fail as `/.m2/repository` cannot be created.

### Describe the solution you'd like

The UDI image should come with empty directories and appropriate permissions for common folders that are required by tools (e.g. `.m2`, `.gradle`, etc.)

### Describe alternatives you've considered

Document issue as a potential caveat with auto-mounted volumes

### Additional context

This behaviour underlies https://issues.redhat.com/browse/CRW-4082

**Comment by l0rd** [comment]
@amisevsk to be more precise this is about pre-creating local dependencies folder rather than config folder right? I am asking because it kind of match for maven but I am not sure that it does for every language. And that's about dependency management tools rather than "any" tool. We have hundreds tools in UDI and we may want to restrict this only to dm tools, specifically:
- maven
- gradle
- sbt
- npm
- yarn
- go
- dotnet
- pip
- cargo

**Comment by l0rd** [comment]
Added to #20799

**Comment by amisevsk** [comment]
I left it vague semi-intentionally -- we should have pre-created paths to any location a user might want to auto-mount a config (e.g. `settings.xml` goes in `$HOME/.m2/`, so `$HOME/.m2/` should exist). Technically, the same applies to npm, but npm reads from `$HOME/.npmrc`, and `$HOME` already exists. 

Looking at sbt, global config goes in `$HOME/.sbt/1.0/`, so the UDI image should `mkdir -p $HOME/.sbt/1.0/` to ensure that if a config file is mounted, the directory still has appropriate permissions, etc.

**Comment by amisevsk** [comment]
Bumped the priority on this one to match the priority of duplicate issue https://github.com/eclipse/che/issues/22620
