### ISSUE TITLE
Support GIT+SSH URLs when starting workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22025]
### Is your enhancement related to a problem? Please describe

Today it's not possible to start a workspace from an git repository URL using the GIT+SSH protocol: `git@github.com:eclipse/che.git`. 

Even if the user has configured an SSH secret to be automatically mounted in workspaces and had uploaded the public key in its git service, starting a workspace won't work.

### Describe the solution you'd like

If a user has configured SSH (secret created in his namespace + key uploaded to git service) or a git credential secret, then Che should be able to start a workspace from a GIT+SSH repository URL: if there is a devfile at the root of the git repo it should be used to define the corresponding DevWorkspace.

I think there are 3 possible solutions here:

- che server downloads the devfile without cloning the git repository (not sure git+ssh allows this)
- the dashboard creates a devworkspace that has an init container that, after cloning the source code, patches the DW CR with the content of the devfile using the `devworkspace-generator` npm library (similar to @amisevsk [work](https://github.com/amisevsk/workspace-bootstrap))
- che server does a git clone in a local temporary directory (depth 1 and sparse) and returns the devfile content (this is fragile)

### Other considerations

Through the GIT+SSH protocol Che would be able to fully support any git service. That won't replace the HTTP + OAuth flow that remains the preferred if support (GitHub, BB, GitLab and Azure DevOps), but an alternative that allows Che to work on other services too (gerrit, gogs, githut...). 

### Screenshots

**Dashboard doesn't even allow to provide a git repo URL that doesn't use HTTP:** :arrow_down:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/606959/222428868-ef22a6ca-7889-45f7-849b-03ac06ab4798.png">

**That what happen if I try the URL `https://<che-host>/f?url=git%40github.com%3Al0rd%2Fgo-hello-world.git`** :arrow_down:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/606959/222429164-05b7e8c6-80a1-4d0f-a4d1-598a7c33be63.png">

**Comment by l0rd** [comment]
Re-opening this issue because I am afraid that there is still a missing part: the devfile in the git repository is ignored. This issue was about:
- not failing when a GIT+SSH URL was provided (this is done)
- using the devfile in the git repo to define the DevWorkspace (this is not done yet)

**Comment by olexii4** [comment]
> Re-opening this issue because I am afraid that there is still a missing part: the devfile in the git repository is ignored. This issue was about:
> 
> * not failing when a GIT+SSH URL was provided (this is done)
> * using the devfile in the git repo to define the DevWorkspace (this is not done yet)

@l0rd Could you add more pieces of information on why you think so?
Unfortunately, I can't reproduce this issue.

**Comment by l0rd** [comment]
@olexii4 Sorry I haven't tested or review the PR. I was assuming that the work that has been completed dashboard-side only and that the devfile cannot be resolved from a GIT+SSH URL. I am probably wrong though. Can you please help me understanding how the resolution is done?

**Comment by olexii4** [comment]
> @olexii4 Sorry I haven't tested or review the PR. I was assuming that the work that has been completed dashboard-side only and that the devfile cannot be resolved from a GIT+SSH URL. I am probably wrong though. Can you please help me understanding how the resolution is done?

I found that the ```che-server ``` part, which was added with the next [PR](https://github.com/eclipse-che/che-server/pull/458) does not work properly.

It always resolves the default defile:
![Знімок екрана 2023-05-01 о 18 35 54](https://user-images.githubusercontent.com/6310786/235481800-4db47e25-416e-436c-ad78-969173043973.png)

@tolusha WDYT?

**Comment by l0rd** [comment]
Closing as this is mostly done. I have opened a separate issue for the missing part: 
- #22354
