### ISSUE TITLE
VS Code SecretStorage API with Promise.allSettled()

### ISSUE THREAD

**Issue by katsoohoo** [eclipse/che#22021]
### Describe the bug

When using [VS Code's SecretStorage API](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with [`Promise.allSettled()`](https://code.visualstudio.com/api/references/vscode-api#SecretStorage), the first few `SecretStorage.get()` returns undefined even though the secrets were stored previously with `SecretStorage.store()`.

However, when using `await Promise` as a synchronous approach, `SecretStorage.get()` successfully returns the stored secrets.

This issue does not occur when running VS Code on macOS.

### Che version

7.58

### Steps to reproduce

I made a sample VS Code extension to reproduce the error - https://github.com/katsoohoo/secretstorage-extension

1. Create an "Empty Workspace" in Red Hat OpenShift Dev Spaces.
2. Install the sample VS Code extension in the workspace.
3. Run the VS Code command `secretstorage-extension.allSettled`.
4. The output channel will open displaying the logs as secrets are being stored, retrieved, and deleted.

### Expected behavior

The first few calls to VS Code's `SecretStorage.get()` should return the secrets if they were previously stored with `SecretStorage.store()`. It should behave as it does on VS Code running on macOS.

### Runtime

OpenShift, CodeReady Container

### Screenshots

Using `Promise.allSettled()` - bug occurs
```
Congratulations, your extension "secretstorage-extension" is now active!
Using Promise.allSettled...
SecretStorage.store 0 fulfilled
SecretStorage.store 1 fulfilled
SecretStorage.store 2 fulfilled
SecretStorage.get 0 fulfilled: undefined
SecretStorage.get 1 fulfilled: undefined
SecretStorage.get 2 fulfilled: pass2
SecretStorage.delete 0 fulfilled
SecretStorage.delete 1 fulfilled
SecretStorage.delete 2 fulfilled
```

Using `await Promise` - expected behavior
```
Congratulations, your extension "secretstorage-extension" is now active!
Using await Promise without loop...
SecretStorage.store 0 fulfilled
SecretStorage.store 1 fulfilled
SecretStorage.store 2 fulfilled
SecretStorage.get 0 fulfilled: pass0
SecretStorage.get 1 fulfilled: pass1
SecretStorage.get 2 fulfilled: pass2
SecretStorage.delete 0 fulfilled
SecretStorage.delete 1 fulfilled
SecretStorage.delete 2 fulfilled
```

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by l0rd** [comment]
Hello @katsoohoo, thank you for reporting this issue and for taking the time to provide the sample extension. Why is this issue important for you? Are you the author or the consumer of an extension that uses this API?

@azatsarynnyy @RomanNikitenko do you have an idea on cause of this problem and if it's something that we can fix?

**Comment by katsoohoo** [comment]
Hi @l0rd,

We are a consumer of an extension that uses this API. We are looking to support our extension in Red Hat Dev Spaces.

**Comment by l0rd** [comment]
@katsoohoo thank you. Is your extension available on open-vsx.org?

**Comment by katsoohoo** [comment]
@l0rd Not yet. We've been using the VS Code command `Extensions: Install from VSIX...` to install our extension in Red Hat Dev Spaces. For now, our VSIX can be downloaded from the VS Code Marketplace - https://marketplace.visualstudio.com/items?itemName=ibm.db2forzosdeveloperextension

**Comment by katsoohoo** [comment]
Logs from the workspace pod:
```
[22:22:32] Extension installed successfully: kat-test.secretstorage-extension
[GIN] 2023/03/27 - 22:22:59 | 204 | 16.15µs | 127.0.0.1 | POST "/activity/tick"
[22:23:35] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[22:23:35] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[22:23:35] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
```

After installing `libsecret` to the docker image defined in `devfile.yaml`, I see these sort of logs:
```
[00:16:18] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: Cannot autolaunch D-Bus without X11 $DISPLAY
```
