### ISSUE TITLE
More documentation to make a custom che editor

### ISSUE THREAD

**Issue by MichelSc** [eclipse/che#22030]
### Summary

We are very interested to adopt Eclipse Che to deploy our theia based applications, in order to add multi-user and https support.

So we do not want to use the 3 or 4 out of the box che editors, but instead we want to open a workspace with our own theia application. We want to deploy a custom che editor.

This issue requires more documentation on what is required to create a custom che editor.
- what is required in the DevFile?
  - for instance that an attribute `type=main' is required for the end point to be used by che to open the attribute
  - are there other requirements?

In the same context, we want to use a che devfile registry to support our custom editor.

The only documented way to make a che devfile registry is https://github.com/eclipse-che/che-devfile-registry, but it generates links for the 4 out of the box editors.

What is required to implement our own che devfile registry? We understand that a che devfile registry is a static web site, serving files with a given structure.
- what is the structure expected by che?
- is the defiles/index.json required by Che? what is its schema?
- what is the required structure of the custom workspace meta.yaml?
- what is the required structure of the other yaml files?
  - they are DevWorkspace resource files (kubernetes Custom Resource File)
- index.json replicates information from meta.yaml? Are both of them expected?
  - or can we generate one from the other?

Many thanks in advance.

**Comment by amisevsk** [comment]
Regarding requirements for getting up and running, the devfile spec is largely Che or editor agnostic. You should be able to get fairly far (if not all the way) without worrying about many specific details. Regarding you question, the `type: main` attribute only marks that endpoint as the "main" entrypoint, causing it to be highlighted in the DevWorkspace CR's status, but even without it you should be able to load the editor by accessing the URL created for that endpoint.

Apart from that endpoint attribute, everything else in the editor's devfile is just what that editor requires to run in a pod. Documentation on devfile features is [here](https://devfile.io/docs/2.2.0/devfile-schema)

For building a custom devfile registry, I'll leave that information to the folks that work on that area.

**Comment by MichelSc** [comment]
About making a custom editor:
- thank you for the reply
- still, my feedback here is that more documentation could be helpful (although I managed to find everything)
- there is (almost) no explicit mention of support of custom editor and one could believe this use case is not supported/deprecated

About making a custom che devfile registry:
- still waiting an answer
- from the generated che devfile registry, I understand
  - index.json is required
     - with valid references to images
     - with valid references to devworkspace yaml files
   - devworkspace yaml file is required for every workspace-editor
     - with valid references to zipped workspaces
  -  could you confirm that? Is there something else required?
- in index.json, the element `links.v2.devWorkspaces` is an object with fields for every to be used editor, containing the url of the devworkspace yaml to be used for that editor
  - in the generated che devfile registry editor, we have the fields 
    - "eclipse/che-theia/latest"
    - "eclipse/che-idea/next"
    - "che-incubator/che-code/latest"
    - "che-incubator/che-code/insiders"
  - what are the allowed/expected fields?
  - what mean these paths?
  - is there a syntax to be followed?

**Comment by amisevsk** [comment]
cc: @svor @olexii4 -- any guidance on adding editors to the devfile registry/dashboard?

**Comment by svor** [comment]
@MichelSc if you are looking for the place where a new editor definition could be contributed, it is [che-plugin-registry](https://github.com/eclipse-che/che-plugin-registry), where you can find [che-editors.yaml](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml) with all available editors. So, you need to extend this file. When you have your custom plugin registry, you'll be able to create workspaces with your editor as described in [Selecting a workspace IDE](https://www.eclipse.org/che/docs/stable/end-user-guide/selecting-a-workspace-ide/)

About devfile registry. It provides devworkspace-...yaml files for the case when Che is running in AirGap mode and it's node possible to get the content of the devfile described in `index.json` as `v2`, in this case `devworkspace-editor-id.yaml` will be used to create a workspace.  Element `links.devWorkspaces` is not required.

**Comment by MichelSc** [comment]
About editor contribution: thank you. I see indeed 11 editor contribution in the default che-plugin-registry. I understand that those editor contributions are the ones referred to by the che-devfile-registry.

About customizing the che-devfile-registry, I understand from your reply that the links element in index.json is not considered, but only the devworkspace<editorid>.yaml files, where <editorid> is a contributed editor.

Thank you. This is very helpful. I am going to try this as soon as possible, but this will not be in the very short term. I will let you know.

**Comment by MichelSc** [comment]
Still in our plans to use/try Che somewhere in the future...
/remove-lifecycle stale
