### ISSUE TITLE
Good enough OpenShift OAuth token scope

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22038]
### Is your enhancement related to a problem? Please describe

The `user:full` scope requested when a user first login to Che can be [considered intimidating](https://twitter.com/DukeAMO/status/1446365785866317828).

<img width="724" alt="image" src="https://user-images.githubusercontent.com/606959/223108630-f2e4776c-ca6d-44a3-89df-9370fbc2b2f6.png">

### Describe the solution you'd like

- review is the `user:full` is required or if `user:info` is enough (dashboard has its backend so the user token should not be required, except for the injection in namespace maybe?)
- document why we need to request 'full'
- investigate if it's possible to include a message that explains why we need the information.

### Other information

[Scoping tokens | Authentication and authorization | OpenShift Container Platform 4.12](https://docs.openshift.com/container-platform/4.12/authentication/tokens-scoping.html)

**Comment by amisevsk** [comment]
The dashboard also uses the user's token for creating the DevWorkspace resource, so some level of write access is currently required.

**Comment by l0rd** [comment]
Wouldn't that error be solved if we use the namespace API rather then project API?

**Comment by tolusha** [comment]
Unfortunately, this does not change anything.

**Comment by tolusha** [comment]
yes, using che-server SA solves the problem. Workspace can be successfully created.
But we bump into another issue with a dasbhoard.

![screenshot-eclipse-che apps 9ddfc237614ff9a22b01 hypershift aws-2 ci openshift org-2023 04 25-11_23_46](https://user-images.githubusercontent.com/1640675/234218449-6144e99d-f7e5-492a-b6b6-c4ee77d2938a.png)

**Comment by l0rd** [comment]
> And we do this intentionally.

What do you mean? To be clear: this problem discourage the adoption of Che and Dev Spaces (see the tweet below) so we should make sure we have a very valid reason to do that "intentionally".

<img width="886" alt="image" src="https://user-images.githubusercontent.com/606959/234332313-0d5216f2-84b2-4540-98eb-4f7dc7608856.png">

**Comment by amisevsk** [comment]
I worry that this goal is at odds with the current functionality of logging the user in within workspaces. If the concern is that the access level granted to Che includes secrets, etc. then anything we do to avoid that will result in `kubectl get secrets` failing within workspaces.

Looking at the OpenShift documentation for [scoping tokens](https://docs.openshift.com/container-platform/4.12/authentication/tokens-scoping.html), it looks like what we need is a role-based scope such as `role:admin:*`. I briefly tested setting scope
```
scope = "role:admin:* user:list-projects user:info"
```
in the Che Operator's oauth-config, which leads to an authorization page that looks like this

![2023-04-25-17:34:01](https://user-images.githubusercontent.com/16168279/234410297-1b8187ae-fc0c-42fb-8b59-6855d8237847.png)

This currently fails to access the dashboard, likely due to an error @tolusha fixed while working on supporting `user:info` -- the request to `/api/kubernetes/namespace/provision` fails with 
> Error occurred while trying to create user profile secret.

(the non-escalating scope prevents editing/creating secrets)

**Comment by tolusha** [comment]
Having scopes `scope = "role:admin:* user:list-projects user:info"` and modified che-server image (`quay.io/abazko/che-server:22038`) results in impossibility to handle Secrets on Dashboard side:

![screenshot-eclipse-che apps 9ddfc237614ff9a22b01 hypershift aws-2 ci openshift org-2023 04 25-11_23_46](https://user-images.githubusercontent.com/1640675/234504240-ff937576-f192-4744-8396-7d6f115237e9.png)

But accordingly to the doc [1] we can use `role:admin:*:!` with privilege escalation to read secret.

[1] https://docs.openshift.com/container-platform/4.12/authentication/tokens-scoping.html#scoping-tokens-role-scope_configuring-internal-oauth

**Comment by l0rd** [comment]
> I worry that this goal is at odds with the current functionality of logging the user in within workspaces.

👍 we agree. It's just that it's not clear why and there is no way to opt-out. If automatic login is the only reason we should:
- explain why this scope is required
- allow developers to opt-out

**Comment by tolusha** [comment]
@l0rd 

> explain why this scope is required

Unfortunately I didn't find a way to customize `Authorize Access` page.
There are some templates [1], but they are more about login. 
So, I suggest documenting and explain why we need `user:full` scope only.

> allow developers to opt-out

Sorry, could you explain more?

https://openshift.github.io/oauth-templates/

**Comment by l0rd** [comment]
What I mean is that I would allow:

1) Admins to configure Che to require a token with `user:info` only.
2) Developers to change the authorization scope from the dashboard preferences. From `user:info` to `user:full` and viceversa. 

If the scope is `user:info` the workspace kubeconfig is not configured automatically (the developers has to `oc login`).

**Comment by tolusha** [comment]
@l0rd 
We already have `oAuthScope` field [1] which is simply ignored for OpenShift. We can reuse it for our purpose.
Having that, there is a question. What is the default value? (`user:info` or `user:full`)
In case if `user:info` we will change our default behavior. 

[1] https://github.com/eclipse-che/che-operator/blob/b9d8ce34b541a30d2d5f7329210bccd580bc0561/api/v2/checluster_types.go#L482

**Comment by l0rd** [comment]
I would stick with current value for the default (`user:full`).
