### ISSUE TITLE
oauth2.0-proxy with 500 error:  redeeming code during OAuth2 callback: token exchange failed

### ISSUE THREAD

**Issue by davidxwwang** [eclipse/che#22048]
### Describe the bug

when login in dex, then the brower redirest to  `https://192.168.49.2.nip.io/oauth/callback?code=kjgknxflhu46tfivw6cexs3uz&state=WzNK3ZIaurPFJ-Z6RtNwAskyG5Tal1XR58CrcwSmUps%3A%2Fdashboard%2F` which tip : 500 error, but not the user dashboard.

### Che version

7.59

### Steps to reproduce

1.  l download the chectl sourcecode(maybe 3 month ago), and change 'quay.io/eclipse/che-operator:next' to 'quay.io/eclipse/che-operator:7.59.0'
2. then `bin/run server:deploy --platform=minikube  -
-k8spoderrorrechecktimeout=300000  --k8spodwaittimeout=300000 --k8spodreadytimeout=300000`
3. `.\bin\run dashboard:open`
4. the dashboard opened and rediect to to dex  successfully, and then l login in using the preseted username(user3@che)
5. the brower redirect to `https://192.168.49.2.nip.io/oauth/callback?code=kjgknxflhu46tfivw6cexs3uz&state=WzNK3ZIaurPFJ-Z6RtNwAskyG5Tal1XR58CrcwSmUps%3A%2Fdashboard%2F` which tip : 500 error but not the user dashboard.

### Expected behavior

the user dashboard open successfully

### Runtime

minikube

### Screenshots

![Screenshot 2023-03-08 114739](https://user-images.githubusercontent.com/13027592/223615458-8485fcc8-5cb6-42a0-a333-98636433e5ca.png)

### Installation method

other (please specify in additional context)

### Environment

Windows

### Eclipse Che Logs

```shell
using `kubectl logs  pod/che-gateway-796fc47796-2kttf -c oauth-proxy -n eclipse-che`
...

[2023/03/08 02:10:59] [oauthproxy.go:823] Error redeeming code during OAuth2 callback: token exchange failed: Post "https://dex.192.168.49.2.nip.io/token": dial tcp 127.0.0.1:443: connect: connection refused
172.17.0.2:37482 - 92adb9205e0198d155c6c5f9dc7a2090 - - [2023/03/08 02:10:59] 192.168.49.2.nip.io GET - "/oauth/callback?code=qyh2j56yves3kljjkjku6jx33&state=vo9NH4BMfhwwlKXh3IIlfZ3_NYf-2wRBiO8LoRLA_V0%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 500 2836 0.022
[2023/03/08 02:10:59] [oauthproxy.go:959] No valid authentication in request. Initiating login.
172.17.0.2:37482 - 8ed7c115c942a99e47a16cc4945165fd - - [2023/03/08 02:10:59] 192.168.49.2.nip.io GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 302 302 0.000

...
```

**Comment by tolusha** [comment]
@davidxwwang 
Could you try with the latest chectl version? [1]
Do you need the exact 7.59.0 Eclipse Che?

[1] https://github.com/che-incubator/chectl#installation

**Comment by davidxwwang** [comment]
> @davidxwwang Could you try with the latest chectl version? [1] Do you need the exact 7.59.0 Eclipse Che?
> 
> [1] https://github.com/che-incubator/chectl#installation

@tolusha thank you , l donot need exact 7.59.0 Eclipse Che , l download the sourcecode of `https://github.com/che-incubator/chectl.git` (main branch ) which using  `quay.io/eclipse/che-operator:next ` today and delete the yarn.lock file,  also some error: oauth2.0-proxy with 500 error: redeeming code during OAuth2 callback: token exchange failed.

**Comment by davidxwwang** [comment]
> @davidxwwang Could you try with the latest chectl version? [1] Do you need the exact 7.59.0 Eclipse Che?
> 
> [1] https://github.com/che-incubator/chectl#installation

@tolusha hi， thanks， l use `chectl update` update the version of chectl to `chectl/0.0.20230302-next.b35c1bc win32-x64 node-v16.13.2` , still get the 500 error.

**Comment by tolusha** [comment]
I didn't notice that you use win platform.
Unfortunately I can't test, but you can have a look at this script [1]

[1] https://gist.github.com/debovema/783f29040059f8b2b784a246dbd96365

**Comment by davidxwwang** [comment]
> I didn't notice that you use win platform. Unfortunately I can't test, but you can have a look at this script [1]
> 
> [1] https://gist.github.com/debovema/783f29040059f8b2b784a246dbd96365

thanks, you mean the user dashboard can work normally on linux platform?

**Comment by vatsal-uppal-1997** [comment]
> yes, linux + minikube + Eclipse Che works fine

I am getting the same issue in linux + minikube. Please find below a log snippet:

`
172.17.0.5:39724 - 1c31f927e2c65edc9fa9ec65891068f5 - - [2023/03/13 07:39:09] test.io GET - "/oauth/callback?code=aqnjb3mzw2mtk7cks3fxzjcqr&state=hS6Evw-uhc5JsuKfbeOgF2IvereJVdNhLrf36xGecaA%3A%2Fdashboard%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 500 2836 2.702

172.17.0.5:39730 - bfaaaf79828ba50a9cebb25ac001d75f - - [2023/03/13 07:39:11] test.io GET - "/oauth/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 302 273 0.000

[2023/03/13 07:39:53] [oauthproxy.go:823] Error redeeming code during OAuth2 callback: token exchange failed: invalid character '<' looking for beginning of value

172.17.0.5:39730 - 1301b43a51bd0c127ea0a7969cee06fb - - [2023/03/13 07:39:44] test.io GET - "/oauth/callback?code=udutjnvd4vwsqmqfusvhqiwb4&state=MQFLJLulggOugLLdn_iI-BSf-86VmQjfkBj9XYDS6gA%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 500 2836 9.769

[2023/03/13 07:39:54] [oauthproxy.go:959] **No valid authentication in request. Initiating login**.

172.17.0.5:39730 - cf8d13a66689e73c5061d37e5cac407f - - [2023/03/13 07:39:54] test.io GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 302 284 0.000
`

Here are some details that might be helpful:

Minikube: v1.27.1 (Same issue on the latest version as well - this is the downgraded version)
Chectl: 0.0.20230302-next.b35c1bc linux-x64 node-v16.13.2 (Same issue on the stable channel as well)
