### ISSUE TITLE
Restore Eclipse Che typescript E2E functional tests PR check

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22044]
### Is your task related to a problem? Please describe

There are Eclipse Che typescript E2E functional tests [1] which doesn't have PR check to avoid breaking changes in the main branch.

[1] https://github.com/eclipse/che/tree/main/tests/e2e

### Describe the solution you'd like

Add github action which will be triggered on new commit in PR, and run smoke Eclipse Che typescript E2E functional test.

**Comment by nallikaea** [comment]
Related description: https://issues.redhat.com/browse/CRW-2891
