### ISSUE TITLE
Add the Smoke test PR check for Operator repository

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22046]
### Is your task related to a problem? Please describe

Run Smoke GUI test on new pull request or new commit to pull request in repo https://github.com/eclipse-che/che-operator

### Describe the solution you'd like

Update existed test script to run Smoke GUI test: https://github.com/eclipse-che/che-operator/blob/main/build/scripts/oc-tests/oc-test-happy-path.sh

**Comment by ScrewTSW** [comment]
done.
