### ISSUE TITLE
Remove che-theia/latest editor from Che 7.63

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22040]
### Is your task related to a problem? Please describe

che-theia/latest editor was  deprecated several releases ago, and is now ready to be removed so that downstream Dev Spaces 3.6 will also not iinclude this editor.

### Describe the solution you'd like

Unclear on the details but I suspect changes will be needed in:

* che-dashboard
* che-plugin-registry
* che-devfile-registry
* che-operator & operator-bundle

Should verify if these need an update too:

* che-server
* devworkspace operator & bundle

Will also need to:

* disable the che-theia builds / stop publishing quay images
* mark the GH repo read-only / archived
* mark the quay repo read-only / archived
* remove theia/endpoint/dev from the orchestrations in che-release (yamls and bash scripts)

### Additional context

Downstream: 
* https://issues.redhat.com/browse/CRW-3489
* https://issues.redhat.com/browse/CRW-3663
* https://issues.redhat.com/browse/CRW-4077

**Comment by l0rd** [comment]
You may want to close this one or transform it as a subtask of [this existing issue](https://github.com/eclipse/che/issues/21771).

**Comment by nickboldt** [comment]
PR to remove theia from operator payload: https://github.com/eclipse-che/che-operator/pull/1635

**Comment by nickboldt** [comment]
Merged into https://github.com/eclipse/che/issues/21771 so we can close this
