### ISSUE TITLE
[Azure] Starting workspace works only from 'Clone Repository' URL (Browser URL does not work)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22053]
### Describe the bug

![image](https://user-images.githubusercontent.com/1461122/224254421-ea85dd74-13ae-4b26-9b31-045534d29a09.png)

- https://dev.azure.com/ibuziuk/_git/quarkus-api-example
- https://ibuziuk@dev.azure.com/ibuziuk/quarkus-api-example/_git/quarkus-api-example

Currently only the last one work (URL from browser results in workspace startup failure)

### Che version

7.61@latest

### Steps to reproduce

1. Start workspace using browser URL e.g.  https://dev.azure.com/ibuziuk/_git/quarkus-api-example
2. ERROR: `Error occurred during creation a workspace from devfile located at `https://dev.azure.com/ibuziuk/_git/quarkus-api-example`. Cause: Neither of `apiVersion` or `schemaVersion` found. This is not a valid devfile.`

### Expected behavior

Both URLs works for workspace startup 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by tolusha** [comment]
I used a bit different url format for my testing `https://dev.azure.com/<organization>/<project>/_git/<repository>`
So, I need to take into account that organization part can be missed.
