### ISSUE TITLE
Dashboard prints warning when tries to start an empty workspace

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22057]
### Describe the bug

Dashboard prints warning when tries to start an empty workspace

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che next version
2. Start an empty workspace
![screenshot-192 168 39 190 nip io-2023 03 14-08_33_54](https://user-images.githubusercontent.com/1640675/224950544-9faf26e7-7f64-43de-8c0d-d2f959584145.png)

### Expected behavior

N/A

### Runtime

minikube

### Screenshots

![Screenshot from 2023-03-14 10-57-48](https://user-images.githubusercontent.com/1640675/224950669-3bc8277b-9207-46a5-a93f-e92524ef58f9.png)
![Screenshot from 2023-03-14 10-56-44](https://user-images.githubusercontent.com/1640675/224950684-e43853fe-e403-48d6-b154-fbd836d7087c.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy happens for me also with https://github.com/che-incubator/quarkus-api-example on dogfooding:
![image](https://user-images.githubusercontent.com/1461122/229453141-ac4e2552-4911-41d5-aba8-09f4d1b6b743.png)

**Comment by ibuziuk** [comment]
should be backported to 7.64.x / 3.6

**Comment by dmytro-ndp** [comment]
Issue looks fixed in Eclipse Che 7.64.0:
![Screenshot from 2023-04-18 13-50-35](https://user-images.githubusercontent.com/1197777/232764621-621d1333-3153-4198-ab7c-b1b74d9ae085.png)
