### ISSUE TITLE
Small typos in tests/performance README

### ISSUE THREAD

**Issue by Daybringer** [eclipse/che#22054]
### Describe the bug

Fixed small typos in che/tests/performance/README.md document.

### Che version

7.61@latest

### Steps to reproduce

None. Documentation typo

### Expected behavior

-

### Runtime

CodeReady Container

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
@dmytro-ndp @ScrewTSW could you please review - https://github.com/eclipse/che/pull/22055 ?
in general, I'm not sure if those tests are functioning and up-to-date

**Comment by l0rd** [comment]
Closing as the PR has been merge
