### ISSUE TITLE
Avoid startup failures on Developer Sandbox because of route counts quota

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22069]
### Is your enhancement related to a problem? Please describe

Quotas are configured on developer sandbox and it's not possible to have an arbitrary number of workspaces on developer sandbox. In particular routes count (30) will cause startup failures if a certain number of workspaces (9) exist, even if the workspaces are stopped. 

And usually developers[ don't have any clue of what's going on (apart that Dev Spaces is broken)](https://github.com/eclipse/che/issues/22068) when that happens.

### Describe the solution you'd like

Set [maxNumberOfWorkspacesPerUser](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.60.0) to 5 on developer sandbox.

Note that currently user should not be able to create more than 4 workspaces because of #22068 (4th workspace fails). This problem has been introduced with the update to 3.4. That means setting `maxNumberOfWorkspacesPerUser: 5` should not require users to delete existing workspaces. But that will change [when the quota is going to be updated](https://github.com/codeready-toolchain/host-operator/pull/768).

### Alternative solution

Set `config.workspace.cleanupOnStop: true` so that routes of stopped workspaces are deleted.

**Comment by ibuziuk** [comment]
Instead of restricting the number of workspaces cleanupOnStop option on DWOC level has been enabled on Developer Sandbox stg and production clusters (svc, routes are removed once workspace is stopped)
```
config:
  workspace:
    cleanupOnStop: true
```

**Comment by l0rd** [comment]
> Instead of restricting the number of workspaces cleanupOnStop option on DWOC level has been enabled on Developer Sandbox stg and production clusters (svc, routes are removed once workspace is stopped)

This may have an effect on performances. I though we would have enabled that in our dev environment first.

**Comment by ibuziuk** [comment]
@l0rd it was enabled on dogfooding yesterday, and today during the verification on staging no performance pitfalls were spotted. We can disable it on production if some particular verification steps are required

**Comment by dmytro-ndp** [comment]
Issue looks fixed properly, because I have checked 11 workspaces start > stop one by one on my Dev Sandbox production account, and have not experienced workspace failure because of too big number of routes.

There were zero routes shown in my OCP namespace at the end:

![Screenshot from 2023-04-07 20-14-08](https://user-images.githubusercontent.com/1197777/230649689-94a1543e-f967-4d19-8b12-c4fb4ba050d9.png)

![Screenshot from 2023-04-07 20-13-50](https://user-images.githubusercontent.com/1197777/230649696-e8c8523e-04c1-44f6-a59c-fc7da12423e8.png)
