### ISSUE TITLE
ensure smooth transition between Che releases when hardcoded values exist in CheCluster CR

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22064]
### Is your task related to a problem? Please describe

Today we embed a number of hardcoded values in the CheCluster CR, including:
- [ ] defaultEditor (changing default to vscode, see [CRW-4077](https://issues.redhat.com/browse/CRW-4077))

- [ ]  openVSXURL (changing default to embedded version, see [CRW-4117](https://issues.redhat.com/browse/CRW-4117)

- [ ]  dashboard.headerMessage (new values don't appear after update so notes about deprecation/removal won't appear!)

- [ ]  ~~devWorkspace.totalLimitPerUser =renamed=to=> devEnvironments.maxNumberOfWorkspacesPerUser~~

- [ ]  ~~devWorkspace.runningLimit  =renamed=to=> devEnvironments.maxNumberOfRunningWorkspacesPerUser~~

- [ ]  devEnvironments.defaultComponents.container.image (container reference for the UDI iamge used when opening an empty workspace doesn't change from :3.4 to :3.5 to :3.6 when updating)

... and more?

### Describe the solution you'd like

We nee to get all this hardcoded stuff out of the CheCluster CR and put it into the CSV, like we did for all the RELATED_IMAGES used by the registries. That way we can actually control behaviour changes between releases and update defaults so they make sense for each release.

### Describe alternatives you've considered

We could also provide doc and bash + yaml to demo to admins how to update their CheCluster CRs when updating between releases, but this is at best a klunky way to encourage customers to stay current with a "service-like" product like Che or Dev Spaces. 

### Additional context

See also:
* https://github.com/eclipse/che/issues/21771
* [CRW-4077](https://issues.redhat.com/browse/CRW-4077) [Ensure smooth transition from old default editor (theia or che-code/insiders) to new default che-code/latest](https://issues.redhat.com/browse/CRW-4077)

**Comment by tolusha** [comment]
All those defaults are not consumed by operator itself, so they can be easily moved to che-operator environment variables (for further productisation) and mounted into dashboard pod.

**Comment by tolusha** [comment]
`devWorkspace.runningLimit =renamed=to=> devEnvironments.maxNumberOfRunningWorkspacesPerUser`
Both fields `runningLimit` and `maxNumberOfRunningWorkspacesPerUser` should work

**Comment by tolusha** [comment]
> devWorkspace.totalLimitPerUser =renamed=to=> devEnvironments.maxNumberOfWorkspacesPerUser

We have never hard such a field as `totalLimitPerUser`, so `maxNumberOfWorkspacesPerUser` is the only option

**Comment by tolusha** [comment]
> openVSXURL (changing default to embedded version)

Unfortunately, we can't set any defaults for `openVSXURL` for the reason, that empty value force to start embedded registry. If we use any defaults, than empty value will never be used and it won't be possible to start any embedded registry.
