### ISSUE TITLE
Document the URLs to whitelisted when VS Code runs behind a proxy

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22079]
### Is your enhancement related to a problem? Please describe

If not configured properly, VS Code behind a proxy won't be able to connect to the open-vsx registry (online or embedded) and users won't be able to install extensions.

When configured to use open-vsx.org VS Code connects:
- `open-vsx.org`
- `openvsxorg.blob.core.windows.net`

When it's configured to use the embedded open-vsx regisry VS Code connects to:
- `<che-host>` (external URL)
- `che-gateway.<namespace-name>:8089`

### Describe the solution you'd like

Update the ["Installing Che in a restricted Network"](https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-in-a-restricted-environment/) section.

Mention that the URLs above needs to be either:
- whitelisted in the proxy configuration
- added in the NO_PROXY environment variable ([this is currently broken](https://github.com/eclipse/che/issues/22078))

**Comment by max-cx** [comment]
The docs Jira issue where this work is tracked is [RHDEVDOCS-5101](https://issues.redhat.com/browse/RHDEVDOCS-5101).

**Comment by nickboldt** [comment]
See also https://issues.redhat.com/browse/CRW-4051

Note that in addition to 

* open-vsx.org
* openvsxorg.blob.core.windows.net

You will also need to whitelist 

* vscode-cdn.net

**Comment by azatsarynnyy** [comment]
> vscode-cdn.net

Note, once [CRW-3885](https://issues.redhat.com/browse/CRW-3885) and [CRW-4178](https://issues.redhat.com/browse/CRW-4178) are resolved there's no need to whitelist this URL.
