### ISSUE TITLE
[UDI]Update dotnet version to 6.0.x

### ISSUE THREAD

**Issue by svor** [eclipse/che#22077]
### Is your task related to a problem? Please describe

Omnisharp server can't start because minimum required version of dotnet is 6.0.100 and UDI provides 5.0.214

```
Starting OmniSharp server at 3/21/2023, 12:47:19 PM
    Target: /projects/aspnetcore-realworld-example-app/Conduit.sln

[ERROR] Error: Found dotnet version 5.0.214. Minimum required version is 6.0.100.
```

![Screenshot from 2023-03-21 14-48-48](https://user-images.githubusercontent.com/1271546/226613229-dd2630f6-b80c-4a44-bee0-f0c74554297d.png)

### Describe the solution you'd like

Upgrade dotnet to 6.0

**Comment by ibuziuk** [comment]
@svor wondering if the version update could also fix https://issues.redhat.com/browse/CRW-3563 ?

**Comment by svor** [comment]
@dmytro-ndp 
To verify the resolution, need to check the installed .NET version in the latest UDI:
`docker run -it quay.io/devfile/universal-developer-image:ubi8-latest /bin/bash -c 'dotnet --version'`
the result should be 6.0.x

**Comment by dmytro-ndp** [comment]
Checked with Eclipse Che Next using ASP.NET sample and quay.io/devfile/universal-developer-image:ubi8-latest (sha256:d4434a3944861c7a4de4570b1f56b3014c4ab1de05f5a9cf59d30d5fa4fc7154)

There was dotnet --version = 6.0.116 shown in terminal:
![Screenshot from 2023-04-19 19-46-14](https://user-images.githubusercontent.com/1197777/233150629-ed2e937e-5c0c-4fa4-82c3-109c7b8ce56b.png)

Issue looks resolved.
