### ISSUE TITLE
chectl install: check_bin_path function in installation not finding /usr/local/bin properly.

### ISSUE THREAD

**Issue by aszhiak** [eclipse/che#22070]
### Describe the bug

The function check_bin_path is unable to find properly "/usr/local/bin" in the path when it is already set in RHEL 9.1.

### Che version

7.61@latest

### Steps to reproduce

1. Get a machine with RHEL 9.1.
2. Enter the following command
` bash <(curl -sL  https://www.eclipse.org/che/chectl/)`
3. Introduce sudo password when asked.

### Expected behavior

The expected behavior is that the script properly detect the /usr/local/bin intead of throwing an error.

### Runtime

minikube

### Screenshots

![Screenshot 2023-03-19 165034](https://user-images.githubusercontent.com/16430949/226188027-5fd0085b-ecad-4bbc-ad4c-b0abd7b5af41.png)

### Installation method

chectl/latest

### Environment

Linux

**Comment by tolusha** [comment]
@aszhiak 
Could you check now? It is supposed to work.

**Comment by aszhiak** [comment]
@tolusha 
Now works perfectly :)
