### ISSUE TITLE
Document `SubdomainIsolation` option

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22072]
Related to https://issues.redhat.com/browse/CRW-3873 / https://github.com/eclipse-che/che-docs/pull/2548

**Comment by vinokurig** [comment]
We already have a documentation page about configuring the `SubdomainIsolation` via the [github oauth secret](https://github.com/eclipse-che/che-docs/pull/2548). We need to document the second way of configuring the `SubdomainIsolation` feature [from CheCluster CR](https://github.com/eclipse/che/issues/21724).

**Comment by tolusha** [comment]
`disableSubdomainIsolation` is deprecated in favor of `che.eclipse.org/scm-github-disable-subdomain-isolation` annotation.
We don't have to document this.

**Comment by ibuziuk** [comment]
@tolusha thanks for the input, but do we have the docs about this annotation?

**Comment by ibuziuk** [comment]
Perfect, closing in this case
