### ISSUE TITLE
Set the namespace in generated kubeconfig

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22083]
### Is your enhancement related to a problem? Please describe

The Dashboards generates a `~/.kube/config` at workspace startup. But the [context in the generated kubeconfig is missing the namespace](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Context):

```bash
{
  "apiVersion": "v1",
  "kind": "Config",
   (...)
  "contexts": [
    {
      "name": "logged-user",
      "context": {
        "user": "developer",
        "cluster": "inCluster",
        "name": "logged-user"
      }
    }
  ],
  "preferences": {},
  "current-context": "logged-user"
}
```

This can have some side effects because clients rely on `kubeconfig` to find the current namespace:

```
$ oc project
No project has been set. Pass a project name to make that the default.
```

Note that workspace Pod namespace is available at `/var/run/secret/kubernetes.io/serviceaccount/namespace`.

### Describe the solution you'd like

The namespace should be set in the [context](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-backend/src/services/kubeclient/kubeConfigProvider.ts#L45)

**Comment by max-cx** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-4344

**Comment by nickboldt** [comment]
Given this is for `.kube` and not openshift... is this a Che only N&N item? @l0rd

**Comment by l0rd** [comment]
> Given this is for `.kube` and not openshift... is this a Che only N&N item? @l0rd

No this issue if for Dev Spaces too. `.kubeconfig` is used by `oc` too.
