### ISSUE TITLE
How to wrap the che dashboard ?

### ISSUE THREAD

**Issue by yuki-ohnaka-cv** [eclipse/che#22099]
### Summary

We would like to create our own dashboard.

We would like to create our own dashboard image, deploy it as a pod/container, and call the che dashboard API from there. (We want to reuse some of che dashboard's APIs.)
However, the che gateway settings are fixed to the che dashboard pod orientation and cannot be changed. (If I change it, the che operator rolls back the change.)
We also tried to include our dashboard container in the che dashboard pod, but the che dashboard container uses the 8080 port and cannot be changed as well.

We do not want to fork che dashboard and customize the che dashboard image itself, as we believe it would be a major pain to keep up with the chen version upgrades.

Do you have any suggestions?

**Comment by l0rd** [comment]
👋 @yuki-ohnaka-cv. Have you tried to specify your container image in CheCluster [`spec.components.dashboard.deployment.containers[].image`](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.62.0#spec-components-dashboard-deployment-containers-image)?

**Comment by yuki-ohnaka-cv** [comment]
@l0rd 
Thanks for the advice.
Do you mean to specify a custom dashboard image for that option, deploy the original `che dashboard` Service/Pod under an alias, and access the original `che dashboard` from the custom dashboard image?

**Comment by tolusha** [comment]
A custom dasbhoard image will be used.
Out of curiosity, why do you need to access original dashboard?

**Comment by yuki-ohnaka-cv** [comment]
@tolusha 
We would like to customize our own dashboard. (We want to extend the functionality while also using `che` features.)
However, we would also like to incorporate future updates to `che`. If we fork `che dashboard` and customize it, we expect that it will be difficult to incorporate updates (due to conflicts, etc.).
Therefore, we wanted to call the `che dashboard` API from the backend of our dashboard.

**Comment by olexii4** [comment]
@yuki-ohnaka-cv I agree with @tolusha.  You can deploy the original Dashboard and open 
```{CHE}/dashboard/api/swagger```
![2023-03-31_17_29_12](https://user-images.githubusercontent.com/6310786/229148838-f123a54c-fc14-4aa2-8a45-786c3d781a27.png)

**Comment by yuki-ohnaka-cv** [comment]
@olexii4 (@tolusha )
Thanks for the solution.
I understood that I still need the original dashboard container/pod.
By deploying my dashboard (FE/BE) container using `spec.components.dashboard.deployment.containers[].image` and manually deploying the original dashboard container I will call the original dashboard API from my dashboard.

I would like to be able to specify the port number of the original dashboard or the port number of the dashboard pod in the che dashboard in the CR patch, so that both my dashboard and the che dashboard can call the `spec.components.dashboard. I thought it would be nice to be able to include it in `deployment.containers[].image`.
