### ISSUE TITLE
allow configuration of ingress rules' pathType

### ISSUE THREAD

**Issue by pantoninho** [eclipse/che#22096]
### Is your enhancement related to a problem? Please describe

I'd like to be able to set che's main ingress rule pathType through CheCluster resource configuration. It is being set as the default value, ImplementationSpecific, which, in the AWS Application Load Balancer works like "Exact". This is problematic because `/dashboard` does not match with the `/` exact route.

### Describe the solution you'd like

I'd like to be able to patch this value through `--che-operator-cr-patch-yaml` flag when deploying Eclipse Che with `chectl`.

### Describe alternatives you've considered

The only solution I've found is to edit the ingress after creation which is ok but makes the deployment process a little bit more complex.

**Comment by pantoninho** [comment]
I'd love to be able to contribute and implement this feature but I've just started getting into the codebase and don't have a lot of context yet.

**Comment by tolusha** [comment]
There are everything related to networking [1] which is used here [2]
Probably we can a new field like `ingressPathType`.

[1] https://github.com/eclipse-che/che-operator/blob/main/api/v2/checluster_types.go#L181
[2] https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/ingress.go#L77
