### ISSUE TITLE
`chectl` on Mac OS Ventura throws self signed cert error (OKD 4.12)

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22097]
### Describe the bug

OKD 4.12
`chectl` on Mac OS Ventura
OpenShift certs are trusted in the Mac OS keychain

When logged in as a cluster admin user, chectl throws a self signed cert error as illustrated below.

```bash
chectl server:deploy --platform openshift --no-auto-update --batch
Error: self signed certificate in certificate chain
Code: SELF_SIGNED_CERT_IN_CHAIN
```

However, if the cluster is accessed by setting `KUBECONFIG` to a cluster admin kubeconfig file, the `chectl` command completes successfully.

### Che version

7.61@latest

### Steps to reproduce

1. Login as a cluster admin user
2. execute a `chectl` command that accesses the cluster
3. Observe the error.

To mitigate:

1. export KUBECONFIG=/path/to/a/cluster-admin/kubeconfig
2. execute a `chectl` command that accesses the cluster
3. Observe success

### Expected behavior

`chectl` command trusts the certs which are in the Mac OS keychain

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

**Comment by tolusha** [comment]
@cgruver 
Kubernetes client reads the configuration from a file either defined in the KUBECONFIG environment variable or in the default path `$HOME/.kube/config`. If both are missed then `export KUBECONFIG=<..>` is a valid workaround.

**Comment by cgruver** [comment]
Understood, but what is vexing is that I am logged into the OKD cluster, with a cluster-admin user.  But, `chectl` does not appear to trust the cert.

```bash
oc get nodes
NAME                                  STATUS   ROLES                        AGE   VERSION
okd4-region-01-master-0.dc1.clg.lab   Ready    control-plane,infra,master   27d   v1.25.7+eab9cc9
okd4-region-01-master-1.dc1.clg.lab   Ready    control-plane,infra,master   27d   v1.25.7+eab9cc9
okd4-region-01-master-2.dc1.clg.lab   Ready    control-plane,infra,master   27d   v1.25.7+eab9cc9
okd4-region-01-worker-0.dc1.clg.lab   Ready    worker                       27d   v1.25.7+eab9cc9
okd4-region-01-worker-1.dc1.clg.lab   Ready    worker                       27d   v1.25.7+eab9cc9
okd4-region-01-worker-2.dc1.clg.lab   Ready    worker                       27d   v1.25.7+eab9cc9
```

```bash
ls -l .kube/  
total 16
drwxr-x--- 4 charrogruver staff   128 Jan  4 07:36 cache
-rw------- 1 charrogruver staff 14613 Apr  7 08:35 config
```

```bash
chectl server:status
    Error: self signed certificate in certificate chain
    Code: SELF_SIGNED_CERT_IN_CHAIN
```

**Comment by tolusha** [comment]
You mentioned, that `export KUBECONFIG=/path/to/a/cluster-admin/kubeconfig` solves the problem.
So, I really don't understand what is going on.
Did you use `oc login` command to log into the cluster?

**Comment by cgruver** [comment]
Yes.  I logged into the cluster with `oc login`.

Note that `oc login` only works if I have the cluster cert in my Keychain.

**Comment by tolusha** [comment]
I see.
You can specify cert in your kubeconfig file. In this case both `oc` and `chectl` tools will work.
```
clusters:
- cluster:
    certificate-authority: <PATH_TO_CERTIFICATE>
    server: <SERVER_API_ADDRESS>
  name: <SOME_NAME>
```
