### ISSUE TITLE
devworkspace-generator should support git repositories other than github.com

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22105]
### Is your enhancement related to a problem? Please describe

Devfile registry build, and in particular the `devworkspace-generator`, requires that the samples are in github.com. 

If the samples are in GitHub enterprise repositories (e.g. `github.<mycompany>.com`) it's not possible to do a custom build of the registry.

Here are [a couple](https://github.com/eclipse-che/che-devfile-registry/blob/main/tools/devworkspace-generator/src/github/github-resolver.ts) of [places](https://github.com/eclipse-che/che-devfile-registry/blob/main/tools/devworkspace-generator/src/github/github-url.ts) where github.com is hardcoded.

### Describe the solution you'd like

Supporting resolvers for GH enterprise, BB, GitLab etc...maybe overkill. 

An alternative could be that samples get cloned locally and then [generate_devworkspace_templates.sh](https://github.com/eclipse-che/che-devfile-registry/blob/main/build/scripts/generate_devworkspace_templates.sh) invokes `devworkspace-generator` using the parameter `--devfile-path` rather than the `--devfile-url`.

### Additional context

Note that currently, using parameter `--devfile-path` rather than `--devfile-url`, results in a devworkspace without a project (even if the `--project` parameter is provided):

```
node lib/entrypoint.js \
     --devfile-path:<git-repo-path>/devfile.yaml \
     --editor-entry:che-incubator/che-code/insiders \
     --plugin-registry-url:https://che-plugin-registry-main.surge.sh/v3/ \
     --output-file:/tmp/all-in-one-local.yaml \
     --project."<name>=<git-repo-path>"
```

So that should be fixed first.

**Comment by vinokurig** [comment]
> An alternative could be that samples get cloned locally and then [generate_devworkspace_templates.sh](https://github.com/eclipse-che/che-devfile-registry/blob/main/build/scripts/generate_devworkspace_templates.sh) invokes devworkspace-generator using the parameter --devfile-path rather than the --devfile-url.

I don't think it is a good idea to git clone projects just for one file. I prefer to extend the resolver to be able to parse GitLab and Bitbucket urls.

**Comment by ibuziuk** [comment]
@l0rd discussed that issue on the standup, wdyt would it be enough to support all SaaS versions (GitHub, BitBucket, GitLab, Azure) + the GitHub enterprise whose domain matches the pattern `github.<mycompany>.com` ?

**Comment by l0rd** [comment]
> @l0rd discussed that issue on the standup, wdyt would it be enough to support all SaaS versions (GitHub, BitBucket, GitLab, Azure) + the GitHub enterprise whose domain matches the pattern `github.<mycompany>.com` ?

GitHub Enteprise is enough. I am not sure we are going to get requests for other Git providers considered that we plan to [switch to CNCF registry.devfile.io in the short/mid term](https://github.com/eclipse/che/issues/20251).

**Comment by vinokurig** [comment]
@l0rd Is it ok to use the `github.<mycompany>.com` pattern and can we consider that the `subdomain isolation` property is always on in the github server instance? It means that the raw file location url will match the `https://raw.<mycompany>.com/<user>/<repo>/<path to the file>`. It will work for the Ford case but might not work for others.
