### ISSUE TITLE
Generalize Dex deployment

### ISSUE THREAD

**Issue by gbonnefille** [eclipse/che#22104]
### Is your enhancement related to a problem? Please describe

I want to deploy Che in local instances, without deploying complex Keycloack, but not on minikube.

### Describe the solution you'd like

The `--platform minikube` deploys a local dex. Having options to deploy dex even with `--platform k8s` could be useful.

**Comment by ibuziuk** [comment]
@gbonnefille thank you for the interest in the project, would you be interested in contributing this functionality?

**Comment by gbonnefille** [comment]
Does it mean the proposed idea deserve a PR?

Technically, I'm not a JS dev.

**Comment by tolusha** [comment]
> The --platform minikube deploys a local dex. Having options to deploy dex even with --platform k8s could be useful.

@gbonnefille 
That is barely possible. 
Installing dex implies configuring Kuberenes API server. We can't do this without knowing the specific platform.

**Comment by gbonnefille** [comment]
> > The --platform minikube deploys a local dex. Having options to deploy dex even with --platform k8s could be useful.
> 
> @gbonnefille That is barely possible. Installing dex implies configuring Kuberenes API server. We can't do this without knowing the specific platform.

I'm not sure to understand what you refer. Installing Dex is *as simple as* deploying an Helm chart. What K8S API need to be configured?
