### ISSUE TITLE
Not possible to create a new workspace from the sample

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#22108]
### Describe the bug

When I'm trying to create a new workspace from a sample chosen on the dashboard, it's failed. See the screenshot attached.

### Che version

next (development version)

### Steps to reproduce

Pick any sample on the dashboard to create a new workspace.

### Expected behavior

A new workspace should be created from the picked sample.

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1636395/228510468-bd4c7066-5e9d-4da6-90c4-5ac7cfb9f3b4.png)

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
che-operator PR does not seem to fix the issue
As a workaround had to explicitly specify the default editor and enable container build capabilities:

```
  devEnvironments:
    disableContainerBuildCapabilities: false
    defaultEditor: che-incubator/che-code/latest
```
