### ISSUE TITLE
Make "Devfile" on User Dashboard uneditable

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22115]
### Is your enhancement related to a problem? Please describe

"Devfile" view should be read-only

### Describe the solution you'd like

Make "Devfile" on User Dashboard uneditable:
![image](https://user-images.githubusercontent.com/1461122/228835615-ed6b2e0d-e7f8-46ed-b21c-310183cffa83.png)

### Describe alternatives you've considered

N/A

### Additional context

Devfile editing UX should happen from workspace, not dashboard - https://github.com/eclipse/che/issues/21606

**Comment by amisevsk** [comment]
Setting priority to P1 as there are other issues with the devfile editor -- e.g. it will set the `schemaVersion` to `2.1.0` and warn about invalid fields that were added in `2.2.0`, which can be confusing if you are trying to work on a `2.2.0` devfile.

**Comment by tolusha** [comment]
@ibuziuk 
I think it is a nice feature to edit devfile after workspace is created.
What do we need to make devfile uneditable?

**Comment by ibuziuk** [comment]
@tolusha well, this is not how we expect the user to edit the devfile - https://github.com/eclipse/che/issues/21606
basically, the editing is expected to happen in the workspace, not from UD

**Comment by ibuziuk** [comment]
PR has been merged, Closing

**Comment by dmytro-ndp** [comment]
Devfile could be edited in Dashboard using Eclipse Che Next:
![Screenshot from 2023-04-19 12-50-13](https://user-images.githubusercontent.com/1197777/233037819-e7708d60-fe51-40b3-b768-1f291616a391.png)

**Comment by ibuziuk** [comment]
should be fixed by https://github.com/eclipse-che/che-dashboard/pull/783

**Comment by dmytro-ndp** [comment]
The notice: read-only devfile in Dashboard will make it harder to work with _Empty Workspace_, which is aimed to simplify custom workspace creation.

**Comment by ibuziuk** [comment]
@dmytro-ndp could you clarify why?

**Comment by dmytro-ndp** [comment]
Because it's not clear how to change devfile.yaml in empty workspace, which is not pushed to any repos.

**Comment by ibuziuk** [comment]
empty workspace is meant to be used for cloning the project manually after startup, not for editing devfile from the UD. More details about the devfile editing experience can be found in the epic - https://github.com/eclipse/che/issues/21606

**Comment by ibuziuk** [comment]
PR has been merged. Closing, feel free to reopen if more clarification is needed

**Comment by dmytro-ndp** [comment]
@ibuziuk : thanks for explanation.
Hope, users will understate it having the guide about creation of devfile (https://github.com/eclipse/che/issues/18671)

**Comment by dmytro-ndp** [comment]
Dashboard > workspace > Devfile is read-only on Che dogfooding instance.

Well done, @ibuziuk !

**Comment by dmytro-ndp** [comment]
@ibuziuk : what do you think about removal of UI elements - **Devfile Documentation** link, **Save / Cancel** buttons which became useless in read-only mode?
![useless-ui-elements](https://user-images.githubusercontent.com/1197777/233383589-f4f0eaed-76dc-467e-a963-1b766dc3a095.png)
