### ISSUE TITLE
[UD] Improve the development flow with skaffold.dev on dogfooding

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22116]
### Is your task related to a problem? Please describe

While implementing new features and fixing issues, building artifacts and applying them on a cluster takes time to see the result. [skaffold.dev](https://skaffold.dev/) supports copying changed files to a deployed container so as to avoid the need to rebuild, redeploy, and restart the corresponding pod ([file sync doc](https://skaffold.dev/docs/filesync/)). Also, it handles the workflow for building, pushing, and deploying applications.

### Describe the solution you'd like

Investigate the possibility and implement the code hot-reloading in the che-dashboard pod using the file sync feature. 

### Describe alternatives you've considered

The alternative option is to implement [the continuous development flow](https://skaffold.dev/docs/workflows/dev/), when skaffold will watch changes, rebuild images, and redeploy the application on the cluster.

**Comment by l0rd** [comment]
Can we do this investigation running skaffold in a Che workspace? We [have been experimenting](https://gist.github.com/l0rd/70eeb2bbef4b18f41e2d1e382e2be05f) with [tilt.dev](https://tilt.dev/) in a Che workspace last year and using skaffold should be straightforward.
