### ISSUE TITLE
As a User, I want to configure SSH keys from the User Dashboard

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22111]
### Is your task related to a problem? Please describe

As a user, I want to configure SSH keys from the User Dashboard

### Describe the solution you'd like

Possibility to add / remove SSH Keys similar to https://github.com/settings/keys

![image](https://user-images.githubusercontent.com/1461122/228793697-69f3f49c-8422-455d-b1d6-10d5cffb2b3d.png)

### Describe alternatives you've considered

Manual SSH configuration by the dedicated secret creation

### Additional context

Info about manual SSH Configuration - https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-devworkspaces-to-use-ssh-keys-for-git-operations

**Comment by vinokurig** [comment]
In order to make the process easier for a user, I believe we should be able not just add SSH key pair from the dashboard input, but also to be able to generate a new key pair by the dashboard. User should be able to copy the public part of the generated key, and then pass it to an SCM provider.
