### ISSUE TITLE
[UD] Increase coverage and stability of the tests for the che-dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22117]
### Is your task related to a problem? Please describe

Even though test coverage is relatively high, not all core functionality is covered with unit tests.

### Describe the solution you'd like

It's needed to determine gaps to be thoughtfully tested.

**Comment by ibuziuk** [comment]
Had a grooming session with @olexii4 and @akurinnoy the target is 85 % coverage for user dashboard
