### ISSUE TITLE
Implement 2FA flow for Git OAuth Page

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse/che#22110]
### Is your task related to a problem? Please describe

Currently we do not have any easy way to log in to for example dogfooding instance, always requires manual, local code modifications to be able to run tests there. This flow is critical for upstream development as dogfooding is running nightly builds which match to the `main` branch

### Describe the solution you'd like

* implement 2FA OAuth flow

### Describe alternatives you've considered

.

### Additional context

.

**Comment by Daybringer** [comment]
Hey, I would like to take this task upon myself.

**Comment by ibuziuk** [comment]
@nallikaea @ScrewTSW noticed that PR was closed, can we also close this issue?
