### ISSUE TITLE
How to increase resource limits of project-clone sidecar?

### ISSUE THREAD

**Issue by miboettc** [eclipse/che#22128]
### Summary

Currently, the project-clone sidecar container has resource limits configured as cpu:1,memory:1Gi. When cloning large projects this is not sufficient, resulting in an OOM error when creating a workspace from a git url. 

Is there a possibility to increase the resource limit for project-clone containers?

**Comment by ibuziuk** [comment]
@amisevsk could you please take that one? AFAIK limits requests are hardcoded and it is not possible to override on DWOC level - https://github.com/devfile/devworkspace-operator/blob/7e8aa722dfb4f2a168933bc51edb1aedb5b56b85/pkg/constants/constants.go#L59-L63

**Comment by miboettc** [comment]
In some (older) issues a variable CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB is mentioned in the context of the customCheProperties field, part of the CheCluster Custom Resource. Would setting this variable help ?

**Comment by AObuchow** [comment]
> In some (older) issues a variable CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB is mentioned in the context of the customCheProperties field, part of the CheCluster Custom Resource. Would setting this variable help ?

I don't believe that will have any effect on the project clone container unfortunately.

@ibuziuk I will be taking this on as part of https://github.com/eclipse/che/issues/22036

**Comment by ibuziuk** [comment]
makes sense, closing in favor of https://github.com/eclipse/che/issues/22036
@miboettc thanks  for reporting and feel free to provide additional details in ^
