### ISSUE TITLE
Eclipse Che install without K8S OIDC

### ISSUE THREAD

**Issue by flavienbwk** [eclipse/che#22138]
### Summary

Hi,

Che currently has a big footprint on one's cluster (looks like it **requires** the edit of kube-apiserver to bind Keycloak as an OIDC provider).

Is it possible to make Che work with Keycloak but without my cluster bound to Keycloak ?

Thank you.

### Relevant information

- Kubernetes 1.26
- Keycloak 20

**Comment by tolusha** [comment]
@flavienbwk 
It is possible to use another OIDC provider, but there is no way to completely get rid of it with the current Che architecture.

**Comment by l0rd** [comment]
We made a choice to require that a Che user should also be a Kubernetes user. 

The rational behind that is that a Che user creates Kubernetes resources and the most straightforward way to control what he/she can do is using Kubernets RBAC. In other words we didn't want to reinvent the wheel.

I am sorry @flavienbwk but I am afraid that we have no plan to support what you are asking at the moment. I am closing this issue but feel free to re-open it if someone is going to work on it.

**Comment by flavienbwk** [comment]
Thank you for your answers.

There's a lot of edge cases and missing step-to-step documentation when configuring Eclipse Che with a native Kubernetes cluster (kubeadm), as opposed to the Minikube-based install. I've finally managed to make a [successful Eclipse Che install](https://github.com/flavienbwk/eclipse-che-kubernetes) on my kubeadm-installed cluster.

**Comment by tolusha** [comment]
@flavienbwk 
Thank you a lot for sharing.
