### ISSUE TITLE
Invalid CSRF token error during authentication: set OAuth2 Proxy --cookie-csrf-per-request flag as "true"

### ISSUE THREAD

**Issue by Ex4amp1e** [eclipse/che#22135]
### Describe the bug

This bug https://github.com/eclipse/che/issues/21861 is still reproducible, because the bump of oauth2-proxy version to 7.4.0 only wasn't enough, because  https://github.com/oauth2-proxy/oauth2-proxy/pull/1708 fix just added a flag to resolve a problem, but the default value is "false", so che-operator has to define it as "true" [here](https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go)

### Che version

7.63@latest

### Steps to reproduce

1. Open two tabs with login form to the dashboard
2. Log in from the first tab
3. Try to log in from the second

### Expected behavior

No errors, user can see 2 tabs and both are successfully logged in

### Runtime

Kubernetes (vanilla)

### Screenshots

![image](https://user-images.githubusercontent.com/58589910/230423964-4725eeb8-9a6a-4330-9d2c-a0db2c2896ce.png)

### Installation method

chectl/latest

### Environment

Linux

**Comment by tolusha** [comment]
@Ex4amp1e 
> so che-operator has to define it as "true" [here](https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go)

Could you point out the exact line you were referring to?

**Comment by miguelborges99** [comment]
@tolusha I think it is the flag "--cookie-csrf-per-request". It is set to false by default. 
This was done to avoid breaking the former behavior, one CSRF cookie for all authentication requests. 
If there are no parallel authentication requests, then one CSRF cookie is enough.

I do not have problems, if the handling of "parallel authentication requests" is enabled by default.

@Ex4amp1e, @JoelSpeed what do you think?

**Comment by ynqa** [comment]
I encountered the same issue. As @miguelborges99 mentioned, adding the `--cookie-csrf-per-request` flag to oauth-proxy avoided 403 error.

Please note that after `kubectl delete deployment che-operator` I executed `kubectl edit deployment che-gateway` for patches. This is to prevent the operator reconcile from reverting the patches.
