### ISSUE TITLE
$GOBIN not set in universal-developer-image:ubi8-latest

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#22132]
### Is your enhancement related to a problem? Please describe

I wanted to install a go binary (`goimports`) in my workspace and then run it, but the Go bin directory (`/home/user/go/bin`) was not on $PATH, so running `./goimports` had no effect. 

### Describe the solution you'd like

In the UDI, $GOBIN should be set: `export GOBIN=/home/user/go/bin`
and $GOBIN should be added to $PATH: `export PATH=$PATH:$GOBIN`

### Describe alternatives you've considered

You can manually add the go bin directory to $PATH by doing: `export PATH=$PATH:/home/user/go/bin`

You could also set this environment variable in the devfile, but this seems like a bit more work to do for certain cases.

**Comment by AObuchow** [comment]
@l0rd @ibuziuk Is this something we'd want for the UDI? A PR for this seems relatively simple and I'd be willing to work on this. 

This is something that can be worked around through the devfile, as shown [here](https://github.com/eclipse-che/che-operator/pull/1698/files#diff-23d39e3ae288b080d8aa0995928cd3c432f887a75f0ab3bba675089f51a4af8eR45). It might be nice to have this set by default, however.

**Comment by l0rd** [comment]
@AObuchow yes please submit a PR
