### ISSUE TITLE
Unable to pull container images from the OpenShift internal registry

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22140]
### Describe the bug

Within a running workspace, `podman` is able to pull images from external registries like `quay.io` but is unable to pull images from the internal OpenShift Registry.

The internal registry certificate is not trusted, and the workspace user is not authorized.

### Che version

7.63@latest

### Steps to reproduce

1. Create a workspace with [https://github.com/eclipse-che-demo-app/che-demo-app.git](https://github.com/eclipse-che-demo-app/che-demo-app.git)
1. Start a terminal
1. Execute:

   ```bash
   podman pull quay.io/sclorg/postgresql-15-c9s:c9s
   ```

1. Observe success:

   ```bash
   WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
   Trying to pull quay.io/sclorg/postgresql-15-c9s:c9s...
   Getting image source signatures
   Copying blob 204a508c7797 done  
   Copying blob 1a4b50973163 done  
   Copying blob eae77addda82 done  
   Copying config 034374e72d done  
   Writing manifest to image destination
   Storing signatures
   034374e72d2c12dacc9e3557f8752d3407b1b69ca9aed1e7ea709a31922f180c
   ```

1. Execute:

   ```bash
   podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
   ```

1. Observe error:

   ```bash
   Trying to pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest...
   Error: initializing source docker://image-registry.openshift-image-registry.svc:5000/openshift/cli:latest: pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": x509: certificate signed by unknown authority
   ```

1. Ignore TLS:

   ```bash
   podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest --tls-verify=false
   ```

1. Observe authentication error:

   ```bash
   Trying to pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest...
   Error: initializing source docker://image-registry.openshift-image-registry.svc:5000/openshift/cli:latest: reading manifest latest in image-registry.openshift-image-registry.svc:5000/openshift/cli: unauthorized: authentication required
   ```

### Expected behavior

Expect `podman` configuration to be setup for interacting with the internal image registry.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

### Additional context

OpenShift is OKD 4.12

**Comment by l0rd** [comment]
@cgruver makes sense. Do you know if the trusted certificates path can be specified in podman configuration?

**Comment by tolusha** [comment]
We can pull images from the OpenShift registry in the following steps:

1. mkdir $HOME/openshift-registry-certs
2. openssl s_client -showcerts -connect image-registry.openshift-image-registry.svc:5000 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $HOME/openshift-registry-certs/ca.crt
3. TOKEN=$(oc whoami -t)
4. podman login --cert-dir $HOME/openshift-registry-certs/ -u opentlc-mgr -p $TOKEN image-registry.openshift-image-registry.svc:5000
5. podman pull --cert-dir $HOME/openshift-registry-certs/ image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

The OpenShift registry certificate can be put into `/etc/docker/certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt` to avoid using `--cert-dir` flag. I believe all those steps can be automated with Dasboard.

**Comment by l0rd** [comment]
@tolusha this is important information. Isn't the registry certificate already included in the OpenShift trusted certificate bundle?

**Comment by tolusha** [comment]
It is even better, the certificate is already mounted into a container:
```
podman login --cert-dir /var/run/secrets/kubernetes.io/serviceaccount -u $(oc whoami) -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000
podman pull --cert-dir /var/run/secrets/kubernetes.io/serviceaccount image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
```

**Comment by l0rd** [comment]
Ok so in UDI we could have a simbolic link like the following one to make things work automatically.

```bash
ln -s /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  \
      /etc/docker/certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
```

**Comment by l0rd** [comment]
Or having the dashboard doing that when it creates the kubeconfig.

**Comment by cgruver** [comment]
I vote for having the dashboard handle it.  A lot of users will build their own tools image rather than using UDI.  So, that would be one less thing to have to build into their custom dev tools images.

**Comment by ibuziuk** [comment]
@l0rd it looks like the symlink approach not going to work due to lack of permissions, basically, `/etc/docker/certs.d/image-registry.openshift-image-registry.svc:5000/` does not exist and we can not create it

**Comment by ibuziuk** [comment]
we can technically introduce another endpoint on the UD end that will do the `podman login` to the internal OpenShift registry and call it during the workspace startup

![image](https://user-images.githubusercontent.com/1461122/233628682-3dd4dc7e-e2a1-48fb-8af5-06a1c48bbccc.png)

Draft PR -  https://github.com/eclipse-che/che-dashboard/pull/785

**Comment by l0rd** [comment]
The PR has been merged.

**Comment by ibuziuk** [comment]
I checked on dogfooding and it does not seem to work 
![image](https://github.com/eclipse/che/assets/1461122/935aa156-8d06-43f2-a3e1-cd4856d14c74)

**Comment by ibuziuk** [comment]
after some investigation and discussions, the podman login injection is working correctly and the following command is executed during workspace startup:
```
podman login --cert-dir /var/run/secrets/kubernetes.io/serviceaccount -u $(oc whoami) -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000
```

However, in order to pull the image from the internal registry one still needs to explicitly provide `--cert-dir /var/run/secrets/kubernetes.io/serviceaccount` flag to the `podman pull` command (or ignore tls via `--tls-verify=false`).

@benoitf do you happen to know if there is a mechanism we can use for configuring podman via file / env var to point to the right certificate that would allow executing `podman pull` from the terminal without extra flags?

**Comment by benoitf** [comment]
@ibuziuk use the `/etc/containers/certs.d` directory ?

**Comment by ibuziuk** [comment]
@l0rd suggested smth. similar https://github.com/eclipse/che/issues/22140#issuecomment-1503003054 
but I don't think we have permission to create the symlink once workspace is started

**Comment by ibuziuk** [comment]
@benoitf tried the approach with symlink but it does not seem to work

```
projects $ mkdir -p $HOME/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000
projects $ ln -s /var/run/secrets/kubernetes.io/serviceaccount/ca.crt $HOME/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
projects $ ls -la $HOME/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
lrwxrwxrwx. 1 user root 52 May 16 17:07 /home/user/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt -> /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
projects $ podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
Trying to pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest...
Error: initializing source docker://image-registry.openshift-image-registry.svc:5000/openshift/cli:latest: pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": x509: certificate signed by unknown authority
```
Checking the file permissions, but https://github.com/containers/image/blob/main/docs/containers-certs.d.5.md#directory-structure does not say anything about that 
also bumped into that issue https://github.com/containers/podman/issues/13823

**Comment by l0rd** [comment]
@ibuziuk you are linking the external routes certs CA (`ca.crt`) but you need to link the internal services certs CA (`service-ca.crt`) to make it work. 

If I run the following commands on developer sandbox

```bash
export CERTS_SRC="/var/run/secrets/kubernetes.io/serviceaccount"
export CERTS_DEST="$HOME/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000"

mkdir -p ${CERTS_DEST} && \
ln -s ${CERTS_SRC}/service-ca.crt ${CERTS_DEST}/service-ca.crt && \
podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
```

I get `unauthorized: authentication required` rather than `x509: certificate signed by unknown authority`

In general we should link both certificates.

**Comment by ibuziuk** [comment]
PR has been sent - https://github.com/eclipse-che/che-dashboard/pull/851

**Comment by ibuziuk** [comment]
PR has been merged https://github.com/eclipse-che/che-dashboard/pull/851 
Closing
@cgruver could you please clarify how you are using the images from the internal registry from the Eclipse Che workspace? Would be really interested in knowing the use-case

**Comment by KevinMGranger** [comment]
@ibuziuk (I'm not Charro but I'm on a team they've worked with)

We're building containers within Dev Spaces. Unless $HOME is persistent, we'll lose those containers when the workspace restarts-- so we push them to the internal registry.
