### ISSUE TITLE
MacOS - unable to install checli 

### ISSUE THREAD

**Issue by JCzz** [eclipse/che#22147]
### Describe the bug

From doc:

https://www.eclipse.org/che/docs/stable/administration-guide/installing-the-chectl-management-tool/

bash <(curl -sL  https://www.eclipse.org/che/chectl/)

### Che version

7.63@latest

### Steps to reproduce

```
bash <(curl -sL  https://www.eclipse.org/che/chectl/)
chectl script requires superuser access.
You will be prompted for your password by sudo.
Password:
env: /opt/homebrew/opt/coreutils/libexec/gnubin: Permission denied
```

### Expected behavior

It works

### Runtime

Kubernetes (vanilla)

### Screenshots

MacOS

### Installation method

chectl/latest

### Environment

macOS

### Eclipse Che Logs

```shell
No log
```

### Additional context

No additional

**Comment by tolusha** [comment]
Can you check if all prerequisites are met?
- The directory `/usr/local/bin` is in the user `$PATH`.
- The `sudo` command is configured for the current user.
- No old or undesired versions of `chectl` present on the system.

/cc @akurinnoy

**Comment by JCzz** [comment]
Hi @tolusha 

Thanks, I can confirm that the prerequisites mentioned is met.
