### ISSUE TITLE
[registry.devfile.io] workspace can not be started - 'Cannot define default editor'

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22141]
### Describe the bug

![image](https://user-images.githubusercontent.com/1461122/231113570-f7596aac-855e-495a-92f6-1100341d7b4d.png)

### Che version

7.63@latest

### Steps to reproduce

Reproducers:
- [ ] https://registry.devfile.io/devfiles/dotnet60/1.0.2

### Expected behavior

Workspace started with the default editor configured for the cluster:

![image](https://user-images.githubusercontent.com/1461122/231113113-649f02b7-ab33-46a5-81bd-07c33358acb4.png)

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

Looks like we can not read the default editor from CR - [https://github.com/eclipse-che/che-dashboard/blob/4b1059f28ba33f76513097dc411c80b4[…]/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts](https://github.com/eclipse-che/che-dashboard/blob/4b1059f28ba33f76513097dc411c80b4d9db2a54/packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts#L619)

**Comment by olexii4** [comment]
@ibuziuk I cannot reproduce it on https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com and locally. Could you provide more information?

BTW: I have the same effect after setting the wrong default editor(not from the current registry).
