### ISSUE TITLE
Unable to build che-devfile-registry locally

### ISSUE THREAD

**Issue by aaswan** [eclipse/che#22148]
### Summary

I am trying to add a new workspace to the installation of eclipse che on minikube. For this purpose after deploying default che server using chectl on minikube, I am trying to build che-devfile-registry in the minikube env.
But whatever changes that I do, I am unable to see the changes getting reflected in the built image.
I followed the below process
1. git clone https://github.com/eclipse-che/che-devfile-registry.git
2. ./build.sh
3. docker images list a new image with the next tag
4. Deploy the registry using helm. helm upgrade --install che-devfile-registry     --debug     --namespace ${NAMESPACE}     --set global.ingressDomain=${DOMAIN}     ./deploy/kubernetes/che-devfile-registry/
5. docker ps | grep che-devfile-registry
6. docker exec -it container_id /bin/bash
7. ls htdocs/devfiles/
I do not see the new devfile that i added. Also the devfile that I deleted for experimentation was also present. The string changes to displayname in few devfiels were also not reflected.
Please help

**Comment by tolusha** [comment]
I have some doubts if this [1] doc is relevant. 
I suggest the following:
1. Clone, modify and build registry locally.
2. Use custom plugin registry image with existed Eclipse Che deployment:
```
kubectl patch checluster/eclipse-che --patch '{"spec": {"components": {"devfileRegistry": {"deployment": {"containers": [{"image": "<CUSTOM_IMAGE>"}]}}}}}' --type=merge -n eclipse-che
```
or, if you have already copied image into minikube:
```
kubectl patch checluster/eclipse-che --patch '{"spec": {"components": {"devfileRegistry": {"deployment": {"containers": [{"image": "<CUSTOM_IMAGE>", "imagePullPolicy": "IfNotPresent"}]}}}}}' --type=merge -n eclipse-che
```


https://github.com/eclipse-che/che-plugin-registry#run-eclipse-che-plugin-registry-on-kubernetes
