### ISSUE TITLE
Dashboard ignores 403 Forbidden errors while creating workspace

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22145]
### Describe the bug

When creating a workspace from a Devfile, it is possible for the dashboard to encounter a 403 Forbidden error. When this happens, the dashboard continues with workspace startup and does not show any messages to the users suggesting there is a problem. 

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace from a devfile that uses a `kubernetes`-type component that the DevWorkspace Operator cannot manage, e.g. https://gist.githubusercontent.com/amisevsk/5b225feda944c050f9b275506916d4e4/raw/3f748ae0502a45f6d7844d949572266d5093519c/kube-components.devfile.yaml
2. Wait for workspace to start without errors or warnings
3. Check devfile/DevWorkspace and see that it contains no components

In the shared sample, on an OpenShift cluster with the Strmzi operator installed, the following request fails:
```
Request URL: https://eclipse-che.apps.<snip>.com/dashboard/api/namespace/<namespace>/devworkspaces/che-test-workspace
Request Method: PATCH
Status Code: 403 Forbidden
```
the payload for this patch adds components to the DevWorkspace.

### Expected behavior

Dashboard should show user a warning or error during workspace start if one of the requests it performs fails.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by vinokurig** [comment]
Is fixed by https://github.com/eclipse-che/che-dashboard/pull/803
