### ISSUE TITLE
GOBIN should be set in Che-Operator Devfile and added to PATH

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#22154]
### Is your enhancement related to a problem? Please describe

I've been using Che to run `make update-dev-resources` for the Che-Operator repo since I have Go 1.19 installed and the repo is on Go 1.18 (Lazy, I know... but a good excuse for dog fooding :P) 

A prerequisite for running `make update-dev-resources` is to have `goimports` installed and on PATH. I've been manually doing this by running `go install golang.org/x/tools/cmd/goimports@latest && export PATH=$PATH:/home/user/go/bin`. 

It'd be nice to already have GOBIN on path.

### Describe the solution you'd like

GOBIN should be declared in the [environment variables](https://github.com/eclipse-che/che-operator/blob/main/devfile.yaml#L25) of the Che-Operator devfile, and added to PATH

### Describe alternatives you've considered

Manually running `export PATH=$PATH:/home/user/go/bin` or adding this command to the Makefile in the Che-Operator repo. 

### Additional context

Related to https://github.com/eclipse/che/issues/22132, which would remove the requirement for setting up GOBIN in devfiles manually.

**Comment by tolusha** [comment]
@AObuchow 
I  think we can close this issue
