### ISSUE TITLE
Unable to load project source code in VSCode project explorer when launching che server with locally built devfile registry as che {{ INTERNAL_URL }} variable is not resolved

### ISSUE THREAD

**Issue by aaswan** [eclipse/che#22169]
### Summary

Unable to load project source code in VSCode project explorer when launching che server with locally built devfile registry as che {{ INTERNAL_URL }} variable is not resolved

### Relevant information

Hi, I am new to eclipse-che. Trying it out in minikube on my local machine.
I am able to deploy & launch the default che-server. I am also able to start the default workspaces in the browser.
Facing issue when trying to open workspaces when building my own devfile registry.
I have followed these steps to build.

Cloned https://github.com/eclipse-che/che-devfile-registry
Changed teh displayname of node meta.yaml
Modified deploy/kubernetes/che-devfile-registry/values.yaml file from cheDevfileRegistryImagePullPolicy: Always to cheDevfileRegistryImagePullPolicy: IfNotPresent
Built the registry using build.sh
using helm installed registry
redeployed che server pointing to new devfile registry host
With the above steps I am able to see the list of workspaces in the dashboard. Verified that my locally built devfile registry is being used via the minikube dashboard.(Also with the help of modified dispalyname of node workspace)
But when I open any workspace it is unable to show project files in the vscode insatnce -> project explorer
There is an error file in /projects folder which says {{ INTERNAL_URL }} could not resolved.
Infact when I checked the devfile in the workspace
projects:

name: xxxx zip: location: {{ INTERNAL_URL }}/resources/v2/xxx.zip When launching che server with defualt devfile registry this variable is correctly resolved. But with the locally built registry the variable is not resolved. From the code of devfile registry I understand the INTERNAL_URL should get resolved with the value of env variable CHE_DEVFILE_REGISTRY_INTERNAL_URL but when I checked the config map of the locally built devfile registry. This CHE_DEVFILE_REGISTRY_INTERNAL_URL var is not defined. But it is defined when working with default devfile registry. I manully added the required key value ("CHE_DEVFILE_REGISTRY_INTERNAL_URL": "http://che-devfile-registry.eclipse-che.svc:8080/") to configmap and updated the projects:
name: xxxx zip: location: http://che-devfile-registry.eclipse-che.svc:8080/resources/v2/xxx.zip t, i got to see the project src in vscode in the explorer. But I want to undersatand what is the correct way to build the devfile registry so the INTERNAL_URL is resolved automatically.

**Comment by aaswan** [comment]
I was following the wrong way to setup the custom devfile registry.
Just a patch is needed to checluster post building the image
./patch-checluster.sh quay.io/eclipse/che-devfile-registry:prism

**Comment by tolusha** [comment]
@aaswan 
The correct way:
1. Build Devfile Registry.
2. Patch CheCluster CR
```bash
c patch checluster/eclipse-che --patch '{"spec": {"components": {"devfileRegistry": {"deployment": {"containers": [{"image": "<IMAGE>"}]}}}}}' --type=merge -n eclipse-che
```

**Comment by aaswan** [comment]
Thanks. That works
