### ISSUE TITLE
chectl server:*  Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Mbd06b** [eclipse/che#22172]
### Describe the bug

I've installed and updated eclipse chectl over the past few years, on Ubuntu and I've never run in to this problem yet.  But I'm stuck. 

When I run any chectl that tries to interact with the chectl server, I am getting a failure that I think is due to some environment issue within how node is being used by chectl. 

`$chectl server:deploy`
  Error: unable to verify the first certificate
 Code: UNABLE_TO_VERIFY_LEAF_SIGNATURE

I tried `export NODE_TLS_REJECT_UNAUTHORIZED=0`
based on this reccomendation... https://github.com/eclipse/che/issues/17956 

`(node:2727463) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
    HttpError: HTTP request failed
`

I've tried  'sudo chectl server:deploy' 
    Error: connect ECONNREFUSED 127.0.0.1:8080
    Code: ECONNREFUSED

and version. 
![image](https://user-images.githubusercontent.com/12649222/233535699-b1fb9df3-d71e-4fc8-94bb-18027c3a934e.png)

I'm using microk8s, but I have kubectl aliased to microk8s.kubectl. 
I have nvm installed on the host machine. 

### Che version

7.64@latest

### Steps to reproduce

1. chectl:update  OR   
2. $ bash <(curl -sL  https://www.eclipse.org/che/chectl/)

(I'm not sure about how to go about diagnosing the problem)

### Expected behavior

The chectl interacts with the server. 

(sorry I don't know how to diagnose the root cause here) 

### Runtime

other (please specify in additional context)

### Screenshots

(see above and below)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

Here's my install log: 
![image](https://user-images.githubusercontent.com/12649222/233536521-abca8492-26ef-4070-bd7d-baabcfe18c0b.png)

**Comment by tolusha** [comment]
@Mbd06b 
Could you check:
1. There is `certificate-authority` field in `~/.kube/config` for your cluster
2. The certificate file contains the complete certificate chain of trust.

```
- cluster:
    certificate-authority: <PATH_TO_CERTS_FILE>
    server: <redacted>
  name: my-cluster
```

**Comment by Mbd06b** [comment]
> @Mbd06b Could you check:
> 
> 1. There is `certificate-authority` field in `~/.kube/config` for your cluster
> 2. The certificate file contains the complete certificate chain of trust.
> 
> ```
> - cluster:
>     certificate-authority: <PATH_TO_CERTS_FILE>
>     server: <redacted>
>   name: my-cluster
> ```

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJT......big long string ..... RS0tLS0tCg==
    server: https://192.168.2.2:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: WTIy.... long token string .... UVT0K

**Comment by Mbd06b** [comment]
Still working on it, to add some detail, it looks like I've got chectl files in multiple locations. 
`$sudo find / -name "*chectl*"`
/root/.cache/chectl
/root/.local/share/chectl
/root/.local/share/chectl/client/bin/chectl
/root/.local/share/chectl/client/7.64.0/bin/chectl.cmd
/root/.local/share/chectl/client/7.64.0/bin/chectl
/root/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.js.map
/root/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.js
/root/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.d.ts
find: ‘/run/user/1000/gvfs’: Permission denied
find: ‘/run/user/121/gvfs’: Permission denied
/home/matthew/.config/chectl
/home/matthew/ethosengine-devops/Kube-manifests/che-manifests/chectl-install.log
/home/matthew/ethosengine-devops/Kube-manifests/ns-host-services/chectl-install.log
/home/matthew/ethosengine-devops/chectl-notes
/home/matthew/ethosengine-devops/chectl-notes/chectl-install.log
/home/matthew/ethosengine-devops/chectl-notes/mychectl.md
/home/matthew/ethosengine-devops/chectl-notes/chectl-linux-x64.tar.gz
/home/matthew/.cache/chectl
/home/matthew/.local/share/chectl
/home/matthew/.local/share/chectl/client/bin/chectl
/home/matthew/.local/share/chectl/client/7.64.0/bin/chectl.cmd
/home/matthew/.local/share/chectl/client/7.64.0/bin/chectl
/home/matthew/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.js.map
/home/matthew/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.js
/home/matthew/.local/share/chectl/client/7.64.0/lib/utils/chectl-version.d.ts
/home/matthew/.local/share/chectl/client/7.59.0/bin/chectl.cmd
/home/matthew/.local/share/chectl/client/7.59.0/bin/chectl
/home/matthew/.local/share/chectl/client/7.59.0/lib/utils/chectl-version.js.map
/home/matthew/.local/share/chectl/client/7.59.0/lib/utils/chectl-version.js
/home/matthew/.local/share/chectl/client/7.59.0/lib/utils/chectl-version.d.ts
/home/matthew/.local/share/chectl/client/7.63.0/bin/chectl.cmd
/home/matthew/.local/share/chectl/client/7.63.0/bin/chectl
/home/matthew/.local/share/chectl/client/7.63.0/lib/utils/chectl-version.js.map
/home/matthew/.local/share/chectl/client/7.63.0/lib/utils/chectl-version.js
/home/matthew/.local/share/chectl/client/7.63.0/lib/utils/chectl-version.d.ts

These files don't seem to agree with the install-log screenshot I took in my original post. 

Suggestions for cleanup?

**Comment by Mbd06b** [comment]
I'm still troubleshooting this. 
I suspect that there's something in the way that node-v16.13.2 is trying to connect that's failing, but I'm still stuck as to how to fix it. 


`$ chectl server:status
`    Error: unable to verify the first certificate
    Code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
`$ chectl version
`chectl/7.71.0 linux-x64 node-v16.13.2


ChatGPT4 has given up on our troubleshooting session, I'm going to try installing w/source to see if I can debug from there from remote server: 
 "I see, thank you for clarifying that. It seems you've been quite thorough in your attempts to resolve this issue. As it stands, it appears to be a complex problem that might be related to how chectl or Node.js handles SSL/TLS connections, or it might be related to the specific configuration of your system or Kubernetes cluster.

Given the complexity of the issue and the fact that it's still open on GitHub, I would recommend continuing the conversation there. The contributors to the chectl project are likely to have the most knowledge about how it interacts with SSL/TLS and certificates, and they might be able to provide more specific advice or solutions.

In the meantime, you might want to consider trying a few more things:

Try running chectl with the --help flag to see if there are any options related to SSL/TLS or certificates that you haven't tried yet.
If you have access to another system or a virtual machine, you could try installing and running chectl there to see if you encounter the same issue. This could help determine if the issue is specific to your current system or if it's a more general issue with chectl.
If you're comfortable with Node.js, you could try downloading the chectl source code and running it in a debugger to see if you can get more information about where and why the error is occurring.
I'm sorry I can't provide a more specific solution. This seems to be a complex issue that might require a deep understanding of chectl, Node.js, SSL/TLS, and possibly Kubernetes and MicroK8s."

**Comment by tolusha** [comment]
@Mbd06b 
In general the workaround below should help.
`export NODE_TLS_REJECT_UNAUTHORIZED=0`

Could you provide the exact command the output of `chectl server:deploy` ?

**Comment by tolusha** [comment]
To be honest I don't know what is wrong.
I have:

```bash
$ microk8s config
 microk8s config             
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVY3I2WUJSYWZ2SmU4Ni9XSS9TRFZncC82TGF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGN5TmpFeU5UQXdOMW9YRFRNegpNRGN5TXpFeU5UQXdOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2N3ZMWDhmRHdSend1eEVyOVYvS1FjVTVDTFlDd1JGNXNXdXIKbkRnMmtiV1d4SXNaQXM5aTNXSUxacWpCYlptbkgrY09JalFpbEQvQVdDQ2FydFZBSlpibWExNkVXNlRsc3F4cQoyejVVa09ORE1MbWlpK0FsekNPVmQ0VkJYWTJFUjVFRHRpUGNRMGRuS1NvZVVIMXNZVEdCV21lMGR3QU1VdDFLCnFibFI1cUdJalBRVmtONDN2NHlJQmxtUmhNUk1iV1diaTRKNm5Gbm1QdlZWa0JONkJkdWhDdTdVM1ZPSzgwMk0KNjA1UFp4ZWlIU2tLUGdCNnprK2NEaEtNTFhvckRsUEdBVlFqNDFDaHdZeGx2ZnovM29QaDB0czRFa2hxbUVSYwpSdjhEMjNiS3hnOXJlVWxvOHpWcHFhbVlTWHNHMHJEdC9XOFV6R2ZlekgrcVViTmRTUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVXBhNVpSOGI0SVRackoxNC9MY2d5RXFQWUlpd3dId1lEVlIwakJCZ3dGb0FVcGE1WlI4YjQKSVRackoxNC9MY2d5RXFQWUlpd3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBbk9TbGY1emtwZFhJYlIydFZncXR5UTMzR3pxZWFicm5PVnltQllid2JydUZDMEVsK0FDdVA2WUZDY2dhCm9wQ0RVTUxmb3h5WjRlOE9oT1IvS3N4b0ZxNzg0N1ZlYVpDKzV2a1FGRWNsMWNRM1EyczQwc0xaNnBjbGdRamkKb1FyN3htNis4MFFsNEVMWW00Sm92cXlLcGk1SjB3ZjhQS1FqTkFjWDRxK1lEVm1YazQ3dVhyd1E3ZTNhemdwZQp0Q2U3S2xWRzdsaCthQlBkaDBUUXV1Qnp4anFQYkRIR01ZVGZzWG9HS3l4N0ZrN1Bwai84ZG1wYkhsemc4TWpCCnY2eXdxY3dvVVZwUWUxVnVmUFBxM21ycmhMNytheWJUL1RMWTB0VkxMcDJiSURiRXZSeGk2R3BHTk1HVWRTeUYKYWxmeFVudFpIaGtpRzNxWUs5Z1BNMUNqdEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.55.2:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: a3ZORG5JMHdIQmd4T0RCY0VUS1RZaW9NdlpYejlWRWdtYWxYRjBsbXNnbz0K
    
$ microk8s config > ~/.kube/config    
$ chectl server:deploy -p  microk8s
    Error: Some required configuration is not specifed in order to deploy Eclipse Che
    on a Kubernetes cluster with an OIDC provider configured. Use the flag '--che-operator-cr-patch-yaml <PATH_TO_PATCH_FILE>' to
    provide a CheCluster Custom Resource patch with the needed configuration. Find an example of such a configuration below:
```

Basically I need to set up dex before continue deploying Eclipse Che.
But I didn't bump into a problem that your described.

**Comment by Mbd06b** [comment]
I've shutdown my server. I'm about to go nuclear on the problem with a fresh OS image.   

![download](https://github.com/eclipse/che/assets/12649222/5a273d0c-7438-4a60-a0c5-f54619348eda)
Last chance before I push the button.

**Comment by Mbd06b** [comment]
It's gone.  So I'm able to use chectl again. 
I've attempted install but my che-operator get's stuck in pending, there are no events or logs on the pod. 

I'm going to close this issue as a configuration issue on my end somewhere that conflicted with the node embededded in chect.

```
$ kubectl get all -n eclipse-che
NAME                                READY   STATUS    RESTARTS   AGE
pod/che-operator-5668b588c5-vlv7z   0/1     Pending   0          6m55s

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/che-operator-service   ClusterIP   10.152.183.56   <none>        443/TCP   6m55s

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/che-operator   0/1     0            0           6m55s

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/che-operator-5668b588c5   1         0         0       6m55s
```
