### ISSUE TITLE
How to provide my custom runtime in my local instance of che-server deployed on minikube

### ISSUE THREAD

**Issue by aaswan** [eclipse/che#22177]
### Summary

I am able to add a new Workspace to eclipse dashboard and also able to list my vscode extension in the extensions tab by adding my extensions meta to the plugin registry. But my vscode extension depends on a command line utility which I want to include in the runtime of the workspace. How can I do that?
Added detailed steps on how I achieved the above results till now

### Relevant information

1. Start minikube: 
> minikube start --driver=virtualbox --addons=ingress,dashboard --vm=true --memory=10240 --cpus=4 --disk-size=50GB --kubernetes-version=v1.26.1 --embed-certs
2. Deploy che server
> server:chectl server:deploy --platform minikube --k8spoddownloadimagetimeout=18000000 --k8spodreadytimeout=18000000
3. Modify che-devfile-registry to add meta for my workspace definition with v2 link
> links:
>   v2: https://github.com/aaswan/base-ui/tree/main

> eval $(minikube -p minikube docker-env)
> ./build.sh -t prism
> ./patch-checluster.sh quay.io/eclipse/che-devfile-registry:prism
5. Modify che-plugin-registry to add meta for my vscode extension in openvsx-sync.json and changing the spec.components.pluginRegistry.openVSXURL: '' in CheCluster resource
> eval $(minikube -p minikube docker-env)
> ./build.sh -t prism 
> ./patch-checluster.sh quay.io/eclipse/che-plugin-registry:prism
6. Retstart che server
> chectl server:stop
> chectl server:start --k8spodreadytimeout=18000000 --k8spoddownloadimagetimeout=18000000 --k8spoderrorrechecktimeout=18000000 --k8spodwaittimeout=18000000

Everything works as expected till here.

7. Modify the components.container.image to a new docker image(having the required command line tools) in devfile.yaml in v2:link

Error: It tries to download the new docker image and fails to find it when preparing workspace, although that docker image is present in the minikube already

**Comment by AObuchow** [comment]
@aaswan Thank you for the detailed information regarding your issue :) 

> Modify the components.container.image to a new docker image(having the required command line tools) in devfile.yaml in v2:link

To get a better understanding of what may be going wrong (and to hopefully try and reproduce it) could you provide more info regarding this step? What does the devfile YAML look like, with your docker image being used in it (is it [this](https://github.com/aaswan/base-ui/blob/main/devfile.yaml) but with a different container image)? And would you be able to host that docker image publicly for reproducibility on something like [quay.io](https://quay.io/)?

I would suggest first trying to get your devfile with your custom image working on a vanilla/plain Che install (i.e. without modifying the Che-devfile-registry) to try and see if that works in isolation.

**Comment by aaswan** [comment]
Yes. https://github.com/aaswan/base-ui/blob/main/devfile.yaml
This is the devfile with a different docker image. [updated now]
I wouldn't be able to host it publicly for now, without the required approvals, which might take considerable time.
Is this the right way to provide build tools for my workspace and runtime dependencies for my vscode extension. 

Exact error:
Failed to pull image "samsung.io/tizen-studio/cli:prism": rpc error: code = Unknown desc = Error response from daemon: Get "https://samsung.io/v2/": dial tcp: lookup samsung.io on 10.0.2.3:53: no such host

**Comment by aaswan** [comment]
I further changed the image to
quay.io.io/tizen-studio/cli:prism

and again got the similar error
Failed to pull image "quay.io.io/tizen-studio/cli:prism": rpc error: code = Unknown desc = Error response from daemon: Get "https://quay.io.io/v2/": dial tcp: lookup quay.io.io on 10.0.2.3:53: read udp 10.0.2.15:53929->10.0.2.3:53: i/o timeout

**Comment by tolusha** [comment]
@aaswan 
The solution is to change `ImagePullPolicy` for DevWorkspace operator

```
kubectl patch devworkspaceoperatorconfigs -n eclipse-che devworkspace-config --patch '{"config": {"workspace": {"imagePullPolicy": "IfNotPresent"}}}' --type merge
```
