### ISSUE TITLE
RecommendedExtensions E2E test is looking at the wrong extension

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22176]
### Is your task related to a problem? Please describe

RecommendedExtensions E2E test is looking at the wrong extension when filter on "java" for "redhat.java" extensions name

**Actual**: "JavaScript Debugger"
**Expected**: "Language Support for Java(TM) by Red Hat"
![233784307-9943a717-c7d4-4b44-88ba-224de43c2809](https://user-images.githubusercontent.com/1197777/233936554-06730a85-0483-4cda-a636-2f1aa0b81cdd.png)

And the same problem is with Go and Python extensions:
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/7594/console
![screenshot-Check_if_extensions_is_installed_and_enabled (2)](https://user-images.githubusercontent.com/1197777/233936620-af0a653d-4b1b-4e75-b077-18300ae79722.png)

https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/7607/console
![screenshot-Check_if_extensions_is_installed_and_enabled (1)](https://user-images.githubusercontent.com/1197777/233936666-6fc55fce-a014-492c-bfec-8a924eb987af.png)

### Describe the solution you'd like
https://github.com/eclipse/che/issues/22176#issuecomment-1519630440

**Comment by nallikaea** [comment]
![image](https://user-images.githubusercontent.com/72726250/233940596-2f5740fe-e114-4ce6-bfe8-3758933e287f.png)

It is not possible to get extension by it`s name and publisher from search. 

**_The possible solution:_**
- Create object from extension.json as:
```
...
{
    publisher: 'redhat',
    name: 'java'
},
{
    publisher: 'redhat',
    name: 'fabric8-analytics'
}...
```
- search in Marketplace by name and collect all results as items list
- filter items list by publisher using method `const author = await item.getAuthor();` 
- check `await item.isInstalled() === true`
[source](https://github.com/redhat-developer/vscode-extension-tester/wiki/ExtensionsViewSection)

**Comment by nallikaea** [comment]
```
function getExtensionPublisherAndName(recomendedExtension: string) {
    const [publisher, name] = string.split(".");
    return { publisher, name };
}
```

**Comment by dmytro-ndp** [comment]
@nallikaea : thank you for investigation!

Feel free to describe solution in description of issue in section `Describe the solution you'd like`.

**Comment by nallikaea** [comment]
> @nallikaea : thank you for investigation!
> 
> Feel free to describe solution in description of issue in section `Describe the solution you'd like`.

I can`t edit it

**Comment by nallikaea** [comment]
https://github.com/eclipse/che/pull/22201 Merged

**Comment by nallikaea** [comment]
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/8202/

Looks like a bug of monaco-page-object lib, because error returned from here:
```
    /**
     * Open the management context menu if the extension is installed
     * @returns Promise resolving to ContextMenu object
     */
    manage() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.getDriver().wait(selenium_webdriver_1.until.elementLocated(ExtensionsViewItem.locators.ExtensionsViewItem.manage), 1000);
            const button = yield this.enclosingItem.findElement(ExtensionsViewItem.locators.ExtensionsViewItem.manage);
            if ((yield button.getAttribute('class')).indexOf('disabled') > -1) {
                throw new Error(`Extension '${yield this.getTitle()}' is not installed`);
            }
            return this.openContextMenu();
        });
    }
```
Our log:
```
 ▼ Try to find extension published by golang.
17:27:38            ▼ Extension was found: Go
17:27:38            ▼ itemWithRightNameAndPublisher?.isInstalled()
17:27:39            ▼ itemWithRightNameAndPublisher?.isInstalled(): true.
17:27:39            ▼ itemWithRightNameAndPublisher.manage(): get context menu.
17:27:39      1) Check if extensions is installed and enabled
17:27:39    [ERROR] CheReporter runner.on.fail: Check if recommended extensions installed for Go Check if extensions is installed and enabled failed after 3766ms
17:27:39              ‣ FullTitle:Check if recommended extensions installed for Go Check if extensions is installed and enabled
17:27:39              ‣ FullTitleSanitized:Check_if_recommended_extensions_installed_for_Go_Check_if_extensions_is_installed_and_enabled
17:27:39              ‣ TestTitle:Check if extensions is installed and enabled
17:27:39              ‣ TestTitleSanitized:Check_if_extensions_is_installed_and_enabled
17:27:39              ‣ DriverHelper.getDriver
17:27:39  
17:27:39        • Property DELETE_WORKSPACE_ON_FAILED_TEST is true - trying to stop and delete running workspace with API.
17:27:39            ▼ TestWorkspaceUtil.stopAndDeleteWorkspaceByName
17:27:39            ▼ TestWorkspaceUtil.stopWorkspaceByName
17:27:39            ▼ ApiUrlResolver.obtainUserNamespace 
17:27:39              ‣ ApiUrlResolver.obtainUserNamespace USER_NAMESPACE.length = 0, calling kubernetes API
17:27:39              ‣ DriverHelper.getDriver
17:27:39              ‣ DriverHelper.getDriver
17:27:39              ‣ DriverHelper.getDriver
17:27:39        • Chrome driver session stopped.
17:27:39  
17:27:39    9 passing (2m)
17:27:39    1 failing
17:27:39  
17:27:39    1) Check if recommended extensions installed for Go
17:27:39         Check if extensions is installed and enabled:
17:27:39       Error: Extension 'Go' is not installed
17:27:39        at ExtensionsViewItem.<anonymous> (/tmp/e2e/node_modules/monaco-page-objects/out/components/sidebar/extensions/ExtensionsViewItem.js:88:23)
17:27:39        at Generator.next (<anonymous>)
17:27:39        at fulfilled (/tmp/e2e/node_modules/monaco-page-objects/out/components/sidebar/extensions/ExtensionsViewItem.js:5:58)
17:27:39        at runMicrotasks (<anonymous>)
17:27:39        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by nallikaea** [comment]
Should be investigated

**Comment by nallikaea** [comment]
Closed, because the solution works as expected, new issue opened in https://github.com/redhat-developer/vscode-extension-tester/issues/767 project
