### ISSUE TITLE
CheCluster no longer allows specifying the ingress class

### ISSUE THREAD

**Issue by AussieScorpio** [eclipse/che#22175]
### Describe the bug

The CheCluster resource supports adding annotations to the created ingress resource. Historically, this allowed one to add the annotation; kubernetes.io/ingress.class: nginx which would allow the ingress controller to generate the appropriate Nginx config.

The annotation kubernetes.io/ingress.class is now deprecated and the nginx-ingress controller does not recognise it. In order to assign the ingress class, ingressClassName: nginx must be added under spec.

Using the annotation ingressclass.kubernetes.io/is-default-class: "true" on the IngressClass is also not an options as the controller will still not assign the class to an Ingress without the ingressClassName explicitly stated.

Whilst the CheCluster resource does support adding the legacy annotation, it doesn't support adding the ingressClassName. (as per https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-networking-settings).

All this presents issues; not the least of which is that without the ingress class, it's not possible for cert-manager to deal with challenges for new certificates. The ingress created for the challenge (or the Che ingress if annotated with acme.cert-manager.io/http01-edit-in-place: "true") is missing the ingress class, so the ingress controller never updates the Nginx config to support routing the challenge.

### Che version

7.65@latest

### Steps to reproduce

The problem is evident from the documentation on available CheCluster fields; https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-networking-settings
And the fact that the the annotation for IngressClass is no longer supported;
https://kubernetes.io/docs/concepts/services-networking/ingress/

### Expected behavior

If Che is determined to control how the Ingress is created, then it must support adding the extra fields required for the Ingress to function as the user requires.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by tolusha** [comment]
cc @AussieScorpio 
https://github.com/eclipse-che/che-operator/pull/1669
