### ISSUE TITLE
Update Woopra / Segment VS Code extension to use Amplitude

### ISSUE THREAD

**Issue by mbenitez1607** [eclipse/che#22185]
### Is your enhancement related to a problem? Please describe

#17543 created a Woopra / Segment extension. Now that Woopra is being deprecated, we need to update the extension to work with Amplitude

### Describe the solution you'd like

Ideally the existing extension only needs a few changes to start working with Amplitude.

**Comment by dkwon17** [comment]
Fixed by https://github.com/che-incubator/devworkspace-telemetry-amplitude-plugin/pull/1
