### ISSUE TITLE
Revise Github Projects managed by Che teams

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse/che#22188]
### Is your task related to a problem? Please describe

Some of our projects, especially on Che Incubator side, have inconsistent and/or outdated configurations, like permissions to push branches or merge PRs. Ideally, all projects should have the same configuration, when it comes to those things. Codeowners, who would approve these PRs. Updating all these things would help in future, when someone would have to push to those projects

### Describe the solution you'd like

- [x] ensure that list https://github.com/eclipse/che/blob/main/.repositories.yaml is up to date.
- [x] all eclipse-che/che-incubator repos must have the same configuration:
 - main branch protected from direct pushes, 
 - all che org members must have permissions to push branches to the upstream repo, 
 - all che org members should be able to merge PRs with at least 1 approved review, 
 - merge commits not allowed, to keep the git history linear.
- [x] every eclipse-che/che-incubator repo should have updated CODEOWNERS file(exact list with repos/owners is TBD).

**Comment by mkuznyetsov** [comment]
as part of this issue, most of che-samples projects should be archived, except those that are currently maintained:

```
che-samples/apache-camel-k
che-samples/bash
che-samples/cpp-hello-world
che-samples/django-realworld-example-app
che-samples/dotnet-web-simple
che-samples/fuse-rest-http-booster
che-samples/golang-example
che-samples/helloworld-rust
che-samples/java-guestbook
che-samples/java-spring-petclinic
che-samples/lombok-project-sample
che-samples/nodejs-angular
che-samples/nodejs-mongodb-sample
che-samples/nodejs-react-redux
che-samples/php-symfony
che-samples/python-hello-world
che-samples/quarkus-quickstarts
che-samples/react-web-app
che-samples/scala-sbt
che-samples/web-nodejs-sample
```

**Comment by mkuznyetsov** [comment]
@l0rd do we want to have CODEOWNERS files in che-samples? if sample is cloned "as-is" to users workspace, will it make sense for him to have .github/CODEOWNERS file in his project, or is this not important?

**Comment by mkuznyetsov** [comment]
updating repositories yaml - https://github.com/eclipse/che/pull/22248

**Comment by mkuznyetsov** [comment]
all che-incubator repos have now following settings:
-added che-incubator team members with write permissions
-add protected rule for main branch, with require of at least 1 codereviewer (where codereviewer PR has been merged)
-only linear history is allowed on main branch

@l0rd should main branch also require only signed commits? Seems like some of the projects were already doing that, while some won't

**Comment by l0rd** [comment]
> @l0rd should main branch also require only signed commits? Seems like some of the projects were already doing that, while some won't

This would be useful yes.

**Comment by l0rd** [comment]
> @l0rd this list shoudln't feature product-related prjects like devspaces, correct?

Ok with that

**Comment by l0rd** [comment]
> as part of this issue, most of che-samples projects should be archived, except those that are currently maintained

Yes, absolutely.

**Comment by l0rd** [comment]
> @l0rd do we want to have CODEOWNERS files in che-samples? if sample is cloned "as-is" to users workspace, will it make sense for him to have .github/CODEOWNERS file in his project, or is this not important?

We should have `CODEOWNERS` files. We can avoid including them [in the zip file of the devfile registry](https://github.com/eclipse-che/che-devfile-registry/blob/db78c85cb8636d62c78f7b9bfecdf8cfe40b3515/build/scripts/clone_and_zip.sh#L43) using a [.gitattributes file with `export-ignore`](https://stackoverflow.com/questions/25261510/how-to-export-git-file-with-ignore-folder#25261739).
