### ISSUE TITLE
Unable to use base Ubuntu image in my workspace

### ISSUE THREAD

**Issue by aaswan** [eclipse/che#22183]
### Summary

I have setup my local che server instance on minikube. I have added a new wokspace by modifying the devfile registry and added my vscode plugin by modifying the plugin registry. I was also able to install the plugin in my workspace.
Problem: Now I want to provide my custom image having some command line tools which are used by the vscode plugin that I included in plugin registry.

**What is the best way to do it?**

Documented my attempt in the details

### Relevant information

I modified the devfile.yaml of my workspace https://github.com/aaswan/base-ui/blob/main/devfile.yaml
Instead of the default quay.io/devfile/universal-developer-image:ubi8-latest image I modified it to use my custom image. I tried with 2 images. 1 of them does not work.

**Dockerfile 1 [that works]**
```
FROM registry.access.redhat.com/ubi8/ubi:8.7-1112
USER 0
COPY --chown=0:0 entrypoint.sh /
RUN \
    # add user and configure it
    useradd -u 10001 -G root -d /home/user --shell /bin/bash -m user && \
    # Set permissions on /etc/passwd and /home to allow arbitrary users to write
    chgrp -R 0 /home && \
    chmod -R g=u /etc/passwd /etc/group /home && \
    chmod +x /entrypoint.sh
USER 10001
ENV HOME=/home/user
WORKDIR /projects
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["tail", "-f", "/dev/null"]
```

**Dockerfile 1 [that does not work]**
```
#FROM registry.access.redhat.com/ubi8/ubi:8.7-1112
FROM ubuntu:20.04
USER 0
COPY --chown=0:0 entrypoint.sh /
RUN \
    # add user and configure it
    useradd -u 10001 -G root -d /home/user --shell /bin/bash -m user && \
    # Set permissions on /etc/passwd and /home to allow arbitrary users to write
    chgrp -R 0 /home && \
    chmod -R g=u /etc/passwd /etc/group /home && \
    chmod +x /entrypoint.sh
USER 10001
ENV HOME=/home/user
WORKDIR /projects
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["tail", "-f", "/dev/null"]
```

The entrypoint.sh is the same for both scenarios.

```
#!/bin/bash
if [ ! -d "${HOME}" ]; then
  mkdir -p "${HOME}"
fi
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-user}:x:$(id -u):0:${USER_NAME:-user} user:${HOME}:/bin/bash" >> /etc/passwd
    echo "${USER_NAME:-user}:x:$(id -u):" >> /etc/group
  fi
fi
exec "$@"
```

The only difference in the 2 Dockerfile is the FROM [ base image ]
When I use the Ubuntu base image, the workspce window keeps refreshing.

**Comment by aaswan** [comment]
In the Chrome console I can see the following errors
client.ba5604a9091231f54969.js:1 Failed to fetch list of available kubernetes namespaces, reason: network issues occured while requesting "/kubernetes/namespace".
fetchInfrastructureNamespaces @ client.ba5604a9091231f54969.js:1
/api/kubernetes/namespace:1          Failed to load resource: net::ERR_FAILED
client.ba5604a9091231f54969.js:1 WebSocket client '/dashboard/api/websocket' received 'open' event

But when I open https://192.168.59.148.nip.io/api/kubernetes/namespace
I can see the namespace
[{"name":"user1-che","attributes":{"phase":"Active"}}]

**Comment by RomanNikitenko** [comment]
I think you faced an error related to Node.js.
Could you try this workaround: https://github.com/che-incubator/che-code/tree/main/build/dockerfiles#readme

so: 
- install Node.js >=16.17.x and <17
- provide `VSCODE_NODEJS_RUNTIME_DIR` env variable with the path to the installed node

**Comment by aaswan** [comment]
Is there any standard Ubuntu based base image for eclipse che, with all the required tools in it. Similar to https://github.com/devfile/developer-images/blob/main/base/ubi8/Dockerfile

**Comment by RomanNikitenko** [comment]
I have not seen such image

**Comment by monaka** [comment]
@aaswan How about images provided by PizzaFactory/Contorno ?
Piatto is base images for Che7 https://github.com/pizzafactory-contorno/piatto
