### ISSUE TITLE
Set empty CPU limits when possible

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22198]
### Is your enhancement related to a problem? Please describe

If a container reach a CPU limit it gets throttled (paused for a few ms). A container that get throttled performs poorly and can have [side effects that are hard to associate with throttling](https://github.com/eclipse/che/issues/22163). 

In other words when setting CPU limits the application may behave in a weird way and users can lose hours figuring out why.

[LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/) are used in Kubernetes clusters to set default request/limit for compute resources in a namespace and automatically inject them to Containers at runtime. If a default CPU limit is set in the Che namespace or in the workspaces namespaces, then we have to specify the CPU limits to avoid that an arbitrary limit gets set. But otherwise we don't have to.

### Describe the solution you'd like

If **there is no LimitRange** or there is one but it **doesn't specify the default CPU Limit** in one of the following namespaces:
- [ ] developer namespace: then the project-clone container, the default component container (UDI) should not specify a CPU limit (if the CPU limits are specified in a Devfile we should honor them) https://github.com/devfile/devworkspace-operator/issues/1126
- [x] developer namespace: then the gateway container should not specify a CPU limit
- [x] CheCluster namespace: server components should not specify a CPU limit

**Comment by tolusha** [comment]
I mark this issue as resolved.
Here is a dedicated issue for DWO https://github.com/devfile/devworkspace-operator/issues/1126
