### ISSUE TITLE
[Bitbucket Server OAuth2.0] Wrong Git Credentials (Authentication Failed)

### ISSUE THREAD

**Issue by Deddinho23** [eclipse/che#22199]
### Describe the bug

We are using the integration with Bitbucket Server (OAuth2.0) and now we just updated Eclipse-Che from 7.63 to 7.65:
In 7.63, Che successfully take the username of the user and make a secret (devworkspace-merged-git-credentials) with the correct credentials. `https://[username]:<<PAT>>`

Now in 7.65, it still create the secret, but instead of the username it use the ID of the users, and that consists in a failure when the workspace trying to clone our repos with these credentials. `https://[user-id]:<<PAT>>`
Neither using a manual clone from the IDE is working...

### Che version

7.65@latest

### Steps to reproduce

1. In the Dashboard, trying to create a Workspace from a Bitbucket Repo;
2. Authentication Failed in project-clone logs.

### Expected behavior

1. In the Dashboard, trying to create a Workspace from a Bitbucket Repo;
2. Successful clone and creation of the Workspace

### Runtime

Kubernetes (vanilla)

### Screenshots

Before (7.63): 
![image](https://user-images.githubusercontent.com/48152430/236476043-8f23807f-41dc-4e00-9b6f-7e7e4440437d.png)
After (7.65):
![image](https://user-images.githubusercontent.com/48152430/236476397-427ca277-dbfe-4320-9981-be2fb5a81bc6.png)

### Installation method

chectl/latest

### Environment

Amazon

### Additional context

AutoProvisioning = True

**Comment by l0rd** [comment]
Thank you @Deddinho23 for reporting this.

@vinokurig @ibuziuk can you please have a look.

**Comment by vinokurig** [comment]
is fixed by https://github.com/eclipse-che/che-server/pull/512
