### ISSUE TITLE
Deprecation warnings when building operator-bundle images downstream: can we switch to non-deprecated CheCluster, DevWorkspace, and DevWorkspaceTemplate?

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22205]
### Is your task related to a problem? Please describe

CVP tests in downstream builds are yellow due to warnings.

These warnings are deprecation notes for Che content:

```
openshift-operators   74s         Warning   AppliedWithWarnings   installplan/install-nxrkx   1 warning(s) generated during installation of operator "devspacesoperator.v3.7.0" (CustomResourceDefinition "checlusters.org.eclipse.che"): org.eclipse.che/v1 CheCluster is deprecated and will be removed in future releases
openshift-operators   78s         Warning   AppliedWithWarnings   installplan/install-nxrkx   1 warning(s) generated during installation of operator "devworkspace-operator.v0.20.0" (CustomResourceDefinition "devworkspaces.workspace.devfile.io"): workspace.devfile.io/v1alpha1 DevWorkspace is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspace
openshift-operators   77s         Warning   AppliedWithWarnings   installplan/install-nxrkx   1 warning(s) generated during installation of operator "devworkspace-operator.v0.20.0" (CustomResourceDefinition "devworkspacetemplates.workspace.devfile.io"): workspace.devfile.io/v1alpha1 DevWorkspaceTemplate is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspaceTemplate
```

### Describe the solution you'd like

Assuming this is a problem in upstream AND downstream, I'm opening a Che issue for this so we can use our own updated content and not throw needless warnings. 

### Additional context

Recent log: http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/devspaces-operator-bundle-container-3.7-165/5fa0c074-add5-4987-a847-5c744ed92942/operator-olm-deployment-bundle-image-output.txt (might need VPN access)

Here's a snap of what the CVP email looks like:

![image](https://github.com/eclipse/che/assets/227597/6caa27de-350f-4bd1-9c88-f53dd86068bc)

**Comment by tolusha** [comment]
@nickboldt 
What are those tests about?
Those warning can be printed if deprecated API is used.
