### ISSUE TITLE
PR time check for dashboard required for starting workspace till DWO kicks (oc apply phase)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22206]
### Is your task related to a problem? Please describe

We need to check the timing for every dashboard PR starting form the workspace startup till the `oc apply` state when the DWO kicks in

### Describe the solution you'd like

Separate PR check for timing workspace startup phase till the DWO kicks in

### Describe alternatives you've considered

N/A

**Comment by dmytro-ndp** [comment]
There is a task to run Smoke UI test, which could be used to measure specific stage time execution.
