### ISSUE TITLE
Doesn't create the Workspace if using a devfile with the same name of an existing one

### ISSUE THREAD

**Issue by Deddinho23** [eclipse/che#22210]
### Describe the bug

Just upgraded in 7.66 from 7.65, I noticed that now if i want to create a workspace from a devfile that have the same name (or its the same) of an existing one, the creation will fail:
![image](https://github.com/eclipse/che/assets/48152430/18312c51-c113-4801-9d30-e0bac0bf9916)
While before, the creation was successful with the name and a post-fix in the end (e.g. workspace and workspace-1e5c1)

### Che version

7.66@latest

### Steps to reproduce

1. Creation of a workspace from a devfile that was used for another existing workspace 
2. When it notice they have the same name choose to create it anyway
3. Error

### Expected behavior

1. Creation of a workspace from a devfile that was used for another existing workspace 
2. When it notice they have the same name choose to create it anyway
3. Creation completed with a post-fix in the name

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Amazon

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy looks like regression
