### ISSUE TITLE
Remove CSV and CRD references to now-obsolete postgres variables

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22214]
### Is your task related to a problem? Please describe

There are still many references to postgres in the CSV and CRD; as postgres is no longer used, these should be removed.

```
./bundle/next/eclipse-che/manifests/che-operator.clusterserviceversion.yaml 
./bundle/next/eclipse-che/manifests/org.eclipse.che_checlusters.yaml 
./bundle/stable/eclipse-che/manifests/che-operator.clusterserviceversion.yaml 
./bundle/stable/eclipse-che/manifests/org.eclipse.che_checlusters.yaml ./config/crd/bases/org.eclipse.che_checlusters.yaml 
./config/manifests/bases/che-operator.clusterserviceversion.yaml 
./deploy/deployment/kubernetes/combined.yaml ./deploy/deployment/kubernetes/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml 
./deploy/deployment/openshift/combined.yaml 
./deploy/deployment/openshift/objects/checlusters.org.eclipse.che.CustomResourceDefinition.yaml 
./helmcharts/next/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml 
./helmcharts/stable/crds/checlusters.org.eclipse.che.CustomResourceDefinition.yaml 
```

### Describe the solution you'd like

Remove mention of postgres since it's no longer included as of 7.62. 

### Additional context

Continues from https://github.com/eclipse/che/issues/21374 and https://issues.redhat.com/browse/CRW-4105

**Comment by tolusha** [comment]
It is safe enough to remove those 2 fields from the CheCluster spec:
- https://github.com/eclipse-che/che-operator/blob/b9d8ce34b541a30d2d5f7329210bccd580bc0561/api/v2/checluster_types.go#L793
- https://github.com/eclipse-che/che-operator/blob/b9d8ce34b541a30d2d5f7329210bccd580bc0561/api/v2/checluster_types.go#L337
