### ISSUE TITLE
Continue with the default devfile button leads to an error

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22217]
### Describe the bug

Workspace start process fails with an error if the `Continue with the default devfile` button is clicked.

### Che version

7.66@latest

### Steps to reproduce

1. Deploy che via the test image: `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
  For the testing purpose I disabled gitlab factory handler in the image.
2. Apply the dashboard changes.
3. Pass a gitlab public repo with a devfile to start a workspace e.g. `https://gitlab.com/ivinokur/test.git`
4. Click the `Continue with the default devfile` button
See an error:
![screenshot-eclipse-che apps rosa qkmea-td9zm-m93 8p7k p3 openshiftapps com-2023 05 17-15_12_34](https://github.com/eclipse/che/assets/7668752/9c4dc556-dea9-4c43-8ab2-94754f4bf235)

### Expected behavior

Workspace starts from the default devfile.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

**Comment by vinokurig** [comment]
lifecycle/frozen

**Comment by akurinnoy** [comment]
Hi @vinokurig ,
can you please confirm if the issue still exists?

**Comment by vinokurig** [comment]
Can not reproduce any more.
