### ISSUE TITLE
[che-dashboard] Bump NodeJS to v18

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22227]
### Is your task related to a problem? Please describe

The end of life for NodeJS v16 is scheduled for 2023-09-11. Before that time, we need to migrate the `che-dashboard` project to NodeJS v18.

### Describe the solution you'd like

The migration includes:

- [ ] bump  NodeJS to v18
- [ ] upgrade dependencies and check them to be allowed to use
- [ ] fix build and unit tests as they may fail after migration
- [ ] update GitHub checks

**Comment by nickboldt** [comment]
See PR https://github.com/eclipse-che/che-dashboard/pull/908

**Comment by nickboldt** [comment]
Once dashboard is moved to node 18, we need to:
* update [job-config.json](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/job-config.json#L644-L649) downstream and 
* rebuild the worker nodes with https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/system/job/jenkins-node-setup/
