### ISSUE TITLE
Since updating to Che 7.65 Devfiles can no longer be edited from the workspace dashboard

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22222]
### Describe the bug

Since Che 7.65 the ability to modify and save a Devfile from the workspace dashboard seems to have been disabled:

![Screenshot 2023-05-18 at 11 45 37 AM](https://github.com/eclipse/che/assets/39659182/99cc549b-5e36-4291-b0eb-c5688054474d)

### Che version

7.66

### Steps to reproduce

1. Create a workspace from: [https://github.com/eclipse-che-demo-app/che-demo-app.git](https://github.com/eclipse-che-demo-app/che-demo-app.git)
2. Select edit workspace from the dropdown on the workspace in the menu on the left of the dashboard
3. Observe that you cannot make changes to the devfile

### Expected behavior

With Che 7.64 and prior, it was possible to modify a devfile from the dashboard and restart the workspace with the modified devfile.

### Runtime

OpenShift

### Screenshots

![Screenshot 2023-05-18 at 11 45 37 AM](https://github.com/eclipse/che/assets/39659182/9230dbea-23f6-41db-b791-6d32ac521615)

### Installation method

OperatorHub

### Environment

macOS

**Comment by RomanNikitenko** [comment]
As a workaround - it's possible to edit a devfile directly in the IDE and then apply changes using `F1` => `Restart Workspace from Local Devfile` command

<img width="365" alt="Screenshot 2023-05-19 at 15 25 49" src="https://github.com/eclipse/che/assets/5676062/fd384bb2-d077-49aa-bdd9-7d4a83058ee6">

**Comment by ibuziuk** [comment]
@cgruver well, devfiles have been made read-only on purpose on the UD as part of the https://github.com/eclipse/che/issues/21606

**Comment by cgruver** [comment]
Ah.  In that case, we need to remove the `Edit` option from the dashboard.

![Screenshot 2023-05-22 at 7 15 43 AM](https://github.com/eclipse/che/assets/39659182/f5f8d12f-3285-4025-8249-b4016b35834c)

**Comment by l0rd** [comment]
> However, the main use case that I have found for editing in the dashboard is where there is an issue and the workspace fails to start.

Note that before disabled editing from the dashboard we have implemented #21997 (workspace should start even if che-server fails to resolve the devfile). But I think that we should push it even further: if the workspace fails to start for whatever reason we should propose to start it in "safe mode".

**Comment by l0rd** [comment]
I have created https://github.com/eclipse/che/issues/22228

**Comment by ibuziuk** [comment]
opened https://github.com/eclipse-che/che-dashboard/pull/823 for fixing the label on UD
closing this issue in favor of https://github.com/eclipse/che/issues/22228
feel free to reopen
