### ISSUE TITLE
When workspace startup fails, propose to start it in "safe mode"

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22228]
### Is your enhancement related to a problem? Please describe

A workspace can fail for multiple reasons:
- vs code fails to start in the container specified in the devfile
- the requested memory/cpu in the devfile are too large
- the container in the devfile is terminating
- Mounting PVs fails
- Route or ingress creation fails
- Git service OAuth doesn't work 
- etc...

In this case the developer doesn't have any clue how to move forward. But we can help him/her providing a minimal workspace to be able to edit the source code (and the devfile if it exist).

### Describe the solution you'd like

When the workspace fails to start we should propose to the developer to start it in safe mode:
- the `devfile.yaml` and `.vscode/editor.yaml` are not resolved (use default component, default editor)
- no route/ingress is created (the editor endpoints with `urlRewriteSupport: false` are ignored)
- ephemeral storage
- Any operation that uses the git service REST API is avoided

**Comment by ibuziuk** [comment]
After the discussion the issue boils down to the following user story "As a user when workspace fails to start I should always have the option to start with the default devfile". Currently, this possibility is missing on the UI:


![image](https://github.com/eclipse/che/assets/1461122/97ae06a7-c64b-454a-984f-91d617b77300)

**Comment by l0rd** [comment]
I just sent a note to the che-dev mailing list about that.
