### ISSUE TITLE
Getting branding assets from Eclipse Che Dashboard should not require authentiction

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22239]
### Describe the bug

In OpenShift console the Eclipse Che / OpenShift Dev Spaces icon is not shown if the user hasn't logged in yet:

<img width="190" alt="image" src="https://github.com/eclipse/che/assets/606959/db02d0a7-a54b-4812-a177-52208d06d4d0">

The icon that is tried to be shown is `https://<che-host>/dashboard/assets/branding/loader.svg`

### Che version

7.67@latest

### Steps to reproduce

Open the topology view in OpenShift Developer Console in a cluster where Eclipse Che or Dev Spaces is installed (for example in Red Hat Developer Sandbox) without being authenticated.

### Expected behavior

I should be able to get the image even if I am not authenticated.

**Comment by tolusha** [comment]
Probably should be added as exception to 
https://github.com/eclipse-che/che-operator/blob/b31b92b13738e7eecba812d21a430ccc94afa5ca/pkg/deploy/gateway/oauth_proxy.go#L148
