### ISSUE TITLE
Workspace startup fails if I add the `merge-contribution` attribute 

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22231]
### Describe the bug

<img width="2501" alt="image" src="https://github.com/eclipse/che/assets/606959/91fe1b31-0b63-4987-a936-757b1dbd71e0">

### Che version

7.67@latest

### Steps to reproduce

Start a workspace on dogfooding instance from https://github.com/l0rd/wildfly-devfile-examples/tree/contribution-bug

### Expected behavior

The attribute [controller.devfile.io/merge-contribution: true](https://github.com/l0rd/wildfly-devfile-examples/blob/contribution-bug/devfile.yaml#L63) should allow to specify the container where VS Code should be mounted.  

I suspect that the devworkspace-generator [always add the attribute in the generated DevWorkspace](https://github.com/eclipse-che/che-devfile-registry/blob/d99ef8a7ff4975facfa7b802420d7544afed7564/tools/devworkspace-generator/src/generate.ts#L145) but it should not (c.f. [this issue](https://github.com/devfile/devworkspace-operator/issues/993))

**Comment by amisevsk** [comment]
Related: https://github.com/eclipse/che/issues/22155

**Comment by l0rd** [comment]
Thanks @amisevsk I am closing this issue as duplicated then.
