### ISSUE TITLE
Readiness Probe Fails for Plugin Registry Image

### ISSUE THREAD

**Issue by ArvinB** [eclipse/che#22233]
### Describe the bug

The following line of code should be using the `probePath` variable:

https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/registry/registry_deployment.go#L97

### Che version

7.67@latest

### Steps to reproduce

Perform a normal deployment and look at the events for the Plugin Registry deployment

### Expected behavior

Readiness probe succeeds

### Runtime

OpenShift

### Screenshots

N/A

### Installation method

OperatorHub

### Environment

Linux

### Eclipse Che Logs

```shell
N/A
```

### Additional context

@tolusha @nickboldt FYI

**Comment by tolusha** [comment]
@ArvinB 
Thank you for reporting. 
Maybe it depends on infrastructure, but I didn't find any suspicious events.
Anyway, I do agree that `probePath` was incorrect.
https://github.com/eclipse-che/che-operator/pull/1690
