### ISSUE TITLE
Login to 500 Internal Server Error

### ISSUE THREAD

**Issue by ywd1988** [eclipse/che#22268]
### Summary

Login to 500 Internal Server Error
![image](https://github.com/eclipse/che/assets/92080991/1f951df2-d98c-4540-a7b8-f651c446e317)

![image](https://github.com/eclipse/che/assets/92080991/0f2b6d32-5052-4ac2-a5c1-397b20df4b61)

**Comment by AObuchow** [comment]
@ywd1988 Thank you for the bug report. Would you please be able to provide more information about your Eclipse Che install? E.g. which version of Che you're running and on what type of Kubernetes cluster. 

When [posting a bug report](https://github.com/eclipse/che/issues/new/choose) to the Eclipse Che repository, the form will prompt you for the required information, including how you installed Che, your K8s environment. etc.

**Comment by ywd1988** [comment]
> @ywd1988感谢您的错误报告。您能不能提供有关Eclipse Che安装的更多信息？例如，您正在运行哪个版本的Che，以及在什么类型的Kubernetes集群上行。
> 
> 当Eclipse存储库[发布错误报告时，该表将提示您提供所需的信息，包括您如何安装车、您的K8s环境。](https://github.com/eclipse/che/issues/new/choose) ETC。

![image](https://github.com/eclipse/che/assets/92080991/130b20c4-fc3f-4396-b44d-9e7f542b124d)

**Comment by AObuchow** [comment]
@ywd1988 Thank you. 

What Linux distribution and version are you using? 

What `chectl` command are you using to deploy Eclipse Che?

**Comment by tolusha** [comment]
@ywd1988 
In case of minikube, please you the following command: 
`chectl server:deploy -p minikube`

**Comment by AObuchow** [comment]
@ywd1988 have you tried @tolusha's suggested command for launching che on minikube?
