### ISSUE TITLE
When stopping a workspace from VS Code I should be redirected to the Dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22269]
### Is your enhancement related to a problem? Please describe

When I stop the workspace from VS Code menu I don't get feedback for ~10s:

![2023-06-05 13 29 23](https://github.com/eclipse/che/assets/606959/5aae6dd4-e710-48cb-8eb8-4ead31193d89)

### Describe the solution you'd like

Immediately redirect the user to the dashboard or immediately show the pop up message.

**Comment by l0rd** [comment]
From implementation point of view we should add a new command "stop workspace and redirect" rather than modifying "stop workspace" that is used by other commands.

**Comment by SkorikSergey** [comment]
https://github.com/eclipse/che/issues/22269 PR with implementation.

**Comment by l0rd** [comment]
@skryzhny 👏 can you prepare a short video to demo this at next sprint review?

**Comment by SkorikSergey** [comment]
> @SkorikSergey 👏 can you prepare a short video to demo this at next sprint review?

Ok.
