### ISSUE TITLE
VS Code extensions list is empty

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#22263]
### Describe the bug

The `Extensions` list is empty in VS Code.

### Che version

next (development version)

### Steps to reproduce

Open the `Extensions` list in VS Code.

### Expected behavior

The extensions list should be loaded from Open VSX.

### Runtime

OpenShift

### Screenshots

![image](https://github.com/eclipse/che/assets/1636395/d0e4e3c6-9ca0-47c5-a507-fcdd0d3b6ac6)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
2023-06-02 10:58:54.371 [error] Error: Failed Installing Extensions: ms-ceintl.vscode-language-pack-uk
    at e.ExtensionManagementCLI.installExtensions (/checode/checode-linux-libc/out/vs/server/node/server.main.js:114:122)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async b.o (/checode/checode-linux-libc/out/vs/server/node/server.main.js:151:38425)
    at async b.j (/checode/checode-linux-libc/out/vs/server/node/server.main.js:151:37213)
    at async b.scanExtensions (/checode/checode-linux-libc/out/vs/server/node/server.main.js:151:36864)
    at async f.call (/checode/checode-linux-libc/out/vs/server/node/server.main.js:151:40409)
```
```


### Additional context

_No response_

**Comment by azatsarynnyy** [comment]
`OPENVSX_REGISTRY_URL="https://open-vsx.org/"`

**Comment by azatsarynnyy** [comment]
I suppose they (upstream) changed the default behavior so that the corresponding language pack is installed automatically now (what I've seen from the logs). The installation process is failed due https://github.com/eclipse/che/issues/21963 and the `Extensions` list is not populated.

**Comment by svor** [comment]
using editor `che-incubator/che-code/latest` won't help

**Comment by AObuchow** [comment]
FWIW, the extension list appears in my older CheCode workspaces that were stopped and re-started today (I'm able to search for and install extensions) but it does not appear on new workspaces that I've created today.

**Comment by azatsarynnyy** [comment]
I started investigating the issue in more detail and noticed that the problem is reproduced when the request to the OpenVSX instance contains an extra slash character: https://open-vsx.org//vscode/gallery/extensionquery

![image](https://github.com/eclipse/che/assets/1636395/fb5d43e2-f9b8-4e70-bb6a-470c92f67cb8)

Since today morning, I'm not able to reproduce this issue anymore.
It works well for me with the newest Che-Code image which is built a few hours ago: 
![image](https://github.com/eclipse/che/assets/1636395/4840558a-7828-4e24-aa11-41b33190f4fe)

No extra slash anymore. So, the Open VSX responds 200 instead of 400:

![image](https://github.com/eclipse/che/assets/1636395/08f39fee-c0b4-455f-a2b2-9f0cf0868b1a)

The `Extensions` panel is populated with the items:

![image](https://github.com/eclipse/che/assets/1636395/eb4eb25c-e583-4fe2-b332-a444eff82958)

**Comment by azatsarynnyy** [comment]
The problem is caused by Che-Code adding an extra slash character to the `openVSXURL` given from the `CheCluster` object. So, if it's configured with the trailing slash, e.g.:
```yaml
pluginRegistry:
      deployment:
        securityContext: {}
      openVSXURL: 'https://open-vsx.org/'
``` 
Che-Code adds one more slash when patching the [products.json](https://github.com/che-incubator/che-code/blob/5fa2e622941e3226f1e0264fd8031d29e27806c8/build/scripts/entrypoint-volume.sh#L63-L65) and it results in the following URL:
https://open-vsx.org//vscode/gallery/extensionquery

The workaround is to set `openVSXURL` without the trailing slash.

To proper fix is to take into account the leading slash when patching the products.json in [the Che-Code entrypoint script](https://github.com/che-incubator/che-code/blob/5fa2e622941e3226f1e0264fd8031d29e27806c8/build/scripts/entrypoint-volume.sh#L63-L65).

**Comment by azatsarynnyy** [comment]
I'm lowering the severity as we have a simple workaround now, so it's not a blocker anymore.

**Comment by RomanNikitenko** [comment]
There is not correct values in the `product.json` file for the case when `openVSXURL` is configured with the trailing slash:

![Screenshot 2023-06-06 at 13 30 54](https://github.com/eclipse/che/assets/5676062/322a26af-631d-470f-83d4-123f90562f3f)
