### ISSUE TITLE
How to get port redirect ingress hostnames to use dashes instead of periods

### ISSUE THREAD

**Issue by brandonp42** [eclipse/che#22267]
### Summary

I can't figure out why ingresses created to redirect to ports have periods in the host name. Ie they are being generated like: `<username>.<workspace>.<endpoint_name>.<domain_name>`

The problem is I have a wildcard certificate with *.<domain_name>, so I want the hostnames to be generated with dashes instead of periods. How can I fix this?

### Relevant information

Kubernetes (K3S) v1.26.5+k3s1

installed via chectl

checluster.spec.networking.ingressClassName = traefik
checluster.spec.networking.hostname = che.<domain_name>
checluster.spec.networking.domain = <domain_name>

SSL cert is using Lets Encrypt and is a wildcard for *.<domain_name>

chectl server:status
Eclipse Che Version    : 7.68.0

**Comment by brandonp42** [comment]
Also FWIW I looked into having cert-manager create individual certificates for each ingress and I don't think that's possible right now because I don't see a way to have either Che or cert-manager generate the TLS secret name in a unique way. The CheCluster resource appears to only let you specify a static name (not a template) and I don't see any way to get cert-manager to generate it either and update the ingress.

If the CheCluster CRD had a way to generate the TLS secret names uniquely for each ingress I think that might work but it would be better IMHO to keep the ingress hostnames in the same domain with dashes instead so I'm not generating tons of certificate requests.

**Comment by brandonp42** [comment]
I found the PR when this was merged, it was just last week. See https://github.com/eclipse-che/che-operator/pull/1672.

**Comment by dkwon17** [comment]
Hi @brandonp42 this is an important use case that I've missed, sorry about that, I've made a PR to address it.

After the PR is merged, you can try to:

* Update the `che-operator` deployment to use the newly built `quay.io/eclipse/che-operator:next` image to get the latest change right away 
* Wait for the new Che release set for Jun 14 

Then you can delete the old workspace ingresses which will then be recreated with new ingresses with the new host names

**Comment by brandonp42** [comment]
@dkwon17 thank you, I will keep an eye on the PR and try it out after the merge.

**Comment by brandonp42** [comment]
I updated my deployment and it looks good to me, thank you again.
