### ISSUE TITLE
Trailing spaces on samples in docs can break commands in confusing way

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22264]
### Describe the bug

Annotated callouts in code samples within the Che documentation can break commands when copy-pasting, leading to confusing behavior. 

For example, the documentation for [self-signed certificates for git repos](https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/) includes the sample command

```
$ kubectl create configmap che-git-self-signed-cert \
  --from-file=ca.crt=<path_to_certificate> \⎵⎵
  --from-literal=githost=<host:port> -n eclipse-che 
```

The two trailing spaces on the second line mean that if you copy-paste this command and update <path_to_certificate>, etc., the command will output 
```
error: exactly one NAME is required, got 2
See 'kubectl create configmap -h' for help and examples
```
since trailing spaces after the line continuation character break multi-line bash commands.

### Che version

7.68@latest

### Steps to reproduce

Copy block from step 1 in the procedure section of https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/ and paste it into a terminal (updating fields as required)

### Expected behavior

Command runs successfully

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by AObuchow** [comment]
@l0rd IMO this should probably be P1 issue for an upcoming sprint as it's important for users to be able to use the commands provided in the docs without any issues.
