### ISSUE TITLE
Add information on UD on how to edit devfile (Restart workspace from local devfile) 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22270]
Since 7.65.0 devfile edit functionality has been removed from UD - https://github.com/eclipse/che/issues/22222
For more details see https://github.com/eclipse/che/issues/21606 

As part of this issue, we can enhance UX and add info sigh, details on how devfile is expected to be edited

![image](https://github.com/eclipse/che/assets/1461122/8b904493-6272-43d4-8684-45562e75f9f8)

**Comment by ibuziuk** [comment]
@RomanNikitenko could you please clarify if we have the documentation for the `Restart workspace from local devfile` functionality that we can reference from the UD ?

**Comment by RomanNikitenko** [comment]
The command is mentioned in [this section](https://www.eclipse.org/che/docs/stable/end-user-guide/microsoft-visual-studio-code-open-source-ide/), AFAIK there is no separate section for that command.
