### ISSUE TITLE
"Open in Verbose mode" button of "Create Workspace" page doesn't switch page to verbose mode when workspace start has failed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22274]
### Describe the bug

Failed workspace is restarted in the same window after clicking on "**Open in Verbose mode**" button at start workspace page.

### Che version

next (development version)

### Steps to reproduce

1. Go to Che dogfooding instance
2. Create workspace from https://github.com/devspaces-samples/quarkus-quickstarts
3. Wait workspace start is failed.
4. Click on "Open in Verbose mode" button

Currently workspace is restarted in the same window.

### Expected behavior

Workspace is restarted in verbose mode.

### Runtime

OpenShift

### Screenshots

[screencast-che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com-2023.06.07-17_11_56.webm](https://github.com/eclipse/che/assets/1197777/a4453efe-9101-418e-9d7b-05231098c4f0)

### Installation method

chectl/next

### Environment

Linux

**Comment by olexii4** [comment]
Fixed with https://github.com/eclipse-che/che-dashboard/pull/896
