### ISSUE TITLE
Slowness, flickering and lags of the graphical interface of IntelliJ IDEA Community on Che-dogfooding

### ISSUE THREAD

**Issue by nallikaea** [eclipse/che#22283]
### Describe the bug

During [Red Hat Dev Tools Week](#22243 )  I as a user tried to use IntelliJ IDEA Community on for my daily development tasks on [Che-dogfooding](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com). It was not easy because a high number of UI bugs such as slowness, flickering and lags. Please, check attached videos to see more details.

### Che version

7.68@latest

### Steps to reproduce

1. Create empty workspace with IntelliJ IDEA Community editor on Che-dogfooding
2. Use UI to create a project from Version Control (File -> New -> Project from Version Control...)
3. Try to move opened window.
4. Clone TS project as https://github.com/eclipse/che
5. Open Editor settings and try to move window
6. Open terminal and try to make it bigger and smaller
7. When Editor ask you to install TypeScript extension agree and click on notification window

### Expected behavior

Interface works correct and smoothly

### Runtime

OpenShift

### Screenshots

[Screencast from 12.06.23 12:40:15.webm](https://github.com/eclipse/che/assets/72726250/3bd4b2ff-59b6-45ad-88de-6b92785bc8ac)
[Screencast from 12.06.23 13:18:39.webm](https://github.com/eclipse/che/assets/72726250/c53f8a86-aec3-46b8-9c19-1a013696dc37)
[Screencast from 12.06.23 13:19:02.webm](https://github.com/eclipse/che/assets/72726250/cea7300f-3be0-4751-b17e-32cce7061d82)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Installation method, Environment:
got already deployed instance on:
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com
![image](https://github.com/eclipse/che/assets/72726250/c3b82db7-1003-4e49-b2ac-1c5b2093c251)

**Comment by nallikaea** [comment]
#22243

**Comment by azatsarynnyy** [comment]
@nallikaea thanks for reporting the issue.
Could you share please what is your local environment (OS, etc.)?
To me, it looks like some issues are specific to the local graphical system.
I can't reproduce the issue on my laptop:

![image](https://github.com/eclipse/che/assets/1636395/27290274-7805-4f12-972b-a7fca68aaf91)

**Comment by nallikaea** [comment]
![image](https://github.com/eclipse/che/assets/72726250/4ee04245-0745-49d8-ba51-7292ccb50356)
![image](https://github.com/eclipse/che/assets/72726250/960abf58-bb41-49e8-a83b-5e96ca6c794b)

**Comment by ibuziuk** [comment]
Community Gateway based version is deprecated as of now - https://www.jetbrains.com/remote-development/gateway/
<img width="233" alt="Image" src="https://github.com/user-attachments/assets/56db9cd3-b442-4827-bba7-c29ecb947d56" />
