### ISSUE TITLE
Attempting to reconnect dialog sometimes appears even though workspace is still running

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22287]
### Describe the bug

When working on my workspace `try-in-web-ide-4u7r` in the dogfooding cluster, sometimes when I would take a 20min break from coding, when I return to the editor, I was greeted with this dialog a few times:

![image](https://github.com/eclipse/che/assets/83611742/6434e8e3-fe96-41b0-b6f2-49c416c1c4fc)

This appeared even though my workspace (`try-in-web-ide-4u7r`) was still running:
<img width="696" alt="image" src="https://github.com/eclipse/che/assets/83611742/720c3753-6c10-4b2f-a675-4e05157c9c17">

As a workaround, IIRC refreshing the editor fixed the issue.

### Che version

next (development version)

### Steps to reproduce

Unfortunately I don't have steps to reproduce this behaviour, it happened to me maybe once every two days.

### Expected behavior

The dialog should not appear. 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS, other (please specify in additional context)

**Comment by ibuziuk** [comment]
@l0rd @azatsarynnyy folks, maybe this is smth you can investigate in the next sprint?

**Comment by RomanNikitenko** [comment]
maybe our patch was just rewritten by VS Code changes...

**Comment by azatsarynnyy** [comment]
> maybe our patch was just rewritten by VS Code changes...

most likely

**Comment by RomanNikitenko** [comment]
btw, one of the screenshots displays a warning that `WebSocket connections are failing`. 
so, maybe @dkwon17 has faced a problem when VS Code really loses WebSocket  connection and tries to reconnect.
yes - the workspace is still running, but VS Code has lost the connection...

what behaviour would be better for such use case?
just propose user to refresh the page without attempt to reconnect?

**Comment by azatsarynnyy** [comment]
I suggest postponing it until https://github.com/eclipse/che/issues/22352 is fixed. I faced the current issue a few times and each time I saw that Dashboard issue.
