### ISSUE TITLE
Git Branch Prefix?

### ISSUE THREAD

**Issue by bjoerm** [eclipse/che#22285]
### Summary

Hello,
Since version 1.68 (May 2022) VS Code supports an option to automatically set a prefix for new Git branches:
https://code.visualstudio.com/updates/v1_68#_git-branch-name-generation

I use this feature almost daily in VS Code and miss this in Che. Can this be added? 

And if you don't mind: Can you tell me why it is not implemented, when I am using a version that is based on a newer version than 1.68? Or is the Git extension a separate thing and I need to ask elsewhere?

Anyway, thanks for your work and thanks in advance for taking your time to read my question.

**Comment by dkwon17** [comment]
Hello @bjoerm , thanks for the question, could you please elaborate what version of Eclipse Che you are using?

I've checked with `next` version of Eclipse Che, and the `git.branchPrefix` seems to be working in VS Code running in Che:

https://github.com/eclipse/che/assets/83611742/74d072e2-55a6-4025-b6bb-3b8dd794bc9d

**Comment by bjoerm** [comment]
Thank you very much for your answer and even the video you added, @dkwon17!

We are using Red Hat OpenShift Dev Spaces Version: 1.74.0. We thought Che as the foundation of Dev Spaces and thus the source of that missing feature in our Dev Spaces. But I see now that that assumptions does not hold. Please forgive me asking in the wrong place and you taking the effort for answering my question.

I will search for a way to ask directly to people in touch with Dev Spaces.

**Comment by dkwon17** [comment]
No problem @bjoerm , Che is the foundation of Dev Spaces and I think your question is a good question to ask here since it's also relevant to the Eclipse Che project

If you can share, what exactly about https://code.visualstudio.com/updates/v1_68#_git-branch-name-generation is not working for you?

Is the `Git: Create Branch...` command or `Git: Branch Prefix` setting missing?

**Comment by bjoerm** [comment]
Thanks again, @dkwon17.

Issue: I am missing the git.branchPrefix in the settings of Dev Spaces. It does not find any settings. Whether searching for git.branchPrefix nor for Git Prefix leads to any entries.

Our version is 1.74.0.

See screenshot (in the background you can see the unsuccessful search in the settings).
![image](https://github.com/eclipse/che/assets/8392548/23b8edf6-e145-4d3d-85d3-208acd40e7e0)

Do you need any further information?

**Comment by dkwon17** [comment]
Could you please check if the vscode `Git` extension appears when searching `@builtin git` in the extension search bar?
<img width="291" alt="image" src="https://github.com/eclipse/che/assets/83611742/501af954-31e3-4fc0-ac22-2de683b6d782">

If not, does it appear when searching `@workspaceUnsupported  git`?

**Comment by dkwon17** [comment]
Is the `git.branchPrefix` setting visible under the `FEATURE CONTRIBUTIONS` section?
<img width="1052" alt="image" src="https://github.com/eclipse/che/assets/83611742/14591d63-9f69-4450-a5c7-f403c54db164">


If yes, are other settings/features provided by the the Git extension (ex. `git.branchProtection`) available in your workspace?

Another thing to check could be if there are any logs by the Git extension in `Developer: Show Logs... > Extension Host (Remote)` from the command palette

**Comment by dkwon17** [comment]
You're welcome, great to hear!
