### ISSUE TITLE
Improve personal access token validation when add it to User Preferences in Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22286]
### Is your enhancement related to a problem? Please describe

There is capability to add personal access token to _Eclipse Che Dashboard_, and it shows too vague error message when validation of token has failed:

![Screenshot from 2023-06-12 15-43-30](https://github.com/eclipse/che/assets/1197777/85b1b952-d098-492b-954e-c71cba8308f8)

The root cause is complicated validation flow on Dashboard side, which consists of 3 steps [1]:
1. Store new token.
2. Request namespace provision as it triggers tokens validation using che-server API.
3. Read available tokens after namespace provisioning.
4. Display error message if new token is not available.

If new token is not available, Dashboard shows too vague error message:
> Token "\<token name\>" was not added because it is not valid.

[1] https://github.com/eclipse-che/che-dashboard/blob/5da6c4a0da735a8f303b39ea74f21ad27e6462b7/packages/dashboard-frontend/src/store/PersonalAccessToken/index.ts#L114-L159

### Describe the solution you'd like

Add token validation method to che-server API, which will check the token and return error message with found problem explanation.

Updated Dashboard flow:
1. Request token validation service in che-server API
2. Display error message which token validation service returns if token is invalid.

**Comment by vinokurig** [comment]
Instead of extending the che-server API we can check the token directly in the dashboard side by making a test request with the token.

**Comment by akurinnoy** [comment]
It's possible to add the check to the dashboard side. But it'll be better to implement this check on the side which uses provided tokens for resolving factory links.

**Comment by vinokurig** [comment]
@ibuziuk @l0rd WDYT?

**Comment by l0rd** [comment]
Please let's discuss it on a call. The description is not clear. Although I agree with the message being too vague, I don't understand the details of the 3 (or 4?) steps.
