### ISSUE TITLE
On dogfooding, sometimes cannot open workspace, redirected to dashboard instead

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22288]
### Describe the bug

Sometimes, when working on my private repository on the dogfooding cluster, the workspace enters the `RUNNING` state, however, the editor does not open, and instead I am being redirected to the dashboard:

https://github.com/eclipse/che/assets/83611742/ab95ef1b-cd31-48da-9aae-a8352575895c

When accessing the editor, the user should be redirected to the dashboard only if the workspace mainUrl returns a 5XX error. Since workspace is in the `RUNNING` state, this means that the health check must have returned a 2xx or 4xx code, see [1].

But for whatever reason, despite health check returning 2xx/4xx, it seems traefik receives a 5xx error when trying to access the mainUrl, therefore causing an unintended redirect to the dashboard.

[1] https://github.com/devfile/devworkspace-operator/blob/61bd5d1888bfa686b01b9b744a3bfcb955e38a8b/controllers/workspace/status.go#L211-L217

### Che version

next (development version)

### Steps to reproduce

Unfortunately I'm not able to reproduce this issue regularly. The GitHub repo I used to create the workspace with was a private repo

### Expected behavior

After the workspace is in the `RUNNING` state, the user should be directed to the editor.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS, other (please specify in additional context)

**Comment by dmytro-ndp** [comment]
I had the same problem with workspaces created from GitHub repo.

**Comment by dkwon17** [comment]
I am now seeing this problem for private and public GitHub repositories

**Comment by dkwon17** [comment]
@dmytro-ndp do you remember if this happened when starting a workspace that has other workspace with a similar name? 

For example, did you have these workspaces:
```
quarkus-api-example
quarkus-api-example-abc1
```

and then did the problem happen when you tried to start `quarkus-api-example-abc1`?

**Comment by dkwon17** [comment]
After more investigation, I am convinced this is a routing issue:
```
time="2023-06-14T17:41:38Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 172.30.109.187:3030: connect: connection refused"
time="2023-06-14T17:41:38Z" level=debug msg="Caught HTTP Status Code 502, returning error page" middlewareType=customError middlewareName=workspace46c5dca769194c5f-errors@file
```

the traefik is trying to access the wrong workspace service, in the log above, it tries to reach `172.30.109.187` which is the incorrect service

**Comment by dkwon17** [comment]
cc @ibuziuk @olexii4 @akurinnoy
