### ISSUE TITLE
Figure out reason of failures generated EmptyWs on k8s infra 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse/che#22295]
### Describe the bug

When we apply the latest version of the DevFile generator: https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator for the EmtyWorkspace sample some k8s objects is not created properly and the Workspace failed by Timeout.

### Che version

7.68@latest

### Steps to reproduce

1. Generate the EmptyWs using library
2 oc apply -f ... generated file

### Expected behavior

The Empty ws should applied without err.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

**Comment by nallikaea** [comment]
Hi, @musienko-maxim 
Can not catch this problem locally. Empty Workspace DevWorkspace generated with [devworkspace-generator]( https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator) successfully deployed on minikube, test marked as passed. Could you please provide mo details? 

![image](https://github.com/eclipse/che/assets/72726250/309ab9b9-1974-432d-85f1-b459a0a3998b)
![image](https://github.com/eclipse/che/assets/72726250/aa8e458d-eac5-4499-847a-656372cca24b)
[log.txt](https://github.com/eclipse/che/files/11834251/log.txt)
