### ISSUE TITLE
When an editor is updated, are existing workspaces updated to use the new definition?

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22291]
### Summary

When Che is updated, it usually comes with a new version of VS Code, IntelliJ and PyCharm. New workspaces will get those new versions but what about existing workspaces?
- Are the existing DevWorkspaecTemplates updated when users restarts an existing workspace?
- Is a new image pulled when a user restarts an existing workspace?

**Comment by ibuziuk** [comment]
@olexii4 could you please take a look and confirm that all works as expected - https://github.com/eclipse-che/che-dashboard/pull/397

**Comment by olexii4** [comment]
@ibuziuk It does not work as expected. I am working on the fix.
