### ISSUE TITLE
`Recent` list in Che Code welcome page enhancement

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22302]
### Is your enhancement related to a problem? Please describe

When opening a new workspace, the `Recent` list can be a bit confusing:
<img width="742" alt="image" src="https://github.com/eclipse/che/assets/83611742/a07209af-d861-4bf1-9304-186bbd38f99f">

Clicking on the recent projects will not open them because they are not cloned for the current workspace.

<details>
<summary>Video of what happens when trying to click on a recent project</summary>

https://github.com/eclipse/che/assets/83611742/d1086e94-3a7f-4cb0-adc7-9b4ab525e6d7

</details>

### Describe the solution you'd like

Would be great if this list can either be hidden, or, if they are links that can start the workspaces in a new window

**Comment by AObuchow** [comment]
> Would be great if this list can either be hidden, or, if they are links that can start the workspaces in a new window

+ 1 to both these suggestions.
