### ISSUE TITLE
Adding extra permissions break Bitbucket Saas OAuth flow

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22301]
### Describe the bug

According to the docs https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-the-bitbucket-cloud/ configuring bitbucket SaaS requires Account and Repositories

![image](https://github.com/eclipse/che/assets/1461122/62bda6c3-e9e6-422e-baeb-1727b32c1cda)

However, if extra permissions are granted OAuth flow will be broken (it will not be possible to clone private repos)

### Che version

7.69@latest

### Steps to reproduce

1. Configure BitBucket SaaS according to the docs, but add extra permissions a part from required Account and Repositories
2. Create workspace based on the private BitBucket repo
3. ERROR: project can not be clonned - `fatal: could not read Username for 'https://bitbucket.org/': No such device or address`

### Expected behavior

OAuth works if extra permissions are added

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

at the very least we should add a warning in the docs that adding extra permissions is prohibited

**Comment by ibuziuk** [comment]
@tolusha do we need docs PR for that or current instructions should be fine?

**Comment by tolusha** [comment]
It does not require any documentation update.
