### ISSUE TITLE
How to set http_proxy for Looking for devfile

### ISSUE THREAD

**Issue by kuberxy** [eclipse/che#22310]
### Summary

Please help me!
How to set http_proxy for Looking for devfile?
My network always get connect timed out.
![Image 2](https://github.com/eclipse/che/assets/35421150/549d05a0-9fc3-457f-a880-c58b9b8a33ea)

**Comment by tolusha** [comment]
Hi. @kuberxy 

You have to configure CheCluster CR to specify proxy settings, see [1]

```yaml
spec:
  components:
    cheServer:
      proxy:
...
```

[1] https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-components-cheServer-proxy-settings

**Comment by kuberxy** [comment]
> Hi. @kuberxy
> 
> You have to configure CheCluster CR to specify proxy settings, see [1]
> 
> ```yaml
> spec:
>   components:
>     cheServer:
>       proxy:
> ...
> ```
> 
> [1] https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-components-cheServer-proxy-settings

Thank you so much. I tried. This method works.
