### ISSUE TITLE
two workspaces are created instead of one

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22323]
### Describe the bug

I have a workspace created from a sample.
I create another workspace from the same sample.

As result I have 3 similar workspaces:
- the old one
plus
- 2 new workspaces

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace from a sample (in my case it was Node.js Web Application).
2. Stop the workspace.
3. Create a new workspace from the same sample.
4. Check list of workspaces

### Expected behavior

Only one workspace is created

### Environment

I faced the problem on the `dogfooding` instance

### Additional context

https://github.com/eclipse/che/assets/5676062/0fbb31e3-3f1a-4d88-a7f8-bb931de1a22a

**Comment by ibuziuk** [comment]
@olexii4 could it be related to https://github.com/eclipse/che/issues/22326 ?

**Comment by olexii4** [comment]
> @olexii4 could it be related to #22326 ?

Yes, it is precisely related to https://github.com/eclipse/che/issues/22326.
