### ISSUE TITLE
VS Code data about a previously opened workspace is cached in the browser when switching workspaces

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22338]
### Describe the bug

When switching workspaces, or deleting and re-creating a workspace, data from previously opened workspaces is still cached in the browser and used by VS Code.

See the below screenshot:

![Screenshot 2023-06-30 at 7 36 03 AM](https://github.com/eclipse/che/assets/39659182/3372dd48-830c-4ea1-b2aa-b95f8fba2b20)

If I click on any of those links under `Recent`, I will get an error because those are reference to code-workspaces, files, and folders from other Che Workspaces.

Potentially related to: #22289

### Che version

7.69

### Steps to reproduce

1. Open a Che Workspace with VS Code as the editor (Don't know if IntelliJ is impacted)
1. Open files, folders, or a code-workspace
1. Close the Che Workspace
1. Open a different Che Workspace
1. Observe that the `Recent` list includes items from the closed Che Workspace. 

### Expected behavior

Cache is not retained after a workspace is closed.

__Note:__ This expected behavior may also have negative UX impacts...  There may be some level of caching needed for a good UX.

Perhaps, cache should be workspace unique, and deleted if a workspace is deleted...

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

**Comment by azatsarynnyy** [comment]
It looks like we're facing [this problem](https://github.com/eclipse/che/issues/21813#issuecomment-1312751451) again.
IIRC, previously, DevWorkspace ID was part of a workspace URL, so [this solution](https://github.com/che-incubator/che-code/pull/148) worked well for Che. Now, the DevWorkspace's name is part of the URL instead, but not ID anymore, we need to adapt Che-Code to this change. 

We have the `DEVWORKSPACE_ID` environment variable. But we can't read it directly from VS Code Core.
To fix this, we can try to pass `DEVWORKSPACE_ID` through the [workbenchWebConfiguration](https://github.com/microsoft/vscode/blob/7c34ea4452bf66116f7013047124bdd8a6909409/src/vs/server/node/webClientServer.ts#L326C2-L326C2) from the backend to frontend to read it in the [Workbench](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/workspaces/browser/workspaces.ts).
