### ISSUE TITLE
New Workspaces Startup Page Improvements

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22332]
### Is your enhancement related to a problem? Please describe

Here are a couple of screenshot of the new workspace startup page:

<img width="400" alt="image" src="https://github.com/eclipse/che/assets/606959/0e3a9dac-59e1-4e5a-96cf-87d11876a7a2">

<img width="400" alt="image" src="https://github.com/eclipse/che/assets/606959/db98ba2b-250f-44ea-9475-68c6fbee5431">

**With respect to the 2 screenshot above a few observations:**

- When a task is finised (for example "3 - Creating Workspace") all its subtasks should be hided
- The spinners/checks for a subtask should be positioned closer to subtask name (there is a big space in between now)
- No spinner appears close to "3 - Creating Workspace" but it does appear close to "4 - Waiting for workspace to start". For consistency we shouldn't show it close to step 4 neither. 
- "Waiting for workspace deployment may be splitted in subtasks (i.e. "cloning git repository", "copying the IDE binary", "starting the IDE" etc...)

**Some feedback also on the subtasks naming/details:**

- What happens in "initializing"? Are we checking if the developer namespace exist? It may be useful here to list the URL parameters provided (project url / editor / image / remote ...)
- Looking for devfile => Inspecting repo .... for a devfile
- Devfile found in repo ... => Devfile found with name/generatedName ...
- (probably here we also inspect for an che-editor.yaml file?)
- Checking existing workspaces => Checking if a workspace with the same exist (and when it completes we should 
- Applying devfile => Generating a DevWorkspace from the Devfile
- DevWorkspace is starting => We never confirm if it's started
- Preparing networking => We never confirm if networking is ready
- Waiting for DevWorkspace ServiceAccount => I think that it should rename this as "Creating workspace ServiceAccount" and then we should confirm "Service account <sa-name> created"
- Waiting for DevWorkspace pull secret => Including Container Registries credentials
- It would be informative to mention when the kubeconfig is generated

**Comment by akurinnoy** [comment]
@l0rd Hi, I've addressed most of the fixes/improvements but also have some comments and questions.

> "Waiting for workspace deployment may be splitted in subtasks (i.e. "cloning git repository", "copying the IDE binary", "starting the IDE" etc...)

All sub-steps under "Waiting for workspace to start" including "Waiting for workspace deployment" are DevWorkspace status conditions (see pic below). I believe it may be split but not on the Dashboard side.

> DevWorkspace is starting => We never confirm if it's started
> Preparing networking => We never confirm if networking is ready

I've fixed the behavior so all sub-steps under "Waiting for workspace to start" are get confirmed according to the DevWorkspace status conditions. 

>  Waiting for DevWorkspace ServiceAccount => I think that it should rename this as "Creating workspace ServiceAccount" and then we should confirm "Service account created"
>  Waiting for DevWorkspace pull secret => Including Container Registries credentials

It's possible to rename these sub-steps on the Dashboard side but I'm not sure it's the best place. So, shell we proceed with it on the Dashboard side?

![vlcsnap-2023-08-08-11h20m11s343](https://github.com/eclipse/che/assets/16220722/ad5e78ad-7e52-4e2a-91d7-88245e8747c1)

**Comment by ibuziuk** [comment]
> It's possible to rename these sub-steps on the Dashboard side but I'm not sure it's the best place. So, shell we proceed with it on the Dashboard side?

I belive no, we should display whatever is received from DWO / DW cc: @amisevsk

**Comment by amisevsk** [comment]
I agree it's probably best to display what DWO sets. On the other hand, these messages are intended to be user facing so I'm open to rewording/clarifying/adding to improve the sequence shown in the dashboard.
