### ISSUE TITLE
Display User email in the Azure DevOps PAT popup

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22339]
### Is your enhancement related to a problem? Please describe

According to the [documentation for creating a PAT ](https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) we use `user email` instead of `username` for the `che.eclipse.org/scm-username` annotation in case of Azure DevOps. When selecting the Azure DevOps provider in the `Add Personal Access Token` dashboard popup displays `Git Provider Username`:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2023 06 30-15_32_20](https://github.com/eclipse/che/assets/7668752/687a069e-8cbf-4baa-997a-1938cf32d748)

### Describe the solution you'd like

Show specific label `user email` for the Azure DevOps case in the dashboard popup.

**Comment by ibuziuk** [comment]
related to https://github.com/eclipse/che/issues/22313

**Comment by ibuziuk** [comment]
closing in favour of https://github.com/eclipse/che/issues/22344
