### ISSUE TITLE
Get rid of setting `Git Provider Username` while configuring PAT

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22344]
### Is your enhancement related to a problem? Please describe

It sounds redundant and overhead from a user point of view and might leads to invalid PAT
 
![screenshot-192 168 39 5 nip io-2023 07 04-10_13_33](https://github.com/eclipse/che/assets/1640675/e4ce876e-15c2-40e7-88dd-d26c0aaca484)

### Describe the solution you'd like

Get rid of setting `Git Provider Username` while configuring PAT to simplify configuration

**Comment by ibuziuk** [comment]
@vinokurig great job, PRs have been merged. Can we close?
