### ISSUE TITLE
Split out extension publishing in che-plugin-registry to a separate phase to make it simpler for users to customize

### ISSUE THREAD

**Issue by etsauer** [eclipse/che#22347]
### Is your enhancement related to a problem? Please describe

As a user of eclipse che & dev spaces, I need to build my own instance of the che-plugin-registry image to get the extensions that I want. Using the build.sh script in the [repo](https://github.com/eclipse-che/che-plugin-registry) works ok, but having to rebuild the entire image every time I want to add an extension to my registry makes it tough to build a process around. The entire build takes about 11-14 minutes, the first 6ish of which is just spent installing packages, building artifacts & running tests.

### Describe the solution you'd like

I would like to be able to run the build.sh script against a pre-built image so that I can skip to the process that starts openvsx and runs through the publishing process. We have no need to modify anything before that stage.

### Describe alternatives you've considered

We've tried going the route of just running our own openvsx instance from the upstream repos, and using the API directly for publishing. The problem with that is that they don't provide APIs for deleting extensions, or modifying extension versions, so it's simpler to just re-populate an empty registry from scratch for each change. I think the self-contained image is a more stable approach for now, but it would be nice to be able to just skip the parts of the build step that we don't need to modify

**Comment by svor** [comment]
The `build.sh` script can be improved to skip yarn build of the editor's generator tool. Yarn build could be sipped when the generator tool wasn't changed or we can add an parameter to the script to avoid yarn build, for example `--skip-generator-build`
