### ISSUE TITLE
Provide env variable with che-code endpoint URL to the tools container

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22346]
### Is your task related to a problem? Please describe

At the moment there is a logic in the `che-code` entrypoint to get  che-code endpoint URL
`yq` is used to read `/devworkspace-metadata/flattened.devworkspace.yaml` file and get the endpoint URL.

We are going to get rid of dependency for `yq` and `jq` tools within https://github.com/eclipse/che/issues/21778.

### Describe the solution you'd like

It would be great to have a possibility to get that endpoint as env variable without any complex logic on the `che-code` entrypoint side. 

<img width="1141" alt="endpoint" src="https://github.com/eclipse/che/assets/5676062/f2ddbbb0-c803-4f06-8c31-14fee8996889">

**Comment by RomanNikitenko** [comment]
@ibuziuk @olexii4 
can it be done on the dashboard side?
or
it's not dashboard area?

**Comment by olexii4** [comment]
> I'm not sure where this should be implemented...
> 
> @ibuziuk @olexii4 can it be done on the dashboard side? or it's not dashboard area?

It is not a dashboard area.
