### ISSUE TITLE
Add token verification step in "Using a Git-provider access token" documentation article

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22359]
### Is your enhancement related to a problem? Please describe

A cause of failure when following the [documentation for PAT](https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) is that the personal access token can be invalid. Considered that there are many moving parts it can be difficult for a user to identify that the problem is the token.

### Describe the solution you'd like

Add a `verification steps` section to the article ([as we already have for TLS certs](https://www.eclipse.org/che/docs/stable/administration-guide/importing-untrusted-tls-certificates/)) with a step to verify the token that consist in trying to git clone a private repository:

```
$ git clone https://invalidtoken@github.com/l0rd/private-test
Cloning into 'private-test'...
Password for 'https://invalidtoken@github.com':
```

**Comment by ibuziuk** [comment]
PR has been merged. Closing

**Comment by deerskindoll** [comment]
> @l0rd @vinokurig @deerskindoll could you please review - [eclipse-che/che-docs#2645](https://github.com/eclipse-che/che-docs/pull/2645) if all is good, I think it would be nice to backport for 3.8

backported to 7.72.x
