### ISSUE TITLE
Podman build fails on latest OKD 4.13 FCOS based builds

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22355]
### Describe the bug

A recent update to either the OpenShift code base, or Fedora CoreOS has broken the ability to run `podman build` in a Che workspace.

The issue manifests after updating `4.13.0-0.okd-2023-06-04-080300` to version `4.13.0-0.okd-2023-06-24-145750`

### Che version

7.70@latest

### Steps to reproduce

Build a cluster with `4.13.0-0.okd-2023-06-24-145750`

Deploy Eclipse Che

Start a workspace enabled for container build

Run:

```bash
podman images
```

Observe the error:

```bash
cannot clone: Permission denied
Error: cannot re-exec process
```

### Expected behavior

Podman images returns a list of images, or empty if no images are present.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

**Comment by ibuziuk** [comment]
cc: @l0rd probably smth. to investigate in the next sprint

**Comment by cgruver** [comment]
Excellent.  This is either fixed upstream, or it's an OKD/FCOS specific issue.

I'll test on a nightly build too.

**Comment by cgruver** [comment]
@l0rd I built a cluster with `4.13.0-0.okd-scos-2023-07-07-043417` which uses CentOS Stream CoreOS as the underlying OS rather than Fedora CoreOS.

Podman works fine.

I'm going to build an OKD/FCOS based cluster from a recent nightly.

**Comment by cgruver** [comment]
Works on latest SCOS based OKD

Fails on latest nightly FCOS based OKD

**Comment by l0rd** [comment]
> Fails on latest nightly FCOS based OKD

@cgruver what is the impact of this? Will the issue be propagated to RHEL/OCP or not? Is OKD usually deployed on FCOS, SCOS, both?

**Comment by cgruver** [comment]
@l0rd OKD is generally deployed with FCOS.  The support for SCOS is relatively new.

Unaddressed, it's possible that the issue would eventually make it into RHCOS.  I opened an issue on the OKD project page to raise awareness, and alerted one of the project leads.
