### ISSUE TITLE
Docs "User Guide" improvements

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22357]
### Is your enhancement related to a problem? Please describe

User Guide documentation can be improved

### Describe the solution you'd like

- [x] `s/User onboarding/Getting started/`
- [x] `s/Starting a new workspace with a clone of a Git repository/Starting a workspace from a Git repository URL/`
- [x] `s/Starting a new workspace from a devfile URL/Starting a workspace from a devfile raw URL/`
- [x] `"Optional parameters for the URLs for starting new workspaces" should be under section "Starting a workspace from Git repository URL"`
- [x] "Adopting Che" should be:
	- `Put on a diet (the only subsection worth saving are "Badge for first time contributors" and "Reviewing pull and merge request" but it's lacking a reference to "Try in Web IDE" GitHub action)`
    - `Renamed something like "Using Che in your team workflow"`
    - `Moved after "Getting Started".`
- [x] `The article "Microsoft Visual Studio Code - Open Source" is under "Documentation/User Guide/Adopting Che/Developer workspaces" but should be under "Documentation/User Guide/IDEs in workspaces/Microsoft Visual Studio Code - Open Source instead" instead`

**Comment by ibuziuk** [comment]
@deerskindoll would you be interested in working on this issue?

**Comment by deerskindoll** [comment]
> @deerskindoll would you be interested in working on this issue?

sure!
