### ISSUE TITLE
Starting a new workspace from a RAW devfile URL doesn't support URL parameter for the devfile file name

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22368]
### Describe the bug

We can [start a new workspace from a RAW devfile URL](https://www.eclipse.org/che/docs/stable/end-user-guide/starting-a-new-workspace-from-a-devfile-url/). In case if the devfile file name differs from the conventional (`devfile.yaml` or `.devfile.yaml`) We have [URL parameter for the devfile file name](https://www.eclipse.org/che/docs/stable/end-user-guide/url-parameter-for-the-devfile-file-name/) to be able to specify the devfile filename. Currently workspace fails to start from the Raw devfile URL with unconventional yaml name, either with the `?df=<filename>.yaml` parameter.

### Che version

7.71@latest

### Steps to reproduce

1. Create a GitHub gist named `test.devfile` with a simple devfile content. Copy the Raw URL of the gist.
2. [Start a workspace with the RAW devfile URL](https://www.eclipse.org/che/docs/stable/end-user-guide/starting-a-new-workspace-from-a-devfile-url/)

See: workspace fails to start.

### Expected behavior

Workspace starts successfully

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

**Comment by ibuziuk** [comment]
IMO, `?df=<filename>.yaml` parameter does not make sense for raw URLs. Wondering what break it in 3.7 if in 3.6 looks like any filename for raw URLs worked

**Comment by vinokurig** [comment]
I assume this worked before the https://github.com/eclipse-che/che-server/pull/519 PR. And before the PR it worked only for defiles by the GitHub RAW file content.

**Comment by vinokurig** [comment]
@ibuziuk @l0rd
> IMO, ?df=<filename>.yaml parameter does not make sense for raw URLs.

Do you think we should ignore the `yaml` file name for the RAW devfile URL approach?
