### ISSUE TITLE
Starting new workspaces fails on deployment in OpenShift 4.12

### ISSUE THREAD

**Issue by willkara** [eclipse/che#22365]
### Describe the bug

I have a brand new OpenShift 4.12 cluster and am deploying Ecclipse Che to act as common IDE for our developers. I have the operator installed and a Che Cluster configured through the Operator Hub in the OpenShift console.

It installs perfectly fine and all the services/routes work!

The issue comes when I try and spin up a workspace. 

1. It always fails on the first `Waiting for workspace deployment` part because my guess is that it needs to wait for the PVC to complete. Weird how it doesn't wait for that.
![creating workspace failure](https://github.com/eclipse/che/assets/3278887/43843d27-3431-4e10-8911-160a92398e89)
2. After this, I hit restart and it continues. Looking at the OpenShift console event log, it then succeeds and starts spinning up other pods, services ...etc.
![event1](https://github.com/eclipse/che/assets/3278887/09f52631-7fbd-48f4-9dcb-18bc5ceecc57)

3. What's weird is that the entire time, nothing changes in the Eclipse Che logs, just the events. Plus, As I see the different services and pods spin up and after it seems like it's done, the workspace still doesn't complete.

The last event I see is:

`
Successfully pulled image "quay.io/che-incubator/che-code@sha256:e33137d2633e43f31cf0417fb6de75c14f27af86a3b7ece8f5cf9ba6117272f1" in 1m2.04654706s (1m2.04655368s including waiting)
`

### Che version

7.71@latest

### Steps to reproduce

Trying to spin up a workspace in OpenShift 4.12 after installing the operator

### Expected behavior

Workspace successfully spins up and can be loaded.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by tolusha** [comment]
Hello, @willkara 
Could you describe the PVC, it might shed light on the problem
`oc describe pvc -n <USER_NAMESPACE> <PVC_NAME>`

**Comment by willkara** [comment]
Hi @tolusha , sorry, just saw this! I  was able to get it working, but in a weird way. I simply waited to hit the restart button for a few seconds _after_ the initial request. I guess that gave the system enough time to "catch-up" and provision the PVC.

I'll continue testing for new workspaces this week and will check with the storage provider on why this seems to be happening a lot.
