### ISSUE TITLE
Remove docker from UDI, create `alias docker=podman` in both upstream and downstream

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22374]
### Is your enhancement related to a problem? Please describe

UDI contains podman, and we do not support docker. The only way to have it working is probably  creating an alias smth. like `alias docker=podman`

### Describe the solution you'd like

remove docker from UDI

### Describe alternatives you've considered

N/A

**Comment by ibuziuk** [comment]
@tolusha reopening for clarification. Is it removed in both upstream and downstream?

**Comment by tolusha** [comment]
Do we have a dedicated repo for downstream?

**Comment by ibuziuk** [comment]
yes https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/devspaces-udi

**Comment by tolusha** [comment]
I see, downstream uses buildah under the hood [1] [2]
@l0rd Should we remote it as well?

[2] https://github.com/redhat-developer/devspaces-images/blob/8bf68c10cbd4c8c61a9faa1e71caf77a48ab135f/devspaces-udi/etc/docker.sh
[1] https://github.com/redhat-developer/devspaces-images/blob/4b2d6333277de869c42d1d90be9951198e3cd19e/devspaces-udi/Dockerfile#L110

**Comment by l0rd** [comment]
> I see, downstream uses buildah under the hood [1] [2] @l0rd Should we remote it as well?
> 
> [2] [redhat-developer/devspaces-images@`8bf68c1`/devspaces-udi/etc/docker.sh](https://github.com/redhat-developer/devspaces-images/blob/8bf68c10cbd4c8c61a9faa1e71caf77a48ab135f/devspaces-udi/etc/docker.sh) [1] [redhat-developer/devspaces-images@`4b2d633`/devspaces-udi/Dockerfile#L110](https://github.com/redhat-developer/devspaces-images/blob/4b2d6333277de869c42d1d90be9951198e3cd19e/devspaces-udi/Dockerfile#L110)

Docker is not included in the downstream image. So there is nothing to remove from my point of view. The script `docker.sh` executes `podman build` when the developer type `docker build`. This is fragile but that's another issue (we should rather add `alias docker=podman` in `.bashrc` as mentioned by @ibuziuk, both upstream and downstream).

**Comment by ibuziuk** [comment]
@l0rd thanks for the input. @tolusha I updated the description, let's add `alias docker=podman` in both upstream and downstream and close the issue after that

**Comment by tolusha** [comment]
I can, but it looks confusing for me:
```
sh-4.4$ docker --help
Manage pods, containers and images

Usage:
  podman [options] [command]
  ..
```
