### ISSUE TITLE
Che proxy settings configmaps are ignored on OpenShift if cluster-wide proxy is enabled.

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22370]
### Is your enhancement related to a problem? Please describe

When running in an OpenShift cluster, proxy environment variables provisioned by the Che Operator in user namespaces are ignored due to the DevWorkspace Operator explicitly setting the HTTP_PROXY, etc. environment variables in workspace containers.

The Che Operator provisions a `che-proxy-settings` configmap (see `reconcileProxySettings()`) that is intended to be automounted as environment variables to all workspaces in the namespace. However, since the DevWorkspace Operator has its own logic for detecting cluster-wide proxy settings and sets environment variables within workspaces according to its own configuration, these env vars are ignored.

### Describe the solution you'd like

There are multiple ways we can resolve this issue:

1. Configure the Che-owned DevWorkspaceOperatorConfig to not set any proxy values, and take full responsibility for proxy configuration in workspace containers (see prerequisite PR https://github.com/devfile/devworkspace-operator/pull/1147)
2. Configure the Che-owned DevWorkspaceOperatorConfig to set values rather than reconciling the proxy-settings configmap to user namespaces (might be tricky to handle `noProxy`)
3. Stop provisioning the proxy settings configmap, as it is having no effect and nobody has complained about a broken configuration (unconfirmed?) 

### Describe alternatives you've considered

I think 1) above is likely the best solution here, but multiple choices would work (including ignoring the issue, potentially)

### Additional context

Related, old DevWorkspace Operator issue: https://github.com/devfile/devworkspace-operator/issues/841

**Comment by l0rd** [comment]
We had a downstream use case requiring the setup of a proxy for Che workspaces on a cluster with no cluster-wide proxy. But I don't remember any requests to have a specific Che proxy on a cluster with a cluster-wide proxy. Setting P2 for now.

**Comment by l0rd** [comment]
Also the title should probably be Eclipse _"Che proxy settings configmaps..."_

**Comment by amisevsk** [comment]
> We had a downstream use case requiring the setup of a proxy for Che workspaces on a cluster with no cluster-wide proxy.

This should still be fine, as the DWO-overriding-Che effect only occurs when a cluster-wide proxy is enabled. To my knowledge, it hasn't been an issue yet, but it might lead to some confusion in documentation (e.g. if you have a cluster-wide proxy enabled, and follow docs to configure additional domains in the CheCluster, those settings would be silently ignored for workspaces). I agree it's a P2 though.
