### ISSUE TITLE
"Restart Workspace from Local Devfile" fails on network restricted clusters

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22388]
### Describe the bug

![image](https://github.com/eclipse/che/assets/606959/a259796c-e62e-4e68-89ed-464b6a3f72a5)

### Che version

7.71@latest

### Steps to reproduce

Deploy Eclipse Che on a cluster that doesn't have access to github.io URLs.
Start a workspace and from VS Code select "restart from local devfile"
<img width="573" alt="image" src="https://github.com/eclipse/che/assets/606959/3940676e-34b6-4353-9d3d-1089af488e01">

### Expected behavior

The workspace should be restarted without errors (the internal plugin registry should be used by the devworkspace generator)

**Comment by l0rd** [comment]
Setting `area/devfile-registry` as I suspect that's related to the DevWorkspace generator

**Comment by RomanNikitenko** [comment]
We discussed it recently.
From the discussion I had understanding that generator needs `pluginRegistryUrl` only to get editor's content.
`Che-Code` uses the generator to get a new devfile context, we don't need editor's related part.

We pass `devfilePath` to the generator, `pluginRegistryUrl` parameter is optional. 
Does the generator really require `pluginRegistryUrl` to regenerate Devfile Context?
If no - I would say it's better to improve generator's logic to use `pluginRegistryUrl` only when it's really required.

**Comment by l0rd** [comment]
@RomanNikitenko the simplest looks to update CheCode to pass the pluginRegistryUrl parameter using the `CHE_PLUGIN_REGISTRY_INTERNAL_URL` env variable if it is set no?
cc @svor @ibuziuk

**Comment by l0rd** [comment]
> Update: I'm not sure that CHE_PLUGIN_REGISTRY_INTERNAL_URL url was used when we got that error, maybe CHE_PLUGIN_REGISTRY_URL was used instead...

We should confirm that. It makes sense that `CHE_PLUGIN_REGISTRY_URL` doesn't work but `CHE_PLUGIN_REGISTRY_INTERNAL_URL` should work.

**Comment by RomanNikitenko** [comment]
There is a pull request with possible solution: https://github.com/che-incubator/che-code/pull/268.
But I'm not able to test it as there is a problem with getting infrastructure with air-gap environment, see CRW-4873.
So, I've stopped progress for this issue.

@musienko-maxim 
does QE team has infrastructure for testing it?
if so - it would be helpful to test https://github.com/che-incubator/che-code/pull/268 as a solution for the current issue.

**Comment by dmytro-ndp** [comment]
@RomanNikitenko : did you try openshift-dev AWS account?
@tolusha could probably help with that.

**Comment by RomanNikitenko** [comment]
yes, thanks @tolusha and @dmytro-ndp I have an instance for testing

**Comment by RomanNikitenko** [comment]
I'm not able to reproduce the problem on the air-gap environment that I've got for testing.

I reviewed the corresponding part of the `devworkspace-generator` library and I see only one use case when `pluginRegistryUrl` is used: 
- to get editor's content when the generator gets `editorEntry` parameter ([please see here](https://github.com/eclipse-che/che-devfile-registry/blob/main/tools/devworkspace-generator/src/main.ts#L110)).

But [starting from Jun 13 we don't pass](https://github.com/che-incubator/che-code/pull/236) `editorEntry` parameter, the generator gets `editorContent` parameter instead. 

So, I think the issue is not actual anymore. 
But, just in case, we can merge [my PR](https://github.com/che-incubator/che-code/pull/268):
- it passes `CHE_PLUGIN_REGISTRY_INTERNAL_URL` to the generator
- it prepares axios instance to use certificates  

@l0rd wdyt?

**Comment by RomanNikitenko** [comment]
I've faced another error for the `quay.io/devspaces/code-rhel8:3.7` on air-gap env:

<img width="450" alt="image" src="https://github.com/eclipse/che/assets/5676062/ea5a3483-0687-42ac-91d1-ca48dbc2f712">

**Comment by RomanNikitenko** [comment]
Tested also the use case for an instance with proxy.
`quay.io/devspaces/code-rhel8:3.7` version of editor has an error:  
<img width="449" alt="image" src="https://github.com/eclipse/che/assets/5676062/f7d4947e-f009-424a-a539-58a8d1391b4e">

For the `quay.io/devspaces/code-rhel8:3.8` version `Restart Workspace from Local Devfile` works well.

**Comment by RomanNikitenko** [comment]
@l0rd 
From my point of view the bug is not actual anymore starting from the 3.8, please see https://github.com/eclipse/che/issues/22388#issuecomment-1739281060.

Can we somehow confirm that users still face the problem for the 3.8?
