### ISSUE TITLE
Announce replacement for Eclipse Mattermost - ECD Slack

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#22389]
### Summary

Hi,
the Mattermost server seems to be offline. I couldn*t find any information that it has been closed.
It is also still linked on the official website.
What is the current status of it?

Best Regards

**Comment by disaster37** [comment]
Same question here

**Comment by ibuziuk** [comment]
Hello, folks 
there is now a new `#forum-che` slack channel -  https://communityinviter.com/apps/ecd-tools/join-the-community 
Feel free to join!

We still need to update the website and send an email on the community mailing list

**Comment by nickboldt** [comment]
Related issues around release notifications:
* https://github.com/eclipse/che/issues/22551
* https://github.com/eclipse/che/issues/22549

**Comment by nickboldt** [comment]
> We still need to update the website and send an email on the community mailing list

@ibuziuk did this get done?
