### ISSUE TITLE
Wrong GitHub.com provider username when configured PAT

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#22386]
### Describe the bug

When configure Personal Access Token the github  username is setting wrong

### Che version

next (development version)

### Steps to reproduce

* Deploy Che from `next` version
* Configure secret PAT (on Dashboard or from `<user>`-che namespace)
* Go to `ConfigMaps` in the `<user>`-che namespace
* Open the `workspace-userdata-gitconfig-configmap`

### Expected behavior

Should be a correct git username 

### Runtime

OpenShift

### Screenshots

![che-next-workspace-userdata-gitconfig-configmap](https://github.com/eclipse/che/assets/5408906/98130c4f-387a-4f2c-8ae3-a295b62ba816)
![rhpd-personal-access-token-github](https://github.com/eclipse/che/assets/5408906/5e321940-32c7-4db8-a826-bd71a348cdfa)

### Installation method

chectl/next

### Environment

Linux

**Comment by vinokurig** [comment]
@artaleks9 
From the screenshot I see that the email param is `null`. Can you confirm that the email has not been setup for the GitHub user?

**Comment by artaleks9** [comment]
| _@artaleks9 What value do you expect in the user.name field?_
