### ISSUE TITLE
che-server resolves the unexisting repo with a default devfile

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22383]
### Describe the bug

Create a new workspace from the unexisting repo and a new workspace will be created without any errors.

### Che version

7.71@latest

### Steps to reproduce

1. Try to create a new workspace from the unexisting repo 
```
<che-server>#https://github.com/eclipse-che/che-dashboard888888888
```
2. A new workspace will be opened without any errors.

### Expected behavior

1. Try to create a new workspace from the unexisting repo 
```
<che-server>#https://github.com/eclipse-che/che-dashboard888888888
```
2. An error message should be appaired during creation.

### Runtime

minikube

### Screenshots

![Знімок екрана 2023-07-21 о 16 47 06](https://github.com/eclipse/che/assets/6310786/1a637a5f-046b-46bf-86f2-a8fc584160bc)
![Знімок екрана 2023-07-21 о 17 08 29](https://github.com/eclipse/che/assets/6310786/abec9e79-a11e-41cb-89c0-002980af4f1d)

### Installation method

chectl/latest

### Environment

macOS

**Comment by amisevsk** [comment]
This is a tricky one, as the same logic covers a) repositories that actually do not exist, and b) repositories that do exist but are inaccessible by the server.
