### ISSUE TITLE
How to start workspace with --disable-workspace-trust?

### ISSUE THREAD

**Issue by ddoan** [eclipse/che#22385]
### Summary

I'm looking at some upstream test code for `che-code` and noticed that it has optional start params like `--disable-workspace-trust` which we are interested in passing into our workspace running on k8s. I'm wondering how we would actually do that?

https://github.com/che-incubator/che-code/blob/main/code/test/integration/browser/src/index.ts#L141

**Comment by dkwon17** [comment]
Hello @ddoan I don't think this is easily possible today cc @azatsarynnyy @l0rd

**Comment by azatsarynnyy** [comment]
Che-Code [launch command](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh#L184) is in the entrypoint script. I think Che-Code can check if there's an environment variable (e.g. `VSCODE_SERVER_OPTIONS`) with the custom options provided. If it's present, custom options should be added to the launch command in a similar way as it's done specifically for [the `--default-workspace` option](https://github.com/che-incubator/che-code/pull/233/files). It requires a small contribution to the entrypoint script.

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy thanks for the tip. We'll try to see if we can get it to work based on that.

@ddoan feel free to contribute a PR to Che-Code once the proposed solution works for you.
