### ISSUE TITLE
How to create che-devfile-registry image with custom devfile yamls ? 

### ISSUE THREAD

**Issue by eyupdzhanY1** [eclipse/che#22397]
### Summary

I can only edit metadata in meta.yaml for each devfile, how to edit fields like cpu request and projects ?

**Comment by svor** [comment]
@eyupdzhanY1 each meta.yaml provides a link to the a repository with the sample. The repository contains devfile.yaml where you can edit everything you need.

So, if you need to add your own sample into the devfile registry, you have to add another meta.yaml with link to your sample which you can customize how you wish.

**Comment by eyupdzhanY1** [comment]
What if repo is private ? when i put ssh link to the repo, it can not resolve, and when i put https link it is not able to get raw devfile.
