### ISSUE TITLE
Incorrect error reported when Oauth fails "Dev file couldn't be found"

### ISSUE THREAD

**Issue by arunhari82** [eclipse/che#22409]
### Describe the bug

Incorrect error reported when Oauth fails "Dev file couldn't be found" and applies default cofiguration. This happens when integrating with Azure repos if an application has an incorrect configuration then when Oauth fails for third party application the message displayed is "Devfile couldn't be found" instead of actually display the oauth error that can lead to troubleshooting.

### Che version

7.71@latest

### Steps to reproduce

1) Miss a configuration that shows the how to enable organization settings on Azure devops repo

https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops

2) Create a workspace it shows as success with message "Dev File couldn't be found"

### Expected behavior

Shows the actual error of Oauth failing and also indicate the warning message that Devfile is not found instead of showing as green and successful.

### Runtime

OpenShift

### Screenshots

![bug-che-2](https://github.com/eclipse/che/assets/73549783/45af9bf0-134b-4c59-a070-9d5e7697775e)

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by vinokurig** [comment]
The `Azure DevOps` provider doesn't return any specific error if the `Third-party application via OAuth` slider turned off. There is no way to distinguish the case when there is no devfile in the repository or the slider is turned off.

**Comment by tolusha** [comment]
What does Auzure DevOps return then? Any specific error code?

**Comment by tolusha** [comment]
Maybe che-server can return a better error message anyway.

**Comment by rafaeltuelho** [comment]
> Maybe che-server can return a better error message anyway.

Maybe in this case, the message could be a couple of hints asking the user to double-check the required oAuth settings?!
