### ISSUE TITLE
What does this error mean? Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope

### ISSUE THREAD

**Issue by ddoan** [eclipse/che#22400]
### Summary

I sometimes get this toast pop-up in my workspace and I don't know if I can prevent it somehow. It will confuse our users.

<img width="469" alt="Screenshot 2023-07-26 at 10 47 44 AM" src="https://github.com/eclipse/che/assets/993727/607bde01-bc0e-481b-b6e6-1b1e98bb9df4">

### Relevant information

Happens for example when I click around the welcome panel.

**Comment by yujiri8** [comment]
I see the same error regularly in firefox.
