### ISSUE TITLE
SQL errors in Che Plugin Registry publish to npmjs during release

### ISSUE THREAD

**Issue by SDawley** [eclipse/che#22405]
### Is your task related to a problem? Please describe

During the release I noticed SQL and spring errors, though they didn't stop or fail the release. 

7.72.0 error: https://github.com/eclipse-che/che-plugin-registry/actions/runs/5682971350/job/15402548878#step:17:471

Looking at last release there were similar errors, but I missed it because they were less verbose.
https://github.com/eclipse-che/che-plugin-registry/actions/runs/5536837773/job/14997334699#step:17:527

Spoke to @svor and decided this was something to look into for the next release.

### Describe the solution you'd like

Solution: Ideally npmjs publish should run without errors.

**Comment by svor** [comment]
fixed by https://github.com/eclipse-che/che-plugin-registry/pull/1776
