### ISSUE TITLE
Move che-docs and che-website out of git.eclipse.org

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22403]
### Is your task related to a problem? Please describe

Today a Jenkins job copies the content from [che-docs](https://github.com/eclipse-che/che-docs/tree/publication) and [che-website](https://github.com/eclipse-che/che-website) to [eclipse foundation Gerrit repo](https://git.eclipse.org/c/www.eclipse.org/che.git/). The foundation use that to publish Eclipse Che [website](https://eclipse.dev/che/).

Eclipse foundation `git.eclipse.org` will be shutdown so we need to find an alternative (**[original issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1759)**).

### Describe the solution you'd like

We should publish the docs and website in a `eclipse-che/che-website` branch.

**Comment by deerskindoll** [comment]
eclipse foundation ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4199

**Comment by ibuziuk** [comment]
the foundation ticket is https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1759 
@l0rd left a comment in the ^ since we need some guidance from what @deerskindoll should we start with

**Comment by ibuziuk** [comment]
@deerskindoll can we close it or more follow up is needed?

**Comment by deerskindoll** [comment]
we can close this issue
