### ISSUE TITLE
Replace or Remove Mattermost notification from Github Actions

### ISSUE THREAD

**Issue by SDawley** [eclipse/che#22407]
### Is your task related to a problem? Please describe

Release actions are currently all failing at the Mattermost notification stage since mattermost is no more.

Example: https://github.com/eclipse/che/actions/runs/5682971423/job/15403670412

### Describe the solution you'd like

For now, we should remove the stage from all relevant github actions. Once we decide on a replacement we can update them again.

**Comment by nickboldt** [comment]
some ideas for possible replacements:
* post to RH External Slack the same way we did to MM (presumably using a similar GH action + auth token, like https://github.com/marketplace/actions/slack-notify ?)
* log events to che-release repo in a single replaced-with-every release release.log.txt file
* log events to che-release repo, but put tag the repo at the start of the release, and put the release.log.txt in the 7.yy.x branch so we have unique histories for each release

**Comment by SDawley** [comment]
Update:
Planning on using https://github.com/slackapi/slack-github-action to replace mattermost. Testing using the #eclipse-che-ci channel in slack.

**Comment by SDawley** [comment]
I've made a che-release-bot for the ECD-tools slack which I'll use to test notifications. If we also want to post to the redhat-internal slack we'll need to get that approved.
