### ISSUE TITLE
checl deploy fails devworkspace-controller Pods get Stuck in Pending State

### ISSUE THREAD

**Issue by Mbd06b** [eclipse/che#22419]
### Describe the bug

Description
The devworkspace-controller pods are stuck in the "Pending" state and are not progressing to the "Running" state, the chectl:deploy step get's stuck on the dev-workspace operator step, either download or wait, and eventually fails from a timeout. 

The issue has been persistent across multiple pods in the devworkspace-controller namespace. There are no logs or events for the pending pods, and the pods' descriptions have not revealed any evident issues I've only been able tot find events noted from other pods in the devworkspace-controller namespace: (kubectl get events -n devworkspace-controller) 

 The Kubernetes cluster is running on MicroK8s, and this issue is blocking the proper functionality of the Eclipse Che deployment.

Note:  I've tried deploy  variations like  -p k8s platform, and specified microk8s hostpath-storage (the microk8s default)),  and I've encountered the similar issues with the devworkspace-controller. 

```
$chectl server:deploy -b code.example.com -p microk8s --che-operator-cr-patch-yaml=checluster-values.yaml  --workspace-pvc-storage-class-name=openebs-jiva-csi-default    --skip-cert-manager
  --k8spoderrorrechecktimeout=600000 --k8spodreadytimeout=600000 --k8spodwaittimeout=600000

› Current Kubernetes context: 'microk8s'
  ✔ Verify Kubernetes API...[1.27]
  ✔ MicroK8s preflight checklist
    ✔ Verify if kubectl is installed...[OK]
    ✔ Verify if microk8s is installed...[OK]
    ✔ Verify if microk8s is running...[OK]
    ✔ Verify if microk8s ingress addon is enabled...[Enabled]
    ✔ Verify if microk8s storage addon is enabled...[Enabled]
  ✔ Create Namespace eclipse-che...[Exists]
  ↓ Install Cert Manager v1.8.2 [skipped]
  ✔ Start following Eclipse Che installation logs...[OK]
  ❯ Deploy Eclipse Che operator
    ❯ Install Dev Workspace operator
      ✔ Create Namespace devworkspace-controller...[Exists]
      ✔ Create Dev Workspace operator resources...[Created]
      ✖ Wait for Dev Workspace operator ready
        → ERR_TIMEOUT: Timeout set to pod ready timeout 60000
      Create ServiceAccount che-operator
      Create RBAC
      Create Certificate che-operator-serving-cert
      Create Issuer che-operator-selfsigned-issuer
      Create Service che-operator-service
      Create CRD checlusters.org.eclipse.che
      Waiting
      Create Deployment che-operator
      Eclipse Che Operator pod bootstrap
      Create ValidatingWebhookConfiguration org.eclipse.che
      Create MutatingWebhookConfiguration org.eclipse.che
      Create CheCluster Custom Resource
    Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000 See details: 
    /home/user/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1691338939062.

error.log:
```

Requested Assistance
Help in understanding why the devworkspace-controller Pods are stuck in Pending.
Guidance on retaining logs for Pods that might get deleted.
Any specific configuration or prerequisites for running devworkspace-controller in a MicroK8s environment.

### Che version

7.72@latest

### Steps to reproduce

Setup microk8s:

Note: openebs is installed, and provides a few storageclass options: $kubectl get storageclass --all-namespaces
NAME                                 PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-hostpath                     openebs.io/local       Delete          WaitForFirstConsumer   false                  5d
openebs-device                       openebs.io/local       Delete          WaitForFirstConsumer   false                  5d
openebs-jiva-csi-default (default)   jiva.csi.openebs.io    Delete          Immediate              true                   5d
microk8s-hostpath (default)          microk8s.io/hostpath   Delete          WaitForFirstConsumer   false                  7h15m

1.Deploy Eclipse Che using chectl, including the devworkspace-controller component.

```
$chectl server:deploy -b code.example.com -p microk8s --che-operator-cr-patch-yaml=checluster-values.yaml  --workspace-pvc-storage-class-name=openebs-jiva-csi-default    --skip-cert-manager
  --k8spoderrorrechecktimeout=600000 --k8spodreadytimeout=600000 --k8spodwaittimeout=600000
```

Observe that the devworkspace-controller pods are stuck in the "Pending" state using the command kubectl get pods -n devworkspace-controller.

$ kubectl get pods -o wide -n devworkspace-controller
NAME                                               READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
devworkspace-controller-manager-6f9975f5fd-vfd2h   0/2     Pending   0          4h38m   <none>   <none>   <none>           <none>
devworkspace-controller-manager-6f9975f5fd-7b6wp   0/2     Pending   0          3h52m   <none>   <none>   <none>           <none>

Check the events in the devworkspace-controller namespace using kubectl get events -n devworkspace-controller to find warnings related to failed container restarts and failed volume mounts.
Attempt to retrieve logs for the pending pods using kubectl logs <pod-name> -n devworkspace-controller, but observe that no logs are available.
Investigate related configurations and logs, including the MicroK8s setup (using dqlite) and storage class descriptions, but find no clear root cause.

### Expected behavior

devworkspace-controller pods should start, allowing the chectl installer to complete. 

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2023-08-06T16:23:24.854Z Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000 See details: /home/matthew/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1691338939062.
2023-08-06T16:23:24.854Z     at Object.newError (~/.local/share/chectl/client/7.72.0/lib/utils/utls.js:37:19)
2023-08-06T16:23:24.854Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.72.0/lib/utils/command-utils.js:53:19)
2023-08-06T16:23:24.854Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.72.0/lib/commands/server/deploy.js:82:44)


```
kubectl get events -n devworkspace-controller
LAST SEEN   TYPE      REASON        OBJECT                                                 MESSAGE
2m18s       Normal    Pulling       pod/devworkspace-controller-manager-6f9975f5fd-9k77z   Pulling image "quay.io/devfile/devworkspace-controller:v0.22.0"
44s         Warning   FailedMount   pod/devworkspace-webhook-server-7df669b449-fj75r       MountVolume.SetUp failed for volume "kube-api-access-8ngmc" : failed to fetch token: serviceaccounts "devworkspace-webhook-server" not found
39s         Warning   BackOff       pod/devworkspace-controller-manager-6f9975f5fd-9k77z   Back-off restarting failed container devworkspace-controller in pod devworkspace-controller-manager-6f9975f5fd-9k77z_devworkspace-controller(2a508ea3-b34f-4a32-a4dd-85a680c92022)
```


### Additional context

Kubernetes Version: MicroK8s (v1.27.4)
Operating System: Ubuntu 22 LTS

microk8s is running
high-availability: no
  datastore master nodes: 192.168.86.100:19001
  datastore standby nodes: none
addons:
  enabled:
    openebs              # (community) OpenEBS is the open-source storage solution for Kubernetes
    cert-manager         # (core) Cloud native certificate management
    community            # (core) The community addons repository
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    rbac                 # (core) Role-Based Access Control for authorisation
    storage              # (core) Alias to hostpath-storage add-on, deprecated
```

Pod Description:  
[devws_pods_description.txt](https://github.com/eclipse/che/files/12270422/devws_pods_description.txt)

**Comment by ibuziuk** [comment]
@tolusha could you please take a look? not sure what is the state of `microk8s`

**Comment by tolusha** [comment]
Could you try if it works on a fresh cluster?
```
microk8s enable cert-manager
kubectl create namespace devworkspace-controller
kubectl apply -f https://raw.githubusercontent.com/devfile/devworkspace-operator/v0.22.0/deploy/deployment/kubernetes/combined.yaml
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=devworkspace-controller  -n devworkspace-controller --timeout=120s
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=devworkspace-webhook-server  -n devworkspace-controller --timeout=120s
```
