### ISSUE TITLE
Migrate to Node.js 18 version for the Che-Code

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22426]
### Is your task related to a problem? Please describe

VS Code [is migrating ](https://github.com/microsoft/vscode/blob/main/build/npm/preinstall.js#L12)to the Node.js 18 version.

### Describe the solution you'd like

We need provide some adaptation on the Che-Code side

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/che-incubator/che-code/pull/265
