### ISSUE TITLE
Automatic git-rebase is broken for the Che-Code

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22428]
### Describe the bug

We have automatic git-rebase for the Che-Code, it's broken at the moment:
```
jq: error: Could not open file .rebase/replace/code/build/lib/mangle/index.js.json: No such file or directory
```
<img width="794" alt="Screenshot 2023-08-09 at 08 15 01" src="https://github.com/eclipse/che/assets/5676062/154dfbc3-8124-4fa2-a731-5aa8ccbfa42b">

### Che version

next (development version)

### Steps to reproduce

See https://github.com/che-incubator/che-code#fixing-the-rebase-insiders-workflow

### Expected behavior

Automatic git-rebase works for the Che-Code

### Additional context

The changes were introduced within https://github.com/che-incubator/che-code/pull/252/commits/260495b5df75377e104a09eac595b3268b8440cb

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
Recently you provided some logic related to the automatic git-rebase for the mangler logic.
It works incorrectly, see an error in the issue, could you take a look?

**Comment by azatsarynnyy** [comment]
Thanks, Roman for noticing it. Provided https://github.com/che-incubator/che-code/pull/266

**Comment by RomanNikitenko** [comment]
Thanks, I'm going to update [my PR](https://github.com/che-incubator/che-code/pull/265) when your fix is merged
