### ISSUE TITLE
Require support with Deploying Eclipse che on Azure

### ISSUE THREAD

**Issue by sharmila1310** [eclipse/che#22420]
Hi Team,

I have been trying with eclipse-che deployment on Azure for about a month now.  Need support with the same.

**Comment by ibuziuk** [comment]
@sharmila1310 hello, `Installing Eclipse Che on the Azure Kubernetes Service (AKS)` blog post could be useful -  https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html 

cc: @karatkep

**Comment by ibuziuk** [comment]
@sharmila1310 feel free to join Eclipse Che Community Call on Monday, September 18th and add your topic to the agenda. More details about the community call / agenda can be found on the `che-dev` [1] mailing list. 

[1] https://www.eclipse.org/lists/che-dev/msg04473.html

**Comment by ibuziuk** [comment]
Closing in favor of https://github.com/eclipse/che/issues/22610
