### ISSUE TITLE
"Error while fetching extensions. Server returned 500" in "POPULAR" section of extensions view in VSCode Editor

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22439]
### Describe the bug

"Error while fetching extensions. Server returned 500" message in "POPULAR" section:
![Screenshot from 2023-08-17 16-05-48](https://github.com/eclipse/che/assets/1197777/5b3419b0-ae28-4bb8-a4df-6b9b86f25704)

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che Next.
2. Create Apache Camel K workspace and open workspace.
3. Go to `VSCode Editor > Extensions View`.

### Expected behavior

There should be list non-empty list of popular extensions.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context

[apache-camel-k.devfile.yaml.txt](https://github.com/eclipse/che/files/12370106/apache-camel-k.devfile.yaml.txt)
[apache-camel-k.workspace.yaml.txt](https://github.com/eclipse/che/files/12370107/apache-camel-k.workspace.yaml.txt)

**Comment by vitaliy-guliy** [comment]
Something wrong with openvsix registry

![Screenshot from 2023-08-17 16-55-54](https://github.com/eclipse/che/assets/1655894/2ba38278-02af-4ce3-8778-7f97c0e6a785)

**Comment by dmytro-ndp** [comment]
The root cause of issue is that https://open-vsx.org/ is broken at the moment:
![Screenshot from 2023-08-17 17-08-09](https://github.com/eclipse/che/assets/1197777/bcf9835b-9050-4f5c-8e3b-d2a7614cf5e1)


So, it was an expected behavior.
