### ISSUE TITLE
Error: Invalid character in header content ["Authorization"] when sign in using GitHub

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22433]
### Describe the bug

User gets `Error: Invalid character in header content ["Authorization"]` when sign in using GitHub. 

It happens when:
- a user has more than 1 personal access tokens
plus
- a user uses `Git Clone` operation, for example.

The cause of the problem:  `GithubService` supports only 1 token.

### Che version

next (development version)

### Steps to reproduce

It happens when a user uses `Git Clone` operation, for example && there is > 1 personal access tokens.
The simplest way to reproduce it:
1. Start a workspace using **gitlab** repo, like: https://gitlab.com/rnikitenko1/web-nodejs-sample
2. Stop the workspace ^.
3. Start a workspace using **github** repo, like: https://github.com/che-samples/web-nodejs-sample
4. `F1` => `Git Clone`

But the cause of the problem: `GithubService`  parses a token incorrectly when there are few tokens, so I think other use cases also present.
### Expected behavior

At the moment `GithubService` reads `/.git-credentials/credentials` file and expects that the file contains only 1 token. 
`GithubService` parse the token incorrectly if there are few tokens. For example, I saw the following value of the parsed token: 
```
[info] GitHubAuthProvider: using @gitlab.com https://oauth2: to create a new session
```

I think `GithubService` should support multiple tokens.
At least `GithubService` could 
- read all tokens
- filter out `gitlab` tokens 
- use a `github` token for Github operations

To be honest, I have no idea what is correct behaviour if there are few `github` tokens - just use the first one? 

Another option could be: maybe `GithubService` should read a token directly from a secret? This way we could analize labels and annotations of the secret.

### Additional context

I reproduced it on the dogfooding instance

**Comment by RomanNikitenko** [comment]
Let's say:
- user has 2 (or even more) `github` tokens in the `/.git-credentials/credentials` file
- user run `F1` => `Git Clone` command
- `GitHubAuthProvider` asks `Che-API` for a token to create a session

which token `Che-API` should return?

Maybe we should provide a command to the Command Palette that will allow to select a token for the current workspace.
The token will be used by default for the current workspace.

@l0rd @vinokurig @azatsarynnyy @vitaliy-guliy  
any thoughts, ideas are welcome!

**Comment by azatsarynnyy** [comment]
> Maybe we should provide a command to the Command Palette that will allow to select a token for the current workspace.

... and storing the user's choice as a VS Code setting. Good idea, I think.

**Comment by RomanNikitenko** [comment]
The idea from @l0rd is:
- we could check `remote` for the current project and return the corresponding token
- it doesn't work for the `Device Authentication flow` token, but for other use cases it should work well

**Comment by vitaliy-guliy** [comment]
I easily cloned a project by following sections in `Steps to reproduce`

![Screenshot from 2023-09-28 14-02-53](https://github.com/eclipse/che/assets/1655894/443ff4f3-d845-4fa0-845b-d010d8e08a26)

What should I pay attention to?

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
please provide content of the `/.git-credentials/credentials` file

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy please provide content of the `/.git-credentials/credentials` file

https://oauth2:5761...something_here...f804a69e@gitlab.com
https://oauth2:gho_d...something_here...354@github.com

**Comment by RomanNikitenko** [comment]
thank you!

well, I guess, existing session is used for git-related operations, so I propose to sign out first from the github and try again to clone a project - so a new session should be created using your credentials from the `/.git-credentials/credentials` file.

**Comment by vitaliy-guliy** [comment]
@RomanNikitenko 
I think we can close this issue as it was solved by your PR https://github.com/che-incubator/che-code/pull/260
I have just tested it and didn't find any issues

![Screenshot from 2023-10-31 12-06-35](https://github.com/eclipse/che/assets/1655894/fae47264-a5b0-488c-8eb9-f33884e9a315)
