### ISSUE TITLE
Eclipse Che dashboard is giving not opening with 404 error after keycloak authentication

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22443]
### Describe the bug

Tried to install Eclipse Che in GKE with Keycloak at OIDC provider.

Please help
DK 

### Che version

7.72@latest

### Steps to reproduce

Steps:
1. Deployed NGINX ingress controller
2. Deployed Keycloak with that ingress controller in http mode
3. Tried to deploy eclipse che with chectl utility
4. Deployment of eclipse che was clean without error. 
5. While testing the eclipse che is presenting the keycloak for authentication, after successful authentication, the redirect to eclipse che is not working fine. It is giving 404 error and dashboard not opening.
6. I am following the below command for the deployment:

chectl server:deploy --platform=k8s --che-operator-cr-patch-yaml che-operator-cr-patch.yaml --domain gosimplyee.life --k8spodreadytimeout=500000 --k8spoderrorrechecktimeout=500000 --installer=operator --debug -n che

che-operator-cr-patch.yaml  is as below:

kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    domain: gosimplyee.life
    annotations:
        kubernetes.io/ingress.class: nginx
    auth:
      oAuthClientName: "che-client-id"
      oAuthSecret: ""
      identityProviderURL: ""

### Expected behavior

Eclipse Che dashboard not opening.

whereas devfile , plug-in registries are openings fine

### Runtime

other (please specify in additional context)

### Screenshots

GKE

### Installation method

chectl/latest

### Environment

GCE

### Eclipse Che Logs

```shell
n upstream response is buffered to a temporary file /tmp/nginx/proxy-temp/0000000012 while reading upstream, client: 10.76.0.1, server: gosimplyee.life, request: "GET /dashboard/monaco.44c72f8b45251763d459.js HTTP/1.1", upstream:
```

**Comment by tolusha** [comment]
I hope it can help you
https://github.com/eclipse/che/issues/21049#issuecomment-1067776895

**Comment by debkantap** [comment]
Hello, Thanks for the response. However I am able to integrate with Keycloak and Che and while redirecting to che dashboard after authentication by keycloak getting 404 error:

"10.76.0.1 - - [22/Aug/2023:09:07:44 +0000] "GET /dashboard HTTP/1.1" 404 19 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/277.0.555192628 Mobile/15E148 Safari/604.1" 4340 0.011 [che-che-gateway-8080] [] 10.76.0.59:8080 19 0.011 404 70bf41cc15ec343242e004cd2d7eb61f"

I googled and found two links are close to my issue:

1. https://stackoverflow.com/questions/68111471/getting-404-error-on-eclipse-che-dashboard-hosted-on-gke
2. https://github.com/eclipse/che/issues/21288

In first link it says "The fix is fixing Ingress path from /dashboard/* to /dashboard/".  but not able to figure out where I need to do this.

Can you pls help.

Thanks & Regards
DK
