### ISSUE TITLE
need jdk 15 or openjdk 17 version  maven image

### ISSUE THREAD

**Issue by tathagata1977** [eclipse/che#22444]
### Summary

Hello Team, Need help , at present we are using quay.io/eclipse/che-java11-maven:7.13.1 image, but we need jdk 15 or openjdk 17 version . I need a Image of this. Is that available ?

### Relevant information

While build process we have dependency and we are getting error, 
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mydas: Fatal error compiling: error: invalid target release: 15 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

so this section of code has dependencies over jdk 15 so we are searching for a image which can support our code base.
Thanks

**Comment by tolusha** [comment]
@tathagata1977 
You can prepare your own image with all needed tools and use it.

**Comment by tathagata1977** [comment]
Thanks @tolusha . I really do not have much idea on this. 
is there any help or is any one using the image ?  if yes I need that link. I search on quay.io could not find it. 
Thanks

**Comment by tolusha** [comment]
Please, try this one `docker.io/maven:3.8.3-openjdk-17`

**Comment by tathagata1977** [comment]
Thanks @tolusha , will try and let you know. 
Thanks for helping.

**Comment by tathagata1977** [comment]
Hello @tolusha ,
I use this image but when ever I am replacing the image 'quay.io/eclipse/che-java11-maven:7.13.1' with other like 'docker.io/maven:3.8.3-openjdk-17' the workspace is not coming up, I am facing below error # 
"Failed to run the workspace: "The following containers have terminated: maven: reason = 'Error', exit code = 1, message = 'null'" "
The detail log is in below # 
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 1.26814056s

Created container che-plugin-metadata-broker-v3-4-0

Started container che-plugin-metadata-broker-v3-4-0

Starting plugin metadata broker

All plugin metadata has been successfully processed

List of plugins and editors to install

- redhat/java/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...

- redhat/vscode-xml/latest - XML Language Support by Red Hat

- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.

- vscode/typescript-language-features/latest - Provides rich language support for JavaScript and TypeScript.

- redhat/vscode-yaml/latest - YAML Language Support by Red Hat, with built-in Kubernetes syntax support

- eclipse-cdt/cdt-vscode/latest - CDT VS Code Extension for C/C++ Developers

- bmewburn/vscode-intelephense-client/latest - PHP code intelligence for Visual Studio Code

- eclipse/che-theia/latest - Eclipse Theia

AttachVolume.Attach succeeded for volume "csi-13830953-e441-4faf-a3f4-92510a36a7dd"

Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:188ee7a9bf2a69b707644a8b6923fd683b7072c473a26557204740eb977c0ab0"

Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:188ee7a9bf2a69b707644a8b6923fd683b7072c473a26557204740eb977c0ab0" in 1.280209274s

Created container remote-runtime-injectort5c

Started container remote-runtime-injectort5c

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 1.306871015s

Created container che-plugin-artifacts-broker-v3-4-0

Started container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Processing plugin redhat/java/latest

Installing plugin extension 1/3

Plugin already downloaded

Installing plugin extension 2/3

Plugin already downloaded

Installing plugin extension 3/3

Plugin already downloaded

Processing plugin redhat/vscode-xml/latest

Installing plugin extension 1/1

Plugin already downloaded

Processing plugin redhat/vscode-yaml/latest

Installing plugin extension 1/1

Plugin already downloaded

Processing plugin vscode/typescript-language-features/latest

Installing plugin extension 1/1

Plugin already downloaded

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Plugin already downloaded

Processing plugin eclipse-cdt/cdt-vscode/latest

Installing plugin extension 1/3

Plugin already downloaded

Installing plugin extension 2/3

Plugin already downloaded

Installing plugin extension 3/3

Plugin already downloaded

Processing plugin bmewburn/vscode-intelephense-client/latest

Installing plugin extension 1/1

Plugin already downloaded

Saving log of installed plugins

All plugin artifacts have been successfully downloaded

Pulling image "quay.io/eclipse/che-jwtproxy:0.10.0"

Successfully pulled image "quay.io/eclipse/che-jwtproxy:0.10.0" in 1.736297885s

Created container che-jwtproxyfw080sr7

Started container che-jwtproxyfw080sr7

Pulling image "docker.io/maven:3.8.3-openjdk-17"

Successfully pulled image "docker.io/maven:3.8.3-openjdk-17" in 1.313584839s

Created container maven

Started container maven

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a"

Successfully pulled image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a" in 1.767255753s

Created container vscode-javaien

Started container vscode-javaien

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a"

Successfully pulled image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a" in 1.758667434s

Created container vscode-xmlyqv

Started container vscode-xmlyqv

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:276765cf3e6f54ae3bd70325132ef0b79019798afc081c5ff6750767995df0c3"

Failed to run the workspace: "The following containers have terminated: maven: reason = 'Error', exit code = 1, message = 'null'".
The DevFile that I create to prepare the workspace is 
apiVersion: 1.0.0
metadata:
  name: Mydas
attributes:
  persistVolumes: 'true'
projects:
  - name: codebase
    source:
      startPoint: Mydas-6.06.08
      location: 'https://gitlab.cataneo.de/applications/codebase.git'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 2Gi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'docker.io/maven:3.8.3-openjdk-17'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: bmewburn/vscode-intelephense-client/latest
    type: chePlugin
commands:
  - name: codebase
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
any additional help would be greatly appreciated here .
Thanks

**Comment by tathagata1977** [comment]
This is my devfile code # 
apiVersion: 1.0.0
metadata:
  name: Mydas
attributes:
  persistVolumes: 'true'
projects:
  - name: codebase
    source:
      startPoint: Mydas-6.06.08
      location: 'https://................../codebase.git'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 2Gi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven@sha256:cc9e3cb0b00357ed118c130ce9f8e8e4724c718f8e2a1bd294f81696116d7b32'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: bmewburn/vscode-intelephense-client/latest
    type: chePlugin
commands:
  - name: codebase
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven

**Comment by tathagata1977** [comment]
@tolusha , please refer detail error log 

Successfully assigned admin-dev/workspacequhebpkxi3pjgkg6.che-plugin-broker to 10.0.10.203

Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 1.248202324s

Created container che-plugin-metadata-broker-v3-4-0

Starting plugin metadata broker

Started container che-plugin-metadata-broker-v3-4-0

All plugin metadata has been successfully processed

List of plugins and editors to install

- redhat/java/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...

- redhat/vscode-xml/latest - XML Language Support by Red Hat

- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.

- vscode/typescript-language-features/latest - Provides rich language support for JavaScript and TypeScript.

- redhat/vscode-yaml/latest - YAML Language Support by Red Hat, with built-in Kubernetes syntax support

- eclipse-cdt/cdt-vscode/latest - CDT VS Code Extension for C/C++ Developers

- bmewburn/vscode-intelephense-client/latest - PHP code intelligence for Visual Studio Code

- eclipse/che-theia/latest - Eclipse Theia

Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:188ee7a9bf2a69b707644a8b6923fd683b7072c473a26557204740eb977c0ab0"

Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:188ee7a9bf2a69b707644a8b6923fd683b7072c473a26557204740eb977c0ab0" in 1.293459107s

Created container remote-runtime-injectorxo2

Started container remote-runtime-injectorxo2

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 1.305501901s

Created container che-plugin-artifacts-broker-v3-4-0

Started container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin redhat/java/latest

Installing plugin extension 1/3

Downloading plugin from https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.82.0-369.vsix

Installing plugin extension 2/3

Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix

Installing plugin extension 3/3

Downloading plugin from https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix

Processing plugin redhat/vscode-xml/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/v069c634/vscode-xml-0.17.0.vsix

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

Processing plugin vscode/typescript-language-features/latest

Installing plugin extension 1/1

Downloading plugin from https://open-vsx.org/api/vscode/typescript-language-features/1.49.3/file/vscode.typescript-language-features-1.49.3.vsix

Processing plugin redhat/vscode-yaml/latest

Installing plugin extension 1/1

Downloading plugin from https://open-vsx.org/api/redhat/vscode-yaml/0.14.0/file/redhat.vscode-yaml-0.14.0.vsix

Processing plugin eclipse-cdt/cdt-vscode/latest

Installing plugin extension 1/3

Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/cdt-vscode/cdt-vscode-0.0.7-75cf95.vsix

Installing plugin extension 2/3

Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-clangd/vscode-clangd-0.1.5-562d00.vsix

Installing plugin extension 3/3

Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/cdt-gdb-vscode/cdt-gdb-vscode-0.0.91-2cbbb8.vsix

Processing plugin bmewburn/vscode-intelephense-client/latest

Installing plugin extension 1/1

Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-intelephense/vscode-intelephense-client-1.5.4.vsix

Saving log of installed plugins

All plugin artifacts have been successfully downloaded

Pulling image "quay.io/eclipse/che-jwtproxy:0.10.0"

Successfully pulled image "quay.io/eclipse/che-jwtproxy:0.10.0" in 1.688451743s

Created container che-jwtproxy7cdqblrm

Started container che-jwtproxy7cdqblrm

Pulling image "docker.io/maven:3.8.3-openjdk-17"

Successfully pulled image "docker.io/maven:3.8.3-openjdk-17" in 1.341230033s

Created container maven

Started container maven

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a"

Successfully pulled image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a" in 1.771292791s

Created container vscode-javaexr

Started container vscode-javaexr

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a"

Successfully pulled image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a" in 1.713314236s

Created container vscode-xml13u

Started container vscode-xml13u

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:276765cf3e6f54ae3bd70325132ef0b79019798afc081c5ff6750767995df0c3"

Failed to run the workspace: "The following containers have terminated: maven: reason = 'Error', exit code = 1, message = 'null'"

**Comment by tolusha** [comment]
You use quite old Che version.
Try to build you own image by replacing java version in this Dockerfile
https://github.com/eclipse-che/che-plugin-registry/tree/7.63.x/sidecars/java

**Comment by tathagata1977** [comment]
@tolusha ,
Yes I know I force to use this version as our Che environment running on OKE. 
is that because of the Che Version you are saying it is not working ?
Thanks

**Comment by tathagata1977** [comment]
We are using 7.41.2 version which is compatible with OKE. 
So what I understand with this version it is not possible to use openjdk17 ? 
In the log file I observed that docker.io/maven:3.8.3-openjdk-17 is downloaded and container created. 
I remove Che plugins but I am still getting the error.  
Also not sure how own created image will be helpful here ? 
Thanks.

**Comment by tolusha** [comment]
It is possible to use java 17 with any Che version.
It is a matter of building an appropriate image.
The idea is that container should run endlessly otherwise you will get the error above.
That's why I recommend to try  https://github.com/eclipse/che/issues/22444#issuecomment-1687765299

**Comment by tathagata1977** [comment]
For now modifying the target dependencies of POM file to jdk 11 we are able to build successfully the monolith code base.
Thanks for helping.
