### ISSUE TITLE
SmokeTests fails against Eclipse Che next version

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22450]
### Describe the bug

SmokeTests fails against Eclipse Che next version

### Che version

next (development version)

### Steps to reproduce

Jenkins job https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Che/job/ocp/job/Disconnected/job/periodic-eclipse-che-tests/

### Expected behavior

All tests passed

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
1) The SmokeTest userstory
04:53:52         Create workspace from factory:http://<redacted>/che-incubator/quarkus-api-example/raw/main/devfile.yaml
04:53:52           Check a project folder has been created:
04:53:52  [0m[31m     Error: No section with title 'quarkus-api-example' found[0m[90m
04:53:52        at ViewContent.<anonymous> (/tmp/e2e/node_modules/monaco-page-objects/out/components/sidebar/ViewContent.js:56:23)
04:53:52        at Generator.next (<anonymous>)
04:53:52        at fulfilled (/tmp/e2e/node_modules/monaco-page-objects/out/components/sidebar/ViewContent.js:5:58)
04:53:52        at runMicrotasks (<anonymous>)
04:53:52        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional context

SmokeTest passed been run against DS 3.8.0 (Eclipse Che 7.72.x): https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DevSandbox/job/sandbox-test/7678/console

**Comment by ibuziuk** [comment]
Closing as done
