### ISSUE TITLE
Dashboard should respect `registry.devfile.io` deployed on the cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22454]
### Is your task related to a problem? Please describe

If `registry.devfile.io` is deployed on the cluster [1], then dashboard try to read index file by path `/devfiles/index.json` instead of `/index`. For instance see [2]

[1] https://github.com/devfile/registry-operator
[2] https://registry.devfile.io/index

### Describe the solution you'd like

Operator configures dashboard with devfile registry url and path to read index file via environment variables. 

### Describe alternatives you've considered

Dashboard should try to read index file from both paths to figure out the proper path.

**Comment by ibuziuk** [comment]
@tolusha can we close the issue?

**Comment by tolusha** [comment]
No, we still need changes on dashboard side to support custom devfile registry deployed on the cluster.
