### ISSUE TITLE
AzureDevops Git repos with white spaces in the URL

### ISSUE THREAD

**Issue by rafaeltuelho** [eclipse/che#22458]
### Describe the bug

When creating a workspace using a git url with white spaces from Azure Devops git repos, we get a fail.

For instance: 
https://rsoares-demos@dev.azure.com/rsoares-demos/Openliberty%20on%20Openshift/_git/Openliberty%20on%20Openshift

 

### Che version

7.73@latest

### Steps to reproduce

1. Create a Git repo with white spaces in its name on Azure Devops.
2. From Devsapces try to create a new workspace from this git repo
3. you should see an error

### Expected behavior

Devspaces should be able to parse/handle the git URL properly

### Runtime

OpenShift

### Screenshots

![image](https://github.com/eclipse/che/assets/39063/1c68adb9-1e60-41dd-8b21-1bb90c2cffbe)

### Installation method

OperatorHub

### Environment

Linux, macOS

**Comment by AObuchow** [comment]
I'd imagine the[ Azure Devops regex](https://github.com/eclipse-che/che-server/blob/ce6ed7e9c03e901c4b8c19a1903c1f04887641db/wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParser.java#L53-L62) in Che Server needs to be updated to resolve this issue.
