### ISSUE TITLE
Failed to deploy Eclipse Che on `arm64` platform

### ISSUE THREAD

**Issue by moonbse** [eclipse/che#22467]
### Summary

I am following this guide to install Che on my Mac book M1 ,  [Che Installation of openshift local](https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-red-hat-openshift-local/)

I have openshift local running on my system, I am able to login both as a developer and an admin both.
`crc status ` gives:

`
CRC VM:          Running
OpenShift:       Running (v4.13.6)
RAM Usage:       6.55GB of 9.353GB
Disk Usage:      21.96GB of 32.68GB (Inside the CRC VM)
Cache Usage:     37.64GB
`

However, when I run `chectl server:deploy --platform crc` , I encounter a timeout , I have the latest version of chectl installed.

The error message I receive is:

`
 Deploy Eclipse Che
    ❯ Install Dev Workspace operator
      ✔ Create CatalogSource devworkspace-operator...[Exists]
      ✖ Create Subscription devworkspace-operator
        Wait for Dev Workspace operator ready
      Create Subscription eclipse-che
      Fetch CheCluster sample from a CSV
      Create CheCluster Custom Resource
    Error: Command server:deploy failed with the error: Cannot create property 
    'context' on string 'Timeout reached while waiting for 
    "devworkspace-operator" subscription is ready.' 
`

I have tried and failed with Minikube and have spent countless hours reading issues and trying to fix them, but it seems all my efforts have been in vain. I would love to eventually contribute to the project, but I am struggling at what seems to be the very first step.

**Comment by tolusha** [comment]
Hello, @moonbse 

>Deploy Eclipse Che ❯ Install Dev Workspace operator ✔ Create CatalogSource devworkspace-operator...[Exists] ✖

Sounds like something already has been installed on the cluster.
Please do:
1. chectl server:delete --delete-all --delete-namespace
2. chectl server:deploy -p crc

**Comment by moonbse** [comment]
@tolusha I tried with commands , still failing and getting timeout with different error message

`❯ Deploy Eclipse Che
    ❯ Install Dev Workspace operator
      ✔ Create CatalogSource devworkspace-operator...[Created]
      ✖ Create Subscription devworkspace-operator
        Wait for Dev Workspace operator ready
      Create Subscription eclipse-che
      Fetch CheCluster sample from a CSV
      Create CheCluster Custom Resource
    Error: Command server:deploy failed with the error: Cannot create property 
    'context' on string 'Timeout reached while waiting for 
    "devworkspace-operator" subscription is ready.'`

**Comment by moonbse** [comment]
Update: 
I was able to resolve subscription issue, more like it resolved itself, I signedIn on CLI as admin for openshift local and subscription worked. 

Now the problem is I am getting timeout while scheduling Devfile Registry pod bootstrap, I tried increasing timeout and running with 
`chectl server:deploy -p crc --k8spodwaittimeout=200000 --k8spoderrorrechecktimeout=120000`

`chectl server:deploy -p crc --k8spodwaittimeout=200000 --k8spoderrorrechecktimeout=120000
› Current Kubernetes context: 'default/api-crc-testing:6443/kubeadmin'
  ✔ Verify Kubernetes API...[1.26]
  ✔ OpenShift version...[4.13]
  ✔ OpenShift Local preflight checklist
    ✔ Verify if oc is installed...[OK]
    ✔ Verify if OpenShift Local is installed...[OK]
    ✔ Verify if OpenShift Local is running...[OK]
    ✔ Retrieving OpenShift Local IP and domain for routes URLs...[127.0.0.1.nip.io]
  ✔ Create Namespace eclipse-che...[Created]
  ✔ Start following Eclipse Che installation logs...[OK]
  ✔ Deploy Eclipse Che
    ✔ Install Dev Workspace operator
      ✔ Create CatalogSource devworkspace-operator...[Created]
      ✔ Create Subscription devworkspace-operator...[Created]
      ✔ Wait for Dev Workspace operator ready...[OK]
    ✔ Create Subscription eclipse-che...[Created]
    ✔ Fetch CheCluster sample from a CSV...[OK]
    ✔ Create CheCluster Custom Resource...[Created]
  ❯ Wait for Eclipse Che ready
    ❯ Devfile Registry pod bootstrap
      ✖ Scheduling
        → Timeout: there are no pods in the namespace: eclipse-che, selector: app.kubernetes.io/na
…
        Downloading images
        Starting
      Plugin Registry pod bootstrap
      Dashboard pod bootstrap
      Gateway pod bootstrap
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Timeout: there are no pods in the 
    namespace: eclipse-che, selector: 
    app.kubernetes.io/name=che,app.kubernetes.io/component=devfile-registry. Check Eclipse Che 
    logs for details. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout
     flag. See details: /Users/nirbhay11.singh/Library/Caches/chectl/error.log. Eclipse Che 
    logs: /var/folders/70/2ttzh6492bs9bnhyqz03n5dmw0bbby/T/chectl-logs/1694072604997.`


checking chectl server:logs

`chectl server:logs
Eclipse Che logs will be available in '/var/folders/70/2ttzh6492bs9bnhyqz03n5dmw0bbby/T/chectl-logs/1694073203472'
› Current Kubernetes context: 'default/api-crc-testing:6443/kubeadmin'
  ✔ Verify Kubernetes API...[1.26]
  ⠹ Read Eclipse Che installation logs
    Error: Command server:logs failed with the error: Cannot create property 'context' on string
     '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container 
    \"che-operator\" in pod \"che-operator-654848c9cc-dnl9m\" is waiting to start: trying and 
    failing to pull image","reason":"BadRequest","code":400}
  ✔ Verify Kubernetes API...[1.26]
  ✖ Read Eclipse Che installation logs`
  
I have made progress but not sure where to go from here

**Comment by tolusha** [comment]
Hello.
Operator image is not pulled for some reasons.
Try to inspect events: `oc get events -n eclipse-che`

**Comment by moonbse** [comment]
@tolusha I guess it is failing before image download even starts  , I used openshift dashboard to sift through the events, DevWorkspace Operator is installed but eclipse-che installation fails with following message:

<img width="641" alt="Screenshot 2023-09-08 at 12 00 16 PM" src="https://github.com/eclipse/che/assets/29522373/15be281f-b94a-4dce-aac4-025d4ddd81f9">


`install failed: deployment che-operator not ready before timeout: deployment "che-operator" exceeded its progress deadline`


<img width="1728" alt="Screenshot 2023-09-08 at 11 39 28 AM" src="https://github.com/eclipse/che/assets/29522373/c15af469-369e-47cf-a811-bc910d1cf1d3">

Tried again and got this stream of events

<img width="1728" alt="Screenshot 2023-09-08 at 11 50 38 AM" src="https://github.com/eclipse/che/assets/29522373/ca7026e2-21d2-401d-8b59-c9129c891541">

On Cli I am failing at 
`❯ Wait for Eclipse Che ready   
  ❯ Devfile Registry pod bootstrap
      ✖ Scheduling
        → Timeout: there are no pods in the namespace: eclipse-che, selector: app.kubernete
…
        Downloading images
        Starting
      Plugin Registry pod bootstrap
      Dashboard pod bootstrap
      Gateway pod bootstrap
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Timeout: there are no pods in the
     namespace: eclipse-che, selector: 
    app.kubernetes.io/name=che,app.kubernetes.io/component=devfile-registry`

**Comment by moonbse** [comment]
Hi, I am only getting events in the openshift dashboard.

Running oc get events -n eclipse-che
`
oc get events -n eclipse-che
No resources found in eclipse-che namespace.
`

`
chectl server:deploy -p crc --k8spodwaittimeout=200000 --k8spoderrorrechecktimeout=120000 --k8spodreadytimeout=120000
› Current Kubernetes context: 'default/api-crc-testing:6443/kubeadmin'
  ✔ Verify Kubernetes API...[1.26]
  ✔ OpenShift version...[4.13]
 ›   Warning: Eclipse Che has been already deployed. Use server:start command to start a 
 ›   stopped Eclipse Che instance.
`

I tried to start the eclipse che instance as suggested above 

`
 chectl server:start
› Current Kubernetes context: 'default/api-crc-testing:6443/kubeadmin'
  ✔ Verify Kubernetes API...[1.26]
  ✔ Start following Eclipse Che installation logs...[OK]
  ❯ Scale Eclipse Che up
    ✖ Scale Devfile Registry Up
      → deployments.apps "devfile-registry" not found
      Devfile Registry pod bootstrap
      Scale Plugin Registry Up
      Plugin Registry pod bootstrap
      Scale Dashboard Up
      Dashboard pod bootstrap
      Scale Gateway Up
      Gateway pod bootstrap
      Scale Eclipse Che Server Up
      Eclipse Che Server pod bootstrap
    Error: Command server:start failed with the error: deployments.apps 
    "devfile-registry" not found See details: 
    /Users/nirbhay11.singh/Library/Caches/chectl/error.log. Eclipse Che logs: 
    /var/folders/70/2ttzh6492bs9bnhyqz03n5dmw0bbby/T/chectl-logs/1694175561932.
`

**Comment by tolusha** [comment]
Could you check 
* if any deployments are created in eclipse-che namespace?
* eclipse-che subscription status, maybe it can shed a light on the problem

**Comment by moonbse** [comment]
@tolusha 
 1. There are few deployments, but none in eclipse-che namespace I suppose
<img width="1419" alt="Screenshot 2023-09-11 at 11 09 46 AM" src="https://github.com/eclipse/che/assets/29522373/afca25ed-396e-47cf-ba3b-ad93464726ba">

For Che-operator deployment:  I am getting nothing here, only bad Gateway

<img width="1726" alt="Screenshot 2023-09-11 at 11 09 28 AM" src="https://github.com/eclipse/che/assets/29522373/4d52ecbc-5833-4c54-bd4e-3c378e1934e3">

2. Eclipse che subscription status 
<img width="1408" alt="Screenshot 2023-09-11 at 11 05 16 AM" src="https://github.com/eclipse/che/assets/29522373/e641cc83-d712-48a4-aeb9-0b0fa7c420c5">

I am stuck at `Wait for Eclipse Che ready` and `Scheduling`
Checking conditions on eclipse-che operator on openshift dashboard I am getting
`installing: waiting for deployment che-operator to become ready: deployment "che-operator" not available: Deployment does not have minimum availability.`

and following conditions 
<img width="1438" alt="Screenshot 2023-09-11 at 11 04 38 AM" src="https://github.com/eclipse/che/assets/29522373/c2669108-96b0-456b-a588-731c4ddb07ad">


Che-operator deployment has some issue and I think that's where it fails.
It says deployment does not have minimum availability. What is minimum availability? Do I need to increase resources in terms of memory?

<img width="1431" alt="Screenshot 2023-09-11 at 11 14 09 AM" src="https://github.com/eclipse/che/assets/29522373/fe4d1ef4-422f-4761-aa9b-deddc88a39de">

**Comment by tolusha** [comment]
@moonbse 
Basically it means, that pod is not up and running.
Something went wrong, it might be CrashLoopBackOff or ImagePullBackOff errors.
Please inspect che-operator pod.

**Comment by moonbse** [comment]
@tolusha  it is ImagePullBackOff, what could be the reason?

**Comment by tolusha** [comment]
Probably it is not possible to pull images from quay.io repository.
Try to create a pod in the `test` namespace using any quay.io image

```
oc create namespace test
oc apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - name: test
    image: quay.io/eclipse/che-operator:7.73.0
EOF    
```

**Comment by moonbse** [comment]
@tolusha I created the test Pod and applied the yml, pod is created with a warning 
`;Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "test" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
pod/test created`

**Comment by tolusha** [comment]
> no image found in image index for architecture `arm64`
That's a problem. We build operator image only for `linux/amd64`,`linux/ppc64le` platforms

**Comment by ibuziuk** [comment]
@moonbse feel free to join Eclipse Che Community Call on Monday, September 18th and add your topic to the agenda. More details about the community call / agenda can be found on the `che-dev` [1] mailing list. 

[1] https://www.eclipse.org/lists/che-dev/msg04473.html

**Comment by moonbse** [comment]
Update: I tried running it on minikube with docker driver as suggested here [What is best practice installing Che locally in M1 Mac](https://github.com/eclipse/che/issues/21908#top) , I was able to download images for amd64. Now, I am not able to changes ImageBackOffPolicy, I need to set it to IfNotPresent. I think this is it, I should be able to run it once I figure out to change this policy, right now it is trying to download the arm image.

**Comment by moonbse** [comment]
> @moonbse feel free to join Eclipse Che Community Call on Monday, September 18th and add your topic to the agenda. More details about the community call / agenda can be found on the `che-dev` [1] mailing list.
> 
> [1] https://www.eclipse.org/lists/che-dev/msg04473.html

@ibuziuk sure would do
