### ISSUE TITLE
Confused behavior run workspace when use factory from azure-devops private repository without PAT/OAuth setup

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#22469]
### Describe the bug

When there is not setup PAT/OAuth secrets, launch of factory from `azure-devops` private repository gives a different message on Dashboard UI, if to compare with others supported git-providers, see screenshot:

![azure-private-repo-no-pat-oauth](https://github.com/eclipse/che/assets/5408906/92e1616b-ba6f-4e15-ba5c-fa6c53f51925)

### Che version

next (development version)

### Steps to reproduce

* Deploy Che from the  `next` version
* Launch a factory from `azure-devops` private repo, like e.g.:
`https://<che_fqdn>#https://chepullreq1@dev.azure.com/chepullreq1/che-pr-private/_git/private-repo`
* Observe the message on Dashboard UI, which is different to rest of git-providres: GitHub.com, GitLab.com, Bitbucket.org
* See screenshots

### Expected behavior

Should be a similar message, like on others supported git-providers

### Runtime

OpenShift

### Screenshots

**GitHub.com:**

![github-private-repo-no-pat-oauth](https://github.com/eclipse/che/assets/5408906/16831bd9-f57a-4d8b-9246-3be53485f422)

**Bitbucket.org:**

![bitbucket-private-r epo-no-pat-oauth](https://github.com/eclipse/che/assets/5408906/2eb3a9b4-cf43-41d2-856d-bc233e1e332f)

**GitLab.com:**

![gitlab-private-repo-no-pat-oauth](https://github.com/eclipse/che/assets/5408906/df4973af-66a2-4ba3-9700-43bd6f7415fd)

### Installation method

chectl/next

### Environment

Linux

**Comment by nallikaea** [comment]
Mentioned in issue  #22441

https://github.com/eclipse/che/issues/22441#issuecomment-1685999326
