### ISSUE TITLE
Tomcat plugins in Eclipse Che

### ISSUE THREAD

**Issue by tathagata1977** [eclipse/che#22462]
### Summary

We are running a monolith code base in Eclipse Che environment. and now the mvn build process able to process the build successfully and create JAR file to be deployed. 
In eclipse Che environment how to deploy this JAR to tomcat environment ? 
Any help would be appropriated here.

### Relevant information

In eclipse Che environment how to deploy build generated JAR files to tomcat environment ?

**Comment by azatsarynnyy** [comment]
Hi @tathagata1977
It's possible to achieve the described goal by modifying the Devfile in the following way: 
- adding a container with the Tomcat server running inside
- exposing the required port
- adding a command that copies the jar to Tomact container
- adding a command that runs Tomcat server

**Comment by tathagata1977** [comment]
Thanks @azatsarynnyy ,
is there any sample Devfile you can refer ? I am running this Che environment in OKE cluster. using quay.io/eclipse/che-java11-maven@sha256:cc9e3cb0b00357ed118c130ce9f8e8e4724c718f8e2a1bd294f81696116d7b32 maven build. 
Thanks

**Comment by azatsarynnyy** [comment]
@tathagata1977 [This Devfile](https://github.com/che-samples/java-guestbook/blob/main/devfile.yaml) should help you understand what it might look like. This example contains adding several container components, exposing the endpoints, and defining the commands.

**Comment by tathagata1977** [comment]
I am not getting any proper solution of this # 
adding a container with the Tomcat server running inside
exposing the required port
adding a command that copies the jar to Tomact container
adding a command that runs Tomcat server
can you help on this ?

**Comment by AObuchow** [comment]
@tathagata1977 It might help if you can show your current devfile, so we can get a better idea of what's going on

**Comment by tathagata1977** [comment]
Thanks @AObuchow for your reply. 
This is my Devfile 

apiVersion: 1.0.0
metadata:
  name: Mydas6-13
attributes:
  persistVolumes: 'true'
projects:
  - name: codebase
    source:
      startPoint: '6.13'
      location: 'https://gitlab...........codebase.git'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 4Gi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven@sha256:cc9e3cb0b00357ed118c130ce9f8e8e4724c718f8e2a1bd294f81696116d7b32'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: bmewburn/vscode-intelephense-client/latest
    type: chePlugin
commands:
  - name: codebase
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven

**Comment by tathagata1977** [comment]
Also I am running this Che environment on OKE.

**Comment by tathagata1977** [comment]
@AObuchow ,
did you had a chance to review this ? any suggestion ?

**Comment by tathagata1977** [comment]
Please note I am running a monolith application here and the jar and war file is on .m2 directory. I want to deploy this war file to Tomcat server which I am not able to achieve here !

**Comment by AObuchow** [comment]
@tathagata1977 I appologize, I haven't had a chance to look into this further. I am not very familiar with Tomcat server or setting up a devfile like you'd need, and I am caught up with other tasks currently, unfortunately.

However, consulting the devfile documentation may be helpful for you (see the links on the left-hand side of [this webpage](https://devfile.io/docs/2.2.0/defining-endpoints). I recommend trying to follow @azatsarynnyy's previous suggestion and consulting the devfile documentation to learn how to do so.

**Comment by tathagata1977** [comment]
I modified the DevFile 
apiVersion: 1.0.0
metadata:
  name: Mydas6-13-tomcat
attributes:
  persistVolumes: 'true'
projects:
  - name: codebase
    source:
      startPoint: '6.13'
      location: 'https://gitlab.......codebase.git'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 4Gi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven@sha256:cc9e3cb0b00357ed118c130ce9f8e8e4724c718f8e2a1bd294f81696116d7b32'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: bmewburn/vscode-intelephense-client/latest
    type: chePlugin
  - referenceContent: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: tomcat
      spec:
        initContainers:
          - name: tomcat-container-nautilus
            image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
            ports:
            - containerPort: 8080
            containerPath: /opt/tomcat
    type: kubernetes
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
But I am getting below errors 
Successfully assigned admin-dev/workspace3hg0p770yyzhsha5.che-plugin-broker to 10.0.10.203

Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 1.334728596s

Created container che-plugin-metadata-broker-v3-4-0

Started container che-plugin-metadata-broker-v3-4-0

Starting plugin metadata broker

All plugin metadata has been successfully processed

List of plugins and editors to install

- redhat/java/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...

- redhat/vscode-xml/latest - XML Language Support by Red Hat

- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.

- vscode/typescript-language-features/latest - Provides rich language support for JavaScript and TypeScript.

- redhat/vscode-yaml/latest - YAML Language Support by Red Hat, with built-in Kubernetes syntax support

- eclipse-cdt/cdt-vscode/latest - CDT VS Code Extension for C/C++ Developers

- bmewburn/vscode-intelephense-client/latest - PHP code intelligence for Visual Studio Code

- eclipse/che-theia/latest - Eclipse Theia

AttachVolume.Attach succeeded for volume "csi-bba17a42-623c-497c-8428-451b27bb5109"

Pulling image "gcr.io/kodekloud/centos-ssh-enabled:tomcat"

Successfully pulled image "gcr.io/kodekloud/centos-ssh-enabled:tomcat" in 412.815598ms

Created container tomcat-container-nautilus

Started container tomcat-container-nautilus

Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspace3hg0p770yyzhsha5' reached timeout"
can anyone review this ?

**Comment by azatsarynnyy** [comment]
@tathagata1977 could you please specify which Eclipse Che version you have?

**Comment by tathagata1977** [comment]
This is 7.41.2 . and I am running it on OKE cluster.

**Comment by tathagata1977** [comment]
@azatsarynnyy  or any one I really need this to work, any help would be appreciated.

**Comment by tolusha** [comment]
@tathagata1977 
The version 7.41.2 is quite old, not sure if some is able to help.
