### ISSUE TITLE
Che still using expired certificate instead of the renewed ones

### ISSUE THREAD

**Issue by Deddinho23** [eclipse/che#22464]
### Describe the bug

Hi everyone, 
we're using a certificate on Che generated by our cert-manager issuer (we followed the related article in the guide: https://eclipse.dev/che/docs/stable/administration-guide/configuring-che-hostname) but for some reason, although the issuer correctly renew the certificate, Che continues to use the first that was issued and don't consider the fact that even the secret containing it was updated with the new one, seems like it's keeping the first one that was given and don't listen if there are any update about the associated secret of the certificate...

### Che version

7.73@latest

### Steps to reproduce

1. Custom Certificate
2. Expire it
3. Keeping the expired, didn't take the new one

### Expected behavior

When the current certificate is expiring, Che should replace with the renewed

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Amazon

**Comment by tolusha** [comment]
Could you check if `self-signed-certificate` Secret exists in the `eclipse-che` namespace?
It must contain the certificate chain of trust, probably it is outdated. If so, it must be updated as well.

**Comment by tolusha** [comment]
> For a second today I enter in Che Dashboard and it had the new one

Could you elaborate more? What does this actually mean?

**Comment by Deddinho23** [comment]
Of course @tolusha, I'll try to explain it in a better way:

Yesterday I was trying to "forcefully" let him take a new certificate, so I created a new certificate's resource with a different name and I have updated the `tlsSecretName` parameter in the CheCluster CRDs to use the new secret, but it didn't work.

This morning at the first access, for some reason, the Che Dashboard URL was using the new certificate instead of the old one that was expired, but as soon as I changed page the certificate in use re-became the expired one

**Comment by tolusha** [comment]
Hello. That's strange.

1. Check if a new secret is used by ingress
`kubectl get ingress che -n eclipse-che -o "jsonpath={.spec.tls}"`
2. Try to open dashboard in an incognito window
