### ISSUE TITLE
Accessing public endpoints of workspace pod

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#22461]
### Summary

In an older version of eclipse che the URL of the IDE looked something likes this:
`https://192.168.49.2.nip.io/workspaced381305089e34ab0/theia-ide/3100`

In a devfile it was possible to define public endpoints, which were acessible by following url
you define public endpoints which were acessible via following url:

`https://<workspaceHash>-<number starting from 1>.<fqn>`
e.g.:
`https://workspaced381305089e34ab0-1.192.168.49.2.nip.io/` (1)

See this old issue:
https://github.com/eclipse/che/issues/21634#issuecomment-1232233771

Now the workspace hash is not present anymore in the url, but can be obtained via `kubectl`
But I fail to access the exposed container like in the old version of che.

Do I have to do now something different with the current Che Version (7.72.0) ?

I also noticed that the public stack examples don`t have public endpoints anymore, only private ones.

I added the definition of my devfile below.

### Relevant information

Che version 7.72.0

My devfile: https://gist.githubusercontent.com/Deel96/2fde413e707a73e6487464b16f6cafe3/raw/a6a08125f86a16b683cc02e4eebc07a431248f06/che-editor.yaml

**Comment by tolusha** [comment]
The workspace URL has been changes.
You can find below the related issue:
https://github.com/eclipse/che/issues/20598
https://github.com/eclipse-che/che-operator/pull/1672
