### ISSUE TITLE
How to set custom _oauth2_proxy expiration time

### ISSUE THREAD

**Issue by ddoan** [eclipse/che#22460]
### Summary

Hello,

Our use case for Che is to create emphemeral workspaces and we find that the default expiration time is too long, resulting in issues like this:

<img width="983" alt="Screenshot 2023-08-25 at 5 44 23 PM" src="https://github.com/eclipse/che/assets/993727/848bdfb7-3b1c-4fc2-8cfe-b0ee0abd1a63">

Our current workaround to have users clear cookies for our site, but that is not a great user experience. We were wondering how we can override the default expiration time to have a lower expiration time. How can we do this?

Thank you!

**Comment by tolusha** [comment]
@ddoan 
Please, provide the following some details:
- Eclipse Che version
- K8s platform

**Comment by ddoan** [comment]
@tolusha sure here you go:

- 7.70.0
- Amazon EKS (kubernetes version 1.27, AMI version 1.27.3-20230816)

**Comment by AObuchow** [comment]
I believe the oath2 proxy cookie expiration time is currently [hard-coded](https://github.com/eclipse-che/che-operator/blob/6cf8df2b860b81ea53b3bc98aafe6c25a313aa7c/pkg/deploy/gateway/oauth_proxy.go#L116), though I may be mistaken.

**Comment by tolusha** [comment]
I think so. We should either allow to configure that timeout or allow to override the whole configuration. 
I still don't know what the best solution is.

**Comment by ddoan** [comment]
Let me know how I can be helpful here. Thanks!

**Comment by ibuziuk** [comment]
@ddoan would you be interested in contributing this functionality to the project?

**Comment by ddoan** [comment]
@ibuziuk yes either myself or someone from my team can do that.

**Comment by tolusha** [comment]
@ddoan 
Please wait until this PR https://github.com/eclipse-che/che-operator/pull/1748 is merged.
Then we can add expiration time fields in the same way.

**Comment by ibuziuk** [comment]
@ddoan great news! feel free to join Eclipse Che Community Call on Monday, September 18th and add your topic to the agenda. More details about the community call / agenda can be found on the `che-dev` [1] mailing list. 

[1] https://www.eclipse.org/lists/che-dev/msg04473.html

**Comment by tolusha** [comment]
Hello @ddoan 
Feel free to submit a RP to add required configuration. See example here https://github.com/eclipse-che/che-operator/pull/1748
I will be glad to help you.

**Comment by ddoan** [comment]
@tolusha Someone from my team put up the PR. Sorry we missed the community meeting, we had a scheduling issue on our end. Thanks for your help.
