### ISSUE TITLE
Plugin registry's build is failed 

### ISSUE THREAD

**Issue by svor** [eclipse/che#22470]
### Describe the bug

Che embedded plugin registry's build is failing because the latest version of muhammad-sammy.csharp extension depends on ms-dotnettools.vscode-dotnet-runtime which is not in the list of embedded extensions:

```
191.9 Downloading https://open-vsx.org/api/muhammad-sammy/csharp/2.0.436/file/muhammad-sammy.csharp-2.0.436.vsix into muhammad-sammy folder...
195.0 🚀  Created namespace muhammad-sammy
195.5 ❌  Cannot resolve dependency: ms-dotnettools.vscode-dotnet-runtime
195.5 See the documentation for more information:
195.5 https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

### Che version

next (development version)

**Comment by ibuziuk** [comment]
Marking as a blocker for 7.74.0 upstream release
