### ISSUE TITLE
Failed to fetch available workspaces and then failed to fetch list of namespaces errors on sandbox

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22472]
### Describe the bug

<img width="662" alt="image" src="https://github.com/eclipse/che/assets/606959/c49cf4da-8fbe-4780-9b9f-4d7f7640d056">

<img width="1753" alt="image" src="https://github.com/eclipse/che/assets/606959/7f8cf774-a699-4476-a7d0-e908649c7b65">

### Che version

7.73@latest

### Steps to reproduce

open a workspace on sandbox

### Expected behavior

should work

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by dkwon17** [comment]
This issue is likely caused by https://github.com/eclipse/che/issues/22353#issuecomment-1696422668

**Comment by ibuziuk** [comment]
@dkwon17 I remember we discussed also cm is not available, is it a separate problem?
<img width="1726" alt="Screenshot 2023-09-07 at 11 55 35" src="https://github.com/eclipse/che/assets/1461122/9b889403-3382-403a-822d-0698e5b951dd">

**Comment by ibuziuk** [comment]
sorry, it is not relevant @tolusha I think it is related to https://github.com/eclipse-che/che-dashboard/pull/912

**Comment by tolusha** [comment]
It is needed to restart operator pod to pull a new operator image.

**Comment by dkwon17** [comment]
This issue is handled by dashboard request retries functionality:
https://github.com/eclipse-che/che-dashboard/pull/942
https://github.com/eclipse-che/che-dashboard/pull/946
https://github.com/eclipse-che/che-dashboard/pull/958
