### ISSUE TITLE
Use 'registry.devfile.io' by default in Eclipse Che

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22485]
### Is your task related to a problem? Please describe

By default, Eclipse Che should be using devfiles from 'registry.devfile.io' as getting started samples. Operator should not  provision and manage dedicated operand in the upstream. 
Note, that for downstream Dev Spaces we should continue using internal devfile registry.

### Describe the solution you'd like

Acceptance criteria:
- [x] Operator fall back on registry.devfile.io by default
- [x] All devfiles from the registry.devfile.io are correctly displayed on the User Dashboard as 'Getting Started' samples
- [x] Workspaces are started successfully based on the 'Getting Started' samples
- [x] Projects are cloned correctly and visible in the newly created workspaces
     - [x] https://github.com/eclipse/che/issues/22486

### Describe alternatives you've considered

N/A

### Depends on
* https://github.com/eclipse/che/issues/22524
* https://github.com/eclipse/che/issues/22525

### Additional context

Part of the https://github.com/eclipse/che/issues/20251

**Comment by tolusha** [comment]
Current issues:

0. Failed to start a terminal
```
The terminal process failed to launch: Path to shell executable "/sbin/nologin" does not exist.
```

2. Editor is not started for stack:
- django
- go
- python
- java-vertex
- wildfly

3. Other errors:
* Quarkus Java:
```
Error creating DevWorkspace deployment: Detected unrecoverable event FailedPostStartHook: Exec lifecycle hook ([/bin/sh -c { nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt 2>&1 & cd ${PROJECT_SOURCE} mvn -Dmaven.repo.local=/home/user/.m2/repository compile } 1>/tmp/poststart-stdout.txt 2>/tmp/poststart-stderr.txt ]) for Container "tools" in Pod "workspace2b83f05581a442e8-5447d46f8c-xbw4h_admin-che(75348ef2-c803-48d8-b5e0-b4c8dbd6d98c)" failed - error: command '/bin/sh -c { nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt 2>&1 & cd ${PROJECT_SOURCE} mvn -Dmaven.repo.local=/home/user/.m2/repository compile } 1>/tmp/poststart-stdout.txt 2>/tmp/poststart-stderr.txt ' exited with 1: , message: "".
```

* Devfile.io:
```
Error creating DevWorkspace deployment: Detected unrecoverable deployment condition: FailedCreate pods "workspace4692df4d2ae747e3-6c77d57894-8kx9g" is forbidden: [maximum memory usage per Container is 6Gi, but limit is 7073741824, maximum cpu usage per Container is 4, but limit is 4500m, maximum cpu usage per Pod is 4, but limit is 5]
```

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/22524

**Comment by nickboldt** [comment]
is there an airgap plan for this for downstream?
