### ISSUE TITLE
[UD] The dashboard does not redirect to the login page If the session expires

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22484]
### Describe the bug

The dashboard does not redirect to the login page If the session expires.

https://youtu.be/aJxqGhx1tGw

### Che version

7.73@latest

### Steps to reproduce

1. Deploy Eclipse CHE.
2. Create a new workspace and open the list of workspaces(`${che-server}/dashboard/#/workspaces`).
3. Open the dashboard in a new browser tab and press logout.
4. Return to the first tad and try to delete existing workspaces. 
5. An authorization error  message will appear in the browser console, but the dashboard does not redirect to the login page

### Expected behavior

A web page that requires login should redirect to the login page If the session expires.

### Runtime

minikube

### Screenshots

![Знімок екрана 2023-09-06 о 13 16 31](https://github.com/eclipse/che/assets/6310786/6ef5a7d1-1be8-4a64-a1e3-0a8ade2d42d0)

### Installation method

chectl/next

### Environment

macOS

**Comment by ibuziuk** [comment]
if the session is expired we should not show the errors, but redirect to the login page

**Comment by olexii4** [comment]
fixed with https://github.com/eclipse-che/che-dashboard/pull/930
