### ISSUE TITLE
Add skaffold to the Universal Developer Image

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22483]
### Is your enhancement related to a problem? Please describe

I'm always frustrated when working on my project I need to manually build a docker image, push it to the registry, and then patch the CR. Hence, it would be nice to have a tool that automates this process.

### Describe the solution you'd like

The UDI should contain skaffold.

### Additional context

Skaffold is an open-source continuous integration tool created by Google that facilitates continuous development for container-based and Kubernetes applications. It handles the workflow for building, pushing, and deploying applications and provides building blocks for creating CI/CD pipelines. Skaffold can be used to automatically build and deploy an application when code changes.

**Comment by ibuziuk** [comment]
Reopening in order to get clarification if we should backport it to downstream for 3.9

**Comment by ibuziuk** [comment]
it was decided not to add scaffold to the downstream for the time being. Closing
