### ISSUE TITLE
Use default devfile during workspace startup based on 'ssh://' if devfile can not be retrieved by che-server

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22488]
### Is your enhancement related to a problem? Please describe

PR with initial SSH support implementation - https://github.com/eclipse-che/che-server/pull/539 
There are a few enhancements that need to be done as part of this issue:
- [x] if SSH URL points to the unsupported provider and che-server can not retrieve devfile, workspace should be started based on the default one (appropriate warning message should be shown on the workspace startup screen)
- [x] default devfile should be also used if SSH url points to the supported provider, but devfile still can not be retrieved (e.g. private repo, no OAuth / PAT are configured)

### Describe the solution you'd like

N/A

### Additional context

Related issue - https://github.com/eclipse/che/issues/22473

**Comment by ibuziuk** [comment]
@vinokurig @l0rd please, review
this is a follow up issue based on the comments from https://github.com/eclipse-che/che-server/pull/539
I think we can close https://github.com/eclipse/che/issues/22473 in favour of this issue

**Comment by l0rd** [comment]
> @vinokurig @l0rd please, review this is a follow up issue based on the comments from [eclipse-che/che-server#539](https://github.com/eclipse-che/che-server/pull/539) I think we can close #22473 in favour of this issue

LGTM

**Comment by ibuziuk** [comment]
@vinokurig please, make sure that the fixes are backported for 3.9

**Comment by vinokurig** [comment]
checrry-picked to 7.74 [d8991eafd1a49aec704fe618834d1d5e99eb6883](https://github.com/eclipse-che/che-server/commit/d8991eafd1a49aec704fe618834d1d5e99eb6883)

**Comment by nickboldt** [comment]
Tracked downstream in https://issues.redhat.com/browse/CRW-4871

**Comment by ibuziuk** [comment]
closing as done
