### ISSUE TITLE
Enhance OAuth integration when user doesn't want to grant permissions

### ISSUE THREAD

**Issue by ehsavoie** [eclipse/che#22499]
### Is your enhancement related to a problem? Please describe

I'm always frustrated when I use a Che instance with GitHub OAuth enabled and I want to use a GitHub project to get the devfile I want to use (dong something quite similar to using a devfile registry).
It asks for GitHub permissions which I don't want to grant. If I press Cancel then it keeps on asking them each time I'm opening the workspace. In the end it finished with a 500 Internal Error json message.

### Describe the solution you'd like

I'd like Che to accept that I don't want to use OAuth to connect to my GitHub account and I don't want to use Che to do Git operations (in my case it is mostly demo) and stop bugging me about those permissions after I refused to grant them.

### Describe alternatives you've considered

I've created a fork of my project on BitBucket because currently it is not integrated with OAuth but that's not going to be something that might be valid in the future.

**Comment by ibuziuk** [comment]
@ehsavoie thanks for reporting this enhancement, could you provide schematic UX mockup for OAuth opt out?
As an alternative you can configure PAT with from UD
<img width="1726" alt="Screenshot 2023-09-08 at 18 01 32" src="https://github.com/eclipse/che/assets/1461122/7144cf9a-13a5-490f-8f44-58986bac009e">

**Comment by ibuziuk** [comment]
@vinokurig thinking about this issue from impl perspective, I'm wondering if user opt out from OAuth / presses `Cancel`, instead of 500 create a cm e.g. `oauth-opt-out` in the user namespace that would be an indicator that OAuth flow should not be used for such a user. This would require no UI changes on UD / OAuth flow end

**Comment by ibuziuk** [comment]
`workspace-preferences-configmap` might be a good place for oauth opt out field

**Comment by vinokurig** [comment]
> If I press Cancel then it keeps on asking them each time I'm opening the workspace. In the end it finished with a 500 Internal Error json message.

This is bug. If oauth page is rejected workspace start must proceed with asking to use a default devfile. 
@ibuziuk 
> thinking about this issue from impl perspective, I'm wondering if user opt out from OAuth / presses Cancel, instead of 500 create a cm e.g. oauth-opt-out in the user namespace that would be an indicator that OAuth flow should not be used for such a user. This would require no UI changes on UD / OAuth flow end

Do you think this should be workspace scope or user scope? I mean if an oauth is rejected for particular workspace, should we automatically reject oauth for all other workspaces, or just for the current?

**Comment by ibuziuk** [comment]
>  If oauth page is rejected workspace start must proceed with asking to use a default devfile.

well, but if the devfile is public we should use it and not fall back on default.
The problem described in this issue is that we require OAuth even for public repositories.

**Comment by vinokurig** [comment]
> well, but if the devfile is public we should use it and not fall back on default.

This should be fixed by https://github.com/eclipse-che/che-dashboard/pull/932 and https://github.com/eclipse-che/che-server/pull/568
> The problem described in this issue is that we require OAuth even for public repositories.

This was added on purpose, we did not use to ask the authorisation for public repos at all. As far as I understood https://github.com/eclipse/che/issues/22499#issuecomment-1711909713, we should ask the authorisation (even for public repos) but keep the decision in a config-map.

**Comment by ibuziuk** [comment]
> we should ask the authorisation (even for public repos) but keep the decision in a config-map.

yes, we should initiate OAuth flow if configured for both public and private repos. If the user opt-out from OAuth, for public repos we should use the original devfile, for private we should use default similar to what was done for https://github.com/eclipse/che/issues/22488
