### ISSUE TITLE
possibility of monolith java application running in Che IDE

### ISSUE THREAD

**Issue by tathagata1977** [eclipse/che#22501]
### Summary

I am working on one of the client need of running there monolith java application which would be running on Tomcat and database is oracle 19c. 
is that possible to do ? 
I am able to create workspace and able to successfully build the code base using maven build process. 
But not sure how to use tomcat and how to connect the DB.  

### Relevant information

I am using Che 7.41.2  version and its running on OKE. 
this is my devfile code # 

apiVersion: 1.0.0
metadata:
  name: Mydas6-13
attributes:
  persistVolumes: 'true'
projects:
  - name: codebase
    source:
      startPoint: '6.13'
      location: 'https://gitlab........./applications/codebase.git'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 4Gi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven@sha256:cc9e3cb0b00357ed118c130ce9f8e8e4724c718f8e2a1bd294f81696116d7b32'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse-cdt/cdt-vscode/latest
    type: chePlugin
  - id: bmewburn/vscode-intelephense-client/latest
    type: chePlugin
commands:
  - name: codebase
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/codebase'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven

**Comment by tolusha** [comment]
@tathagata1977 
You use a quite old version of Eclipse Che and devfile API.

**Comment by l0rd** [comment]
@tathagata1977 to answer your question: yes it's possible to include tomcat and a database. Or you can configure your application to connect to an external DB if you don't want to start a new one per workspace. You need to add a component to add another container. 

But as mentioned by @tolusha you are using an old version of Che and of the Devfile specification. That makes it hard to help you.

We are not testing / supporting OKE, although it should be possible to configure an IDP and run Che there.

**Comment by tathagata1977** [comment]
@l0rd Thanks for your reply. I am kind of stuck , as this old version is the only one which presently works correctly in OKE. I know your are not supporting OKE, but my client is on Oracle cloud and they want to use Che as there development tool/ environment. 
I need help here to proceed further. I am able to build the application , but not able to deploy. 
If any meeting is require for this action plan I am OK to do so. 
Please let me know.

**Comment by ibuziuk** [comment]
@tathagata1977 feel free to join Eclipse Che Community Call on Monday, September 18th and add your topic to the agenda. More details about the community call / agenda can be found on the `che-dev` mailing list. 

[1] https://www.eclipse.org/lists/che-dev/msg04473.html
