### ISSUE TITLE
Empty workspace smoke test is failing for developer-images repository

### ISSUE THREAD

**Issue by svor** [eclipse/che#22509]
### Describe the bug

Empty workspace smoke test is failing in [PRs for developer-images repository](https://github.com/devfile/developer-images/actions/runs/6166055904)
For example: 
-  https://github.com/devfile/developer-images/pull/120
- https://github.com/devfile/developer-images/pull/125

From the [kubectl events](https://github.com/devfile/developer-images/suites/16041319192/artifacts/920062173) we have:
```
admin-devspaces           5m59s       Normal    BackOff                   pod/workspace9206667fc7e24b2b-b46b8478d-lnphs                   Back-off pulling image "quay.io/che-incubator/che-code:latest"
admin-devspaces           5m39s       Warning   Failed                    pod/workspace9206667fc7e24b2b-b46b8478d-lnphs                   Error: ErrImagePull
admin-devspaces           5m39s       Warning   Failed                    pod/workspace9206667fc7e24b2b-b46b8478d-lnphs                   Failed to pull image "quay.io/che-incubator/che-code:latest": rpc error: code = Unknown desc = failed to register layer: write /checode-linux-libc/extensions/che-github-authentication/dist/extension.js: no space left on device
```

### Che version

next (development version)

### Steps to reproduce

Check PRs check on https://github.com/devfile/developer-images

### Expected behavior

Empty workspace smoke test on udi8 / workspace-api-tests-on-minikube (pull_request) check shouldn't fail because of `no space left on device`

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

### Logs
[kubectl-events.log](https://github.com/eclipse/che/files/12596762/kubectl-events.log)

**Comment by ibuziuk** [comment]
@musienko-maxim could you please take a look?

**Comment by musienko-maxim** [comment]
The root cause is limited Disk space the provided GitHub for not enterprise plan - just 14 GB. But our images - especially UDI + others can be over this limit, and we must be forced to walk on the edge. I have some ideas that can help with this, and I am planning to create a new PR. I hope it will work
