### ISSUE TITLE
Jupyter Notebook.

### ISSUE THREAD

**Issue by jhyungjeon** [eclipse/che#22519]
### Summary

Hello I want to add jupyter-notebook to plugin.
The image uses docker pull jupyter/tensorflow-notebook.
After adding it, the error [Errno 13] Permission denied: '/home/jovyan/.local' occurs.
I'm curious about the solution.

### Relevant information

Entered start.sh with args: jupyter lab
There is no entry in /etc/passwd for our UID=1234. Attempting to fix...
Renaming old jovyan user to nayvoj (1000:100)
Added new jovyan user (1234:0). Fixed UID!
WARNING: no write access to /home/jovyan. Try starting the container with group 'users' (100), e.g. using "--group-add=users".
Executing the command: jupyter lab
[I 2023-09-18 04:59:38.922 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-18 04:59:38.928 ServerApp] Package jupyter_lsp took 0.0059s to import
[W 2023-09-18 04:59:38.928 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.930 ServerApp] Package jupyter_server_mathjax took 0.0014s to import
[I 2023-09-18 04:59:38.934 ServerApp] Package jupyter_server_terminals took 0.0036s to import
[I 2023-09-18 04:59:38.951 ServerApp] Package jupyterlab_git took 0.0171s to import
[I 2023-09-18 04:59:38.953 ServerApp] Package nbclassic took 0.0011s to import
[W 2023-09-18 04:59:38.954 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.954 ServerApp] Package nbdime took 0.0000s to import
[I 2023-09-18 04:59:38.954 ServerApp] Package notebook took 0.0000s to import
[I 2023-09-18 04:59:38.955 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-18 04:59:38.955 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.956 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-09-18 04:59:38.958 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-09-18 04:59:38.960 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-18 04:59:38.963 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-18 04:59:38.963 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-09-18 04:59:38.965 ServerApp] nbclassic | extension was successfully linked.
[I 2023-09-18 04:59:38.965 ServerApp] nbdime | extension was successfully linked.
[I 2023-09-18 04:59:38.967 ServerApp] notebook | extension was successfully linked.
[W 2023-09-18 04:59:38.968 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local'

**Comment by l0rd** [comment]
@jhyungjeon the information you are providing are not useful to provide an answer. Please update the issue description providing the following information:
- steps you have followed to install Che
- detailed steps to reproduce your issue
