### ISSUE TITLE
`Copy endpoint URL to clipboard` button's icon isn't visible in Che-Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#22512]
### Describe the bug

`Copy endpoint URL to clipboard` button's icon isn't visible in Che-Code. From the user's perspective, it may look like there is no button to copy the endpoint URL.

### Che version

7.74@latest

### Steps to reproduce

Hover over the endpoint actions panel.

### Expected behavior

There should be an icon defined in https://github.com/che-incubator/che-code/blob/f4c40881f407bc24573d99c09df02040f02aae9b/code/extensions/che-port/package.json#L97-L102

### Runtime

OpenShift

### Screenshots

![image](https://github.com/eclipse/che/assets/1636395/3aaeafd1-ba3d-4f41-97a9-b2acbf2900f1)

### Installation method

OperatorHub

### Environment

Linux

**Comment by l0rd** [comment]
I am wondering if we should not completely [rework the extension and leverage the VS Code built-in ports widget](#22527).
