### ISSUE TITLE
It is not possible to start a terminal when workspace started from a devfile from the `registry.devfile.io`

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22524]
### Describe the bug

It is not possible to start a terminal when workspace started from a devfile from the `registry.devfile.io`

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che on OpenShift
2. Configure external devfile registry `https://registry.devfile.io`
```
oc patch checluster/eclipse-che --patch '{"spec": {"components": {"devfileRegistry": {"disableInternalRegistry": true, "externalDevfileRegistries": [{"url": "'https://registry.devfile.io'"}]}}}}' --type=merge -n eclipse-che
```
3. Start a workspace
4. Start a terminal 
![screenshot-eclipse-che apps ci-ln-zpry0jk-76ef8 aws-2 ci openshift org-2023 09 18-13_57_44](https://github.com/eclipse/che/assets/1640675/4062aca8-c491-4574-b838-45d0406f0e82)

It is worth to note, that `New terminal (Select a container)` command works fine.

### Expected behavior

Terminal successfully started.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by l0rd** [comment]
Included in #20251
