### ISSUE TITLE
Investigate if VS Code ports widgets can be re-used to manage workpaces endpoints

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22527]
### Is your enhancement related to a problem? Please describe

Port extensions has [bugs](https://github.com/eclipse/che/issues/22512) and is not user friendly.

### Describe the solution you'd like

Manage the exposed ports using VS Code built-int port-forwarding widget: https://code.visualstudio.com/docs/editor/port-forwarding. Ideally we should replace that widget with ours (because the built-in extension doesn't make sense when running in kube):
- Instead of the column "visibility" we should have the column "exposure" and the value can be public/internal/none

**Comment by l0rd** [comment]
As first iteration we only need to investigate it. This issue should be worked for Hack 'n Hustle day.

**Comment by vitaliy-guliy** [comment]
Having investigated the ability to use the widget to display/manage container endpoint I would say it's a bit complex at this time. I would postpone with it to the next Hack'n'Hustle day or to wait until the corresponding Extension API appear.
