### ISSUE TITLE
Failing e2e tests does not create screenshot

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22529]
### Describe the bug

When running `export USERSTORY=SmokeTest && npm run test` to run the smoke tests, if there is a test failure, there are no [screenshot, pagesource, or browserlog](https://github.com/eclipse/che/blob/74f10465b196d7b752c68c50b8d69b10135e8750/tests/e2e/utils/CheReporter.ts#L140-L142) files in the reports folder.

Here is the terminal output: [log](https://gist.github.com/dkwon17/dee972a4ce2126d95ec32d803b0b84f8)

### Che version

7.74@latest

### Steps to reproduce

1. Checkout this branch (this contains a smoke test that will always fail) https://github.com/dkwon17/che/tree/failSmoke
2. Set env variables:
```
export TS_SELENIUM_BASE_URL=<baseurl>
export TS_SELENIUM_OCP_USERNAME=<username>
export TS_SELENIUM_OCP_PASSWORD=<password>
```
3. Run `cd `tests/e2e` 
4. Run `export USERSTORY=SmokeTest && npm run test`
5. After smoke test fails, check the `tests/e2e/reports` folder to verify that there is no screenshot, pagesource file or browser log file

### Expected behavior

I expected a screenshot, pagesource file and browser log file

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

macOS

### Additional context

I noticed the screenshot is created (but no pagesource, or browserlog file) if the `driverHelper` is retrieved with `e2eContainer.get` like so: https://github.com/eclipse/che/blob/41d1364f679779f61e3d17f248bcb5de260c22a4/tests/e2e/utils/CheReporter.ts#L28, instead of [constructor injection](https://github.com/eclipse/che/blob/74f10465b196d7b752c68c50b8d69b10135e8750/tests/e2e/utils/CheReporter.ts#L37)

**Comment by nallikaea** [comment]
Hi, @dkwon17 
Thank you for the reporting

> Additional context
> I noticed the screenshot is created (but no pagesource, or browserlog file) if the driverHelper is retrieved with e2eContinare.get like so:
> 
> [che/tests/e2e/utils/CheReporter.ts](https://github.com/eclipse/che/blob/41d1364f679779f61e3d17f248bcb5de260c22a4/tests/e2e/utils/CheReporter.ts#L28)
> 
> Line 28 in [41d1364](https://github.com/eclipse/che/commit/41d1364f679779f61e3d17f248bcb5de260c22a4)
> 
>  const driverHelper: DriverHelper = e2eContainer.get(CLASSES.DriverHelper); 
> , instead of [constructor injection](https://github.com/eclipse/che/blob/74f10465b196d7b752c68c50b8d69b10135e8750/tests/e2e/utils/CheReporter.ts#L37)
> 

Are you sure that you fetch latest changes? Because I fixed it in this commit https://github.com/eclipse/che/commit/aace77aed3a7766c3f120f738794a059803a8f18#diff-72495e762091ed981a5bca85057b2c1650d2fbcc39185d50f518aaba9fc51931

**Comment by nallikaea** [comment]
Thank you for creating the issue, I double checked and provided fix:

https://github.com/eclipse/che/pull/22536
