### ISSUE TITLE
Editor is not started when workspace started from some devfiles from the `registry.devfile.io`

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22525]
### Describe the bug

Editor is not started when workspace started from some devfiles from the `registry.devfile.io`:
- django
- go
- python
- java-vertex
- wildfly

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che on OpenShift
2. Configure external devfile registry `https://registry.devfile.io`
```
oc patch checluster/eclipse-che --patch '{"spec": {"components": {"devfileRegistry": {"disableInternalRegistry": true, "externalDevfileRegistries": [{"url": "'https://registry.devfile.io'"}]}}}}' --type=merge -n eclipse-che
```
3. Try a start a workspace from the stacks above

![screenshot-eclipse-che apps ci-ln-zpry0jk-76ef8 aws-2 ci openshift org-2023 09 18-14_28_44](https://github.com/eclipse/che/assets/1640675/20b78c3b-500f-4e30-87a2-a454c7e6eb5e)

### Expected behavior

Workspace is started successfully

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by l0rd** [comment]
Included in https://github.com/eclipse/che/issues/20251

**Comment by RomanNikitenko** [comment]
The pull request for the `Vert.x Java Stack`: https://github.com/devfile/registry/pull/295

**Comment by RomanNikitenko** [comment]
The pull request for the `WildFly Bootable Jar Stack`: https://github.com/devfile/registry/pull/296

**Comment by ibuziuk** [comment]
@RomanNikitenko both PRs have been merged and https://github.com/eclipse/che/issues/22814 is closed
can we close this issue as well cc: @musienko-maxim

**Comment by RomanNikitenko** [comment]
@ibuziuk 
There are 5 stacks in the PR description, I tested creation of workspace for those stacks on the `dogfooding` instance.
A workspace starts successfully for `django`, `go`, `python`, it still fails for `java-vertex` and `wildfly`.

I see that new versions (with fixed devfile) for the stacks are still absent on the devfile.io:

<img width="470" alt="image" src="https://github.com/eclipse/che/assets/5676062/10f22aa1-a9ff-423e-bd9f-6e60c422d71c">

Do you know when it's going to be updated?
At the same it's OK for me to close the current issue as the PRs were merged and we are just waiting for update on the devfile.io side.

**Comment by ibuziuk** [comment]
@RomanNikitenko is it still outdated or the issue can be resolved

**Comment by RomanNikitenko** [comment]
At the moment the registry doesn't contain my changes, but I guess it should be updated tomorrow:
https://github.com/devfile/registry?tab=readme-ov-file#registry

> The public registry is updated weekly, by 12pm EST Wednesdays, with any updated stacks in this repository.

**Comment by RomanNikitenko** [comment]
The devfile registry was updated,
I successfully started workspaces for `WildFly Bootable Jar` and `Vert.x` Java stacks

<img width="869" alt="image" src="https://github.com/eclipse/che/assets/5676062/0279dee3-200a-4150-8190-4fb444d0322f">

<img width="773" alt="image" src="https://github.com/eclipse/che/assets/5676062/1a3cb619-492b-4490-8edc-622f2a158638">
