### ISSUE TITLE
Devfile Registry builder tool broken when using --rhel option

### ISSUE THREAD

**Issue by rafaeltuelho** [eclipse/che#22528]
### Describe the bug

Trying to build a custom Devfile Registry using the `build.sh` script from https://github.com/eclipse-che/che-devfile-registry, but when I choose the RHEL (actually Centos) based image passing the `--rhel` option the build breaks:

```
error: cannot update repo 'centos-8-for-appstream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for http://mirror.centos.org/centos-8/8/AppStream/x86_64/os/repodata/repomd.xml (IP: 64.176.215.221)
+ microdnf --enablerepo=fedora30-updates --enablerepo=fedora30-secondary-updates install -y skopeo jq
```

This happens because the Centos 8 Appstream was deprecated and is not available anymore: http://mirror.centos.org/centos-8/8/AppStream

### Che version

7.74@latest

### Steps to reproduce

1. clone https://github.com/eclipse-che/che-devfile-registry
2. run `build.sh` using `--rhel`

### Expected behavior

Build a Devfile Registry image using RHEL Ubi8 base image

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by ibuziuk** [comment]
@svor can we close the issue now?
