### ISSUE TITLE
Fix the PROW CI e2e test for DWO project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse/che#22535]
### Is your task related to a problem? Please describe

* After implementing the nodeJs version 18.1 in the chectl project, the chectl tool needs some specific libs for correct working. It needs an image based on NodeJs v.18.1 and adding some specific binaries: 
https://github.com/che-incubator/chectl/commit/499bc11e5ab989a7f96270a7c814f12a6469bb58#diff-6704820b78e3aea8581dff31b66a527b85fc1e2635264f0c6961acb16529ff24R14-R31
This is the main reason for failures of e2e test in the DWO repo:
- https://github.com/devfile/devworkspace-operator/pull/1174
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_devworkspace-operator/1174/pull-ci-devfile-devworkspace-operator-main-v8-devworkspace-operator-e2e/1700185805533745152 (Error: node is not installed.
).

### Describe the solution you'd like

The main Idea is to try to create a new runner image that contains all binaries and libs for node js:
https://github.com/che-incubator/chectl/commit/499bc11e5ab989a7f96270a7c814f12a6469bb58#diff-6704820b78e3aea8581dff31b66a527b85fc1e2635264f0c6961acb16529ff24R14-R31
And add GO + other tolls (yq, python libs)

### Describe alternatives you've considered

Theoretically, I will try to use a custom Image from Quai for this repo, but I am unsure if it will work.

### Additional context

* https://github.com/openshift/release/pull/43556
* https://github.com/devfile/devworkspace-operator/pull/1176

**Comment by l0rd** [comment]
This issue status is "Done" but it's still open.
