### ISSUE TITLE
Reduce amount of logs produced by the dashboard pod

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22533]
### Is your task related to a problem? Please describe

Under some conditions, the dashboard pod generates a huge number of logs, which leads to increased resource usage. 

### Describe the solution you'd like

We need to look at what gets logged and try to reduce the amount of logs.

Additionally, add the ability to set the log level via an environment variable.

**Comment by l0rd** [comment]
A user reported that Dashboard resource usage has increased significantly with Dev Spaces 3.7 (his Che instance is used by around 100 developers). @akurinnoy can it be related to this?

**Comment by akurinnoy** [comment]
@l0rd Yes, it is very likely they are related.
