### ISSUE TITLE
[che-release] Add status badges and links to actions 

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22549]
### Is your task related to a problem? Please describe

So that we can see the status of the latest release in one place without having to scroll a bunch of messages in MM or slack, it was suggested on today's cabal that we could instead use the README in che-release to list the status of all the projects that make up a release

### Describe the solution you'd like

Add status badges and links to release GH actions so we can see the status and debug problems from a single dashboard view.

**Comment by l0rd** [comment]
Using `shields.io`:

![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release.yml?label=che-operator%20release)
![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release-che-docs.yml?label=che-operator%20release-che-docs)
![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release-chectl.yml?label=che-operator%20release-chectl)
![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release-community-operator-PRs.yml?label=che-operator%20release-community-operator-PRs)
![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release-helm-charts.yaml?label=che-operator%20release-helm-charts)
![GitHub Workflow Status (with event)](https://img.shields.io/github/actions/workflow/status/eclipse-che/che-operator/release-next-catalog-and-operator-image.yaml?label=che-operator%20release-next-catalog-and-operator-image)

**Comment by nickboldt** [comment]
Merged: https://github.com/eclipse-che/che-release/pull/82

Dashboard for statuses is now: 

https://github.com/eclipse-che/che-release#statuses

**Comment by SDawley** [comment]
@nickboldt 
The badge in the che-release README for che-server reads successful but the release workflow wasn't :/ 
https://github.com/eclipse-che/che-server/actions/runs/6563685717

**Comment by nickboldt** [comment]
![image](https://github.com/eclipse/che/assets/227597/a83cb432-9700-4281-b295-2a832c5c93c6)

**Comment by nickboldt** [comment]
https://github.com/eclipse-che/che-server/actions/runs/6566023490/job/17835826105 has passed and now we see:

![image](https://github.com/eclipse/che/assets/227597/ba55f410-bb61-4d78-9b01-05ee652853d2)

**Comment by ibuziuk** [comment]
@nickboldt can we close?
