### ISSUE TITLE
Generate E2E typescript test report for ReportPortal

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22543]
### Is your task related to a problem? Please describe

Make it possible to generate test report for ReportPortal https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com

### Describe the solution you'd like

Use [@reportportal/agent-js-mocha](https://github.com/reportportal/agent-js-mocha#readme) library.

[Reporter option](https://github.com/reportportal/agent-js-mocha#reportportalagent-js-mocha):
```
const mochaMain = new Mocha({
  reporter: '@reportportal/agent-js-mocha',
  reporterOptions: {
    endpoint: 'https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/api/v1',
    token: 'RP_TOKEN',
    launch: 'RP_LAUNCH_NAME',
    project: 'RP_PROJECT_NAME',
    description: 'RP_LAUNCH_DESCRIPTION'
  },
  timeout: 250000
});
```
There are dedicated projects:
- project for **devspaces** test reports: https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/ui/#devspaces/dashboard
- project for **che** test reports: https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/ui/#che/dashboard

### Additional context

Downstream issue: https://issues.redhat.com/browse/CRW-1433

**Comment by nallikaea** [comment]
https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/
