### ISSUE TITLE
Che-dashboard build is failing after reaching a certain point

### ISSUE THREAD

**Issue by moonbse** [eclipse/che#22545]
### Describe the bug

I am noticing that connection is breaking during build when I run Task for build, it goes upto [webpack.Progress] 92% sealing asset processing copy-webpack-plugin and gets disconnected. I tried on firefox and chrome too , doesn't look like browser.

I am having difficult retrieving logs command once this websocket connection breaks, cpu utilization peaks to 60-80 percent and remains there until I stop the server from command line. Other thing I noticed is slow response to cli commands, it seems like server gets stuck somewhere. Fans are running at full speed.

`chectl server:stop` is not responding, I am unable to close workspace from UI too. Finally deleted the cluster using `minikube delete `and CPU utilisation dropped instantly and fans stopped
`kubectl logs -f che-dashboard-6686df4989-w9ftn -n eclipse-che`
Unable to connect to the server: net/http: TLS handshake timeout
this happens everytime I am triggering build task

`kspaced0975cc37e4447eb-7cdbd766b9-zvb89" is waiting to start: PodInitializing
[WARN] The WebSocket connection closed. Code: 1001, reason: 
[ERROR] Stopped watching /api/v1/namespaces/admin-che/pods. Reason: null
[ERROR] Stopped watching /api/v1/namespaces/admin-che/events. Reason: null
[ERROR] Stopped watching /api/v1/namespaces/admin-che/events. Reason: null
[ERROR] Stopped watching /apis/workspace.devfile.io/v1alpha2/watch/namespaces/admin-che/devworkspaces. Reason: null
error: http2: client connection lost
Tried again same result, build breaking at the same point. Have live logs of dashboard pod open` 

This is log file ending after connection breaks.

### Che version

7.74@latest

### Steps to reproduce

1. Copy https link of che-dashboard repository
2. It Opens up a workspace for same, run task for installing dependencies.
3. Try running Task for devfile build : it goes to a point and then connection breaks and cpu utilisation peaks and remains there. At this point we are not able to stop the workspace or anything.

final out of terminal looks something like this: 

`@eclipse-che/dashboard-backend: <s> [webpack.Progress] 87% sealing code generation
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 88% sealing runtime requirements
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 88% sealing runtime requirements
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 89% sealing hashing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 89% sealing hashing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 89% sealing after hashing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 89% sealing after hashing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 90% sealing record hash
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 90% sealing record hash
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 91% sealing module assets processing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 91% sealing module assets processing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 91% sealing chunk assets processing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 91% sealing chunk assets processing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 92% sealing asset processing
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 92% sealing asset processing copy-webpack-plugin
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 92% sealing asset processing copy-webpack-plugin
@eclipse-che/dashboard-backend: <s> [webpack.Progress] 92% sealing asset processing TerserPlugin`

### Expected behavior

It should build the application and give a localhost url to run it

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
kubectl logs -f che-dashboard-6686df4989-w9ftn -n eclipse-che
Unable to connect to the server: net/http: TLS handshake timeout
this happens everytime I am triggering build task
logs I retrieved before running build command
Server listening at http://0.0.0.0:8080
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'event',
  params: { namespace: 'admin-che', resourceVersion: '6718' }
}
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'pod',
  params: { namespace: 'admin-che', resourceVersion: '6718' }
}
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'devWorkspace',
  params: { namespace: 'admin-che', resourceVersion: '6718' }
}
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'event',
  params: { namespace: 'admin-che', resourceVersion: '6840' }
}
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'pod',
  params: { namespace: 'admin-che', resourceVersion: '6840' }
}
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'devWorkspace',
  params: { namespace: 'admin-che', resourceVersion: '6840' }
}
[INFO] WS message: { method: 'UNSUBSCRIBE', channel: 'logs', params: {} }
[INFO] WS message: {
  method: 'SUBSCRIBE',
  channel: 'logs',
  params: {
    namespace: 'admin-che',
    podName: 'workspace79d814d871dc4cad-674db46685-x8wgv'
  }
}
[WARN] The WebSocket connection closed. Code: 1001, reason:
```

**Comment by moonbse** [comment]
Unable to watch logs with following on running

`kubectl logs -f che-dashboard-768c76457-kx5nd -n eclipse-che --timestamps
`
I have following pods running with their status:

`admin-che                 workspace36d22fc5bc4a4103-6669f5bc79-xwbmf         2/2     Running     0             26m
cert-manager              cert-manager-677874db78-mh277                      1/1     Running     2 (44m ago)   45m
cert-manager              cert-manager-cainjector-6c5bf7b759-cwrsc           1/1     Running     2 (44m ago)   45m
cert-manager              cert-manager-webhook-5685fdbc4b-gq2ln              1/1     Running     2 (44m ago)   45m
devworkspace-controller   devworkspace-controller-manager-594897dfbd-vxtgs   2/2     Running     0             43m
devworkspace-controller   devworkspace-webhook-server-99df6fb7c-xfq47        2/2     Running     0             42m
dex                       dex-c6d746d9c-nqwnv                                1/1     Running     3 (43m ago)   44m
eclipse-che               che-74cc8c4bf4-5pbfx                               1/1     Running     0             33m
eclipse-che               che-dashboard-768c76457-kx5nd                      1/1     Running     0             33m
eclipse-che               che-gateway-7c8b6f5df5-qj92p                       4/4     Running     0             33m
eclipse-che               che-operator-64567d845c-snfzs                      1/1     Running     0             42m
eclipse-che               che-tls-job-jsx6t                                  0/1     Completed   0             41m
eclipse-che               devfile-registry-8596b9bd78-66n66                  1/1     Running     0             41m
eclipse-che               plugin-registry-6cdc4b77db-ccqps                   1/1     Running     0             40m
ingress-nginx             ingress-nginx-admission-create-crfwd               0/1     Completed   0             47m
ingress-nginx             ingress-nginx-admission-patch-rmztg                0/1     Completed   0             47m
ingress-nginx             ingress-nginx-controller-64d5884ccb-4d66d          1/1     Running     2 (44m ago)   47m
kube-system               coredns-64897985d-qwgkc                            1/1     Running     2 (44m ago)   47m
kube-system               etcd-minikube                                      1/1     Running     3 (43m ago)   47m
kube-system               kube-apiserver-minikube                            1/1     Running     0             43m
kube-system               kube-controller-manager-minikube                   1/1     Running     0             43m
kube-system               kube-proxy-29nw9                                   1/1     Running     3 (43m ago)   47m
kube-system               kube-scheduler-minikube                            1/1     Running     2 (44m ago)   47m
kube-system               storage-provisioner                                1/1     Running     3 (43m ago)   47m
`

`2023-09-25T06:43:21.753983293Z Unable to watch logs of che-gateway in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "che-gateway" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:21.754442481Z container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:21.754465141Z Unable to watch logs of tools in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:24.784027712Z container "che-gateway" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:24.784412914Z Unable to watch logs of che-gateway in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "che-gateway" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:24.789915678Z container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:24.790366081Z Unable to watch logs of tools in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:27.808101661Z container "che-gateway" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:27.809366304Z Unable to watch logs of che-gateway in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "che-gateway" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:27.811184414Z container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:43:27.811279225Z Unable to watch logs of tools in workspace36d22fc5bc4a4103-6669f5bc79-xwbmf: container "tools" in pod "workspace36d22fc5bc4a4103-6669f5bc79-xwbmf" is waiting to start: PodInitializing
2023-09-25T06:50:07.028918468Z [WARN] The WebSocket connection closed. Code: 1001, reason:`

**Comment by moonbse** [comment]
Once websocket connection breaks during build it keeps retrying without any success 
![Uploading Screenshot from 2023-09-25 15-04-07.png…]()

**Comment by l0rd** [comment]
@moonbse my guess is that your laptop (more likely the VM where minikube runs) doesn't have the resources required by the dev environments specified by the Che dashboard devfile (in particular CPU). The devfile specifies limits of 5 CPU and 10GB of RAM.

**Comment by moonbse** [comment]
@l0rd this was indeed the issue, increased the VM cpus to 6 and memory to 12G, it built successfully.
