### ISSUE TITLE
Trigger slack notifications from chectl release action

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#22551]
### Describe the solution you'd like

replace https://github.com/eclipse-che/che-release/blob/main/.github/workflows/release-send-mattermost-announcement.yml with an action that notifies: ECD slack channel #forum-che-release that a release is done.

WIP in https://github.com/eclipse-che/che-release/blob/addSlack/.github/workflows/release-send-slack-announcement.yml

Message should be short, with link to release notes for that version.

Ths should be triggered when a new chectl release is completed, from https://github.com/che-incubator/chectl/blob/main/.github/workflows/release-announce.yml (but could also be triggered by workflow)

### Additional context

Rather than writing a bot/webhook/app, using built in slack notifications work pretty well.

https://github.com/integrations/slack#configuration

See also:

* https://docs.google.com/document/d/1x1QooSXn1AYkL9LJljuxJteQgJYVltNL37WyJV2N2fY/edit#heading=h.8wiks6s8memb
* https://github.com/eclipse/che/issues/22549
* https://github.com/eclipse/che/issues/22550

**Comment by nickboldt** [comment]
nothing showing up in https://app.slack.com/client/TMU5A34SW/C05SD64M85R yet 

asked for slack integration to be added to the che-incubator repos (starting with chectl) so we can at least watch for events there.

**Comment by nickboldt** [comment]
PR notification working: 
![image](https://github.com/eclipse/che/assets/227597/3ce93022-c2f4-4f60-bf8f-29a788210158)
and updates automatically as tests pass/fail too:
![image](https://github.com/eclipse/che/assets/227597/347a3baf-d143-4f6d-a963-a4a6bceb8394)

**Comment by nickboldt** [comment]
![image](https://github.com/eclipse/che/assets/227597/5f3f38a6-0727-4da6-bf00-02dbaf01071c)

h2. working: issues, pulls, releases, branches/tags, issues:

`/github subscribe che-incubator/chectl pulls`

* includes link to the PR, repo, and tests; slack message updates automatically as changes happen / workflows run

`/github subscribe che-incubator/chectl releases`

* includes link to the release, eg https://github.com/che-incubator/chectl/releases/tag/20231013185130

`/github subscribe che-incubator/chectl branches`

* includes link to the branch/tag and repo on creation (and a notification if deleted too)

`/github subscribe eclipse/che issues`

* includes a link to the issue, repo and threaded comments under it (if comments enabled); otherwise just creation and closure are reported

------

h2. also working: comments and deployments (probably overkill / too verbose):

`/github subscribe eclipse/che issues comments `

* includes a link to the issue, repo and threaded comments under it; also creation and closure are reported

`/github subscribe che-incubator/chectl deployments`

* includes link to the action that deployed the gh page

**Comment by nickboldt** [comment]
Events to track:

```
/github subscribe che-incubator/chectl releases workflows:{event:"workflow_dispatch","push" branch:"main"}  
/github unsubscribe che-incubator/chectl issues pulls commits deployments branches

/github subscribe eclipse-che/che-operator workflows:{event:"workflow_dispatch","push" branch:"main"}
/github unsubscribe eclipse-che/che-operator issues pulls commits releases deployments branches

/github subscribe eclipse-che/che-release workflows:{event:"workflow_dispatch","push" branch:"main"}
/github unsubscribe eclipse-che/che-release issues pulls commits releases deployments branches

/github subscribe eclipse/che issues releases +label:'status/need-triage'
/github unsubscribe eclipse/che pulls commits deployments branches

/github subscribe list features
```

**Comment by ibuziuk** [comment]
@nickboldt can we close?

**Comment by nickboldt** [comment]
if you're happy with the outcome here, then yes. Closing
