### ISSUE TITLE
Implement automated reporting of devsandbox periodic jobs into Slack

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse/che#22556]
### Is your enhancement related to a problem? Please describe

Currently reporting has to be done manually, this feature should enable automated reporting of pipeline status

### Describe the solution you'd like

We already have an approved slack app and an existing library in jenkins. I just need to use the logic in our periodic jobs and modify it a little bit

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ibuziuk** [comment]
closing as duplicate https://github.com/eclipse/che/issues/22490
