### ISSUE TITLE
Workspace Does not Automatically Refresh to reflect installed extensions or workspace settings - Safari Browser

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22571]
### Describe the bug

On the creation of a new workspace, VS Code no longer automatically refreshes to reflect installed extensions or workspace settings.

This behavior seemed to start with release 7.74 and persists in 7.75.

### Che version

7.75@latest

### Steps to reproduce

Create a workspace from: [https://github.com/quarkus-super-heroes-dev-ex/quarkus-super-heroes-dev-ex-edition.git](https://github.com/quarkus-super-heroes-dev-ex/quarkus-super-heroes-dev-ex-edition.git)

Observe that extensions start to install automatically, but that the extension view does not refresh to reflect completed install, nor does the color theme change to reflect the settings in the `code-workspace` file.

### Expected behavior

Extensions are installed, and the workspace automatically refreshes to reflect the changes.

### Runtime

OpenShift

### Screenshots

Observed Behavior - The workspace is not refreshing:

<img width="1119" alt="Screenshot 2023-09-28 at 7 51 10 AM" src="https://github.com/eclipse/che/assets/39659182/ad69cf7c-de1b-40b1-9126-0a6c35c78483">

After a Browser Reload of the page, the workspace refreshes properly:

<img width="947" alt="Screenshot 2023-09-28 at 7 51 28 AM" src="https://github.com/eclipse/che/assets/39659182/9b63fec1-6e40-4655-a3bd-d8b2c2156d7d">

### Installation method

OperatorHub

### Environment

macOS

**Comment by ibuziuk** [comment]
@l0rd @azatsarynnyy @vitaliy-guliy  could it be related to https://issues.redhat.com/browse/CRW-4790

**Comment by azatsarynnyy** [comment]
Should be fixed by https://github.com/microsoft/vscode/pull/203972
