### ISSUE TITLE
Terminal welcome message to help with Git setup, Workspace customization and Devfile creation

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22581]
### Is your enhancement related to a problem? Please describe

For developers it's not straightforward to figure out how to setup git (if that's not automatically setup), how to customize a workspace and how to use a devfile. 

### Describe the solution you'd like

Do something similar to what GitHub codespaces does:

<img width="1449" alt="image" src="https://github.com/eclipse/che/assets/606959/a88cd0ce-d241-4145-bddd-05c7690f3dad">

**Comment by dmytro-ndp** [comment]
@l0rd : Terminal message will be duplicating _Welcome_ page inside VS Code Editor, and _User Preferences_ page in Dashboard.
Taking that into account, I have set label severity/P2.

Feel free to change severity of issue if it was wrong assumption.
