### ISSUE TITLE
Change Login, Logout, Stop and delete workspace tests to be hooks (suileSetup, suiteTeardown)

### ISSUE THREAD

**Issue by nallikaea** [eclipse/che#22587]
### Is your task related to a problem? Please describe

On previous approach when each test was starting on new stage there was necessary to have Login tests before each test file. Now, if we run test one by one it looks redundant. We should keep one test spec to check login and logout, in other cases move this logic into suiteSetup hook, which will check if user logged and perform login if not. 
The same with deleting workspace by UI. We can check once and perform this action by API to save regression run time.

### Describe the solution you'd like

https://github.com/eclipse/che/blob/0811b7e4873b8d7ab3625eb4988a534fa538993d/tests/e2e/tests-library/LoginTests.ts#L31

Method should be updated according to logic above. Test files which used the methods should be updated.

**Comment by dmytro-ndp** [comment]
Stop and delete workspace looks differently from login/logout, because each test should delete test workspace after its execution, doesn't matter if it fail or succeed, to not affect next test execution.

**Comment by dmytro-ndp** [comment]
+1
