### ISSUE TITLE
Add devfile validation mechanism to the generator tool

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22594]
### Is your enhancement related to a problem? Please describe

   Now the devfile schema is not validated on the che-dashboard side before creating a devworkspace. But the che-dashboard added some changes to the origin devfile before creating a workspace.  
   We should have a client-side schema validation before creating a devworkspace to prevent possible errors.

### Describe the solution you'd like

Add schema validation into [devworkspace-generator](https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator). It will be the best place for schema validation before generating a new devworkspace object.

After adding schema validation into [devworkspace-generator](https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator), we could remove schema validation from the [che-server](https://github.com/eclipse-che/che-server).  

[issuecomment](https://github.com/eclipse-che/che-dashboard/pull/945#issuecomment-1753145554)

**Comment by svor** [comment]
Related PR was merged, ["@eclipse-che/che-devworkspace-generator": "next"](https://www.npmjs.com/package/@eclipse-che/che-devworkspace-generator?activeTab=versions) was published and t[he dashboard should already use it](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-backend/package.json#L30C5-L30C54)
