### ISSUE TITLE
Add a way to reject the authorisation opt-out flag from the dashboard

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22600]
### Is your task related to a problem? Please describe

when https://github.com/eclipse-che/che-server/pull/576 is merged, the only way to reject the authorisation opt-out flag would be manually editing the `workspace-preferences` config-map.

### Describe the solution you'd like

Update the `Git Services` tab of the `User Preferences` dashboard page: 
* When an SCM authorisation is rejected add the corresponding item to the `Git Services` tab.
* The tab should have some additional label to mark it as an authorisation reject item.
* When the workspace create/start page is reloaded after the authorisation reject (url with the `error_code=access_denied` query parameter) show a notification with the description that the authorisation page will not appear for the specific SCM provider, and some instructions how to revert the option back from the `Git Services` tab.

**Comment by akurinnoy** [comment]
Hi @vinokurig @olexii4,

Please have a look at the picture below - that is how I believe the git services page may look like:




![mockup_git_services](https://github.com/eclipse/che/assets/16220722/e3880d49-5a68-4a33-b71e-6a72431445d6)

cc @ibuziuk
