### ISSUE TITLE
Make the workspace aware when a user has been logged out.

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22619]
### Is your enhancement related to a problem? Please describe

When my user session expires in OpenShift, the Dev Spaces workspace appears to be unaware.  

From a UX perspective the workspace appears to stop working properly.

It is not until I attempt to restart the "broken" workspace that I am prompted to login to OpenShift.

### Describe the solution you'd like

The workspace should alert a user that their session is about to expire and give them the opportunity to re-authenticate without restarting the workspace.

**Comment by AObuchow** [comment]
@cgruver just to make sure, the desired UX would ressemble something like: CheCode gives you a dialog box prompting to redirect you to the OpenShift authentication page, in a separate browser tab?

**Comment by cgruver** [comment]
@AObuchow Yes.  That would be a better UX.  It needs some sort of indication that your login session has expired.  Currently it just looks like the workspace broke until you realize that you just need to log in again.
