### ISSUE TITLE
Need support in deploying Eclipse-che on ASK

### ISSUE THREAD

**Issue by sharmila1310** [eclipse/che#22610]
### Summary

Hi..  Good Day!
I have been trying to deploy eclipse-che on AKS for about 20 days from know. 
I created a AKS cluster integrated with Azure Active Directory.
Need support with configuring OAuth2 Proxy.  I have a domain in godaddy, not sure for eclipse-che, should a create a subdomain name mapping to where?  
Is there any source where i can get full detials on deploying che on AKS, any one can please helm me out with this. Worked smothly on Minikube on local system.

**Comment by tolusha** [comment]
Hello @sharmila1310 

We are looking for contributions from the community as part of https://github.com/eclipse/che/issues/22392
We already have the community-contributed blog post for setting up Eclipse Che on Azure that might be helpful - https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html

**Comment by karatkep** [comment]
@ibuziuk, Hi Ilya, 
Sorry for delay with response, was quite busy on my project. Yes, for sure, I can help with some sort of documentation. Please let me know communication channel to discuss.

**Comment by sharmila1310** [comment]
Thanks a lot for your reply...
I am trying to deploy che on AKS. I need this workspace setup for my current project. Totally new to eclipse-che. I am trying for past 2 months. I am not sure about OIDC provider  and DNS. 
Please, you decide on communication channel.. we can connet. 
Thank you
Sharmila

**Comment by tolusha** [comment]
@sharmila1310 
Please find the guide here [1]
Feel free to ask any questions.

[1] https://eclipse.dev/che/docs/next/administration-guide/installing-che-on-microsoft-azure/
