### ISSUE TITLE
Can anyone please create a document for deploying Eclipse che on Azure Kubernetes Service ( i am struck with OIDC provider part)

### ISSUE THREAD

**Issue by sharmila1310** [eclipse/che#22613]
### Summary

Looking for a document, which explains how to deploy eclipse Che on Azure Kubernetes service. Please, can anyone share s clear document, it will be very useful for many. Thanks a lot

**Comment by tolusha** [comment]
@sharmila1310 
Please try https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-microsoft-azure/

**Comment by sharmila1310** [comment]
Thanks a lot @tolusha , for all your efforts. :)
