### ISSUE TITLE
Rework "Overview" and remove "DevWorkspace" tab from the "Workspace Details"

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22612]
### Is your enhancement related to a problem? Please describe

Rework "Overview" and remove "DevWorkspace" tab from the "Workspace Details"

### Describe the solution you'd like

![image](https://github.com/eclipse/che/assets/1461122/cd7d4ad3-db27-41de-8512-177e51ca4209)
- [ ] 'Workspace Details' link should open the 'Overview' tab (currently it opens 'Devfile' tab)
- [ ] Remove 'DevWorkspace' Tab
- [ ] On the 'Overview' tab replace 'Workspace name' with the 'Workspace' field which links to the DevWorkspace object (initial implementation was done as part of https://github.com/eclipse/che/issues/22422)

**Comment by ibuziuk** [comment]
@l0rd please, review the proposal
cc: @olexii4 @akurinnoy

**Comment by l0rd** [comment]
Looks good 👍

**Comment by akurinnoy** [comment]
>  'Workspace Details' link should open the 'Overview' tab (currently it opens 'Devfile' tab)

@ibuziuk I'm not able to reproduce this behavior on the dogfooding cluster, I always get the Overview tab opened. Can you check if the issue persists on your side?

**Comment by ibuziuk** [comment]
@akurinnoy yes, I can reproduce it consistently on dogfooding 
<img width="1450" alt="Screenshot 2023-11-15 at 15 28 24" src="https://github.com/eclipse/che/assets/1461122/7360ce82-bf2d-4ee3-ad76-39a97ad61703">

**Comment by akurinnoy** [comment]
@ibuziuk I have completely forgotten about this menu item, thanks!
