### ISSUE TITLE
Add dependent projects supports in VS Code launcher

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22629]
### Is your enhancement related to a problem? Please describe

We recently added [`dependentProjects`](https://github.com/devfile/api/issues/1082) in the devfile spec. But VS Code launcher only looks at [projects](https://github.com/che-incubator/che-code/blob/main/launcher/src/code-workspace.ts#L60) and won't include those in the `vscode-workspace` file.

### Describe the solution you'd like

Launcher should add `dependentProjects` too.

**Comment by amisevsk** [comment]
Progress here would be blocked until the dependentProjects PR makes it way into a Devfile API release and DevWorkspace pulls in that new version. Otherwise, dependentProjects cannot be added to a DevWorkspace.

**Comment by l0rd** [comment]
Ok so even devworkspace next is not including that right? And it's not included in 2.2.1 but we need a 2.2.2?

**Comment by amisevsk** [comment]
Yes, dependentProjects will land in devfile 2.2.2, and DWO v0.24 is built off devfile 2.2.1. We can accelerate the process by depending on a non-tagged version of devfile/api and pull changes in quicker, however -- it depends on priority for dependentProjects and devfile/api's release cadence (which if past releases are an indicator, could be a long time)

**Comment by l0rd** [comment]
> it depends on priority for dependentProjects and devfile/api's release cadence (which if past releases are an indicator, could be a long time)

I think it was decided to release a new Devfile API "on demand" so we could ask to release v2.2.2 this sprint so that we can move forward with this cc @yangcao77

**Comment by vitaliy-guliy** [comment]
I have opened a [pull request](https://github.com/che-incubator/che-code/pull/302), but cannot test it because devfile v2.2.2 is not supported yet.

It's like a note, that we have to return to the PR after updating the DWO to DevFile API v.2.2.2

**Comment by AObuchow** [comment]
@vitaliy-guliy sounds good, once DWO 0.25.0 is released upstream we should be good to test your PR as the update to DevFile API v2.2.2 [was merged](https://github.com/devfile/devworkspace-operator/pull/1202). Technically, though, myself or @amisevsk should be able to get you a nightly build version of DWO to test.

**Comment by amisevsk** [comment]
I've almost got a DWO update ready, just need to test it quickly on a real cluster

**Comment by amisevsk** [comment]
PR: https://github.com/devfile/devworkspace-operator/pull/1205

**Comment by vitaliy-guliy** [comment]
The functionality is added to the launcher and covered with corresponding unit tests.
Will work successfully when the dashbord supports devfile v2.2.2.
