### ISSUE TITLE
Pre-create `.m2` directory in UDI images to avoid common pitfalls

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22620]
### Is your enhancement related to a problem? Please describe

When creating a new devfile for a project (and not working off of an existing sample), it's possible to shoot yourself in the foot and hit a dead end due to how Kubernetes and OpenShift manage mounting files to DevWorkspaces. 

Imagine I'm a new-ish user and I attempt to create a devfile for my Java maven project:

1. I start with a basic devfile, starting a single UDI container that clones my project
2. Then, I decide I would like to add my maven `settings.xml` file, and I find a page in the Che docs documenting exactly how to do that: https://eclipse.dev/che/docs/stable/end-user-guide/mounting-secrets/
3. After creating the recommended secret, I test my workspace, and find that maven does not work, with an error like
    ```
    [ERROR] Could not create local repository at /home/user/.m2/repository -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
    ```

At this point, I likely have to open an issue to figure out what's going wrong.

What has happened behind the scenes is that e.g. OpenShift has mounted my `settings.xml` to `/home/user/.m2/settings.xml`. However, since the `/home/user/.m2` directory did not exist at start, it was automatically created with owner `0` and `755` permissions, preventing my regular user in the container from accessing it:

```
projects $ ls -al /home/user/.m2
total 4
drwxr-xr-x. 2 root root       26 Oct 20 16:34 .
drwxrwxr-x. 1 root root       30 Oct 20 16:34 ..
-rw-r-----. 1 root 1002860000  4 Oct 20 16:34 settings.xml
```

(The fix here, and the reason it doesn't happen for samples, is that the samples contain an `.m2` volume that creates the directory with appropriate permissions)

### Describe the solution you'd like

The UDI container should pre-create the (empty) `.m2` directory with appropriate permissions (`777`). This would allow maven to keep working in the above example, and let the user decide later that they also would like to mount an `.m2` volume as we do in samples to keep their downloaded artefacts between workspace runs.

### Describe alternatives you've considered

Update documentation to explain this caveat with mounting files from configmaps/secrets in documentation, and potentially also include documentation around setting up workspace volumes (i.e. you generally want a volume to store dependencies, node modules, etc. so they don't have to be downloaded every time you start the workspace)

**Comment by l0rd** [comment]
If that's not too hard I would extend the scope of this issue to other folder such as

```
$HOME/certs
$HOME/.gradle
$HOME/.config/pip
```

**Comment by AObuchow** [comment]
Related: [Pre-create common tooling config directories for installed tools in UDI image](https://github.com/eclipse/che/issues/22029). We might want to close the current issue as a duplicate, or we can leave it open as a task for the relate issue, since it has a smaller scope.

**Comment by amisevsk** [comment]
Ah I searched but couldn't find that issue. Closing this one in favor of https://github.com/eclipse/che/issues/22029

**Comment by amisevsk** [comment]
Duplicate of https://github.com/eclipse/che/issues/22029
