### ISSUE TITLE
VS Code launcher should update the projects in vscode-workspace at restart

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22630]
### Is your enhancement related to a problem? Please describe

Currently VS Code launcher is adding projects from the devfile only when the `.vscode-workspace` file doesn't exist. So it does that only at startup. 

The problem is that if a user starts a workspace, adds a new project (or dependent project) in the devfile.yaml and select "restart from local devfile", the new project won't be added to the `.vscode-workspace` file and the user won't see it (although it has been cloned in `/projects`).

### Describe the solution you'd like

Launcher should update an existing `vscode-workspace` file if:
- it was created automatically by the launcher
- the projects have changed

**Comment by SDawley** [comment]
Decided to include in 3.11 release/next sprint.

**Comment by l0rd** [comment]
@vitaliy-guliy can you confirm that if a user starts a new workspace from a git repository with a `.vscode/settings.json` then the VS  Code settings in that file will be applied to the VS Code workspace?
