### ISSUE TITLE
After revoking Che authorization for gitlab.com I cannot authenticate anymore 

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22632]
### Describe the bug

After revoking Che authorization in gitlab.com `User Settings > Applications > Authorized Applications`, trying to clone a **private** GitLab repository fails permanently. 

### Che version

nightly (dogfooding)

### Steps to reproduce

- Login to a Che instance configured with OAuth for gitlab.com (for example che dogfooding)
- Start a workspace from a private gitlab.com repository
- When asked, authorize the Che instance to use your gitlab.com account
- Observe that the workspace is created successfully and that the source code is cloned successfully
- Delete the workspace
- Go in gitlab.com `User Settings > Applications > Authorized Applications` and revoke the authorization to Che application
- Start a new workspace from a private gitlab.com repository (the same or another)
- Observe that the workspace is started but 1) defvile is not found 2) source code is not cloned

### Expected behavior

I would expect that, after revoking the authorization, when starting a new workspace from a gitlab.com private repository I would have been asked again to authorize Che and that the workspace would start successfully (devfile found and sources cloned).

### Runtime

OpenShift

### Screenshots

<img width="657" alt="image" src="https://github.com/eclipse/che/assets/606959/ae4b46c1-1aed-4802-a7ba-b5c26ba63515">

### Installation method

chectl/next

### Environment

Amazon

**Comment by l0rd** [comment]
This looks related to the fact that che-server is somehow caching the git tokens. Even if I revoke the authorization from gitlab.com and if I delete the secrets from my namespace, GitLab still shows up in the Git services tab and che-server never redirects me to the Authorization page.

Related to https://github.com/eclipse/che/issues/22631

**Comment by l0rd** [comment]
I was not able to reproduce the problem on GitHub and Azure DevOps

**Comment by tolusha** [comment]
I was able to reproduce this issue with Eclipse Che 7.76.0
But not anymore with the latest changes.
I can't reproduce this issue on the dogfooding cluster as well.
