### ISSUE TITLE
Not all Git Services are shown in user preferences

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22631]
### Describe the bug

I have setup 3 git services (GitHub, GitLab and AzureDevops):

```bash
$ kubectl get secrets -l "controller.devfile.io/git-credential=true" -o json | \
   jq '.items[].metadata.annotations' | grep "che.eclipse.org/scm-url"
"che.eclipse.org/scm-url": "https://gitlab.com",
"che.eclipse.org/scm-url": "https://github.com",
"che.eclipse.org/scm-url": "https://dev.azure.com",
```

But on dashboard I only see GitLab:

<img width="922" alt="image" src="https://github.com/eclipse/che/assets/606959/8bf6c7e6-250d-4b6c-89d7-86595037f3e2">

### Che version

next (development version)

### Steps to reproduce

On dogfooding instance I have started workspaces from the different:
- azure devops (for example https://marioloriedo@dev.azure.com/marioloriedo/publicproject/_git/public-repo)
- gitlab (for example https://gitlab.com/mario.loriedo/microservices-demo-frontend)
- github

And Che setup successfully the git credential secret for all. But on Dashboard user preferences I can only see GitLab.

### Expected behavior

I would like to see all the git services

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by l0rd** [comment]
Refreshing or using incognito doesn't help. I have added che-server label as dashboard gets the list from che-server that probably keep these info in cache (and if it's restarted lose them).

**Comment by ibuziuk** [comment]
@vinokurig @akurinnoy folks, could you please take a look? 

> I have added che-server label as dashboard gets the list from che-server.

My understanding was that dashboard reads tokens as k8s secrets, without involving che-server at all

> The suspect is that che-server keeps these token in cache, lose them when it's restarted, and add them back to the cache as soon as the developer starts a workspace for the given git service.

@vinokurig I thought that we do not do any caching at all on the che-server end, do we?

**Comment by vinokurig** [comment]
> I thought that we do not do any caching at all on the che-server end, do we?

Right, we do not. 

This looks like something has changed in the Gitlab side. Dashboard displays the Git services items if a token request is successful, but now I see that Gitlab returns the token even if the authorisation is rejected.

**Comment by l0rd** [comment]
@vinokurig this is not GitLab specific. Today we were able to reproduce this problem with GitHub:
- Start a `github.com` workspace for the first and authorize Che to access your GH data
- Go to `User Preferences > Git Services` and observe that github.com is listed
- Restart the che-server pod and observe that github.com is not listed anymore
