### ISSUE TITLE
Changes in workspace get lost if restarting from local Devfile with typo

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22638]
### Describe the bug

With the [recent changes](https://github.com/eclipse-che/che-dashboard/pull/896) the default workspace is started in ephemeral mode (aka "safe mode"). 

This is ok for workspace creation but when it's about a "restart" then all the changes in the workspace get lost.

We should be very careful and avoid proposing to restart in ephemeral mode when it was about the restart of an existing workspace:
- Restart
- Restart using defaults (tooltip: using the default component)
- Edit DevWork### Describe the bug

With the [recent changes](https://github.com/eclipse-che/che-dashboard/pull/896) the default workspace is started in ephemeral mode (aka "safe mode"). 

This is ok for workspace creation but when it's about a "restart" then all the changes in the workspace get lost.

### Che version

next (development version)

### Steps to reproduce

- Start an empty workspace
- Add a few files to the workspace and then add a devfile with an image that doesn't exist (see example below)
- Select restart from local Devfile
- Wait for an error message
- Click the "Restart with default devfile" button.
- Wait for the target workspace to restart and open IDE
- See that the devfile doesn't exist anymore, and all the changes got lost

```yaml
schemaVersion: 2.2.0
metadata:
  name: devfile-with-typo
components:
  - name: tools
    container:
      image: quay.io/does/not/exist
```

### Expected behavior

The workspace should not be restarted in ephemeral mode

**Comment by ibuziuk** [comment]
fixed in main for 7.77.0 https://github.com/eclipse-che/che-dashboard/pull/967
