### ISSUE TITLE
Fix version mismatch in Eclipse Che repos: should be 7.77.0 after release of 7.76.0

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22646]
### Is your task related to a problem? Please describe

[Dmytro] There is outdated version Eclipse 7.76.0 in main branches, while 7.77.0 is expected after release of 7.76.0:

- [x] 7.76.0-SNAPSHOT in [che-server](https://github.com/eclipse-che/che-server/blob/main/pom.xml#L19C1-L19C39)
- [x] 7.76.0-next in [che-dashboard](https://github.com/eclipse-che/che-dashboard/blob/main/packages/common/package.json#L3C1-L3C1)
- [x] 7.76.0-next in [che-devfile-registry](https://github.com/eclipse-che/che-devfile-registry/blob/main/VERSION#L1)
- [ ] 7.76.0-next in [eclipse/che](https://github.com/eclipse/che/blob/main/VERSION)

At the same time version is correct in the next repos:
- 7.77.0-SNAPSHOT in [che-plugin-registry](https://github.com/eclipse-che/che-plugin-registry/blob/main/VERSION#L1)
- 7.77.0-next in [che-code](https://github.com/che-incubator/che-code/blob/main/package.json#L3)

### Describe the solution you'd like

[Nick] Recently, GH action runners were updated to no longer include `hub` already installed, so GH actions that use `hub` need to explictly install it. For example, https://github.com/eclipse-che/che-devfile-registry/pull/793

### Additional context

It was che-bot who created MR with update to next in Eclipse Che repo: https://github.com/eclipse/che/pull/22568#issue-1916434314

**Comment by tolusha** [comment]
> 7.76.0 in [che-operator](https://github.com/eclipse-che/che-operator/blob/main/version/version.go#L16)

That's ok - the latest stable version is printed.

**Comment by dmytro-ndp** [comment]
@tolusha : thanks for the notice.

**Comment by mkuznyetsov** [comment]
Next release will ensure that all versions are properly updated, closing this issue for now
