### ISSUE TITLE
 Consider Making HttpClient.newBuilder() Singleton？

### ISSUE THREAD

**Issue by yankooo** [eclipse/che#22645]
### Summary

Hello team,

While going through the codebase of che-server, I noticed that HttpClient.newBuilder() is invoked multiple times, particularly in object constructors. This approach could lead to the creation of numerous HttpClient instances, each potentially having its own thread pool. Over time, this can result in a significant number of threads.

Considering the overhead of maintaining multiple threads and the fact that HttpClient is designed to be shared, would it make sense to refactor the code to use a singleton pattern for HttpClient? This way, we can have a single, shared instance across the application, reducing the thread count and potentially improving performance.

I'd be eager to hear your thoughts on this and am open to contributing if there's consensus on making this change.

Thank you for your time and consideration.

### Relevant information

<img width="670" alt="image" src="https://github.com/eclipse/che/assets/31951382/5c6eae4c-a391-4b08-95f5-c667479eace2">

**Comment by dkwon17** [comment]
Thank you for the suggestion @yankooo , any thoughts @vinokurig ?
