### ISSUE TITLE
IntelliJ Devfile is not picked up without pushing to git

### ISSUE THREAD

**Issue by Midula22** [eclipse/che#22678]
### Describe the bug

Unlike Vscode, there is no way to restart the workspace with local devfile in InteliJ. Devfile in InteliJ is not picked up without pushing to git and starting a new workspace, IntelliJ Devfile is not picked up without pushing to git and starting a new workspace.

### Che version

7.77@latest

### Steps to reproduce

1. Start a workspace in InteliJ
2. After making changes in the devfile, there is no way to restart the workspace locally. The only way to apply devfile changes is to push the devfile to the git repo and start a new workspace again with applied devfile changes.

where as to apply any devfile changes in a workspace opened in VS Code we have a command palette option.
![Screenshot (69)](https://github.com/eclipse/che/assets/146935657/c76bc630-8774-46b2-abe9-1592402ef69c)

### Expected behavior

There can be a command palette option to restart the workspace locally to apply any changes in the devfile, instead of pushing the changes devfile onto git repo and start a new workspace.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by l0rd** [comment]
@Midula22 thank you for reporting this issue. I am closing it as there is already an issue for that: https://github.com/eclipse/che/issues/22487. Don't hesitate to reopen or open another issue if you have other questions and feedback.
