### ISSUE TITLE
Eclipse Che: Need Github Repo/ source code for Gateway component (Che gateway)

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22679]
### Summary

We are looking for latest che gateway source code. Unable to find it in Github. Please provide the link. We are deploying eclipse che version 7.75

**Comment by tolusha** [comment]
Hello.

Please find the link below
https://github.com/traefik/traefik

**Comment by l0rd** [comment]
@debkantap I am closing this issue as @tolusha provided an answer. Don't hesitate to re-open or open a new one if you have  other questions or concerns.
