### ISSUE TITLE
Support private raw URLs with `?token` parameter on github.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22685]
### Describe the bug

Starting workspaces based on private raw URL from github.com that point to devfile.yaml do not work
<img width="1289" alt="Screenshot 2023-11-23 at 13 46 20" src="https://github.com/eclipse/che/assets/1461122/a0e4f89c-c5e1-4d13-a6f9-91241c5eb991">

### Che version

7.77@latest

### Steps to reproduce

1. open workspaces.openshift.com
2. get raw URL to devfile from a private github repositori
3. try to start a workspace base on this URL
4. ERROR: workspace can not be started - `Cannot build factory with any of the provided parameters. Please check parameters correctness, and resend query.`

Note that it fails with the same error with & without the `token` URL paramater

### Expected behavior

Workspaces are started based on the private raw URLs to devfile from github.com

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

### Additional context

Public raw URLs like https://raw.githubusercontent.com/eclipse-che-demo-app/che-demo-app/main/devfile.yaml work just fine on Developer Sandbox / workspaces.openshift.com

**Comment by vinokurig** [comment]
@ibuziuk This is expected, if the url points to a private repository, then che can not read the content, even if PAT or Oauth is configured. As a workaround, a GitHub PAT can be passed through the url: `https://<che_fqdn>#https://<token>@raw.githubusercontent.com/che-samples/cpp-hello-world/main/devfile.yaml`, see: https://eclipse.dev/che/docs/stable/end-user-guide/starting-a-workspace-from-a-raw-devfile-url/

**Comment by vinokurig** [comment]
If taking into account the token query parameter that comes with the url e.g. `https://raw.githubusercontent.com/vinokurig/private/main/devfile.yaml?token=<token>` then it should work, so this is really a bug.

**Comment by ibuziuk** [comment]
right, I belive the issue is about honoring `?token` URL parameter
