### ISSUE TITLE
Not Possible to use public repositories from https://github.com/ when OAuth for GitHub Enterprise is configured

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22682]
### Describe the bug

When OAuth for GitHub Enterprise is configured starting workspaces from  https://github.com/ are failing with the following error:

<img width="918" alt="Screenshot 2023-11-23 at 13 05 15" src="https://github.com/eclipse/che/assets/1461122/78350f89-4ffe-4205-821b-5e6c95f76f6d">

### Che version

7.77@latest

### Steps to reproduce

1. Install the latest Eclipse Che
2. Configure OAuth for GitHub Enterprise Server
3. Start workspace from one of the private repositories hosted on GitHub Enterprise Server
4. SUCCESS: During workspace startup user is redirected on the OAuth page and workspace is started without any problems
5. Stop the existing workspace and start another one based on public github.com repositories e.g. https://github.com/ibuziuk/meta-workspace
6. ERROR: workspace startup is failing with the "Cannot build factory" message - see screenshot from description

### Expected behavior

workspace from public public github.com repositories e.g. https://github.com/ibuziuk/meta-workspace are started without errors when GitHub Enterprise Serve OAuth is configured.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

Recently functionality for supporting both GitHub Enterprise and GitHub SaaS OAuth providers has been added to the project as part of https://issues.redhat.com/browse/CRW-4840 / https://www.youtube.com/watch?v=WCl3TZwtwKU
However, we need to make sure that even if one provider is configured, workspaces for public repositories from the other provide should be started without any problems:

- [x] **No OAuth is configured** - workspaces  from public repositories of both GitHub enterprise and GitHub SaaS can be started
- [x] **GitHub Enterprise OAuth is configured** - workspaces for public and private GitHub Enterprise repositories can be started + public repositories from github.com
- [x] **GitHub Enterprise & GitHub SaaS OAuth are configured ** - workspaces for both public and private GitHub Enterprise / GitHub SaaS repositories can be started

**Comment by tolusha** [comment]
The issue can be reproduced on 7.74 (DS 3.9) but CAN'T be reproduced on 7.77 (DS 3.10)

But I would like to point out that it is not possible to clone the repo from GitHub Server if OAuth is not configured.
That's because such kind of urls are treated as repository urls from arbitrary git provider and the only way to clone the project is to use a raw devfile url.
