### ISSUE TITLE
Che-in-Che development is broken

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22686]
### Describe the bug

It's not possible to build Che-Code using Che-in-Che development.

### Che version

7.77@latest

### Steps to reproduce

1. Start a workspace using Che-Code repository
2. Run `devfile` commands for the che-in-che development

<img width="903" alt="image" src="https://github.com/eclipse/che/assets/5676062/5625283e-fdc6-47f6-acc4-4e9acc60c1f3">

### Expected behavior

it's possible to build Che-Code

### Runtime

I've faced the problem on the dogfooding instance

**Comment by azatsarynnyy** [comment]
Should be fixed by https://github.com/che-incubator/che-code/pull/312
