### ISSUE TITLE
URL ending with `.git` does not work for GitHub Enterprise Server

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22687]
### Describe the bug

It is not possible to start workspaces based on URL ending with `.git` does not work for GitHub Enterprise Server

### Che version

7.77@latest

### Steps to reproduce

for github.com it is possible to start workspaces based on the following URLs

- https://github.com/ibuziuk/meta-workspace.git
- https://github.com/ibuziuk/meta-workspace

If you put the same repository on GitHub Enterprise Server only the second URL will work, the first one ending with `.git` will fail to start

### Expected behavior

both URLs with and without .git should work for GitHub Enterprise server

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by tolusha** [comment]
It is not possible to reproduce the issue.
I was able to create workspaces in both cases.

**Comment by amisevsk** [comment]
Assigned dashboard label on the assumption the problem lies with resolving the git repo/devfile.

**Comment by ibuziuk** [comment]
@vinokurig thanks for verification, could you please provide the version of the Github Enterprise Server against which it was verifed, and I believe we can close the issue
