### ISSUE TITLE
Add attribute `controller.devfile.io/bootstrap-devworkspace: true` when Devfile resolution via API fails or is not supported

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22697]
### Is your enhancement related to a problem? Please describe

This is a subtask of https://github.com/eclipse/che/issues/22491

### Describe the solution you'd like

After [this recent PR](https://github.com/devfile/devworkspace-operator/pull/1193), when the attribute `controller.devfile.io/bootstrap-devworkspace: true` is set on a DevWorkspace object, then the project clone is configured to search for a devfile and apply it after cloning the DW projects.

To close [the issue to automatically restart a workspace](https://github.com/eclipse/che/issues/22491) and [the epic to support resolving devfiles for any git service](https://github.com/eclipse/che/issues/21951) we need now to automatically add this attribute when the che-server fails to resolve a Devfile (because of an unsupported git service or because an error occurred).

**Comment by ibuziuk** [comment]
@l0rd am I correct that this issue boils down to setting attribute when we start workspace with default devfile

**Comment by ibuziuk** [comment]
@l0rd in this cases, there is a question if we need an extra UI item, clicking on which  the label would be added. If we want to implement it without UI changes, it is not clear when `restart with default devfile` should be shown in general

**Comment by l0rd** [comment]
@ibuziuk, UI item? No, there should be no need. 

What I mean is that if the startup of a workspace fails because of an invalid devfile, we currently prompt the user to `restart with default devfile`. But if the default devfile has `controller.devfile.io/bootstrap-devworkspace: true` then, the `project-clone` container will find the invalid devfile in the git repository and replace the default devfile with it...

**Comment by ibuziuk** [comment]
@l0rd thanks, my understanding is that we should rework when `restart with default devfile` is shown e.g. 

- if workspace failed to start due to the invalid image, `restart with default devfile` is shown and no attribute is injected
- if workspace can not be started because the URL can not be resolved (ssh, gerit, gitea), we do not fail, but instead automatically use with devfile with the `controller.devfile.io/bootstrap-devworkspace: true` annotation

**Comment by l0rd** [comment]
@akurinnoy @svor @olexii4 that's fantastic that you have been able to close this one but when I tried to test it on our dogfooding instance, it didn't work for me.

I have tested using the repository `git@git.sr.ht:~l0rd/public-project-sample` and...

#### The devfile is not resolved

This is expected as sourcehut is an unknown git service for che server:
![image](https://github.com/eclipse/che/assets/606959/5589cc28-1ae4-4c7f-a8ae-009d7c36d05f)

#### There is no `controller.devfile.io/bootstrap-devworkspace: true` attribute

This is **not** expected:
```bash
kubectl get devworkspaces public-project-sample -o json | jq '.spec.template.attributes | keys'
[
  "che-theia.eclipse.org/sidecar-policy",
  "controller.devfile.io/devworkspace-config",
  "controller.devfile.io/scc",
  "controller.devfile.io/storage-type",
  "dw.metadata.annotations"
]
```

And this is `project-clone` init-container log:

```
2023/12/21 14:37:25 Using temporary directory /projects/project-clone-2749812435
2023/12/21 14:37:25 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2023/12/21 14:37:25 Processing project public-project-sample
2023/12/21 14:37:25 Cloning project public-project-sample to /projects/project-clone-2749812435/public-project-sample
Cloning into '/projects/project-clone-2749812435/public-project-sample'...
Warning: Permanently added 'git.sr.ht,173.195.146.142' (ECDSA) to the list of known hosts.
2023/12/21 14:37:25 Cloned project public-project-sample to /projects/project-clone-2749812435/public-project-sample
2023/12/21 14:37:25 Setting up remotes for project public-project-sample
2023/12/21 14:37:25 Fetched remote origin at git@git.sr.ht:~l0rd/public-project-sample
2023/12/21 14:37:25 Moving cloned project public-project-sample from temporary directory /projects/project-clone-2749812435/public-project-sample to /projects/public-project-sample
```

**Comment by svor** [comment]
@l0rd we'll double check the flow. I'll reopen the issue for now

**Comment by l0rd** [comment]
This is what I get now, if I try to start the workspace from `git@git.sr.ht:~l0rd/public-project-sample`:

![image](https://github.com/eclipse/che/assets/606959/f1d75adb-c2d2-4770-823b-d56d7b1e84cb)

There is a Devfile in the git repository, and the DevWorkspace will be able to read it and use it. This prompt to the user is an error.

**Comment by l0rd** [comment]
@ibuziuk from my point of view this issue cannot be resolved yet.

**Comment by l0rd** [comment]
Besides the sourcehut outage, I am still I am wondering: why are we trying to resolve the devfile if the protocol is git+SSH and the host is not amongst one of those for which we support the REST API?

**Comment by l0rd** [comment]
I have tested again this morning and it worked as expected 👍 

The dashboard still says that "Devfile could not be found in... Applying the default configuration" which is misleading but that can be handled as a separate issue.
