### ISSUE TITLE
Fix the happy-path test for the che-dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22698]
### Is your task related to a problem? Please describe

This PR (https://github.com/eclipse-che/che-dashboard/pull/1002) has introduced some changes so that some locators don't match elements on the page, and therefore the happy-path test fails.

### Describe the solution you'd like

Fix locators to match needed elements to make the happy-path test pass.

### Additional context

https://github.com/eclipse-che/che-dashboard/pull/1002#issuecomment-1830373769

**Comment by artaleks9** [comment]
* It seems, in this [PR](https://github.com/eclipse-che/che-dashboard/pull/1002) was changed the locator and the `dashboard-happy-path` failed with error when try to delete workspace on Dashboard:
```
Stop the workspace by UI:
     TimeoutError: Waiting for element to be located By(xpath, //tr[td//a[text()='quarkus-api-example-mg59']]//span[@data-testid='workspace-status-indicator']//*[local-name()='svg' and @fill='green'])
```
* This needs to investigate it and fix up in Che test framework:
https://github.com/eclipse/che/blob/main/tests/e2e/pageobjects/dashboard/Workspaces.ts#L72 -->
https://github.com/eclipse/che/blob/main/tests/e2e/pageobjects/dashboard/Workspaces.ts#L220

**Comment by artaleks9** [comment]
@akurinnoy 
Due the last changes, the part of Xpath locator, which is related to `workspace-status-indicator` -> `//*[local-name()='svg' and @fill='green']` for `Runing` workspace (`@fill='gray'` for `Stopped` workspace) now is modified:
```
Running = 'currentColor'
Stopped = 'var(--pf-global--palette--black-500)'
```

But to use this in the Xpath locator is not good practise.
It would be nice to add some attribute , like `@data-testid=` for `Running/Stopped` workspace and apply it inthe locator.

**Comment by artaleks9** [comment]
@akurinnoy
In the last [**_PR_**](https://github.com/eclipse-che/che-dashboard/pull/1015)  the `dashboard-happy-path` test is success.
The issue is closed.
