### ISSUE TITLE
Add Gateway-based IDEA editor to Che Plugin registry

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#22708]
### Is your task related to a problem? Please describe

Currently, the Gateway-based solution for running IDEA in Che Workspace is hosted in my personal account. So, it's not possible to use it from the Dashboard like other IDEs.

### Describe the solution you'd like

- add a new editor definition to Che Plugin regsitry
- publish the sources to https://github.com/che-incubator GH org
- setup a GH action for publishing a new image to https://quay.io/repository/che-incubator account

**Comment by azatsarynnyy** [comment]
The sources are added to https://github.com/che-incubator/che-idea-dev-server/tree/main
The images published to https://quay.io/repository/che-incubator/che-idea-dev-server?tab=tags
The editor definition is added to the plugin registry by https://github.com/eclipse-che/che-plugin-registry/pull/1843

**Comment by ibuziuk** [comment]
@azatsarynnyy reopening for clarification.  Basically, there is no Gateway-based editor in the drop-down list on the dogfooding instance, is it expected?

<img width="1721" alt="Screenshot 2024-01-04 at 13 59 02" src="https://github.com/eclipse/che/assets/1461122/9eeb7a49-61c0-4593-b6c3-417403a6db84">

Basically, for a user it is not clear how to try it

**Comment by azatsarynnyy** [comment]
@ibuziuk it's called`IntelliJ IDEA Ultimate (Desktop)`.
"Gateway-based" it's a detail of implementation.

**Comment by ibuziuk** [comment]
awesome, thank you! Closing
do we happen to have some docs? maybe we can prioritize posting a blog post on  https://che.eclipseprojects.io/?

**Comment by azatsarynnyy** [comment]
> do we happen to have some docs?

I believe it's self-explanatory - the steps are described on the page where the Dashboard redirects to, once the Workspace is started:
![image](https://github.com/eclipse/che/assets/1636395/1732278e-7edc-4ed8-8d21-24f52dbd3e0a)

> maybe we can prioritize posting a blog post on https://che.eclipseprojects.io/?

good idea - maybe I'll find a time for it
