### ISSUE TITLE
Docs: Dead Links / Moved pages?

### ISSUE THREAD

**Issue by danwos** [eclipse/che#22712]
### Summary

**Are AWS/Azure and Co. still supported, at least by a rough installation guide?**

I need to ask this because there are some dead links on the Eclipse Che homepage and the GitHub README.
Especially links to installation guides, which are *not* related to RedHat OpenShift, got somehow removed.

#### Findings
Source: https://eclipse.dev/che/
All links on this overview.
![image](https://github.com/eclipse/che/assets/998700/2941e9a0-0143-411e-8b27-3b4a72445093)
For instance AWS: https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/
Opens/Redirects to :  https://eclipse.dev/che/docs/stable/overview/introduction-to-eclipse-che/ (as all other links)

Source: `/Readme.md`
Nearly all links to documentation chapters redirect to the doc-start-page or to 404.
For instance:
![image](https://github.com/eclipse/che/assets/998700/cc306bae-aaa9-421a-b5c2-17e54147f5cd)
The last 3 entries are answered with a 404.

Source: ChatGpt
Looks like also here some "old" links get referenced.

#### Motivation
I'm new to Eclipse Che and try to get an overview of how to get it running on something different from OpenShift.
Mostly as I want to analyze the whitelable possibilities and multi-tenant feature.
The dead links and the knowledge that there was related content in the past, but not now anymore, create negative feelings about project health (no worry, other indicators are fine and I like the project :))

**Comment by l0rd** [comment]
@danwos thanks. 

**Webpage**
We are going to [fix the links in the webpage](https://github.com/eclipse-che/che-website/pull/95). Anyway the current situation is that we only have documentation for [minikube](https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-minikube/) and [OpenShift](https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-openshift-using-cli/). For the rest we have this [open issue to document the rest](https://github.com/eclipse/che/issues/22392) (we are looking for contributions) with links to different content:
- [AKS](https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html)
- [Rancher](https://github.com/eclipse/che/issues/21049#issuecomment-1022108499)
- [GKE](https://github.com/eclipse/che/issues/21049#issuecomment-1067776895)
- [kubeadm](https://github.com/flavienbwk/eclipse-che-kubernetes)
- [EKS](https://github.com/eclipse/che/issues/22358#issuecomment-1635436182)
- microk8s [1](https://github.com/eclipse/che/issues/21378#issuecomment-1685410001) [2](https://github.com/eclipse/che/issues/22445)

**README file**
Open a [PR to fix those as well](https://github.com/eclipse/che/pull/22724).

**ChatGPT**
I don't know how we can help 🤷
