### ISSUE TITLE
If there is no SSH key configured UD should show a warning and do not allow starting a workspace

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22728]
### Is your enhancement related to a problem? Please describe

if SSH is not configured we should not allow starting a workspace based on ssh://

### Describe the solution you'd like

Show a warning that SSH is not configured

### Additional context

add Docs links on UI

**Comment by amisevsk** [comment]
For clarity, this is if the user attempts to start a workspace using an ssh url, correct?
