### ISSUE TITLE
Add a new workspace creation URL parameter named `editor-image`

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22733]
### Is your enhancement related to a problem? Please describe

In some cases a user may want to re-use the existing `che-code` or `che-idea` definitions and replace the injectro container `image` only. 

But for such use case we still require to copy the existing `che-code` or `che-idea` yaml definition, change the injector container `image` and reference the URL in the `editor` URL parameter. This is an unnecessary and error-prone work.

### Describe the solution you'd like

Add a new URL parameter named `editor-image` with the following behavior:

- The parameter is passed to the DevWorkspace generator that uses it to patch the `<editor>-injector` image.
- This should work together with the `editor` URL parameter too. For example: 
	- `editor-image=quay.io/mloriedo/che-code:copilot-builtin` ==> replace the default editor image 
	- `editor=che-incubator/che-idea/next&editor-image=quay.io/mloriedo/che-rider:2023:2` ==> use the `che-incubator/che-idea/next` editor but replace the of the injector image

This is a subtask of the epic #22729

**Comment by ibuziuk** [comment]
Reopening due to missing documentation
