### ISSUE TITLE
Eclipse Che: Unable to get the Helm Chart for eclipse che

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22735]
### Summary

Hello,

I found this link for helm chart for eclipse che:
**_https://artifacthub.io/packages/helm/eclipse-che/eclipse-che_**

But when I click te below link, I got 404 not found error:
**_https://eclipse-che.github.io/che-operator/charts_**

I remember is was working 2/3 months back. Has it been moved? 
Kindly suggest?

Thanks & regards
Debkanta

**Comment by tolusha** [comment]
Hello, @debkantap 

This is the correct link
`https://artifacthub.io/packages/helm/eclipse-che/eclipse-che`

**Comment by debkantap** [comment]
Thanks @tolusha . But when I wanted to see the helm repo in git, I am getting 404. Here is the link for the helm repo:
https://eclipse-che.github.io/che-operator/charts

This is the repo that I got in the link that you provided.

Thanks 
Debkanta
