### ISSUE TITLE
[Help] how to launch the che dashboard

### ISSUE THREAD

**Issue by vinay-keshava** [eclipse/che#22736]
### Summary

https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-minikube/
I followed this tutorial to deploy when i execute the command 
$ chectl dashboard:open

it opens through the browser and says site not found
[using qemu driver for minikube]

Any insight would be helpful
Thanks

**Comment by tolusha** [comment]
Hello, @vinay-keshava 
Did `chectl server:deploy` command completed successfully?
Could you run `chectl server:logs` and attach obtained logs?
