### ISSUE TITLE
Failed to start a workspace via factory with devfile 2.2.2

### ISSUE THREAD

**Issue by svor** [eclipse/che#22753]
### Describe the bug

It is not possible to start a workspace if a repository contains a devfile with schema version 2.2.2.

Factory resolved is failed on che-server side. Since we have devfile schema validation on the dashboard, we can remove it from che-server.

### Che version

7.79@latest

### Steps to reproduce

Use this repository to create a workspace in Che https://github.com/svor/web-nodejs-sample/tree/devfile-2-2-2 (it provides a devfile with 2.2.2 schema version)

### Expected behavior

we should support devfiles with 2.2.2 scema version and the workspace should be started

### Runtime

OpenShift

### Screenshots

![screenshot-nimbusweb me-2024 01 08-15_46_16](https://github.com/eclipse/che/assets/1271546/9e43b522-dfef-457c-901c-f3e8558e50d4)

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
Thanks @svor marking it as a blocker for 7.80.0 / 311
