### ISSUE TITLE
The UD does not have a length limitation for auto-generated names

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22758]
### Describe the bug

It is impossible to create a new workspace from a git repository URL when the repository doesn't have a Devfile and its path includes more than 63 characters.

### Che version

7.79@latest

### Steps to reproduce

1. Open the Create Workspace page.
2. Paste an unexisted URL ```https://github.com/olexii4/che-editor-theiahkhjkhkjhkjhjhghjhgfghfhgfhgjfghfghjfghjfhgfghfghjfhgfghfhgjfhgjfhg```.
3. Press 'Create & Open'.
4. Continue with a default devfile.

### Expected behavior

It should create a new workspace with a name shorter than 63 characters.

### Runtime

OpenShift

### Screenshots

![Знімок екрана 2024-01-10 о 15 42 20](https://github.com/eclipse/che/assets/6310786/ac787f0a-9ee8-4dc8-ace7-8fe3cffec9ad)

### Installation method

chectl/latest, chectl/next

### Environment

macOS

**Comment by dmytro-ndp** [comment]
@olexii4: hello,
I have reproduced the error on Che dogfooding instance (Eclipse Che **Next**) and DevSandbox Stage with Dev Spaces 3.12.0 (Eclipse Che **7.82.x**):
![Screenshot from 2024-03-11 19-07-17](https://github.com/eclipse/che/assets/1197777/8a882e14-a92e-421c-9999-83a1b4b34461)

![Screenshot from 2024-03-11 19-07-52](https://github.com/eclipse/che/assets/1197777/1a18f532-5426-43af-9750-19f754509b65)

Therefore, reopening the issue for further investigation.

**Comment by dmytro-ndp** [comment]
@olexii4 : thanks for the answer.
Actually, I tested issue resolution using unexisted repo, because was in "_Steps to reproduce_" of description of the issue:
![screenshot-github com-2024 03 12-12_59_33](https://github.com/eclipse/che/assets/1197777/650cedb7-5c46-4e0c-8c06-bcfa509e3648)

**Comment by dmytro-ndp** [comment]
@olexii4 : The error has been reproduced on Dev Spaces 3.12.0 deployed to the DevSandbox with an existing repository having a 70-character-long name: https://github.com/dmytro-ndp/70_symbols_long_repo_name_kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
![Screenshot from 2024-03-12 14-12-03](https://github.com/eclipse/che/assets/1197777/b8a92465-9c5c-4247-863a-2a32a1792b45)

**Comment by olexii4** [comment]
@dmytro-ndp  I investigate the problem. It happens because of the changed behavior of che-server.

We can test these changes with a custom repository instead of ```github.com```. 

Steps to reproduce:

1. Open the Create Workspace page.
2. Paste an unexisted URL ```https://custom.repo/olexii4/che-editor-theiahkhjkhkjhkjhjhghjhgfghfhgfhgjfghfghjfghjfhgfghfghjfhgfghfhgjfhgjfhg```.
3. Press 'Create & Open'.
4. Continue with a default devfile.
