### ISSUE TITLE
Can't use universal-developer-image:ubi8-latest with sqlite

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22752]
### Summary

When trying to use the latest universal developer image with an application that uses `sqlite`, I get following error:

```
django.db.utils.NotSupportedError: SQLite 3.27 or later is required (found 3.26.0).
```

Indeed the image has version 3.26

```
$ yum list | grep sqlite
sqlite-libs.x86_64                                                3.26.0-18.el8_8                                                   @System                     
anope-sqlite.x86_64                                               2.1.0-2.el8                                                       epel                        
asterisk-sqlite.x86_64                                            18.12.1-1.el8.2                                                   epel                        
gnokii-smsd-sqlite.x86_64                                         0.6.31-29.el8                                                     epel                        
libdbi-dbd-sqlite.x86_64                                          0.9.0-14.el8                                                      epel                        
libsqlite3x.x86_64                                                20071018-26.el8                                                   epel                        
libsqlite3x-devel.x86_64                                          20071018-26.el8                                                   epel                        
mono-data-sqlite.x86_64                                           6.8.0-4.el8                                                       epel                        
opendbx-sqlite.x86_64                                             1.4.6-21.el8                                                      epel                        
pdns-backend-sqlite.x86_64                                        4.8.3-1.el8                                                       epel                        
perl-RDF-Trine-sqlite.noarch                                      1.019-8.el8                                                       epel                        
preludedb-sqlite3.x86_64                                          5.2.0-1.el8                                                       epel                        
proftpd-sqlite.x86_64                                             1.3.6e-5.el8                                                      epel                        
python3-aiosqlite.noarch                                          0.12.0-1.el8                                                      epel                        
root-sql-sqlite.x86_64                                            6.30.02-1.el8                                                     epel                        
rubygem-sqlite3.x86_64                                            1.4.2-2.el8                                                       epel                        
rubygem-sqlite3-doc.noarch                                        1.4.2-2.el8                                                       epel                        
soci-sqlite3.x86_64                                               4.0.0-2.el8                                                       epel                        
soci-sqlite3-devel.x86_64                                         4.0.0-2.el8                                                       epel                        
sqlite.i686                                                       3.26.0-18.el8_8                                                   ubi-8-baseos-rpms           
sqlite.x86_64                                                     3.26.0-18.el8_8                                                   ubi-8-baseos-rpms           
sqlite-devel.i686                                                 3.26.0-18.el8_8                                                   ubi-8-baseos-rpms           
sqlite-devel.x86_64                                               3.26.0-18.el8_8                                                   ubi-8-baseos-rpms           
sqlite-libs.i686                                                  3.26.0-18.el8_8                                                   ubi-8-baseos-rpms           
strongswan-sqlite.x86_64                                          5.9.10-1.el8                                                      epel                        
uwsgi-plugin-sqlite3.x86_64                                       2.0.23-1.el8                                                      epel                        
zabbix40-dbfiles-sqlite3.noarch                                   4.0.39-1.el8                                                      epel                        
zabbix40-proxy-sqlite3.x86_64                                     4.0.39-1.el8                                                      epel                        
zabbix6.0-dbfiles-sqlite3.noarch                                  6.0.22-2.el8.1                                                    epel                        
zabbix6.0-proxy-sqlite3.x86_64                                    6.0.22-2.el8.1                                                    epel  
```

My question here is: What is the process to update the universal developer image predefined packages? 

Thank you in advance!

**Comment by jorgeadrian93** [comment]
@ibuziuk thanks for answering, 
So is contributing the only way to add/update new capabilities to the developer base image? 

I'm definitely not containerization expert, but when trying to follow the next [documentation](https://www.linuxcapable.com/install-sqlite-on-fedora-linux/) on how to install sqlite on fedora, if I modified the [Dockerfile](https://github.com/devfile/developer-images/blob/main/universal/ubi8/Dockerfile) What is the process to push changes?

**Comment by ibuziuk** [comment]
@jorgeadrian93 if you just want to fall back on the default image the new tools should be contributed there. 
However, you can extend the default image e.g. do the `FROM quay.io/devfile/universal-developer-image:latest` and add whatever you want.
@l0rd is currently working on a blog post that should be soon published on https://che.eclipseprojects.io/ that describes the flow - https://github.com/l0rd/che-blog/blob/cde-customization-part1/_posts/2023-10-25-cde-customization-part1.adoc
stay tuned!

**Comment by jorgeadrian93** [comment]
Awesome! Thanks a lot 😄  
I truly appreciate your help.

**Comment by jorgeadrian93** [comment]
Hi @ibuziuk , I'm reopening this issue because I tried to customize the default universal base image, but the new image gets stuck when trying to open the editor. I even changed the start `spec.devEnvironments.startTimeoutSeconds` to `3000`, but it doesn't start after 10 minutes. The tricky part, is that I can access the container from the terminal via OpenShit. 

I'll try to explain what I did: 

1. I downloaded the [developer-images](https://github.com/devfile/developer-images/tree/main) source code.
2. I rebuilt the ubi8/Dockerfile but changing the base image `ubi:8.9-1107` to `ubi:9.3-1476` and de `epel` packages to 9 as well. 
3. Then use the new base image to build the [universal](https://github.com/devfile/developer-images/blob/main/universal/ubi8/Dockerfile) image

The build was successful, but I got the problem I described above. 
Why did I compile with `ubi9`? I need the updated version of `sqlite` and `ubi8` does not have that update. 

Thanks in advance for your help. 

![image](https://github.com/eclipse/che/assets/19197341/98425c07-987c-4d89-b962-db4f67486639)
![image](https://github.com/eclipse/che/assets/19197341/5ff2b7f4-337f-4009-9bef-288db6e61b9f)
![image](https://github.com/eclipse/che/assets/19197341/c209f272-0d7b-4dd9-9a09-4380401dd2ca)

**Comment by RomanNikitenko** [comment]
@jorgeadrian93 
I guess you faced a problem described in the comment:
https://github.com/eclipse/che/issues/21778#issuecomment-1640281523

It's possible to check logs using a terminal from openshift console => `tools` container => `cat /checode/entrypoint-logs.txt`

<img width="1386" alt="Screenshot 2024-01-26 at 12 46 01" src="https://github.com/eclipse/che/assets/5676062/dc4595fd-99d0-4340-a281-14f69d779570">

This workaround helps to start a workspace:
https://github.com/che-incubator/che-code/blob/main/build/dockerfiles/README.md 

But there are still some errors in logs related to libs, so I'm working on an ability to start VS Code editor in a `ubi9-based` image, there is a PR: https://github.com/che-incubator/che-code/pull/324.
It's under review and testing.

**Comment by jorgeadrian93** [comment]
I confirm that the error is the same that you mention with the node libraries, thanks for confirming that there is a workaround and a PR in progress 👍 It looks like we are on the bleeding edge. 

I'll keep an eye on this to test on my side once it merges. Thanks again!
