### ISSUE TITLE
Add che-docs to the release process

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22764]
### Is your task related to a problem? Please describe

Currently che-docs release is a manual process - 
We need to automate it and make part of the Eclipse Che release cycle - https://github.com/eclipse-che/che-docs/blob/main/RELEASE.adoc

### Describe the solution you'd like

PRs to che-docs are sent automatically during the Eclipse Che release process - https://github.com/eclipse-che/che-docs/pull/2672

Also, as part of this issue Eclipse Che docs with the appropriate version should be published on https://quay.io/repository/eclipse/che-docs?tab=tags&tag=next e.g. `7.81.0`

### Additional context

https://github.com/eclipse-che/che-docs/blob/main/RELEASE.adoc

**Comment by mkuznyetsov** [comment]
related PR: https://github.com/eclipse-che/che-docs/pull/2693
