### ISSUE TITLE
Update configbump

### ISSUE THREAD

**Issue by LMantovan** [eclipse/che#22767]
### Is your enhancement related to a problem? Please describe

I'm using eclipse che 7.79.0 on kubernetes. I noticed that configbump is stuck on 0.1.4 but there are many new version, aligned with che-server version. The 0.1.4 version is full of security vulnerabilities and I'd like to reduce them

### Describe the solution you'd like

I know that I can update version modifying CheCLuster CR but I wonder if it is possible to align configbump to the che-server version without manually modify it

**Comment by AObuchow** [comment]
> I know that I can update version modifying CheCLuster CR but I wonder if it is possible to align configbump to the che-server version without manually modify it

To be clear, you don't want to have to specify a new configbump image in the Che Cluster CR, but instead want it to be updated when Che-Server (or rather, your entire Eclipse Che installation) is updated?

**Comment by LMantovan** [comment]
> > I know that I can update version modifying CheCLuster CR but I wonder if it is possible to align configbump to the che-server version without manually modify it
> 
> To be clear, you don't want to have to specify a new configbump image in the Che Cluster CR, but instead want it to be updated when Che-Server (or rather, your entire Eclipse Che installation) is updated?

Exactly, configbump version is now aligned to Eclipse Che version so for example with Eclipse Che 7.80 the configbump 7.80 must be hardcoded

**Comment by AObuchow** [comment]
@LMantovan And upon updating Eclipse Che, the configbump version in the Che Cluster CR does not change automatically? Have you tried removing the configbump field specified in the Che Cluster CR if you are currently specifying it?

**Comment by LMantovan** [comment]
@AObuchow Yes it changes automatically. I didn't set configbump field in CR yet

**Comment by tolusha** [comment]
We have to set the corresponding ConfigBump image [1] on Eclipse Che operator release.
Currently it is `0.1.4`
[1] https://quay.io/repository/che-incubator/configbump?tab=tags&tag=latest
[2] https://github.com/eclipse-che/che-operator/blob/main/config/manager/manager.yaml#L77

**Comment by tolusha** [comment]
Should be fixed by https://github.com/eclipse-che/che-operator/pull/1803
