### ISSUE TITLE
Deploy che with chectl,meet some issue

### ISSUE THREAD

**Issue by zhao890516** [eclipse/che#22775]
### Summary

use command" chectl server:deploy --platform minikube" to deploy che. Report me ：
[report.txt](https://github.com/eclipse/che/files/13983612/report.txt)

### Relevant information

I am located in China, is it due to my internet connection？

Please provide some solution suggestions，Thanks

**Comment by tolusha** [comment]
Hello @zhao890516 

chectl simply applies resources to install cert-manager at that step.
You can check if it works without chectl on a fresh cluster with the following command:
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml

kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller -n cert-manager --timeout=120s 
kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=cainjector -n cert-manager --timeout=120s 
kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=webhook -n cert-manager --timeout=120s
```

**Comment by zhao890516** [comment]
Thank you for your answer. It has helped me solve my confusion
