### ISSUE TITLE
Zombie processes remain in workspace container after a task is terminated.

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22772]
### Describe the bug

While working in che-code, I encountered a lot of processes labeled `<defunct>` in my workspace container. I noticed that every time a devfile task or corresponding yarn script gets terminated, one or more zombie processes appear.

### Che version

next (development version)

### Steps to reproduce

1. Clone repository git@github.com:eclipse-che/che-dashboard.git
2. Run the task "Install dependencies".
3. Open the terminal and run the `top` command (and hit `c` to see more than just the command name). You may see some zombie processes at this point.
4. Split the terminal, run `yarn build`, and terminate it in a minute.
	- Alternatively, run the "build" task, and terminate it in a minute.
5. In the terminal where the `top` command runs, you can see a few more zombie processes.
6. You can try steps 4-5 with other tasks, e.g. "watch frontend", and "watch backend".

### Expected behavior

No zombie processes should remain after a task termination.

### Runtime

OpenShift

### Screenshots

https://youtu.be/yWVRiQFYfxs

[![Steps to reproduce](https://img.youtube.com/vi/yWVRiQFYfxs/maxresdefault.jpg)](https://youtu.be/yWVRiQFYfxs)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by vitaliy-guliy** [comment]
I got the same when I played with `ssh` service. I've just started and stopped it several times by a command in terminal

![Screenshot from 2024-01-22 16-48-26](https://github.com/eclipse/che/assets/1655894/82fbaea9-89f9-48e5-b658-1a6a4fbd4a2d)

**Comment by vitaliy-guliy** [comment]
I've just double checked it on the dogfooding instance and haven't faced any issues anymore.
No zombie processes appeared after running `yarn install` command.
I tried to launched `yarn` in both VS Code terminal and in the OpenShift console terminal. In both cases it was successful.
