### ISSUE TITLE
Breaking changes in che-incubator/che-code from 7.78 to 7.80

### ISSUE THREAD

**Issue by Deddinho23** [eclipse/che#22780]
### Describe the bug

Hi guys
Recently i have updated our instance of Eclipse Che using chectl from the 7.76.0 to the 7.80.0, after I noticed some problem about the automatic start with the .code-workspace in the env variable VSCODE_DEFAULT_WORKSPACE (It just won't consider it) and some problems in the GUI (I will include some Before->After example about this), I decided to do some troubleshooting by myself and I have discovered that the env variable VSCODE_DEFAULT_WORKSPACE stopped working with the version 7.79.0 of the che-incubator/che-code image, meanwhile the graphical problems seems started with the 7.80.0 version of it (or maybe earlier, i noticed for example that even the circle with the number of changes disappeared)

GUI Example:
Before (che-code:7.76.0)
![image](https://github.com/eclipse/che/assets/48152430/7fef7755-afee-41be-bd84-20261d87e865)

After (che-code:7.80.0)
![image](https://github.com/eclipse/che/assets/48152430/b782d7f2-7d43-4577-bd45-fcbaabee09de)

For now I just updated the DevWorkspaceTemplate of the users that was encountering the problems, changing the version of the che-code, but I'm not sure if that will remain permanent or the Operator will update it 

### Che version

7.80@latest

### Steps to reproduce

.checode-workspace problems (in 7.79.0 release or newer):
1.  Start a workspace specifying in the devfile the env variable VSCODE_DEFAULT_WORKSPACE

GUI problems (in 7.80.0, probably even earlier but not in the 7.76.0 or before):
1. In Source Control, view Source Control Repositories and start to make tighter the menu till the branch name it's over the other button

### Expected behavior

Working regularly like the old versions

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Amazon

**Comment by ibuziuk** [comment]
@azatsarynnyy @RomanNikitenko @vitaliy-guliy please, review

**Comment by vitaliy-guliy** [comment]
It could not work (it's not clear) when we introduced the launcher the first time, but at the moment the variable is taken into account.
To test the current behavior you can create a workspace using the following repository

https://github.com/vitaliy-guliy/recommended-extensions-sample/tree/vscode-default-workspace

**Comment by Deddinho23** [comment]
Hi @vitaliy-guliy, thank to your response I just found where the problem was!
Idk if recently was added a json syntax control on the .code-workspace file, but in the older versions if it had some plus ',' where it wasn't needed the workspace was starting correctly the same, meanwhile now if the file have some syntax error it won't start with the .code-workspace and open the first project cloned.
So now I have removed the unnecessaries commas from my .code-workspace and it worked!

However the graphical problems remain, about the name of the branches I still guess it's a bug, but for the circles at the end of the line with the number of changes (it was very useful) it was a choice by design to remove it?

**Comment by vitaliy-guliy** [comment]
> Hi @vitaliy-guliy, thank to your response I just found where the problem was! Idk if recently was added a json syntax control on the .code-workspace file, but in the older versions if it had some plus ',' where it wasn't needed the workspace was starting correctly the same, meanwhile now if the file have some syntax error it won't start with the .code-workspace and open the first project cloned. So now I have removed the unnecessaries commas from my .code-workspace and it worked!

You can play a bit again with `,` character and look at `/checode/entrypoint-logs.txt` file?
When launcher tries to parse `.code-workspace` file
https://github.com/che-incubator/che-code/blob/main/launcher/src/code-workspace.ts#L53
and the file does not have a strict format, `entrypoint-logs.txt` should contain the corresponding output.
And this explains why the editor opens the first cloned project
https://github.com/che-incubator/che-code/blob/main/launcher/src/vscode-launcher.ts#L44

> 
> However the graphical problems remain, about the name of the branches I still guess it's a bug, but for the circles at the end of the line with the number of changes (it was very useful) it was a choice by design to remove it?

**Comment by Deddinho23** [comment]
> > Hi @vitaliy-guliy, thank to your response I just found where the problem was! Idk if recently was added a json syntax control on the .code-workspace file, but in the older versions if it had some plus ',' where it wasn't needed the workspace was starting correctly the same, meanwhile now if the file have some syntax error it won't start with the .code-workspace and open the first project cloned. So now I have removed the unnecessaries commas from my .code-workspace and it worked!
> 
> You can play a bit again with `,` character and look at `/checode/entrypoint-logs.txt` file? When launcher tries to parse `.code-workspace` file https://github.com/che-incubator/che-code/blob/main/launcher/src/code-workspace.ts#L53 and the file does not have a strict format, `entrypoint-logs.txt` should contain the corresponding output. And this explains why the editor opens the first cloned project https://github.com/che-incubator/che-code/blob/main/launcher/src/vscode-launcher.ts#L44

Yep no problem and as I tried with this `.code-workspace`:
```json
{
	"folders": [
		{
			"path": ".."
		},
		{
			"name": "recommended-extensions-sample",
			"path": "/projects/recommended-extensions-sample"
		},
	]
}
```
It gives me this error in the `entrypoint-logs.txt`:
```
# Generating Workspace file...
  > env.VSCODE_DEFAULT_WORKSPACE environment variable is set to /projects/recommended-extensions-sample/workspace-file
  > Using workspace file /projects/recommended-extensions-sample/workspace-file
Unexpected token ] in JSON at position 148 Unable to generate che.code-workspace file
```

**Comment by vitaliy-guliy** [comment]
> Yep no problem and as I tried with this `.code-workspace`:
> 
> ```json
> {
> 	"folders": [
> 		{
> 			"path": ".."
> 		},
> 		{
> 			"name": "recommended-extensions-sample",
> 			"path": "/projects/recommended-extensions-sample"
> 		},
> 	]
> }
> ```
> 
> It gives me this error in the `entrypoint-logs.txt`:
> 
> ```
> # Generating Workspace file...
>   > env.VSCODE_DEFAULT_WORKSPACE environment variable is set to /projects/recommended-extensions-sample/workspace-file
>   > Using workspace file /projects/recommended-extensions-sample/workspace-file
> Unexpected token ] in JSON at position 148 Unable to generate che.code-workspace file
> ```

The same error when trying to parse json here https://jsonformatter.org/json-parser

**Comment by vitaliy-guliy** [comment]
@Deddinho23 if nothing to fix, let's close the issue

**Comment by vitaliy-guliy** [comment]
Closed as there is nothing to fix
