### ISSUE TITLE
Eclipse Che: Unable to add plug-in automatically in workspace using Devfile

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22783]
### Summary

I created a simple devfile and tried to add "redhat.java", plug-in in the dev workspace automatically while creating the workspace, but it is not added automatically. Any clue where I am doing wrong.  I have installed eclipse che on vanilla k8s
I have followed the below link:
https://medium.com/eclipse-che-blog/devfile-v2-and-ide-plug-ins-in-eclipse-che-7a560ae724b1
and here is my simple devfile:

---*****----------------

schemaVersion: 2.2.0
metadata:
  name: helloworld-example
attributes:
  .vscode/extensions.json: |
    {
      "recommendations": [
        "redhat.java"
      ]
    }
components:
  - name: dev-tooling
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: install
    exec:
      commandLine: npm install
      component: dev-tooling
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      commandLine: node app.js
      component: dev-tooling
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: run

**Comment by debkantap** [comment]
Also followed this link below:
https://devfile.io/docs/2.0.0/adding-plugin-component

**Comment by ibuziuk** [comment]
@debkantap in order to install extensions automatically just add `.vscode/extensions.json` to the root of the repository e.g. https://github.com/che-incubator/quarkus-api-example/blob/main/.vscode/extensions.json

**Comment by debkantap** [comment]
@ibuziuk ..Thanks for your reply. I did added the extensions.json in my devfile repo, but not lucky. My devfile is very simple and attached. The devfile repo screenshot is also attached. May be doing some mistake, can you please help.
Thanks 
Debkanta
![devfile-repo](https://github.com/eclipse/che/assets/105507936/ebfd06d1-17d8-41e1-9a4d-fcc29170a8c0)

----Devfile---

schemaVersion: 2.2.0
metadata:
  name: helloworld-example
attributes:
  .vscode/extensions.json: |
    {
      "recommendations": [
        "redhat.java"
      ]
    }
components:
  - name: dev-tooling
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: http-3000
          targetPort: 3000
  - name: sonarlint-vscode
    plugin:
    reference: https://github.com/sainirijul/che-plugin-registry/blob/master/v3/plugins/sonarsource/sonarlint-vscode/1.13.0/meta.yaml
commands:
  - id: install
    exec:
      commandLine: npm install
      component: dev-tooling
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      commandLine: node app.js
      component: dev-tooling
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: run

-----
