### ISSUE TITLE
Failed to start a workspace from the sample: No SSH keys found

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22789]
### Describe the bug

Failed to start a workspace from the sample: No SSH keys found

### Che version

next (development version)

### Steps to reproduce

1. Try to start a workspace from the sample

### Expected behavior

Workspace successfully started

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context

![Uploading screenshot-eclipse-che.apps.ci-ln-53v6512-76ef8.aws-2.ci.openshift.org-2024.01.24-16_46_59.png…]()

**Comment by ibuziuk** [comment]
@akurinnoy could you please take a look?
