### ISSUE TITLE
Dashboard URL is unavailable for a few seconds when pod is deleted / restarted

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22786]
### Describe the bug

The dashboard URL is unavailable for a few seconds when pod is deleted/restarted

### Che version

7.80@latest

### Steps to reproduce

1. Install the latest Eclipse Che
2. wait until all operands are running
3. access Dashboard and login
4. manually delete the dashboard pod 
5. quickly go back to the Dashboard URL and hit refresh
6. ERROR: sometimes for a few seconds dashboard will not be accessible

### Expected behavior

Since Rolling Update strategy is used dashboard should be always available

### Runtime

Kubernetes (vanilla), OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by akurinnoy** [comment]
Hi @ibuziuk, I spent some time trying to reproduce this bug, but the dashboard was available for me all the time. Do you have any clues that will help?

**Comment by ibuziuk** [comment]
the reproducer is changing CR that triggers dashboard operand restart e.g.

```
    devfileRegistry:
      deployment:
        securityContext: {}
      disableInternalRegistry: true / false
```
