### ISSUE TITLE
customize devworkspace operator image

### ISSUE THREAD

**Issue by LMantovan** [eclipse/che#22806]
### Is your enhancement related to a problem? Please describe

I'm trying to use my own registry with eclipse-che images. I can change the registry with che-cluster CR and by --che-operator-image flag on chectl. 

### Describe the solution you'd like

I'd like to change registry even on devworkspace-controller-manager and devworkspace-webhook-server pod

**Comment by dkwon17** [comment]
Hi @LMantovan are you running Che on Kubernetes or OpenShift?

**Comment by LMantovan** [comment]
@dkwon17 I'm running it on Kubernetes

**Comment by tolusha** [comment]
@LMantovan 
There is no way to configure image registry for DevWorkspace operator image. 
But it is possible to achieve in the following steps;
1. Download DWO templates `https://github.com/devfile/devworkspace-operator/blob/main/deploy/deployment/kubernetes/combined.yaml`
2. Replace images in template
3. Apply customized template `kubectl apply -f <template>`
4. Deploy Eclipse Che and skip installing DWO `chectl server:deploy --skip-devworkspace-operator ...`
