### ISSUE TITLE
Doc Bug:  Eclipse Che Documentation contains outdated config for "Configuring workspaces nodeSelector"

### ISSUE THREAD

**Issue by ginilekshmi** [eclipse/che#22801]
### Describe the bug

Doc Bug:  Eclipse Che Documentation contains outdated config for "Configuring workspaces nodeSelector"
https://eclipse.dev/che/docs/stable/administration-guide/configuring-workspaces-nodeselector/

### Che version

7.80@latest

### Steps to reproduce

Eclipse Che Documentation contains outdated config for "Configuring workspaces nodeSelector"
https://eclipse.dev/che/docs/stable/administration-guide/configuring-workspaces-nodeselector/

### Expected behavior

Doc should be modified with new correct config:
```
spec:
  devEnvironments:
    tolerations: 
    nodeSelector:
```

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

**Comment by ibuziuk** [comment]
@deerskindoll please, note that we need to have this docs in 7.82.0 / 3.12
@vinokurig is working on the docs PR
