### ISSUE TITLE
[UD] Expose URL parameters to users(Git Repo Options)

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22816]
### Is your enhancement related to a problem? Please describe

Expose URL parameters to users. Improve the **Import from Git** widget(It needs for https://github.com/eclipse/che/issues/22784).

### Mockups

**With Git Repo options collapsed (the default)**

![image](https://github.com/eclipse/che/assets/606959/ec163fe1-c2b4-426f-88b0-aa77c5eb6d7e)

**With Git Repo options expanded (the user needs to click on the labels to expand)**
![Знімок екрана 2024-04-28 о 22 03 33](https://github.com/eclipse-che/che/assets/6310786/6d0a892a-2062-4032-af4b-6aeaf8247765)

**Comment by RomanNikitenko** [comment]
From my point of view, the current behaviour is not obvious:
>- when the editor selector panel (Choose an Editor) is opened, the selected editor will override the editor definition in the factory repo;
>- when the editor definition panel (Use an Editor Definition) is opened and the fields are empty the editor definition in the factory repo will be applied.

`Choose an Editor` is open by default, but I don't want to select it - editor is defined in my repo (`./che/che-editor.yaml`)  - I don't want to override it - how I can unselect it? 
it looks like I should open `Use an Editor Definition` - but again - there are two fields that I don't need to define - editor is defined in my repo (`./che/che-editor.yaml`)...
