### ISSUE TITLE
Bring my own IDE:  How could i do some task from my ide ?

### ISSUE THREAD

**Issue by batleforc** [eclipse/che#22812]
### Summary

Hi,
For some time, I've been using my eclipse Che instance with my own IDE (IDEA or VsCode, for the case where I have my own computer on me). I had a case where I wanted to stop/restart from local devfile and ended up unable to do so. Is there a way to trigger those restart from my own IDEA (or vscode) installed on my computer ? If so, does creating a Task File to make those automatic seems a good idea ? I also started translating my command into idea's own command so it could be a solution.

**Comment by RomanNikitenko** [comment]
> I had a case where I wanted to stop/restart from local devfile and ended up unable to do so.

About VS Code
Do you mean these commands:

<img width="331" alt="image" src="https://github.com/eclipse/che/assets/5676062/5c308b72-74d7-45ee-ba9e-4f0499e46abe">

please provide steps to reproduce if they don't work for your case.

> Is there a way to trigger those restart from my own IDEA (or vscode) installed on my computer ?

it's possible to run these actions from the dashboard - does it work for your case?
You can take a look what `Stop Workspace` does under the hood [here](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/extensions/che-api/src/impl/k8s-workspace-service-impl.ts#L62) using k8s service.
`Restart Workspace` first stops a workspace and then [start it](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/src/vs/workbench/contrib/remote/browser/che/devWorkspaceAssistant.ts#L131-L133) on the browser side.

About IDEA - maybe @azatsarynnyy could help you...

**Comment by batleforc** [comment]
> > I had a case where I wanted to stop/restart from local devfile and ended up unable to do so.
> 
> About VS Code Do you mean these commands:

Yes those one, and yeah it works for me. The full online work perfectly for me (and it saved my life a lot of time :rofl: ) 


> > Is there a way to trigger those restart from my own IDEA (or vscode) installed on my computer ?
> 
> it's possible to run these actions from the dashboard - does it work for your case?

For the basic one yeah, but the one where I need for example a restart from local devfile (because I need to update my image for example) I didn't find it on the dashboard.

> Also you can take a look what `Stop Workspace` does under the hood [here](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/extensions/che-api/src/impl/k8s-workspace-service-impl.ts#L62) using k8s service. `Restart Workspace` first stops a workspace and then [start it](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/src/vs/workbench/contrib/remote/browser/che/devWorkspaceAssistant.ts#L131-L133) on the browser side.

Thanks for the link, I will search how it works and start to work on a possible integration :+1: 

Just so you understand, I want to keep the ability to handle my workspace like with the full online vscode with hybrid case (https://github.com/che-incubator/che-idea-dev-server or directly connecting my VS Code with the Kubernetes extension to the pod). And I'm thinking if it's easy to make a tiny CLI to do the basics that I will embed in my future image.

**Comment by RomanNikitenko** [comment]
> I need for example a restart from local devfile (because I need to update my image for example) I didn't find it on the dashboard.

you are right - `restart from local devfile` action is absent on the dashboard...

>  I want to keep the ability to handle my workspace like with the full online vscode with hybrid case (https://github.com/che-incubator/che-idea-dev-server or directly connecting my VS Code with the Kubernetes extension to the pod)

probably you are looking for something like: https://github.com/eclipse/che/issues/22706

**Comment by batleforc** [comment]
> > I need for example a restart from local devfile (because I need to update my image for example) I didn't find it on the dashboard.
> 
> you are right - `restart from local devfile` action is absent on the dashboard...
>
> > I want to keep the ability to handle my workspace like with the full online vscode with hybrid case (https://github.com/che-incubator/che-idea-dev-server or directly connecting my VS Code with the Kubernetes extension to the pod)
> 
> probably you are looking for something like: #22706

Yep, it could for VsCode, and for IDEA (Jetbrains gateway) I would just reproduce it. To direct connect into my pod, I use the “join from vscode” provided in the Kubernetes extension when you right-click a pod. Does the extension force the usage of ssh ?

**Comment by batleforc** [comment]
Hi, I'm back a little more than a month later. 
Will working on my CLI to hasten some process, I ended up encountering a problem with how to keep alive my workspace when I hope in with VS Code and that the default IDE che-code.
How can I get the [MACHINE_EXEC_PORT](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/extensions/che-api/src/impl/k8s-workspace-service-impl.ts#L56), by default it's 3333 ?

The process that I intend to set up:

1. Start a session with `./dev-cli workspaces open-vs-code {container name} {Other param that may be needed}`
2. [DONE] The CLI start a new [VS Code window](https://github.com/batleforc/Dev-cli/blob/main/src/vscode/open_code.rs#L45) that will go in the targeted container and folder (default to `/projects/` but can be set)
3. [Need help] Then the CLI don't give back the term and will call [every minute](https://github.com/che-incubator/che-code/blob/main/code/extensions/che-activity-tracker/src/activity-tracker-service.ts#L21) the [health check endpoint](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/extensions/che-api/src/impl/k8s-workspace-service-impl.ts#L56) through an [in process reverse proxy](https://github.com/kube-rs/kube/blob/main/examples/pod_portforward_hyper_http.rs#L39-L63).

**Comment by RomanNikitenko** [comment]
> How can I get the [MACHINE_EXEC_PORT](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/code/extensions/che-api/src/impl/k8s-workspace-service-impl.ts#L56), by default it's 3333 ?

yes, it's defined [here](https://github.com/che-incubator/che-code/blob/6e0a908d58cacb380c216dde3af544d75e3913d5/build/scripts/entrypoint-volume.sh#L26)

**Comment by batleforc** [comment]
Thanks, I think I will go with a default value then
