### ISSUE TITLE
Failed to install `chectl`

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22820]
### Describe the bug

Failed to install `chectl`

### Che version

next (development version)

### Steps to reproduce

1. `bash <(curl -sL  https://www.eclipse.org/che/chectl/)`

### Expected behavior

`chectl` in installed

### Runtime

Kubernetes (vanilla)

### Screenshots

![screenshot-eclipse dev-2024 02 14-09_25_29](https://github.com/eclipse/che/assets/1640675/57e30935-6210-44c5-b50e-0b715f0db8bb)

### Installation method

chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment]
@tolusha opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4290

**Comment by ibuziuk** [comment]
Looks like the website is back now - https://eclipse.dev/che/

**Comment by ibuziuk** [comment]
Closing. The reason for the outage was an unplanned test of faulty persistent volumes in production - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4287#note_1753011
