### ISSUE TITLE
[plugin-registry] Upgrade openvsx base image to v0.14.3

### ISSUE THREAD

**Issue by svor** [eclipse/che#22826]
### Is your task related to a problem? Please describe

Currently we use **ghcr.io/eclipse/openvsx-server:v0.14.1** as a base image for the plugin registry: https://github.com/eclipse-che/che-plugin-registry/blob/main/build/dockerfiles/Dockerfile#L15

Currently the latest version of openvsx image is v0.14.3   

### Describe the solution you'd like

Update base image in che-plugin registry Dockerfile to v0.14.3

Check the build and the functionality of the internal openvsx server

**Comment by monaka** [comment]
off-topic: How about using Mend Reovate for tracking upstreams ?

**Comment by ArvinB** [comment]
@svor FYI I notice that plugins published into openvsx are sometimes marked inactive. I think there should be a wait between publishing each extension to allow for openvsx to fully publish (larger extensions).

You can see what I mean by doing the following:

—

docker pull registry.redhat.io/devspaces/pluginregistry-rhel8:3.11
docker run -it --entrypoint /bin/bash registry.redhat.io/devspaces/pluginregistry-rhel8:3.11

—

Then:

cp -r /var/lib/pgsql/15/data/old /var/lib/pgsql/15/data/database
/usr/local/bin/start_services.sh
psql
SELECT * FROM extension;

---

Specifically, what I found helpful to resolve this is to add a tiny 'sleep 15' in the import_vsix.sh right before the ovsx publish statement.

Also, a sleep 30 after the publish loop is done.

Thanks,
Arvin

**Comment by svor** [comment]
@ArvinB thank you for the investigation, I'll take a look!

**Comment by ArvinB** [comment]
@svor Your welcome! This does increase the build time a bit, but it really isn't too bad. The `publish` simply doesn't fully finish for larger vsix files because it's transferring it into the postgres resource files before moving on to the next extension, thus it never completes and gets marked active.
