### ISSUE TITLE
Gitconfig is not automatically created

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22828]
### Describe the bug

Gitconfig is not automatically created on Developer Sandbox / m3 cluster

<img width="1341" alt="Screenshot 2024-02-19 at 14 26 19" src="https://github.com/eclipse/che/assets/1461122/5e17d314-a463-4ae7-a5c4-f9a0ad57bddf">

### Che version

7.81@latest

### Steps to reproduce

1. go to workspaces.openshift.com
2. create a workspace based on github repo e.g. https://github.com/che-incubator/quarkus-api-example
3. SUCCESS - workspace has been started
4. ERROR - there is no Gitconfig created

<img width="1341" alt="Screenshot 2024-02-19 at 14 27 40" src="https://github.com/eclipse/che/assets/1461122/1337a6ed-5a1c-4087-b441-86cd09d93e64">

### Expected behavior

Gitconfig with username / email is created

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by vinokurig** [comment]
The logic works as expected: we do not set the `user.name` and `user.email` data if one of the fields is missing in the provider's user profile page. Updated the related documentation page.

**Comment by nykredit-gusg** [comment]
@vinokurig I am experiencing the same issue. The git config file is not automatically created. I have verified that my name, and e-mail, is retrievable through the GitHub API.
