### ISSUE TITLE
Eclipse Che: Unable to add plug-in automatically in workspace using Devfile for IntelliJ IDEA Community Editor

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22830]
### Summary

I am not able to install plug-ins automatically using devfile for intellij IDEA editor or JetBrains Pycharm editor. Request your help/pointer to achieve this.

### Relevant information

For vscode editor able to do this using extensions.json

**Comment by dkwon17** [comment]
Hi, I don't think this is supported, any ideas @azatsarynnyy ?

**Comment by azatsarynnyy** [comment]
I'm not sure If IDEA has a functionality similar to VS Code's `extensions.json`. If it does - it should work.
AFAIK, there's nothing in Devfile itself for installing IDEA plugins.

**Comment by debkantap** [comment]
Thanks everyone for the response.. I shall test this and post here.

Thanks & Regards
Debkanta

**Comment by debkantap** [comment]
I tried it..but getiing the following error:
"_**Requied Plugins not loaded. Project 'java-spring-petclinic-modified' requires '233.13135.103' or newer build of the IDE, but the current build is '221.5080.210**_"
 This is what I did:

1. I forked the https://github.com/eclipse-che/che-devfile-registry
2. Copied the https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles/java-web-spring  to another folder "java-web-spring-modified" and changed to meta.yaml to map to my devfile registry "java-spring-petclinic-modified"
3. Then I modified the "java-spring-petclinic-modified" and added the ".idea" folder with externalDependencies.xml
4. The content of my externalDependencies.xml is as below:
----
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ExternalDependencies">
    <plugin id="DevKit" />
    <plugin id="Git4Idea" />
    <plugin id="JUnit" />
    <plugin id="com.intellij" min-version="213.6777.52" />
    <plugin id="com.intellij.copyright" />
    <plugin id="com.intellij.java-i18n" />
    <plugin id="com.intellij.properties" />
    <plugin id="com.intellij.uiDesigner" />
    <plugin id="org.intellij.groovy" />
    <plugin id="org.editorconfig.editorconfigjetbrains" />
    <plugin id="org.jetbrains.kotlin" min-version="&lt;ide.build.baseline&gt;-1.6.10" max-version="&lt;ide.build.baseline&gt;-1.6.99" />
  </component>
</project>
----
5. then I build my devfile registry and created the custom image for devfile
6. Using that custom devfile image I deploted eclipse che on k8s
7. then tried to open the devfile by selecting the intellij editor and getting the error as mentioned above.

I am wondering where from the version of intellij is selected by che devworkspace manager and how do I modify that?

Request you help please.

Thanks & regards
Debkanta

**Comment by debkantap** [comment]
@monaka ...any help please.

TR
Debkanta
