### ISSUE TITLE
[docs] Previous Versions Docs aren't working

### ISSUE THREAD

**Issue by maheshrajrp** [eclipse/che#22831]
### Describe the bug

Hi,
Help Documents related to previous che versions aren't working. 

### Che version

7.81@latest

### Steps to reproduce

1. Visit https://eclipse.dev/che/docs/stable/overview/introduction-to-eclipse-che/
2. Click on version dropdown old (7.41)
3. On clicking it opens and then redirects to previous site.

### Expected behavior

It should show help documentation related to the previous version. Also, having documentations related to all the previous version should help.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

other (please specify in additional context)

**Comment by tolusha** [comment]
@maheshrajrp 
Do you use eclipse-che <= 7.41 ?
It is quite old one.

**Comment by maheshrajrp** [comment]
> @maheshrajrp 
> Do you use eclipse-che <= 7.41 ?
> It is quite old one. 
> 

using 7.38 to be exact.. imagine the nightmare !! 😶

**Comment by maheshrajrp** [comment]
> @deerskindoll could you please take a look? 
> @maheshrajrp it is strongly recommended to update to the latest version  

thanks for responding. 

but, unfortunately AKS doesn't seem to be supporting External OIDC which is huge blocker.. as currently the ecosystem is built around Azure.. waiting for AKS to implement the feature, which I believe might take a year..

**Comment by maheshrajrp** [comment]
> @deerskindoll could you please take a look? 
> @maheshrajrp it is strongly recommended to update to the latest version  

unrelated to the issue, is there any major critical issue that i need to be aware of, as I might be sticking with v7.38.0 for a longer period.. 

thanks.

**Comment by monaka** [comment]
@maheshrajrp
FYI. I've been using Che on AKS since many years ago.
So until a week ago, I couldn't upgrade my Che instance to latest versions.

My workaround is to use vcluster by Loft on my AKS cluster.
Hope some helps.

**Comment by deerskindoll** [comment]
eclipse foundation issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4333

**Comment by maheshrajrp** [comment]
> @maheshrajrp
> FYI. I've been using Che on AKS since many years ago.
> So until a week ago, I couldn't upgrade my Che instance to latest versions.
> 
> My workaround is to use vcluster by Loft on my AKS cluster.
> Hope some helps.

thanks for responding.. does it incur cost !? if yes can you share the pricing you spend !?

**Comment by ibuziuk** [comment]
did some follow-up on the closed issues, and it is expected that we do not have the live documentation for 7.41.0 - https://github.com/eclipse/che/issues/21688#issuecomment-1339387181

@deerskindoll we need to remove it from the website to avoid confusion <img width="133" alt="image" src="https://user-images.githubusercontent.com/606959/218582769-758a2304-895b-4155-8d58-e0c79bda65a4.png">

@maheshrajrp in order to get the old docs you will need to build it from the corresponding branch e.g. https://github.com/eclipse-che/che-docs/tree/7.41.x

**Comment by monaka** [comment]
> does it incur cost !?

All components in my env are free beer, OSS.
It's enough for us even if Loft proposes their proprietary version "Vcluster-Pro".

I read https://vrelevant.net/vcluster-with-oidc/ before as a concrete example.
Anyway it's a off-topic. Please raise an another issue if you want to get some more supports. @maheshrajrp

**Comment by ibuziuk** [comment]
Closing as Done
