### ISSUE TITLE
After revoke OAuth application the 'Authorization' indicator is still turned in 'User Preferences' Dashboard

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#22836]
### Describe the bug

When the OAtuh application is revoked on git provider side, the 'Authorization' indicator is left turned on Dashboard, that is a bug.
In the same time the Personal Access Token is properly deleted from `<user>-namespace`

**IMPORTANT**: the issue is relevant only for Gitlab and Bitbucket Server (oauth1 and oauth2).
### Che version

7.81@latest

### Steps to reproduce

1. Deploy Che
2. Configure git provider OAuth
3. Start a workspace from the git repository with a devfile.
4. Go to the `Dashboard` ->  User Preferences -> Git Services -> `Authorization` indicator is turn on
5. Go to git provider -> revoke OAuth application
6. Go to the `Dashboard` ->  User Preferences -> Git Services -> `Authorization` indicator is left turn on 

### Expected behavior

After revoke OAuth application on git provider side, the `Authorization` indicator should be turn off in `User Preferences` of Dashboard

### Runtime

OpenShift

### Screenshots

![git-services-Eclipse-Che-User-Preferences](https://github.com/eclipse/che/assets/5408906/cddf0a09-6991-4ae0-a231-19674d870b03)
![personal-access-token-Eclipse-Che-User-Preferences](https://github.com/eclipse/che/assets/5408906/611d6247-ba39-41a5-9de1-e5201aac4c40)

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
The issue looks related to #22827, IMHO

**Comment by vinokurig** [comment]
Duplicates https://github.com/eclipse/che/issues/22790

**Comment by ibuziuk** [comment]
@vinokurig this was fixed for 7.85.0 / 3.14 right?

**Comment by vinokurig** [comment]
@ibuziuk 
> this was fixed for 7.85.0 / 3.14 right?

Yes, do you think we need to cherry-pick this to 7.84?

**Comment by ibuziuk** [comment]
I think it should be ok not to cherry-pick it
