### ISSUE TITLE
Volume size defined in the parent devfile is not overridable in the child 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22834]
### Describe the bug

Currently, if volume size is defined in the parent devfile there is no way to override it in the child. No matter which value is set the one from parent will be used

### Che version

7.81@latest

### Steps to reproduce

1. Create a parent devfile with volume and size
2. Reference is from another devfile as parent and set different value for volume size
3. Start a workspace based on new devfile
4. ERROR: volume size is not overridden and the value from parent is used

### Expected behavior

volume size defined in the child devfile is applied when the workspace is created

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

We should consider also updating the test with this case - https://github.com/testsfactory/parentDevfile/tree/main

**Comment by dkwon17** [comment]
I believe we can close this issue, creating a workspace with this devfile [1] correctly creates a workspace with the correct volume size.

After starting the workspace, running `cat $DEVWORKSPACE_FLATTENED_DEVFILE` shows the correct volume size:
```
- attributes:
    controller.devfile.io/imported-by: parent
  name: projects
  volume:
    size: 30Gi
```

[1] https://gist.githubusercontent.com/dkwon17/9ecac5397bef1178f77f308565814996/raw/4801b3c07a2cababd53b3594754c628cde7b8947/child-devfile.yaml
