### ISSUE TITLE
Docs: Eclipse Che Security Best Practices

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22835]
### Is your task related to a problem? Please describe

There is a downstream article about Dev Spaces security best practices that we should make part of the upstream documentation - https://developers.redhat.com/articles/2024/02/19/red-hat-openshift-dev-spaces-security-best-practices

### Describe the solution you'd like

Add a separate "Security Best Practices" section to the Eclipse Che docs

**Comment by ibuziuk** [comment]
@deerskindoll will you be able to work on this content during the next sprint?

**Comment by deerskindoll** [comment]
> @deerskindoll will you be able to work on this content during the next sprint?

ok

**Comment by ibuziuk** [comment]
@deerskindoll any updates on this issue?

**Comment by deerskindoll** [comment]
> @deerskindoll any updates on this issue?

I have a draft where I transfer the text and format it. 

where in the overall admin guide structure would you like me to place the doc? in the Preparing installation section? or a complete separate section for visibility?

**Comment by ibuziuk** [comment]
@deerskindoll I believe we need a separate "Security Best Practices" Section

**Comment by ibuziuk** [comment]
@deerskindoll any progress? when the docs are going to land in the upstream?
