### ISSUE TITLE
Eclipse Che: Need documentation for extracting che server, workspace metrics running on k8s with prometheus 

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22843]
### Summary

I referred the following link for monitoring, but it is for openshift, but my eclipse che is running on k8s
https://eclipse.dev/che/docs/stable/administration-guide/monitoring-che/
Also checked the below link, but no luck:
https://github.com/ibuziuk/devworkspace-operator/tree/main/doc/grafana#grafana-dashboards-for-the-devworkspace-operator
Do you have any pointer on this please.

Thanks & regards
Debkanta

**Comment by monaka** [comment]
In vanilla K8s, monitoring with Prometheus is an option.
So it is necessary to make assumptions for their clusters.

I think the reasonable assumption is "Their cluster supports `ServiceMonitor` CR."
Famous products are...
prometheus-operator https://artifacthub.io/packages/search?ts_query_web=prometheus-operator
or
grafana-agent-operator https://artifacthub.io/packages/helm/grafana/grafana-agent-operator

After they set their cluster up `ServiceMonitor`, we may be able to write some information.

**Comment by akurinnoy** [comment]
@ibuziuk @dkwon17 please take a look at this question.

**Comment by dkwon17** [comment]
Hi @debkantap , if you are using Prometheus Operator, you can still use the `ServiceMonitor` CR mentioned in [1], [2]

as long as for the `ServiceMonitor` , `Role`, and `RoleBinding` in [1], the `openshift-operators` namespace is replaced with the namespace that has the `devworkspace-controller-metrics` service.

Additionally, the  `openshift-monitoring` namespace in the `RoleBinding`s in [1], [2] should be replaced with the namespace the Prometheus Operator's operands are running in, for the Kubernetes cluster.

[1] https://eclipse.dev/che/docs/stable/administration-guide/monitoring-the-dev-workspace-operator/
[2] https://eclipse.dev/che/docs/stable/administration-guide/monitoring-che/

**Comment by dkwon17** [comment]
There are also older, unmaintained docs that show an example for collecting metrics using Prometheus without the Prometheus Operator and `ServiceMonitor`: [1]

These old docs describe importing Grafana dashboards [2] [3] from the web UI, but it would probably be better using a configmap so that the dashboards persist if the Grafana pod is recreated.

[1] https://62b9c9a770930d4cffbd14da--eclipse-che-docs-pr.netlify.app/docs/next/administration-guide/installing-prometheus-and-grafana/
[2] https://github.com/devfile/devworkspace-operator/blob/main/docs/grafana/grafana-dashboard.json
[3] https://github.com/eclipse-che/che-server/blob/main/docs/grafana/dashboard.json

**Comment by debkantap** [comment]
@dkwon17, I am not using prometheous operator..deployed the prometheous only, not Grafana for now..
trying to test the metrics locally, but no luck ..any idea why I am not getting the token. when I am trying to print token, it is giving 'e'
TOKEN=$(kubectl get secrets -o=json -n ${NAMESPACE} | jq -r '[.items[] |
  select (
    .type == "kubernetes.io/service-account-token" and
    .metadata.annotations."kubernetes.io/service-account.name" == "devworkspace-controller-serviceaccount")][0].data.token' \
  | base64 --decode)

missing something fundamental!!!

TR
Debkanta

**Comment by dkwon17** [comment]
What version of Kubernetes are you using? Maybe the secret was not auto-generated for your Kubernetes version [1] [2]?

You can try manually creating the secret by creating:
```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: devworkspace-controller-serviceaccount-token
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: devworkspace-controller-serviceaccount
```

[1] https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#auto-generated-legacy-serviceaccount-token-clean-up
[2] https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token

**Comment by debkantap** [comment]
Many thanks @dkwon17 for guiding me.
I am using V1.29.2 of k8s.
Yes, secrets was not auto created, I had to create it..
Now I am able to get the metrics from devworkspace-controller.

Again thanks a ton!!

Regards
Debkanta
