### ISSUE TITLE
Document Steps to follow to onboard Custom Editor into Plugin Registry

### ISSUE THREAD

**Issue by maheshrajrp** [eclipse/che#22854]
### Summary

Hi All,

We have a custom Eclipse Theia Editor Implementation similar to old Che-Theia, however there isn't any proper documentation on how to onboard a custom editor into plugin registry.  I can see we have documentation to add plugins, but not editor. A proper documentation would really help.

Thanks

**Comment by svor** [comment]
@maheshrajrp hello, I've just merged a PR with changes that provides some explanation of haw to contribute new editor into the plugin registry repository: https://github.com/eclipse-che/che-plugin-registry/blob/main/CONTRIBUTE.md#adding-a-che-editor-to-che

Hope this helps a bit. If you want me to look into anything further just let me know!

**Comment by maheshrajrp** [comment]
hi @svor 
thanks for documenting, I have a few questions, probably basic ones I guess, not sure if we have a documentation for these. like for example, I can see for Jupyter there's just one component mentioned in schema whereas, in the second one we have the-code-injector,  che-code-runtime-description, in short, what is a component, why do we need it, and what is the use case when we might need multiple components. Also, the same for commands and events, why and when do we need it? in short, having an explanation on how to create a plugin and thoughts that needs to be put into when creating one should really help alot to newbie users like me.

Also, we have @l0rd repo for trying out theia, where he had mentioned "Only works with libc v3 images (doesn't work with current universal developer image that is based on UBI8)", I'm figuring out the parts of the repo, and I have questions related to this. Maybe could we provide a disclaimer similar to that, helping us understand when and why there can be such issue ? 

Repo URL:
https://github.com/l0rd/theia-editor/tree/main

Maybe I am asking for too much, I dont know. I'll leave you to be the judge of it. But these are the main questions I have right now

**Comment by svor** [comment]
I'd say it's very depends on the editor

>in the second one we have the-code-injector, che-code-runtime-description, in short, what is a component, why do we need it, and what is the use case when we might need multiple components. Also, the same for commands and events, why and when do we need it?

@RomanNikitenko @azatsarynnyy can you help with this
