### ISSUE TITLE
Update che-docs preview to use https instead of http

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22864]
### Is your enhancement related to a problem? Please describe

When running the `start-preview-server` task to start the [che-docs](https://github.com/eclipse-che/che-docs) preview server, the preview is accessible by clicking the `Open in New Tab` button in the notification that appears:

<img width="502" alt="image" src="https://github.com/eclipse/che/assets/83611742/8c9ef749-73bb-4c86-84e0-72b41df5f195">

The preview url only works with http, not https.

### Describe the solution you'd like

It would be better if it was using https.

I noticed that simply changing the protocol to https like so: https://github.com/dkwon17/che-docs/commit/b2a9df1501abda42f52fe5003dc3b569690505a2 did not fix the problem, as I see this message when trying to access the preview url:
<img width="1440" alt="image" src="https://github.com/eclipse/che/assets/83611742/541a333c-06f9-4cc2-a7b7-3b509b542104">

**Comment by ibuziuk** [comment]
@dkwon17 seems to work for me with https://github.com/eclipse-che/che-docs/pull/2700
