### ISSUE TITLE
Verify functionality of each sample from devfile.io on Che

### ISSUE THREAD

**Issue by svor** [eclipse/che#22869]
### Is your task related to a problem? Please describe

Since we start using [devfile.io](https://registry.devfile.io/viewer) as a default registry for Che samples, we have to make sure that everything declared in the devfiles works as expected with a default Che-code editor:
- workspace can start;
- dev container provides all needed tools to work with the sample project;
- all declared commands work as expected;
- check debugging (if it's possible);
- try to run the sample project (if it's possible);
- Check if the devfile has an https endpoint, see: https://github.com/eclipse/che/issues/22869#issuecomment-1983269642 and https://github.com/eclipse/che/issues/22864. This is needed to properly open the application url from the editor's popup on latest version of Chrome browser.

All samples are available on [Che dogfooding instance](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/)

Here  is the list of samples:
| Devfile link | Verified | Assigned |
| :-------------: | :-------------: | :-------------:| 
| [.NET 5.0](https://github.com/devfile/registry/tree/main/stacks/dotnet50) |:heavy_check_mark: | @ibuziuk | 
| [.NET 6.0](https://github.com/devfile/registry/tree/main/stacks/dotnet60) | :heavy_check_mark:| @ibuziuk | 
| [.NET Core 3.1](https://github.com/devfile/registry/tree/main/stacks/dotnetcore31) | :heavy_check_mark: | @vitaliy-guliy |
| [Angular](https://github.com/devfile/registry/tree/main/stacks/nodejs-angular/2.0.2) | :heavy_check_mark: | @vitaliy-guliy |
| [Django](https://github.com/devfile/registry/tree/main/stacks/python-django) | :heavy_check_mark: https://github.com/devfile-samples/python-django-ex/pull/1 | @tolusha  |
| [Go Runtime](https://github.com/devfile/registry/tree/main/stacks/go/1.2.0) | :heavy_check_mark: https://github.com/devfile/registry/pull/357 | @tolusha  |
| [Laravel](https://github.com/devfile/registry/tree/main/stacks/php-laravel/1.0.1) | :heavy_check_mark:https://github.com/devfile/registry/pull/349 | @dkwon17 |
| [Maven Java](https://github.com/devfile/registry/tree/main/stacks/java-maven/1.3.0) | :heavy_check_mark: https://github.com/devfile/registry/pull/412 | @azatsarynnyy |
| [Next.js](https://github.com/devfile/registry/tree/main/stacks/nodejs-nextjs/1.0.3) | :heavy_check_mark: https://github.com/devfile/registry/pull/347 | @RomanNikitenko| 
| [Node.js Runtime](https://github.com/devfile/registry/tree/main/stacks/nodejs/2.1.1) | :heavy_check_mark: https://github.com/devfile/registry/pull/403 | @azatsarynnyy  |
| [Nuxt.js](https://github.com/devfile/registry/tree/main/stacks/nodejs-nuxtjs/1.0.3) | :heavy_check_mark: https://github.com/devfile/registry/pull/346 | @RomanNikitenko |  
| [Open Liberty Gradle](https://github.com/devfile/registry/tree/main/stacks/java-openliberty-gradle) | :heavy_check_mark:https://github.com/devfile/registry/pull/350 | @dkwon17 |
| [Open Liberty Maven](https://github.com/devfile/registry/tree/main/stacks/java-openliberty) | :heavy_check_mark:https://github.com/devfile/registry/pull/351 | @dkwon17 |
| [Python](https://github.com/devfile/registry/tree/main/stacks/python/2.1.0) | :heavy_check_mark: https://github.com/devfile/api/issues/1524 | @dmytro-ndp |
| [Quarkus Java](https://github.com/devfile/registry/tree/main/stacks/java-quarkus) |https://github.com/eclipse/che/issues/22906 | @vinokurig |
| [React](https://github.com/devfile/registry/tree/main/stacks/nodejs-react/2.0.2) |:heavy_check_mark:| @vinokurig |
| [Spring Boot](https://github.com/devfile/registry/tree/main/stacks/java-springboot/1.3.0) | :heavy_check_mark: https://github.com/devfile/api/issues/1526 | @dmytro-ndp |
| [Svelte](https://github.com/devfile/registry/tree/main/stacks/nodejs-svelte/1.0.3) | :heavy_check_mark: | @svor |
| [Universal Developer Image](https://github.com/devfile/registry/tree/main/stacks/udi) | :heavy_check_mark: | @svor |
| [Vert.x Java](https://github.com/devfile/registry/tree/main/stacks/java-vertx/1.3.0) | :heavy_check_mark:| @artaleks9  |
| [Vue](https://github.com/devfile/registry/tree/main/stacks/nodejs-vue/1.0.2) | :heavy_check_mark:| @artaleks9 |
| [WebSphere Liberty Gradle](https://github.com/devfile/registry/tree/main/stacks/java-websphereliberty-gradle) | :heavy_check_mark:| @akurinnoy  |
| [WebSphere Liberty Maven](https://github.com/devfile/registry/tree/main/stacks/java-websphereliberty) | :heavy_check_mark:| @akurinnoy  |
| [WildFly](https://github.com/devfile/registry/tree/main/stacks/java-wildfly/2.0.0) |:heavy_check_mark:| @olexii4 |
| [WildFly Bootable Jar](https://github.com/devfile/registry/tree/main/stacks/java-wildfly-bootable-jar/1.2.0) |:heavy_check_mark:| @olexii4  |

### Describe the solution you'd like

In case some problem was detected, need to provide a PR with the fix into https://github.com/devfile/registry.

If it's a problem that required additional investigation, it's better to register an issue where the problem should be described.

### Additional context

An example PR that contributed changes to the net 6.0 devfile: https://github.com/devfile/registry/pull/298

**Comment by ibuziuk** [comment]
PRs for .NET 5 and 6
 - https://github.com/devfile/registry/pull/312
 - https://github.com/devfile/registry/pull/298

**Comment by artaleks9** [comment]
**Vert.x Java**
- workspace runs, but `Unable to resolve nonexistent file` in the project tree:

![vertx-unable-resovle-file](https://github.com/eclipse/che/assets/5408906/92476982-588b-4d8c-a493-ce729a56da61)

- needed tools are provided, but 
- commands:
  -- _mvn-package_ -> build fail:
  
![vertx-build-mvn-package-error](https://github.com/eclipse/che/assets/5408906/a4747524-d19e-45e3-92b8-494aa23b7707)

  -- _run_  -> starting, but  `Application is not available`:
 
![vertx-run-application](https://github.com/eclipse/che/assets/5408906/dab4b650-f79c-4f86-a99c-7754d48e2adb)

![vertx-http-vertx-apps-no-available](https://github.com/eclipse/che/assets/5408906/1d4e2dee-9733-4834-b76a-33ccc067edf7)
 
  -- _debug_ -> launch, but `Application is not available`:
  
![vertx-dubug-launch](https://github.com/eclipse/che/assets/5408906/bb6f78d4-31f9-4968-8627-c024d4bf4d91)
![vertx-http-vertx-apps-no-available](https://github.com/eclipse/che/assets/5408906/c9b7319e-39b2-40bf-9aeb-6fd083e2c77a)

**Comment by artaleks9** [comment]
**Vue**

- workspace runs, but some code lines is highlight red
- needed tools are provided
- commands:
  -- _install:_
![vue-install-command](https://github.com/eclipse/che/assets/5408906/0e20cf91-1284-4868-bc36-94e7b2701f1d)

  -- _build_ launching, but `Application is not available`:
  
![vue-build-command-id](https://github.com/eclipse/che/assets/5408906/49c1ab89-6575-4961-ba93-f1bcfd2f7384)
![vue-application-not-available](https://github.com/eclipse/che/assets/5408906/2d418353-4e27-4d83-845f-92ef3b21f3d8)

**Comment by tolusha** [comment]
**[Django](https://github.com/devfile/registry/tree/main/stacks/python-django)**

Added recommended extensions and debug configuration
https://github.com/devfile-samples/python-django-ex/pull/1

**Comment by tolusha** [comment]
[Go Runtime](https://github.com/devfile/registry/tree/main/stacks/go/1.2.0)

https://github.com/devfile/api/issues/1490

**Comment by akurinnoy** [comment]
[Update stacks/java-websphereliberty/devfile.yaml](https://github.com/devfile/registry/pull/343#top)

[Update stacks/java-websphereliberty-gradle/devfile.yaml](https://github.com/devfile/registry/pull/344#top)

**Comment by RomanNikitenko** [comment]
- [Next.js PR](https://github.com/devfile/registry/pull/347) 
- [Nuxt.js PR](https://github.com/devfile/registry/pull/346)

**Comment by olexii4** [comment]
- [java-wildfly-bootable-jar PR]( https://github.com/devfile/registry/pull/345)
 - [WildFly v2.0.1 stack fails to build and deploy](https://github.com/devfile/api/issues/1493)

**Comment by dmytro-ndp** [comment]
@artaleks9 : about you comment: https://github.com/eclipse-che/che/issues/22869#issuecomment-2004470113
I have faced the same problem when check Python and Spring Boot devfiles.
Solution: use `https` endpoints instead of `http` in devfile, e.g. https://github.com/devfile/registry/pull/367

**Comment by vitaliy-guliy** [comment]
Pull request for dotnetcore31 and angular samples https://github.com/devfile/registry/pull/398
Requires merging of https://github.com/devfile-samples/devfile-stack-nodejs-angular/pull/3

**Comment by ibuziuk** [comment]
Closing as done
The only missing PR is https://github.com/odo-devfiles/springboot-ex/pull/5 but it can be merged outside the scope of the issue
