### ISSUE TITLE
Failure to build che-code and/or universal developer image due to kubernetes yum repo outage

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#22868]
### Describe the bug

A pull request check that builds che-dev image for che-code repository is failing because it is not possible to fetch yum packages for kubernetes repository.

The repository was added here
https://github.com/devfile/developer-images/blob/main/universal/ubi8/Dockerfile#L255

The failing job https://github.com/che-incubator/che-code/actions/runs/8156281567/job/22293535637

The issue potentially breaks the build of universal developer image as well.

### Che version

next (development version)

### Steps to reproduce

Create a pull request to che-code repository.

### Expected behavior

Che-dev pull request check should be passed.

**Comment by ibuziuk** [comment]
````
ibuziuk@ibuziuk-mac ~ % curl -I https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
HTTP/2 404 
content-length: 1449
content-type: text/html; charset=utf-8
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
date: Wed, 06 Mar 2024 15:47:57 GMT
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
````

**Comment by ibuziuk** [comment]
@mkuznyetsov will you be able to follow up on this ticket?

**Comment by vitaliy-guliy** [comment]
May be helpful
https://discuss.kubernetes.io/t/facing-challanges-for-installation-of-kubernest-cluster-setup-through-kubeadm-on-rhel8-9-vm-404-for-https-packages-cloud-google-com-yum-repos-kubernetes-el7-x86-64-repodata-repomd-xml-ip-142-250-115-139/27345
