### ISSUE TITLE
Can not start a workspace from Bitbucket server repository via OAuth2

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22871]
### Describe the bug

When starting a workspac from a Bitbucket Server private repository using OAuth2, an error occurs:
![screenshot-eclipse-che apps 2d236a98ef176eb912cb hypershift aws-2 ci openshift org-2024 03 07-10_32_15](https://github.com/eclipse/che/assets/7668752/e818a8de-7d87-4052-927a-65a46361fec8)
 

### Che version
7.83@next

### Steps to reproduce

1. Setup [oauth2 for BitBucket Server](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/).
2. Start a repository from a private BitBucket Server repository with a valid devfile.
3. Consent the BitBucket Server authorisation request.

See: an error occurs

### Expected behavior

Workspace must start successfully.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

### Additional context

Another try to start the workspace would be successful.

**Comment by artaleks9** [comment]
This bug is also reproduced with Bitbucket server OAuth1
