### ISSUE TITLE
Definition of the Che-Code editor in the ./che/che-editor.yaml file is ignored

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22879]
### Describe the bug

Editor definition in `./che/che-editor.yaml` is ignored:
- I defined editor image [here](https://github.com/RomanNikitenko/web-nodejs-sample/blob/f2600b056f8d3bb5ea4df96cd56364483b72e089/.che/che-editor.yaml#L33), so `quay.io/devspaces/code-rhel8:3.12` should be used as an editor image
- but it uses `quay.io/che-incubator/che-code:insiders` instead

### Che version

7.83.0-SNAPSHOT

### Steps to reproduce

1. Go to the dashboard =>  `Create Workspace` => `Import from Git`
2. Set `Git repo URL`: https://github.com/RomanNikitenko/web-nodejs-sample/tree/ubi9-devspaces-editor
3. Click `Create & Open`
4. Go to the Openshift console and check what image is used for the `che-code-injector` container

### Expected behavior

Image defined for the `che-code-injector` component in the `./che/che-editor.yaml` file should be used as an editor image.

### Additional context

I reproduced it on the dogfooding instance

**Comment by dmytro-ndp** [comment]
@RomanNikitenko : thanks for reporting.

There is Che 7.83.0 on Che dogfooding instance for a few weeks already.
Are you sure it's Eclipse Che 7.82 issue, not Eclipse Che Next?

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
you are right, I've changed it, thank you!

**Comment by akurinnoy** [comment]
Hi @RomanNikitenko ,

The `che-server` cannot properly resolve the link you provided because of the query parameter `...?rgh-link-date=2024-03-14T20%3A54%3A01Z`. In this case, it resolves the devfile from the main branch. 
As a workaround, you can use the repo link without a search param (`https://github.com/RomanNikitenko/web-nodejs-sample/tree/ubi9-devspaces-editor`) as it works as expected.

**Comment by RomanNikitenko** [comment]
@akurinnoy 
could you clarify where did you find the query parameter in my link?
I just put `https://github.com/RomanNikitenko/web-nodejs-sample/tree/ubi9-devspaces-editor` to the `Git Repo URL` field on the dashboard...

**Comment by akurinnoy** [comment]
@RomanNikitenko 


https://github.com/eclipse/che/assets/16220722/d25f947f-5bfb-4629-882d-417ae1adb152

**Comment by RomanNikitenko** [comment]
@akurinnoy 
did you try to follow `steps to reproduce`?

**Comment by RomanNikitenko** [comment]
https://github.com/eclipse/che/assets/5676062/e8c68351-8eb2-4108-bf29-0357c17cfe8c

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko
> 
>  Screen.Recording.2024-03-15.at.10.33.01.mov

I don't have any params like `...?rgh-link-date=2024-03-14T20%3A54%3A01Z` in my reference on my side.
It would be nice if someone could check that reference to detect if a problem with the link on my side or on your side.

**Comment by akurinnoy** [comment]
@RomanNikitenko 
> I don't have any params like ...?rgh-link-date=2024-03-14T20%3A54%3A01Z in my reference on my side.
It would be nice if someone could check that reference to detect if a problem with the link on my side or on your side.

I took a closer look, and it was added on my side by a browser extension, so I'm sorry for misleading you.

**Comment by akurinnoy** [comment]
The introduction of the Editor Selector panel (https://github.com/eclipse-che/che-dashboard/pull/1055) changed which editor is applied to a new workspace. After some discussions, we decided to do it as follows:
- when the editor selector panel (`Choose an Editor`) is opened, the selected editor will override the editor definition in the factory repo;
- when the editor definition panel (`Use an Editor Definition`) is opened and the fields are empty the editor definition in the factory repo will be applied.

So the workaround in your case should be as follows:
- in the Editor Selector panel switch to Use an Editor Definition
- paste the git repo URL 
- and click Create & Open

**Comment by akurinnoy** [comment]
@RomanNikitenko,

At the moment @olexii4 is working on the issue for improving the `Import from Git` widget [1]. It looks like a good place to discuss changes in the UX.

[1] https://github.com/eclipse/che/issues/22816

**Comment by RomanNikitenko** [comment]
Thank you for the clarification - now I understand how it works.
 
At the same time, from my point of view, it's not obvious:
>- when the editor selector panel (Choose an Editor) is opened, the selected editor will override the editor definition in the factory repo;
>- when the editor definition panel (Use an Editor Definition) is opened and the fields are empty the editor definition in the factory repo will be applied.

`Choose an Editor` is open by default, but I don't want to select it - editor is defined in my repo (./che/che-editor.yaml)  - I don't want to override it - how I can unselect it? 
it looks like I should open `Use an Editor Definition` - but again - there are two fields that I don't need to define - editor is defined in my repo (./che/che-editor.yaml)...
