### ISSUE TITLE
Tooling container `$PATH` is overridden

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22878]
### Describe the bug

The container `quay.io/mloriedo/cloud-dev-images:golang` has the following `$PATH`:

```
/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

but after using it as a tooling container of a Che workspace the `$PATH` becomes:

```
/checode/checode-linux-libc/ubi9/bin/remote-cli:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

The consequence is kind of drastic as I cannot use `go`:

```
$ go version
bash: go: command not found
```

### Che version

next (development version)

### Steps to reproduce

https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/cloud-dev-images?image=quay.io/mloriedo/cloud-dev-images:openjdk&che-editor=che-incubator/che-code/insiders

### Expected behavior

The folders in the original `$PATH` should still be in the workspace `$PATH`.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by RomanNikitenko** [comment]
@ibuziuk 
I don't know if it's related to VS Code side or operator area, but anyway we should take it for an investigation.

**Comment by RomanNikitenko** [comment]
I did the following:
- started Che-Code in `quay.io/mloriedo/cloud-dev-images:golang` container using port-forwarding (so - no dashboard, no operator)
- then checked `PATH` 

it was overridden:

<img width="1165" alt="image" src="https://github.com/eclipse/che/assets/5676062/9c3ac294-ebce-4d19-9807-7c20721f1a22">

**Comment by RomanNikitenko** [comment]
btw:
PATH has correct value when I create a terminal using `Terminal` => `New Terminal (select a Container)`

<img width="1453" alt="image" src="https://github.com/eclipse/che/assets/5676062/561175c5-6cd8-4e7f-b8e4-877fec93837c">
