### ISSUE TITLE
Eclipse Che: How to set workspace default resources (memory, CPU)

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22881]
### Summary

I am running eclipse che on k8s. eclipse che version 7.82.
How can I set the devworkspace default memory, CPU. I came across the below link, but no luck:
https://github.com/eclipse/che/issues/20381

---------------
spec:
  k8s:
    singleHostExposureType: 'gateway'
    tlsSecretName: 'che-tls-certificates'
  metrics:
    enable: true
  server:
    serverExposureStrategy: 'single-host'
    useInternalClusterSVCNames: true
    workspaceNamespaceDefault: 'che-<username>'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "-1"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "3"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "43200000"
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: 'che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h'
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: 'app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h'
      CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '500m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
---------------

Pls advice

TR
debaknta

**Comment by tolusha** [comment]
@debkantap 
You can set them in a devfile [1] 

[1] https://devfile.io/docs/2.2.2/limiting-resources-usage

**Comment by debkantap** [comment]
Thanks @tolusha for the response. This I have seen. Just wondering if anything there at the global level. But I think this should be fine.. I was trying to test vertical scaling, using "InPlacePodVerticalScaling" feature gate functionality -
https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/

This is alpha feature, it worked from resource perspective, but container restart is happening, which in-tern invalidating the session, resulting the user to login again.

TR
Debkanta

**Comment by debkantap** [comment]
Thanks @tolusha
