### ISSUE TITLE
Publish Db2 Connect to Open VSX

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22896]
### Is your task related to a problem? Please describe

I would like to install the extension for `Db2 Connect`, but I don't see it listed in the `open-vsx` https://open-vsx.org registry. 
The Db2 Connect plugin is in the vs code marketplace https://marketplace.visualstudio.com/items?itemName=IBM.Db2Connect

### Describe the solution you'd like

Is it possible to publish Db2 Connect to Open VSX?

**Comment by ibuziuk** [comment]
hello, @jorgeadrian93 
you should reach out to the extension owners and request to publish it to https://open-vsx.org/
Eclipse Che team does not own the extention
