### ISSUE TITLE
Provide hover with full workspace name in `Recent workspaces` list

### ISSUE THREAD

**Issue by apupier** [eclipse/che#22892]
### Is your enhancement related to a problem? Please describe

When having several workspaces having long names, the names are cropped and if several have same prefix we cannot make the difference apart from clicking on them.

### Describe the solution you'd like

I would like having the full name on hover

### Additional context

![image](https://github.com/eclipse/che/assets/1105127/ad17a1f4-2934-464c-aed9-fd6e1e630dc1)

**Comment by ibuziuk** [comment]
cc: @olexii4 @akurinnoy looks like a nice UX improvement
