### ISSUE TITLE
Failed to deploy Eclipse Che on disconnected cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22895]
### Describe the bug

Failed to deploy Eclipse Che on disconnected cluster

```
Error: Command server:deploy failed with the error: Eclipse Che is not Active
```

Sometimes 1 minute is not enough to wait Eclipse Che Active.
https://github.com/che-incubator/chectl/blob/ca5bf299c1d2c84cc77d1bd513112c9cdd14d89d/src/tasks/che-tasks.ts#L203

Probably we can make it configurable.

Another problem, is that Eclipse Che uses external devfile registry, despite the fact it should not
https://github.com/eclipse-che/che-docs/blob/2d9422d5569c4d6d0f13b6a71cfe823f4fccef8d/modules/administration-guide/attachments/restricted-environment/prepare-restricted-environment.sh#L90

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che on disconnected cluster

### Expected behavior

Eclipse Che is successfully deployed

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
The issue has been reproduced in Eclipse Che 7.85.0 on disconnected cluster:
```
05:35:19  [22:35:18] Wait Eclipse Che active [started]
05:37:55  [22:37:49] Wait Eclipse Che active [failed]
05:37:55  [22:37:49] → Eclipse Che is not Active.
05:37:55  [22:37:49] Wait for Eclipse Che ready [failed]
05:37:55  [22:37:49] → Eclipse Che is not Active.
05:37:55  Error: Command server:deploy failed with the error: Eclipse Che is not Active. See details: /home/hudson/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1714012139953.
```
Actually, Che Server pod had started successfully in the Eclipse Che instance: https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Che/job/ocp/job/Disconnected/job/install-che-to-disconnected-ocp/181/artifact/logs-and-configs/eclipse-che/logs/che.deployment.log/*view*/
