### ISSUE TITLE
Java-quarkus sample application starts with errors and outputs a blank screen

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22906]
### Describe the bug

CORS errors appear in the browser console and the page is not fully loaded.

### Che version

7.83@latest

### Steps to reproduce

1. Start a workspace from the `Java-Quarkus` sample.
2. Call the `dev-run` devfile command.
3. When the application is started, open the http-8080 endpoint in a new tab.

See: Only a blank screen with quarkus logo is visible, CORS errors are listed in the browser's console:
![Screenshot 2024-04-01 at 13 27 13](https://github.com/eclipse/che/assets/7668752/467a6a14-2f44-42b5-bdae-523b7917550c)

### Expected behavior

The application must be fully loaded without errors

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

### Additional context

If starting the application with `odo`, everything  works fine.

**Comment by maxandersen** [comment]
related to https://github.com/quarkusio/quarkus/issues/34097

is there a way for a process running in che what is the actual host?

**Comment by vinokurig** [comment]
Is blocked by https://github.com/quarkusio/quarkus/discussions/40241
