### ISSUE TITLE
Launching tests on PR checks fail on OpenShift CI because of error "failed to fetch Master Machines: failed to load asset"

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#22916]
### Describe the bug

The tests in PR checks don't run on OpenShift CI. It's observed in some repositories (che-server, plugin-registry) and have the same error. It seems, related to AWS infrastructure problem.

See error here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_che-plugin-registry/1906/pull-ci-eclipse-che-che-plugin-registry-main-v14-plugins-test-pr-check/1777697202299211776

Related PR:
https://github.com/eclipse-che/che-plugin-registry/pull/1906
https://github.com/eclipse-che/che-server/pull/676

### Che version

7.84@latest

### Steps to reproduce

Create PR and observe a launching tests on OpenShift CI

### Expected behavior

The tests should run

### Runtime

OpenShift

### Screenshots

![pull-ci-eclipse-che-che-plugin-registry](https://github.com/eclipse-che/che/assets/5408906/e7a26679-e086-4f88-9966-5d66dce07a65)

### Installation method

other (please specify in additional context)

### Environment

Amazon

**Comment by dmytro-ndp** [comment]
OpenShift CI jobs have been unblocked.
