### ISSUE TITLE
On ubuntu based workspace, VS Code "stop workspace" command fails

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22928]
### Describe the bug

![2024-04-17 14 49 36](https://github.com/eclipse-che/che/assets/606959/f7fcec32-6745-4889-9535-d1bf860213ed)

### Che version

next (development version)

### Steps to reproduce

On dogfooding instance. Open a workspace and try to stop it from VS Code UI.
Note that I am using Safari on macOS.

### Expected behavior

The workspace is stopped.

**Comment by svor** [comment]
@RomanNikitenko could you take a look please

**Comment by RomanNikitenko** [comment]
tested on the dogfooding instance using Safari on macOS


https://github.com/eclipse-che/che/assets/5676062/58b2d231-e869-4a3c-9583-4da1e684b662

**Comment by RomanNikitenko** [comment]
so, probably, Safari is not the cause of the problem, there was another reason...

**Comment by l0rd** [comment]
It's reproducible on an ubuntu based container ([Dockerfile](https://github.com/l0rd/cloud-dev-images/blob/main/ubuntu/Dockerfile), [image](quay.io/mloriedo/cloud-dev-images:ubuntu), [link to open it on dogfooding](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/cloud-dev-images?image=quay.io/mloriedo/cloud-dev-images:ubuntu&che-editor=che-incubator/che-code/insiders)).

From the extension host (remote) output:
```
2024-04-19 08:18:48.650 [error] Error: error:0A0000B9:SSL routines::no cipher match
	at configSecureContext (node:internal/tls/secure-context:231:11)
	at createSecureContext (node:_tls_common:117:3)
	at Object.createSecureContext (/checode/checode-linux-libc/ubi9/node_modules/@vscode/proxy-agent/out/index.js:444:34)
	at connect (node:_tls_wrap:1750:48)
	at Object.connect (/checode/checode-linux-libc/ubi9/node_modules/@vscode/proxy-agent/out/index.js:363:29)
	at Agent.createConnection (node:https:158:22)
	at Agent.createSocket (node:_http_agent:341:26)
	at Agent.addRequest (node:_http_agent:288:10)
	at /checode/checode-linux-libc/ubi9/node_modules/agent-base/dist/index.js:77:31
```

**Comment by l0rd** [comment]
> About - ubuntu - we have a separate issue for that: https://github.com/eclipse-che/che/issues/22862.
> Apart of Stop Workspace problem - it's not possible to install extensions, for example.

That's fair enough, no problem to close this issue but the issue you have linked says `che-code` doesn't start on vanilla ubuntu based image, which is false.

**Comment by RomanNikitenko** [comment]
In that issue `docker.io/ubuntu:20.04` image was reported, it's still not possible to start a workspace for that image.

About newer version of ubuntu - yes it's possible to start a workspace after these changes: https://github.com/che-incubator/che-code/pull/332, but there are still problems that I mentioned above.
