### ISSUE TITLE
Installation of Eclipse Che Next chectl is failing because https://eclipse.dev/che/chectl/ is not available

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22921]
### Describe the bug

It's not possible to install Eclipse Che using chectl, because chectl install script has disappeared from https://eclipse.dev/che/chectl/
![Screenshot from 2024-04-16 09-42-40](https://github.com/eclipse-che/che/assets/1197777/01f070bf-43e0-471e-a2f8-6758455eb41e)

Error message when try to install Eclipse Che using https://www.eclipse.org/che/chectl/ :
```
$bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

It affected periodic Eclipse Che tests and E2E tests on OpenShift CI jobs, which are failing on "_Build git source code into an image and tag it as root_" step with error message:
```
{  error occurred handling build root-amd64: the build root-amd64 failed after 55s with reason DockerBuildFailed: Dockerfile build strategy has failed.}
```
An example of failed job: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_ch[…]-main-v14-gitlab-with-oauth-setup-flow/1780130915125563392

### Che version

next (development version)

### Steps to reproduce

Download chectl script from https://eclipse.dev/che/chectl/

### Expected behavior

chectl script has been downloaded successfully

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context

Eclipse Foundation related tickets:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4545
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4535

**Comment by RomanNikitenko** [comment]
I faced the same problem within smoke test for the che-code: https://github.com/che-incubator/che-code/actions/runs/8689506423/job/23831378684

**Comment by ibuziuk** [comment]
@mkuznyetsov could you please take a look:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4535
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4545

**Comment by ibuziuk** [comment]
a more important question is why do we host https://raw.githubusercontent.com/che-incubator/chectl/gh-pages/install.sh
under https://eclipse.dev/che/chectl in general

**Comment by dmytro-ndp** [comment]
@tolusha , @l0rd , @benoitf : do you remember why it was decided to keep [chectl deployment bash script](https://raw.githubusercontent.com/che-incubator/chectl/gh-pages/install.sh) at the https://eclipse.org/che/chectl long time ago?

**Comment by ibuziuk** [comment]
@dmytro-ndp should be fixed by https://github.com/eclipse-che/che-website-publish/pull/4/

**Comment by dmytro-ndp** [comment]
@ibuziuk: thanks for the update.

https://eclipse.dev/che/chectl/ is currently redirecting to the https://che-incubator.github.io/chectl/install.sh, and it works when do it in browser.

At the same time Eclipse Che automated tests are using curl command, which doesn't handle such redirection correctly:
```
$ curl -sL https://eclipse.org/che/chectl/
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="https://www.eclipse.org/che/chectl/">
<script>location = "https://che-incubator.github.io/chectl/install.sh"</script>
<meta http-equiv="refresh" content="0; url=https://che-incubator.github.io/chectl/install.sh">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>The page you requested has been relocated to <a
        href="https://che-incubator.github.io/chectl/install.sh">https://che-incubator.github.io/chectl/install.sh</a>.
</p>
```

As a result, our tests keep failing:
```
$ bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

**Comment by ibuziuk** [comment]
@dmytro-ndp in this case we should consider updating the tests to use https://che-incubator.github.io/chectl/install.sh directly. it is not clear at this point why website hosted chectl scripts in general

**Comment by dmytro-ndp** [comment]
@ibuziuk : thanks for heads up.
I have opened issue https://github.com/eclipse-che/che/issues/22925 to fix E2E tests.

This issue could be closed, because https://eclipse.dev/che/chectl/ is returning chectl deployment script right now.
