### ISSUE TITLE
Dashboard should switch to the tab with already running workspace

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22933]
### Is your enhancement related to a problem? Please describe

I have a running workspace opened in a separate tab. If I go to the dashboard tab and select this workspace in the Recent Workspaces section, the dashboard opens the necessary browser tab, but starts over from the beginning: workspace opening steps, loading editor files, and so on.

https://github.com/eclipse-che/che/assets/16220722/cacbac9d-dd71-433f-b466-2c7c93b79b53

,

### Describe the solution you'd like

The dashboard should focus on the running workspace tab.

**Comment by olexii4** [comment]
@akurinnoy Are you going to use ```https://www.npmjs.com/package/better-opn``` ?
