### ISSUE TITLE
Error when start a workspace via factory from the dashboard

### ISSUE THREAD

**Issue by svor** [eclipse/che#22949]
### Describe the bug

It's not possible to start a workspace from the dashboard using a factory that contains an information about devfile (e.g. https://github.com/che-incubator/quarkus-api-example?df=smoke-test.devfile.yaml)

The error is **Could not reach devfile at https://github.com/che-incubator/quarkus-api-example?override.devfileFilename=smoke-test.devfile.yaml**

Also I see that **df=smoke-test.devfile.yaml** was automatically replaced with **override.devfileFilename=smoke-test.devfile.yaml**

### Che version

next (development version)

### Steps to reproduce

1. Open Create Workspace page on the dashboard
2. Put https://github.com/che-incubator/quarkus-api-example?df=smoke-test.devfile.yaml factory into Git repo URL:
3. Click Create & Open
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 04 30-17_16_13](https://github.com/eclipse-che/che/assets/1271546/f004b8dd-1fc9-41e9-bc2b-dbea4a500d8b)

### Expected behavior

Workspace should start without problems 

### Runtime

OpenShift

### Screenshots

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.04.30-17_07_17.webm](https://github.com/eclipse-che/che/assets/1271546/c0c10407-9f09-4038-ae09-852bf017e54b)

### Installation method

chectl/latest

### Environment

Linux

**Comment by RomanNikitenko** [comment]
I think smoke test fails for the Che-Code because of this issue: https://github.com/che-incubator/che-code/actions/runs/8896663168/job/24434464747?pr=353
