### ISSUE TITLE
Right click not working after first one.

### ISSUE THREAD

**Issue by guydog28** [eclipse/che#22953]
### Describe the bug

With the latest che, (7.85), after right clicking on something in the workspace, and choosing something from the right click menu, right click no longer pops up the menu anymore after that without refreshing the browser window.

### Che version

7.85@latest

### Steps to reproduce

1. Launch Workspace 
2. Right click a file, and select Open (doesn't really matter, click on any item in any right click context menu will do).
3. Right click the same thing again - no context menu.
4. Refresh browser
5. Repeat from step 2.

### Expected behavior

Context menu will appear on every right click.

### Runtime

Kubernetes (vanilla)

### Installation method

OperatorHub

### Environment

Amazon

### Eclipse Che Logs

I see these console errorr on Workspace browser load:

```
 GET https://che.dev.mydomain.com/myuser/my-workspace/3100/oss-dev/static/out/vsda_bg.wasm 404 (Not Found)
loader.js:3 
 
 GET https://che.dev.mydomain.com/myuser/my-workspace/3100/oss-dev/static/out/vsda.js net::ERR_ABORTED 404 (Not Found)

ERR [Extension Host] (node:6488) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

WARN: [Extension Host] Error trying to update permissions to installed binaries: Error: ENOENT: no such file or directory, scandir '/home/user/.local/state/vs-kubernetes/tools'

ERR [Extension Host] Unable to create telemetry client: "DEVWORKSPACE_TELEMETRY_BACKEND_PORT" is not set.
```

This shows up a bunch of times in the browser console after the first right-click attempt:

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at s.add (workbench.web.main.js:37:1529)
    at o.showHover (workbench.web.main.js:734:48235)
    at I.showHover (workbench.web.main.js:647:45670)
    at I.f (workbench.web.main.js:637:2108)
    at I.update (workbench.web.main.js:637:1894)
    at workbench.web.main.js:734:49958
    at workbench.web.main.js:149:19407
```

### Additional context

Reverting to 7.84, stopping and starting workspace resolved the issue.

**Comment by RomanNikitenko** [comment]
I can reproduce the behaviour using `quay.io/che-incubator/che-code:7.85.0` as editor image, 
thank you for reporting the problem!

I tested it for the `quay.io/che-incubator/che-code:next` - the bug already fixed in upstream.
Also page refreshing works as a workaround, although it allows to use a context menu only once and then the bug is reproduced again...

**Comment by guydog28** [comment]
@RomanNikitenko We also saw that refreshing the browser brought the right click back for one time only.  My team definitely did not like refreshing all day 😂. Reverting to 7.84 was better for us.

Do we know what commit it was fixed in, and if that will be a part of 7.86?

**Comment by RomanNikitenko** [comment]
@guydog28 
- sorry, I'm not aware what commit brings the fix
- the fix is present in the `main` of the Che-Code (as I can not reproduce the bug for the `next` version), so yes - it will be part of `7.86`

**Comment by RomanNikitenko** [comment]
Release process is starting today for `7.86`.
The bug is fixed for that version, closing this issue.
