### ISSUE TITLE
Deprecate and archive che-devfile-registry

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22960]
### Is your task related to a problem? Please describe

Eclipse Che is using devfile.io by default starting from 7.82.0 - https://github.com/eclipse-che/che/releases/tag/7.82.0
We can now deprecate and archive - https://github.com/eclipse-che/che-devfile-registry + related samples

### Describe the solution you'd like

Since devfile.io is used by default we can deprecate and archive https://github.com/eclipse-che/che-devfile-registry

As part of this exercise, we should also archive https://github.com/che-samples which we are not going to support anymore

### Additional context

In terms of downstream, we should replace getting-started samples with CM approach that operator would be managing - https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.13/html/administration_guide/configuring-devspaces#configuring-getting-started-samples 

tricky part is air-gap, and we need to find a solution for it

**Comment by ibuziuk** [comment]
cc: @tolusha @svor

**Comment by svor** [comment]
Devfile registry maintains [devworkspace generator tool](https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator). This tool is used in a few places to generate DevWorkspace and DevWorkspaceTemplate objects:
- [Upstream devfile registry](https://github.com/eclipse-che/che-devfile-registry/blob/main/build/scripts/generate_devworkspace_templates.sh#L24-L59)
- [Downstream devfile registry](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/che-devfile-registry/build/scripts/generate_devworkspace_templates.sh#L34-L35)
- [Che Dashboard](https://github.com/eclipse-che/che-dashboard/blob/e6a16fa1271c9cdcd7948dfa1ee0a9f99a346115/packages/dashboard-backend/package.json#L30)
- [Che Code](https://github.com/che-incubator/che-code/blob/c454fb62a5766957ab76f859a764d97f4a57008c/code/extensions/che-remote/package.json#L35)
- [E2E tests](https://github.com/search?q=repo%3Aeclipse-che%2Fche%20che-devworkspace-generator&type=code)
- Maybe somewhere else

So, this tool should be moved to another place with all related GH actions: https://github.com/eclipse-che/che-devfile-registry/tree/main/.github/workflows

**Comment by ibuziuk** [comment]
N.B. https://issues.redhat.com/browse/CRW-6618

**Comment by ibuziuk** [comment]
@tolusha @olexii4 @akurinnoy please, review the proposal - https://github.com/eclipse-che/che/issues/23026

**Comment by ibuziuk** [comment]
@tolusha @svor can I get +1 for archiving https://github.com/eclipse-che/che-devfile-registry ? I believe we can do it now

**Comment by svor** [comment]
> @tolusha @svor can I get +1 for archiving https://github.com/eclipse-che/che-devfile-registry ? I believe we can do it now

+1 from me
@mkuznyetsov what about Che release process, should it be updated when che-devfile-registry is archived?

**Comment by ibuziuk** [comment]
good point, I can archive it after the release process to avoid hiccups during the build

**Comment by mkuznyetsov** [comment]
> > @tolusha @svor can I get +1 for archiving https://github.com/eclipse-che/che-devfile-registry ? I believe we can do it now
> 
> +1 from me @mkuznyetsov what about Che release process, should it be updated when che-devfile-registry is archived?

right, [che-release](https://github.com/eclipse-che/che-release/blob/main/make-release.sh#L145) must be updated to not trigger che-devfile-registry release workflow anymore.
