### ISSUE TITLE
Automatic 'podman login' with configured container registry not working

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#22987]
### Describe the bug

After having configured a container registry in User Dashboard, new workspaces are not being automatically logged into the configured container registries. I tried with quay.io and docker.io and neither worked.

This is currently reproducible in the 3.14 builds of DevSpaces and on the dogfooding cluster.

### Che version

7.86@latest

### Steps to reproduce

1. Configure a container registry from the User Dashboard's User Preferences (click on the gravatar in the top right of the dashboard -> user preferences -> add a container registry with your credentials.
2. Start a workspace
3. Open a terminal and run `podman login --get-login <container-registry>`. For example: `podman login --get-login quay.io`
4. You'll see `Error: not logged into <container-registry>`. E.g. `Error: not logged into quay.io`

### Expected behavior

We should already be logged into the configured container registries.
For example, if quay.io is configured as a container registry, the output of `podman login --get-login quay.io` should be your quay.io username.  

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by AObuchow** [comment]
I can see that the associated `kubernetes.io/dockercfg`, `kubernetes.io/dockerconfigjson` are being created, and the dockerconfigjson has the appropriate value. Perhaps some other error is occurring when running the[ podman login command](https://github.com/eclipse-che/che-dashboard/pull/1094/files#diff-ac8ad14c1eff38ff4c3c3736b243cad43e98807f4354041dc79728b66e904f4bR178-R179) that's being "swallowed" by the `|| true`.

**Comment by tolusha** [comment]
Hello, @AObuchow 
I've tried on dogfooding cluster (+minikube cluster), but I wasn't able to reproduce the issue unfortunately.

**Comment by AObuchow** [comment]
@tolusha After looking into this further, I believe the [podman login command](https://github.com/eclipse-che/che-dashboard/pull/1094/files#diff-ac8ad14c1eff38ff4c3c3736b243cad43e98807f4354041dc79728b66e904f4bR178-R179) needs to surround the username and password with single quotes `''` to support any "special characters" such as `!`, so that they aren't interpreted by bash.

```
aobuchow@fedora:~$ echo !test
bash: !test: event not found
aobuchow@fedora:~$ echo '!test'
!test
```
