### ISSUE TITLE
Configuring Keycloak SSO to eclipse che

### ISSUE THREAD

**Issue by AkramMulani** [eclipse/che#22988]
### Summary

I have deployed eclipse che on "minikube" cluster using "chectl" command line tool.

where minikube has driver "docker"

It's working cool. but now I want to setup GitLab SSO. I think we can do it using keycloak.

So anyone has idea of how to configure keycloak for GitLab SSO or any SSO to eclipse che?

**Comment by dmytro-ndp** [comment]
@AkramMulani hello,
Do you think https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-minikube-keycloak-oidc/ article is relevant to your question?
