### ISSUE TITLE
Update Universal Developer Image to UBI9 to update Podman

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22995]
### Is your enhancement related to a problem? Please describe

The UDI based on UBI8 contains an old version of podman which has a few bugs that are fixed in podman 4.9+

### Describe the solution you'd like

Update the Universal Developer Image to be based on UBI9

**Comment by vitaliy-guliy** [comment]
I've just built universal developer image based on UBI8 (as it is in the repository) and noticed the image contains podman 4.9
```
$ podman -v
podman version 4.9.4-rhel
```

The same version I have on the dogfooding instance and on the developer sandbox.

**Comment by cgruver** [comment]
Closing as resolved.
