### ISSUE TITLE
As a User, I want to be warned that creating a workspace from unknown source could be dangerous 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23018]
### Is your enhancement related to a problem? Please describe

As a User, I want to be warned that creating a workspace from an unknown source could be dangerous

### Describe the solution you'd like

It is recommended not to create workspaces automatically, but first to show a user a warning message that describes the possible dangers of creating workspaces from unknown or untrusted repositories.
Potentially, add functionality to allowlist the list of repo that the administrator has to approve first.

### Additional context

Example of a similar functionality in Code OSS
<img width="517" alt="Screenshot 2024-06-26 at 13 58 13" src="https://github.com/eclipse-che/che/assets/1461122/55fbaf81-de0f-416e-a78c-7ad095965961">

**Comment by akurinnoy** [comment]
Hi @ibuziuk, I prepared some figma prototypes of what this warning might look like on the Getting Started and Workspace startup pages.

**Getting Started**
https://www.figma.com/proto/YcjE2a2NVzBsd8tMKZhzvH/Untrusted-main?page-id=0%3A1&node-id=10-27&viewport=294%2C512%2C0.08&t=4zIUgTuU2mkc2nkJ-1&scaling=contain&content-scaling=fixed&starting-point-node-id=10%3A27

**Workspace startup (with a modal warning)**
https://www.figma.com/proto/wlg9f5ic7IiZhaHqRwAY1M/Untrusted-startup-1?page-id=0%3A1&node-id=1-7&viewport=561%2C175%2C0.07&t=HKMPA6cbEzcOMEsa-1&scaling=contain&content-scaling=fixed&starting-point-node-id=1%3A7

**Workspace startup (with inline warning)**
https://www.figma.com/proto/65O4RMIqtu4MEtXiR4cgOl/Untrusted-startup-2?page-id=0%3A1&node-id=1-2&viewport=1023%2C911%2C0.25&t=BcHADMo1ne9Om9ea-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1%3A2
