### ISSUE TITLE
Allow Ports in Git Provider Endpoint for Dashboard - Personal Access Tokens

### ISSUE THREAD

**Issue by dlsiddon** [eclipse/che#23013]
### Is your enhancement related to a problem? Please describe

Currently adding a personal access token in the dashboard user preferences section does not allow adding a port number to the URL. Our enterprise currently has bitbucket installed and bound to a port other than 443.  I believe this is due to sanitation here
https://github.com/eclipse-che/che-dashboard/blob/28abf62c50c55e0bebc48ca98be9e5b70921548b/packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/index.tsx#L102

![image](https://github.com/eclipse-che/che/assets/73399407/5fb5eb72-8369-46f0-b78a-d9db5f82c951)

### Describe the solution you'd like

Expanding the regex to allow ports in the Git Provider Endpoint field.

Maybe this regex will work:
`/^https?:\/\/(?:(?:[a-z\d]+(?:-[a-z\d]+)*)\.)+[a-z]{2,}(?::\d+)?(?:\/[^\s]*)?$/i`

### Describe alternatives you've considered

I was able to create the necessary token through oc commands in our openshift environment following the instructions [here](https://eclipse.dev/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) but editing/adding in the dashboard ui does not allow submitting of the form when a port is in the url.

**Comment by ibuziuk** [comment]
@dlsiddon thanks for reporting, would you be interested in providing a PR with a fix to https://github.com/eclipse-che/che-dashboard with validation improvement ?
@olexii4 looks like smth. we should tune on the dashboard validation end.

**Comment by dlsiddon** [comment]
@ibuziuk I'll see if I can do all of the requirements of the PR. I have a personal fork with what i think are the personal changes, but looks like there is some setup for proper PR submission.
