### ISSUE TITLE
Setting Vale extension configuration file path in ".vscode/settings.json" file, Does not gets populated to Workspace, Remote, or User level in Openshift Dev Spaces.

### ISSUE THREAD

**Issue by dipakkarde** [eclipse/che#23010]
### Describe the bug

**Issue :**

Customer has vscode running on their local system and installed vale extension, Vale extension allows to specify a configuration file path by setting this in `.vscode/settings.json` file, Which gets populated to Workspace, Remote, or User level.

But with Dev Spaces when running python workspace with Vale extension installed, this setting is applied at the Folder level, which is not functioning and it does not gets populated to Workspace, Remote, or User level.

**Environment :**

RHOCP : 4.14
Dev Spaces : 3.12 and 3.13

### Che version

7.84

**Steps to reproduce**

Below are the reproducer steps :

- Install Dev Spaces 3.12 or 3.13
- Create a `python` workspace.
- Install Vale Extension.
- Configure vale settings, and set vale configuration file location by setting this in `.vscode/settings.json` file
But this does not gets populated to to Workspace, Remote, or User level.
- Manually setting vale configuration file location to Workspace, Remote, or User level works fine.
But this will be manual task for users to update the settings every-time and it is not feasible and
customer is expecting that this should be populated by updating the `.vscode/settings.json `file only.

**Expected behavior**

Setting Vale extension configuration file path in ` .vscode/settings.json` file, Should get populated to Workspace, Remote, or User level in Openshift Dev Spaces.

### Runtime

OpenShift

### Screenshots

<img width="1376" alt="vale-extension (4)" src="https://github.com/eclipse-che/che/assets/88081595/2d011329-114f-4b96-89d7-52a909cfd38e">

### Installation method

OperatorHub

### Environment

Linux

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
could you take a look?

**Comment by vitaliy-guliy** [comment]
It seems it's a normal behavior that folder settings are not propagated to upper level.
If you change something for user level, it will take effect for workspace and folder level, but not vice versa.

The additional info can be taken here https://code.visualstudio.com/docs/getstarted/settings

**Comment by vitaliy-guliy** [comment]
@dipakkarde could you test the case and provide your input again or just close the issue if it follows the doc https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence ?
