### ISSUE TITLE
Workspace start page goes to cyclic reload if refresh token mode is applied

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#23028]
### Describe the bug

Workspace start dashboard page reloads cyclically, if [refresh token mode](https://github.com/eclipse-che/che-docs/pull/2749/files) is applied. A new personal access token is created on each page restart.

### Che version

7.88@latest

### Steps to reproduce

1. Configure [GitHub oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
2. Apply [refresh token mode](https://github.com/eclipse-che/che-docs/pull/2749/files)
3. Start a workspace from a GitHub repository with a devfile.

### Expected behavior

Workspace starts after only one page refresh.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

**Comment by vinokurig** [comment]
Token expiration period for supported git porviders:
| Provider name | Expiration time |
|----------|----------|
| GitHub SAAS (github.com) | no expiration  |
| GitHub Enterprise Server | no expiration |
| GitLab SAAS (gitlab.com) | 2 hours |
| GitLab Server | 2 hours |
| Bitbucket SAAS (bitbucket.org) | 2 hours |
| Bitbucket Server | 90 days |
| Microsoft Azure Devops | 1 hour |

**Comment by ibuziuk** [comment]
@vinokurig thanks for investigation, we can skip GitHub in this case and refresh tokens every time for other providers if the property is enabled - https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-for-git-providers/ (we also need to mention that in the docs).

**Comment by vinokurig** [comment]
The issue is relevant for Azure devops as well.

**Comment by ibuziuk** [comment]
Moving to P1 to unblock the 7.89.0 release
