### ISSUE TITLE
As an admin, I would like to specify the `allowList` of the URLs based on which workspaces / CDEs can be started

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23030]
### Is your task related to a problem? Please describe

As an admin, I would like to specify the allowList of the URLs based on which workspaces / CDEs can be started e.g.

- only from private GitHub, BitBucket, Azure, Gitlab
- only from particular org
- only from ssh of particular repo etc

### Describe the solution you'd like
potential СR semantics

```
  devEnvironments:
      allowList / allowURLs / ? :
         - https://github.com # allow from github
         - git@github.com # allow from github over ssh
         - https://github.com/eclipse-che # allow particular group
         - https://github.com/eclipse-che/che # allow particular repo from github
         - etc.. # similar for other providers
```

### Describe alternatives you've considered

N/A

### Additional context
allowList is empty by default - all repos should be allowes

**Comment by tolusha** [comment]
```
devEnvironments:
  // This field specifies a list of URLs that are permitted to start workspaces. Only the exact URLs listed will be allowed to 
  // initiate a workspace environment. 
  allowedWorkspaceStartUrls:
    - "https://github.com"
    - "https://gitlab.com/your-group"
 
````

**Comment by ibuziuk** [comment]
@tolusha I believe we need smth. better

**Comment by ibuziuk** [comment]
@tolusha `allowedGitUrls` / `allowedGitURLs` ?

**Comment by tolusha** [comment]
It might be any urls, not just git ones

**Comment by tolusha** [comment]
`allowedWorkspaceSourceUrls`

**Comment by ibuziuk** [comment]
we should not use `Workspace` wording IMO. 

> It might be any urls, not just git ones

How come? we support only git no? no matter if it is self-hosted / ssh / provider etc.

**Comment by tolusha** [comment]
I mean it can be a raw devfile url.
Which basically can be anything.

**Comment by ibuziuk** [comment]
```
devEnvironments:
  allowedUrls | allowedSourceUrls 

```
?

**Comment by tolusha** [comment]
I am writing the documentation..
