### ISSUE TITLE
"Restart from local devfile" option resulting in http error

### ISSUE THREAD

**Issue by etsauer** [eclipse/che#23031]
### Describe the bug

When I update my devfile and hit the "restart from local devfile" option, I get a pop-up in vscode that says "Failed to update Devfile. HttpError: HTTP request failed". I've been unable to find any more info in the IDE output tab, Problems tab, or pod logs about this issue.

### Che version

7.81

### Steps to reproduce

1. Spin up this workspace: https://github.com/etsauer/devhub-plugin
2. Make a change to the devfile (I was adding a poststart task)
3. Click the che logo, then select "restart workspace from local devfile"

### Expected behavior

Work space restarts, and the page reloads

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by etsauer** [comment]
Here is all the version info from the Dashboard:

Dashboard Version 7.86.1
Server Version 3.14 @ 95f3e #3 :: Eclipse Che Dashboard 7.86.0 @ 4278a
Username user1
Browser Name chrome
Browser Version 126.0.0
Browser OS Windows 10

**Comment by etsauer** [comment]
I've tried doign a clean restart of the workspace, both using the "restart workspace" option from within the IDE, and the stop/start options from the Dashboard. The workspace restarts cleanly in both cases, but it doesn't change the "restart from local devfile" behavior

**Comment by vitaliy-guliy** [comment]
Probably duplication of https://github.com/eclipse-che/che/issues/22913

@etsauer could could you share the repo or even the devfile with your changes before the restart?

**Comment by etsauer** [comment]
Devfile is linked above. Only change I made was I added `    - load-project-envs` at the end under events.preStart

**Comment by vitaliy-guliy** [comment]
I'm not sure we can fix it on the editor side.

I did a fork of the repository from issue description https://github.com/vitaliy-guliy/devhub-plugin
then added `- load-project-envs` at the end of the devfile https://github.com/vitaliy-guliy/devhub-plugin/blob/main/devfile.yaml#L63
and tried to create a workspace from https://github.com/vitaliy-guliy/devhub-plugin

![Screenshot from 2024-07-09 17-46-20](https://github.com/eclipse-che/che/assets/1655894/880088da-9758-461f-9e1c-7ca898cc7800)

**Comment by etsauer** [comment]
So is the problem here that che doesn't support multiple preStart tasks?

**Comment by etsauer** [comment]
Ok, I figured it out... from the error message above, 

```
1 error occurred:
	* preStart type events are invalid: 
load-project-envs should either map to an apply command or a composite command with apply commands
```

and from reading about the different event types, I figured out that you can't have `exec` type commands listed in a `preStart` hook because at that point, there's no container to execute our commands in. So only `apply` type commands are valid in the `preStart` phase. I moved my command into a `postStart` event instead and everything works.

Here's the resulting devfile that works. https://github.com/etsauer/devhub-plugin/pull/4/files

So... could the topic for this issue move to, "how can we get the error message above to display in the IDE pop-up as well"?

**Comment by AObuchow** [comment]
@vitaliy-guliy Resolving this issue might also help debug https://github.com/eclipse-che/che/issues/23045 more easily
