### ISSUE TITLE
Move stow / kubedoc and other internal features to the Universal Base Image 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23033]
### Is your task related to a problem? Please describe

Move all internal Eclipse-specific configuration to the Universal Base Image:
- stow
- kubedoc 
- smth. else?

In the context of the current issue, this should be done for ubi8 only

### Describe the solution you'd like

([quay.io/devfile/base-developer-image:ubi8-latest](https://quay.io/repository/devfile/base-developer-image) the image should contain all Eclipse Che specific configuration

### Describe alternatives you've considered

N/A

### Additional context

Motivation https://issues.redhat.com/browse/CRW-6577

**Comment by dkwon17** [comment]
PR: https://github.com/devfile/developer-images/pull/179

**Comment by ssbarnea** [comment]
@dkwon17 @ibuziuk Maybe one of you can give me a hint regarding where I can raise bug report about the https://github.com/devfile/developer-images repository as it seems to have the issue tracker disabled and the README.md file does not mention any alternative way to raise issues.

**Comment by ibuziuk** [comment]
@ssbarnea hello, you can raise upstream issues in https://github.com/eclipse-che/che/issues
The current plan is to deprecate and remove ubi 8 from the upstream UDI codebase (ubi 9 should be only supported version in the upstream) as part of https://github.com/eclipse-che/che/issues/23034 
N.B. arm64 is planned to be added for UBI 9 as part of this issue
