### ISSUE TITLE
Deprecate and remove ubi 8 from the upstream UDI codebase (ubi 9 should be only supported version in the upstream)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23034]
### Is your task related to a problem? Please describe

Currently, UDI codebase has base images for both ubi 8 & 9 - https://github.com/devfile/developer-images/tree/main/base 
As part of this task, ubi 8 should be removed from the codebase, and ubi 9 is going to be the only supported version in the upstream.

### Describe the solution you'd like

Remove ubi 8 from https://github.com/devfile/developer-images codebase and only support ubi 9

### Describe alternatives you've considered

N/A

### Additional context

Old ubi 8 tags would still be available on https://quay.io/repository/devfile/base-developer-image?tab=tags but ubi 9 is going to be the only supported version in the upstream which would be updated regularly and built for `amd64` and `arm64`

**Comment by AObuchow** [comment]
A follow-up once https://github.com/devfile/developer-images/pull/190 is merged is to update the universal developer image repo GH actions to build and push the new UBI9-based UDI as well as update the README to only reference the UBI9-based images. See [this comment](https://github.com/devfile/developer-images/pull/190#issuecomment-2489439716) for more details.

**Comment by ibuziuk** [comment]
@dkwon17 I merged https://github.com/devfile/developer-images/pull/199, so I believe we can close the issue
