### ISSUE TITLE
chectl: It seems no check OIDC provider configured using `getEnsureOIDCProviderInstalledTask` Task

### ISSUE THREAD

**Issue by ynqa** [eclipse/che#23047]
### Describe the bug

There is a task called `getEnsureOIDCProviderInstalledTask` to check whether OIDC provider was configured
- https://github.com/che-incubator/chectl/blob/7.88.0/src/tasks/platform-tasks.ts#L20

However, this task is not called from anywhere, especially not from [deploy.ts](https://github.com/che-incubator/chectl/blob/7.88.0/src/commands/server/deploy.ts). So it seems to be skipped on `server:deploy` running regardless of whether `--skip-oidc-provider-check` is specified or not.

### Che version

7.88@latest

### Steps to reproduce

Simply run the following `server:deploy` command without `--skip-oidc-provider-check` flag

```
chectl server:deploy \
    --platform=k8s \
    --skip-cert-manager \
    --domain=${DOMAIN} \
    --che-operator-cr-patch-yaml=${PATCH_FILE_PATH}
```

If the task is enabled, the title of `Check if OIDC Provider installed` will be displayed
- https://github.com/che-incubator/chectl/blob/7.88.0/src/tasks/platform-tasks.ts#L23C15-L23C47

But not like:
(Note that this is the state in progress)

```
✔ Verify Kubernetes API...[1.28+]
  ✔ Kubernetes preflight checklist
    ✔ Verify if kubectl is installed...[OK]
    ✔ Verify domain is set...[OK]
  ✔ Create Namespace eclipse-che...[Exists]
  ↓ Install Cert Manager v1.8.2 [skipped]
  ✔ Start following Eclipse Che installation logs...[OK]
  ❯ Deploy Eclipse Che operator
    ❯ Install Dev Workspace operator
      ⠙ Create Namespace devworkspace-controller
        Create Dev Workspace operator resources
        Wait for Dev Workspace operator ready
      Create ServiceAccount che-operator
      Create RBAC
      Create Certificate che-operator-serving-cert
      Create Issuer che-operator-selfsigned-issuer
      Create Service che-operator-service
      Create CRD checlusters.org.eclipse.che
      Waiting
      Create Deployment che-operator
      Eclipse Che Operator pod bootstrap
      Create ValidatingWebhookConfiguration org.eclipse.che
      Create MutatingWebhookConfiguration org.eclipse.che
      Create CheCluster Custom Resource
```

### Expected behavior

During the certain per-installation phase, the title of `Check if OIDC Provider installed` is displayed, and it is checked whether `issuer url` and `client id` are defined as arguments of kube-apiserver.

### Runtime

Kubernetes (vanilla)

### Screenshots

Probably not necessary.

### Installation method

chectl/latest

### Environment

macOS

**Comment by ibuziuk** [comment]
@ynqa would you be interested in contributing a fix?

**Comment by ynqa** [comment]
@ibuziuk I just submitted the pull request https://github.com/che-incubator/chectl/pull/2902. Please confirm it :)

**Comment by ynqa** [comment]
https://github.com/che-incubator/chectl/pull/2902 was merged.
