### ISSUE TITLE
Resource monitor doesn't work

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23044]
### Describe the bug

I get `Resource monitor won't be displayed. Metrics Server is not enabled on the cluster.` warning on the dogfooding instance.
I'm not aware if it's something that really should be configured
or
it's a potential problem on the resource monitor extension side.

### Che version

7.88@latest

### Steps to reproduce

1. Create a workspace on the dogfooding instance.
2. Click `Resources` button on the bottom panel.
3. Check notifications

### Expected behavior

Resource monitor should display info about resources.

### Runtime

I reproduced it on the dogfooding instance

### Screenshots

<img width="456" alt="image" src="https://github.com/user-attachments/assets/1d66089f-4b42-46c3-a4a0-0129d92fdf8d">

### Eclipse Che Logs

I found the following in logs:

```shell
workbench.web.main.js:2031 [eclipse-che.resource-monitor]Cannot connect to Metrics Server. Status code: 404. Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

```

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/d8d4482f-d752-449b-ac51-23d7e74a24fa">

**Comment by ibuziuk** [comment]
Does not seem to work for me on Developer Sandbox / 3.14 but the error is different:

<img width="446" alt="Screenshot 2024-07-18 at 14 43 52" src="https://github.com/user-attachments/assets/b8ed40b1-e46b-4266-9d4b-549ae0c71966">

**Comment by paddy667** [comment]
I have the same issue, version:
![image](https://github.com/user-attachments/assets/30b19532-ff3b-4f49-95cd-2d7c98324931)

**Comment by vitaliy-guliy** [comment]
I noticed that on the dogfooding instance when the url to the metrics server has trailing slash, nothing is returned
```
$ kubectl get --raw /apis/metrics.k8s.io/v1beta1/
Error from server (NotFound): the server could not find the requested resource
```

If I remove trailing slash, it works
```
$ kubectl get --raw /apis/metrics.k8s.io/v1beta1 | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nodes",
      "singularName": "node",
      "namespaced": false,
      "kind": "NodeMetrics",
      "verbs": [
        "get",
        "list"
      ]
    },
    {
      "name": "pods",
      "singularName": "pod",
      "namespaced": true,
      "kind": "PodMetrics",
      "verbs": [
        "get",
        "list"
      ]
    }
  ]
}
```

On the developer sandbox it works with and without trailing slash.
