### ISSUE TITLE
Che-Code white page

### ISSUE THREAD

**Issue by batleforc** [eclipse/che#23055]
### Describe the bug

While starting WorkSpace using che code i end up having a white screen and nothing more is loading

### Che version

next (development version)

### Steps to reproduce

1. Have an instance running of Eclipse che (Fully wiped then 
2. Start workspace like https://github.com/batleforc/Dev-cli.git with any version of the che-code image (0.86/0.88/latest/insiders)
3. Enjoy the white page.

In reality, the devtools show that there is a problem :
![image](https://github.com/user-attachments/assets/7734d2fa-fe04-443a-a596-63948b3bd5ae)
And at the mentioned place : 
![image](https://github.com/user-attachments/assets/9b143b14-9627-4456-9db5-ff5532b4b5cd)

### Expected behavior

The usual VsCode IDE showing

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/next

### Environment

Linux

**Comment by batleforc** [comment]
The problem was fixed by removing the new line in /checode/checode-linux-libc/ubi9/out/vs/code/browser/workbench/workbench.js

**Comment by azatsarynnyy** [comment]
> The problem was fixed by removing the new line in /checode/checode-linux-libc/ubi9/out/vs/code/browser/workbench/workbench.js
> 
> In theory, this is the line that generate the problem https://github.com/che-incubator/che-code/blob/eeb3e4aa7a76b848e7cbcb3661770137464d8e8f/code/src/vs/code/browser/workbench/workbench.ts#L48

@batleforc thanks for reporting and investigating it.
@vitaliy-guliy can it be related to https://github.com/che-incubator/che-code/pull/340

**Comment by batleforc** [comment]
Hi, Your answer gives me a temporary fix :D 
The ssh key injected inside was my own, and I found out with [the MR content](https://github.com/che-incubator/che-code/blob/1dbb207fce2719ae6a3b581a9f31a4a91720c6c3/launcher/src/local-storage-key-provider.ts#L28). Once the config map removed, the IDE worked fine. Turn's out, I had a newline at the end of the file that broke everything.
It's totally my fault --'

**Comment by azatsarynnyy** [comment]
> Hi, Your answer gives me a temporary fix :D The ssh key injected inside was my own, and I found out with [the MR content](https://github.com/che-incubator/che-code/blob/1dbb207fce2719ae6a3b581a9f31a4a91720c6c3/launcher/src/local-storage-key-provider.ts#L28). Once the config map removed, the IDE worked fine. Turn's out, I had a newline at the end of the file that broke everything. It's totally my fault --'

Hi @batleforc 
I'm glad that the PR I mentioned helped you figure out the cause of the problem.
The issue can be closed, right?

**Comment by batleforc** [comment]
> > Hi, Your answer gives me a temporary fix :D The ssh key injected inside was my own, and I found out with [the MR content](https://github.com/che-incubator/che-code/blob/1dbb207fce2719ae6a3b581a9f31a4a91720c6c3/launcher/src/local-storage-key-provider.ts#L28). Once the config map removed, the IDE worked fine. Turn's out, I had a newline at the end of the file that broke everything. It's totally my fault --'
> 
> Hi @batleforc I'm glad that the PR I mentioned helped you figure out the cause of the problem. The issue can be closed, right?

Shouldn't this case be prevented ? Any user that would have a newline at the end of the ssh key would encounter the same bug.

**Comment by ibuziuk** [comment]
@batleforc great catch, removing the blocker label and making it P1
maybe you would be interested in providing PR with fix as well ;-) ?

**Comment by vitaliy-guliy** [comment]
Thanks @batleforc for the contribution.
