### ISSUE TITLE
Integrate Che with all JetBrains IDEs that support remote development via Gateway

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#23057]
### Is your task related to a problem? Please describe

JetBrains provides several IDEs with the remote development support:
- IntelliJ IDEA Ultimate
- PyCharm
- GoLand
- WebStorm
- CLion
- PhpStorm
- RubyMine
- Rider

Currently, IntelliJ IDEA Ultimate can be used with Che.

### Describe the solution you'd like
1. Include all JetBrains IDEs that support remote development in the existing editor image https://quay.io/repository/che-incubator/che-idea-dev-server?tab=tags 
We can rename it within this issue or later to reflect that it's a single image for different JetBrains IDEs.
2. Add the new editor definitions to the Che-Operator.

### Additional context

https://github.com/che-incubator/che-idea-dev-server
https://github.com/eclipse-che/che-operator/tree/main/editors-definitions

**Comment by ibuziuk** [comment]
@azatsarynnyy as part of this issue I believe we need to enable all the supported flavours:
<img width="572" alt="Screenshot 2024-08-05 at 14 56 15" src="https://github.com/user-attachments/assets/5812db32-cbce-47df-a78d-d231c61d1bb5">
