### ISSUE TITLE
Publish Dev Spaces compatibility matrix

### ISSUE THREAD

**Issue by deerskindoll** [eclipse/che#23051]
### Is your task related to a problem? Please describe

Please consider publishing compatibility matrix to Customer Portal to make it discoverable by our Customers. 
If we could add Web Terminal to this matrix even better.

### Describe the solution you'd like

potential docs improvement

### Additional context

https://issues.redhat.com/browse/CRW-5743

**Comment by ibuziuk** [comment]
Please, do not create product specific issues to the upstream
