### ISSUE TITLE
feat: Enable to patch command/args for oauth2-proxy Deployment

### ISSUE THREAD

**Issue by ynqa** [eclipse/che#23052]
### Is your enhancement related to a problem? Please describe

The cue is the following CSRF-related issue. This was resolved by adding a specific flag to oauth2-proxy (see details below)

- https://github.com/eclipse-che/che/issues/22135#issuecomment-2238657733

### Describe the solution you'd like

The following codes let you partially override the settings of oauth2-proxy Deployment:

- https://github.com/eclipse-che/che-operator/blob/7.88.0/api/v2/checluster_types.go#L567
- https://github.com/eclipse-che/che-operator/blob/7.88.0/api/v2/checluster_types.go#L642-L670

However, it's not possible to override the command/args. Therefore, how about making it possible to patch the command/args in Containers struct?

### Describe alternatives you've considered

As an alternative, there is a way to adjust the default command/args each time. However, considering the issue description and subsequent comments, this method seems challenging as the necessary flags may not be required in all situations.

Additionally, oauth2-proxy has many other configurable flags besides `--cookie-csrf-per-request`, so it seems better to allow users to adjust them.

### Additional context

By the way, how about renaming this struct and its caller to something like `deploymentPatch` instead of `deployment`? Since it is not equivalent to apps/v1 Deployment, it caused some confusion about what settings are possible.

- https://github.com/kubernetes/kubernetes/blob/v1.30.3/pkg/apis/apps/types.go#L355

**Comment by tolusha** [comment]
Hello, @ynqa 
Accordingly to [1], oauth2-proxy can be configured via [environment variables](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#environment-variables). 

Could you try the following:
```
        deployment:
          containers:
            - env:
                - name: OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST
                  value: "..."
              name: oauth-proxy

```

[1] https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/

**Comment by ynqa** [comment]
@tolusha Thank you :) I completely overlooked it. It looks all arguments can be expressed as environment variables. So this enhancement may not be necessary. Close this one.
