### ISSUE TITLE
How does running a devfile task in an arbitrary container work?

### ISSUE THREAD

**Issue by ryanw666** [eclipse/che#23069]
### Summary

I'm writing a custom vscode extension that needs to be able to run devfile tasks. I found that the `workbench.action.tasks.runTask` command doesn't work as expected when run from an extension: it only opens the command dropdown and filters the list of tasks to show, but doesn't actually run it. So I resorted to using `vscode.window.createTerminal` and passing the commands into there. But this means they're always running in the `tools` container (the one that contains VSCode in che workspaces), whereas in the devfile each command could have a `component` (container) specified.

I looked in VSCode documentation and couldn't find anything about choosing a container for tasks to run in, so I wonder how Che implements this behavior, and is there a way I can replicate it in VSCode terminals? Or does anyone know a way to have an extension actually trigger a task?

**Comment by ibuziuk** [comment]
@azatsarynnyy @RomanNikitenko @vitaliy-guliy please, review

**Comment by vitaliy-guliy** [comment]
In a sample [I created](https://github.com/vitaliy-guliy/vscode-test-extension/tree/test-run-container-task) I was able to easily run a task described in the devfile.

```
  - id: test-sql
    exec:
      component: mariadb
      commandLine: |
        mysql -u root petclinic < ${PROJECT_SOURCE}/mysql/test.sql && \
        echo "\e[32mDone.\e[0m"
```

One important thing here, that you have to specify the container in the task definition.

Having that it become possible to run a task with
```
commands.executeCommand('workbench.action.tasks.runTask', `devfile: test-sql`);
```

**Comment by vitaliy-guliy** [comment]
@ryanw666 feel free to reopen issue if necessary
