### ISSUE TITLE
Used CPU value is wrong in resources monitor

### ISSUE THREAD

**Issue by svor** [eclipse/che#23066]
### Describe the bug

The value of the used CPU is significantly higher than the limited one, and it's not very readable. Please see the attached screenshot.:
![screenshot-nimbusweb me-2024 07 31-15_05_56](https://github.com/user-attachments/assets/9dd52476-4781-4a66-9a6b-56818e0af2b6)

### Che version

7.89@latest

### Steps to reproduce

1. I've started workspace using https://github.com/redhat-developer/devspaces/tree/devspaces-3-rhel-8 on dev sandbox https://devspaces.apps.sandbox-m4.g2pi.p1.openshiftapps.com/

### Expected behavior

The value of used CPU resources from resources monitor should be readable 

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

Linux

**Comment by ibuziuk** [comment]
@dkwon17 we need to address it for 3.16
potentially related issues:
- https://github.com/eclipse-che/che/issues/23066
- https://issues.redhat.com/browse/CRW-6888
