### ISSUE TITLE
As an admin, I would like to restrict the total number of 'Running' workspaces on a cluster

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23081]
### Is your task related to a problem? Please describe

As an admin, I would like to restrict the total number of 'Running' workspaces on a cluster using CR property e.g.

```
 devEnvironments:
    maxNumberOfRunningWorkspaces: 200 // -1 by default which means unlimited
```

N.B. We already have `maxNumberOfWorkspacesPerUser`, but this issue is about limiting the overall number of the DW objects with the "Running" state on the cluster.

from the Dashboard UX perspective when the threshold is hit and yet another workspace is about to start the error message should be shown:

"Max number of workspaces running on the cluster: N"

### Describe the solution you'd like

N/A

### Additional context

N/A

**Comment by ibuziuk** [comment]
@dkwon17 @AObuchow @tolusha @olexii4 @akurinnoy please, review 
we need to prioritize it for the next sprint

**Comment by tolusha** [comment]
@ibuziuk 
Does it sound better?
`maxNumberOfRunningWorkspacesPerCluster`

because we already have
`maxNumberOfRunningWorkspacesPerUser`

**Comment by ibuziuk** [comment]
`maxNumberOfRunningWorkspacesPerCluster` sounds good
