### ISSUE TITLE
Smoke test fails for Che-Code

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23099]
### Describe the bug

The error is:
```
The SmokeTest userstory
       Create workspace from factory:https://github.com/che-incubator/quarkus-api-example?df=smoke-test.devfile.yaml
         Create and open new workspace from factory:https://github.com/che-incubator/quarkus-api-example?df=smoke-test.devfile.yaml:
     TimeoutError: Exceeded maximum clicking attempts, the 'By(xpath, //div[@id='page-sidebar']//a[text()='Create Workspace'])' element is not clickable
      at DriverHelper.waitAndClick (/tmp/e2e/utils/DriverHelper.ts:308:15)
      at async Dashboard.clickCreateWorkspaceButton (/tmp/e2e/pageobjects/dashboard/Dashboard.ts:97:9)
      at async Context.<anonymous> (/tmp/e2e/tests-library/WorkspaceHandlingTests.ts:71:13)
```

### Che version

7.90@latest

### Steps to reproduce

Please see https://github.com/che-incubator/che-code/actions/runs/10427763710/job/28929617792?pr=402

### Expected behavior

Smoke test successfully passes for the Che-Code

**Comment by ibuziuk** [comment]
@dmytro-ndp @musienko-maxim should we make it a blocker?

**Comment by musienko-maxim** [comment]
It seems the problem on the Smoke test side is that the trust dialog is not performed:
![Selection_002](https://github.com/user-attachments/assets/718270b5-d493-4f24-94af-b4f548b38f0b)
I need to create an issue and update the test image by performing the dialog. Try to look at this and fix ASAP

**Comment by dmytro-ndp** [comment]
SmokeTest itself has already fixed to handle untrusted source warning (see PR https://github.com/eclipse-che/che/pull/23088).
It should be enough to update quay.io/mmusiien/che-e2e:smoke-test , so no need to create of a separate issue, IMHO.

**Comment by musienko-maxim** [comment]
The test image was updated to the actual state we need to check it in the next running of a smoke test

**Comment by RomanNikitenko** [comment]
@dmytro-ndp @musienko-maxim 
The smoke test passed successfully in my PR https://github.com/che-incubator/che-code/actions/runs/10451332989/job/29039258589?pr=398.
Thank you both for your help!
