### ISSUE TITLE
The Untrusted Repository modal reappears when the workspace starts

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#23097]
### Describe the bug

The Untrusted Repository modal reappears when the workspace starts.

### Che version

7.90@latest

### Steps to reproduce

1. Create a new workspace from an untrusted repository URL: 
    1.1. If necessary, remove the `trusted-sources` filed from the `workspace-preferences-configmap`);
    1.2. Paste the repository URL into the Import from Git field and click Create & Open;
    1.3. Confirm that you trust the authors of the repository;
2. While the workspace is starting up, switch between the tabs on the page: Progress -> Logs -> Events;
3. The Untrusted Repository modal should appear at some moment.

### Expected behavior

Once confirmed, the Untrusted Repository modal should not be displayed for the same repository URL.

### Runtime

minikube

### Screenshots

https://github.com/user-attachments/assets/47c8bb20-07d7-4143-8b6e-fca1411377d1

### Installation method

chectl/next

### Environment

macOS

**Comment by ibuziuk** [comment]
👍 I believe we will need a cherry-pick to 7.90.x
