### ISSUE TITLE
Add option to deploy che component (che-dashboard, che-server, che-gateway, etc.) on specific nodes

### ISSUE THREAD

**Issue by huonguyenlt** [eclipse/che#23096]
### Is your enhancement related to a problem? Please describe

I am deploying che on EKS. I want to deploy all the che components to the same node or node groups. However, it looks like there is no option to do that. 
I install che using che operator. I can add the node selector to the che-operator deployment to install it on the specific node. But when che operator starts to deploy other che components (che-dashboard, che-server, che-gateway, etc.), all the components go to different nodes. Please help.

### Describe the solution you'd like

1. If you already had the solution for it, please educate me. Or
2. add nodeselector option for each che component

**Comment by ibuziuk** [comment]
@huonguyenlt thank you for creating this story. Would you be interested in contributing this functionality to che-operator - https://github.com/eclipse-che/che-operator 
cc: @tolusha
