### ISSUE TITLE
Workspace details dropdown item is missing

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#23093]
### Describe the bug

In the list of workspaces in the left hand tab on the dashboard, there used to be a `Workspace Details` item used to navigate to the Workspace Details page:

![image](https://github.com/user-attachments/assets/0d36f000-a73e-41d4-81a0-b027d3e9adb5)

In the latest version of Eclipse Che, it is missing:
![Screenshot from 2024-08-15 11-48-22](https://github.com/user-attachments/assets/80cd1bfe-8544-41a4-a217-fdd1ada5f7a8)

### Che version

next (development version)

### Steps to reproduce

 Create a workspace, and open the workspace dropdown on the left hand side of the dashboard

### Expected behavior

The `Workspace Details` item should exist in the dropdown

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by achdmbp** [comment]
has this issue been triaged? do you agree this is a bug and needs to be fixed? I believe this functionality was there in the past so it might be a matter of just bringing the code back. let me know if this is ready to create a PR for it

**Comment by mbenitez1607** [comment]
@achdmbp as you can see above the team is looking at this, however in early stages. However, if you have a PR or are able to provide one please do so, someone will be happy to review it
