### ISSUE TITLE
Workspace should be started when click Continue button on Untrusted source warning window

### ISSUE THREAD

**Issue by svor** [eclipse/che#23107]
### Describe the bug

When click the **Continue** button on Untrusted source warning window, a workspace is not started. To start the workspace need to click **Create&Open** button second time   

### Che version

next (development version)

### Steps to reproduce

Try to start a workspace using any factory on dogfooding instance

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.20-11_23_39.webm](https://github.com/user-attachments/assets/4a061eee-a83e-48c4-9ee3-580885962ba5)

### Expected behavior

After clicking the **Continue** button, the workspace should be created

### Runtime

OpenShift

### Installation method

chectl/latest, chectl/next

### Environment

Linux

**Comment by akurinnoy** [comment]
Hi @svor , can you please confirm that the bug is still there?

**Comment by svor** [comment]
@akurinnoy after pressing Continue button, two new tabs are opened where the workspace is starting:
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.26-10_33_44.webm](https://github.com/user-attachments/assets/5e6d9f29-aaad-431c-87c7-1c99835d6f26)
