### ISSUE TITLE
Can I use gitlab as an OIDC provider?

### ISSUE THREAD

**Issue by huonguyenlt** [eclipse/che#23104]
### Summary

I tried to setup gitlab as an oidc provider and then associated it with my EKS cluster. When I try to login to the che server. It request me to login to gitlab to continue. But after login to gitlab, I have this error: "The redirect URI included is not valid." I use same che server url for the redirect url when setup gitlab oidc
![image](https://github.com/user-attachments/assets/2286b79b-2670-4f63-9516-b62c6917add6). 

So the question is is there any error in my setup, or we can just not use gitlab as an oidc provider

**Comment by huonguyenlt** [comment]
I think I need to know the redirect url of eclipse che. It is not mentioned anywhere in the document

**Comment by dkwon17** [comment]
Hello @tolusha , could you please take a look?

**Comment by tolusha** [comment]
Hello @huonguyenlt 
Could you try this url: `https://<CHE_HOST>/oauth/callback`
``
