### ISSUE TITLE
I cannot uninstall chectl client and I cannot use another version!

### ISSUE THREAD

**Issue by mcz-adhamsabry** [eclipse/che#23108]
### Describe the bug

I removed chectl client from `/usr/local/bin` and `/usr/local/lib` which were installed via https://che-incubator.github.io/chectl/install.sh
I followed the instructions in https://github.com/che-incubator/chectl :
![image](https://github.com/user-attachments/assets/48183991-5cd7-4233-ab74-9afdc2a470c5)
Every time I run `chectl --version`, no luck, shows the latest version
I ran `which chectl` to confirm the installation folder.

### Che version

7.90@latest

### Steps to reproduce

I removed chectl client from `/usr/local/bin` and `/usr/local/lib` which were installed via https://che-incubator.github.io/chectl/install.sh
I followed the instructions in https://github.com/che-incubator/chectl :
![image](https://github.com/user-attachments/assets/48183991-5cd7-4233-ab74-9afdc2a470c5)
Every time I run `chectl --version`, no luck, shows the latest version
I ran `which chectl` to confirm the installation folder.

### Expected behavior

It should output the version I downloaded

### Runtime

other (please specify in additional context)

### Screenshots

![image](https://github.com/user-attachments/assets/48183991-5cd7-4233-ab74-9afdc2a470c5)

### Installation method

other (please specify in additional context)

### Environment

macOS

### Eclipse Che Logs

```shell
Downloaded version from https://github.com/che-incubator/chectl/releases
```

**Comment by tolusha** [comment]
@mcz-adhamsabry 
Try to remove the chectl from `~/.local/share/chectl` folder as well

**Comment by tolusha** [comment]
@mcz-adhamsabry
Feel free to open you have any questions.
