### ISSUE TITLE
docs: remove PostgreSQL from the "Che architecture"

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23111]
### Is your task related to a problem? Please describe

Postgres was removed in 2023 - https://che.eclipseprojects.io/2023/03/20/@ilya.buziuk-decommissioning-postgresql-database.html
However, we never updated docs :/

https://eclipse.dev/che/docs/stable/administration-guide/server-components/

### Describe the solution you'd like

remove PostgresSQL images / mentions from https://eclipse.dev/che/docs/stable/administration-guide/server-components/

**Comment by ibuziuk** [comment]
@svor @deerskindoll please prioritize for the next sprint

**Comment by deerskindoll** [comment]
I searched the docs and this seems to be the only mention of postgresql: https://eclipse.dev/che/docs/stable/administration-guide/calculating-che-resource-requirements/

**Comment by deerskindoll** [comment]
@svor the only references I could find are in the following doc: https://eclipse.dev/che/docs/stable/administration-guide/calculating-che-resource-requirements/

do you want me to simply remove the references or is there anything else I need to do?

**Comment by deerskindoll** [comment]
done! can I close the issue?

**Comment by svor** [comment]
@deerskindoll 
I don't see any information about PostgreSQL in the doc, feel free to close it!
