### ISSUE TITLE
418 I'm a teapot Error on Workspace Access after Redirection

### ISSUE THREAD

**Issue by damonlee** [eclipse/che#23133]
### Describe the bug

# Title: 418 I'm a teapot Error on Workspace Access after Redirection

## Content:

I have successfully deployed Eclipse Che on Azure AKS with HTTPS enabled. However, I am encountering an issue when trying to access a workspace via its URL (e.g., https://testbed.pro/empty-pawj/3100/). Clicking the "Open" button on https://testbed.pro/dashboard redirects to the workspace URL, but results in a 418 I'm a teapot error and fails to load the webpage. **However, after starting the created workspace and setting up port forwarding, the IDE runs correctly in the web browser.**

```
upstream prematurely closed connection while reading response header from upstream
```

I have checked the following:

* **Workspace Pod:** The Workspace Pod is running and accessible via port-forwarding.

I'm not sure what else to check. Any help would be appreciated.

**Additional information:**

* **Azure Kubenetes Service**
* **Azure Active Directory(Entra ID)**
* **Che version:** 7.91.0
* **Kubernetes version:** Client Version: v1.30.2  , Server Version: v1.30.3
* #### Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
* **Ingress controller:** Nginx

Please let me know if you need any further information. 

![image](https://github.com/user-attachments/assets/5062b0d6-bff8-4292-8a1a-3a11b0e42de1)

![image](https://github.com/user-attachments/assets/c95450a0-132f-41c7-8684-c06322257f63)

![image](https://github.com/user-attachments/assets/e9bc899d-8ece-440d-8f65-3e386eb20c4a)

![image](https://github.com/user-attachments/assets/5022d9cb-e4e9-4b46-ad72-92fe81cd0349)

### Che version

7.91@latest

### Steps to reproduce

1. https://testebed.pro
2. Azure AD Auth
3. https://testebed.pro/dashboard
4. workspace create
5. workspace start
6. workspace open
7.  https://testbed.pro/empty-pawj/3100/
8. code 418

### Expected behavior

IDE Open

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Azure

### Additional context

[all.txt](https://github.com/user-attachments/files/16903043/all.txt)

**Comment by akurinnoy** [comment]
@tolusha Can you take a look?

**Comment by inswave-damon** [comment]
Issue Status: Resolved after version update


While the exact cause of the issue is still unknown, the problem appears to have been resolved after updating to the latest version. I have tested the new version, and the bug no longer occurs. If more investigation is needed to pinpoint the root cause, please feel free to reach out. Thank you for your attention.
