### ISSUE TITLE
Add images used in internal samples as RELATED_IMAGES variables into the che-operator container

### ISSUE THREAD

**Issue by svor** [eclipse/che#23149]
### Is your task related to a problem? Please describe

Currently it's hard to collect all related images that should be pre-pull

### Describe the solution you'd like

All images that used in editors' definitions and internal samples' devfiles should be added as environment variables into the operator container to pre-pull them.

Currently we only have env variables that describe related images used in editors:  `RELATED_IMAGE_editor_definition_che_code_latest_che_code_runtime_description=registry.redhat.io/devspaces/udi-rhel8@sha256:9199796c9dd82a16ebb2c4ff8d06b9727f392eb93eb7ffa2974ad6c16e3d8e5d`

Need similar variables for images used in samples:
`RELATED_IMAGE_sample_devfile_ansible_devspaces_demo=ghcr.io/ansible/ansible-workspace-env-reference@sha256:03d7f0fe6caaae62ff2266906b63d67ebd9cf6e4a056c7c0a0c1320e6cfbebce`

**Comment by tolusha** [comment]
To find out the list of samples:
http://che-dashboard.eclipse-che.svc:8080/dashboard/api/airgap-sample

To find out the list of editors:
http://che-dashboard.eclipse-che.svc.cluster.local:8080/dashboard/api/editors

**Comment by ibuziuk** [comment]
@tolusha is it documented by any chance?

**Comment by tolusha** [comment]
Operators should:
1. reads the list of samples and editors from the dashboard using internal urls, parse and grab images.
2. uses those images to configure imagepuller operator
3. store them in `/tmp/external_images.txt` file 
4. document how to read that file by admin

**Comment by ibuziuk** [comment]
@tolusha looks like there is some mismatch with images based on:

```
sh-5.1# env | grep ^RELATED_IMAGE_editor_definition_
RELATED_IMAGE_editor_definition_che_idea_latest_idea_rhel8_injector=registry.redhat.io/devspaces/idea-rhel8@sha256:0286c708c10dc4740f3e7c70f79b7c6976d63e069ee4a4380004bdbe77ff7e05
RELATED_IMAGE_editor_definition_che_code_latest_che_code_injector=registry.redhat.io/devspaces/code-rhel8@sha256:007bc86b63ddc948be828536bc0a6b7dbaeee3d272287f62f2336009e7b9c6a0
RELATED_IMAGE_editor_definition_che_code_latest_che_code_runtime_description=registry.redhat.io/devspaces/udi-rhel8@sha256:9199796c9dd82a16ebb2c4ff8d06b9727f392eb93eb7ffa2974ad6c16e3d8e5d
RELATED_IMAGE_editor_definition_che_idea_latest_idea_rhel8=registry.redhat.io/devspaces/udi-rhel8@sha256:9199796c9dd82a16ebb2c4ff8d06b9727f392eb93eb7ffa2974ad6c16e3d8e5d
```

last idea image point to UDI for some reason

**Comment by ibuziuk** [comment]
N.B. `api/airgap-sample` does not provide the image information

**Comment by tolusha** [comment]
That's because upstream doesn't have any samples
