### ISSUE TITLE
Update smoke test pull request check due to dashboard improvements

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#23140]
### Describe the bug

A new popup has been added to the dashboard that blocks the normal execution of smoke tests

![selection_008](https://github.com/user-attachments/assets/49f64171-d758-4e42-ab0e-901ac865a608)

It needs to update the smoke test due to changes and rebuild corresponding docker image.

Original run https://github.com/che-incubator/che-code/actions/runs/10808194144?pr=413

### Che version

next (development version)

### Steps to reproduce

Create any pull request to che-code and check for Smoke Test pull request check

### Expected behavior

Check should be passed

**Comment by musienko-maxim** [comment]
It seems the problem has been fixed on the Dashboard side: https://github.com/che-incubator/che-code/actions/runs/11216559312/job/31176114515?pr=420.
