### ISSUE TITLE
Filter out "init-ssh-agent" from Che Code's Devfile task lists

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#23144]
### Describe the bug

We recently added support in DWO for having the ssh-agent initialized as a postStart event, allowing users to have their ssh passphrase automatically inputed when performing git operations in their workspace terminals, see https://github.com/devfile/devworkspace-operator/issues/1295

However, a side effect of this postStart event (which includes a DevWorkspace command) is that the command is shown in the editor. We should filter out this command from the editor, similar to what was done for https://github.com/eclipse-che/che/issues/22098.

### Che version

7.91@latest

### Steps to reproduce

1. Create a workspace on a Che install that's using DWO nightly (e.g. the Che Dogfooding cluster). For my testing, I created a workspace from the Che Dashboard
2. Open the list of tasks in CheCode: Terminal -> Run Task...
3. See that there's a task shown called `init-ssh-agent` even though this task/command is not defined in the devfile:

### Expected behavior

The init-ssh-agent command/task should not be shown as a devfile command IMO as it's confusing to users as to where it's coming from.

### Runtime

OpenShift

### Screenshots

![image](https://github.com/user-attachments/assets/969207ec-c5a7-43f9-9339-7331f2c40705)

### Installation method

OperatorHub

### Environment

Linux

### Additional context

The command has the [hard-coded id](https://github.com/devfile/devworkspace-operator/pull/1307/files#diff-36043890c52c8201a8bc84238c219be45ce07bf172d89f693c7c54ffe70d046eR48) of `init-ssh-agent`. You can check this postStart command by checking the flattened devfile in your workspace:
![image](https://github.com/user-attachments/assets/43ad3ae7-6d66-41a7-979b-50524e660903)

**Comment by RomanNikitenko** [comment]
@AObuchow @dkwon17 
so, if I understand correctly, the suggestion is - exclude the command from the devfile task list using hard-coded id.
correct?

**Comment by AObuchow** [comment]
> @AObuchow @dkwon17 so, if I understand correctly, the suggestion is - exclude the command from the devfile task list using hard-coded id. correct?

@RomanNikitenko Correct :) I think this would be the simplest approach to resolving this issue.

**Comment by dkwon17** [comment]
With this PR: https://github.com/devfile/devworkspace-operator/pull/1329, the command ids are now: `init-ssh-agent-1`, `init-ssh-agent-2`, ..., etc.

Please see: https://github.com/devfile/devworkspace-operator/pull/1329/files#r1809335501

**Comment by AObuchow** [comment]
> With this PR: [devfile/devworkspace-operator#1329](https://github.com/devfile/devworkspace-operator/pull/1329), the command ids are now: `init-ssh-agent-command-1`, `init-ssh-agent-command-2`, ..., etc.
> 
> Please see: https://github.com/devfile/devworkspace-operator/pull/1329/files#r1809335501

@RomanNikitenko With these changes, maybe a regex should be used to determine which events should be filtered out? Alternatively, you can determine the number of `init-ssh-agent-command-x` commands by counting the number of container components in a devworkspace, and then building the list of commands to filter out.

**Comment by RomanNikitenko** [comment]
@AObuchow @dkwon17 
I created PR to fix current issue: https://github.com/che-incubator/che-code/pull/445
Currently it uses a regex to filter out `init-ssh-agent-command-x` commands.
I think the next time we have a similar need - we could consider adding an attribute for commands that should not be displayed on the UI.
This way we could avoid hard-coded ids and provide more flexible and clear approach.
wdyt?

**Comment by AObuchow** [comment]
> I think the next time we have a similar need - we could consider adding an attribute for commands that should not be displayed on the UI. This way we could avoid hard-coded ids and provide more flexible and clear approach. wdyt?

I think this is a great idea, the command attribute could be something like `controller.devfile.io/internal-command: true`. I've opened https://github.com/devfile/devworkspace-operator/issues/1333
