### ISSUE TITLE
Eclipse Che failed to open workspace from factory on airgap OCP cluster: "The workspace has not received an IDE URL in the last 20 seconds. Try to re-open the workspace."

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#23166]
### Describe the bug

Eclipse Che failed to open workspace from factory on airgap OCP cluster: "The workspace has not received an IDE URL in the last 20 seconds. Try to re-open the workspace.":
![screenshot-Wait_workspace_readiness (20)](https://github.com/user-attachments/assets/2bbf6dee-e64d-463b-8685-400ef4aa9daa)

Workspace had later started successfully in a background.
It was possible to enter workspace if close start workspace page and then open workspace from the RECENT WORKSPACES panel:
![Screenshot from 2024-09-30 20-01-58](https://github.com/user-attachments/assets/eca4e7d7-77f2-41ea-bc99-d54307576134)

### Che version

next (development version)

### Steps to reproduce

1. Install Eclipse Che to arigap OCP cluster.
2. Configure Eclipse Che to work on arigap OCP cluster.
3. Go to Dashboard and create workspace from factory https://github.com/che-incubator/quarkus-api-example/raw/main/devfile.yaml

### Expected behavior

Workspace started successful.

### Runtime

OpenShift

### Screenshots

![screenshot-Wait_workspace_readiness (20)](https://github.com/user-attachments/assets/2bbf6dee-e64d-463b-8685-400ef4aa9daa)

![Screenshot from 2024-09-30 19-48-20](https://github.com/user-attachments/assets/ff4b1559-9544-4ab7-a188-f8238f652007)

![Screenshot from 2024-09-30 19-47-24](https://github.com/user-attachments/assets/b0a1d479-a365-48c6-8bd3-1a756d8d2d03)

### Installation method

chectl/next

### Environment

Linux

### Additional context

Browser logs:

> "SEVERE" "" "https://eclipse-che.apps.abazko-disconnected.devcluster.openshift.com/dashboard/ - Failed to load resource: the server responded with a status of 403 (Forbidden)"
"SEVERE" "" "https://eclipse-che.apps.abazko-disconnected.devcluster.openshift.com/favicon.ico - Failed to load resource: the server responded with a status of 403 (Forbidden)"
"SEVERE" "" "https://oauth-openshift.apps.abazko-disconnected.devcluster.openshift.com/favicon.ico - Failed to load resource: the server responded with a status of 403 (Forbidden)"
"WARNING" "" "https://eclipse-che.apps.abazko-disconnected.devcluster.openshift.com/dashboard/client.6e5c7181.js 0:332873 "No custom editor found""
"SEVERE" "" "https://eclipse-che.apps.abazko-disconnected.devcluster.openshift.com/api/factory/token/refresh?url=http://ec2-18-217-70-183.us-east-2.compute.amazonaws.com:10023/che-incubator/quarkus-api-example.git - Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

Here is [the har file from the test run](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Che/job/ocp/job/basic/job/run-typescript-tests-on-ocp/362/artifact/e2e-report/The_SmokeTest_userstory__Create_workspace_from_factory-http-++ec2-18-217-70-183.us-east-2.compute.amazonaws.com-10023+che-incubator+quarkus-api-example+raw+main+devfile.yaml_Wait_workspace_readiness/har-Wait_workspace_readiness.har/*view*/
)

Link to the test run: https://red.ht/3zAmbHW

**Comment by dmytro-ndp** [comment]
This issue duplicates https://github.com/eclipse-che/che/issues/23166

**Comment by erkerb4** [comment]
@dmytro-ndp , Can you double-check the issue that's duplicating? The duplication issue points to this (_same_) issue. We just upgraded to 7.91.0, and we are seeing this exact behavior.

**Comment by dmytro-ndp** [comment]
@erkerb4 : sorry, my fault

Correct duplicating issue link: https://github.com/eclipse-che/che/issues/23159

The fix of the issue had been merged into the Eclipse Che 7.92.x a few days ago: https://github.com/eclipse-che/che-dashboard/commit/2b0fd23af29dfb737eb6981b6b2d4f00e4d55ee3
