### ISSUE TITLE
Remove lerna from Che Dashboard

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse/che#23164]
### Is your task related to a problem? Please describe

it appears that we can remove Lerna library from Che Dashboard, to avoid maintenance work, that could be related with this library (like potentially having to update to Lerna 8)

### Describe the solution you'd like

commands in package.json and other scripts that feature `lerna` should be rewritten

### Describe alternatives you've considered

keep lerna

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy please, reivew

**Comment by RomanNikitenko** [comment]
@mkuznyetsov 
please take a look at https://github.com/eclipse-che/che-dashboard/pull/1229

should we close this issue?
