### ISSUE TITLE
Dashboard should show an editor's tags

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#23161]
### Is your enhancement related to a problem? Please describe

Che Dashboard displays tags read from an editor's definitions. See `Tech Preview` on the following screenshot:

![image](https://github.com/user-attachments/assets/34da5714-aa3f-45e1-8b55-e8bf97136327)

The problem is that the tags are not displayed for some editors.
It looks like the Dashboard shows tags for the editors read from the [plugin-registry](https://github.com/eclipse-che/che-plugin-registry/blob/a296330b8e6d306d3fc0b99edb0c3adff9269a40/che-editors.yaml#L10), but it doesn't for ones contributed through the [che-operator](https://github.com/eclipse-che/che-operator/blob/6164f7b76f9b002a900f6225ccbf0a342508982a/editors-definitions/che-pycharm-server-latest.yaml#L18).

### Describe the solution you'd like

Che Dashboard should display tags for the editor definitions contributed through the che-operator the same way it does for those contributed through the plugin-registry.

**Comment by svor** [comment]
Currently, all editors are contributed solely by the che-operator

**Comment by ibuziuk** [comment]
@akurinnoy @olexii4 could you please take a look. Added as Unplanned to the current sprint
