### ISSUE TITLE
Deploy specific workspace on specific node

### ISSUE THREAD

**Issue by huonguyenlt** [eclipse/che#23165]
### Summary

I know that we can use nodeSelector to deploy workspaces on specific nodes. However, I need the ability to deploy different workspaces on different nodes. I need a workspace that runs dotnet framework which only works on windows container. So, beside linux node, I also need a windows node to host that workspace. Not sure there is any way to achieve this?

**Comment by tolusha** [comment]
I think you can add nodeselector for a pod directly into a devfile using pod override feature [1]

[1] https://devfile.io/docs/2.3.0/overriding-pod-and-container-attributes
