### ISSUE TITLE
As a user I want to be notified when starting a CDE with Gateway editor that downloading IDE binaries could take a few minutes

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23170]
### Is your enhancement related to a problem? Please describe

Currently, a user has no clue why CDE based on Gateway editors started for a long time:
 
<img width="1242" alt="Screenshot 2024-09-30 at 17 37 21" src="https://github.com/user-attachments/assets/e51b9b83-9a2e-4f7b-b930-69bea7c99e2e">

Users can only get some meaningful info from the code-injector container

<img width="1242" alt="Screenshot 2024-09-30 at 17 37 37" src="https://github.com/user-attachments/assets/184ccde4-8a43-4624-a004-3e4e86edb95b">

### Describe the solution you'd like

As a user I want to be notified when starting a CDE with Gateway editor that downloading binaries could take a few minutes:

- On the startup screen we should show the extra step: Downloading IDE binaries... (it can take a few minutes depending on your internet connection)
Ideally with a progress bar

### Describe alternatives you've considered

N/A

### Additional context

code-injector logs can be more verbose as well

**Comment by azatsarynnyy** [comment]
I created the issue https://github.com/eclipse-che/che/issues/23173 for more verbose container output while downloading the IDE binaries
