### ISSUE TITLE
Add the "Deprecated" Tag to the Intelij IDEA Community

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23172]
Intelij IDEA Community is deprecated in favour of Gateway / desktop. Need to add the 'Deprecated'  tag to the editor definition and 
display it correctly on the user dashboard:

<img width="455" alt="Screenshot 2024-10-01 at 12 10 51" src="https://github.com/user-attachments/assets/40736b53-c5d4-4296-8d88-45152a88438a">

**Comment by ibuziuk** [comment]
@tolusha @olexii4 @akurinnoy please, review. Not sure if we need changes for the Dashboard as well:
- https://github.com/eclipse-che/che-operator/pull/1910
- https://github.com/eclipse-che/che-operator/pull/1911

**Comment by azatsarynnyy** [comment]
[From the source code](https://github.com/eclipse-che/che-dashboard/blob/5c42201658e5ac0f1b74e18852fa066b1af01dd9/packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx#L153-L155), I see that the suggested PRs will not work as expected.
It looks like the Dashboard doesn't show the editor's tag as it's defined in the yaml definition. But it detects the `Tech Preview` tag only.

**Comment by ibuziuk** [comment]
@azatsarynnyy right, we discussed it briefly today with @olexii4 @akurinnoy, and changes on UD are expected. Also, it would be nice if we put the `Deprecated` editors last in the list
