### ISSUE TITLE
Poor podman performance on universal developer image (UBI/UDI)

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#23180]
### Summary

Recently I've been having trouble building a container with `podman`. 
I'm wondering if there are any known issues regarding this. 

In the attached images the build process takes more than 40 minutes and counting. 

The Dockerfile is simple

```
FROM registry.access.redhat.com/ubi8/python-311@sha256:c98f01c776a3fc42e171062de485c8fb2c99d45cd1488778d6fcfda921105720

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```

![image](https://github.com/user-attachments/assets/e5c57619-05ea-4834-b503-7a66644bea4b)

![image](https://github.com/user-attachments/assets/d4713f3f-f60e-4022-80a9-bd166ead8048)

### Relevant information

I have 2 DevSpaces instances running on different versions of OpenShift and it is the same behavior on both. 

Instance 1
```
OpenShift 4.15.18
Red Hat OpenShift Dev Spaces 3.16.0 
```

Instance 2 
```
OpenShift 4.13.4
Red Hat OpenShift Dev Spaces 3.16.1
```

I have also run my tests with the universal developer image UBI/UDI
```
UBI: quay.io/devfile/universal-developer-image:ubi8-latest
UDI: registry.redhat.io/devspaces/udi-rhel8:latest
```

**Comment by adnanalawiyat** [comment]
is `fuse-overlay` enabled ? https://eclipse.dev/che/docs/stable/end-user-guide/using-the-fuse-overlay-storage-driver/

**Comment by jorgeadrian93** [comment]
I didn't have it activated, thank you.
