### ISSUE TITLE
Apply CSS to the Gateway startup page

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23189]
Currently, the page looks pretty minimalistic:

<img width="1227" alt="Screenshot 2024-10-09 at 14 00 26" src="https://github.com/user-attachments/assets/e012790c-7bdf-479a-a549-c1a0650a906a">

We need to apply some nice styles / fonts for it to make it more production-ready feature + improve UX

**Comment by azatsarynnyy** [comment]
Before:

![image](https://github.com/user-attachments/assets/45b51d98-89b0-457d-8924-4c9c42a70968)

---

After:

![image](https://github.com/user-attachments/assets/16d994a8-64ee-494d-b677-0cc1aad1492e)
