### ISSUE TITLE
Error installing Che with chectl: ignoredUnrecoverableEvents in body must be of type array: "null"

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#23185]
### Describe the bug

Trying to install Che with chectl next does not work on Minikube. 

### Che version

7.92@latest

### Steps to reproduce

1. Start a minikube cluster:
```
$ minikube start --addons=ingress,dashboard --vm=true --memory=10240 --cpus=4 --disk-size=50GB --kubernetes-version=v1.23.9
```
2. Install che with chectl next channel:
```
$ chectl version
chectl/0.0.20240910-next.ed3a4c8 linux-x64 node-v18.18.0

$ chectl server:deploy -p minikube
```
3. There is an error:
```
    ✔ Create Deployment che-operator...[Created]
    ✔ Eclipse Che Operator pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Create ValidatingWebhookConfiguration org.eclipse.che...[Created]
    ✔ Create MutatingWebhookConfiguration org.eclipse.che...[Created]
    ✖ Create CheCluster Custom Resource
      → CheCluster.org.eclipse.che "eclipse-che" is invalid: spec.devEnvironments.ignoredUnrecoverableEvents: Invalid value: "null": spec.devEnvironments.ignoredUnrecoverableEvents in body must be of type array: "null"
```

### Expected behavior

Che should be installed

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

**Comment by AObuchow** [comment]
@dkwon17 I wonder if something odd happened with https://github.com/eclipse-che/che-operator/pull/1897/files#diff-10f5235ef9752eb68e9938878907ee064b366dd04540ac315d0b8912860a38dcR208 ?

I'm using `chectl/0.0.20240919-next.9c29dbd linux-x64 node-v18.18.0` and haven't encountered this bug. The version you're using seems a bit older.

I wonder if the version of chectl you're using is not providing a value for the `ignoredUnrecoverableEvents` when creating the Che Cluster CR and this is causing the CRD validation to fail?

**Comment by dkwon17** [comment]
I'm not able to reproduce the issue with `chectl/0.0.20240919-next.9c29dbd linux-x64 node-v18.18.0`
