### ISSUE TITLE
Upgrade or remove Lerna build system from the dashboard

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#23198]
### Is your enhancement related to a problem? Please describe

 The dashboard is using an old version of **Lerna** `"lerna": "^6"`.
 https://github.com/eclipse-che/che-dashboard/blob/main/package.json#L43

### Describe the solution you'd like

 The **lerna** package needs to be upgraded to the latest major versions.

### Describe alternatives you've considered

 The **lerna** package needs to be removed from the dashboard.

**Comment by RomanNikitenko** [comment]
related issue https://github.com/eclipse-che/che/issues/23164
