### ISSUE TITLE
Installation guide on EKS

### ISSUE THREAD

**Issue by soumbouy** [eclipse/che#23209]
### Summary

Hi , 
Would you have a guideline for an installation on AWS EKS ?

**Comment by ibuziuk** [comment]
Hello, thank you for your interest in Eclipse Che
Currently, we only have community-supported docs for AKS - https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-microsoft-azure/ based on the blog post https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html contributed by @karatkep

We are looking forward to having more contributions (blogs / docs) from the community with their success stories on running Eclipse Che on different flavors of k8s.

**Comment by tolusha** [comment]
We are looking for contribution for our documentation.
Probably @huonguyenlt can help you.
