### ISSUE TITLE
 [dev sandbox] Cannot push to a github branch: permission denied

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#23212]
### Describe the bug

I permanently face issues with pushing to my branch in che-code repository.
At the same time there is no problems with pushing to the branch from the dogfooding cluster.

When I forked che-code and then crate a workspace from a fork, everything is fine.
The issue appear only on the developer sandbox when pushing to a branch in che-code* repository.

\* in fact, not only to che-code repository

### Che version

7.93@latest

### Steps to reproduce

I'm not sure it is reproducible for other accounts.

1. Create a workspace using https://github.com/che-incubator/che-code
2. Create a branch, do some changes, commit and push

### Expected behavior

A branch should be pushed.

### Runtime

OpenShift

### Screenshots

![Screenshot from 2024-10-29 13-29-52](https://github.com/user-attachments/assets/c5358e21-bdfb-4eeb-9e6e-d21a290fd896)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by ibuziuk** [comment]
@vitaliy-guliy have you granted the permissions to the che-incubator organization:
<img width="614" alt="Screenshot 2024-10-31 at 15 44 33" src="https://github.com/user-attachments/assets/33f0c679-fa27-44f9-b4a3-5c1cbc0561d8">

**Comment by vitaliy-guliy** [comment]
@ibuziuk I've requested access to `che-incubator` for `Red Hat OpenShift Dev Spaces (Developer Sandbox)` and waiting for the response.
I will comment here once my request is granted.

**Comment by vitaliy-guliy** [comment]
Everything's fine, after getting the permissions I can easily commit and push to che-code repository by clicking a button.
