### ISSUE TITLE
Kubeconfig Format Corruption After Switching Clusters and Restarting Workspace

### ISSUE THREAD

**Issue by eye0fra** [eclipse/che#23238]
### Describe the bug

Hello,
I've encountered an issue with Kubernetes context renewal/injection. Initially, the kubeconfig is in JSON format. However, when I use the oc command line to log into a different cluster for testing, the format switches to YAML.
Upon restarting the workspace, the injection process disrupts the YAML file, causing it to become a single inline entry. Consequently, the kubeconfig becomes unusable, affecting all related dependencies, such as kubedock.
The current workaround is to delete the kubeconfig and restart the workspace to restore the correct kubeconfig format.

### Che version

7.94@latest

### Steps to reproduce

1. **Initial Setup:**
   - Ensure you have a kubeconfing in JSON format at the start of the workspaces
   - Verify that your workspace is configured to use this `kubeconfig`. (kubedock is working)

2. **Switch Cluster:**
   - Use the `oc` command line tool to log into a different OpenShift cluster:
     ```bash
     oc login <cluster-url> --token=<your-token>
     ```
   - Note that the `kubeconfig` format changes to YAML.
   - I believe is not necessary to use a different cluster, but run oc login command to override the config.

3. **Restart Workspace:**
   - Restart your development workspace.

4. **Observe the Issue:**
   - Check the `kubeconfig` file. It should now be a single inline YAML entry.
   - Attempt to use Kubernetes-related commands or dependencies like `kubedock` and observe failures due to the malformed `kubeconfig`.

5. **Workaround:**
   - Delete the kubeconfig.
   - Restart the workspace to restore the correct `kubeconfig` format.

### Expected behavior

The kubeconfig should maintain its format and functionality after switching context.

### Runtime

OpenShift

### Screenshots

<img width="816" alt="Screenshot 2024-11-07 at 11 36 35" src="https://github.com/user-attachments/assets/bfd42e68-86a2-405f-aeff-8f4696fa39c2">
<img width="924" alt="Screenshot 2024-11-07 at 10 21 35" src="https://github.com/user-attachments/assets/b9eb94eb-94c5-420b-afa0-3fee814d28d8">
<img width="1642" alt="Screenshot 2024-11-06 at 17 01 43" src="https://github.com/user-attachments/assets/03af5467-6bb2-41d6-884a-0d03d5e95bbd">
<img width="704" alt="Screenshot 2024-11-06 at 16 59 55" src="https://github.com/user-attachments/assets/f0d511dd-885d-42ee-bcc4-c2a0ccb89ec1">

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

OpenShift DevSpaces 3.16.1

**Comment by vinokurig** [comment]
Hello @eye0fra, could you please elaborate more on:
* workspace you started, can you provide the devfile you used?
* `Verify that your workspace is configured to use this kubeconfig. (kubedock is working)`, could you please provide some description related to kubedoc.
* Where did you launch the `oc whoami` command? was your local machine terminal, or workspace pod's terminal?
Currently I was able to reproduce the case where the config file changes from JSON to YAML in the workspace dev container terminal, but that did not affect the oc commands.

**Comment by eye0fra** [comment]
1. The workspace can be empty and is not dependent on the devfile definition.
2. If the kubedock process is running without errors, it indicates that the kube config file is intact and not corrupted.
3. What do you mean "my local machine," all the tests are on the workspace terminal. If you can execute the command afterwards, is the YAML formatted correctly? Based on the attached picture, I have doubts about its functionality.

**Comment by vinokurig** [comment]
@eye0fra According to the error this is a formatting issue, can you provide the content of the `/home/.kube/config` file after the new `oc login`. You can hide the sensitive data with `***`.

**Comment by vinokurig** [comment]
@eye0fra Could you please provide the cluster's kubernetes version as well.

**Comment by eye0fra** [comment]
> @eye0fra According to the error this is a formatting issue, can you provide the content of the `/home/.kube/config` file after the new `oc login`. You can hide the sensitive data with `***`.

It is yaml.

![image](https://github.com/user-attachments/assets/8ccb1b64-4fd9-4999-9efe-84d50f4a630a)

**Comment by eye0fra** [comment]
> @eye0fra Could you please provide the cluster's kubernetes version as well.

`Kubernetes Version: v1.29.7+4510e9c`

**Comment by vinokurig** [comment]
@eye0fra Thank you for the response, but can you paste the real content of the kubeconfig file as a raw text. We might miss some formatting cases if we parse the image.

**Comment by ibuziuk** [comment]
@eye0fra sorry, I'm a bit late with follow up, but please clarify if you can reproduce the bug on workspaces.openshift.com?

**Comment by eye0fra** [comment]
1. Injected by DevSpaces
```json
{
  "apiVersion": "v1",
  "kind": "Config",
  "clusters": [
    {
      "name": "inCluster",
      "cluster": {
        "server": "https://100.65.0.1:443",
        "certificate-authority": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
        "insecure-skip-tls-verify": false
      }
    }
  ],
  "users": [
    {
      "name": "developer",
      "user": {
        "token": "sha256~xxxxx"
      }
    }
  ],
  "contexts": [
    {
      "name": "logged-user",
      "context": {
        "user": "developer",
        "cluster": "inCluster",
        "name": "logged-user",
        "namespace": "xxxxxxxx"
      }
    }
  ],
  "preferences": {},
  "current-context": "logged-user"
}
```

2. oc login to another cluster

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://xxx:6443
  name: xxx:6443
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://100.65.0.1:443
  name: inCluster
contexts:
- context:
    cluster: xxx/xxx:6443
    namespace: xxx-d
    user: xxx:6443
  name: xxx:6443/xxx
- context:
    cluster: inCluster
    namespace: xxx-devspaces-d
    user: developer
  name: logged-user
current-context: xxx/xxx:6443/xxx
kind: Config
preferences: {}
users:
- name: xxx/xxx:6443
  user:
    token: sha256~xxx
- name: developer
  user:
    token: sha256~xxx

```

3. Workspace Restart

```yaml
apiVersion: v1 clusters: - cluster:     server: https://xxx:6443   name: xxx:6443 - cluster:     certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt     server: https://100.65.0.1:443   name: inCluster contexts: - context:     cluster: xxx/xxx:6443     namespace: xxx-d     user: xxx/xxx:6443   name: xxx/xxx:6443/xxx - context:     cluster: inCluster     namespace: xxx-devspaces-d     user: developer   name: logged-user current-context: xxx/xxx:6443/xxxx kind: Config preferences: {} users: - name: xxx/xxx:6443   user:     token: sha256~xxxx - name: developer   user:     token: sha256~xxx
```

**Comment by eye0fra** [comment]
looks ok in workspaces.openshift.com

**Comment by eye0fra** [comment]
The `workspaces.openshift.com` does not have persistentHome enabled, so to simulate the persistent of the home, I attached a volume on the `/home/user`, and yes it has the same issue.

**Comment by vinokurig** [comment]
I managed to reproduce the issue by applying the [Persistent user home](https://eclipse.dev/che/docs/stable/administration-guide/about-persistent-user-home/) option. After workspace restart the kube config file content formatting breaks.
