### ISSUE TITLE
Extensions are no available for installation when I use dogfooding instance

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23239]
### Describe the bug

There is an empty list of extensions when I use dogfooding instance for development.

### Che version

7.94@latest

### Steps to reproduce

1. Create a workspace on the dogfooding instance.
2. Go to the `Extensions` panel
3. Check list of extensions that available for installation.

### Expected behavior

`Extensions` panel is not empty and contains extensions for installation.

### Screenshots

<img width="1158" alt="Screenshot 2024-11-08 at 10 30 11" src="https://github.com/user-attachments/assets/0ef987bd-c002-41af-972e-c8c10aec40a0">

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/c8c56e38-c210-4e38-b41e-8a9f0d519112">

### Environment

I faced the problem on the dogfooding instance

**Comment by ibuziuk** [comment]
switched dogfooding back to `https://open-vsx.org` for now:
```
 pluginRegistry:
      openVSXURL: "https://open-vsx.org" 
```

**Comment by svor** [comment]
it happens again, all pods were recreated on Nov 17, 2024, resulting in the loss of all previously published extensions.

**Comment by svor** [comment]
I've updated the OpenShift template by adding two PVCs for postgres db and local extensions storage, also I've changed the imagePullPolicy to ifNotPresent: https://github.com/eclipse/openvsx/pull/1011/commits/43a9b33715e77de496660906c63953892f99ee11. 
For now I'm going to close the issue and will monitor the state of the self hosted registry on the dogfooding instance
