### ISSUE TITLE
Workspace not able to start due to websocket issue

### ISSUE THREAD

**Issue by danieleh11** [eclipse/che#23275]
### Summary

Im facing this issue on my workspace that its failing to start, still did not get a fix for it.
when the workspace starts on my ide browser i get a message:

Could not establish a websocket connection. The application will be using the HTTP fallback mode. This may affect performance and the behavior of some features.

I tried to run the application with no proxy / with proxy. but still not able to get the workspace up with my git repository code.
its running on kubernetes in AWS environment.

Any suggestions?

**Comment by ibuziuk** [comment]
@danieleh11 hello, could you please clarify how you installed Eclipse Che?

**Comment by ibuziuk** [comment]
also, when the workspace is started could you execute `oc get dw` command and provide the output 
relevant docs - https://eclipse.dev/che/docs/stable/end-user-guide/managing-workspaces-with-apis/

**Comment by danieleh11** [comment]
We can close this as the issue was on the certificate. 
was missing the intermediate part of it.
