### ISSUE TITLE
unable to run in mac

### ISSUE THREAD

**Issue by mcheung63** [eclipse/che#5982]
unable to run in mac

**Reproduction Steps:**

<img width="954" alt="2017-08-13 11 19 36" src="https://user-images.githubusercontent.com/1779905/29250917-e7864cae-807d-11e7-8632-6734aa51bfbb.png">

**OS and version:**    

/Users/peter>uname -a
Darwin PeteriMac.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Diagnostics:** 

/Users/peter>docker --version
Docker version 17.06.0-ce, build 02c1d87

**Comment by TylerJewell** [comment]
Product worked perfectly ... see the "Mount syntax" - it tells you what to type.
